[it] localizzazione termine distributed-system
cncf/glossary pull request #1002
Opened 2022-06-27 08:36 UTC by ugho16

Signed-off-by: Paolo [81316809+ugho16@users.noreply.github.com](mailto:81316809+ugho16@users.noreply.github.com)

2022-07-05 15:51 UTC, ugho16 commented on content/it/distributed_system.md
> +Tradizionalmente i sistemi scalerebbero verticalmente, cioè si aggiunge più CPU o memoria a una singola macchina. Scalare verticalmente è un processo lungo, richiede dei momenti di down e raggiunge v
```suggestion
Tradizionalmente i sistemi verrebbero scalati verticalmente, cioè aggiungendo più CPU o memoria a una singola macchina. La scalabilità verticale è un processo lungo, richiede dei momenti di down e raggiunge velocemente i suoi limiti.
```

2022-07-05 15:51 UTC, ugho16 commented on content/it/distributed_system.md
> +I sistemi distribuiti permettono di scalare orizzontalmente, cioè di aggiungere altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consentendo a un sistema di gestir
```suggestion
I sistemi distribuiti possono essere scalati orizzontalmente, cioè aggiungendo altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consentendo a un sistema di gestire un improvviso aumento di carico di lavoro o di consumo di risorse.
```

2022-07-05 15:55 UTC, ugho16 commented on content/it/distributed_system.md
> +Un sistema non distribuito è esposto al rischio di fallire, perché se una macchina si blocca il sistema intero si blocca. Un sistema distribuito può essere progettato in modo da continuare a funziona
```suggestion
Un sistema non distribuito è esposto al rischio di fallimento: se un computer si blocca, si ferma il sistema intero. Un sistema distribuito può essere progettato in modo da continuare a funzionare e produrre il medesimo risultato anche se alcuni computer si bloccano.
```

2022-07-15 19:48 UTC, fsbaraglia requested changes

2022-07-15 19:48 UTC, fsbaraglia commented on content/it/distributed_system.md
> +Tradizionalmente i sistemi verrebbero scalati verticalmente, cioè aggiungendo più CPU o memoria a una singola macchina. La scalabilità verticale è un processo lungo, richiede dei momenti di down e ra
```suggestion
Tradizionalmente i sistemi verrebbero [scalati](/it/scalability/) verticalmente, cioè aggiungendo più CPU o memoria a una singola macchina. La scalabilità verticale è un processo lungo, richiede dei momenti di down e raggiunge velocemente i suoi limiti.
```

2022-07-15 19:48 UTC, fsbaraglia commented on content/it/distributed_system.md
> +I sistemi distribuiti possono essere scalati orizzontalmente, cioè aggiungendo altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consentendo a un sistema di gestire
```suggestion
I sistemi distribuiti possono essere [scalati orizzontalmente](/it/horizontal-scaling/), cioè aggiungendo altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consentendo a un sistema di gestire un improvviso aumento di carico di lavoro o di consumo di risorse.
```

2022-07-18 07:43 UTC, sistella requested changes

2022-07-18 07:43 UTC, sistella commented on content/it/distributed_system.md
> +Un sistema distribuito è un insieme di elementi computazionali autonomi collegati in rete, il quale agli occhi dell'utente costituisce un unico sistema coerente. Generalmente chiamati [nodi](/it/node
Alcune sfumature...
```suggestion
Un sistema distribuito è un insieme di elementi computazionali autonomi collegati in rete, pur apparendo all'utente un unico sistema coerente. Generalmente chiamati [nodi](/it/nodes/), questi elementi possono essere dispositivi hardware (ad esempio computer o smartphone) oppure processi software. I nodi sono programmati per raggiungere un obiettivo comune e si scambiano messaggi all'interno della rete per collaborare.
```

2022-07-18 07:43 UTC, sistella commented on content/it/distributed_system.md
> +Tradizionalmente i sistemi verrebbero [scalati](/it/scalability/) verticalmente, cioè aggiungendo più CPU o memoria a una singola macchina. La scalabilità verticale è un processo lungo, richiede dei
Ormai è una battaglia personale: siccome il verbo "scalare" non ha questo uso proprio nell'italiano (ancora), bisogna usare una parafrasi:
```suggestion
I sistemi tradizionali sono [scalabili](/it/scalability/) verticalmente, cioè vi si può aggiungere più CPU o memoria a una singola macchina. La scalabilità verticale è un processo lungo, richiede dei momenti di down e raggiunge velocemente i suoi limiti.
```

2022-07-18 07:43 UTC, sistella commented on content/it/distributed_system.md
> +I sistemi distribuiti possono essere [scalati orizzontalmente](/it/horizontal-scaling/), cioè aggiungendo altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consente
```suggestion
I sistemi distribuiti sono [scalabili orizzontalmente](/it/horizontal-scaling/), per esempio aggiungendo altri nodi al sistema quando è necessario. Questo processo può essere automatizzato, consentendo a un sistema di gestire un improvviso aumento di carico di lavoro o di consumo di risorse.
```

2022-07-18 13:05 UTC, annalisag-spark approved these changes

2022-07-23 08:46 UTC, sistella approved these changes

2022-07-24 20:15 UTC, merged