[bn] Localize content/bn/api-gateway.md
cncf/glossary pull request #1009
Opened 2022-06-29 05:09 UTC by Saber382

Signed-off-by: Saber Imtiaz saberimtiazmitul382@gmail.com
Localizes `content/bn/api-gateway.md` to Bengali
This is an intial PR as may need some improvements!
Tracking issue: #410

2022-06-29 05:15 UTC, mitul3737 requested changes

2022-06-29 05:15 UTC, mitul3737 commented on content/bn/api-gateway.md
> +title: API গেটওয়ে
Kindly update the title using the title in English. For example, API গেটওয়ে(API Gateway)

2022-06-29 05:34 UTC, mitul3737 requested changes

2022-06-29 05:34 UTC, mitul3737 commented on content/bn/api-gateway.md
> +একটি এপিআই গেটওয়ে নিরাপত্তা এবং [observability](/observability/)  এর মতো অপারেশনাল উদ্বেগগুলিকে সহজ করতে পারে ।
You can update the link for the Bengali page as `bn/observability/`

2022-07-25 06:19 UTC, Imtiaz1234 approved these changes
LGTM

2022-07-25 06:20 UTC, mitul3737 approved these changes
LGTM

2022-07-25 06:20 UTC, merged