Added chaos_engineering localization for ES
cncf/glossary pull request #1029
Opened 2022-07-02 04:51 UTC by jthan24

Added content for chaos_engineering localization!!

2022-07-05 13:01 UTC, krol3 reviewed
@jthan24  great work! I few comments

2022-07-05 13:01 UTC, krol3 commented on content/es/chaos_engineering.md
> +La Ingeniería del Caos es una técnica para conocer los requerimientos de resiliencia. Esta disciplina ayuda a obtener una infraestructura, plataforma y aplicación ante fallos. Los Ingenieros utilizan
```suggestion
La Ingeniería del Caos es una técnica para cumplir los requerimientos de resiliencia. Esta disciplina ayuda a obtener una infraestructura, plataforma y aplicación resistente ante fallos. Los Ingenieros utilizan los experimentos de caos de forma proactiva inyectando fallas aleatorias para verificar que la infraestructura, plataforma y aplicación puedan auto recuperarse y que la falla no sea de notable impacto para los usuarios finales. Los experimentos de caos buscan descubrir puntos ciegos (por ejemplo, monitoreo o técnicas de autoescalamiento) y mejorar la comunicación entre los equipos durante incidentes críticos. Este acercamiento ayuda a incrementar la resiliencia y la confianza de los equipos en sistemas complejos, particularmente en producción.
```

2022-07-05 13:56 UTC, electrocucaracha requested changes
Parece ser que el wordlist fue ordenado con vim, lo cual es tiene un orden deferente a `sort` y dificulta un poco la visualización de cambios.

2022-07-05 13:56 UTC, electrocucaracha commented on content/es/chaos_engineering.md
> +title: Ingenieria del Caos
```suggestion
title: Ingeniería del Caos
```

2022-07-05 13:56 UTC, electrocucaracha commented on content/es/chaos_engineering.md
> +## ¿Qué es?
Es necesario agregar un espacio en blanco después de los títulos
```suggestion
## ¿Qué es?

```

2022-07-05 13:56 UTC, electrocucaracha commented on content/es/chaos_engineering.md
> +## Problema de aborda
```suggestion
## Problema de aborda

```

2022-07-05 13:56 UTC, electrocucaracha commented on content/es/chaos_engineering.md
> +## ¿Cómo ayuda?
```suggestion
## ¿Cómo ayuda?

```

2022-07-07 02:26 UTC, jthan24 commented on content/es/chaos_engineering.md
> +Ingeniería del Caos o CE es la disciplina de experimentación en [Sistemas Distribuidos](/distributed_systems/) para producción para construir confianza en las capacidades de los sistemas en condicion
:done:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +Las prácticas de [SRE](/site_reliability_engineering/) y [DevOps](/devops/) tienen foco en el incremento de la resiliencia del producto y de la [confiabilidad](/reliability/). Un sistema con la habil
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +Ingeniería del Caos o CE es la disciplina de experimentación en [Sistemas Distribuidos](/distributed_systems/) para producción para construir confianza en las capacidades de los sistemas en condicion
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +La Ingeniería del Caos es una técnica para conocer los requerimientos de resiliencia. Esta disciplina ayuda a obtener una infraestructura, plataforma y aplicación ante fallos. Los Ingenieros utilizan
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +title: Ingenieria del Caos
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +## ¿Qué es?
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +## Problema de aborda
:heavy_check_mark:

2022-07-07 02:27 UTC, jthan24 commented on content/es/chaos_engineering.md
> +## ¿Cómo ayuda?
:heavy_check_mark:

2022-07-07 02:29 UTC, jthan24 commented
> 

Podria devolverlos y lanzarlos sobre algun contenedor? para que todos usemos el mismo? jejeje!!

2022-07-08 17:09 UTC, electrocucaracha commented
> > 
> 
> Podria devolverlos y lanzarlos sobre algun contenedor? para que todos usemos el mismo? jejeje!!

Hay dos cosas a tomar en consideración aquí, la primera sería la versión del comando `sort` y la segunda el `locale` configurado en la máquina.

La versión provista por [Coreutils](https://www.gnu.org/software/coreutils/coreutils.html) 

```bash
$ docker run --rm ubuntu:20.04 sort --version
sort (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Haertel and Paul Eggert.
```
es distinta a la que ofrece Busybox
```bash
$ docker run --rm busybox:1.35 sort --version
sort: unrecognized option `--version'
BusyBox v1.35.0 (2022-06-06 22:14:08 UTC) multi-call binary.
```

Además, [parece ser](https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do/87763#87763) que el `locale` configurado en la máquina puede afectar la manera en que se realiza el ordenamiento. Hasta el momento hemos utilizado:

`LC_ALL= sort -o content/es/.wordlist.txt content/es/.wordlist.txt`

Pero los valores son omitidos durante la ejecución del contenedor

`docker run --rm -v $(pwd):/opt/cncf/glossary -e "LC_ALL=" ubuntu:20.04 sort -o /opt/cncf/glossary/content/es/.wordlist.txt /opt/cncf/glossary/content/es/.wordlist.txt`

Por lo que quizá sea mejor usar el `sort` de `Coreutils` sin valor en `LC_ALL` corriendo nativamente.

2022-07-09 19:17 UTC, jthan24 commented
> > > 
> > 
> > 
> > Podria devolverlos y lanzarlos sobre algun contenedor? para que todos usemos el mismo? jejeje!!
> 
> Hay dos cosas a tomar en consideración aquí, la primera sería la versión del comando `sort` y la segunda el `locale` configurado en la máquina.
> 
> La versión provista por [Coreutils](https://www.gnu.org/software/coreutils/coreutils.html)
> 
> ```shell
> $ docker run --rm ubuntu:20.04 sort --version
> sort (GNU coreutils) 8.30
> Copyright (C) 2018 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Mike Haertel and Paul Eggert.
> ```
> 
> es distinta a la que ofrece Busybox
> 
> ```shell
> $ docker run --rm busybox:1.35 sort --version
> sort: unrecognized option `--version'
> BusyBox v1.35.0 (2022-06-06 22:14:08 UTC) multi-call binary.
> ```
> 
> Además, [parece ser](https://unix.stackexchange.com/questions/87745/what-does-lc-all-c-do/87763#87763) que el `locale` configurado en la máquina puede afectar la manera en que se realiza el ordenamiento. Hasta el momento hemos utilizado:
> 
> `LC_ALL= sort -o content/es/.wordlist.txt content/es/.wordlist.txt`
> 
> Pero los valores son omitidos durante la ejecución del contenedor
> 
> `docker run --rm -v $(pwd):/opt/cncf/glossary -e "LC_ALL=" ubuntu:20.04 sort -o /opt/cncf/glossary/content/es/.wordlist.txt /opt/cncf/glossary/content/es/.wordlist.txt`
> 
> Por lo que quizá sea mejor usar el `sort` de `Coreutils` sin valor en `LC_ALL` corriendo nativamente.

Hice la prueba pero aun asi me muestra demasiados cambios respecto a, e incluso volvi a descargar el archivo de .wordlist sin editar y lo volvi a agregar pero genero varios cambios!!  Estos fueron los terminos agregados.... 

Ingenieria
SRE
autoescalamiento
confiabilidad
indisponibilidad
monitoreo
proactiva

2022-07-27 22:22 UTC, krol3 commented
@jthan24 can you fix the conflicts ?

2022-08-23 16:00 UTC, raelga commented
@jthan24 Podrías squashear los commits en uno solo firmándolo?

Tienes más información en https://github.com/cncf/glossary/pull/1029/checks?check_run_id=7226085252:

- Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
- In your local branch, run: git rebase HEAD~5 --signoff
- Force push your changes to overwrite the branch: git push --force-with-lease origin es/chaos_engineering

2022-09-13 15:46 UTC, krol3 commented
@jthan24 te podemos ayudar en algo?

2022-11-29 17:40 UTC, electrocucaracha approved these changes

2022-12-02 23:34 UTC, krol3 approved these changes
LGTM, small suggestion.

2022-12-02 23:34 UTC, krol3 commented on content/es/chaos_engineering.md
> +Ingeniería del Caos o CE es la disciplina de experimentación sobre un [Sistema Distribuido](/distributed_systems/) en producción para construir confianza en la capacidad del sistema para soportar con
```suggestion
Ingeniería del Caos o CE (Chaos Engineering) es la disciplina de experimentación sobre un [Sistema Distribuido](/distributed_systems/) en producción para construir confianza en la capacidad del sistema para soportar condiciones inesperadas y turbulentas.
```

2022-12-06 15:11 UTC, 92nqb approved these changes
lgtm!

2022-12-13 17:39 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  you
```suggestion
you
your
```

2022-12-13 17:42 UTC, merged