feat: add content es/portability
cncf/glossary pull request #1043
Opened 2022-07-05 13:42 UTC by krol3

Closes https://github.com/cncf/glossary/issues/695

2022-07-14 01:47 UTC, krol3 commented on content/es/portability.md
> +Tradicionalmente, el software es construido para entornos específicos (p.ej. AWS o Linux). El software portátil, por otro lado, funciona en diferentes entornos operativos sin necesidad de una adaptac
@electrocucaracha la palabra portátil tambien es valida en espanol, porque motivos usar portable, parecen ambos sinonimos? https://es.bab.la/diccionario/ingles-espanol/portable#translationsdetails-en1

2022-07-16 13:36 UTC, electrocucaracha commented on content/es/portability.md
> +Tradicionalmente, el software es construido para entornos específicos (p.ej. AWS o Linux). El software portátil, por otro lado, funciona en diferentes entornos operativos sin necesidad de una adaptac
Entiendo, personalmente asocio la palabra portátil con una laptop. Checa el artículo en español de [Wikipedia](https://es.wikipedia.org/wiki/Portabilidad):

>  ...De este modo, si un determinado software compilado pudiere ser ejecutado en cualquier sistema operativo, diríamos que ese software es 100% **portable**.

2022-08-09 15:59 UTC, 92nqb requested changes

2022-08-09 15:59 UTC, 92nqb commented on content/es/portability.md
> +La portabilidad es una característica del software, siendo una forma de reutilización que ayuda a evitar el "bloqueo" de ciertos entornos operativos, p.ej. proveedores de nube, sistemas operativos o
No se si "vendor" se puede traducir como "vendedor". Quizas "distribuidor" es mejor

2022-08-09 21:22 UTC, electrocucaracha commented on content/es/portability.md
> +La portabilidad es una característica del software, siendo una forma de reutilización que ayuda a evitar el "bloqueo" de ciertos entornos operativos, p.ej. proveedores de nube, sistemas operativos o
Puede ser válido, aunque supongo que en este contexto se refiere a los vendedores de software

2022-08-09 21:23 UTC, electrocucaracha approved these changes

2022-08-09 22:15 UTC, ramrodo commented on content/es/portability.md
> +La portabilidad es una característica del software, siendo una forma de reutilización que ayuda a evitar el "bloqueo" de ciertos entornos operativos, p.ej. proveedores de nube, sistemas operativos o
Igual creo que deberíamos cambiar la palabra de "vendedores", suena mejor "distribuidor" como menciona @92nqb

2022-08-10 15:26 UTC, ramrodo commented
/lgtm

2022-08-16 23:42 UTC, i02sopop commented
/lgtm

2022-08-17 06:22 UTC, raelga approved these changes

2022-08-17 06:23 UTC, merged