[localization/german] Add localization for API
cncf/glossary pull request #1055
Opened 2022-07-10 08:24 UTC by gdenn

Issue: https://github.com/cncf/glossary/issues/508

2022-07-10 08:24 UTC, gdenn commented
@iamNoah1 @DaveVentura

2022-07-11 16:04 UTC, DavidWagnerDO reviewed
Grundsätzlich gefällt mir die Beschreibung rcihtig gut und ist auch mMn korrekt. Ich habe auch keine Rechtschreibe- oder Grammatikfehler gefunden.

Aber teilweise ist die Übersetzung, gerade in der letzten Hälfte relativ weit weg von dem englischen Original.

Ich finde deine Beschreibung eigentlich sogar besser.

Aber trotzdem die Frage an die anderen, nochmal zum Commitment:
Wenn ich mich richtig erinnere, wollten wir uns am Englischen orientieren.
[siehe hier](https://cloud-native.slack.com/archives/C02PCHJ55D2/p1649185045528839?thread_ts=1649182084.295099&cid=C02PCHJ55D2) 
Wie weit wollen/dürfen  wir uns von der Englischen Original entfernen? @iamNoah

2022-07-20 20:07 UTC, iamNoah1 requested changes
Sorry, dass ich so viele Änderungen bzw. Vorschläge eingebaut habe. Das hat mehrere Gründe. Zum einem wurde im Maintainerkreis entschieden, dass localization teams selbst entscheiden dürfen zu welchem Grad die Lokalisierung dem englischen Original gleichkommen soll. Zum anderen war der Fokus der Beschreibung sehr stark auf HTTP APIs gelegen. Wir dürfen nicht vergessen, dass es auch andere APIs gibt als nur HTTP Endpunkte. Das habe ich versucht etwas ins grade Licht zu rücken.

2022-07-20 20:07 UTC, iamNoah1 commented on content/de/application_programming_interface.md
> +Softwareanwendungen nutzten das Format, um Informationen über einen festen Source Code auszutauschen.
```suggestion

```

2022-07-20 20:07 UTC, iamNoah1 commented on content/de/application_programming_interface.md
> +In diesem Kontext spricht man auch davon, dass eine Applikation einen Endpunkt „konsumiert“.
```suggestion

```

2022-07-20 20:07 UTC, iamNoah1 commented on content/de/application_programming_interface.md
> +APIs lösen dieses Problem, in dem sie ein festes Kommunikationsprotokoll etablieren.
Wir sprechen eigentlich erst im nächsten Abschnitt davon, wie das problem gelöst wird.

2022-07-21 15:01 UTC, gdenn commented
@iamNoah1 danke für das Feedback, ich habe am WE wieder Zeit um daran zu arbeiten.

2022-07-28 08:11 UTC, iamNoah1 reviewed
Friendly ping @gdenn

2022-08-01 19:59 UTC, gdenn commented on content/de/application_programming_interface.md
> +In diesem Beispiel wäre eine API die konkrete Sprache, die gesprochen wird.
Mmh ich finde das sich beides nicht so super anhört, vlt. belassen wir es besser bei:

"APIs regeln die Kommunikation zwischen Softwareanwendungen. Im weiteren Sinne kann man das mit einem Gespräch zwischen zwei Personen vergleichen."

@iamNoah1 was denkst du?

2022-08-01 20:03 UTC, gdenn commented
@iamNoah1 do we squash commits with the merge? We have a lot of fill-up commits through the Github PR suggestion that we apply. ^^

2022-08-02 08:29 UTC, iamNoah1 commented
> @iamNoah1 do we squash commits with the merge? We have a lot of fill-up commits through the Github PR suggestion that we apply. ^^

No worries, I will squash at the end :) @gdenn

2022-08-02 08:30 UTC, iamNoah1 commented on content/de/application_programming_interface.md
> +In diesem Beispiel wäre eine API die konkrete Sprache, die gesprochen wird.
Find ich gut :)

2022-09-08 13:20 UTC, iamNoah1 commented
@gdenn friendly ping, are you still interested in completing the contribution or should we take over?

2022-09-12 06:10 UTC, gdenn commented
@iamNoah1 sorry, completely forgot, i'll finish. I also linked you in one of the threads, perhaps you can have a quick look at it.

best

2022-09-12 06:25 UTC, iamNoah1 commented
@gdenn no worries, I don't see any mention that I didn't answer yet. Can you point me to the open remark or add it again here? Things get messy with the grow of the thread ^^

2022-10-21 10:38 UTC, DaveVentura commented on content/de/application_programming_interface.md
> +Um die wachsende Komplexität zu beherrschen werden verschiedene Bereiche voneinander durch Modularisierung entkoppelt oder abstrahiert. Der Grad der Modularisierung kann dabei von internen Bereichen
```suggestion
Um die wachsende Komplexität zu beherrschen werden verschiedene Bereiche voneinander durch Modularisierung entkoppelt oder abstrahiert. Der Grad der Modularisierung kann dabei von internen Bereichen innerhalb einer Anwendung, bis hin zu einer eigenständigen Anwendung reichen (siehe [verteilten Anwendung](/distributed-apps/)). In beiden Fällen jedoch wird eine Standardisierung benötigt, die beschreibt wie, die einzelnen Anwendungen oder Anwendungsbereiche miteinander kommunizieren können. 
```

2022-10-21 10:39 UTC, DaveVentura approved these changes

2022-10-24 08:42 UTC, iamNoah1 approved these changes

2022-10-24 08:43 UTC, iamNoah1 commented on content/de/application_programming_interface.md
> +status: Feedback erwünscht
```suggestion
status: Completed
```

2022-10-24 08:45 UTC, merged