[it] localizzazione termine scalability
cncf/glossary pull request #1071
Opened 2022-07-13 20:23 UTC by fsbaraglia

2022-07-18 12:45 UTC, annalisag-spark commented on content/it/scalability.md
> +Un sistema scalabile facilita l'aggiunta di ulteriore capacità. Si distinguono due approcci di scalabilità. Da un lato, c'è la [scalabilità orizzontale](/it/horizontal_scaling/) che aggiunge altri no
```suggestion
Un sistema scalabile facilita l'aggiunta di ulteriore capacità. Si distinguono due approcci di scalabilità. Da un lato, c'è la [scalabilità orizzontale](/it/horizontal_scaling/) che aggiunge altri nodi per gestire un carico maggiore. Dall'altro la [scalabilità verticale](/it/vertical_scaling/) con la quale i singoli nodi vengono resi più potenti per eseguire più transazioni (ad esempio, aggiungendo più memoria o CPU a una singola macchina). Un sistema scalabile è in grado di cambiare facilmente e di soddisfare le esigenze degli utenti.
```

2022-07-23 08:59 UTC, sistella requested changes

2022-07-23 08:59 UTC, sistella commented on content/it/scalability.md
> +category: Propriety
```suggestion
category: Proprietà
```

2022-07-23 08:59 UTC, sistella commented on content/it/scalability.md
> +La scalabilità si riferisce alla capacità di un sistema di estendersi, o altrimenti detto di aumentare la propria capacità di fare qualsiasi cosa il sistema debba fare. Ad esempio, un [cluster](/it/c
Ho aggiunto le virgolette al termine `record` perché mi pare un concetto connaturato a Kubernetes e difficilmente traducibile (come i log di git, se non ho capito male)
```suggestion
La scalabilità si riferisce alla capacità di un sistema di estendersi, o altrimenti detto di aumentare la propria capacità di fare qualsiasi cosa il sistema debba fare. Ad esempio, un [cluster](/it/cluster/) [Kubernetes](/it/kubernetes/) è scalabile perché vi si possono aumentare o ridurre il numero delle  applicazioni [containerizzate](/it/containerization/). La scalabilità dipende, però, da diversi fattori. Quanti [nodi](/it/nodes/) ha, quanti [containers](/it/container/) può gestire ogni nodo e quanti "record" e operazioni può supportare il pannello di controllo.
```

2022-07-26 07:15 UTC, sistella approved these changes

2022-07-26 07:30 UTC, annalisag-spark approved these changes

2022-07-26 07:30 UTC, annalisag-spark commented
🤓👆🏼

2022-07-26 19:50 UTC, merged