[it] localizzazione termine Monolithic Apps
cncf/glossary pull request #1079
Opened 2022-07-14 10:32 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

2022-07-18 08:02 UTC, ugho16 commented on content/it/monolithic-apps.md
> +Trasformare un'applicazione in [microservizi](/it/microservices.md) aumenta gli sforzi operativi, in quanto ci sono più cose da testare, rilasciare e mantenere in esecuzione. Nelle prime fasi del cic
```suggestion
Trasformare un'applicazione in [microservizi](/it/microservices/) aumenta gli sforzi operativi, in quanto ci sono più cose da testare, rilasciare e mantenere in esecuzione. Nelle prime fasi del ciclo di vita di un prodotto può essere vantaggioso rimandare questa complessità e costruire un'applicazione monolitica, fino a quando il prodotto non sarà considerato un successo.
```

2022-07-23 09:40 UTC, sistella requested changes
Questa era tosta, bella traduzione! Solo qualche sfumatura...

2022-07-23 09:40 UTC, sistella commented on content/it/monolithic-apps.md
> +Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, qua
```suggestion
Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, quando l'applicazione aumenta in complessità, i monoliti possono diventare difficili da manutenere. Un maggior numero di sviluppatori che lavorino sullo stesso codice sorgente, implica  anche un aumenta della probabilità di effettuare cambiamenti che vadano in conflitto tra loro, da cui la necessità di rendere più fitta la comunicazione tra gli stessi sviluppatori.
```

2022-07-23 09:40 UTC, sistella commented on content/it/monolithic-apps.md
> +Un monolite ben progettato può rispettare i principi lean, essendo il modo più semplice per rendere operativa un'applicazione. Quando il valore di mercato di un'applicazione monolitica si dimostra un
```suggestion
Un monolite ben progettato può rispettare i principi lean, essendo il modo più semplice per realizzare un'applicazione funzionante. Quando un'applicazione monolitica dimostra di creare valore con successo, questa può essere scomposta in microservizi. Realizzare un'applicazione basata su microservizi prima di averne dimostrato il valore può essere un prematuro dispendio di energie a livello ingegneristico. Se l'applicazione non produce alcun valore, quelle energie saranno state sprecate.
```
Trovo anche che manchi una vera connotazione dei principi lean, ma qui anche l'inglese è carente. Forse potremmo aggiungere tra parentesi qualcosa tipo `(di opportunità ed efficienza innanzitutto)`. Che ne dite @annalisag-spark @fsbaraglia

2022-07-25 07:28 UTC, ugho16 commented on content/it/monolithic-apps.md
> +Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, qua
```suggestion
Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, quando l'applicazione aumenta in complessità, i monoliti possono diventare difficili da manutenere. Un maggior numero di sviluppatori che lavorino sullo stesso codice sorgente implica  anche un aumento della probabilità di effettuare cambiamenti che vadano in conflitto tra loro, da cui la necessità di rendere più fitta la comunicazione tra gli stessi sviluppatori.
```

2022-07-25 13:56 UTC, fsbaraglia requested changes

2022-07-26 07:18 UTC, sistella commented on content/it/monolithic-apps.md
> +Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, qua
@fsbaraglia sono simpaticamente contro l'uso del termine "deployabile"  :D

2022-07-26 07:19 UTC, sistella approved these changes

2022-07-26 07:35 UTC, annalisag-spark requested changes
ho visto solo due cosette, per il resto ineccepibile

2022-07-26 07:35 UTC, annalisag-spark commented on content/it/monolithic-apps.md
> +Trasformare un'applicazione in [microservizi](/it/microservices/) aumenta gli sforzi operativi, in quanto ci sono più cose da testare, rilasciare e mantenere in esecuzione. Nelle prime fasi del ciclo
```suggestion
Trasformare un'applicazione in [microservizi](/it/microservices/) aumenta gli sforzi operativi, in quanto ci sono più elementi da testare, rilasciare e mantenere in esecuzione. Nelle prime fasi del ciclo di vita di un prodotto può essere vantaggioso rimandare questa complessità e costruire un'applicazione monolitica, fino a quando il prodotto non sarà considerato un successo.
```

2022-07-26 07:35 UTC, annalisag-spark commented on content/it/monolithic-apps.md
> +Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, qua
```suggestion
Un'applicazione monolitica contiene tutte le funzionalità in un programma rilasciabile come una singola unità. Spesso questo è il modo più semplice di iniziare a creare un'applicazione. Tuttavia, quando l'applicazione aumenta in complessità, i monoliti possono diventare difficili da manutenere. Un maggior numero di sviluppatori che lavorino sullo stesso codice sorgente implica anche un aumento della probabilità di effettuare cambiamenti che vadano in conflitto tra loro, da cui la necessità di rendere più fitta la comunicazione tra gli stessi sviluppatori.
```

2022-07-26 09:19 UTC, annalisag-spark approved these changes

2022-07-26 09:19 UTC, annalisag-spark commented
Vai!

2022-07-26 19:49 UTC, fsbaraglia approved these changes

2022-07-26 19:49 UTC, merged

2022-07-26 19:50 UTC, fsbaraglia commented
Bravo 👍