[it] localizzazione termine cloud native security
cncf/glossary pull request #1083
Opened 2022-07-14 19:03 UTC by fsbaraglia

@annalisag-spark  @sistella please review :D

2022-07-18 12:35 UTC, annalisag-spark requested changes

2022-07-18 12:35 UTC, annalisag-spark commented on content/it/cloud_native_security.md
> +_Cloud native security_ introduce un nuovo modo di operare che protegge le applicazioni migrando dai modelli di sicurezza tradizionali a uno in cui la sicurezza è coinvolta in ogni fase del ciclo di
```suggestion
_Cloud native security_ introduce un nuovo modo di operare che protegge le applicazioni migrando dai modelli di sicurezza tradizionali a uno in cui la sicurezza è coinvolta in ogni fase del ciclo di release del software. Gli audit e i controlli manuali sono in gran parte sostituiti da scansioni automatizzate. Le pipeline di rilascio rapido del codice sono integrate con strumenti che analizzano il codice alla ricerca di vulnerabilità prima della sua compilazione. Le librerie open source vengono prelevate da fonti affidabili e monitorate per individuare eventuali vulnerabilità. Invece di rallentare il cambiamento, un modello di sicurezza cloud native lo abbraccia aggiornando frequentemente i componenti vulnerabili o garantendo che l'infrastruttura venga regolarmente sostituita.
```

2022-07-23 09:57 UTC, sistella requested changes

2022-07-23 09:57 UTC, sistella commented on content/it/cloud_native_security.md
> +_Cloud native security_ è un approccio che include la sicurezza nelle [applicazioni cloud native] (/it/cloud_native_apps/). Garantisce che la sicurezza faccia parte dell'intero ciclo di vita dell'app
```suggestion
_Cloud native security_ è un approccio che include la sicurezza nelle [applicazioni cloud native](/it/cloud_native_apps/). Garantisce che la sicurezza faccia parte dell'intero ciclo di vita dell'applicazione, dalla fase di sviluppo fino alla messa in produzione. Cloud native security mira a garantire gli stessi standard dei modelli di sicurezza tradizionali, adattandosi al contempo alle particolarità degli ambienti cloud native, in particolare alle rapide modifiche del codice e all'infrastruttura altamente effimera. Cloud native security è molto legata alla pratica chiamata [DevSecOps](/it/devsecops/).
```

2022-07-23 09:57 UTC, sistella commented on content/it/cloud_native_security.md
> +I modelli tradizionali di sicurezza sono stati costruiti sulla base di una serie di presupposti che non sono più validi. Le applicazioni cloud native cambiano frequentemente, utilizzano un gran numer
```suggestion
I modelli tradizionali di sicurezza sono stati costruiti sulla base di una serie di presupposti che non sono più validi. Le applicazioni cloud native cambiano frequentemente, utilizzano un gran numero di strumenti e librerie open source, spesso vengono fatte eseguire in un'infrastruttura controllata dal fornitore e sono soggette a rapidi cambiamenti dell'infrastruttura. Le revisioni del codice, i lunghi cicli di garanzia della qualità, la scansione delle vulnerabilità dei server e le revisioni della sicurezza dell'ultimo minuto non sono sufficientemente [scalabili](it/scalability/) quando si usano con le [applicazioni cloud native](it/cloud-native-apps/).
```

2022-07-23 09:57 UTC, sistella commented on content/it/cloud_native_security.md
> +_Cloud native security_ introduce un nuovo modo di operare che protegge le applicazioni migrando dai modelli di sicurezza tradizionali a uno in cui la sicurezza è coinvolta in ogni fase del ciclo di
```suggestion
Cloud native security introduce un nuovo modo di operare che protegge le applicazioni migrando dai modelli di sicurezza tradizionali ad uno in cui la sicurezza è coinvolta in ogni fase del ciclo di rilascio del software. Gli audit e i controlli manuali sono in gran parte sostituiti da scansioni automatizzate. Le pipeline di rilascio rapido del codice sono integrate con strumenti che analizzano il codice alla ricerca di vulnerabilità prima della sua compilazione. Le librerie open source vengono prelevate da fonti affidabili e monitorate per individuare eventuali vulnerabilità. Invece di rallentare il cambiamento, un modello di sicurezza cloud native lo abbraccia aggiornando frequentemente i componenti vulnerabili o garantendo che l'infrastruttura venga regolarmente sostituita.
```
Inoltre, non sono sicuro dell'ultimo verbo "sostituita". Capisco che è una buona traduzione di replaced, ma cosa si intende per sostituita nel senso del CNS?

2022-07-26 07:15 UTC, sistella approved these changes

2022-07-26 07:31 UTC, annalisag-spark approved these changes

2022-07-26 07:32 UTC, annalisag-spark commented
Dàje!

2022-07-26 19:48 UTC, merged