german localize cloud native apps
cncf/glossary pull request #1085
Opened 2022-07-15 12:22 UTC by DaveVentura

2022-07-15 12:28 UTC, iamNoah1 requested changes
Du hast das .md vergessen an der Datei, deshalb sind die ganzen checks kaputt

2022-07-27 15:12 UTC, iamNoah1 requested changes

2022-07-27 15:12 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Auch wenn es keinen einheitlichen Weg zu Cloud Native Anwendungen gibt, weisen sie doch einige Gemeinsamkeiten auf.
Würde ich komplett löschen

2022-07-27 15:12 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Cloud Native Anwendungen sind belastbar, verwaltbar und werden durch die zugehörigen Cloud-Dienste unterstützt.
```suggestion
Cloud Native Anwendungen folgen gewissen Prinzipien, die sie für den Betrieb in einer Cloud optimieren und somit deren volles Potential ausschöpfen lässt.```

2022-07-27 15:12 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Die verschiedenen Cloud-Services ermöglichen ein hohes Maß an Beobachtbarkeit, sodass Entwickler Probleme erkennen und beheben können, bevor sie eskalieren.
Zu dem Potential der Cloud gehören beispielsweise Skalierbarkeit, Ausfallsicherheit und Überwachung und diverse Automatisierungen. All das führt dazu, dass Cloud Native Anwendungen den modernen Anforderungen der heutigen Welt gerecht werden können.

2022-07-27 15:19 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Die verschiedenen Cloud-Services ermöglichen ein hohes Maß an Beobachtbarkeit, sodass Entwickler Probleme erkennen und beheben können, bevor sie eskalieren.
```suggestion
Zu dem Potential der Cloud gehören beispielsweise Skalierbarkeit, Ausfallsicherheit und Überwachung und diverse Automatisierungen. All das führt dazu, dass Cloud Native Anwendungen den modernen Anforderungen der heutigen Welt gerecht werden können. . 
```

2022-08-05 14:01 UTC, DaveVentura commented on content/de/cloud-native-apps.md
> +Der Begriff bezieht sich auch auf Anwendungen, die die Vorteile der Innovationen in der Infrastruktur nutzen, die durch Cloud Computing vorangetrieben wurden.
hab mich an der englischen version orientiert, ist mir auch aufgefallen

2022-08-05 16:21 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Cloud Native Anwendungen folgen gewissen Prinzipien, die sie für den Betrieb in einer Cloud optimieren und somit deren volles Potential ausschöpfen lässt.```
```suggestion
Cloud Native Anwendungen folgen gewissen Prinzipien, die sie für den Betrieb in einer Cloud optimieren und somit deren volles Potential ausschöpfen lässt.
```

2022-08-05 16:21 UTC, iamNoah1 commented on content/de/cloud-native-apps.md
> +Zu dem Potential der Cloud gehören beispielsweise Skalierbarkeit, Ausfallsicherheit und Überwachung und diverse Automatisierungen. All das führt dazu, dass Cloud Native Anwendungen den modernen Anfor
```suggestion
Zu dem Potential der Cloud gehören beispielsweise Skalierbarkeit, Ausfallsicherheit und Überwachung und diverse Automatisierungen. All das führt dazu, dass Cloud Native Anwendungen den modernen Anforderungen der heutigen Welt gerecht werden können. 
```

2022-08-05 16:21 UTC, iamNoah1 approved these changes
Nice, lgtm

2022-08-05 16:22 UTC, iamNoah1 commented
@CathPag we need a second review here :) Please use squash and merge :)

2022-08-11 13:42 UTC, CathPag approved these changes
LGTM

2022-08-11 13:42 UTC, merged