[it] Localizzazione termine Service Mesh
cncf/glossary pull request #1115
Opened 2022-07-26 08:49 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

2022-07-26 09:38 UTC, annalisag-spark requested changes

2022-07-26 09:38 UTC, annalisag-spark commented on content/it/service-mesh.md
> +In un mondo costituito da [microservizi](/it/microservices), le applicazioni sono suddivise in diversi [servizi](/it/services) che comunicano attraverso una rete. Proprio come una rete Wi-Fi, le reti
```suggestion
In un mondo costituito da [microservizi](/it/microservices), le applicazioni sono spacchettate in diversi [servizi](/it/services) che comunicano tra loro attraverso una rete. Proprio come una qualunque rete Wi-Fi, le reti di computer sono intrinsecamente inaffidabili, hackerabili e spesso lente. Le service mesh rispondono a questo nuovo set di sfide gestendo il traffico (cioè la comunicazione) tra i servizi e conferendo in modo uniforme [affidabilità](/it/reliability), [osservabilità](/it/observability) e sicurezza a tutti i servizi.
```

2022-07-26 09:38 UTC, annalisag-spark commented on content/it/service-mesh.md
> +In un mondo costituito da [microservizi](/it/microservices), le applicazioni sono suddivise in diversi [servizi](/it/services) che comunicano attraverso una rete. Proprio come una rete Wi-Fi, le reti
solo suggerimenti!
per la questione maschile / femminile dei termini, invece, la querelle è aperta, bisognerebbe contare le occorrenze in rete e la loro autorevolezza, ma tant'è 😏
io voto per LE service mesh 😝

2022-07-26 09:38 UTC, annalisag-spark commented on content/it/service-mesh.md
> +I service mesh aggiungono in modo uniforme affidabilità, osservabilità e sicurezza a tutti i servizi all'interno di un cluster senza richiedere modifiche al codice. Prima dei service mesh queste funz
```suggestion
Le service mesh conferiscono in modo uniforme affidabilità, osservabilità e sicurezza a tutti i servizi all'interno di un cluster senza richiedere modifiche al codice. Prima dell'avvento delle service mesh, queste funzionalità dovevano essere aggiunte al codice di ogni singolo servizio, diventando una potenziale fonte di bug e debiti tecnici.
```

2022-07-26 12:59 UTC, annalisag-spark approved these changes

2022-08-10 09:29 UTC, fsbaraglia approved these changes

2022-10-28 21:58 UTC, merged