Create microservices.md
cncf/glossary pull request #1139
Opened 2022-07-30 06:01 UTC by SahityaGupta25

Signed-off-by: SahityaGupta25 <99082422+SahityaGupta25@users.noreply.github.com>

2022-08-05 11:39 UTC, anubha-v-ardhan requested changes
Thank you @SahityaGupta25.
Please go though these suggested changes and commit them if you agree.

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +| [Microservices](https://github.com/cncf/glossary/blob/main/content/en/microservices.md) | Completed | Concept  |
```suggestion
---
title: माइक्रोसर्विसेज़ (Microservices)
status: Completed
category: अवधारणा
---
```

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +#समस्या यह संबोधित करता है
```suggestion
# समस्या
```

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +# यह कैसे मदद करता है
```suggestion
# समाधान
```

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +```
```suggestion
माइक्रोसर्विसेज एप्लीकेशन विकास के लिए एक आधुनिक दृष्टिकोण है जो क्लाउड नेटिव तकनीकों का लाभ उठाता है। जहाँ आधुनिक एप्लिकेशन, जैसे नेटफ्लिक्स (Netflix), एक एकल ऐप प्रतीत होते हैं, वे वास्तव में छोटी सेवाओं का एक संग्रह हैं - सभी एक साथ मिलकर काम कर रहे हैं। उदाहरण के लिए, एक एकल पृष्ठ जो आपको वीडियो तक पहुंचने, खोजने और पूर्वावलोकन करने की अनुमति देता है, संभवतः छोटी सेवाओं द्वारा संचालित होता है जो प्रत्येक इसके एक पहलू को संभालते हैं (जैसे आपके ब्राउज़र में खोज, प्रमाणीकरण और पूर्वावलोकन चलाना)। संक्षेप में, माइक्रोसर्विसेज एक एप्लिकेशन आर्किटेक्चर पैटर्न को संदर्भित करता है जो आमतौर पर  मोनोलिथिक एप्लिकेशन के विपरीत होता है।
```

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +[Micro Services](https://github.com/cncf/glossary/blob/main/content/en/microservices.md) अखंड अनुप्रयोगों द्वारा उत्पन्न चुनौतियों की प्रतिक्रिया है। आम तौर पर, किसी एप्लिकेशन के विभिन्न हिस्सों को अ
```suggestion
माइक्रोसर्विस अखंड एप्लीकेशनों द्वारा उत्पन्न चुनौतियों की प्रतिक्रिया है। आम तौर पर, किसी एप्लिकेशन के विभिन्न हिस्सों को अलग-अलग [स्केल](/scalability/) करने की आवश्यकता होती है। उदाहरण के लिए, एक ऑनलाइन स्टोर, चेकआउट की तुलना में अधिक उत्पाद दर्शाता है। इसका मतलब है कि आपको चेकआउट की तुलना में चल रहे उत्पाद दृश्य कार्यक्षमता की अधिक प्रतियों की आवश्यकता होगी। एक अखंड एप्लीकेशन में, उन बिट्स को अलग से तैनात नहीं किया जा सकता है। यदि आप व्यक्तिगत रूप से उत्पाद की कार्यक्षमता को माप नहीं सकते हैं, तो आपको पूरे ऐप को उन सभी घटकों के साथ डुप्लिकेट करना होगा जिनकी आपको आवश्यकता नहीं है - संसाधनों का एक अक्षम उपयोग। मोनोलिथिक एप्लिकेशन भी डेवलपर्स के लिए डिजाइन के नुकसान को आसान बनाते हैं। चूंकि सभी कोड एक ही स्थान पर हैं, इसलिए उस कोड को [युग्मित (tightly-coupled)](/tightly-coupled-architectures/) करना आसान है और चिंताओं को अलग करने के सिद्धांत को लागू करना कठिन है। मोनोलिथ में अक्सर डेवलपर्स को उत्पादक होने से पहले पूरे कोडबेस को समझने की आवश्यकता होती है।
```

2022-08-05 11:39 UTC, anubha-v-ardhan commented on content/hi/microservices.md
> +```
```suggestion
विभिन्न माइक्रोसर्विसेज में कार्यक्षमता को अलग करने से उन्हें स्वतंत्र रूप से तैनात, अपडेट और स्केल करना आसान हो जाता है। अलग-अलग टीमों को बड़े एप्लिकेशन के अपने छोटे हिस्से पर ध्यान केंद्रित करने की अनुमति देकर आप उनके लिए बाकी संगठन को नकारात्मक रूप से प्रभावित किए बिना अपने ऐप्स पर काम करना आसान बनाते हैं। माइक्रोसर्विसेज कई समस्याओं का समाधान करते हैं पर वे परिचालन ओवरहेड भी बनाते हैं - वे चीजें जिन्हें आपको तैनात करने और परिमाण या अधिक के क्रम में वृद्धि का ट्रैक रखने की आवश्यकता होती है। कई [क्लाउड-नेटिव तकनीकों](/cloud-native-tech/) का उद्देश्य माइक्रोसर्विसेज को तैनात और प्रबंधित करना आसान बनाना है।

```

2022-09-23 20:15 UTC, Garima-Negi commented
@SahityaGupta25 any updates on the changes requested?

2022-09-25 07:09 UTC, SahityaGupta25 commented
@Garima-Negi No

2023-01-05 13:51 UTC, anubha-v-ardhan commented
Hello @SahityaGupta25 Are you still working on this PR? Any updates about the requested changes

2023-01-07 13:56 UTC, Garima-Negi commented
closing this PR due to inactivity

2023-01-07 13:56 UTC, closed without merging