[it] Localizzazione termine Containerization
cncf/glossary pull request #1146
Opened 2022-08-01 10:44 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

2022-08-05 06:59 UTC, annalisag-spark requested changes
Piccole cose e proposte di assestamento. Vedi tu se hanno senso.
Grazie :)

2022-08-05 06:59 UTC, annalisag-spark commented on content/it/containerization.md
> +Prima che i container si diffondessero, Le organizzazioni si affidavano alle [macchine virtuali](/it/virtual-machine/) per orchestrare più applicazioni su una singola macchina [bare metal](/it/bare-m
```suggestion
Prima che i container si diffondessero, le organizzazioni si affidavano alle [macchine virtuali](/it/virtual-machine/) per orchestrare più applicazioni su una singola macchina [bare metal](/it/bare-metal-machine/). Le macchine virtuali sono molto più grandi dei container e richiedono un hypervisor per funzionare. A causa dell'archiviazione, del backup e del trasferimento di questi modelli di macchine virtuali più grandi, anche la creazione dei modelli di macchine virtuali è lenta. Inoltre, le macchine virtuali possono soffrire di una deriva della configurazione che viola il principio di [immutabilità](/it/immutability/).
```

2022-08-05 06:59 UTC, annalisag-spark commented on content/it/containerization.md
> +Le immagini container sono leggere (a differenza delle macchine virtuali tradizionali) e il processo di containerizzazione richiede un file con un elenco di dipendenze. Questo file può essere con un
```suggestion
Le immagini container sono leggere (a differenza delle macchine virtuali tradizionali) e il processo di containerizzazione richiede un file con un elenco di dipendenze. Questo file può prevedere un [controllo di versione](/it/version-control/) e il processo di creazione può essere automatizzato, permettendo all'organizzazione di concentrarsi su altre priorità, mentre i processi automatizzati si occupano della creazione. L'immagine container è memorizzata con un identificatore univoco legato al suo esatto contenuto e alla sua configurazione. Poiché i container vengono pianificati e riprogrammati, vengono sempre ripristinati allo stato iniziale, eliminando così la deriva della configurazione.
```

2022-08-05 07:59 UTC, annalisag-spark approved these changes

2022-08-10 09:27 UTC, fsbaraglia approved these changes

2022-08-10 09:27 UTC, fsbaraglia commented
@sistella  your review and merge please

2022-10-28 21:58 UTC, merged