Localize term  site_reliabilty_engineering into Hindi
cncf/glossary pull request #1152
Opened 2022-08-02 09:37 UTC by taniaduggal

Fixes #1130 
Signed-off-by: Tania Duggal <taniaduggal60@gmail.com>

2022-08-05 04:03 UTC, taniaduggal commented
@anubha-v-ardhan  Please take a look.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-05 05:07 UTC, anubha-v-ardhan requested changes
Thank you @taniaduggal, please go through the suggested changes and commit them if you agree :)

2022-08-05 05:07 UTC, anubha-v-ardhan commented on content/hi/site_reliability_engineering.md
> +साइट विश्वसनीयता इंजीनियरिंग या एसआरई एक अनुशासन है जो संचालन और सॉफ्टवेयर इंजीनियरिंग को जोड़ती है। उत्तरार्द्ध विशेष रूप से बुनियादी ढांचे और संचालन की समस्याओं पर लागू होता है। मतलब, उत्पाद सुविधा
```suggestion
साइट विश्वसनीयता इंजीनियरिंग या SRE एक अनुशासन है जो संचालन (operations) और सॉफ्टवेयर इंजीनियरिंग को जोड़ती है। उत्तरार्द्ध विशेष रूप से इंफ्रास्टक्टर और संचालन की समस्याओं पर लागू होता है। अर्थात, उत्पाद सुविधाओं के निर्माण के बजाय, साइट विश्वसनीयता इंजीनियर एप्लीकेशनों को चलाने के लिए सिस्टम बनाते हैं। इसकी डेवॉप्स के साथ समानताएं हैं, लेकिन जहाँ डेवॉप्स उत्पादन के लिए कोड प्राप्त करने पर ध्यान केंद्रित करता है, SRE यह सुनिश्चित करता है कि उत्पादन में चल रहा कोड ठीक से काम करता है।
```

2022-08-05 05:07 UTC, anubha-v-ardhan commented on content/hi/site_reliability_engineering.md
> +अनुप्रयोगों को मज़बूती से चलाना सुनिश्चित करने के लिए प्रदर्शन की निगरानी, ​​​​अलर्टिंग, डिबगिंग से लेकर समस्या निवारण तक कई क्षमताओं की आवश्यकता होती है। इसके बिना, सिस्टम ऑपरेटर केवल समस्याओं पर प्
```suggestion
एप्लीकेशनों की विश्वसनीय चलन सुनिश्चित करने के लिए प्रदर्शन की निगरानी, ​​​​अलर्टिंग, डिबगिंग से लेकर समस्या निवारण तक कई क्षमताओं की आवश्यकता होती है। इसके बिना, सिस्टम ऑपरेटर केवल समस्याओं पर प्रतिक्रिया कर सकते हैं बनाम उनसे बचने की दिशा में सक्रिय रूप से काम करना जिससे डाउनटाइम केवल समय की बात बन जाता है।
```

2022-08-05 05:07 UTC, anubha-v-ardhan commented on content/hi/site_reliability_engineering.md
> +एक एसआरई दृष्टिकोण अंतर्निहित प्रणाली में लगातार सुधार करके सॉफ्टवेयर विकास प्रक्रिया की लागत, समय और प्रयास को कम करता है। सिस्टम लगातार बुनियादी ढांचे और अनुप्रयोग घटकों को मापता है और उनकी निगरानी
```suggestion
एक SRE दृष्टिकोण अंतर्निहित प्रणाली में लगातार सुधार करके सॉफ्टवेयर विकास प्रक्रिया की लागत, समय और प्रयास को कम करता है। सिस्टम लगातार बुनियादी ढांचे और एप्लीकेशन घटकों को मापता है और उनकी निगरानी करता है। जब कुछ गलत हो जाता है, तो सिस्टम साइट विश्वसनीयता इंजीनियरों को इंगित करता है कि इसे कब, कहाँ और कैसे ठीक किया जाए। यह दृष्टिकोण परिचालन कार्यों को स्वचालित करके अत्यधिक स्केलेबल और विश्वसनीय सॉफ्टवेयर सिस्टम बनाने में मदद करता है।
```

2022-08-05 05:08 UTC, anubha-v-ardhan requested changes
Hey @taniaduggal, Can you please change the file name to `site-reliability-engineering.md`. We prefer keeping the file names same as English version

2022-08-08 05:29 UTC, taniaduggal commented
@anubha-v-ardhan Please again review at pr. I made suggested changes.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-10 02:39 UTC, anubha-v-ardhan requested changes
@taniaduggal The file name is still `site_reliability_engineering.md`, Can we change it to `site-reliability-engineering.md` to maintain consistency with English version.

2022-08-10 03:00 UTC, taniaduggal commented
@anubha-v-ardhan How can I change it? Please suggests.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Anubhav Vardhan ***@***.***>
Sent: Wednesday, August 10, 2022 8:09:58 AM
To: cncf/glossary ***@***.***>
Cc: Tania Duggal ***@***.***>; Mention ***@***.***>
Subject: Re: [cncf/glossary] Localize site-reliabilty-engineering.md into Hindi (PR #1152)


@anubha-v-ardhan requested changes on this pull request.

@taniaduggal<https://github.com/taniaduggal> The file name is still site_reliability_engineering.md, Can we change it to site-reliability-engineering.md to maintain consistency with English version.

—
Reply to this email directly, view it on GitHub<https://github.com/cncf/glossary/pull/1152#pullrequestreview-1067582196>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYVTZXRURVD75YCNRIPU6CLVYMI75ANCNFSM55KOWEMA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-08-10 06:59 UTC, Garima-Negi commented
Hi @taniaduggal , in your local branch `taniaduggal:tania/site_reliability_engineering1` , using an IDE you can select filename and then right click and select rename .

2022-08-10 20:44 UTC, sayantani11 approved these changes
Thanks!
LGTM

2022-08-15 08:10 UTC, taniaduggal commented
@Garima-Negi Please merge this PR if changes looks good.

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-18 01:48 UTC, anubha-v-ardhan approved these changes
LGTM

2022-08-18 01:48 UTC, anubha-v-ardhan commented
Thank you @taniaduggal :)

2022-08-18 01:48 UTC, merged