[it] Localizzazione termine Containers-as-a-service
cncf/glossary pull request #1186
Opened 2022-08-09 13:50 UTC by ugho16

Added Containers-as-a-service Italian localization
Signed-off-by: Paolo <ugho16@users.noreply.github.com>

2022-08-10 09:26 UTC, fsbaraglia approved these changes
good to me

2022-08-10 09:26 UTC, fsbaraglia commented
@sistella  @annalisag-spark  please your review is needed

2022-08-17 07:00 UTC, annalisag-spark requested changes

2022-10-24 14:28 UTC, annalisag-spark requested changes

2022-10-24 14:47 UTC, ugho16 commented on content/it/containers-as-a-service.md
> +Quando si distribuiscono applicazioni containerizzate su una piattaforma CaaS, gli utenti acquisiscono visibilità sulle performance del sistema attraverso aggregazioni di log e strumenti di monitorag
```suggestion
Quando si distribuiscono applicazioni containerizzate su una piattaforma CaaS, gli utenti acquisiscono visibilità sulle performance del sistema attraverso aggregazioni di log e strumenti di monitoraggio. I servizi CaaS includono anche funzionalità incorporate per l'[auto scaling](/it/auto-scaling/) e la gestione dell'orchestrazione. Ciò permette ai team di costruire [sistemi distribuiti](/it/distributed-systems/) ad alta visibilità e alta disponibilità. Inoltre, consentendo rapide distribuzioni, i servizi CaaS aumentano la velocità dei team di sviluppo. Mentre i container assicurano un obiettivo di distribuzione uniforme, i servizi CaaS diminuiscono i costi operativi a livello ingegneristico riducendo le risorse [DevOps](/it/devops/) necessarie per gestire una distribuzione.

```

2022-10-24 14:54 UTC, annalisag-spark approved these changes

2022-10-28 21:58 UTC, merged