[es] Localize 'Container Image'
cncf/glossary pull request #1228
Opened 2022-08-15 19:14 UTC by RedwineOS

Solves [576](https://github.com/cncf/glossary/issues/576)

2022-08-30 17:43 UTC, electrocucaracha reviewed
@RedwineOS muchas gracias por tu contribución, dejo un par de observaciones menores. Por otra parte, este PR debe ser realizado hacia el branch de `dev-es` en lugar de `main`

2022-08-30 17:43 UTC, electrocucaracha commented on content/es/container-image.md
> +## ¿Qué es esto?
```suggestion
## ¿Qué es?
```

2022-08-30 17:43 UTC, electrocucaracha commented on content/es/container-image.md
> +## El problema que aborda
```suggestion
## Problema que aborda
```

2022-08-30 22:22 UTC, ramrodo commented on content/es/container-image.md
> +El framework de una imagen debe de seguir el esquema estándar definido por el Open Container Iniative (OCI).
```suggestion
El framework de una imagen debe de seguir el esquema estándar definido por el Open Container Initiative (OCI).
```

2022-08-30 22:23 UTC, ramrodo requested changes
Suggestion requested

2022-09-02 09:00 UTC, RedwineOS commented
By error I originally made the PR pointing `main` instead of `dev-es`, so sorry for all the reviewers added after changing the target.

2022-09-02 10:40 UTC, 92nqb approved these changes

2022-09-05 16:21 UTC, ramrodo commented
/lgtm

2022-09-05 16:21 UTC, ramrodo approved these changes

2022-09-05 17:50 UTC, raelga approved these changes

2022-09-05 22:30 UTC, electrocucaracha commented
@RedwineOS podrías agregar las siguientes palabras al [wordlist](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt):

```
CRI
Container
Initiative
OCI
Open
Runtime
framework
```

No olvides ordenarlas con el siguiente comando:

```bash
LC_ALL= sort -o content/es/.wordlist.txt content/es/.wordlist.txt
```

2022-09-06 12:08 UTC, RedwineOS commented
> @RedwineOS podrías agregar las siguientes palabras al [wordlist](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt):
> 
> ```
> CRI
> Container
> Initiative
> OCI
> Open
> Runtime
> framework
> ```
> 
> No olvides ordenarlas con el siguiente comando:
> 
> ```shell
> LC_ALL= sort -o content/es/.wordlist.txt content/es/.wordlist.txt
> ```

Hecho.

2022-09-09 01:55 UTC, krol3 commented on content/es/container-image.md
> +Una imagen puede da lugar a cualquier número de contenedores, según sea necesario, permitiendo una mayor escalabilidad.
```suggestion
Una imagen puede dar lugar a cualquier número de contenedores, según sea necesario, permitiendo una mayor escalabilidad.
```

2022-09-20 15:46 UTC, merged