Localizzazione Stateful Apps
cncf/glossary pull request #1239
Opened 2022-08-18 14:17 UTC by annalisag-spark

2022-10-28 21:59 UTC, fsbaraglia approved these changes

2022-12-14 10:11 UTC, ugho16 requested changes

2022-12-14 10:11 UTC, ugho16 commented on content/it/stateful-apps.md
> +Quando parliamo di applicazioni _stateful_ (letteralmente "a pieno stato") (e [stateless](/stateless-apps/)) (letteralmente "senza stato"),
```suggestion
Quando parliamo di applicazioni _stateful_ (letteralmente "a pieno stato") e [stateless](/it/stateless-apps/) (letteralmente "senza stato"),
```

2022-12-14 10:24 UTC, ugho16 approved these changes

2023-01-09 14:16 UTC, merged