[it] Localizzazione Stateless Apps
cncf/glossary pull request #1241
Opened 2022-08-19 08:58 UTC by annalisag-spark

Tradotto da commit inglese 919b82f

2022-08-19 09:05 UTC, iamNoah1 requested changes
That's weird, the platform_as_a_service.md is not intended to be in this PR as well I guess :)

2022-08-19 09:09 UTC, annalisag-spark commented
I know @iamNoah1 and trying to understand why it keeps on popping up every time I open a new PR. I don't know where it gets wrong, I just follow the steps suggested by the GitHub interface. I asked Seokho if he has got time to explain me once and for all the path to follow 😰
It's rater frustrating

2022-10-29 19:25 UTC, fsbaraglia approved these changes

2022-10-29 19:25 UTC, fsbaraglia commented
removed the file platform_as_a_service.md

2022-12-14 10:03 UTC, ugho16 requested changes

2022-12-14 10:03 UTC, ugho16 commented on content/it/stateless-apps.md
> +
```suggestion
```

2022-12-14 10:03 UTC, ugho16 commented on content/it/stateless-apps.md
> +poiché pod diversi in un [cluster](/cluster/) possono funzionare in modo indipendente,
```suggestion
poiché pod diversi in un [cluster](/it/cluster/) possono funzionare in modo indipendente,
```

2022-12-14 10:03 UTC, ugho16 commented on content/it/stateless-apps.md
> +
```suggestion
```

2023-01-09 14:36 UTC, annalisag-spark commented
@iamNoah1 ciao! it should be ok now, could you please have a look so that we can merge it? thanks

2023-09-06 22:23 UTC, fsbaraglia commented
@iamNoah1 please review it again

2025-04-10 09:54 UTC, closed without merging

2025-04-10 09:54 UTC, sistella commented
This term changed a lot with [PR #2685](https://github.com/cncf/glossary/pull/2685/files).
Will better handle in another PR