Added lang-bn Microservices
cncf/glossary pull request #1246
Opened 2022-08-20 11:43 UTC by sarkartanmay393

### Describe your changes
Completely localized this topic.

Signed-off-by: Tanmay Sarkar <84321236+sarkartanmay393@users.noreply.github.com>
Localizes ``content/bn/<microservices.md>``  to Bengali.
This is an initial PR as may need some improvements!
Tracking issue: #410

2022-08-20 11:44 UTC, sarkartanmay393 commented
@mitul3737 take a look

2022-08-26 15:56 UTC, mitul3737 requested changes

2022-08-26 15:56 UTC, mitul3737 commented on content/bn/microservices.md
> +অ্যাপ্লিকেশন ডেভেলপমেন্টে (Application Development) একটি আধুনিক পন্থা হলো মাইক্রোসার্ভিস (Microservice), যা ক্লাউড নেটিভ (Cloud Native) প্রযুক্তির সুবিধা নেয়। যেখানে আধুনিক অ্যাপ্লিকেশনগুলি, যেমন নে
```suggestion
অ্যাপ্লিকেশন ডেভেলপমেন্টে (Application Development) একটি আধুনিক পন্থা হলো মাইক্রোসার্ভিস (Microservice), যা ক্লাউড নেটিভ (Cloud Native) প্রযুক্তির সুবিধা নেয়। যেখানে আধুনিক অ্যাপ্লিকেশনগুলি, যেমন নেটফ্লিক্স(netflix) একটি একক অ্যাপ এর মত দেখায় কিন্তু এটি আসলে অনেকগুলি ছোট ছোট সার্ভিসের একত্রিত রূপ, সবগুলি একে অপরের সাথে আবদ্ধ ভাবে কাজ করে চলেছে। এই ক্ষেত্রে, কোনো অ্যাপ এর একটি একক পেজ যা আমাদের search, authenticate এবং ভিডিও দেখতে অনুমতি দেয় তা আসলে অনেকগুলি ছোট ছোট সার্ভিস দ্বারা চালিত হয়, যেখানে এক একটি সার্ভিস এক একটি বৈশিষ্ট্য সামলায়। সংক্ষেপে, মাইক্রোসার্ভিস বলতে একটি এপ্লিকেশন আর্কিটেকচার প্যাটার্ন (Application Architecture Pattern) কে বোঝানো হয় যা [মনোলিথিক এপ্লিকেশন (Monolithic Application)](/bn/monolithic_apps/) এর থেকে স্বাভাবিকত বিপরীত।
```

2022-09-09 11:59 UTC, sarkartanmay393 commented on content/bn/microservices.md
> +অ্যাপ্লিকেশন ডেভেলপমেন্টে (Application Development) একটি আধুনিক পন্থা হলো মাইক্রোসার্ভিস (Microservice), যা ক্লাউড নেটিভ (Cloud Native) প্রযুক্তির সুবিধা নেয়। যেখানে আধুনিক অ্যাপ্লিকেশনগুলি, যেমন নে
+1

2022-09-09 12:00 UTC, sarkartanmay393 commented on content/bn/microservices.md
> +মাইক্রোসার্ভিসেস হল মনোলিথিক এপ্লিকেশনের দ্বারা জাহির করা চ্যালেঞ্জগুলির প্রতি একটি উত্তর। স্বাভাবিকভাবে, একটি অ্যাপ্লিকেশনের বিভিন্ন অংশকে আলাদা আলাদা ভাবে বড় ([scaled](/scalability/) separately) ক
+1

2022-09-09 12:01 UTC, sarkartanmay393 commented on content/bn/microservices.md
> +কার্যকারিতা(functionality) কে বিভিন্ন মাইক্রোসার্ভিসে আলাদা করে স্বাধীনভাবে স্থাপন, আপডেট এবং দক্ষতা মিশ্রিত করা সহজ। বিভিন্ন দলকে একটি বৃহত্তর অ্যাপ্লিকেশনের ছোট অংশে ফোকাস করার অনুমতি দিয়ে সংস্থার
+1

2022-09-09 12:04 UTC, sarkartanmay393 commented
@mitul3737 Check once. I have made your suggested changes. Why can't I add to batch and commit all of your suggested changes at once ?

2022-09-09 12:54 UTC, mitul3737 approved these changes
lgtm

2022-09-09 12:56 UTC, Imtiaz1234 approved these changes
LGTM

2022-09-09 12:56 UTC, merged