[DE] Add german definition for canary deployment
cncf/glossary pull request #1247
Opened 2022-08-20 21:17 UTC by bcubk

Signed-off-by: Baris Cubukcuoglu <cubukcuoglu.baris@gmail.com>

### Describe your changes

This PR adds the german definition for Canary Deployment according to [Canary Deployment](https://glossary.cncf.io/canary-deployment/)

### Related issue number or link (ex: `resolves #512 `)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-08 14:14 UTC, iamNoah1 requested changes
Vielen Dank @bcubk für den Beitrag und die Geduld. Im Großen und Ganzen finde ich alles gut, habe nur ein paar kleinere Änderungsvorschläge gemacht :)

2022-09-08 14:14 UTC, iamNoah1 commented on content/de/canary_deployment.md
> +Der Datenverkehr wird schrittweise von der ursprünglichen Version der Anwendung auf die aktualisierte Version verlagert.
```suggestion
Der Datenverkehr wird nun schrittweise von der aktuell produktiven Umgebung auf die Umgebung mit der neuen Version der Anwendung gelenkt. 
```

mit dem Echtzeit-Datenverkehr und eine Umgebung, die eine neue Version der ohne Datenverkehr.

2022-09-08 14:14 UTC, iamNoah1 commented on content/de/canary_deployment.md
> +Der Begriff "Canary" (Kanarienvogel) stammt aus der Praxis des "Kanarienvogels im Kohlebergwerk", wo Kanarienvögel in Kohlebergwerke gebracht wurden, um die Bergleute zu schützen.
```suggestion
Der Begriff "Canary" (Kanarienvogel) stammt aus der Praxis des "Kanarienvogels im Kohlebergwerk", bei der Kanarienvögel in Kohlebergwerke gebracht wurden, um die Bergleute zu schützen. 
```

2022-09-28 14:40 UTC, bcubk commented
@iamNoah1, deine Anmerkungen habe ich nun eingearbeitet. Die Commits habe ge-squashed. Es wäre Ready zum Mergen.

2022-09-29 10:07 UTC, iamNoah1 approved these changes

2022-09-29 10:07 UTC, iamNoah1 commented on content/de/canary_deployment.md
> +Durch Canary-Deployments können Unternehmen nachvollziehen, wie sich eine neue Software unter realen Bedingungen verhält, bevor ein Großteil des Datenverkehrs auf die neue Version umgestellt wird.
```suggestion
Durch Canary-Deployments können Unternehmen nachvollziehen, wie sich die neue Version einer Anwendung unter realen Bedingungen verhält, bevor ein Großteil des Datenverkehrs auf die neue Version umgestellt wird.
```

2022-09-29 10:08 UTC, iamNoah1 approved these changes
nice @bcubk danke für den Beitrag :)

2022-10-03 09:57 UTC, DaveVentura approved these changes

2022-10-03 09:57 UTC, DaveVentura commented on content/de/canary_deployment.md
> +Unabhängig davon, wie vollständig die Teststrategie ist, werden auf Produktivsystemen immer einige Fehler entdeckt. Die direkte Verlagerung des gesamten Datenverkehrs von einer aktuellen Version auf
```suggestion
Unabhängig davon, wie vollständig die Teststrategie ist, werden auf Produktivsystemen immer wieder einige Fehler entdeckt. Die direkte Verlagerung des gesamten Datenverkehrs von einer aktuellen Version auf eine neue, birgt ein hohes Risiko für Fehlerfälle.  
```

2022-10-03 10:16 UTC, iamNoah1 approved these changes

2022-10-03 10:16 UTC, iamNoah1 commented on content/de/canary_deployment.md
> +status: Feedback erwünscht
```suggestion
status: Completed
```

2022-10-03 10:16 UTC, merged