[hi] Localize content/en/kubernetes.md into Hi
cncf/glossary pull request #1248
Opened 2022-08-21 05:00 UTC by amolmote

Signed-off-by: amolmote <amolmote201@gmail.com>
Localize kubernetes.md
### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-02 16:44 UTC, sayantani11 requested changes
I have reviewed as far as I read. I will take a look at the rest soon.

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +कुबेरनेट्स, जिसे अक्सर K8s के रूप में संक्षिप्त किया जाता है, एक खुला स्रोत कंटेनर ऑर्केस्ट्रेटर है जो
Replace `खुला स्रोत` with `open source` but written in hindi

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +(ठीक आपके लैपटॉप के OS की तरह जो आपके ऐप्स को प्रबंधित करता है)।
replace with `ऐप्स को प्रबंध करता है`

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +कुबेरनेट्स एक [क्लस्टर] (/cluster/) में [नोड्स] (/nodes/) में कंटेनरों को शेड्यूल करता है।
nit: कुबेरनेट्स एक [क्लस्टर] (/cluster/) के [नोड्स] (/nodes/) में कंटेनरों

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +यह कई बुनियादी ढांचे के निर्माण को बंडल करता है, जिसे कभी-कभी "आदिम" कहा जाता है।
I would like to know from other reviewers if we should write `"आदिम"` or primitive but written in Hindi.
@anubha-v-ardhan @jayesh-srivastava @Garima-Negi

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +इस तरह से कि उन्हें अनुप्रयोगों में बनाया जा सकता है।
`बैलेंसर्स लोड करें, लगातार स्टोरेज, और अन्य एक साथ इस तरह से कि उन्हें अनुप्रयोगों में बनाया जा सकता है। `
load balancers, persistent storage are technical terms so we localise it not translate it.

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +इस तरह से कि उन्हें अनुप्रयोगों में बनाया जा सकता है।
`अनुप्रयोगों` here should be replaced by apps/applications

2022-09-02 16:44 UTC, sayantani11 commented on content/hi/kubernetes.md
> +इस तरह से कि उन्हें अनुप्रयोगों में बनाया जा सकता है।
`अनुप्रयोगों` here should be replaced by apps/applications

2022-09-08 09:06 UTC, amolmote commented on content/hi/kubernetes.md
> +कुबेरनेट्स एक [क्लस्टर] (/cluster/) में [नोड्स] (/nodes/) में कंटेनरों को शेड्यूल करता है।
```suggestion
कुबेरनेट्स एक [क्लस्टर] (/cluster/) के [नोड्स] (/nodes/) में कंटेनरों को शेड्यूल करता है। 
```

2022-09-18 11:09 UTC, closed without merging

2022-09-18 11:11 UTC, amolmote commented
its my bad @sayantani11, someone already opened PR of this. Thank you for your suggestions.