Create cloud-computing.md
cncf/glossary pull request #1250
Opened 2022-08-21 10:36 UTC by shivam-sharma7

- created a `cloud-computing.md` file and Localise in Hindi who prefer learning and understanding more in the Hindi language can understand better.
 
## issue: #1242

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-08-21 12:50 UTC, sarkartanmay393 commented
You can change the PR's name from `Create cloud-computing.md` to `[hi] Localize cloud-computing.md` or `[hi] Localize content/hi/cloud-computing.md`

2022-09-23 19:49 UTC, Garima-Negi commented
@shivam-sharma7 can you join us on slack : cloud-native.slack.com on the #glossary-localization-hindi channel?

2022-09-23 20:04 UTC, Garima-Negi requested changes
Hi @shivam-sharma7 the PR looks good, can you also fix the alignment of the sentences? they seem to be on extra newlines and discontinued. thanx!

2023-01-07 15:23 UTC, Garima-Negi approved these changes

2023-02-08 22:06 UTC, sayantani11 approved these changes
Looks good!

2023-03-13 16:49 UTC, jayesh-srivastava approved these changes

2023-04-22 06:52 UTC, anubha-v-ardhan requested changes
LGTM! Thankyou @shivam-sharma7 for your contributions.
Sorry for the extremely long time this review took

2023-04-22 06:52 UTC, anubha-v-ardhan commented on content/hi/cloud-computing.md
> +## समस्या यह संबोधित करता है
```suggestion
## समस्या
```

2023-04-22 06:52 UTC, anubha-v-ardhan commented on content/hi/cloud-computing.md
> +## यह कैसे मदद करता है ?
```suggestion
## समाधान
```

2023-04-22 06:52 UTC, anubha-v-ardhan commented on content/hi/cloud-computing.md
> +और वे [पैमाने](/ मापनीयता/) आवश्यकतानुसार और मांग पर कर सकते हैं। क्लाउड कंप्यूटिंग संगठनों को अपनी जरूरत के अनुसार अधिक या कम बुनियादी ढांचे को अपनाने की अनुमति देता है।
```suggestion
और वे आवश्यकतानुसार [स्केल](/scalability/) कर सकते हैं। क्लाउड कंप्यूटिंग संगठनों को अपनी जरूरत के अनुसार अधिक या कम बुनियादी ढांचे को अपनाने की अनुमति देता है।
```

2023-04-22 16:06 UTC, shivam-sharma7 commented
> LGTM! Thankyou @shivam-sharma7 for your contributions. Sorry for the extremely long time this review took

No problem! 🙂

2023-04-23 18:39 UTC, anubha-v-ardhan approved these changes

2023-06-25 13:54 UTC, merged

2023-06-25 13:54 UTC, anubha-v-ardhan commented
Thank You @shivam-sharma7