Localize service-mesh fr
cncf/glossary pull request #1272
Opened 2022-08-27 16:55 UTC by Krast76

Fix #1262 

Localize content/fr/service-mesh.md to fr.

2022-09-11 15:12 UTC, Krast76 commented on content/fr/service-mesh.md
> +réglementaires, fournir des métriques pour les équipes opérationnelles fournir des informations détaillées à propos du trafic
J'ai juste remplacé le "ou" par un "et", car dans les fait ça peu être les deux :)

2022-09-11 15:18 UTC, Krast76 commented
> De plus je suis pour changer le mot service mesh par maillage de services. Etant donné qu'il s'agit un terme on pourrait peut etre citer le terme anglais et la traduction FR.

Je n'appelle jamais ça "maillage de service" dans mon quotidien. Néanmoins, dans la traduction  Coréenne (ko) c'est ce qu'ils ont fait, reparlons en à notre prochain point

2022-09-28 16:21 UTC, huats commented
> > De plus je suis pour changer le mot service mesh par maillage de services. Etant donné qu'il s'agit un terme on pourrait peut etre citer le terme anglais et la traduction FR.
> 
> Je n'appelle jamais ça "maillage de service" dans mon quotidien. Néanmoins, dans la traduction Coréenne (ko) c'est ce qu'ils ont fait, reparlons en à notre prochain point

Par contre "des services maillés" oui moi je l'utilise souvent

2022-10-13 21:37 UTC, fydrah requested changes

2022-10-13 21:37 UTC, fydrah commented on content/fr/service-mesh.md
> +Les services mesh répondent à cette problématique en gérant le trafic (i.e., la communication) entre les services et ajoute de la
"ajoutent"

2022-10-13 21:37 UTC, fydrah commented on content/fr/service-mesh.md
> +Cela signifie que beaucoup de trafic va faire des aller et retour sur le réseau.
"faire des aller et retour" --> "transiter"

2022-10-13 21:37 UTC, fydrah commented on content/fr/service-mesh.md
> +Par dessus tout cela, chaque application peut avoir besoin de chiffrer ses communications pour des contraintes
"Par dessus tout cela,..." --> "De plus,.." ou "En supplément,..."

2022-10-13 21:37 UTC, fydrah commented on content/fr/service-mesh.md
> +devenant une potentielle source de bug, voir une dette technique.
"...voir de dette technique."

2022-11-01 21:26 UTC, huats commented on content/fr/service-mesh.md
> +devenant une potentielle source de bug, voir une dette technique.
"devenant une potentielle source de bug, voir de dette technique" moi ca ne me choque pas. Sinon tu peux dire "devenant une potentielle source de bug ou de dette technique"
Et pense a signer ton commit

2023-01-25 04:40 UTC, fydrah requested changes

2023-01-25 04:40 UTC, fydrah commented on content/fr/service-mesh.md
> +Après avoir migré vers une architecture microservices. Les ingénieurs doivent gérer une centaine
A comma between "[...] microservices. Les ingénieurs [...]" instead of a dot

2023-01-31 17:43 UTC, fydrah approved these changes

2023-02-05 15:57 UTC, huats approved these changes
LGTM

2023-02-05 19:13 UTC, merged