Localize cloud-native apps and tech to fr
cncf/glossary pull request #1273
Opened 2022-08-28 15:02 UTC by Krast76

Fix #1260 and #1258.

@fydrah @huats This PR needs a special focus, because I translated some important words (such as scale etc).
I think we have to review it together at our next meeting.

2022-08-31 16:22 UTC, fydrah commented on content/fr/cloud-native-tech.md
> +Les technologies Cloud native, aussi référencées comme ensemble des technologies cloud native, sont les technologies
"ensemble des technologies cloud natives" --> "comme la pile des technologies cloud natives"

2022-08-31 16:36 UTC, fydrah commented on content/fr/cloud-native-apps.md
> +Aujourd'hui, les applications Cloud native incluent les applications qui fonctionnent dans le centre de données des fournisseurs de cloud ainsi que les applications qui tournent sur des plateformes h
"tournent sur des plateformes hébergées dans des centres de données traditionnelles." --> "tournent sur des plateformes hébergées dans les centres de données internes aux entreprises."

2022-08-31 16:36 UTC, fydrah commented on content/fr/cloud-native-tech.md
> +title: Technologies Cloud Native
'Natives'

2022-08-31 16:37 UTC, fydrah commented on content/fr/cloud-native-tech.md
> +Les technologies Cloud native, aussi référencées comme ensemble des technologies cloud native, sont les technologies
'Natives'

2022-08-31 16:37 UTC, fydrah commented on content/fr/cloud-native-tech.md
> +en tant que groupe, les technologies cloud native permettent des systèmes faiblement couplés qui sont résilient, gérables et observable.
'natives'

2022-10-05 16:09 UTC, Krast76 commented
Well spotted @huats, fixed.

2022-10-13 16:08 UTC, fydrah requested changes

2022-12-01 17:21 UTC, huats requested changes

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-apps.md
> +Ces applications s'intègrent facilement avec leurs architectures cloud respective, en tirant avantage des ressources proposées par le Cloud et de leur capacité de [mise à l'échelle](/scalability/).
respectives

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-apps.md
> +Aujourd'hui, les applications Cloud native incluent les applications qui fonctionnent dans le centre de données des fournisseurs de cloud ainsi que les applications qui tournent sur des plateformes h
Native

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-apps.md
> +Les applications Cloud Native sont résilientes, elles sont manipulables et tirent profit de l'ensemble des services Cloud dans lequel elles
gérables au lieu de manipulables

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-apps.md
> +Les applications Cloud Native sont résilientes, elles sont manipulables et tirent profit de l'ensemble des services Cloud dans lequel elles
"dans lequel elles" -> "où elles"

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-tech.md
> +Elles sont conçues dès le départ pour exploiter les capacités du cloud computings ainsi que des conteneurs, du service meshes, des micro-services. Les infrastructures immuables illustrent cette appro
enlever le s à computings

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-tech.md
> +Elles sont conçues dès le départ pour exploiter les capacités du cloud computings ainsi que des conteneurs, du service meshes, des micro-services. Les infrastructures immuables illustrent cette appro
"du service meshes" -> "des services meshes"

2022-12-01 17:21 UTC, huats commented on content/fr/cloud-native-tech.md
> +en tant que groupe, les technologies cloud natives permettent de créer des systèmes faiblement co uplés qui sont résilients, gérabels et observables..
"co uplés" -> "couplés"
"gérabels" -> "gérables"

2023-01-31 17:55 UTC, fydrah reviewed
waiting for changes related to huats review

2023-02-05 15:59 UTC, huats approved these changes

2023-02-05 16:45 UTC, fydrah requested changes

2023-02-05 16:45 UTC, fydrah commented on content/fr/cloud-native-tech.md
> +title: Technologies Cloud Native
@Krast76 missing that one I think, otherwise it looks good

2023-02-15 17:06 UTC, fydrah requested changes

2023-02-15 17:06 UTC, fydrah commented on content/fr/cloud-native-apps.md
> +title: Applications Cloud Native
Missing 's' to Natives

2023-02-15 17:06 UTC, fydrah commented on content/fr/cloud-native-apps.md
> +Les applications Cloud Native sont des applications conçues pour tirer avantage des innovations du [cloud computing](/cloud-computing/).
Missing 's' to Natives

2023-02-22 17:17 UTC, fydrah approved these changes
All comments resolved, LGTM

2023-02-22 17:17 UTC, merged