[it] Localizzazione termine Loosely coupled architecture
cncf/glossary pull request #1283
Opened 2022-09-01 08:29 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added Loosely coupled architecture Ialian localization

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-10-24 13:29 UTC, annalisag-spark requested changes

2022-10-24 13:29 UTC, annalisag-spark commented on content/it/loosely-coupled-architecture.md
> +Un'architettura loosely coupled (accoppiata in modo leggero) è uno stile architetturale nel quale i singoli componenti di un'applicazione sono costruiti in modo indipendente l'uno dall'altro (il para
```suggestion
Un'architettura loosely coupled (debolmente accoppiata) è uno stile architetturale nel quale i singoli componenti di un'applicazione sono costruiti in modo indipendente l'uno dall'altro (si tratta del paradigma opposto a quello delle [architetture tightly coupled](/it/tightly-coupled-architectures/), cioè strettamente accoppiate).
```

2022-10-24 14:37 UTC, annalisag-spark approved these changes

2022-10-28 22:00 UTC, fsbaraglia approved these changes

2022-10-28 22:00 UTC, merged