[hi] Localize content/en/virtual-machine.md
cncf/glossary pull request #1287
Opened 2022-09-02 08:16 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>
Fixes #1237
### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-07 09:46 UTC, taniaduggal commented
@jayesh-srivastava

2022-09-12 08:42 UTC, taniaduggal commented
@anubha-v-ardhan

2022-09-23 19:34 UTC, Garima-Negi requested changes

2022-09-23 19:34 UTC, Garima-Negi commented on content/hi/virtual-machine.md
> +एक वर्चुअल मशीन (VM) एक कंप्यूटर और उसका ऑपरेटिंग सिस्टम है जो विशिष्ट हार्डवेयर से नहीं जुड़ा होता है। VMs को एक भौतिक कंप्यूटर को कई वर्चुअल मशीनों में विभाजित करने के लिए [वर्चुअलाइजेशन](/virtuali
Theres a typo in `infrastructure`

2022-09-23 19:34 UTC, Garima-Negi commented on content/hi/virtual-machine.md
> +एक वर्चुअल मशीन (VM) एक कंप्यूटर और उसका ऑपरेटिंग सिस्टम है जो विशिष्ट हार्डवेयर से नहीं जुड़ा होता है। VMs को एक भौतिक कंप्यूटर को कई वर्चुअल मशीनों में विभाजित करने के लिए [वर्चुअलाइजेशन](/virtuali
rest all LGTM!

2023-01-07 15:34 UTC, Garima-Negi approved these changes

2023-01-25 10:13 UTC, seokho-son commented
Whereas there are some options to resolve the failure on the Pull Request Labeler action,
I am going to force merge this PR, considering #1582 :)

2023-01-25 10:13 UTC, seokho-son approved these changes

2023-01-25 10:13 UTC, merged