[es] localize 'Containerization'
cncf/glossary pull request #1288
Opened 2022-09-02 15:44 UTC by RedwineOS

### Describe your changes
Localization in spanish for containerization.

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #577 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-11 15:30 UTC, bconfiden2 reviewed
According to [build error](https://github.com/cncf/glossary/runs/8209221669?check_suite_focus=true), some words such as `Container` and `Initiative` are English, and the other words such as `hipervisor` and `reprogrmados` are Spanish.
So I wonder why these errors occur.
Should these words be in file `.wordlist.txt` ??
I'm curious about how `spellcheck.yml`-Spanish l10n team's CI-works!! :pleading_face: :pleading_face:

2022-09-11 16:38 UTC, RedwineOS commented
> According to [build error](https://github.com/cncf/glossary/runs/8209221669?check_suite_focus=true), some words such as `Container` and `Initiative` are English, and the other words such as `hipervisor` and `reprogrmados` are Spanish. So I wonder why these errors occur. Should these words be in file `.wordlist.txt` ?? I'm curious about how `spellcheck.yml`-Spanish l10n team's CI-works!! 🥺 🥺

Those words have to be present in the `.wordlist` file so that the job does not fail.

2022-09-27 15:51 UTC, ramrodo commented
Colocar la opción `-f` para que sea incase sensitive:

```bash
sort -f -o content/es/.wordlist.txt content/es/.wordlist.txt
```

2022-10-04 14:30 UTC, electrocucaracha requested changes

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  canary
Dado que la lista de palabras prioriza las mayúsculas y para evitar tener duplicados, sugiero
```suggestion
Canary
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  deployment
ditto: línea 29
```suggestion
Deployment
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +Foster
```suggestion
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  git
ditto: línea 29
```suggestion
Git
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  github
ditto: línea 29
```suggestion
GitHub
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +YAML
```suggestion
```

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/containerization.md
> +Antes de que los contenedores se convirtieran en prevalentes, las organizaciones dependían de máquinas virtuales para orquestar múltiples aplicaciones en una única computadora. Las máquinas virtuales
```suggestion
Antes de que los contenedores se convirtieran relevantes, las organizaciones dependían de máquinas virtuales para orquestar múltiples aplicaciones en una única computadora. Las máquinas virtuales son significativamente más pesadas que los contenedores y requieren de un hipervisor para su funcionamiento. Debido al almacenamiento, copias de seguridad y transferencia de estas plantillas de máquinas virtuales, la creación de las mismas también se trata de un proceso lento. Adicionalmente, las máquinas virtuales pueden sufrir variaciones en la configuración, lo cuál contradice el principio de inmutabilidad.
```
Si esta sugerencia es aceptada, será necesario eliminar `prevalentes` del wordlist

2022-10-04 14:30 UTC, electrocucaracha commented on content/es/containerization.md
> +La contenerización es el proceso que consiste en empaquetar una aplicación y sus dependencias en una [imagen de contenedor](./container-image.md). La construcción del contenedor requiere del seguimie
```suggestion
La contenerización es el proceso que consiste en empaquetar una aplicación y sus dependencias en una [imagen de contenedor](/es/container-image.md). La construcción del contenedor requiere del seguimiento del estándar [Open Container Initiative](https://opencontainers.org) (OCI). Mientras la salida de este proceso sea un contenedor de imagen que se adhiera a dicho estándar, la herramienta de contenerización usada no es relevante.
```

2022-10-04 14:35 UTC, electrocucaracha commented
> According to [build error](https://github.com/cncf/glossary/runs/8209221669?check_suite_focus=true), some words such as `Container` and `Initiative` are English, and the other words such as `hipervisor` and `reprogrmados` are Spanish. So I wonder why these errors occur. Should these words be in file `.wordlist.txt` ?? I'm curious about how `spellcheck.yml`-Spanish l10n team's CI-works!! 🥺 🥺

@bconfiden2 those English word are exceptions that we have to add into our [word list](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt), [this](https://github.com/cncf/glossary/blob/dev-es/content/es/.spellcheck.yml#L21) is our configuration file which uses Aspell Spanish dictionary on [any](https://github.com/cncf/glossary/blob/dev-es/.github/workflows/es-spellcheck.yml) PR to `dev-es`

2022-10-04 15:44 UTC, ramrodo commented on content/es/containerization.md
> +Antes de que los contenedores se convirtieran en prevalentes, las organizaciones dependían de máquinas virtuales para orquestar múltiples aplicaciones en una única computadora. Las máquinas virtuales
Creo que debería de ser: _Antes de que los contenedores se convirtieran **en relevantes**_:

```suggestion
Antes de que los contenedores se convirtieran en relevantes, las organizaciones dependían de máquinas virtuales para orquestar múltiples aplicaciones en una única computadora. Las máquinas virtuales son significativamente más pesadas que los contenedores y requieren de un hipervisor para su funcionamiento. Debido al almacenamiento, copias de seguridad y transferencia de estas plantillas de máquinas virtuales, la creación de las mismas también se trata de un proceso lento. Adicionalmente, las máquinas virtuales pueden sufrir variaciones en la configuración, lo cuál contradice el principio de inmutabilidad.
```

2022-10-10 22:53 UTC, krol3 reviewed
LGTM small changes

2022-10-10 22:53 UTC, krol3 commented on content/es/containerization.md
> +Al contrario que con las máquinas virtuales tradicionales, las imágenes de contenedor son ligeras y el proceso de contenerización requiere de una lista exhaustiva de dependencias. Este archivo puede
```suggestion
Al contrario que con las máquinas virtuales tradicionales, las imágenes de contenedor son ligeras y el proceso de contenerización requiere de una lista exhaustiva de dependencias. Este archivo puede ser versionado y el proceso de construcción automatizado, permitiendo a una organización centrarse en otras prioridades mientras que los procesos automatizados se encargan de la construcción. Una imagen de contenedor se almacena junto a un identificador único que está vinculado a un contenido y configuración exacta. Conforme los contenedores son programados y reprogramados siempre van a ser revertidos a su estado inicial, lo cuál elimina variaciones en la configuración.
```

2022-10-11 15:18 UTC, electrocucaracha approved these changes

2022-10-11 15:48 UTC, merged