Traduction de container.md
cncf/glossary pull request #1302
Opened 2022-09-07 19:11 UTC by huats

Signed-off-by: Christophe Sauthier <christophe.sauthier@gmail.com>

### Describe your changes

This PR localizes `container.md` concept to French

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1261 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ X ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ X ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-11 15:28 UTC, Krast76 commented on content/fr/container.md
> +tout ce ceci pour faire fonctionner une simple application.
"tout ce ceci" -> "tout cela"

2022-09-11 15:43 UTC, Krast76 commented on content/fr/container.md
> +répartissant la surcharge en ressources liées qu système d'exploitation et permettant un usage efficace de la machine physique.
"qu" -> "au".

Ici on parle de "surcharge de ressource" dans le sens "les ressources disponibles" ? Je me demande si "répartissant les ressources disponibles du système d'exploitation et..."

2022-10-13 21:31 UTC, fydrah requested changes

2022-10-13 21:31 UTC, fydrah commented on content/fr/container.md
> +Etant donné que les conteneurs partagent le même système d'exploitation, les processus peuvent être considérés moins sécurisés que leurs alternatives.
"Étant donné..."

2022-10-13 21:31 UTC, fydrah commented on content/fr/container.md
> +Pour garantir les ressources, les administrateurs doivent contraindre et limiter l'utilisation de la mémoire et du CPU afin de ne pas faire baisser les performances des autres applications.
"...de ne pas 'impacter' les performances..." me paraîtrait plus logique.

2022-10-19 12:58 UTC, huats commented on content/fr/_TEMPLATE.md
>  Quelques lignes à propos du problème qu'il adresse.
C'est déjà changé j'ai l'impression

2022-11-26 15:03 UTC, Krast76 approved these changes

2023-01-25 04:48 UTC, fydrah approved these changes

2023-01-25 04:52 UTC, merged