DevsecOps_translated
cncf/glossary pull request #1305
Opened 2022-09-09 09:40 UTC by octonawish-akcodes

### Describe your changes
Translated Devsecops in hindi

### Related issue number or link (ex: `resolves #issue-number`)
Closes #1183 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-14 20:38 UTC, Garima-Negi requested changes

2022-09-14 20:38 UTC, Garima-Negi commented on content/hi/devsecops.md
> +सुरक्षा दुर्घटनाओं और संबंधित लागतों को कम करें।
The alignment of sentences can be fixed. The original paragraph has sentences in continuation, please fix the extra new line and spaces.

2022-09-14 20:38 UTC, Garima-Negi commented on content/hi/devsecops.md
> +category: concept
Please use अवधारणा in place of concept

2022-09-14 20:38 UTC, Garima-Negi commented on content/hi/devsecops.md
> +डेवलपर और परिचालन कार्यप्रवाह में न्यूनतम या बिना किसी व्यवधान के।
```suggestion
यह सुरक्षा प्राथमिकताओं को शामिल करने के लिए डेवलपर और परिचालन कार्यप्रवाह में न्यूनतम या बिना किसी व्यवधान के, [DevOps](/devops/) दृष्टिकोण का विस्तार करता है।
```

2022-10-03 15:40 UTC, octonawish-akcodes commented
check now @Garima-Negi

2023-01-07 15:32 UTC, Garima-Negi requested changes

2023-01-07 15:32 UTC, Garima-Negi commented on content/hi/devsecops.md
> +## समस्या यह संबोधित करता है
only ## समस्या is to be used here

2023-01-07 15:32 UTC, Garima-Negi commented on content/hi/devsecops.md
> +## यह कैसे मदद करता है
## समाधान should be used here

2023-01-11 14:08 UTC, octonawish-akcodes commented on content/hi/devsecops.md
> +## यह कैसे मदद करता है
done

2023-04-17 21:24 UTC, Garima-Negi approved these changes

2023-04-18 02:49 UTC, seokho-son commented
Hi @octonawish-akcodes 
Thank you for your contribution ! :) 
Please make sure to check the boxes in the checklist yourself. This is part of the template to obtain confirmation from the contributor.
![image](https://user-images.githubusercontent.com/5966944/232656470-f698eb73-f7e4-40c7-9599-6e023d2c7eee.png)

(Hello Hindi team, @Garima-Negi @sayantani11 , could you please guide contributors to complete the checklist before a reviewer starts the review? Thank you!)

2023-04-18 02:59 UTC, octonawish-akcodes commented
> Hi @octonawish-akcodes Thank you for your contribution ! :) Please make sure to check the boxes in the checklist yourself. This is part of the template to obtain confirmation from the contributor. ![image](https://user-images.githubusercontent.com/5966944/232656470-f698eb73-f7e4-40c7-9599-6e023d2c7eee.png)
> 
> (Hello Hindi team, @Garima-Negi @sayantani11 , could you please guide contributors to complete the checklist before a reviewer starts the review? Thank you!)

Done

2023-04-22 06:53 UTC, anubha-v-ardhan approved these changes

2023-04-22 07:05 UTC, anubha-v-ardhan requested changes

2023-04-22 07:05 UTC, anubha-v-ardhan commented on content/hi/devsecops.md
> +DevOps प्रथाओं में [निरंतर एकीकरण] (/ निरंतर-एकीकरण /) और [निरंतर परिनियोजन] (/ निरंतर-वितरण /) शामिल हैं
```suggestion
DevOps प्रथाओं में [निरंतर एकीकरण](/hi/continuous-integration//) और [निरंतर डिलीवरी](/hi/continuous-delivery/) शामिल हैं
```

2023-06-25 13:58 UTC, merged

2023-06-25 13:59 UTC, anubha-v-ardhan commented
Thank you @octonawish-akcodes