Localized `content/bn/cloud-native-apps.md`
cncf/glossary pull request #1316
Opened 2022-09-14 16:32 UTC by PratikDey

Signed-off-by: [Pratik Dey](pratikdey.pro@gmail.com)
Localizes `content/bn/cloud-native-apps.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

2022-09-14 17:52 UTC, mitul3737 requested changes

2022-09-14 17:52 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +দৃঢ় অটোমেশনের(automation) সাথে মিলিত, তারা প্রকৌশলীদেরকে(engineers) ন্যূনতম পরিশ্রমের সাথে ঘন ঘন এবং অনুমানযোগ্যভাবে উচ্চ-প্রভাবিত পরিবর্তন করতে দেয়।
Can you kindly make a more suitable sentence from this?

2022-09-16 17:49 UTC, mitul3737 requested changes

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +বিভিন্ন ক্লাউড পরিষেবাগুলি উচ্চ মাত্রার(high degree) [পর্যবেক্ষণযোগ্যতা](observability)(/observability/) সক্ষম করে,
```suggestion
বিভিন্ন ক্লাউড পরিষেবাগুলি উচ্চ মাত্রার(high degree) [পর্যবেক্ষণযোগ্যতা](observability)(/bn/observability/) সক্ষম ,
```

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +সমস্যাগুলি বৃদ্ধির আগে ব্যবহারকারীদের সনাক্ত করতে এবং সমাধান করতে সক্ষম করে।
```suggestion
সমস্যাগুলি বৃদ্ধির আগে ব্যবহারকারীদের সনাক্ত করতে এবং সমাধান করতে সক্ষম ।
```

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +দৃঢ় অটোমেশনের(automation) সাথে মিলিত হয়ে তারা ইঞ্জিনিয়ারদের(engineer) ন্যূনতম পরিশ্রমের সাথে ঘন ঘন এবং অনুমানযোগ্যভাবে(predictably) উচ্চ-প্রভাবিত(high-impact) পরিবর্তন করতে দেয়।
I don't find any meaning in this sentence in Bengali. It would be great if you could make a suitable sentence from English.

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +ক্লাউড নেটিভ অ্যাপ্লিকেশনগুলি বিশেষভাবে [ক্লাউড কম্পিউটিং](/cloud-computing/)-এ উদ্ভাবনের সুবিধা নেওয়ার জন্য ডিজাইন করা হয়েছে।
All the links should start with `/bn/`

```suggestion
ক্লাউড নেটিভ অ্যাপ্লিকেশনগুলি বিশেষভাবে [ক্লাউড কম্পিউটিং](/bn/cloud-computing/)-এ উদ্ভাবনের সুবিধা নেওয়ার জন্য ডিজাইন করা হয়েছে।
```

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +এই অ্যাপ্লিকেশনগুলি তাদের নিজ নিজ ক্লাউড আর্কিটেকচারের সাথে সহজেই একত্রিত হয়, ক্লাউডের সংস্থান এবং [স্কেলিং](/scalability/) ক্ষমতার সুবিধা নিয়ে থাকে।
```suggestion
এই অ্যাপ্লিকেশনগুলি তাদের নিজ নিজ ক্লাউড আর্কিটেকচারের সাথে সহজেই একত্রিত হয়, ক্লাউডের সংস্থান এবং [স্কেলিং](/bn/scalability/) ক্ষমতার সুবিধা নিয়ে থাকে।
```

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +প্রতিটি ডেটাসেন্টারের(data-center) পরিষেবা ছিল যা নির্দিষ্ট পরিবেশে অ্যাপ্লিকেশনগুলিকে [শক্তভাবে সংযুক্ত](/tightly-coupled-architectures/) করে,
```suggestion
প্রতিটি ডেটাসেন্টারের(data-center) পরিষেবা ছিল যা নির্দিষ্ট পরিবেশে অ্যাপ্লিকেশনগুলিকে [শক্তভাবে সংযুক্ত](/bn/tightly-coupled-architectures/) করে,
```

2022-09-16 17:49 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +প্রায়শই [ভার্চুয়াল মেশিন](/virtual-machine/) এবং পরিষেবার মতো অবকাঠামোর(infrastructure) জন্য ম্যানুয়াল প্রভিশনিংয়ের(manual provisioning) উপর অনেক বেশি নির্ভর করে।
```suggestion
প্রায়শই [ভার্চুয়াল মেশিন](/bn/virtual-machine/) এবং পরিষেবার মতো অবকাঠামোর(infrastructure) জন্য ম্যানুয়াল প্রভিশনিংয়ের(manual provisioning) উপর অনেক বেশি নির্ভর করে।
```

2022-09-18 10:30 UTC, mitul3737 commented on content/bn/cloud-native-apps.md
> +দৃঢ় অটোমেশনের(automation) সাথে মিলিত হয়ে তারা ইঞ্জিনিয়ারদের(engineer) ন্যূনতম পরিশ্রমের সাথে ঘন ঘন এবং অনুমানযোগ্যভাবে(predictably) উচ্চ-প্রভাবিত(high-impact) পরিবর্তন করতে দেয়।
Yes, seems good.

2022-09-20 05:38 UTC, mitul3737 approved these changes
LGTM

2022-09-27 03:03 UTC, Imtiaz1234 approved these changes
lgtm

2022-09-27 03:04 UTC, merged