[it] Localizzazione termine idempotence
cncf/glossary pull request #1321
Opened 2022-09-16 15:07 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added idempotence italian localization

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-09-19 12:29 UTC, annalisag-spark requested changes

2022-09-19 12:29 UTC, annalisag-spark commented on content/it/idempotence.md
> +Se i parametri sono i medesimi, un'operazione idempotente non avrà ripercussioni sull'applicazione chiamata.
Giusto per pignoleria, utilizzerei "gli stessi" al posto di "medesimi", solo per evitare l'uso di quest'ultimo aggettivo due volte a distanza di una manciata di parole. Decidi tu :)

2022-09-19 14:06 UTC, ugho16 commented on content/it/idempotence.md
> +Se i parametri sono i medesimi, un'operazione idempotente non avrà ripercussioni sull'applicazione chiamata.
Giusto, faccio subito!

2022-09-19 14:06 UTC, ugho16 commented on content/it/idempotence.md
> +Se i parametri sono i medesimi, un'operazione idempotente non avrà ripercussioni sull'applicazione chiamata.
```suggestion
Se i parametri sono gli stessi, un'operazione idempotente non avrà ripercussioni sull'applicazione chiamata.
```

2022-09-19 14:17 UTC, annalisag-spark approved these changes

2022-10-28 22:05 UTC, fsbaraglia approved these changes

2022-10-29 19:23 UTC, merged