[it] Localizzazione termine Event-Driven Architecture
cncf/glossary pull request #1332
Opened 2022-09-23 14:29 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added Event-Driven architecture Italian localization.

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-10-24 13:24 UTC, annalisag-spark requested changes

2022-10-24 13:24 UTC, annalisag-spark commented on content/it/event-driven-architecture.md
> +Un'architettura ad eventi è un'architettura software che promuove la creazione, la processazione e la consumazione di eventi.
```suggestion
Un'architettura basati sugli eventi è un paradigma di progettazione software che promuove la creazione, l'elaborazione e il consumo di eventi.
```

2022-10-24 13:24 UTC, annalisag-spark commented on content/it/event-driven-architecture.md
> +Le architetture ad eventi costituiscono un fulcro centrale per tutti gli eventi (ad esempio Kafka).
```suggestion
Le architetture ad eventi ne costituiscono un fulcro centrale (ad esempio Kafka).
```

2022-10-24 13:24 UTC, annalisag-spark commented on content/it/event-driven-architecture.md
> +Si possono definire i produttori degli eventi (origine) e i consumatori (destinatari), e il fulcro centrale garantisce il flusso degli eventi.
```suggestion
All'interno di questo tipo di architettura, infatti, si possono definire i produttori degli eventi (origine) e i loro consumatori (destinatari), e il fulcro centrale ne garantisce il flusso corretto.
```

2022-10-24 14:07 UTC, ugho16 commented on content/it/event-driven-architecture.md
> +Un'architettura basati sugli eventi è un paradigma di progettazione software che promuove la creazione, l'elaborazione e il consumo di eventi.
``
```suggestion
Un'architettura basata sugli eventi è un paradigma di progettazione software che promuove la creazione, l'elaborazione e il consumo di eventi.
```

2022-10-24 14:36 UTC, annalisag-spark approved these changes

2022-10-28 22:01 UTC, fsbaraglia approved these changes

2022-10-28 22:01 UTC, merged