[it] Localizzazione termine Client-Server Architecture
cncf/glossary pull request #1335
Opened 2022-09-30 09:18 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added client-server architecture Italian localization

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-10-24 13:18 UTC, annalisag-spark requested changes

2022-10-24 13:18 UTC, annalisag-spark commented on content/it/client-server-architecture.md
> +Per esempio, un programma di elaborazione di testi come Microsoft Word può essere installato ed eseguito interamente sul tuo computer.
```suggestion
Per esempio, un programma di elaborazione di testi come Microsoft Word può essere installato ed eseguito interamente sul computer di ogni singolo utente.
```

2022-10-24 13:18 UTC, annalisag-spark commented on content/it/client-server-architecture.md
> +Questo tipo di architettura è in opposizione alle applicazioni self-contained (come le applicazioni desktop) che eseguono tutto il lavoro da un unico posto.
```suggestion
Questo tipo di architettura è in opposizione alle applicazioni self-contained (ossia autonome, come le applicazioni desktop per esempio) che eseguono tutto il lavoro da un unico posto.
```

2022-10-24 13:18 UTC, annalisag-spark commented on content/it/client-server-architecture.md
> +Un'architettura client-server risolve una grande sfida posta dalle applicazioni self-contained: gli aggiornamenti regolari. Nel caso di un'applicazione self-contained, per ogni aggiornamento gli uten
```suggestion
Un'architettura client-server risolve una grande sfida posta dalle applicazioni self-contained: gli aggiornamenti regolari. Nel caso di un'applicazione self-contained, per ogni aggiornamento gli utenti dovrebbero scaricare e installare l'ultima versione. Immagina di dover scaricare sul tuo computer l'intero catalogo dei prodotti di Amazon per poterlo navigare!
```

2022-10-24 13:18 UTC, annalisag-spark commented on content/it/client-server-architecture.md
> +Conservare i dati su un server permette a più client di vedere e condividere gli stessi dati. Considera la differenza di utilizzo di un programma di elaborazione di testi al confronto con un tradizio
```suggestion
Conservare i dati su un server permette a più client di vedere e condividere gli stessi dati. Consideriamo la differenza di utilizzo di un programma di elaborazione di testi al confronto con un tradizionale programma di elaborazione di testi offline. Nel primo i file esistono solo lato server e possono essere condivisi con altri utenti che possono semplicemente scaricarli dal server. Nel mondo legacy, i file dovevano essere copiati su dispositivi rimovibili (come i floppy disk) e condivisi con i singoli utenti.
```

2022-10-24 14:34 UTC, annalisag-spark approved these changes

2022-10-28 22:02 UTC, fsbaraglia approved these changes

2022-10-28 22:02 UTC, merged