[DE] Localization of Blue Green Deployment
cncf/glossary pull request #1342
Opened 2022-10-04 10:16 UTC by iamNoah1

### Describe your changes
Localizing Blue Green Deployment 

### Related issue number or link (ex: `resolves #issue-number`)
https://github.com/cncf/glossary/issues/511 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-21 10:46 UTC, DaveVentura requested changes

2022-10-21 10:46 UTC, DaveVentura commented on content/de/blue-green-deployment.md
> +die Inkompatibilit einzelner Komponenten zur Folge haben kann.
```suggestion
die Inkompatibilität einzelner Komponenten zur Folge haben kann. 
```

2022-10-21 10:46 UTC, DaveVentura commented on content/de/blue-green-deployment.md
> +Für solche Fälle muss die gesamte Anwendung gleichzeit aktualisiert werden.
```suggestion
Für solche Fälle müssen alle Komponente der Anwendung gleichzeitig aktualisiert werden. 
```

2022-10-21 10:46 UTC, DaveVentura commented on content/de/blue-green-deployment.md
> +Das Aktualisieren einzelner Komponenten einer Anwendung um deren kompletten Ausfall zu vermeiden,
```suggestion
Das Aktualisieren einzelner Komponenten einer Anwendung, um deren kompletten Ausfall zu vermeiden, 
```

2022-10-21 10:46 UTC, DaveVentura commented on content/de/blue-green-deployment.md
> +In der Regel bezieht sich der Begriff Blue-Green-Deployment auf die Aktualisierung einer gesamten Anwendung,
```suggestion
In der Regel bezieht sich der Begriff Blue-Green-Deployment auf die Aktualisierung einer gesamten Anwendung
```

2022-10-21 21:21 UTC, iamNoah1 commented
@DaveVentura hab die Änderungen eingebaut

2022-10-29 14:17 UTC, bcubk commented on content/de/blue-green-deployment.md
> +funktioniert leider nicht immer. Das liegt daran, dass gewisse Aktualisierung,
_Das liegt daran, dass gewisse Aktualisierung,_ Einzahl/Mehrzahl passt nicht. Vorschlag: _dass eine Aktualisierung die Inkompatibilität ..._

2022-10-29 14:18 UTC, bcubk commented
@iamNoah1, mir sind noch zwei Sachen aufgefallen. Sonst siehts ganz gut aus 👍

2022-11-08 20:28 UTC, iamNoah1 commented on content/de/blue-green-deployment.md
> +Das Aktualisieren einzelner Komponenten einer Anwendung, um deren kompletten Ausfall zu vermeiden,
@bcubk bezieht sich auf die Anwendung, aber ich passe es gerne an :)

2022-11-08 20:29 UTC, iamNoah1 commented on content/de/blue-green-deployment.md
> +funktioniert leider nicht immer. Das liegt daran, dass gewisse Aktualisierung,
passt :) danke @bcubk

2022-11-08 20:30 UTC, iamNoah1 commented
@bcubk hab deine Vorschläge eingebaut.

2022-11-09 06:57 UTC, DaveVentura approved these changes

2022-11-09 14:00 UTC, merged