Dev bn
cncf/glossary pull request #1363
Opened 2022-10-11 18:02 UTC by PratikDey

Signed-off-by: [Pratik Dey](pratikdey.pro@gmail.com)
Localizes `content/bn/containers-as-a-service.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

2022-10-11 22:26 UTC, mitul3737 requested changes

2022-10-11 22:26 UTC, mitul3737 commented on content/bn/containers-as-a-service.md
> +CaaS ছাড়া, সফ্টওয়্যার ডেভেলপমেন্ট দলগুলিকে স্থাপন, পরিচালনা এবং নিরীক্ষণ করতে হবে
Kindly form a suitable sentence here.

2022-10-11 22:26 UTC, mitul3737 commented on content/bn/containers-as-a-service.md
> +CaaS প্রদানকারীরা একটি ফ্রেমওয়ার্ক বা অর্কেস্ট্রেশন প্ল্যাটফর্ম অফার করে যা
Kindly form some meaning ful sentence from line 14-19

2022-10-11 22:26 UTC, mitul3737 commented on content/bn/containers-as-a-service.md
> +যেখানে কন্টেইনারগুলি একটি ধারাবাহিক স্থাপনার লক্ষ্য নিশ্চিত করে,
Kindly form a suitable sentence from line 33-35

2022-10-20 14:28 UTC, Mouly22 approved these changes

2022-10-20 21:46 UTC, mitul3737 approved these changes
lgtm

2022-10-20 21:46 UTC, merged