[it] Localizzazione termine Debugging
cncf/glossary pull request #1378
Opened 2022-10-13 13:34 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added Debugging Italian localization

### Related issue number or link (ex: `resolves #issue-number`)
NA

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-24 13:10 UTC, annalisag-spark requested changes

2022-10-24 13:10 UTC, annalisag-spark commented on content/it/debugging.md
> +Questi bug conducono a un codice che è probabile che non funzioni come si desidera (comportamento indefinito) quanvo viene eseguito.
```suggestion
Questi bug porteranno ad avere un codice che non funzionerà come si desidera (comportamento indefinito) quando viene eseguito.
```

2022-10-24 14:33 UTC, annalisag-spark approved these changes

2022-10-28 22:04 UTC, fsbaraglia approved these changes

2022-10-28 22:04 UTC, merged