[Spanish] localize 'Immutable Infrastructure'
cncf/glossary pull request #1381
Opened 2022-10-15 00:49 UTC by tinniaru3005

### Describe your changes
Localize the `content/en/immutable-infrastructure.md` document to Spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1377 
Closes #1377 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-15 16:56 UTC, electrocucaracha requested changes
Hi @tinniaru3005,

Firstly, thanks for taking the time to translate this term. Overall, it seems good, but there are few suggestions which I think they are necessary. If you accept them, just make sure to update the word list to avoid any leftover.

Last but not least, the translation PRs need to target to the special branch, in this case `dev-es`. I have changed it, but it seems the PR template has been modified in master, so more likely you will have to recreate this branch and cherry-pick the commits.

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +status: Terminada
```suggestion
status: Completed
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +tags: ["infraestructura", "", ""]
```suggestion
tags: ["infrastructure", "", ""]
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +([maquinas virtuales](/virtual-machine/), [contenedores](/container/), dispositivos de red)
```suggestion
([máquinas virtuales](/virtual-machine/), [contenedores](/container/), dispositivos de red) 
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +que no se puede cambiar una vez implementado.
```suggestion
que no se puede cambiar una vez implementada. 
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +Esto se puede hacer cumplir mediante un proceso automatizado que sobrescribe los cambios no autorizados o
```suggestion
Esto se puede hacer cumplir mediante un proceso automatizado que sobreescriba los cambios no autorizados o
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +a través de un sistema que no permitirá cambios en primer lugar.
```suggestion
a través de un sistema que no permita cambios en primer lugar.
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +creando una nueva versión del contenedor o recreando el contenedor existente a partir de su imagen.
```suggestion
la creación una nueva versión del contenedor o recreando el contenedor existente a partir de su imagen.
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +Operar un sistema de este tipo se vuelve mucho más sencillo.
```suggestion
Operar un sistema de este tipo se vuelve mucho más sencillo
```

2022-10-15 16:56 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +La infraestructura inmutable va de la mano con [infraestructura como código](/infrastructure-as-code/)
```suggestion
La infraestructura inmutable va de la mano con [infraestructura como código](/es/infrastructure_as_code/) 
```

2022-10-15 17:18 UTC, tinniaru3005 commented
Hey @electrocucaracha, Thanks for helping me out with making the changes. Can you please let me know of some more changes are required?

2022-10-16 17:23 UTC, electrocucaracha commented
Apparently you will need to recreate this PR. The main issue seems to be the main branch that you used. So the workflow after forking this repo is to create a branch from `dev-es`

```bash
git clone https://github.com/cncf/tinniaru3005/
git checkout -b dev-es origin/dev-es
git branch tinniaru3005:es-immutable-infrastructure
```

I'll let some nitpicks for considering during the recreation process

2022-10-16 17:25 UTC, electrocucaracha reviewed
Please, recreate this PR using `dev-es` as base branch.

2022-10-16 17:25 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +maquinas
```suggestion
```

2022-10-16 17:25 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +que no se puede cambiar una vez implementada.
```suggestion
Infraestructura inmutable se refiere a la infraestructura informática
([máquinas virtuales](/virtual-machine/), [contenedores](/container/), dispositivos de red)
que no se puede cambiar una vez implementada.
```

2022-10-16 17:25 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +La infraestructura inmutable va de la mano con [infraestructura como código](es/infrastructure_as_code)
```suggestion
La infraestructura inmutable va de la mano con [infraestructura como código](es/infrastructure_as_code)
```

2022-10-17 02:12 UTC, closed without merging