[Spanish] localize 'Idempotence'
cncf/glossary pull request #1382
Opened 2022-10-16 12:13 UTC by tinniaru3005

### Describe your changes
- Converted `idempotence.md` to spacnish
- Added the new words to .wordlist.txt

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-16 17:03 UTC, electrocucaracha requested changes
These translation PRs require targeting to `dev-es` branch. Please, change them accordingly.

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/idempotence.md
> +tags: ["infraestructura", "arquitectura", ""]
```suggestion
status: Completed
category: Propiedad
tags: ["infrastructure", "architecture", ""]
```

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/idempotence.md
> +no importa cuantas veces lo ejecutes.
```suggestion
no importa cuantas veces se ejecute.
```

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/idempotence.md
> +title: Idempotence
```suggestion
title: Idempotencia
```

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +arquitectura
```suggestion
```

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +Idempotence
```suggestion
```

2022-10-16 17:03 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +infraestructura
```suggestion
```

2022-10-16 23:55 UTC, tinniaru3005 commented
Hey @electrocucaracha. Can you please tell me if it is fine now?

2022-10-17 15:47 UTC, electrocucaracha requested changes
The translation looks good, but the word list is unsorted. This PR also requires to be recreated using `dev-es` as branch base.

2022-10-17 15:47 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  Paganini
```suggestion
on-premises
Open
operación
Paganini
```

2022-10-17 16:31 UTC, electrocucaracha commented
I sent you a [PR](https://github.com/tinniaru3005/cncf-glossary/pull/1) with the only commit, need it for this. I think if you merge it in your branch, this will fix it.

2022-10-17 18:19 UTC, tinniaru3005 commented
> I sent you a [PR](https://github.com/tinniaru3005/cncf-glossary/pull/1) with the only commit, need it for this. I think if you merge it in your branch, this will fix it.

Hey @electrocucaracha, I did it. Thank you so much for the help. :)

2022-10-20 23:13 UTC, electrocucaracha commented
@raelga @krol3 @92nqb could you take a look this PR? It seems to be ready for review.

2022-10-31 18:14 UTC, 92nqb approved these changes

2022-10-31 18:18 UTC, merged