[it] localizzazione termine SaaS
cncf/glossary pull request #1403
Opened 2022-10-20 12:57 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added Software as a Service (SaaS) Italian localization

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-24 13:02 UTC, annalisag-spark requested changes

2022-10-24 13:02 UTC, annalisag-spark commented on content/it/software-as-a-service.md
> +Problemi di scalabilità, disponibilità e capacità sono gestiti dal fornitore del servizio e, con il pagamento ricorrente, possono essere un modo conveniente per le organizzazioni di sfruttare le appl
```suggestion
Problemi di scalabilità, disponibilità e capacità sono gestiti dal fornitore del servizio e, avendo un modello di pagamento a consumo, possono essere un modo conveniente per le organizzazioni di sfruttare le applicazioni aziendali.
```

2022-10-24 14:33 UTC, annalisag-spark approved these changes

2022-10-28 22:04 UTC, fsbaraglia approved these changes

2022-10-28 22:04 UTC, merged