Spanish localization for content/en/reliability.md
cncf/glossary pull request #1419
Opened 2022-10-27 05:16 UTC by anairinac

Creating glossary document Spanish localization for content/en/reliability.md related to https://github.com/cncf/glossary/issues/1399

Signed-off-by: Irina Calvo <anairinac@gmail.com>

### Describe your changes

Creating glossary document Spanish localization for content/en/reliability.md 

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #1399

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-27 15:56 UTC, electrocucaracha requested changes
Muchas gracias por esta contribución @anairinac,  he dejado algunas sugerencias necesarias para poder aprobar este PR.

2022-10-27 15:56 UTC, electrocucaracha commented on content/es/reliability.md
> +category: property
```suggestion
category: Propiedad
```

2022-10-27 15:56 UTC, electrocucaracha commented on content/es/reliability.md
> +Si tenemos un [sistema distribuido](/distributed-systems/) que continúa funcionando mientras la infraestructura cambia y componentes indivuduales fallan, esta es fiable.
```suggestion
Si tenemos un [sistema distribuido](/distributed-systems/) que continúa funcionando mientras la infraestructura cambia y los componentes individuales fallan, este es fiable. 
```

2022-10-27 15:56 UTC, electrocucaracha commented on content/es/reliability.md
> +Por otro lado, si falla fácilmente y operadores deben intervenir manualmente para mantenerlo en ejecución, entonces es poco confiable.
```suggestion
Por otro lado, si falla fácilmente y los operadores deben intervenir manualmente para mantenerlo en ejecución, entonces es poco confiable. 
```

2022-10-27 15:56 UTC, electrocucaracha commented on content/es/reliability.md
> +La meta de las [aplicaciones nativas para la nube](/cloud-native-apps/) es construir sistemas inherentemente fiables.
```suggestion
La meta de las [aplicaciones nativas para la nube](/es/cloud-native-apps/) es construir sistemas inherentemente fiables.
```

2022-10-27 17:37 UTC, anairinac commented on content/es/reliability.md
> +La meta de las [aplicaciones nativas para la nube](/cloud-native-apps/) es construir sistemas inherentemente fiables.
@electrocucaracha creo que el documento de Cloud Native apps aún no se ha localizado al español, entonces no estoy segura si esa referecia funcionaría: 
[/es/cloud-native-apps/](https://glossary.cncf.io/es/cloud-native-apps/) vs [/cloud-native-apps/](https://glossary.cncf.io/cloud-native-apps/)

2022-10-27 18:08 UTC, electrocucaracha commented on content/es/reliability.md
> +La meta de las [aplicaciones nativas para la nube](/cloud-native-apps/) es construir sistemas inherentemente fiables.
Creo que ya vi cuál es el problema, este brach debería estar basado en `dev-es` y no `main`. Voy a cambiar el PR, no sé si sea necesario cambiar el código y hacer un rebase.

2022-10-31 17:24 UTC, electrocucaracha commented on content/es/reliability.md
> +status: Feedback Appreciated
```suggestion
status: Completed
```

2022-10-31 17:27 UTC, electrocucaracha commented
@anairinac un par de observaciones respecto a este cambio:
1. Tienes que recrear este PR usando como base el branch `dev-es`, de otra manera el PR mostrara cambios innecesarios
2. Los commits tienen que ser firmados, esto es necesario para pasar el CI de DCO.
3. Puedes limitar el número de reviewers a @raelga @krol3 y @92nqb 

Cualquier cosa puedes contactarme por slack

2022-11-09 01:16 UTC, closed without merging

2022-11-09 01:17 UTC, anairinac commented
Closed PR since I'm opening another one to fix the source branch issue.