[it] Localizzazione termine Self Healing
cncf/glossary pull request #1420
Opened 2022-10-27 12:31 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added Self Healing Italian localization

### Related issue number or link (ex: `resolves #issue-number`)
NA

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-28 21:56 UTC, fsbaraglia requested changes

2022-10-28 21:56 UTC, fsbaraglia commented on content/it/self-healing.md
> +tags: ["infrastrutura", "architettura", ""]
```suggestion
tags: ["infrastruttura", "architettura", ""]
```

2022-10-31 08:53 UTC, annalisag-spark approved these changes

2022-11-16 22:13 UTC, fsbaraglia approved these changes

2022-11-16 22:13 UTC, merged