[Spanish] localize 'Platform as a Service (PaaS)' #1400
cncf/glossary pull request #1424
Opened 2022-10-28 20:14 UTC by mdf-ido

### Describe your changes
Adding the description of PaaS in spanish.

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1400 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-10-31 17:16 UTC, mdf-ido reviewed
Added the opening question marks

2022-10-31 17:19 UTC, electrocucaracha requested changes
@mdf-ido muchas gracias por realizar la traducción de este término. He realizado un par de sugerencias necesarias en este cambio. Algo importante a notar es que este PR debe apuntar al branch `dev-es` . Tambien es necesario que los commits sean firmados para que puedan pasar las validaciones del CI.

2022-10-31 17:19 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +Para aprovechar soluciones como los microservicios, contenedores o las aplicaciones distribuidas, los equipos de operaciones y los desarrolladores tienen que dedicar tiempo y trabajo en mantener la i
```suggestion
Para aprovechar los patrones de las aplicaciones nativas para la nube como son los [microservicios](/microservices/) o las [aplicaciones distribuidas](/distributed-apps/), los equipos de operaciones y los desarrolladores necesitan ser capaces de descargar un tiempo significativo de trabajo en operaciones y mantenimiento.
```

2022-10-31 17:19 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +Estos incluyen tareas como el aprovisionamiento de infraestructura, el manejo del descubrimiento de servicios y el equilibrio de carga a las aplicaciones entre otros.
```suggestion
Estos incluyen tareas como el aprovisionamiento de infraestructura, el manejo del [descubrimiento de servicios](/service-discovery/) y balanceo de cargas, y [escalamiento](/scalability/) de aplicaciones.
```

2022-10-31 17:19 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +Una solución PaaS proporciona la infraestructura, a los desarrolladores, de aplicaciones de forma totalmente automatizada.
```suggestion
Una solución PaaS ofrece herramientas de infraestructura comunes, a los desarrolladores de aplicaciones de forma totalmente automatizada. 
```

2022-10-31 17:19 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +Permite que los desarrolladores puedan enfocarse en escribir codigo y les quita la  preocupación de mantener la infraestructura.
```suggestion
Permite que los desarrolladores puedan comprender y preocuparse menos por la infraestructura y asi dedicar mas tiempo en escribir código de la aplicación. 
```

2022-10-31 17:19 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +También proporciona cierta supervisión y observabilidad para ayudar a los equipos de aplicaciones a garantizar que sus aplicaciones estén en buen estado.
```suggestion
También proporciona cierta supervisión y [observabilidad](/es/observability/) para ayudar a los equipos de aplicaciones a garantizar que sus aplicaciones estén en buen estado.
```

2022-10-31 17:43 UTC, mdf-ido commented
@electrocucaracha - Pregunta: Sera que mejor hago un pull de dev-es en vez de forking el repo?

2022-10-31 19:13 UTC, electrocucaracha commented
> @electrocucaracha - Pregunta: Sera que mejor hago un pull de dev-es en vez de forking el repo?

El fork es necesario, el detalle es que cuando creas tu branch local debe ser utilizando `dev-es` como base.

```bash
$ git clone git@github.com:mdf-ido/glossary.git
...
$ cd glossary
$ git switch dev-es
$ git branch 1400-spanish-localize-platform-as-service
$ git switch 1400-spanish-localize-platform-as-service
``` 

Y de igual manera, al crear el PR, este debe de ir dirigido hacia `dev-es`

2022-10-31 19:44 UTC, mdf-ido commented
> > @electrocucaracha - Pregunta: Sera que mejor hago un pull de dev-es en vez de forking el repo?
> 
> El fork es necesario, el detalle es que cuando creas tu branch local debe ser utilizando `dev-es` como base.
> 
> ```shell
> $ git clone git@github.com:mdf-ido/glossary.git
> ...
> $ cd glossary
> $ git switch dev-es
> $ git branch 1400-spanish-localize-platform-as-service
> $ git switch 1400-spanish-localize-platform-as-service
> ```
> 
> Y de igual manera, al crear el PR, este debe de ir dirigido hacia `dev-es`.
> 
> Por último, es necesario agregar varias palabras en el [diccionario ](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt)para evitar [errores en el CI](https://github.com/cncf/glossary/actions/runs/3363410364/jobs/5577965393#step:5:13), estas palabras están ordenadas alfabéticamente para detectar duplicidad fácilmente.

Gracias por su ayuda, las palabras que tengo que añadir al diccionario son las que el Spell check encontró?

2022-10-31 19:56 UTC, electrocucaracha commented
> Gracias por su ayuda, las palabras que tengo que añadir al diccionario son las que el Spell check encontró?

Asi es, basicamente son:

* PaaS
* fundamentals
* platform
* App
* Engine
* Foundry
* Heroku

y luego ordenarlas en orden alfabético

```bash
$ sort -f -o content/es/.wordlist.txt content/es/.wordlist.txt
```

2022-11-01 00:30 UTC, mdf-ido reviewed
@electrocucaracha - Ya cambie el branch y actualize el diccionario. Gracias por su ayuda y espero aprender en esta para hacer otras y ayudarles!

2022-11-01 15:55 UTC, electrocucaracha commented
> @electrocucaracha - Ya cambie el branch y actualize el diccionario. Gracias por su ayuda y espero aprender en esta para hacer otras y ayudarles!

Lo único que no cuadra en este PR es que hay cambios en otros archivos no relacionados, podrías hacer rebase de los cambios?

2022-11-01 20:58 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +your
Parece ser que agregaste un salto de línea al documento, quizá fue el editor que usaste.

2022-11-01 22:04 UTC, mdf-ido commented on content/es/.wordlist.txt
> +your
Ok, no veo el salto de línea en mi editor pero ahora investigo.

2022-11-02 03:00 UTC, mdf-ido commented
@electrocucaracha - Vi el último error del spell checker. Crees que necesito añadir la palabra true y asi al diccionario?

2022-11-02 18:01 UTC, electrocucaracha commented
> @electrocucaracha - Vi el último error del spell checker. Crees que necesito añadir la palabra true y asi al diccionario?

Parece ser que la eliminaste de la lista original.

Por otra parte, quizá sea necesario recrear este PR ya que tienes algunos cambios de `main` o al menos aparecen otros cambios de archivos no relacionados. Cualquier duda puedes contactarme via slack

2022-11-09 05:16 UTC, electrocucaracha approved these changes

2022-11-11 19:26 UTC, ramrodo approved these changes
/lgtm

2022-11-11 19:28 UTC, electrocucaracha commented
@seokho-son @jihoon-seo can you help us to merge this PR?

2022-11-11 22:02 UTC, jihoon-seo approved these changes

2022-11-11 22:30 UTC, raelga approved these changes

2022-11-11 22:30 UTC, merged