Create Spanish localization for event-driven-architecture.md
cncf/glossary pull request #1427
Opened 2022-10-29 04:35 UTC by anairinac

Signed-off-by: Irina Calvo <anairinac@gmail.com>

### Describe your changes

Created the Spanish localization for the event-driven-architecture.md document

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #1373

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-02 18:23 UTC, electrocucaracha requested changes
Solo algunos cambios menores en la traducción. Por cierto es necesario agregar `HTTP` y `Kafka` en el word list.

```bash
$ echo "HTTP" >> content/es/.wordlist.txt
$ echo "Kafka" >> content/es/.wordlist.txt
$ sort -f -o content/es/.wordlist.txt content/es/.wordlist.txt
```

2022-11-02 18:23 UTC, electrocucaracha commented on content/es/event-driven-architecture.md
> +status: Feedback Appreciated
```suggestion
status: Completed
```

2022-11-08 15:50 UTC, krol3 commented on content/es/event-driven-architecture.md
> +tags: ["", "", ""]
@anairinac como estas? necesitas alguna ayuda para aplicar los comentarios de @electrocucaracha ?

2022-11-08 16:04 UTC, anairinac commented on content/es/event-driven-architecture.md
> +tags: ["", "", ""]
Hola! Esta noche voy a aplicar todos los cambios, no he podido porque he estado trabajando mucho 😳

2022-11-09 05:14 UTC, electrocucaracha approved these changes

2022-11-11 19:30 UTC, ramrodo approved these changes
/lgtm

2022-11-11 19:31 UTC, electrocucaracha commented
@raelga @92nqb @krol3 can you merge this PR?

2022-11-11 22:26 UTC, raelga approved these changes

2022-11-11 22:27 UTC, merged