service.md localised to Hindi
cncf/glossary pull request #1428
Opened 2022-10-29 11:30 UTC by NitishKumar06

Signed-off-by: NitishKumar06 <justnitish06@gmail.com>

Fix: #1304

2022-10-30 07:36 UTC, seokho-son commented
Hi @NitishKumar06 
Please don't remove PR template and try to use the PR template so that reviewers or maintainers aware this PR fulfils the checklist.

2023-01-08 17:19 UTC, Garima-Negi requested changes

2023-01-08 17:19 UTC, Garima-Negi commented on content/hi/service.md
> +status: पूरा हुआ
status should be completed:
`status: Completed`

2023-01-08 17:19 UTC, Garima-Negi commented on content/hi/service.md
> +title: सेवा
please add the english name of term in parenthesis:
e.g title: सर्वरलेस (Serverless)

2023-01-08 17:19 UTC, Garima-Negi commented on content/hi/service.md
> +इस परिभाषा में, हम अधिक पारंपरिक एक पर ध्यान केंद्रित करेंगे: माइक्रोसर्विस की तरह सेवा।
```suggestion
हम एक अधिक पारंपरिक अर्थ पर ध्यान केंद्रित करेंगे
```

2023-01-08 17:19 UTC, Garima-Negi commented on content/hi/service.md
> +कैसे या भले ही सेवाएं माइक्रोसर्विसेज से भिन्न हों या नहीं, यह बारीक है और अलग-अलग लोगों की अलग-अलग राय हो सकती है।
```suggestion
यदि सेवाएँ माइक्रोसर्विसेज से भिन्न हैं और वे कैसे भिन्न हैं, यह बारीक है और अलग-अलग लोगों की अलग-अलग राय हो सकती है।
```

2023-04-17 22:26 UTC, Garima-Negi approved these changes

2023-04-18 18:06 UTC, sayantani11 approved these changes
nicely done!

2023-04-19 08:13 UTC, jayesh-srivastava commented
@Garima-Negi Isn't this suppose to target dev-hi branch?

2023-04-21 16:12 UTC, merged