Add german translation for bare metal machine
cncf/glossary pull request #1431
Opened 2022-10-29 13:57 UTC by bcubk

Signed-off-by: Baris Cubukcuoglu <cubukcuoglu.baris@gmail.com>

### Describe your changes
This PR add a german definition for Bare Metal Machine (see https://glossary.cncf.io/bare-metal-machine)

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #510

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-09 07:54 UTC, DaveVentura requested changes
Ich finde, die Abschnitte sind hier etwas vermischt. Ich weiß, dass du dich an der englischen Version orientiert hast aber wir können das ja nach eigenen Ermessen anpassen.

Ich habe ein paar Vorschläge zur "Verschiebung" von Aussagen hinterlassen :)

Ansonsten gut übersetzt, hab jetzt auch keine Rechtschreibfehler gefunden.

2022-11-09 07:54 UTC, DaveVentura commented on content/de/bare-metal-machine.md
> +Die Verknüpfung eines Betriebssystems mit einem physischen Computer ist das ursprüngliche Muster der Datenverarbeitung.
Gehört das nicht eher ins "Was"?

2022-11-09 07:54 UTC, DaveVentura commented on content/de/bare-metal-machine.md
> +Die kompletten Ressourcen des physischen Computers stehen dem Betriebssystem direkt zur Verfügung. Aufgrund einer fehlenden Virtualisierung gibt es keine künstliche Verzögerung bei der Übersetzung vo
und der erste Satz hier wiederum eher ins wie?

Für diesen Abschnitt würde ich sowas wie das folgende vorschlagen:
"Bei Virtualisierungen kommt es zu künstlichen Verzögerung bei der Übersetzung von Betriebssystemanweisungen in Maschinencode. Falls die Verarbeitung eines Workloads einen schnellen Zugriff auf Hardwareressourcen erfordert, kann Bare Metal die richtige Lösung sein."

2022-11-09 07:54 UTC, DaveVentura commented on content/de/bare-metal-machine.md
> +Durch die Bereitstellung der gesamten Ressourcen eines Computers für ein einziges Betriebssystem, kann die bestmögliche Leistung erzielt werden. Falls die Verarbeitung eines Workloads einen schnellen
Hier gehört der zweite Satz für mich in den Problem Abschnitt (s.o.)

2022-11-13 20:13 UTC, bcubk commented
@DaveVentura, ich habe deine Punkte eingearbeitet. Kannst du eventuell nochmal schauen, ob es deiner Meionung nach passt?

2022-11-13 21:13 UTC, iamNoah1 requested changes
@bcubk bitte auf das signing off achten und noch die semantic line breaks einbauen. Danke :)

2022-11-14 10:05 UTC, DaveVentura approved these changes

2022-11-30 15:01 UTC, iamNoah1 requested changes
@bcubk Danke für den Beitrag und sorry für die Verzögerung. Hab ein paar kleine Anmerkungen.

2022-11-30 15:01 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +Durch die Skalierbarkeit von [Cloud Native Apps](/cloud-native-apps/) kann eine große Anzahl von parallelen Events effizient verarbeitet werden. Dies kann durch horizontale Skalierung (durch Hinzufüg
```suggestion
Durch die Skalierbarkeit von [Cloud Native Apps](/cloud-native-apps/) kann eine große Anzahl von parallelen Events effizient verarbeitet werden. Dies kann entweder durch horizontale oder vertikale Skalierung erreicht werden. Für bestimmte Workloads kann eine vertikale Skalierung und/oder eine schnelle Reaktionszeit der physischen Hardware erforderlich sein. Für diesen Fall eignet sich Bare Metal. 
```

2022-11-30 15:01 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +Mithilfe von Bare Metal lassen sich physische Hardware sowie die Hardwaretreiber optimieren, damit bestimmte Aufgaben effizienter bearbeitet werden können.
Weiß nicht ob wir diesen letzten Satz nicht viellicht einfach löschen sollten.

2023-01-01 12:35 UTC, bcubk commented on content/de/bare-metal-machine.md
> +Bare Metal beschreibt einen physischen Computer, speziell einen Server, welcher nur ein einziges Betriebssystem hat.
Wobei `im Prinzip` ein Füllwort ist. Würde das weglassen

2023-01-05 15:28 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +Bare Metal beschreibt einen physischen Computer, speziell einen Server, welcher nur ein einziges Betriebssystem hat.
agreed.

2023-01-05 15:32 UTC, iamNoah1 reviewed
Danke @bcubk hab nur noch die semantic line breaks als suggestions eingebaut. Ansonsten passts für mich.

2023-01-05 15:32 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +Bei Virtualisierungen kommt es zu künstlicher Verzögerung bei der Übersetzung von Betriebssystemanweisungen in Maschinencode. Falls die Verarbeitung eines Workloads einen schnellen Zugriff auf Hardwa
```suggestion
Bei Virtualisierungen kommt es zu künstlicher Verzögerung bei der Übersetzung von Betriebssystemanweisungen in Maschinencode. 
Falls die Verarbeitung eines Workloads einen schnellen Zugriff auf Hardwareressourcen erfordert, kann Bare Metal die richtige Lösung sein.
```

2023-01-05 15:32 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +
```suggestion
```

2023-01-05 15:32 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +Durch die Skalierbarkeit von [Cloud Native Apps](/cloud-native-apps/) kann eine große Anzahl von parallelen Events effizient verarbeitet werden. Dies kann entweder durch horizontale oder vertikale Sk
```suggestion
Durch die Skalierbarkeit von [Cloud Native Apps](/cloud-native-apps/) kann eine große Anzahl von parallelen Events effizient verarbeitet werden. 
Dies kann entweder durch horizontale oder vertikale Skalierung erreicht werden. 
Für bestimmte Workloads kann eine vertikale Skalierung und/oder eine schnelle Reaktionszeit der physischen Hardware erforderlich sein. 
Für diesen Fall eignet sich Bare Metal. 
```

2023-01-05 15:33 UTC, iamNoah1 approved these changes

2023-01-05 15:33 UTC, iamNoah1 commented on content/de/bare-metal-machine.md
> +status: Feedback erwünscht
```suggestion
status: Completed
```

2023-01-05 15:34 UTC, merged

2023-01-05 15:34 UTC, iamNoah1 commented
Danke @bcubk. Gute Arbeit.