[French] Traduction de containerization.md
cncf/glossary pull request #1432
Opened 2022-10-30 21:24 UTC by huats

Signed-off-by: Christophe Sauthier [christophe.sauthier@gmail.com](mailto:christophe.sauthier@gmail.com)

Describe your changes
This PR localizes containerization.md concept to French

Related issue number or link (ex: resolves #issue-number)
resolves https://github.com/cncf/glossary/issues/1266

Checklist before opening this PR (put x in the checkboxes)
[ X ] This PR does not contain plagiarism
don’t copy other people’s work unless you are quoting and contributing it to them.
[ X ] I have signed off on all commits
[signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: git commit -s) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +Le processus de construction du conteneur nécessaire de respecter le standard de l'[Open Container Initiative](https://opencontainers.org) (OCI).
Le processus de construction du conteneur "nécessite" de respecter

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +Avant que les conteneurs ne se généralisent, les organisations orchestraient de nombreuses applications au sein d'une unique [machine physique](/bare-metal-machine/).
La traduction me parait pas bonne : 

"Before containers became prevalent, organizations relied on virtual machines (VMs) to orchestrate multiple applications on a single [bare-metal machine](https://glossary.cncf.io/bare-metal-machine/)."

J'aurais plutôt traduit ça comme ça : 

Avant que les conteneurs prévalent, les organisations s'appuyaient sur des machines virtuelles pour orchestrer différentes applications sur une machine physique.

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +Les VMs sont VMs sont sensiblement plus grosses que les conteneurs et nécessitent un hyperviseur pour fonctionner.
"Les VMs sont Vms sont" -> "Les VMs sont"

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +À cause du stockage, du backup et du transfert de ces gros templates de VM, la création des templates de VM est également longue.
Templates c'est un anglicisme, on traduit ça par "modèle de VM" ? Ou à la limite modèle (template)

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +De plus, les VMs peuvent souffrir d'une dérive de configuration ce qui enfreint le principe de l'i[immutabilité](/immutable-infrastructure/).
"i[immuatabilité]" -> [immuatabilité]"

2022-11-26 15:13 UTC, Krast76 commented on content/fr/containerization.md
> +De plus, les VMs peuvent souffrir d'une dérive de configuration ce qui enfreint le principe de l'i[immutabilité](/immutable-infrastructure/).
Et d'ailleurs, en français c'est immuabilité il me semble

2023-01-25 05:09 UTC, fydrah requested changes

2023-01-25 05:09 UTC, fydrah commented on content/fr/containerization.md
> +À cause du stockage, du backup et du transfert de ces gros modèles de VM, la création des modèles de VM est également longue.
backup --> sauvegarde

2023-01-25 05:09 UTC, fydrah commented on content/fr/_TEMPLATE.md
> +## Problème auquel il répond
I think you can rebase and remove this change, since the last PR merged already includes this change

2023-01-25 05:09 UTC, fydrah commented on content/fr/containerization.md
> +Etant donné que les conteneurs sont planifiés et replanifiés, ils sont toujours
I would use "instancié et ré-instanciés" instead of 'planifié'

2023-01-25 05:10 UTC, fydrah requested changes

2023-01-25 05:10 UTC, fydrah commented on content/fr/containerization.md
> +Etant donné que les conteneurs sont planifiés et replanifiés, ils sont toujours
'Étant'

2023-01-25 17:19 UTC, fydrah approved these changes

2023-01-26 17:48 UTC, Krast76 approved these changes

2023-01-26 21:30 UTC, merged