[it] Localizzazione termine Firewall
cncf/glossary pull request #1436
Opened 2022-11-03 10:06 UTC by ugho16

### Describe your changes
Added Firewall Italian localization.

### Related issue number or link (ex: `resolves #issue-number`)
NA

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-16 22:14 UTC, fsbaraglia approved these changes

2022-12-14 09:44 UTC, annalisag-spark requested changes

2022-12-14 09:44 UTC, annalisag-spark commented on content/it/firewall.md
> +Un firewall (letteralmente _muro di fuoco_) è un sistema che filtra il traffico di un network basandosi su regole specifiche.
ma la traduzione letterale ha senso inserirla? mumble 🧐

2022-12-14 10:15 UTC, annalisag-spark approved these changes

2022-12-14 10:21 UTC, merged