[Spanish] localize 'Policy as Code (PaC)'
cncf/glossary pull request #1439
Opened 2022-11-04 10:14 UTC by tinniaru3005

### Describe your changes
Localize the `content/en/policy-as-code.md` document to Spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1401 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-04 17:02 UTC, electrocucaracha requested changes
It seems like your local `dev-es` branch is not properly updated, and it keeps bringing some changes from `main`

2022-11-04 17:02 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  Open
```suggestion
Open
PaC
```

2022-11-04 17:06 UTC, electrocucaracha commented on content/es/policy-as-code.md
> +category: concepto
```suggestion
category: Concepto
```

2022-11-04 17:22 UTC, tinniaru3005 commented
> It seems like your local `dev-es` branch is not properly updated, and it keeps bringing some changes from `main`

When I am forking the repository I am only able to fork from the `main` branch. Then I am creating my own branch and working on it. Can you please tell me a way I can form from the `dev-es` branch

2022-11-07 23:32 UTC, tinniaru3005 commented
Hey @electrocucaracha, can you please tell me if the changes are fine now?

2022-11-08 17:19 UTC, electrocucaracha approved these changes

2022-11-11 19:31 UTC, ramrodo approved these changes
/lgtm

2022-11-11 22:38 UTC, raelga approved these changes

2022-11-12 22:17 UTC, krol3 commented
Hi @tinniaru3005 it's only missing the DCO to merge it

2022-11-29 16:54 UTC, merged