[Spanish] localize 'Event Streaming'
cncf/glossary pull request #1440
Opened 2022-11-04 11:32 UTC by tinniaru3005

### Describe your changes
Localize the `content/en/event-streaming.md` document to Spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1374 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-04 17:23 UTC, electrocucaracha requested changes
Make sure to add the missing words into the wordlist

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +status: Terminada
```suggestion
status: Completed
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +## Lo que es
```suggestion
## ¿Qué es?
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +category: concepto
```suggestion
category: Concepto
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +## como ayuda
```suggestion
## ¿Cómo ayuda?
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +La transmisión de eventos es un enfoque en el que el software envía datos de eventos de una aplicación a otra para comunicar continuamente lo que están haciendo.
```suggestion
La transmisión de eventos es un enfoque en el que el software envía datos de eventos de una aplicación a otra para comunicar continuamente lo que esta haciendo.
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +Por ejemplo, NASDAQ recibe actualizaciones sobre precios de acciones y materias primas cada segundo.
```suggestion
Por ejemplo, NASDAQ recibe actualizaciones sobre los precios de las acciones y materias primas cada segundo.
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +yahoo! Finanzas proporciona una [API] (https://glossary.cncf.io/application-programming-interface/) que extrae de NASDAQ y envía (o transmite) la información (o eventos) de su aplicación a cualquier
```suggestion
Yahoo! Finance proporciona una [API](/es/application-programming-interface/) que extrae de NASDAQ y envía (o transmite) la información (o eventos) de su aplicación a cualquier aplicación que se suscriba a ella.
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +A medida que los datos se vuelven más en tiempo real, escalar una solución de este tipo se vuelve ineficiente.
```suggestion
En medida que los datos se vuelven más en tiempo real, escalar una solución de este tipo se vuelve ineficiente.
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +Abrir una conexión una vez y permitir que los eventos fluyan es ideal para la recopilación en tiempo real.
```suggestion
Abrir una conexión solo una vez y permitir que los eventos fluyan, es ideal para la recopilación en tiempo real.
```

2022-11-04 17:23 UTC, electrocucaracha commented on content/es/event-streaming.md
> +Si tuviera una aplicación que monitoreara un conjunto específico de acciones, le gustaría recibir esa información casi en tiempo real.
```suggestion
Si tuviera una aplicación que monitoreará un conjunto específico de acciones, le gustaría recibir esa información casi en tiempo real.
```

2022-11-06 16:08 UTC, tinniaru3005 commented
Hey @electrocucaracha, Can you please tell me which extra words are required to be added?

2022-11-07 22:23 UTC, electrocucaracha commented
> Hey @electrocucaracha, Can you please tell me which extra words are required to be added?

Those are usually reported by the CI [logs](https://github.com/cncf/glossary/actions/runs/3396495884/jobs/5647625809#step:5:13). For this case, you need to add the following ones:
```text
Finance
NASDAQ
Yahoo
monitoreará
TCP
```

2022-11-07 22:34 UTC, electrocucaracha approved these changes
@raelga @krol3 @92nqb can you take a look on this change

2022-11-08 15:41 UTC, krol3 approved these changes
LGTM, Nice job @tinniaru3005

2022-11-08 15:44 UTC, merged