[hi] Localize `Serverless` for Hindi
cncf/glossary pull request #1443
Opened 2022-11-06 11:24 UTC by shivam-sharma7

`Serverless` now Localized into Hindi.

Signed-off-by: Shivam Sharma <meshivam81@gmail.com>

### Related issue- #1435  

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-06 11:25 UTC, shivam-sharma7 commented
review/ @NitishKumar06 @anubha-v-ardhan

2022-12-26 14:20 UTC, shivam-sharma7 commented
review/ @NitishKumar06 @anubha-v-ardhan

2023-01-07 18:26 UTC, shivam-sharma7 commented
review/ @Garima-Negi

2023-01-14 09:27 UTC, NitishKumar06 commented on content/hi/serverless.md
> +### समस्या यह संबोधित करता है
```suggestion
### समस्या जो यह संबोधित करता है
```

2023-01-14 09:28 UTC, NitishKumar06 reviewed
Please add this

2023-02-05 07:17 UTC, shivam-sharma7 commented
review/ @Garima-Negi

2023-02-12 10:56 UTC, NitishKumar06 reviewed
Please squash your commits

2023-04-22 07:23 UTC, anubha-v-ardhan requested changes

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +### यह क्या है
```suggestion
## यह क्या है
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +### समस्या जो यह संबोधित करता है
```suggestion
## समस्या
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +### यह  कैसे मदद करता है
```suggestion
## समाधान
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +---
```suggestion
---
title: सर्वरलेस (Serverless)
status: Completed
category: प्रौद्योगिकी
tags: ["architecture", "", ""]
---
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +सर्वरलेस एक क्लाउड नेटिव डेवलपमेंट मॉडल है जो डेवलपर्स को सर्वर को प्रबंधित किए बिना एप्लिकेशन बनाने और चलाने की अनुमति देता है। सर्वर रहित सर्वर अभी भी हैं, लेकिन वे [abstracted](/abstraction/) ऐप ड
```suggestion
सर्वरलेस एक क्लाउड नेटिव डेवलपमेंट मॉडल है जो डेवलपर्स को सर्वर को प्रबंधित किए बिना एप्लिकेशन बनाने और चलाने की अनुमति देता है। सर्वरलेस में सर्वर अभी भी हैं, लेकिन वे [ऐब्स्ट्रैक्टेड](/hi/abstraction/) ऐप डेवलपमेंट से दूर हैं। एक क्लाउड प्रदाता सर्वर इन्फ्रास्ट्रक्चर के प्रावधान, रखरखाव और [स्केलिंग](/hi/scalability/) के नियमित कार्य को संभालता है। डेवलपर्स डिप्लॉयमेंट के लिए अपने कोड को [कंटेनर](/hi/container/) में पैकेज कर सकते हैं। एक बार डिप्लॉय होने के बाद, सर्वरलेस ऐप्स डिमांड का जवाब देते हैं और आवश्यकतानुसार स्वचालित रूप से ऊपर और नीचे स्केल करते हैं। सार्वजनिक क्लाउड प्रदाताओं से सर्वरलेस पेशकशों को आमतौर पर इवेंट-संचालित निष्पादन मॉडल के माध्यम से ऑन-डिमांड मीटर किया जाता है। नतीजतन, जब कोई सर्वरलेस फ़ंक्शन निष्क्रिय रहता है, तो इसका कुछ भी खर्च नहीं होता है।
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +एक मानक [Infrastructure-as-a-Service (IaaS)](/infrastructure-as-a-service/) [cloud computing](/cloud-computing/) मॉडल के तहत, उपयोगकर्ता क्षमता की इकाइयों को पूर्व-खरीद करते हैं, जिसका अर्थ है कि आप
```suggestion
एक मानक [इन्फ्रास्ट्रक्चर एस सर्विस (IaaS)](/infrastructure-as-a-service/) [क्लाउड कंप्यूटिंग](/cloud-computing/) मॉडल के तहत, उपयोगकर्ता क्षमता की इकाइयों को पूर्व-खरीद करते हैं, जिसका अर्थ है कि आप अपने ऐप्स चलाने के लिए हमेशा-ऑन सर्वर घटकों के लिए सार्वजनिक क्लाउड प्रदाता का भुगतान करते हैं। उच्च मांग के समय सर्वर क्षमता को बढ़ाना और उस क्षमता की आवश्यकता नहीं होने पर इसे कम करना उपयोगकर्ता की जिम्मेदारी है। ऐप को चलाने के लिए आवश्यक क्लाउड इन्फ्रास्ट्रक्चर तब भी सक्रिय रहता है, जब ऐप का उपयोग नहीं किया जा रहा हो।
```

2023-04-22 07:23 UTC, anubha-v-ardhan commented on content/hi/serverless.md
> +सर्वर रहित आर्किटेक्चर के साथ, इसके विपरीत, ऐप्स केवल आवश्यकतानुसार लॉन्च किए जाते हैं। जब कोई ईवेंट चलने के लिए ऐप कोड को ट्रिगर करता है, तो सार्वजनिक क्लाउड प्रदाता गतिशील रूप से उस कोड के लिए संसा
```suggestion
इसके विपरीत, सर्वरलेस आर्किटेक्चर के साथ, ऐप्स केवल आवश्यकतानुसार लॉन्च किए जाते हैं। जब कोई ईवेंट चलने के लिए ऐप कोड को ट्रिगर करता है, तो सार्वजनिक क्लाउड प्रदाता गतिशील रूप से उस कोड के लिए संसाधन आवंटित करता है। कोड निष्पादित होने पर उपयोगकर्ता भुगतान करना बंद कर देता है। लागत और दक्षता लाभों के अलावा, सर्वरलेस डेवलपर्स को ऐप स्केलिंग और सर्वर प्रोविजनिंग से जुड़े नियमित और छोटे कार्यों से मुक्त करता है। सर्वरलेस होने के साथ, नियमित कार्य जैसे ऑपरेटिंग सिस्टम और फ़ाइल सिस्टम का प्रबंधन, सुरक्षा पैच, लोड संतुलन, क्षमता प्रबंधन, स्केलिंग, लॉगिंग और निगरानी सभी क्लाउड सेवा प्रदाता को लोड कर दिए जाते हैं।
```

2023-04-23 10:59 UTC, anubha-v-ardhan approved these changes
LGTM!

2023-06-28 17:27 UTC, jayesh-srivastava approved these changes
LGTM!

2023-06-28 18:22 UTC, merged

2024-01-05 07:47 UTC, shivam-sharma7 commented
Thanks