Localized `content/bn/blue-green-deployment.md` to Bengali
cncf/glossary pull request #1454
Opened 2022-11-12 11:23 UTC by PratikDey

Signed-off-by: [Pratik Dey](https://github.com/cncf/glossary/pull/pratikdey.pro@gmail.com)
Localizes content/bn/containers-as-a-service.md to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

2022-11-13 20:10 UTC, mitul3737 requested changes

2022-11-13 20:10 UTC, mitul3737 commented on content/bn/blue-green-deployment.md
> +একটি প্রোডাকশন ট্র্যাফিক পরিবেশন করে (বর্তমানে সমস্ত ব্যবহারকারী যে সংস্করণটি ব্যবহার করছেন), যখুন অন্যটি আপডেট করা হয়।
Kindly create a  better sentence from this one : একটি প্রোডাকশন ট্র্যাফিক পরিবেশন করে (বর্তমানে সমস্ত ব্যবহারকারী যে সংস্করণটি ব্যবহার করছেন), যখুন অন্যটি আপডেট করা হয়।

2022-11-13 20:10 UTC, mitul3737 commented on content/bn/blue-green-deployment.md
> +এই অস্পষ্টতা এড়াতে, পৃথক উপাদান উল্লেখ করার সময় "শূন্য-ডাউনটাইম স্থাপনা" শব্দটি পছন্দ করা হয়।
```suggestion
এই অস্পষ্টতা এড়াতে, পৃথক উপাদান উল্লেখ করার সময় "শূন্য-ডাউনটাইম স্থাপনা (zero-downtime deployment)" শব্দটি পছন্দ করা হয়।
```

2022-11-13 20:10 UTC, mitul3737 commented on content/bn/blue-green-deployment.md
> +উত্পাদন ট্র্যাফিক সুইচ ওভার করা হয় (প্রায়শই লোড ব্যালেন্সার ব্যবহারের মাধ্যমে)।
```suggestion
 উৎপাদনে ট্র্যাফিক সুইচ ওভার করা হয় (প্রায়শই লোড ব্যালেন্সার ব্যবহারের মাধ্যমে)।
```

2022-11-13 20:10 UTC, mitul3737 commented on content/bn/blue-green-deployment.md
> +যদি এটি উত্পাদন সিস্টেমে করা হয় তবে গ্রাহকরা ডাউনটাইম লক্ষ্য করবেন।
```suggestion
যদি এটি উৎপাদন সিস্টেমে করা হয় তবে গ্রাহকরা ডাউনটাইম লক্ষ্য করবেন।
```

2022-11-13 20:10 UTC, mitul3737 commented on content/bn/blue-green-deployment.md
> +যাইহোক, এটির ব্যবহার সাধারণত একটি "গন্ধ" যে উত্তরাধিকারী সফ্টওয়্যার পুনরায় ইঞ্জিনিয়ার করা প্রয়োজন যাতে উপাদানগুলি পৃথকভাবে আপডেট করা যায়।
Kindly make a better sentence from যাইহোক, এটির ব্যবহার সাধারণত একটি "গন্ধ (smell)" যে উত্তরাধিকারী সফ্টওয়্যার পুনরায় ইঞ্জিনিয়ার করা প্রয়োজন যাতে উপাদানগুলি পৃথকভাবে আপডেট করা যায়।

2022-11-22 11:19 UTC, mitul3737 approved these changes
LGTM!

2022-11-22 11:22 UTC, Imtiaz1234 approved these changes
lgtm!

2022-11-22 11:22 UTC, merged