[Spanish] localize 'Debugging
cncf/glossary pull request #1458
Opened 2022-11-14 18:51 UTC by vasucp1207

Signed-off-by: Vasu Singh <vasucp1207@gmail.com>

### Describe your changes
[Spanish] localize 'Debugging

### Related issue number https://github.com/cncf/glossary/issues/1372

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-28 11:20 UTC, raelga approved these changes

2022-11-29 17:26 UTC, electrocucaracha requested changes

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +etiquetas: ["aplicación", "", ""]
```suggestion
title: Depuración
status: Completed
category: concepto
tags: ["application", "", ""]
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +## Lo que es
```suggestion
## ¿Qué es?
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Dependiendo de cuán crítica sea una aplicación, los errores pueden tener un impacto negativo significativo, financieramente o incluso en vidas humanas.
```suggestion
Dependiendo de que tan crítica sea una aplicación, los bugs pueden tener un impacto negativo significativo; financiero o incluso en vidas humanas.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +## Cómo ayuda
```suggestion
## ¿Cómo ayuda?
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +El análisis de registros, seguimientos y métricas, por ejemplo, se utiliza para la depuración directamente en producción.
```suggestion
El análisis de registros, trazas y métricas, son un ejemplo de lo que se utiliza para la depuración directamente en producción.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +La depuración es el proceso o actividad de encontrar y resolver errores (bugs) de programas, software o sistemas informáticos para obtener el resultado deseado.
```suggestion
La depuración es el proceso o actividad de encontrar y resolver bugs (o errores) de programas, software o sistemas informáticos para obtener el resultado deseado.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Un error es un defecto o un problema que conduce a resultados incorrectos o inesperados.
```suggestion
Un bug es un defecto o un problema que conduce a resultados incorrectos o inesperados.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +El desarrollo de software es una actividad compleja que hace que sea casi imposible escribir código sin introducir errores.
```suggestion
El desarrollo de software es una actividad compleja que hace que sea casi imposible escribir código sin introducir bugs.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Esos errores conducen a un código que probablemente no funcionará como se desea (comportamiento indefinido) cuando se ejecute.
```suggestion
Esos bugs conducen a un código que probablemente no funcionará como se desea (un comportamiento no definido) cuando se ejecute.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Por lo general, el código de la aplicación tiene que pasar por diferentes etapas o entornos en los que se prueba.
```suggestion
Por lo general, el código de la aplicación tiene que pasar por diferentes etapas o ambientes en los que se prueba.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Cuando aparecen errores, los ingenieros tienen que depurar (p. ej., encontrar y reparar) la aplicación para disminuir el comportamiento no deseado de los sistemas de producción.
```suggestion
Cuando aparecen bugs, los ingenieros tienen que depurar (p. ej., encontrar y reparar) la aplicación para disminuir el comportamiento no deseado de los sistemas de producción.
```

2022-11-29 17:26 UTC, electrocucaracha commented on content/es/debugging.md
> +Una vez que han identificado la fuente de la falla, corrigen el código y crean una corrección de errores o un parche.
```suggestion
Una vez que han identificado la fuente de la falla, corrigen el código y crean un bug fix o parche.
```

2022-12-06 15:19 UTC, 92nqb requested changes
@vasucp1207 Thanks for contributing, I've added few comments

2022-12-06 15:19 UTC, 92nqb commented on content/es/debugging.md
> +Por lo general, el código de la aplicación tiene que pasar por diferentes etapas o ambientes en los que se prueba.
```suggestion
Por lo general, el código de una aplicación tiene que pasar por diferentes etapas o entornos en los que se prueba.
```

2022-12-06 15:19 UTC, 92nqb commented on content/es/debugging.md
> +Una vez que han identificado la fuente de la falla, corrigen el código y crean un bug fix o parche.
```suggestion
Una vez que han identificado el origen del error, corrigen el código y crean un bug fix o parche.
```

2022-12-06 20:37 UTC, electrocucaracha approved these changes

2022-12-13 17:10 UTC, 92nqb approved these changes
lgtm

2022-12-13 17:11 UTC, merged