Add /pt-br/infrastructure-as-a-service.md
cncf/glossary pull request #1474
Opened 2022-11-20 13:22 UTC by MrErlison

Signed-off-by: Mr. Erlison <sisal.cordame_0a@icloud.com>

Added translation for portuguese of the term infrastructure as a service.

resolves #827

- [x] This PR does not contain plagiarism
- [x] I have signed off on all commits

2022-11-25 16:59 UTC, edsoncelio requested changes
Just a few typos, after that will be LGTM, thanks!

2022-11-25 16:59 UTC, edsoncelio commented on content/pt-br/infrastructure-as-a-service.md
> +Infraestrutura como serviço, ou IaaS, é um modelo de serviço de [computação em nuvem](/pt-br/cloud-computing/) que oferece máquinas [física](/pt-br/bare-metal-machine/) ou [virtualizada](/pt-br/virtu
typo: `máquinas física` -> `máquinas físicas`

2022-11-25 16:59 UTC, edsoncelio commented on content/pt-br/infrastructure-as-a-service.md
> +Em configurações tradicionais (_on-premise_), as organizações geralmente concentram seus enforços no uso efetivo de recursos de computação.
typo: `enforços` -> `esforços`

2022-12-01 17:47 UTC, edsoncelio approved these changes
LGTM

2023-03-15 17:41 UTC, jessicalins approved these changes
LGTM, thanks!

2023-03-15 22:34 UTC, merged