[Spanish] localize 'Digital Certificate
cncf/glossary pull request #1499
Opened 2022-11-28 19:22 UTC by vasucp1207

Signed-off-by: Vasu Singh <vasucp1207@gmail.com>

### Describe your changes
[Spanish] localize 'Digital Certificate

### Related issue https://github.com/cncf/glossary/issues/1371

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-11-29 17:56 UTC, electrocucaracha requested changes

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +categoría: tecnología
```suggestion
title: Certificado Digital
status: Feedback Appreciated
category: Tecnología
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +## Lo que es
```suggestion
## ¿Qué es?
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +## Cómo ayuda
```suggestion
## ¿Cómo ayuda?
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +Un certificado (digital), también conocido como certificado de clave pública o certificado SSL, es un documento digital que se utiliza para ayudar a proteger las comunicaciones a través de la red.
```suggestion
Un certificado (digital), también conocido como certificado de clave pública o certificado SSL, es un documento digital utilizado para ayudar a proteger las comunicaciones que ocurren a través de la red.
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +Los certificados nos permiten saber que la entidad particular con la que nos estamos comunicando es quien dice ser.
```suggestion
Los certificados nos permiten conocer la entidad en particular con la que nos estamos comunicando y si es quien dice ser.
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +Los clientes de correo electrónico modernos que utilizan certificados pueden notificarle si la identidad del remitente es correcta, al igual que los navegadores web (observe el pequeño candado frente
```suggestion
Los clientes de correo electrónico modernos que utilizan certificados pueden notificar si la identidad del remitente es correcta, al igual que los navegadores web (vea el pequeño candado frente a la barra de direcciones en su navegador web).
```

2022-11-29 17:56 UTC, electrocucaracha commented on content/es/digital-certificate.md
> +Proporcionan una técnica de encriptación que hace que sea casi imposible que alguien que intercepte la comunicación pueda leer los datos.
```suggestion
Proporcionan una técnica de encriptación que hace que sea casi imposible que alguien que intercepte la comunicación y pueda leer los datos.

## Términos relacionados
```

2022-12-02 23:24 UTC, krol3 approved these changes
lgtm!  @vasucp1207  Please fix the Spellcheck, you need to add the word `ssl`

2022-12-03 07:21 UTC, vasucp1207 commented
> lgtm! @vasucp1207 Please fix the Spellcheck, you need to add the word `ssl`

I do not get it can you please specify more about it?

2022-12-03 20:16 UTC, electrocucaracha commented
> > lgtm! @vasucp1207 Please fix the Spellcheck, you need to add the word `ssl`
> 
> I do not get it can you please specify more about it?

There is a CI task that checks for spelling errors in the Spanish content. The task extends its internal dictionary with more words defined in this [list](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt). This PR requires the addition of new words in that list, otherwise CI [task won't pass](https://github.com/cncf/glossary/actions/runs/3607532915/jobs/6079607326#step:5:13)

Could you include those words into that file? And also make sure that they are added in [alphabetical order](https://github.com/cncf/glossary/blob/dev-es/.github/workflows/es-spellcheck.yml#L27-L30).

2022-12-05 17:25 UTC, vasucp1207 commented
@electrocucaracha, I updated the wordlist file when that merges then I also update this PR.

2022-12-05 17:50 UTC, electrocucaracha commented
> @electrocucaracha, I updated the wordlist file when that merges then I also update this PR.

You have to include those changes in this PR to make the Spellchecker CI pass.

2022-12-05 21:26 UTC, vasucp1207 commented
@electrocucaracha, check now.

2022-12-05 21:47 UTC, vasucp1207 commented
@electrocucaracha, check now.

2022-12-06 15:21 UTC, 92nqb requested changes

2022-12-06 15:21 UTC, 92nqb commented on content/es/digital-certificate.md
> +Proporcionan una técnica de cifrada que hace que sea casi imposible que alguien que intercepte la comunicación y pueda leer los datos.
```suggestion
Proporcionan una técnica de cifrado que hace que sea casi imposible que alguien que intercepte la comunicación y pueda leer los datos.
```

2022-12-13 17:13 UTC, 92nqb approved these changes
lgtm

2022-12-13 17:14 UTC, merged