1398 spanish localize nodes
cncf/glossary pull request #1505
Opened 2022-12-01 02:33 UTC by mdf-ido

### Describe your changes

Adding the definition of Nodes in Spanish. 

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #1398 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2022-12-01 17:09 UTC, electrocucaracha requested changes

2022-12-01 17:09 UTC, electrocucaracha commented on content/es/nodes.md
> +tags: ["arquitectura"]
```suggestion
tags: ["architecture"]
```

2022-12-01 17:09 UTC, electrocucaracha commented on content/es/nodes.md
> +Un nodo es un servidor que trabaja en conjunto a otros servidores, o nodos, para realizar una tarea común. Por ejemplo, tu laptop, el módem y la impresora están conectados a través de tu red wifi com
```suggestion
Un nodo es un servidor que trabaja en conjunto a otros servidores, o nodos, para realizar una tarea común. Por ejemplo, tu laptop, el módem y la impresora están conectados a través de tu red wifi comunicándose y colaborando, y cada uno representa un nodo. En [computación en la nube](/es/cloud-computing/), un nodo puede ser un servidor físico, un servidor virtual, denominado [VM](/virtual-machine/), o incluso un [contenedor](/container/).
```

2022-12-01 17:09 UTC, electrocucaracha commented on content/es/nodes.md
> +Una aplicación podría (y muchas lo hacen) ejecutarse en una sola máquina, esto conlleva algunos riesgos como el fallo del sistema subyacente interrumpira la aplicación. Para solucionar esto, los desa
```suggestion
Una aplicación podría (y muchas lo hacen) ejecutarse en una sola máquina, esto conlleva algunos riesgos como el fallo del sistema subyacente interrumpira la aplicación. Para solucionar esto, los desarrolladores comenzaron a crear [aplicaciones distribuidas](/distributed-apps/) donde cada proceso se ejecuta en su propio nodo. Así, los nodos ejecutan aplicaciones o procesos como parte de un grupo que forma un [clúster](/es/cluster/), o grupo, de nodos que trabajan juntos para lograr un objetivo común.
```

2022-12-01 17:09 UTC, electrocucaracha commented on content/es/nodes.md
> +Un nodo es una unidad de cálculo distinta (memoria, CPU, red) que se puede asignar a un clúster. En una plataforma o aplicación [nativa de la nube](/cloud-native-tech/) un nodo representa una única u
```suggestion
Un nodo es una unidad de cálculo distinta (memoria, CPU, red) que se puede asignar a un clúster. En una plataforma o aplicación [nativa para la nube](/es/cloud-native-tech/) un nodo representa una única unidad que puede realizar trabajo. Idealmente, los nodos individuales son indiferenciados en el sentido de que cualquier nodo de un tipo particular es indistinguible de cualquier otro nodo del mismo tipo.
```

2022-12-02 23:06 UTC, krol3 requested changes
Nice work!

2022-12-02 23:06 UTC, krol3 commented on content/es/nodes.md
> +Un nodo es un servidor que trabaja en conjunto a otros servidores, o nodos, para realizar una tarea común. Por ejemplo, tu laptop, el módem y la impresora están conectados a través de tu red wifi com
```suggestion
Un nodo es un servidor que trabaja en conjunto a otros servidores, o nodos, para realizar una tarea común. Por ejemplo, tu laptop, el módem y la impresora están conectados a través de tu red wifi comunicándose y colaborando, cada uno representa un nodo. En [computación en la nube](/es/cloud-computing/), un nodo puede ser un servidor físico, un servidor virtual, denominado [VM](/virtual-machine/), o incluso un [contenedor](/container/).
```

2022-12-02 23:06 UTC, krol3 commented on content/es/nodes.md
> +Una aplicación podría (y muchas lo hacen) ejecutarse en una sola máquina, esto conlleva algunos riesgos como el fallo del sistema subyacente interrumpira la aplicación. Para solucionar esto, los desa
```suggestion
Una aplicación podría (y muchas lo hacen) ejecutarse en una sola máquina, esto conlleva algunos riesgos como el fallo del sistema subyacente interrumpirá la aplicación. Para solucionar esto, los desarrolladores comenzaron a crear [aplicaciones distribuidas](/distributed-apps/) donde cada proceso se ejecuta en su propio nodo. Así, los nodos ejecutan aplicaciones o procesos como parte de un grupo que forma un [clúster](/es/cluster/), o grupo, de nodos que trabajan juntos para lograr un objetivo común.
```

2022-12-13 18:00 UTC, electrocucaracha commented
@mdf-ido podrías agregar `VM` en la lista de palabras para poder aprobar este cambio?

2022-12-13 23:38 UTC, electrocucaracha approved these changes

2023-01-05 16:41 UTC, electrocucaracha commented
@krol3 podrías revisar nuevamente estos cambios?

2023-01-07 03:23 UTC, merged

2023-01-07 03:27 UTC, mdf-ido commented
@electrocucaracha - Todo bien con esto o necesita alguna actualización de mi parte?

2023-01-07 03:33 UTC, electrocucaracha commented
@mdf-ido listo, ya lo agregue al branch *dev-es* y en algún momento pondremos todos los cambios en *main* muchas gracias