Localization Reliability lang/bn
cncf/glossary pull request #1608
Opened 2023-01-10 10:06 UTC by abhijeet-26

Signed-off-by: Abhijeet Basfore abhibas14@gmail.com

Signed-off-by: Abhijeet Basfore <68768410+abhijeet-26@users.noreply.github.com>

### Describe your changes
Bengali Version - Reliability
link- https://glossary.cncf.io/reliability/

### Related issue number or link (ex: `resolves #issue-number`)
#410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-10 10:54 UTC, mitul3737 requested changes

2023-01-10 10:54 UTC, mitul3737 commented on content/bn/reliability.md
> +যদি আমাদের একটি বিতরণ ব্যবস্থা ([distributed system](/distributed-systems/)) থাকে যা পরিকাঠামো পরিবর্তন এবং পৃথক উপাদানগুলি
```suggestion
যদি আমাদের একটি বিতরণ ব্যবস্থা ([distributed system](/bn/distributed-systems/)) থাকে যা পরিকাঠামো পরিবর্তন এবং পৃথক উপাদানগুলি 
```

2023-01-10 10:54 UTC, mitul3737 commented on content/bn/reliability.md
> +ক্লাউড নেটিভ অ্যাপ্লিকেশনের ([cloud native applications](/cloud-native-apps/)) লক্ষ্য হল সহজাতভাবে নির্ভরযোগ্য সিস্টেম তৈরি করা।
```suggestion
ক্লাউড নেটিভ অ্যাপ্লিকেশনের ([cloud native applications](/bn/cloud-native-apps/)) লক্ষ্য হল সহজাতভাবে নির্ভরযোগ্য সিস্টেম তৈরি করা।
```

2023-01-13 13:11 UTC, mitul3737 approved these changes
LGTM

2023-01-13 13:11 UTC, Imtiaz1234 approved these changes
LGTM

2023-01-13 13:11 UTC, merged