Update observability term
cncf/glossary pull request #1610
Opened 2023-01-10 15:57 UTC by electrocucaracha

### Describe your changes
This change synchronizes the changes made on the `observability` term to the Spanish version.

### Related issue number or link (ex: `resolves #issue-number`)
NA

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-10 16:57 UTC, krol3 approved these changes
LGTM

2023-01-17 12:54 UTC, 92nqb requested changes
I've added some comments

2023-01-17 12:54 UTC, 92nqb commented on content/es/observability.md
> +En otras palabras, la observabilidad permite a los usuarios comprender el estado de un sistema a partir de su salida externa y tomar medidas (correctivas).
```suggestion
En otras palabras, la observabilidad permite a los usuarios comprender el estado de un sistema a partir de su salida externa y así tomar medidas (correctivas).
```

2023-01-17 12:54 UTC, 92nqb commented on content/es/observability.md
> +Entendiendo de que más información no necesariamente significa que en un sistema sea más observable es esencial.
```suggestion
Es esencial entender que más información no necesariamente significa que en un sistema sea más observable.
```

2023-01-17 12:54 UTC, 92nqb commented on content/es/observability.md
> +De hecho, a veces, la cantidad de información generada por un sistema puede dificultar la identificación de señales de salud valiosas a partir del ruido generado por la aplicación.
```suggestion
De hecho, a veces, la cantidad de información generada por un sistema puede dificultar la identificación de señales de salud valiosas debido al ruido generado por la aplicación.
```

2023-01-18 02:23 UTC, krol3 approved these changes
LGTM

2023-01-18 08:44 UTC, 92nqb approved these changes
LGTM

2023-01-18 08:45 UTC, merged