Add api-gateway-hindi.md
cncf/glossary pull request #1614
Opened 2023-01-11 09:40 UTC by AniketNS

Signed-off-by: Aniket Shitole <91371143+AniketNS@users.noreply.github.com>

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-07 01:09 UTC, jihoon-seo reviewed
@AniketNS Thank you for your contribution.
But please:
- rename the file from `content/hi/api-gateway-hindi.md` to `content/hi/api-gateway.md` .
- change the target branch to `dev-hi`, not `main`.
  (to do so, first you will need to branch off your feature branch from `dev-hi`, not `main`.)

FYI: This PR resolves #1540.

2023-02-07 19:39 UTC, AniketNS commented
Hello @jihoon-seo, I've made the changes please check and tell me if you want something else.

2023-06-28 14:42 UTC, anubha-v-ardhan requested changes

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +एपीआय गेटवे एक ऐसा उपकरण है जो अद्वितीय एप्लिकेशन एपीआय को एकत्र करता है, जिससे वे सभी एक ही स्थान पर उपलब्ध हो जाते हैं।
```suggestion
[एपीआइ](/application-programming-interface/) गेटवे एक ऐसा उपकरण है जो अद्वितीय एप्लिकेशन एपीआइ को एकत्र करता है, जिससे वे सभी एक ही स्थान पर उपलब्ध हो जाते हैं।
```

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +एपीआय गेटवे (अक्सर बाहरी) एपीआय उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।
```suggestion
एपीआइ गेटवे (अक्सर बाहरी) एपीआइ उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।
```

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +यदि आप बाहरी उपभोक्ताओं के लिए एपीआय उपलब्ध करा रहे हैं, तो आप सभी पहुंच को प्रबंधित और नियंत्रित करने के लिए एक प्रवेश बिंदु चाहते हैं।
```suggestion
यदि आप बाहरी उपभोक्ताओं के लिए एपीआइ उपलब्ध करा रहे हैं, तो आप सभी पहुंच को प्रबंधित और नियंत्रित करने के लिए एक प्रवेश बिंदु चाहते हैं। 
```

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +इसके अतिरिक्त, यदि आपको उन इंटरैक्शन पर कार्यक्षमता लागू करने की आवश्यकता है, तो एक एपीआय गेटवे आपको बिना किसी ऐप कोड परिवर्तन की आवश्यकता के इसे सभी
```suggestion
इसके अतिरिक्त, यदि आपको उन इंटरैक्शन पर कार्यक्षमता लागू करने की आवश्यकता है, तो एक एपीआइ गेटवे आपको बिना किसी ऐप कोड परिवर्तन की आवश्यकता के इसे सभी 
```

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +एक एप्लिकेशन में विभिन्न एपीआय के लिए एक एकल पहुंच बिंदु प्रदान करना, एपीआय गेटवे संगठनों के लिए एक केंद्रीय स्थान में क्रॉस-कटिंग व्यवसाय या सुरक्षा तर्क को लागू करना आसान बनाता है।
```suggestion
एक एप्लिकेशन में विभिन्न एपीआइ के लिए एक एकल पहुंच बिंदु प्रदान करना, एपीआइ गेटवे संगठनों के लिए एक केंद्रीय स्थान में क्रॉस-कटिंग व्यवसाय या सुरक्षा को लागू करना आसान बनाता है। 
```

2023-06-28 14:42 UTC, anubha-v-ardhan commented on content/hi/api-gateway.md
> +जैसा कि सभी अनुरोध एपीआय गेटवे के माध्यम से प्रवाहित होते हैं, यह मेट्रिक्स-एकत्रीकरण, दर-सीमित और प्राधिकरण जैसी कार्यक्षमता जोड़ने के लिए एक ही स्थान प्रस्तुत करता है।
```suggestion
एक एपीआइ गेटवे सिस्टम में सभी वेब सेवाओं के अनुरोधों के लिए एकल पहुंच बिंदु प्रदान करके सुरक्षा और अवलोकन जैसी परिचालन संबंधी चिंताओं को सरल बना सकता है। 
जैसा कि सभी अनुरोध एपीआइ गेटवे के माध्यम से प्रवाहित होते हैं, यह मेट्रिक्स-एकत्रीकरण, दर-सीमित और प्राधिकरण जैसी कार्यक्षमता जोड़ने के लिए एक ही स्थान प्रस्तुत करता है।
```

2023-10-08 04:33 UTC, aj11anuj commented
@AniketNS friendly ping for implementing suggested changes on this PR

2023-11-08 19:06 UTC, kumarankit999 reviewed
Have you Resolved all the issues in this PR? if not, then resolve first and make changes!

2023-11-10 05:46 UTC, AniketNS reviewed
I've made the suggested changes. Please check and let me know if there are any other corrections.

2023-11-10 05:47 UTC, AniketNS commented on content/hi/api-gateway.md
> +एक एप्लिकेशन में विभिन्न एपीआय के लिए एक एकल पहुंच बिंदु प्रदान करना, एपीआय गेटवे संगठनों के लिए एक केंद्रीय स्थान में क्रॉस-कटिंग व्यवसाय या सुरक्षा तर्क को लागू करना आसान बनाता है।
Done

2023-11-10 05:47 UTC, AniketNS commented on content/hi/api-gateway.md
> +एक एप्लिकेशन में विभिन्न एपीआय के लिए एक एकल पहुंच बिंदु प्रदान करना, एपीआय गेटवे संगठनों के लिए एक केंद्रीय स्थान में क्रॉस-कटिंग व्यवसाय या सुरक्षा तर्क को लागू करना आसान बनाता है।
Done

2023-11-10 05:48 UTC, AniketNS commented on content/hi/api-gateway.md
> +---
All done

2023-11-11 01:28 UTC, aj11anuj requested changes

2023-11-11 01:28 UTC, aj11anuj commented on content/hi/api-gateway.md
> +title: एपीआइ गेटवे (API Gateway)
```suggestion
title: एपीआई गेटवे (API Gateway)
```

2023-11-11 01:28 UTC, aj11anuj commented on content/hi/api-gateway.md
> +
```suggestion
## यह क्या है?

[एपीआई](/application-programming-interface/) गेटवे एक ऐसा उपकरण है जो अद्वितीय एप्लिकेशन एपीआई को एकत्र करता है, जिससे वे सभी एक ही स्थान पर उपलब्ध हो जाते हैं।
यह संगठनों को प्रमुख कार्यों को स्थानांतरित करने की अनुमति देता है, जैसे प्रमाणीकरण और प्राधिकरण या अनुप्रयोगों के बीच अनुरोधों की संख्या को केंद्रीय रूप से प्रबंधित स्थान पर सीमित करना। 
एपीआई गेटवे (अक्सर बाहरी) एपीआई उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करते हैं।

```

2023-11-11 01:28 UTC, aj11anuj commented on content/hi/api-gateway.md
> +यदि आप बाहरी उपभोक्ताओं के लिए एपीआइ उपलब्ध करा रहे हैं, तो आप सभी पहुंच को प्रबंधित और नियंत्रित करने के लिए एक प्रवेश बिंदु चाहते हैं।
```suggestion
यदि आप बाहरी उपभोक्ताओं के लिए एपीआई उपलब्ध करा रहे हैं, तो आप सभी पहुंच को प्रबंधित और नियंत्रित करने के लिए एक प्रवेश बिंदु चाहते हैं। 
```

2023-11-11 01:28 UTC, aj11anuj commented on content/hi/api-gateway.md
> +जैसा कि सभी अनुरोध एपीआइ गेटवे के माध्यम से प्रवाहित होते हैं, यह मेट्रिक्स-एकत्रीकरण, दर-सीमित और प्राधिकरण जैसी कार्यक्षमता जोड़ने के लिए एक ही स्थान प्रस्तुत करता है।
```suggestion
एक एप्लिकेशन में विभिन्न एपीआई के लिए एक एकल पहुंच बिंदु प्रदान करना, एपीआई गेटवे संगठनों के लिए एक केंद्रीय स्थान में क्रॉस-कटिंग व्यवसाय या सुरक्षा को लागू करना आसान बनाता है।
वे एप्लिकेशन उपभोक्ताओं को उनकी सभी जरूरतों के लिए एक ही पते पर जाने की अनुमति भी देते हैं। 
एक एपीआई गेटवे सिस्टम में सभी वेब सेवाओं के अनुरोधों के लिए एकल पहुंच बिंदु प्रदान करके सुरक्षा और अवलोकन जैसी परिचालन संबंधी चिंताओं को सरल बना सकता है। 
जैसा कि सभी अनुरोध एपीआई गेटवे के माध्यम से प्रवाहित होते हैं, यह मेट्रिक्स-एकत्रीकरण, दर-सीमित और प्राधिकरण जैसी कार्यक्षमता जोड़ने के लिए एक ही स्थान प्रस्तुत करते हैं।
```

2023-11-14 15:37 UTC, kumarankit999 approved these changes
lgtm

2023-11-16 01:10 UTC, aj11anuj approved these changes
Changes looks good to me

@AniketNS DCO checks of this PR is failing, can you fix it?
(Till DCO checks are not passed)
/hold

2023-11-16 08:08 UTC, AniketNS commented
> Changes looks good to me
> 
> @AniketNS DCO checks of this PR is failing, can you fix it? (Till DCO checks are not passed) /hold

Can you please tell me, how can I do that?

2023-11-16 14:05 UTC, aj11anuj commented
Squash your commits, and while squashing add "Signed-off-by: Aniket Shitole [91371143+AniketNS@users.noreply.github.com](mailto:91371143+AniketNS@users.noreply.github.com)" as commit description
.

2023-12-12 14:25 UTC, merged