[hi] Localize kubernetes.md to Hindi
cncf/glossary pull request #1615
Opened 2023-01-11 10:12 UTC by Omkar0114

Signed-off-by: Omkar kulkarni <88308267+Omkar0114@users.noreply.github.com>

Localize kubernetes.md to Hindi

resolve #1588

- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-17 11:31 UTC, Omkar0114 commented
Hey, @Garima-Negi , @jayesh-srivastava , @sayantani11 @anubha-v-ardhan can you take a look on this PR? And suggest any changes !

2023-06-28 14:44 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +---
```suggestion
---
title: कुबेरनेट्स (Kubernetes)
status: Completed
category: प्रौद्योगिकी
tags: ["infrastructure", "fundamental", ""]
---
```

2023-06-28 14:44 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +## समस्या जिसे यह संबोधित करता है
```suggestion
## समस्या 
```

2023-06-28 14:45 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +## यह कैसे मदद करता है
```suggestion
## समाधान
```

2023-06-28 14:46 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +यह एक "डेटासेंटर ऑपरेटिंग सिस्टम" के रूप में कार्य करते हुए आधुनिक बुनियादी ढांचे पर कंटेनरीकृत अनुप्रयोगों के जीवनचक्र को स्वचालित करता है जो एक [वितरित प्रणाली](/distributed-systems/) में अनुप्रयोग
```suggestion
यह एक "डेटासेंटर ऑपरेटिंग सिस्टम" के रूप में कार्य करते हुए आधुनिक बुनियादी ढांचे पर कंटेनरीकृत एप्लीकेशन के जीवनचक्र को स्वचालित करता है जो एक [वितरित प्रणाली](/distributed-systems/) में एप्लीकेशन का प्रबंधन करता है।
```

2023-06-28 14:48 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +कुबेरनेट्स [कंटेनर](/container/) [नोड्स](/nodes/) में एक [क्लस्टर](/cluster/) में शेड्युल करता है। कंटेनरीकृत अनुप्रयोगों को चलाने के लिए लोड बैलेंसर, लगातार भंडारण, आदि जैसे कई बुनियादी ढांचे के संस
```suggestion
कुबेरनेट्स [कंटेनर](/container/) को [नोड्स](/nodes/) में एक [क्लस्टर](/cluster/) में शेड्युल करता है। कंटेनरीकृत एप्लीकेशन को चलाने के लिए लोड बैलेंसर, आग्रही (persistent) स्टोरेज, आदि जैसे कई बुनियादी ढांचे के संसाधनों को बंडल करता है।
```

2023-06-28 14:49 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +कुबेरनेट्स स्वचालन और विस्तारणीयता को सक्षम करता है, जिससे उपयोगकर्ता पुनरुत्पादित तरीके से घोषणात्मक रूप से (नीचे देखें) अनुप्रयोगों को तैनात कर सकते हैं।
```suggestion
कुबेरनेट्स स्वचालन और विस्तारणीयता को सक्षम करता है, जिससे उपयोगकर्ता पुनरुत्पादित तरीके से घोषणात्मक रूप से (नीचे देखें) एप्लीकेशन को तैनात कर सकते हैं।
```

2023-06-28 14:51 UTC, anubha-v-ardhan commented on content/hi/kubernetes.md
> +कुबेरनेट्स [स्वयं](/सेल्फ-हीलिंग/) ठीक हो जाता है।
```suggestion
कुबेरनेट्स [स्वयं](/self-healing/) ठीक हो जाता है।
```

2023-06-30 15:26 UTC, Omkar0114 commented on content/hi/kubernetes.md
> +---
Updated :)

2023-06-30 15:26 UTC, Omkar0114 commented on content/hi/kubernetes.md
> +## यह कैसे मदद करता है
updated

2023-06-30 15:26 UTC, Omkar0114 commented on content/hi/kubernetes.md
> +कुबेरनेट्स [कंटेनर](/container/) [नोड्स](/nodes/) में एक [क्लस्टर](/cluster/) में शेड्युल करता है। कंटेनरीकृत अनुप्रयोगों को चलाने के लिए लोड बैलेंसर, लगातार भंडारण, आदि जैसे कई बुनियादी ढांचे के संस
Updated :+1:

2023-06-30 15:26 UTC, Omkar0114 commented on content/hi/kubernetes.md
> +कुबेरनेट्स [स्वयं](/सेल्फ-हीलिंग/) ठीक हो जाता है।
updated

2023-06-30 15:29 UTC, Omkar0114 commented
Hi, @anubha-v-ardhan Updated docs with your suggestions, have a look once. Suggest any changes if needed :)

2023-06-30 16:17 UTC, anubha-v-ardhan approved these changes
LGTM!

Please wait for one more approval from another maintainer before we can merge this.

2023-07-03 05:23 UTC, Omkar0114 commented
Hi, one approved is there! Anyone can review it @Garima-Negi @sayantani11 @jayesh-srivastava

2023-09-07 14:57 UTC, Omkar0114 commented
Hey @anubha-v-ardhan @sayantani11 @Garima-Negi @jayesh-srivastava Anyone can review this PR as one LGTM has been added!

2023-10-06 07:33 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-06 07:33 UTC, aj11anuj commented on content/hi/kubernetes.md
> +यह एक "डेटासेंटर ऑपरेटिंग सिस्टम" के रूप में कार्य करते हुए आधुनिक बुनियादी ढांचे पर कंटेनरीकृत एप्लीकेशन के जीवनचक्र को स्वचालित करता है जो एक [वितरित प्रणाली](/distributed-systems/) में एप्लीकेशन क
```suggestion
यह एक "डेटासेंटर ऑपरेटिंग सिस्टम" के रूप में कार्य करते हुए आधुनिक इन्फ्रा़स्ट्रक्चर पर कंटेनरीकृत एप्लीकेशन के जीवनचक्र को स्वचालित करता है जो एक [वितरित प्रणाली](/distributed-systems/) में एप्लीकेशन का प्रबंधन करता है।
```

2023-10-06 07:33 UTC, aj11anuj commented on content/hi/kubernetes.md
> +कुबेरनेट्स [कंटेनर](/container/) को [नोड्स](/nodes/) में एक [क्लस्टर](/cluster/) में शेड्युल करता है। कंटेनरीकृत एप्लीकेशन को चलाने के लिए लोड बैलेंसर, आग्रही (persistent) स्टोरेज, आदि जैसे कई बुनिया
```suggestion
कुबेरनेट्स [कंटेनर](/container/) को [नोड्स](/nodes/) के एक [क्लस्टर](/cluster/) में शेड्युल करता है। कंटेनरीकृत एप्लीकेशन को चलाने के लिए लोड बैलेंसर, सतत (persistent) स्टोरेज, आदि जैसे कई इन्फ्रा़स्ट्रक्चर के संसाधनों को बंडल करता है।
```

2023-10-06 07:33 UTC, aj11anuj commented on content/hi/kubernetes.md
> +जैसे-जैसे कम्प्यूट संसाधनों की मांग बढ़ती है और संगठनों को कम इंजीनियरों के साथ अधिक परिचालन क्षमता प्रदान करने की आवश्यकता होती है, उस मांग को पूरा करने के लिए नई तकनीकों और कार्य विधियों की आवश्यकत
```suggestion
जैसे-जैसे कम्प्यूट संसाधनों की मांग बढ़ती है और संगठनों को कम इंजीनियरों के साथ अधिक आयोजन करने की क्षमता प्रदान करने की आवश्यकता होती है, उस मांग को पूरा करने के लिए नई तकनीकों और कार्य विधियों की आवश्यकता होती है।
```

2023-11-12 05:16 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-14 15:38 UTC, kumarankit999 approved these changes
lgtm

2023-11-14 16:24 UTC, merged