[it] Localizzazione Application Programming Interface (API)
cncf/glossary pull request #1619
Opened 2023-01-13 15:08 UTC by ugho16

Signed-off-by: Paolo <ugho16@users.noreply.github.com>

### Describe your changes
Added API italian localization

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1601 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-18 07:40 UTC, annalisag-spark requested changes

2023-01-18 07:40 UTC, annalisag-spark commented on content/it/application-programming-interface.md
> +Sono gli elementi costitutivi delle moderne applicazioni e forniscono agli sviluppatori un modo per integrare le applicazioni tra loro.
```suggestion
Sono gli elementi costitutivi delle moderne applicazioni e forniscono agli sviluppatori un modo per integrarle tra loro.
```

2023-03-30 11:13 UTC, annalisag-spark commented on content/it/application-programming-interface.md
> +title: Application Programming Interface (API)
Interfaccia di Programmazione delle Applicazioni (API)

2023-05-09 12:28 UTC, sistella requested changes

2023-05-09 12:28 UTC, sistella commented on content/it/application-programming-interface.md
> +Senza un framework condiviso, per le applicazioni è difficile [scalare](/it/scalability/) e integrarsi.
```suggestion
Senza un framework condiviso, per le applicazioni è difficile implementare la [scalabilità](/it/scalability/) e integrarsi.
```
Il verbo italiano "scalare" non ha il significato di "to scale"...

2023-05-09 15:08 UTC, sistella approved these changes

2023-05-10 07:48 UTC, merged