[it] Localization security-chaos-engineering.md
cncf/glossary pull request #1629
Opened 2023-01-17 16:09 UTC by annalisag-spark

Signed-off-by: annalisag-spark <83414097+annalisag-spark@users.noreply.github.com>

### Describe your changes
Localization of Security Chaos Engineering

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-17 16:22 UTC, ugho16 requested changes

2023-01-17 16:22 UTC, ugho16 commented on content/it/security-chaos-engineering.md
> +Security Chaos Engineering o SCE è una disciplina basata su [Chaos Engineering](it/chaos-engineering/).
```suggestion
Security Chaos Engineering o SCE è una disciplina basata su [Chaos Engineering](/it/chaos-engineering/).
```

2023-01-17 16:22 UTC, ugho16 commented on content/it/security-chaos-engineering.md
> +La priorità principale per i [site reliability engineers](it/site-reliability-engineering/) (SRE) e gli ingegneri della sicurezza informatica è
```suggestion
La priorità principale per i [site reliability engineers](/it/site-reliability-engineering/) (SRE) e gli ingegneri della sicurezza informatica è
```

2023-01-17 16:22 UTC, ugho16 commented on content/it/security-chaos-engineering.md
> +Security Chaos Engineering si basa su [osservabilità](it/observability/) e pratiche di resilienza informatica.
```suggestion
Security Chaos Engineering si basa su [osservabilità](/it/observability/) e pratiche di resilienza informatica.
```

2023-01-17 16:22 UTC, ugho16 commented on content/it/security-chaos-engineering.md
> +SCE migliora la resilienza informatica dell'intero prodotto, identificare problemi di sicurezza nascosti,
```suggestion
SCE migliora la resilienza informatica dell'intero prodotto, identifica problemi di sicurezza nascosti,
```

2023-01-17 16:22 UTC, ugho16 commented on content/it/security-chaos-engineering.md
> +Questo approccio aiuta gli ingegneri SRE, [DevOps](it/devops/) e [DevSecOps](it/devsecops/) a
```suggestion
Questo approccio aiuta gli ingegneri SRE, [DevOps](/it/devops/) e [DevSecOps](/it/devsecops/) a
```

2023-01-18 08:56 UTC, ugho16 approved these changes

2023-05-10 14:06 UTC, annalisag-spark commented
@sistella 😇

2023-06-05 08:18 UTC, sistella submitted a review, later dismissed
la review più tosta dell'anno! mi sa che dobbiamo parlarne comunque....

2023-06-05 08:18 UTC, sistella commented on content/it/security-chaos-engineering.md
> +Gli SRE e gli ingegneri della sicurezza informatica intervengono sia in situazioni critiche che precedono il guasto, sia post-mortem.
Penso che con incident situations si voglia indicare le situazioni in cui l'incidente si è proprio verificato, dunque non solo una situazione critica. E il post-mortem è una valutazione a bocce ferme, mentre magari qui si sta prendendo in considerazione un tempo più prossimo all'incident.... 
```suggestion
Gli SRE e gli ingegneri della sicurezza informatica sono coinvolti in caso di incidente, sia prima, sia dopo il guasto.
```

2023-09-04 13:30 UTC, fsbaraglia commented on content/it/security-chaos-engineering.md
> +tra cui stato stazionario, ipotesi, verifica continua, lessons learned e implementazione delle mitigazioni.
@sistella  :D tra l'altro questo termine l'ho scritto io in inglese :D

2023-09-04 13:33 UTC, fsbaraglia requested changes

2023-09-04 13:33 UTC, fsbaraglia commented on content/it/security-chaos-engineering.md
> +tra cui stato stazionario, ipotesi, verifica continua, lessons learned e implementazione delle mitigazioni.
```suggestion
tra cui lo stato stazionario (steady state), ipotesi, verifica continua, lessons learned e implementazione delle mitigazioni.
```

2023-09-06 22:11 UTC, fsbaraglia approved these changes

2023-09-06 22:11 UTC, merged