Update cloud_native_tech.md
cncf/glossary pull request #163
Opened 2021-07-02 13:58 UTC by JasonMorgan

Minor changes and added references to the landscape

2021-07-19 02:26 UTC, murillodigital reviewed
Added comment

2021-07-19 02:26 UTC, murillodigital commented on definitions/cloud_native_tech.md
> +Cloud native technologies, also referred to as the cloud native or new stack, are the technologies used to build [cloud native applications](https://github.com/cncf/glossary/blob/main/definitions/clo
I think adding the use of managed services as a component of cloud native architectures and the value of the cloud is also important.

2021-07-19 12:57 UTC, DanielJonesEB commented
Just dropping a note to say that a review is in my to-do list, I'm just super busy right now. Will hopefully look at it before Friday.

2021-07-21 13:26 UTC, DanielJonesEB requested changes
The inconsistent hyphenation is a hard blocker to merging, and if we can tidy up that other sentence I think that'd be lovely, even if that's more a matter of opinion.

2021-07-21 13:26 UTC, DanielJonesEB commented on definitions/cloud_native_tech.md
> +The cloud native stack has many different technology categories, addressing a variety of challenges. If you have a look at the [CNCF Cloud Native Landscape](https://landscape.cncf.io/), you'll see ho
The last sentence is a little cumbersome due to the negative examples, and I'm sure there should be a "being" after "include". "The list goes on" strikes me as rather conversational for written documentation.

All good with the sentiment though.

2021-07-21 13:26 UTC, DanielJonesEB commented on definitions/cloud_native_tech.md
> +Cloud native technologies, also referred to as the cloud native or new stack, are the technologies used to build [cloud native applications](https://github.com/cncf/glossary/blob/main/definitions/clo
Tech can be cloud native _without_ leveraging managed services. Whilst I agree that this is an important thing for folks to consider and I encourage my customers to use managed services wherever possible, in the context of the glossary we should err on the side of being minimal rather than inclusive.

2021-07-21 13:26 UTC, DanielJonesEB commented on definitions/cloud_native_tech.md
> +While each technology addresses a very specific problem, as a group, cloud native technologies enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust auto
Inconsistent hyphenation of cloud native/cloud-native.

2021-07-21 13:27 UTC, DanielJonesEB commented on definitions/cloud_native_tech.md
> -Cloud native technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, private, and hybrid clouds. They uphold the ‘promise of the clou
Last sentence here parses terribly, so good job for reworking it.

2021-07-21 13:34 UTC, CathPag commented on definitions/cloud_native_tech.md
> +Cloud native technologies, also referred to as the cloud native or new stack, are the technologies used to build [cloud native applications](https://github.com/cncf/glossary/blob/main/definitions/clo
ok, so we'll skip this for now

2021-07-21 13:40 UTC, CathPag commented on definitions/cloud_native_tech.md
> +The cloud native stack has many different technology categories, addressing a variety of challenges. If you have a look at the [CNCF Cloud Native Landscape](https://landscape.cncf.io/), you'll see ho
How does this sound: "Challenges include difficulties creating scalable, fault-tolerant, self-healing applications, as well as inefficient resource utilization, among others."

2021-07-21 13:42 UTC, CathPag commented on definitions/cloud_native_tech.md
> +While each technology addresses a very specific problem, as a group, cloud native technologies enable loosely coupled systems that are resilient, manageable, and observable. Combined with robust auto
updated. At least I think. Isn't reflected in this view

2021-07-21 13:44 UTC, CathPag approved these changes
Wove in requested updates and LGTM

2021-07-21 13:45 UTC, CathPag approved these changes

2021-08-13 13:06 UTC, merged