[it] Localization function-as-a-service.md
cncf/glossary pull request #1630
Opened 2023-01-17 17:15 UTC by annalisag-spark

Signed-off-by: annalisag-spark <83414097+annalisag-spark@users.noreply.github.com>

### Describe your changes
Localized FaaS into Italian.

### Related issue number or link (ex: `resolves #issue-number`)
Resolves issue #1600 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-17 17:29 UTC, ugho16 requested changes

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +Function as a Service (FaaS) è un tipo di [servizio](/service/) di [cloud computing](it/cloud-computing/) [serverless](it/serverless/)
```suggestion
Function as a Service (FaaS) è un tipo di [servizio](/it/service/) di [cloud computing](/it/cloud-computing/) [serverless](/it/serverless/) 
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +tipicamente associata alla creazione e all'avvio di applicazioni a [microservizi](it/microservices/).
```suggestion
tipicamente associata alla creazione e all'avvio di applicazioni a [microservizi](/it/microservices/).
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +[Google Cloud Functions](https://cloud.google.com/functions/) e [icrosoft Azure Functions](https://azure.microsoft.com/it-it/products/functions/).
```suggestion
[Google Cloud Functions](https://cloud.google.com/functions/) e [Microsoft Azure Functions](https://azure.microsoft.com/it-it/products/functions/).
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +Vice versa, se l'azienda cresce rapidamente, il reparto IT potrebbe avere difficoltà a tenere il passo.
```suggestion
Viceversa, se l'azienda cresce rapidamente, il reparto IT potrebbe avere difficoltà a tenere il passo.
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +In base a un modello di cloud computing standard [Infrastructure-as-a-Service (IaaS)](it/infrastructure-as-a-service/),
```suggestion
In base a un modello di cloud computing standard [Infrastructure-as-a-Service (IaaS)](/it/infrastructure-as-a-service/),
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +FaaS offre agli sviluppatori un'[astrazione](it/abstraction/) per l'esecuzione di applicazioni Web in risposta a eventi senza gestire i server.
```suggestion
FaaS offre agli sviluppatori un'[astrazione](/it/abstraction/) per l'esecuzione di applicazioni Web in risposta a eventi senza gestire i server.
```

2023-01-17 17:29 UTC, ugho16 commented on content/it/function-as-a-service.md
> +e lo sviluppatore non dovrà dedicare tempo o risorse alla creazione del codice per garantirne la [scalabilità](it/scalabilità/).
```suggestion
e lo sviluppatore non dovrà dedicare tempo o risorse alla creazione del codice per garantirne la [scalabilità](/it/scalabilità/).
```

2023-01-18 08:56 UTC, ugho16 approved these changes

2023-05-10 14:08 UTC, annalisag-spark commented
@sistella 😇

2023-06-05 08:31 UTC, sistella requested changes
piccole modifiche, per il resto va benissimo!

2023-06-05 08:31 UTC, sistella commented on content/it/function-as-a-service.md
> +Alcuni esempi FaaS popolari includono: [AWS Lambda di Amazon](https://aws.amazon.com/it/lambda/),
è stato rimosso dall'inglese, nel frattempo
```suggestion
```

2023-06-05 08:31 UTC, sistella commented on content/it/function-as-a-service.md
> +[Google Cloud Functions](https://cloud.google.com/functions/) e [Microsoft Azure Functions](https://azure.microsoft.com/it-it/products/functions/).
è stato rimosso dall'inglese, nel frattempo
```suggestion
```

2023-06-05 08:31 UTC, sistella commented on content/it/function-as-a-service.md
> +e potenzialmente assumere uno staff IT o appaltare l'acquisto, la gestione e l'aggiornamento di tutte le apparecchiature e le licenze.
```suggestion
e potenzialmente assumere uno staff IT o dei consulenti per l'acquisto, la gestione e l'aggiornamento di tutte le apparecchiature e le licenze.
```
con riferimento al fatto che di queste attivita se ne devono occupare o lo staff IT o i consulenti.

2023-06-05 08:31 UTC, sistella commented on content/it/function-as-a-service.md
> +e lo sviluppatore non dovrà dedicare tempo o risorse alla creazione del codice per garantirne la [scalabilità](/it/scalabilità/).
qui è più bella la traduzione dell'originale, seriamente!! Brava @annalisag-spark !!!

2023-09-06 22:16 UTC, fsbaraglia requested changes

2023-09-06 22:16 UTC, fsbaraglia commented on content/it/function-as-a-service.md
> +e lo sviluppatore non dovrà dedicare tempo o risorse alla creazione del codice per garantirne la [scalabilità](/it/scalabilità/).
```suggestion
e lo sviluppatore non dovrà dedicare tempo o risorse alla creazione del codice per garantirne la [scalabilità](/it/scalability/).
```

2023-09-06 22:16 UTC, fsbaraglia approved these changes

2023-10-03 07:45 UTC, sistella approved these changes

2023-10-03 07:48 UTC, merged