1394-spanish-localize-microservicesarchitecture
cncf/glossary pull request #1636
Opened 2023-01-22 01:27 UTC by mdf-ido

Signed-off-by: Mo Figueroa <moisesdfigueroa@gmail.com>

### Describe your changes
Translates microservices architecture in Spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1394

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-23 17:34 UTC, electrocucaracha requested changes

2023-01-23 17:34 UTC, electrocucaracha commented on content/es/microservices-architecture.md
> +tags: ["arquitectura", "fundamental", ""]
```suggestion
title: Arquitectura de Microservicios
status: Feedback Appreciated 
tags: ["architecture", "fundamental", ""]
```

2023-01-23 17:34 UTC, electrocucaracha commented on content/es/microservices-architecture.md
> +Este enfoque arquitectónico permite a los desarrolladores introducir nuevas características o actualizar la funcionalidad mucho más rápido que si estuvieran todo junto, como en una [aplicación monolí
En medida de lo posible, es necesario mantener el `semantic line breaks` que se tiene de la versión original, en otras palabras conservar los saltos de línea.
```suggestion
Una arquitectura de microservicios es un enfoque arquitectónico que divide las aplicaciones en (micro)[servicios](/service/) individuales e independientes, donde cada servicio se centra en una funcionalidad específica.
Estos servicios trabajan juntos estrechamente, apareciendo ante el usuario final como una sola entidad.
Tomemos Netflix como ejemplo.
Su interfaz permite acceder, buscar y preestrenar vídeos.
Es probable que estas funciones estén gestionadas por servicios pequeños, cada uno de los cuales se encarga de una funcionalidad, por ejemplo, la autenticación, la búsqueda y la ejecución de preestrenar vídeos en el navegador.

Este enfoque arquitectónico permite a los desarrolladores introducir nuevas características o actualizar la funcionalidad mucho más rápido que si estuvieran todo junto, como en una [aplicación monolítica](/monolithic-apps/) (más sobre esto más adelante).
```

2023-01-31 16:47 UTC, electrocucaracha approved these changes

2023-02-07 16:16 UTC, 92nqb approved these changes
LGTM!

2023-02-07 16:50 UTC, merged