[Spanish] Localize Monolitic Applications
cncf/glossary pull request #1637
Opened 2023-01-22 20:33 UTC by mdf-ido

Signed-off-by: Mo Figueroa <moisesdfigueroa@gmail.com>

### Describe your changes
Translates Monolithic Apps in Spanish

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-23 12:32 UTC, krol3 reviewed
LGTM small changes!

2023-01-23 12:32 UTC, krol3 commented on content/es/monolithic-apps.md
> +la probabilidad de conflictos y la necesidad de comunicación interpersonal entre desarrolladores se aumenta.
```suggestion
la probabilidad de conflictos y la necesidad de comunicación interpersonal entre desarrolladores aumenta. 
```

2023-01-24 08:56 UTC, raelga approved these changes

2023-01-24 17:12 UTC, krol3 commented on content/es/monolithic-apps.md
> +tags: ["arquitectura", "fundamental"]
Por convención, los tags los dejamos en ingles

2023-01-24 17:14 UTC, krol3 reviewed
Tenemos unas convenciones en el glossario espanol, vamos a crear unas notas para dejar claro esa parte.

2023-01-24 17:53 UTC, electrocucaracha requested changes
Algunos cambios en cuanto a etiquetas y saltos de lineas

2023-01-24 17:53 UTC, electrocucaracha commented on content/es/monolithic-apps.md
> +tags: ["arquitectura", "fundamental"]
```suggestion
title: Aplicaciones monolíticas
status: Completed
category: Concepto
tags: ["architecture", "fundamental", ""]
```

2023-01-24 17:53 UTC, electrocucaracha commented on content/es/monolithic-apps.md
> +Una aplicación monolítica contiene toda la funcionalidad en un único programa desplegable. Suele ser el punto de partida más sencillo y fácil a la hora de crear una aplicación. Sin embargo, una vez q
```suggestion
Una aplicación monolítica contiene toda la funcionalidad en un único programa desplegable.
Suele ser el punto de partida más sencillo y fácil a la hora de crear una aplicación.
Sin embargo, una vez que la aplicación crece en complejidad, los monolitos pueden ser difíciles de mantener.
Mientras más desarrolladores trabajen en la misma base de código, 
```

2023-01-24 17:53 UTC, electrocucaracha commented on content/es/monolithic-apps.md
> +La división de una aplicación en [microservicios](/microservices/) aumenta su sobrecarga operativa ya que hay más cosas que probar, desplegar y mantener en funcionamiento. Al principio del ciclo de v
```suggestion
La división de una aplicación en [microservicios](/microservices/) aumenta su sobrecarga operativa
ya que hay más cosas que probar, desplegar y mantener en funcionamiento.
Al principio del ciclo de vida de un producto, puede ser ventajoso reducir la complejidad y construir una aplicación monolítica
hasta que se determine que el producto tiene éxito.
```

2023-01-24 17:53 UTC, electrocucaracha commented on content/es/monolithic-apps.md
> +Un monolito bien diseñado puede defender los principios "lean" al ser la forma más sencilla de poner en marcha una aplicación. Cuando la aplicación monolítica demuestra su valor de negocio y éxito, s
```suggestion
Un monolito bien diseñado puede defender los principios "lean" al ser la forma más sencilla de poner en marcha una aplicación.
Cuando la aplicación monolítica demuestra su valor de negocio y éxito, se puede descomponer en microservicios.
Crear una aplicación basada en microservicios antes de que haya demostrado su valor puede suponer un gasto prematuro de esfuerzos de ingeniería.
Si la aplicación no aporta valor, ese esfuerzo se desperdicia.
```

2023-01-27 00:53 UTC, mdf-ido commented
@krol3 y @electrocucaracha  Gracias por los buenos consejos!

2023-01-27 16:49 UTC, electrocucaracha approved these changes

2023-01-27 16:50 UTC, merged