create observability.md
cncf/glossary pull request #1639
Opened 2023-01-23 19:11 UTC by swastiksingh22

Signed-off-by: swastiksingh22 s.singh.swastik.98@gmail.com

### Describe your changes
I have added hindi version of observability.md. Thankyou I'll wait for your response.

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-28 15:08 UTC, anubha-v-ardhan requested changes
Hey @swastiksingh22 , The content of observability has changed on the English version. It would be nice if we can update this PR with latest content

2023-06-28 15:08 UTC, anubha-v-ardhan commented on content/hi/observability.md
> +---
```suggestion
---
title: ऑब्जर्वेबिलिटी (Observability)
status: Completed
category: संकल्पना
tags: ["property", "", ""]
---
```

2023-10-06 07:35 UTC, aj11anuj commented
@swastiksingh22 gentle ping to implement necessary changes

2023-11-12 06:21 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-14 15:39 UTC, kumarankit999 approved these changes
looks good to me!

2023-11-15 03:40 UTC, aj11anuj commented
@swastiksingh22 you need to change target branch from 'cncf: main' to 'cncf: dev-hi'.

2023-11-18 03:08 UTC, abhay-raj19 commented
Looks good to me 👍
Thanks @swastiksingh22 for contributing

2023-11-18 03:09 UTC, abhay-raj19 approved these changes

2023-11-26 09:05 UTC, merged