Adding self-healing.md in Hindi
cncf/glossary pull request #1642
Opened 2023-01-24 14:49 UTC by ShivangShandilya

Signed-off-by: Shivang Shandilya <101946115+ShivangShandilya@users.noreply.github.com>

### Describe your changes

This PR adds self-healing.md in Hindi Language

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #1593

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-11 02:28 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +status: पूरित
```suggestion
status: completed

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +category: गुण
```suggestion
category: property

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +title: सेलफ हीलिंग (Self Healing)
```suggestion
title: स्व-उपचार (Self Healing)

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +एक स्व-उपचार प्रणाली बिना किसी मानवीय हस्तक्षेप के कुछ प्रकार की विफलताओं से उबरने में सक्षम है।
```suggestion
एक स्व-उपचार प्रणाली बिना किसी मानवीय हस्तक्षेप के कुछ प्रकार की विफलताओं से उबरने में सक्षम होती है। 

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +इसमें एक "अभिसरण" या "नियंत्रण" लूप है जो सिस्टम की वास्तविक स्थिति को सक्रिय रूप से देखता है और इसकी तुलना उस स्थिति से करता है जिसे ऑपरेटर शुरू में चाहते थे।
```suggestion
इसमें एक "अभिसरण" या "नियंत्रण" लूप होता है, जो सिस्टम की वास्तविक स्थिति को सक्रिय रूप से देखता है और इसकी तुलना उस स्थिति से करता है जिसे ऑपरेटर शुरू में चाहते थे।

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +यदि कोई अंतर है (उदाहरण के लिए, वांछित से कम एप्लिकेशन इंस्टेंस चल रहे हैं),
```suggestion
यदि कोई अंतर होता है (उदाहरण के लिए, वांछित से कम एप्लिकेशन के इंस्टेंस चल रहे हैं), तो 

```

2023-10-11 02:28 UTC, aj11anuj commented on content/hi/self-healing.md
> +यह सुधारात्मक कार्रवाई करेगा (उदाहरण के लिए, नए उदाहरण प्रारंभ करें)।
```suggestion
यह सुधारात्मक कार्रवाई करेगा (उदाहरण के लिए, नए एप्लीकेशन इंस्टैंस प्रारंभ करन)।
```

2023-11-12 06:06 UTC, aj11anuj requested changes

2023-11-12 06:06 UTC, aj11anuj commented on content/hi/self-healing.md
> +यह सुधारात्मक कार्रवाई करेगा (उदाहरण के लिए, नए एप्लीकेशन इंस्टैंस प्रारंभ करन)।
```suggestion
---
title: स्व-उपचार (Self Healing)
status: completed
category: property
tags: ["infrastructure", "property"]
---

एक स्व-उपचार प्रणाली बिना किसी मानवीय हस्तक्षेप के कुछ प्रकार की विफलताओं से उबरने में सक्षम होती है। 
इसमें एक "अभिसरण" या "नियंत्रण" लूप होता है, जो सिस्टम की वास्तविक स्थिति को सक्रिय रूप से देखता है और इसकी तुलना उस स्थिति से करता है जिसे ऑपरेटर शुरू में चाहते थे।
यदि कोई अंतर होता है (उदाहरण के लिए, वांछित से कम एप्लिकेशन के इंस्टेंस चल रहे हैं), तो 
यह सुधारात्मक कार्रवाई करेगा (उदाहरण के लिए, नए एप्लीकेशन इंस्टैंस प्रारंभ करन)।
```

2023-11-12 06:07 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-14 15:40 UTC, kumarankit999 approved these changes
lgtm

2023-11-15 03:42 UTC, aj11anuj commented
@ShivangShandilya you need to change target branch from 'cncf: main' to 'cncf: dev-hi'.

2023-11-17 13:57 UTC, bishal7679 approved these changes
LGTM!
Thank you @ShivangShandilya

2023-11-17 13:58 UTC, merged