Traduction de container-orchestration en FR
cncf/glossary pull request #1666
Opened 2023-01-25 21:02 UTC by huats

### Describe your changes
This PR localizes container-orchestration concept to French

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1664 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-01-31 17:51 UTC, fydrah requested changes

2023-01-31 17:51 UTC, fydrah commented on content/fr/container-orchestration.md
> +Gérer des [microservices](/microservices), la sécurité, et la communication réseaux à grande échelle — et des [systèmes distribués](/distributed-systems) en général — est compliqué, pour ne pas dire
I would move "manuellement" just after "Gérer" --> "Gérer manuellement des microservices [...]", what do you think?

2023-02-01 18:43 UTC, fydrah approved these changes

2023-02-05 15:38 UTC, Krast76 requested changes

2023-02-05 15:38 UTC, Krast76 commented on content/fr/container-orchestration.md
> +Tout d'abord, on déclare tel qu'il devrait être (i.e. x conteneurs, y pods, etc...).
"on déclare comment il devrait être"

2023-02-05 15:55 UTC, huats commented on content/fr/container-orchestration.md
> +Tout d'abord, on déclare tel qu'il devrait être (i.e. x conteneurs, y pods, etc...).
Hum. Utiliser "comment" me semble plus du "parlé" au lieu de "tel" qui me semble plus écrit... Je suis pour garder "tel"

2023-02-05 18:48 UTC, fydrah commented on content/fr/container-orchestration.md
> +Tout d'abord, on déclare tel qu'il devrait être (i.e. x conteneurs, y pods, etc...).
Je suis de l'avis de Christophe sur ce coup là :)

2023-02-05 19:17 UTC, Krast76 approved these changes

2023-02-06 13:44 UTC, merged