[hi] Localize virtualization.md to Hindi
cncf/glossary pull request #1674
Opened 2023-01-27 19:20 UTC by SaxenaAnushka102

Signed-off-by: ANUSHKA SAXENA <anushkasaxena102@gmail.com>

### Describe your changes
Created a file `virualization.md` to localize the page: https://glossary.cncf.io/virtualization/ into Hindi 

### Related issue number 
Resolves #1597

### Checklist before opening this PR 
- [x] This PR does not contain plagiarism
- [x] I have signed off on all commits

2023-10-06 08:26 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-06 08:26 UTC, aj11anuj commented on content/hi/virtualization.md
> +title: आभासीकरण (Virtualization)
```suggestion
title: वर्चुअलाइजेशन (Virtualization)
```

2023-10-06 08:26 UTC, aj11anuj commented on content/hi/virtualization.md
> +वर्चुअलाइजेशन कई समस्याओं का समाधान करता है, जिसमें सुरक्षा के लिए एक दूसरे से अलग होते हुए भी एक ही भौतिक मशीन पर और अधिक एप्लीकेशन को चलने की अनुमति देकर भौतिक हार्डवेयर उपयोग में सुधार भी शामिल है
```suggestion
वर्चुअलाइजेशन कई समस्याओं का समाधान करता है, जिसमें सुरक्षा के लिए एक दूसरे से अलग होते हुए भी एक ही भौतिक मशीन पर और अधिक एप्लीकेशन को चलने की अनुमति देकर हार्डवेयर के उपयोग में सुधार भी कर सकते हैं।
```

2023-10-06 08:26 UTC, aj11anuj commented on content/hi/virtualization.md
> +आभासी मशीन पर चलने वाले विभिन्न एप्लीकेशन को इस बात की कोई जानकारी नहीं होती है कि वे एक भौतिक कंप्यूटर साझा कर रहे हैं। आभासीकरण डेटासेंटर के उपयोगकर्ताओं को डेटासेंटर में एक नया कंप्यूटर जोड़ने की
```suggestion
वर्चुअल मशीन पर चलने वाले विभिन्न एप्लीकेशन को इस बात की कोई जानकारी नहीं होती है कि वे एक भौतिक कंप्यूटर को साझा कर रहीं हैं। वर्चुअलाइजेशन डेटासेंटर के उपयोगकर्ताओं को डेटासेंटर में एक नया कंप्यूटर को जोड़ने की भौतिक बाधाओं के बारे में चिंता किए बिना, मिनटों में एक नए "कंप्यूटर" (वि एम) को तुरंत शुरू करने की अनुमति देता है। वर्चुअल मशीन उपयोगकर्ताओं को एक नया वर्चुअल कंप्यूटर प्राप्त करने के लिए लगने वाली समयावधि को घटाने में भी सक्षम बनाता है।
```

2023-11-12 05:23 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-14 15:40 UTC, kumarankit999 approved these changes
lgtm

2023-11-14 17:49 UTC, bishal7679 commented
It seems this PR is ready to merge!
Just let me go through a final review once!

2023-11-14 18:08 UTC, merged