[fr] Traduction pour `Abstraction`
cncf/glossary pull request #1691
Opened 2023-02-04 14:54 UTC by sestegra

Signed-off-by: Stéphane Este-Gracias <sestegra@gmail.com>

### Describe your changes
This PR localizes abstraction to French

### Related issue number or link (ex: `resolves #issue-number`)
Fix #1168

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-05 15:44 UTC, Krast76 requested changes

2023-02-05 15:44 UTC, Krast76 commented on content/fr/abstraction.md
> +Tous ces détails sont cachés sous le « capot » ou l'abstraction du système d'exploitation.
On pourrait pas traduire cette phrase par : "Tous ces détails sont cachés sous le "capot" abstrait par le système d'exploitation." ?

2023-02-05 16:39 UTC, fydrah requested changes

2023-02-05 16:39 UTC, fydrah commented on content/fr/abstraction.md
> +Vous n'avez pas besoin d'avoir une compréhension approfondie du processeur, de la mémoire et du fonctionnement des programmes, vous utilisez simplement le système d'exploitation et le système d'explo
"le système d'exploitation et le système d'exploitation [...]" --> "le système d'exploitation et ce dernier [...]" ou "... et celui-ci [...]" to avoid repetition.

2023-02-05 16:39 UTC, fydrah commented on content/fr/abstraction.md
> +Si cela fonctionne avec la couche d'abstraction, cela fonctionne avec le système — peu importe ce qui se trouve sous le capot.
to avoid repetition with L13, could we change it for "peu importe ce qui se trouve en dessous."?

2023-02-05 17:26 UTC, sestegra commented on content/fr/abstraction.md
> +Vous n'avez pas besoin d'avoir une compréhension approfondie du processeur, de la mémoire et du fonctionnement des programmes, vous utilisez simplement le système d'exploitation et le système d'explo
Modification effectuée

2023-02-05 17:26 UTC, sestegra commented on content/fr/abstraction.md
> +Tous ces détails sont cachés sous le « capot » ou l'abstraction du système d'exploitation.
Modification effectuée

2023-02-05 17:37 UTC, sestegra commented on content/fr/abstraction.md
> +Si cela fonctionne avec la couche d'abstraction, cela fonctionne avec le système — peu importe ce qui se trouve sous le capot.
Pour remplacer `capot`, j'hésite entre `dessous` ou `derrière`.

2023-02-14 18:34 UTC, sestegra commented on content/fr/abstraction.md
> +Si cela fonctionne avec la couche d'abstraction, cela fonctionne avec le système — peu importe ce qui se trouve sous le capot.
Mise à jour effectuée

2023-02-14 19:58 UTC, fydrah approved these changes
Updates done, this looks good to me.

2023-02-14 22:06 UTC, huats approved these changes
LGTM !

2023-02-15 13:32 UTC, sestegra commented on content/fr/abstraction.md
> +
Ligne suppriméee

2023-02-15 17:11 UTC, huats approved these changes
LGTM

2023-02-22 17:15 UTC, Krast76 approved these changes

2023-02-22 17:16 UTC, merged