[es] Localization scalability.md
cncf/glossary pull request #1701
Opened 2023-02-07 15:57 UTC by ramrodo

### Describe your changes

Localization of `scalability.md`

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-08 02:32 UTC, electrocucaracha requested changes

2023-02-08 02:32 UTC, electrocucaracha commented on content/es/scalability.md
> +La escalabilidad se refiere a qué tan bien puede crecer un sistema.
Hasta donde [se](https://www.ejemplos.co/que-o-que/) lleva acento cuando se utiliza en preguntas.
```suggestion
La escalabilidad se refiere a que tan bien puede crecer un sistema.
```

2023-02-08 02:32 UTC, electrocucaracha commented on content/es/scalability.md
> +Eso está aumentando la capacidad de hacer lo que se supone que debe hacer el sistema.
Me parece que esto debería llevar una coma,
```suggestion
Esto es, aumentando la capacidad para hacer lo que sea que el sistema deba hacer.
```

2023-02-08 02:32 UTC, electrocucaracha commented on content/es/scalability.md
> +aumentando o reduciendo el número de aplicaciones [en contenedores](/es/containerización/),
```suggestion
aumentando o reduciendo el número de aplicaciones [en contenedores](/es/containerization/),
```

2023-02-08 02:32 UTC, electrocucaracha commented on content/es/scalability.md
> +¿Cuántos [nodos](/es/nodes/) tiene, cuántos [contenedores](/container/) puede manejar cada nodo,
```suggestion
¿Cuántos [nodos](/es/nodes/) tiene?, ¿cuántos [contenedores](/container/) puede manejar cada nodo?,
```

2023-02-08 16:25 UTC, electrocucaracha approved these changes

2023-02-13 17:43 UTC, ramrodo commented
@krol3 @92nqb could you review this PR, please? Thanks :)

2023-02-14 17:05 UTC, krol3 approved these changes
LGTM

2023-02-14 17:06 UTC, merged