Add Rodolfo Martinez to Spanish approver team
cncf/glossary pull request #1704
Opened 2023-02-07 21:49 UTC by electrocucaracha

### Describe your changes

Given his active [collaboration](https://github.com/cncf/glossary/pulls?q=author%3Aramrodo) in Spanish localization team, this PR recognizes the effort made by @ramrodo and promotes him to the approver role.

/cc @ramrodo @krol3

### Related issue number or link (ex: `resolves #issue-number`)
NA

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-08 01:02 UTC, ramrodo commented
Thanks! Happy to continue contributing :)

2023-02-14 13:44 UTC, krol3 approved these changes
LGTM

2023-02-21 13:58 UTC, raelga commented
/lgtm

2023-02-21 13:58 UTC, raelga approved these changes

2023-02-23 12:57 UTC, seokho-son commented
Maintainers are discussing extending the max number of approvers(reviewers) for each localization team from 4 to 5.
So that, folks who have leadership in the localization team can keep stay with the leadership.
Anyway, please wait for a while for the outcome.

2023-03-02 15:15 UTC, seokho-son commented
Hi @electrocucaracha 
In the latest Glossary meeting, we agreed to accept additional approvers for an ongoing localization team. I think we can remain the existing approvers for Spanish team and add @ramrodo .

2023-03-02 15:32 UTC, raelga requested changes
Adds @ramrodo along current approvers

2023-03-02 15:32 UTC, raelga commented on .github/settings.yml
> +  - username: ramrodo
```suggestion
  - username: raelga
    permission: push

  - username: ramrodo
```

2023-03-02 15:32 UTC, raelga commented on .github/settings.yml
> +         - ramrodo
```suggestion
         - raelga
         - ramrodo
```

2023-03-02 15:32 UTC, raelga commented on CODEOWNERS
> +/content/es/ @ramrodo @electrocucaracha @krol3 @92nqb
```suggestion
/content/es/ @raelga @ramrodo @electrocucaracha @krol3 @92nqb
```

2023-03-02 16:37 UTC, raelga approved these changes

2023-03-07 04:23 UTC, seokho-son approved these changes
LGTM!

Hi @ramrodo please check and confirm following policies :)
[Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

2023-03-07 04:23 UTC, merged

2023-03-08 15:22 UTC, ramrodo commented
> Hi @ramrodo welcome to the Spanish approver team! please check and confirm following policies :) [Policies for localization approvers (to be confirmed by candidates) #723](https://github.com/cncf/glossary/discussions/723)

Thanks, @seokho-son. I'll do.