ES: Localize term 'distributed apps' apps in Spanish.
cncf/glossary pull request #1720
Opened 2023-02-13 22:32 UTC by 92nqb

### Describe your changes

Localization of distributed-apps.md

### Related issue number or link (ex: `resolves #issue-number`)

It closes #600 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-14 02:13 UTC, electrocucaracha requested changes

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +Las aplicaciones distribuidas suelen estar formadas por componentes individuales llamados [microservicios](/microservices/)
```suggestion
Las aplicaciones distribuidas suelen estar formadas por componentes individuales llamados [microservicios](/es/microservices/)
```

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +En un entorno de nube nativa, los componentes individuales suelen ejecutarse como [contenedores](/container/) en un [clúster](/cluster/).
```suggestion
En un entorno nativo para la nube, los componentes individuales suelen ejecutarse como [contenedores](/container/) en un [clúster](/es/cluster/).
```

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +Una aplicación que se ejecuta en un único ordenador representa un único punto de fallo: si ese ordenador falla, la aplicación deja de estar disponible.
https://es.wikipedia.org/wiki/Punto_%C3%BAnico_de_fallo
```suggestion
Una aplicación que se ejecuta en un único ordenador representa un punto único de fallo: si ese ordenador falla, la aplicación deja de estar disponible. 
```

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +Las aplicaciones distribuidas a menudo se contraponen a las [aplicaciones monolíticas](/monolithic-apps/).
```suggestion
Las aplicaciones distribuidas a menudo se contraponen a las [aplicaciones monolíticas](/es/monolithic-apps/). 
```

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +También pueden convertirse en un lastre para la velocidad de los desarrolladores a medida que crecen
```suggestion
También pueden convertirse en un lastre en la velocidad de desarrollo a medida que crecen 
```

2023-02-14 02:13 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +- ahora estás ejecutando muchos componentes de aplicación en lugar de una única aplicación.
```suggestion
- ahora estás ejecutando muchos componentes en lugar de una aplicación única.
```

2023-02-21 07:04 UTC, 92nqb commented
@electrocucaracha, thanks for your feedback. 
I've accepted your suggestions :)

2023-02-21 13:46 UTC, krol3 approved these changes
LGTM

2023-02-21 17:19 UTC, electrocucaracha commented on content/es/distributed-apps.md
> +- ahora estás ejecutando muchos componentes en lugar de una aplicación única.
Parece ser que en inglés usan un carácter diferente, por lo que el rendering se comporta distinto
```suggestion
— ahora estás ejecutando muchos componentes en lugar de una aplicación única.
```

2023-02-28 16:56 UTC, electrocucaracha approved these changes

2023-02-28 16:58 UTC, merged