Create cloud native apps.md
cncf/glossary pull request #1721
Opened 2023-02-14 09:09 UTC by Martande8055

Signed-off-by: Saurabh Subhash Martande <smartande8055@gmail.com>

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-15 05:27 UTC, Martande8055 commented
Is there any update on this PR?

2023-04-13 01:19 UTC, shivam-sharma7 requested changes

2023-04-13 01:19 UTC, shivam-sharma7 commented on content/hi/cloud native apps.md
> +जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई "एक आकार सभी फिट बैठता है" पथ नहीं है, उनमें कुछ समानताएँ हैं।
```suggestion
जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई एक आकार सभी फिट बैठता है। पाथ नहीं है, उनमें कुछ समानताएँ हैं।
```

2023-04-13 01:19 UTC, shivam-sharma7 commented on content/hi/cloud native apps.md
> +जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई "एक आकार सभी फिट बैठता है" पथ नहीं है, उनमें कुछ समानताएँ हैं।
Need to add suggested changes

2023-04-13 17:14 UTC, Martande8055 commented on content/hi/cloud native apps.md
> +जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई "एक आकार सभी फिट बैठता है" पथ नहीं है, उनमें कुछ समानताएँ हैं।
changes Done

2023-10-08 13:18 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +[वर्चुअल मशीन](/virtual-machine/) और सेवाओं जैसी बुनियादी सुविधाओं के लिए अक्सर मैन्युअल प्रावधान पर बहुत अधिक भरोसा करते हैं।
```suggestion
[वर्चुअल मशीन](/virtual-machine/) और अन्य सेवाऍ जैसी बुनियादी सुविधाओं के लिए अक्सर मैन्युअल प्रावधान पर बहुत अधिक भरोसा किया जाता है।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +यह, बदले में, उस विशिष्ट डेटासेंटर के लिए डेवलपर्स और उनके अनुप्रयोगों को विवश करता है।
```suggestion
यह बदले में उस विशिष्ट डेटासेंटर के लिए डेवलपर्स और उनके अनुप्रयोगों को विवश करता है।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +नही विफलता की स्थिति में उन्हें स्वचालित रूप से पुनरारंभ किया जा सकता है।
```suggestion
ना ही विफलता की स्थिति में उन्हें स्वचालित रूप से पुनरारंभ किया जा सकता है।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +क्लाउड के लिए डिज़ाइन नहीं किए गए एप्लिकेशन क्लाउड वातावरण की लचीलापन और स्केलिंग क्षमताओं का लाभ नहीं उठा सकते।
```suggestion
क्लाउड के लिए डिज़ाइन नहीं किए गए एप्लिकेशन क्लाउड वातावरण की लचीलापन (resilience) और स्केलिंग क्षमताओं का लाभ नहीं उठा सकते।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई एक आकार सभी फिट बैठता है। पाथ नहीं है, उनमें कुछ समानताएँ हैं।
```suggestion
जबकि क्लाउड नेटिव एप्लिकेशन के लिए कोई एक आकार तभी फिट बैठता है, जब उनमें कुछ समानताएँ हों।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +क्लाउड नेटिव ऐप्स लचीला, प्रबंधनीय और उनके साथ आने वाली क्लाउड सेवाओं के सूट द्वारा सहायता प्राप्त हैं।
```suggestion
क्लाउड नेटिव ऐप्स लचीले व प्रबंधनीय होते हैं और उनके साथ आने वाली क्लाउड सेवाओं द्वारा उन्हें सहायता प्राप्त होती है।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +इससे पहले कि वे आगे बढ़ें, उपयोगकर्ताओं को समस्याओं का पता लगाने और उनका समाधान करने में सक्षम बनाता है।
```suggestion
इससे पहले कि वे आगे बढ़ें, उपयोगकर्ताओं को समस्याओं का पता लगाने और उनका समाधान करने में सक्षम बनाती है।
```

2023-10-08 13:18 UTC, aj11anuj commented on content/hi/cloud native apps.md
> +मजबूत स्वचालन के साथ संयुक्त, वे इंजीनियरों को न्यूनतम परिश्रम के साथ बार-बार और अनुमानित रूप से उच्च प्रभाव वाले परिवर्तन करने की अनुमति देते हैं।
```suggestion
मजबूत स्वचालन के साथ संयुक्त, वे इंजीनियरों को न्यूनतम परिश्रम के साथ बार-बार और अनुमानित रूप से उच्च प्रभाव वाले परिवर्तन करने की अनुमति देती हैं।
```

2023-11-12 10:21 UTC, aj11anuj approved these changes

2023-11-17 04:36 UTC, abhay-raj19 commented
Looks good to me @Martande8055 .
Thanks for contributing.

2023-11-24 15:19 UTC, bishal7679 requested changes
Left some suggestions!

2023-11-24 15:19 UTC, bishal7679 commented on content/hi/cloud native apps.md
> +इससे पहले कि वे आगे बढ़ें, उपयोगकर्ताओं को समस्याओं का पता लगाने और उनका समाधान करने में सक्षम बनाती है।
```suggestion
विभिन्न क्लाउड सेवाएँ उपयोगकर्ताओं को समस्याओं के बढ़ने से पहले उनका पता लगाना और उनका समाधान करने में सक्षम बनाने के साथ साथ [अवलोकन योग्यता](/observability/) की एक उच्च स्तर को सक्षम करती हैं।
```

2023-11-27 17:37 UTC, bishal7679 approved these changes

2023-11-27 17:38 UTC, merged