[hi] Localize idempotence.md to Hindi
cncf/glossary pull request #1729
Opened 2023-02-15 02:40 UTC by neelshah2409

Signed-off-by: Neel Shah (19csnee138@ldce.ac.in)
### Describe your changes
-   Localize idempotence.md to Hindi

### Related issue number or link (ex: `resolves #issue-number`)
- resolves #1693 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-08 12:40 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-08 12:40 UTC, aj11anuj commented on content/hi/idempotence.md
> +title: इडैम्पोटेन्ट (Idempotence)
```suggestion
title: इडेमपोटेन्स (Idempotence)
```

2023-10-08 12:40 UTC, aj11anuj commented on content/hi/idempotence.md
> +गणित या कंप्यूटर विज्ञान में, इडेमपोटेंसी एक ऑपरेशन का वर्णन करता है जो हमेशा एक ही परिणाम की ओर जाता है, इससे कोई फर्क नहीं पड़ता कि आप इसे कितनी बार निष्पादित करते हैं। यदि पैरामीटर समान हैं, तो एक
```suggestion
गणित या कंप्यूटर विज्ञान में, इडेमपोटेंसी एक ऑपरेशन का वर्णन करता है जो हमेशा एक ही परिणाम की ओर जाता है, 
इससे कोई फर्क नहीं पड़ता कि आप इसे कितनी बार निष्पादित करते हैं। 
यदि पैरामीटर समान हैं, तो एक इडेमपोटेन्ट ऑपरेशन उस एप्लिकेशन को प्रभावित नहीं करेगा जिसे वह कॉल करता है।
```

2023-10-08 12:40 UTC, aj11anuj commented on content/hi/idempotence.md
> +category: गुण
```suggestion
category: प्रॉपर्टी
tags: ["प्रॉपर्टी"]
```

2023-11-12 07:42 UTC, aj11anuj approved these changes

2023-11-14 07:58 UTC, bishal7679 requested changes
Commit these if you find useful!

2023-11-14 07:58 UTC, bishal7679 commented on content/hi/idempotence.md
> +इससे कोई फर्क नहीं पड़ता कि आप इसे कितनी बार निष्पादित करते हैं।
```suggestion
गणित या कंप्यूटर विज्ञान में, इडेमपोटेन्स एक ऐसे ऑपरेशन का वर्णन करता है जिसका परिणाम हमेशा एक ही होता है, चाहे आप इसे कितनी भी बार निष्पादित करें।
```

2023-11-14 07:58 UTC, bishal7679 commented on content/hi/idempotence.md
> +यदि पैरामीटर समान हैं, तो एक इडेमपोटेन्ट ऑपरेशन उस एप्लिकेशन को प्रभावित नहीं करेगा जिसे वह कॉल करता है।
```suggestion
यदि पैरामीटर समान हैं, तो एक इडेमपोटेन्ट ऑपरेशन को कई बार निष्पादित करने से कोई अतिरिक्त प्रभाव नहीं पड़ेगा।
```

2023-11-14 08:02 UTC, bishal7679 commented
@neelshah2409 Please make one empty commit by sign-off and Please change the target branch of this PR to dev-hi, not main.

2023-11-16 18:09 UTC, bishal7679 approved these changes
Ready to merge!

2023-11-16 18:09 UTC, merged

2023-11-17 04:25 UTC, kumarankit999 reviewed
lgtm, Thanks @neelshah2409