ES: localize 'Containers'
cncf/glossary pull request #1740
Opened 2023-02-21 05:20 UTC by josefloressv

### Describe your changes
Localize the `content/en/container.md` document to Spanish

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #578

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-21 06:54 UTC, 92nqb commented
Hi @josefloressv, thanks a lot for your contribution!

You must change the target branch from [main:cncf](https://github.com/cncf/glossary/tree/main/) to [cncf:dev-es](https://github.com/cncf/glossary/tree/dev-es)

Let me know if you need help :)

2023-02-21 14:03 UTC, krol3 requested changes
Algunas sugerencias @josefloressv

2023-02-21 14:03 UTC, krol3 commented on content/es/container.md
> +distribuyen la sobrecarga de recursos del sistema operativo y crear un uso eficiente de la máquina física.
```suggestion
distribuyen la sobrecarga de recursos del sistema operativo y crean un uso eficiente de la máquina física.
```

2023-02-21 14:03 UTC, krol3 commented on content/es/container.md
> +Dado que los contenedores comparten el mismo Sistema Operativo, los procesos pueden considerarse menos seguros que las alternativas.
```suggestion
Dado que los contenedores comparten el mismo sistema operativo, los procesos pueden considerarse menos seguros que las alternativas.
```

2023-02-21 14:03 UTC, krol3 commented on content/es/container.md
> +Para garantizar los recursos, los administradores deben restringir y limitar el uso de la memoria y la CPU para que otras aplicaciones no funcionen mal.
```suggestion
Para garantizar los recursos, los administradores deben restringir y limitar el uso de la memoria y la CPU para que otras aplicaciones no tengan un rendimiento deficiente.
```

2023-02-21 17:02 UTC, josefloressv commented
> Hi @josefloressv, thanks a lot for your contribution!
> 
> You have to change the target branch from [main:cncf](https://github.com/cncf/glossary/tree/main/) to [cncf:dev-es](https://github.com/cncf/glossary/tree/dev-es)
> 
> Let me know if you need help :)

@92nqb I changed this PR to use [cncf:dev-es](https://github.com/cncf/glossary/tree/dev-es) but that brought another problem because I forked from main, I have applied rebase commands but I only forked the main branch for this repo. Do you know another way to resolve this?

2023-02-21 17:05 UTC, electrocucaracha commented
> > Hi @josefloressv, thanks a lot for your contribution!
> > You have to change the target branch from [main:cncf](https://github.com/cncf/glossary/tree/main/) to [cncf:dev-es](https://github.com/cncf/glossary/tree/dev-es)
> > Let me know if you need help :)
> 
> @92nqb I changed this PR to use [cncf:dev-es](https://github.com/cncf/glossary/tree/dev-es) but that brought another problem because I forked from main, I have applied rebase commands but I only forked the main branch for this repo. Do you know another way to resolve this?

Utiliza el argumento de `cherry-pick` para mover un commit de un branch a otro

2023-03-07 05:25 UTC, josefloressv commented
Gracias Victor, tendré que cerrar este PR y enviaré otro a la rama correcta.

2023-03-07 05:25 UTC, closed without merging