[ES] localization of 'distributed system'
cncf/glossary pull request #1743
Opened 2023-02-22 00:43 UTC by valeriahhdez

Add [ES] localization of 'Distributed system'

### Describe your changes
This is a Spanish localization of the concept 'Distributed system' 

### Related issue number or link (ex: `resolves #issue-number`)
Issue #601 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-23 23:33 UTC, electrocucaracha requested changes
Además de estos cambios, sería necesario renombrar el archivo por `distributed-systems.md`

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +construido
```suggestion
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +distribuidos
```suggestion
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +En cambio, un sistema distribuido puede ser contruido de tal manera que si una máquina deja de funcionar, el sistema completo puede seguir funcionando para producir los mismos resultados.
```suggestion
En cambio, un sistema distribuido puede ser construido de tal manera
que si una máquina deja de funcionar, el sistema completo puede seguir funcionando para producir los mismos resultados. 
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +category: concepto
```suggestion
category: Concepto
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +Un sistema distribuido es una colección de elementos computacionales autónomos conectados entre sí a través de una red que se muestra a los usuarios como un sistema único coherente.
```suggestion
Un sistema distribuido es una colección de elementos computacionales autónomos
conectados entre sí a través de una red que se muestra a los usuarios como un sistema único coherente. 
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +Conocidos usualmente como [nodos](/es/nodes/), estos elementos pueden ser dispositivos de hardware (por ejemplo, computadoras o teléfonos móviles) o procesos de software.
```suggestion
Conocidos generalmente como [nodos](/es/nodes/), estos elementos pueden ser dispositivos de hardware (por ejemplo, computadoras o teléfonos móviles) o procesos de software. 
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +Tradicionalmente, los sistemas implementarían un [escalamiento](/scalability/) vertical.
```suggestion
Tradicionalmente, los sistemas implementarían un [escalamiento](/es/scalability/) vertical. 
```

2023-02-23 23:33 UTC, electrocucaracha commented on content/es/distributed-system.md
> +Este proceso se puede automatizar, lo que permite al sistema manejar un incremento repentino de la carga de trabajo o del consumo de recursos.
```suggestion
Este proceso se puede automatizar, lo que permite al sistema manejar un incremento repentino de la carga de trabajo o del consumo de recursos.

```

2023-02-24 03:02 UTC, electrocucaracha approved these changes

2023-03-01 18:52 UTC, ramrodo commented
/lgtm
@92nqb @valeriahhdez could you review/approve this PR, please?

2023-03-02 00:51 UTC, krol3 approved these changes
lgtm, Thanks @valeriahhdez !

2023-03-02 00:52 UTC, merged