[it] Localizzazione termine Service Proxy
cncf/glossary pull request #1746
Opened 2023-02-23 16:37 UTC by ugho16

### Describe your changes
Added Service Proxy Italian Localization

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1656 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-22 08:51 UTC, sistella requested changes
Oltre ai commenti puntuali, mi pare ci siano troppe cose tra parentesi. Ma questo è un giudizio soggettivo, io preferirei dei periodi spezzati, e meno parentesi :)

2023-03-22 08:51 UTC, sistella commented on content/it/service-proxy.md
> +Per tenere traccia delle comunicazioni tra servizi, cioè traffico di rete, e potenzialmente trasformarlo o reindirizzarlo, bisogna raccogliere dati.
```suggestion
Per tenere traccia delle comunicazioni tra servizi, anche detto traffico di rete, e potenzialmente trasformarlo o reindirizzarlo, bisogna raccogliere dati.
```
o se preferisci "cioè del". Mi pare suonino meglio..

2023-03-22 08:51 UTC, sistella commented on content/it/service-proxy.md
> +Fungendo da guardiani tra i servizi, i proxy forniscono informazioni riguardo a che tipo di comunicazione sta avvenendo.
```suggestion
Fungendo da porta d'accesso ai servizi, i proxy forniscono informazioni riguardo a che tipo di comunicazione sta avvenendo.
```
premetto che non ho effettivamente mai sentito la traduzione di gatekeeper in questo contesto, ma mi pare giusto evidenziare che i service proxy qui hanno la funzione di "interceptors" più che di sicurezza (quest'ultima più resa dalla parola "guardiano"). Che ne pensi?

2023-03-22 08:51 UTC, sistella commented on content/it/service-proxy.md
> +Fungendo da guardiani tra i servizi, i proxy forniscono informazioni riguardo a che tipo di comunicazione sta avvenendo.
beh, in effetti dopo si parla del fatto che possono rigettare una richiesta... non so, vedi tu, io preferisco "porta d'accesso" :D

2023-03-22 14:20 UTC, ugho16 commented
@sistella Sì in effetti ci sono molte parentesi. Avevo preferito rimanere più fedele possibile all'inglese ma così effettivamente è più scorrevole. Grazie!

2023-03-22 14:28 UTC, sistella approved these changes

2023-03-30 11:12 UTC, annalisag-spark requested changes

2023-03-30 11:12 UTC, annalisag-spark commented on content/it/service-proxy.md
> +Per tenere traccia delle comunicazioni tra servizi, anche detto traffico di rete, e potenzialmente trasformarlo o reindirizzarlo, bisogna raccogliere dati.
```suggestion
Per tenere traccia delle comunicazioni tra servizi, ovvero di ciò che viene definito traffico di rete, e potenzialmente trasformarlo o reindirizzarlo, è evidentemente necessario raccogliere dati.
```

2023-03-30 14:08 UTC, annalisag-spark approved these changes

2023-03-30 14:21 UTC, merged