[DE] Localize Chaos Engineering
cncf/glossary pull request #1749
Opened 2023-02-25 08:31 UTC by bcubk

### Describe your changes
Die PR adds a  new page which localizes `Chaos Engineering` into german.

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1405 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-02-28 08:23 UTC, DaveVentura requested changes
Cooles Thema. Auch eine gute Übersetzung. Liest sich gut.
Was mich noch interessieren würde, ist auf welchem System dieses Chaos Engineering praktiziert wird.
Auf Dev/Test Systemen? Oder ist es üblich das auch auf Prod zu machen?
Wäre diese Frage auch relevant für den Artikel?

Edit:
Ich sehe gerade, dass in Zeile 9 ja von Prod die Rede ist.

2023-02-28 08:23 UTC, DaveVentura commented on content/de/chaos-engineering.md
> +Chaos Engineering (kurz CE) ist eine experimentbasierte, ganzheitliche Disziplin, um unerwartete Schwachstellen in [verteilten Systeme](/distributed-systems/) in der Produktion zu erkennen, zu widers
```suggestion
Chaos Engineering (kurz CE) ist eine experimentbasierte, ganzheitliche Disziplin, um unerwartete Schwachstellen in [verteilten Systeme](/distributed-systems/) in der Produktion zu erkennen, solchen zu widerstehen und das Vertrauen in die Fähigkeiten des Systems zu erhöhen. 
```

2023-02-28 08:23 UTC, DaveVentura commented on content/de/chaos-engineering.md
> +Chaos-Engineering wird eingesetzt, um die Resilienz der Infrastruktur, Plattform und Anwendungen zu erhöhen.
```suggestion
Chaos-Engineering wird eingesetzt, um die Resilienz von Infrastruktur, Plattform und Anwendungen zu erhöhen.
```

2023-04-15 17:07 UTC, iamNoah1 requested changes
Danke @bcubk für den Beitrag. Ich habe mir Zeit genommen um das Review gewissenhaft zu machen. Guck mal, was du davon hälst.

2023-04-15 17:07 UTC, iamNoah1 commented on content/de/chaos-engineering.md
> +Das Ziel dieser Chaos-Experimente ist es, blinde Flecken zu entdecken (z. B. Überwachungs- oder Autoskalierungstechniken) und die Kommunikation zwischen den Teams bei kritischen Ereignissen zu verbes
Dieser und der nächste Satz sprechen nicht darüber, wie Chaos Engineering das Problem löst. Das mit den blinden Flecken haben wir glaube ich quasi auch schon gesagt. Das könnte noch in die entsprechende Stelle mit aufnehmen, aber ich finde Überwachungs- und Autoskalierungstechniken als Beispiele für blinde Flecken irgendwie nicht schlüssig. Bei dem Aspekt mit dem Team-Gefüge bin ich auch nicht ganz sicher. Ist es wirklich Chaos Engineering was da hilft, oder ist es eher so eine allgemeine On-Call, Incident-Management und blameless Post-Mortem Kultur?!

2023-04-15 17:07 UTC, iamNoah1 commented on content/de/chaos-engineering.md
> +Software-Ingenieure, die Chaos-Engineering betreiben, definieren Chaos-Experimente, um proaktiv zufällige Ausfälle zu verursachen.
Dieser und der nächste Satz sind die beiden Sätze, die wie ich finde, den Nagel auf den Kopf treffen. Vielleicht kann man weiter ausführen, was das für Ausfälle sind, die da provoziert werden?!

2023-06-18 10:44 UTC, bcubk commented on content/de/chaos-engineering.md
> +Chaos Engineering (kurz CE) ist eine experimentbasierte, ganzheitliche Disziplin, um unerwartete Schwachstellen in [verteilten Systeme](/distributed-systems/) in der Produktion zu erkennen, solchen z
Finde ich gut. Würde ich genauso übernehmen 👍

2023-06-18 11:13 UTC, bcubk commented
Oh nice, I fu**** up the PR. I'll close it and create a new one 😞

2023-06-18 11:13 UTC, bcubk commented
Oh nice, I fu**** up the PR. I'll close it and create a new one 😞

2023-06-18 11:13 UTC, closed without merging