Create devsecops.md
cncf/glossary pull request #1754
Opened 2023-02-28 01:06 UTC by valeriahhdez

Add Spanish localization of 'DevSecOps'

### Describe your changes
This is a Spanish localization of the concept 'DevSecOps'

### Related issue number or link (ex: `resolves #issue-number`)
#599 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-01 19:04 UTC, ramrodo commented on content/es/devsecops.md
> +DevSecOps se enfoca en romper los silos del equipo y promueve la creación de flujos de trabajo automatizados y seguros.
La traducción del término `silos` es la misma que `silos` en Español, por lo que considero que no hay ningún error aquí.

Sin embargo, tras investigar el significado de [`silos` en la RAE](https://dle.rae.es/silo), se dice que es un: _Lugar seco en donde se guarda el trigo u otros granos, semillas o forraje._. 

En mi opinión, creo que podemos continuar con ésta palabra y tal vez, poder mejorar esa oración desde el concepto original en Inglés para que se pueda entender mejor. Porque la verdad en lo personal, no entiendo la analogía.

2023-03-01 19:04 UTC, ramrodo approved these changes
/lgtm

2023-03-01 20:48 UTC, valeriahhdez commented on content/es/devsecops.md
> +DevSecOps se enfoca en romper los silos del equipo y promueve la creación de flujos de trabajo automatizados y seguros.
De acuerdo con [este artículo](https://miro.com/blog/overcome-silo-mentality/#:~:text=What%20are%20team%20silos%3F,t%20incentivize%20inclusivity%20among%20teams.), la idea de silos en inglés se refiere a cuando no hay o hay poco flujo de información entre equipos de trabajo dentro de una compañía. En linguee encontré que, por ejemplo, _silos mentality_ se traduce al español como _mentalidad de silos_  ¿es este un caso en donde no es necesario localizat y podemos usar el término en inglés? 

En caso de que opten por localizar el término, [Linguee ](https://www.linguee.com/english-spanish/translation/silo+mentality.html) y [tr-ex](https://tr-ex.me/translation/english-spanish/silo+mentality#gref) traducen _silos mentality_ como _mentalidad compartimentada_ o _aislacionista_ 

Basada en esta información, propongo la siguiente traducción:
_DevSecOps se enfoca en romper el aislamiento del equipo y promueve la creación de flujos._

2023-03-01 22:56 UTC, electrocucaracha commented on content/es/devsecops.md
> +DevSecOps se enfoca en romper los silos del equipo y promueve la creación de flujos de trabajo automatizados y seguros.
Me parece que un `silo` es un granero de metal, en el concepto técnico, refiere al aislamiento entre distintos grupos y las consecuencias que se originan por la hermeticidad entre ellos. Sugiero utilizar un término un poco más común como lo recomienda @valeriahhdez 

```suggestion
DevSecOps se enfoca en romper el aislamiento del equipo y promueve la creación de flujos de trabajo automatizados y seguros.
```

2023-03-03 04:16 UTC, electrocucaracha requested changes

2023-03-03 04:16 UTC, electrocucaracha commented on content/es/devsecops.md
> +
```suggestion
con una interrupción mínima o nula en el flujo de trabajo operativo y de desarrollo.
```

2023-03-03 04:16 UTC, electrocucaracha commented on content/es/devsecops.md
> +
```suggestion
```

2023-03-03 04:16 UTC, electrocucaracha commented on content/es/devsecops.md
> +pueden exacerbar problemas existentes.
Quizá sería mejor utilizar un sinónimo de [exacerbar](https://dle.rae.es/exacerbar)
```suggestion
pueden intensificar los problemas existentes.
```

2023-03-03 04:16 UTC, electrocucaracha commented on content/es/devsecops.md
> +flujos de trabajo de CI/CD automatizados y la aplicación de políticas que empoderan al desarrollador.
```suggestion
Cuando se elijan las aplicaciones de seguridad, las organizaciones deben aprovechar
los flujos de trabajo automatizados de CI/CD y la aplicación de políticas que empoderen al desarrollador.
```

2023-03-03 19:44 UTC, electrocucaracha approved these changes

2023-03-03 21:38 UTC, 92nqb approved these changes

2023-03-03 21:38 UTC, merged