[it] Localizzazione termine Bare Metal Machine
cncf/glossary pull request #1756
Opened 2023-03-01 16:39 UTC by ugho16

### Describe your changes
Added Bare Metal Machine Italian localization

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1598 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-21 15:20 UTC, sistella requested changes

2023-03-21 15:20 UTC, sistella commented on content/it/bare-metal-machine.md
> +Installare un sistema operativo ed eseguire le applicazioni direttamente su quell'hardware fisico senza [virtualizzazione](/it/virtualization/), si definisce eseguire su “bare metal.”
```suggestion
Installare un sistema operativo ed eseguire le applicazioni direttamente su quell'hardware fisico senza [virtualizzazione](/it/virtualization/), si definisce come in esecuzione su “bare metal”.
```

2023-03-21 15:20 UTC, sistella commented on content/it/bare-metal-machine.md
> +Tutte le risorse del computer fisico sono direttamente disponibili per il sistema operativo, e senza livelli di virtualizzazione non c'è ritardo artificiale nella traduzione delle istruzione del sist
```suggestion
Tutte le risorse del computer fisico sono direttamente disponibili per il sistema operativo, e, senza livelli di virtualizzazione, non si introduce ritardo nella traduzione delle istruzione del sistema operativo all'hardware.
```
una proposta di traduzione un po' più libera... se piace.

2023-03-21 15:20 UTC, sistella commented on content/it/bare-metal-machine.md
> +che possono essere gestiti [scalando orizzontalmente](/it/horizontal-scaling/) (aggiungendo più macchine).
```suggestion
che possono essere gestiti utilizzando la proprietà di [scalabilità orizzontale](/it/horizontal-scaling/) (aggiungendo più macchine al pool di risorse).
```
(ne ho fatto una battaglia personale:) il verbo "scalare" non ha significato proprio di "to scale" in italiano; finora abbiamo usato sempre delle locuzioni.

2023-03-21 15:20 UTC, sistella commented on content/it/bare-metal-machine.md
> +Alcuni carichi di lavoro possono richiedere di [scalare verticalmente](/it/vertical-scaling/) (aggiungendo più potenza a una macchina fisica esistente)
```suggestion
Alcuni carichi di lavoro possono richiedere di utilizzare la [scalabilità verticale](/it/vertical-scaling/) (aggiungendo più potenza a una macchina fisica esistente);
```
come sopra. Il ";" alla fine è per dare una piccola pausa con questo terzo caso, coperto dal bare metal

2023-03-30 09:45 UTC, annalisag-spark requested changes

2023-03-30 09:45 UTC, annalisag-spark commented on content/it/bare-metal-machine.md
> +Nel contesto di [applicazioni cloud native](/it/cloud-native-apps/),
Eviterei gli a capo delle successive frasi

2023-03-30 09:45 UTC, annalisag-spark commented on content/it/bare-metal-machine.md
> +Bare metal permette anche di regolare l'hardware fisico ed eventualmente anche i driver hardware drivers per aiutare a raggiungere l'obiettivo.
```suggestion
Il bare metal permette anche di regolare l'hardware fisico ed eventualmente anche i driver hardware per aiutare a raggiungere l'obiettivo.
```

2023-05-09 12:30 UTC, sistella approved these changes

2023-05-09 14:11 UTC, merged