[ES] added content/es/data-center.md
cncf/glossary pull request #1801
Opened 2023-03-09 18:38 UTC by marianogg9

### Describe your changes
- added `content/es/data-center.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- resolves #597 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-09 23:15 UTC, electrocucaracha commented
Parece ser que este término sufrió algunas actualizaciones recientemente y difiere bastante la [versión](https://github.com/cncf/glossary/blob/main/content/en/data-center.md) de `main`. @krol3 podrías actualizar el branch de `dev-es`?

2023-03-10 14:56 UTC, krol3 commented
> Parece ser que este término sufrió algunas actualizaciones recientemente y difiere bastante la [versión](https://github.com/cncf/glossary/blob/main/content/en/data-center.md) de `main`. @krol3 podrías actualizar el branch de `dev-es`?

Claro si !

2023-03-23 16:37 UTC, krol3 commented
@electrocucaracha , @ramrodo  pueden ayudar a revisar este PR?

2023-04-02 16:09 UTC, electrocucaracha commented
@marianogg9 podrías hacerle rebase a este PR (`git rebase dev-es`) para tener los últimos cambios al documento

2023-04-02 16:10 UTC, electrocucaracha requested changes
@marianogg9 podrías realizar `git rebase dev-es` a este PR para obtener los últimos cambios del documento

2023-04-03 18:21 UTC, electrocucaracha commented on content/es/data-center.md
> +status: Feedback Appreciated
@marianogg9 estás utilizando la última [versión](https://github.com/cncf/glossary/blob/dev-es/content/en/data-center.md) del documento?

2023-04-05 17:07 UTC, marianogg9 commented on content/es/data-center.md
> +status: Feedback Appreciated
si, disculpas, no habia actualizado el header

2023-04-05 20:57 UTC, ramrodo approved these changes
/lgtm

2023-04-25 15:55 UTC, electrocucaracha approved these changes

2023-04-25 15:56 UTC, merged