Update _index.md
cncf/glossary pull request #1808
Opened 2023-03-17 02:30 UTC by valeriahhdez

Add a section on how to solve spell-check failures. Replace heading verbs with the infinitive form to make them parallel.

### Describe your changes
This PR replaces heading verbs with infinitive forms to create parallel structures.  
It also adds a section that describes what to do in case a PR's spell-check fails. 

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-17 19:22 UTC, electrocucaracha requested changes

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/.wordlist.txt
> +click
```suggestion
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +4. Al terminar, describa los cambios en el mensaje del commit y dé click en "Sign off and propose changes".
La versión de `click` en español según la [RAE](https://dle.rae.es/clic) es `clic`
```suggestion
4. Al terminar, describa los cambios en el mensaje del commit y dé clic en "Sign off and propose changes". 
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +Nótese que las palabras están ordenadas alfabéticamente. Le pedimos encarecidamente cuide este orden.
```suggestion
Nótese que las palabras están en orden alfabético, le pedimos encarecidamente mantenga este orden. 
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/contribute/_index.md
>  3) [Actualizar los existentes](#update-an-existing-term)
```suggestion
3) [Actualizar un término existente](#update-an-existing-term)
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +## Ayudar a traducir el glosario
```suggestion
## Ayudar a traducir el glosario {#help-translate-the-glossary}
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +5. resolver fallas en la {revisión de ortografía}(#spell-check).
```suggestion
5. resolver fallas en la [revisión de ortografía](#spell-check).
```

2023-03-17 19:22 UTC, electrocucaracha commented on content/es/.wordlist.txt
>  Not
```suggestion
Nicolas
Not
nótese
```

2023-03-17 21:57 UTC, electrocucaracha requested changes

2023-03-17 21:57 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +2. Vaya a la carpeta "es" y localice el archivo _".wordlist.txt".
```suggestion
2. Vaya a la carpeta "es" y localice el archivo ".wordlist.txt".
```

2023-03-17 21:57 UTC, electrocucaracha commented on content/es/contribute/_index.md
> +Existen cuatro formas en las que puede contribuir:
```suggestion
Existen cuatro formas en las que se puede contribuir:
```

2023-03-17 23:52 UTC, ramrodo requested changes
¡Excelente contribución!

Solo un pequeño comentario.

2023-03-17 23:52 UTC, ramrodo commented on content/es/contribute/_index.md
> +
Solo dejar una línea en blanco al final de cada archivo.

```suggestion
```

2023-03-21 04:51 UTC, electrocucaracha approved these changes

2023-03-22 15:39 UTC, krol3 approved these changes
Excellent @valeriahhdez

2023-03-22 18:00 UTC, ramrodo commented
/lgtm

2023-03-22 18:02 UTC, merged