localization term autoscaling
cncf/glossary pull request #1809
Opened 2023-03-17 10:12 UTC by sistella

### Describe your changes
new term localization: auto-scaling

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1645 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-20 10:28 UTC, ugho16 commented on content/it/auto-scaling.md
> +increasing the number of servers allowing for more video streaming and scaling back once consumption has normalized.
```suggestion
Con *Autoscaling out* si intende l'aggiunta dinamica di nuove risorse, come ad esempio: l'aumento del numero di server che permettano più streaming video concorrenti, server che potranno poi essere terminati una volta che il flusso si sarà normalizzato.
```

2023-03-30 09:35 UTC, annalisag-spark requested changes

2023-03-30 09:35 UTC, annalisag-spark commented on content/it/auto-scaling.md
> +Questa non elasticità comportava maggiori costi di business e/o perdità di business in caso di disservizi dovuti a un sovraccarico di richieste.
```suggestion
Questa mancanza di elasticità comportava maggiori costi di business e/o perdita di business in caso di disservizi dovuti a un sovraccarico di richieste.
```

2023-03-30 09:35 UTC, annalisag-spark commented on content/it/auto-scaling.md
> +In passato le infrastrutture e le applicazioni erano pensate perchè le loro architetture potessero soddisfare persino i picchi di utilizzo dei sistemi. Questo comportava l'impiego di molte risorse in
```suggestion
In passato le infrastrutture e le applicazioni erano pensate perché le loro architetture potessero soddisfare persino i picchi di utilizzo dei sistemi. Questo comportava l'impiego di molte risorse in maniera non elastica, cioè che non variavano accordandosi al numero di richieste degli utenti.
```

2023-03-30 09:35 UTC, annalisag-spark commented on content/it/auto-scaling.md
> +Possono inoltre monitorare l'utilizzo delle applicazioni e sfruttare la loro scalabilità, offrendo così una esperienza ottimale all'utente. Si consideri ad esempio l'aumento dei fruitori che Netflix
```suggestion
Possono inoltre monitorare l'utilizzo delle applicazioni e sfruttare la loro scalabilità, offrendo così un'esperienza ottimale all'utente. Si consideri ad esempio l'aumento dei fruitori che Netflix deve affrontare il venerdì sera. 
```

2023-04-13 08:00 UTC, annalisag-spark commented
@sistella non so se avessi intercettato i miei suggerimenti. vedi tu se li ritieni sensati :)

2023-05-08 15:48 UTC, annalisag-spark commented on content/it/auto-scaling.md
> +Possono inoltre monitorare l'utilizzo delle applicazioni e sfruttare la loro scalabilità, offrendo così una esperienza ottimale all'utente. Si consideri ad esempio l'aumento dei fruitori che Netflix
@sistella qui ci sono indicazioni pending, appena puoi valutale e possiamo andare avanti, credo :)

2023-05-10 14:04 UTC, annalisag-spark approved these changes

2023-06-29 12:57 UTC, merged