[bn] Localize canary-deployment.md
cncf/glossary pull request #1810
Opened 2023-03-19 14:18 UTC by nerdynikhil

### Describe your changes

Link https://glossary.cncf.io/canary-deployment/

### Related issue number https://github.com/cncf/glossary/issues/410

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-19 18:57 UTC, mitul3737 requested changes

2023-03-19 18:57 UTC, mitul3737 commented on content/bn/canary-deployment.md
> +title: কনেরী ডিপ্লোইমন্ট (Canary Deployment)
```suggestion
title: ক্যানারি ডিপ্লয়মেন্ট (Canary Deployment)
```

2023-03-19 18:57 UTC, mitul3737 commented on content/bn/canary-deployment.md
> +ক্যানারি ডিপ্লোইমন্ট হল একটি স্থাপনার কৌশল যা দুটি পরিবেশ দিয়ে শুরু হয়:
```suggestion
ক্যানারি ডিপ্লয়মেন্ট হল একটি স্থাপনার কৌশল যা দুটি পরিবেশ দিয়ে শুরু হয়:
```

2023-03-19 18:57 UTC, mitul3737 commented on content/bn/canary-deployment.md
> +এটি লাইভ ট্রাফিকের 1%, তারপর 10%, 25% এবং আরও অনেক কিছু সরানোর মাধ্যমে শুরু হতে পারে,
```suggestion
এটি লাইভ ট্রাফিকের 1%, তারপর 10%, 25% এবং আরও অনেক কিছু সরানোর মাধ্যমে শুরু হতে পারে 
```

2023-03-19 18:57 UTC, mitul3737 commented on content/bn/canary-deployment.md
> +যতক্ষণ না সমস্ত ট্রাফিক আপডেট সংস্করণের মাধ্যমে চলছে।
```suggestion
যতক্ষণ না সমস্ত ট্রাফিক আপডেট সংস্করণের মাধ্যমে চলছে।
```

2023-03-19 18:57 UTC, mitul3737 commented on content/bn/canary-deployment.md
> +সংস্থাগুলি উত্পাদনে সফ্টওয়্যারটির নতুন সংস্করণ পরীক্ষা করতে পারে, প্রতিক্রিয়া পেতে পারে,
```suggestion
সংস্থাগুলি উৎপাদনে সফ্টওয়্যারটির নতুন সংস্করণ পরীক্ষা করতে পারে, প্রতিক্রিয়া পেতে পারে,
```

2023-03-21 18:59 UTC, mitul3737 approved these changes

2023-03-21 18:59 UTC, Imtiaz1234 approved these changes

2023-03-21 18:59 UTC, merged