[bn] Localize debugging.md
cncf/glossary pull request #1812
Opened 2023-03-19 14:57 UTC by nerdynikhil

Signed-off-by: Nikhil Barik nklmarch17@gmail.com

Localizes ``debugging.md``  to Bengali

This is an initial PR as may need some improvements!

Tracking issue: #410

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-19 18:49 UTC, mitul3737 requested changes

2023-03-19 18:49 UTC, mitul3737 commented on content/bn/debugging.md
> +সফ্টওয়্যার ডিবেলপ্মন্ট একটি জটিল কার্যকলাপ যা বাগ প্রবর্তন ছাড়া কোড লেখা প্রায় অসম্ভব করে তোলে।
```suggestion
সফ্টওয়্যার  ডেভেলপমেন্ট জটিল কার্যকলাপ যা বাগ প্রবর্তন ছাড়া কোড লেখা প্রায় অসম্ভব করে তোলে।
```

2023-03-19 18:49 UTC, mitul3737 commented on content/bn/debugging.md
> +যখন বাগগুলি উপস্থিত হয়, তখন প্রকৌশলীদের উত্পাদন সিস্টেমের জন্য অবাঞ্ছিত আচরণ কমাতে অ্যাপটি ডিবাগ করতে হয় (যেমন, অনুসন্ধান এবং ঠিক করা)।
```suggestion
যখন বাগগুলি উপস্থিত হয়, তখন প্রকৌশলীদের  উৎপাদন সিস্টেমের জন্য অবাঞ্ছিত আচরণ কমাতে অ্যাপটি ডিবাগ করতে হয় (যেমন, অনুসন্ধান এবং ঠিক করা)।
```

2023-03-19 18:49 UTC, mitul3737 commented on content/bn/debugging.md
> +একবার তারা ব্যর্থতার উত্স সনাক্ত করার পরে, তারা কোডটি সংশোধন করে এবং একটি বাগ ফিক্স বা প্যাচ তৈরি করে।
```suggestion
একবার তারা ব্যর্থতার উৎস সনাক্ত করার পরে, তারা কোডটি সংশোধন করে এবং একটি বাগ ফিক্স বা প্যাচ তৈরি করে।
```

2023-03-21 19:03 UTC, Imtiaz1234 approved these changes

2023-03-21 19:03 UTC, merged