[bn] Localize function-as-a-service.md
cncf/glossary pull request #1813
Opened 2023-03-19 17:09 UTC by nerdynikhil

Signed-off-by: Nikhil Barik nklmarch17@gmail.com
Localizes ``content/bn/function-as-a-service.md``  to Bengali
This is an intial PR as may need some improvements!
Tracking issue: 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-20 03:12 UTC, mitul3737 requested changes

2023-03-20 03:12 UTC, mitul3737 commented on content/bn/function-as-a-service.md
> +title: ফংগক্শন-ঐজ়-এ-সর্বিস (Function as a Service) (FaaS)
```suggestion
title: ফাংশন-এজ়-এ-সার্ভিস (Function as a Service) (FaaS)
```

2023-03-20 03:12 UTC, mitul3737 commented on content/bn/function-as-a-service.md
> +ফংগক্শন-ঐজ়-এ-সর্বিস
```suggestion
ফাংশন-এজ়-এ-সার্ভিস
```

2023-03-20 03:12 UTC, mitul3737 commented on content/bn/function-as-a-service.md
> +একটি পরিষেবা হিসাবে ফাংশন (FaaS) হল এক প্রকার [সর্বরলেস](/bn/serverless/) [ক্লাউড কম্পিউটিং](/bn/cloud-computing/) [সর্বিস](/bn/service/)
```suggestion
একটি পরিষেবা হিসাবে ফাংশন (FaaS) হল এক প্রকার [সার্ভারলেস](/bn/serverless/) [ক্লাউড কম্পিউটিং](/bn/cloud-computing/) [সর্বিস](/bn/service/) 
```

2023-03-20 03:12 UTC, mitul3737 commented on content/bn/function-as-a-service.md
> +সাধারণত [মাইক্রোসার্ভিসেস](/bn/microservices/) অ্যাপ্লিকেশন তৈরি এবং চালু করার সাথে যুক্ত।
```suggestion
সাধারণত [মাইক্রোসার্ভিসেস](/bn/microservices-architecture/) অ্যাপ্লিকেশন তৈরি এবং চালু করার সাথে যুক্ত।
```

2023-03-21 19:04 UTC, mitul3737 approved these changes

2023-03-21 19:04 UTC, Imtiaz1234 approved these changes

2023-03-21 19:04 UTC, merged