[bn] Localize horizontal-scaling.md
cncf/glossary pull request #1814
Opened 2023-03-19 17:33 UTC by nerdynikhil

Signed-off-by: Nikhil Barik [nklmarch17@gmail.com](mailto:nklmarch17@gmail.com)
Localizes `content/bn/horizontal-scaling.md` to Bengali
This is an intial PR as may need some improvements!
Tracking issue:

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-20 03:17 UTC, mitul3737 requested changes

2023-03-20 03:17 UTC, mitul3737 commented on content/bn/horizontal-scaling.md
> +title: অনুভূমিক পরিমাপ (Horizontal Scaling)
```suggestion
title: অনুভূমিক স্কেলিং (Horizontal Scaling)
```

2023-03-20 03:17 UTC, mitul3737 commented on content/bn/horizontal-scaling.md
> +অনুভূমিক স্কেলিং হল এমন একটি কৌশল যেখানে আরও [নাড](/bn/nodes/) যোগ করে একটি সিস্টেমের ক্ষমতা বৃদ্ধি করা হয়।
```suggestion
অনুভূমিক স্কেলিং হল এমন একটি কৌশল যেখানে আরও [নোড](/bn/nodes/) যোগ করে একটি সিস্টেমের ক্ষমতা বৃদ্ধি করা হয়।
```

2023-03-20 03:17 UTC, mitul3737 commented on content/bn/horizontal-scaling.md
> +স্বতন্ত্র নোডগুলিতে আরও গণনা সংস্থান যোগ করার বিপরীতে (পরবর্তীটি [উল্লম্ব পরিমাপে](/bn/vertical-scaling/) নামে পরিচিত)।
```suggestion
স্বতন্ত্র নোডগুলিতে আরও গণনা সংস্থান যোগ করার বিপরীতে (পরবর্তীটি [উল্লম্ব স্কেলিং](/bn/vertical-scaling/) নামে পরিচিত)।
```

2023-03-20 03:17 UTC, mitul3737 commented on content/bn/horizontal-scaling.md
> +এই পদ্ধতিটি নতুন দৃষ্টান্ত, বা [নাড](/bn/nodes/), যোগ করে একটি অ্যাপ্লিকেশনের কর্মক্ষমতা বাড়ায়
```suggestion
এই পদ্ধতিটি নতুন দৃষ্টান্ত, বা [নোড](/bn/nodes/), যোগ করে একটি অ্যাপ্লিকেশনের কর্মক্ষমতা বাড়ায়
```

2023-03-20 03:17 UTC, mitul3737 commented on content/bn/horizontal-scaling.md
> +* [উল্লম্ব পরিমাপে](/bn/vertical-scaling/)
```suggestion
* [উল্লম্ব  স্কেলিং](/bn/vertical-scaling/)
```

2023-03-21 19:07 UTC, mitul3737 approved these changes

2023-03-21 19:08 UTC, Imtiaz1234 approved these changes

2023-03-21 19:12 UTC, merged

2024-01-20 12:23 UTC, asem-hamid commented
Fixes #1866