[bn] Localize managed-services.md
cncf/glossary pull request #1818
Opened 2023-03-19 18:59 UTC by nerdynikhil

Signed-off-by: Nikhil Barik [nklmarch17@gmail.com](mailto:nklmarch17@gmail.com)
Localizes `content/bn/managed-services.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue:

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-20 03:35 UTC, mitul3737 requested changes

2023-03-20 03:35 UTC, mitul3737 commented on content/bn/managed-services.md
> +title: মৈনিজ্ড (Managed services)
```suggestion
title: ম্যানাজ্ড সার্ভিসেস (Managed services)
```

2023-03-20 03:35 UTC, mitul3737 commented on content/bn/managed-services.md
> +একটি মৈনিজ্ড পরিষেবা হল একটি সফ্টওয়্যার অফার যেখানে অপারেশন এবং পরিচালনা তৃতীয় পক্ষ দ্বারা যত্ন নেওয়া হয়।
```suggestion
একটি ম্যানাজ্ড  পরিষেবা হল একটি সফ্টওয়্যার অফার যেখানে অপারেশন এবং পরিচালনা তৃতীয় পক্ষ দ্বারা যত্ন নেওয়া হয়।
```

2023-03-20 03:35 UTC, mitul3737 commented on content/bn/managed-services.md
> +মৈনিজ্ড পরিষেবাগুলি প্রথম দিন থেকে খুব কম অপারেশনাল ওভারহেড সহ ব্যবহারের জন্য প্রস্তুত৷
```suggestion
ম্যানাজ্ড  পরিষেবাগুলি প্রথম দিন থেকে খুব কম অপারেশনাল ওভারহেড সহ ব্যবহারের জন্য প্রস্তুত৷
```

2023-03-20 03:35 UTC, mitul3737 commented on content/bn/managed-services.md
> +ভালভাবে সংজ্ঞায়িত, এবং সাধারণত [API](/bn/application-programming-interface/) চালিত, সীমানা।
```suggestion
ভালভাবে সংজ্ঞায়িত, এবং সাধারণত [API](/bn/application-programming-interface/) চালিত সীমানা।
```

2023-03-21 19:13 UTC, mitul3737 approved these changes

2023-03-21 19:13 UTC, Imtiaz1234 approved these changes

2023-03-21 19:13 UTC, merged