[bn] localize Service Mesh.md
cncf/glossary pull request #1826
Opened 2023-03-22 05:53 UTC by Refayatul

Localized content/bn/service-mesh.md to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #410

2023-03-22 18:18 UTC, mitul3737 requested changes

2023-03-22 18:18 UTC, mitul3737 commented on content/bn/service-mesh.md
> +পরিষেবাগুলির মধ্যে ট্র্যাফিক (যেমন, যোগাযোগ) পরিচালনা করে এবং [নির্ভরযোগ্যতা](/reliability/), [অবজারভেবিলিটি](/observability/), এবং
```suggestion
পরিষেবাগুলির মধ্যে ট্র্যাফিক (যেমন, যোগাযোগ) পরিচালনা করে এবং [নির্ভরযোগ্যতা](/bn/reliability/), [অবজারভেবিলিটি](/bn/observability/), এবং
```

2023-03-23 06:04 UTC, mitul3737 approved these changes

2023-03-23 09:01 UTC, mitul3737 requested changes

2023-03-23 09:01 UTC, mitul3737 commented on content/bn/service-mesh.md
> +## সমাধান
```suggestion
## এটা কিভাবে সাহায্য করে
```

2023-03-23 09:01 UTC, mitul3737 commented on content/bn/service-mesh.md
> +## সমস্যা
```suggestion
## এটা যেসব সমস্যাতে দৃষ্টিপাত করে
```

2023-03-23 11:55 UTC, mitul3737 approved these changes

2023-03-23 11:57 UTC, Imtiaz1234 approved these changes

2023-03-23 12:02 UTC, merged