[bn] loalized mutual-transport-layer-security.md
cncf/glossary pull request #1827
Opened 2023-03-22 06:21 UTC by Refayatul

[bn] Localized content/bn/mutual-transport-layer-security.md to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #410

2023-03-22 17:17 UTC, mitul3737 requested changes

2023-03-22 17:17 UTC, mitul3737 commented on content/bn/mutual-transport-layer-security.md
> +মিউচুয়াল টিএলএস (এমটিএলএস) একটি প্রযুক্তি যা দুটি [পরিষেবা](/service/) এর মধ্যে প্রেরিত বার্তাগুলি প্রমাণীকরণ এবং এনক্রিপ্ট করতে ব্যবহৃত হয়।
```suggestion
মিউচুয়াল টিএলএস (এমটিএলএস) একটি প্রযুক্তি যা দুটি [পরিষেবা](/bn/service/) এর মধ্যে প্রেরিত বার্তাগুলি প্রমাণীকরণ এবং এনক্রিপ্ট করতে ব্যবহৃত হয়। 
```

2023-03-22 17:17 UTC, mitul3737 commented on content/bn/mutual-transport-layer-security.md
> +মিউচুয়াল টিএলএস একটি [ট্রান্সপোর্ট লেয়ার সিকিউরিটি](/transport-layer-security/) (টিএলএস) প্রোটোকল কিন্তু, শুধুমাত্র একটি সংযোগের পরিচয় যাচাই করার পরিবর্তে উভয় পক্ষকেই যাচাই করে।
```suggestion
মিউচুয়াল টিএলএস একটি [ট্রান্সপোর্ট লেয়ার সিকিউরিটি](/bn/transport-layer-security/) (টিএলএস) প্রোটোকল কিন্তু, শুধুমাত্র একটি সংযোগের পরিচয় যাচাই করার পরিবর্তে উভয় পক্ষকেই যাচাই করে।
```

2023-03-22 17:17 UTC, mitul3737 commented on content/bn/mutual-transport-layer-security.md
> +[মাইক্রোপরিষেবা](/microservices/) একটি নেটওয়ার্কের মাধ্যমে যোগাযোগ করে এবং আপনার ওয়াইফাই নেটওয়ার্কের মতো, সেই নেটওয়ার্কে যোগাযোগ ট্রান্সলেশনগুলি হ্যাক হতে পারে।
```suggestion
[মাইক্রোপরিষেবা](/bn/microservices-architecture/) একটি নেটওয়ার্কের মাধ্যমে যোগাযোগ করে এবং আপনার ওয়াইফাই নেটওয়ার্কের মতো, সেই নেটওয়ার্কে যোগাযোগ ট্রান্সলেশনগুলি হ্যাক হতে পারে। 
```

2023-03-23 06:04 UTC, mitul3737 approved these changes

2023-03-23 09:01 UTC, Imtiaz1234 requested changes

2023-03-23 09:01 UTC, Imtiaz1234 commented on content/bn/mutual-transport-layer-security.md
> +## সমস্যা
```suggestion
## এটা যেসব সমস্যাতে দৃষ্টিপাত করে
```

2023-03-23 09:01 UTC, Imtiaz1234 commented on content/bn/mutual-transport-layer-security.md
> +## সমাধান
```suggestion
## এটা কিভাবে সাহায্য করে
```

2023-03-23 11:55 UTC, mitul3737 approved these changes

2023-03-23 11:57 UTC, Imtiaz1234 approved these changes

2023-03-23 11:57 UTC, merged