[bn] Localization for Distributed apps
cncf/glossary pull request #1832
Opened 2023-03-22 10:06 UTC by abhijeet-26

Signed-off-by: Abhijeet Basfore abhibas14@gmail.com

### Describe your changes
link -> https://glossary.cncf.io/distributed-apps/

### Related issue number or link (ex: `resolves #issue-number`)
#410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-23 08:55 UTC, mitul3737 requested changes

2023-03-23 08:55 UTC, mitul3737 commented on content/bn/distributed-apps.md
> +## এটি যেই সমস্যাটি নির্দেশ করে
```suggestion
## এটা যেসব সমস্যাতে দৃষ্টিপাত করে
```

2023-03-23 08:55 UTC, mitul3737 commented on content/bn/distributed-apps.md
> +## এটা কিভাবে সাহায্য করে
```suggestion
## এটা কিভাবে সাহায্য করে
```

2023-03-23 08:55 UTC, mitul3737 commented on content/bn/distributed-apps.md
> +বিতরিত অ্যাপ্লিকেশনগুলি সাধারণত পৃথক [মাইক্রোসার্ভিসগুলির](/bn/microservices/)  সমন্বয়ে গঠিত হয় যা বিস্তৃত অ্যাপ্লিকেশনের মধ্যে বিভিন্ন উদ্বেগ পরিচালনা করে।
```suggestion
বিতরিত অ্যাপ্লিকেশনগুলি সাধারণত পৃথক [মাইক্রোসার্ভিসগুলির](/bn/microservices-architecture/)  সমন্বয়ে গঠিত হয় যা বিস্তৃত অ্যাপ্লিকেশনের মধ্যে বিভিন্ন উদ্বেগ পরিচালনা করে। 
```

2023-03-23 08:55 UTC, mitul3737 commented on content/bn/distributed-apps.md
> +একটি ক্লাউড নেটিভ পরিবেশে, পৃথক উপাদানগুলি সাধারণত একটি [ক্লাস্টারে](/cluster/) [পাত্র(container)](/bn/container/)   হিসাবে চালিত হয়।
```suggestion
একটি ক্লাউড নেটিভ পরিবেশে, পৃথক উপাদানগুলি সাধারণত একটি [ক্লাস্টারে](/bn/cluster/) [পাত্র(container)](/bn/container/)   হিসাবে চালিত হয়। 
```

2023-03-23 09:04 UTC, mitul3737 requested changes

2023-03-23 09:04 UTC, mitul3737 commented on content/bn/distributed-apps.md
> +## এটি যেই সমস্যাটি নির্দেশ করে
```suggestion
## এটা যেসব সমস্যাতে দৃষ্টিপাত করে
```

2023-03-30 16:33 UTC, mitul3737 approved these changes

2023-03-30 16:47 UTC, Imtiaz1234 approved these changes

2023-03-30 16:47 UTC, merged