ai-naymul/issue #1779
cncf/glossary pull request #1854
Opened 2023-03-29 13:20 UTC by ai-naymul

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-29 16:21 UTC, ai-naymul commented
I am a newbie to contribute to open source It's my first contribtion so if there is any mistake that I have done please give me review of that
Thank you :)

2023-03-29 16:55 UTC, ramrodo commented
Hi @ai-naymul, thanks for your contribution, and congrats on your first contribution! :)

Before we can merge your PR, all the tests should pass. Right now, the [DCO verification is failing](https://github.com/cncf/glossary/pull/1854/checks?check_run_id=12366217887).

To solve this, you need to sign off your commits. You can find more info on how to do/set up this in the template at opening a PR:

```
[ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`)
    is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco).
    If you are working locally, you could add an alias to your `gitconfig` by running
    `git config --global alias.ci "commit -s"`.
```

It's probably that you need to amend your commits or delete those and create them again now with signing off them.

2023-03-29 16:58 UTC, ramrodo commented on content/es/tightly-coupled-architectures.md
> +etiquetas: ["fundamental", "arquitectura", "propiedad"]
This whole section should not be translated. See [this other Spanish localization](https://github.com/cncf/glossary/blob/dev-es/content/es/distributed-systems.md?plain=1#L2-L5) where we keep the words in the original language.

2023-03-29 17:00 UTC, ramrodo commented on content/es/tightly-coupled-architectures.md
> +La arquitectura estrechamente acoplada es un estilo arquitectónico en el que varios componentes de la aplicación son interdependientes.(el paradigma opuesto de [arquitecturas débilmente acopladas](/a
```suggestion
La arquitectura estrechamente acoplada es un estilo arquitectónico en el que varios componentes de la aplicación son interdependientes (el paradigma opuesto de [arquitecturas débilmente acopladas](/arquitectura débilmente acoplada/)).Esto significa que un cambio en un componente probablemente afectará a otros componentes. Por lo general, es más fácil de implementar que los estilos arquitectónicos acoplados de forma más flexible, pero puede dejar un sistema más vulnerable a fallas en cascada. También tienden a requerir implementaciones coordinadas de componentes que pueden volverse un lastre para la productividad del desarrollador.
```

2023-03-29 17:05 UTC, ramrodo requested changes
It seems that you're taking a deprecated version of the file. The most recent version of this concept is:

https://github.com/cncf/glossary/blob/main/content/en/tightly-coupled-architectures.md?plain=1

and this localization differs from the paragraphs you translated.

Please use the most recent version and submit your changes again.

2023-03-29 17:12 UTC, ai-naymul reviewed
I have changed the path and the header of the file
Thank you :)

2023-03-29 17:41 UTC, ai-naymul commented
Hello ramrodo,
Please check the file is that correct or not or is there any mistake I have done let me know
and this is my first time that's why all of these happening :)

Sorry for your inconvenience

2023-03-29 18:22 UTC, ramrodo commented on content/es/tightly-coupled-architectures.md
> +También tienden a requerir lanzamientos coordinados de componentes.
```suggestion
También tienden a requerir lanzamientos coordinados de componentes
```

2023-03-29 18:24 UTC, ramrodo commented on content/es/tightly-coupled-architectures.md
> +Si bien no es necesariamente consistente con todas las mejores prácticas de desarrollo de [microservicios](/microservicios/)
```suggestion
Si bien no es necesariamente consistente con todas las mejores prácticas de desarrollo de [microservicios](/es/microservices-architecture/)
```

2023-03-29 18:25 UTC, ramrodo commented on content/es/tightly-coupled-architectures.md
> +al igual que las [aplicaciones monolíticas](/monolithic-apps/), pueden acelerar el ciclo de desarrollo inicial.
```suggestion
al igual que las [aplicaciones monolíticas](/es/monolithic-apps/), pueden acelerar el ciclo de desarrollo inicial.
```

2023-03-29 23:07 UTC, ai-naymul commented
I have change those please check that correct or not or is there any mistake I have done let me know
And please give me some tips why my DCO is faillng again and again,I am commiting the "signed-of-by" everytime but it's failing please help me in that case
 #case?https://github.com/cncf/glossary/pull/1854/commits/053bb51c437c013817b7d6c0732f718ca1152d7a

2023-04-01 06:54 UTC, ai-naymul commented
> > I have change those please check that correct or not or is there any mistake I have done let me know And please give me some tips why my DCO is faillng again and again,I am commiting the "signed-of-by" everytime but it's failing please help me in that case how can I solve this #case?[053bb51](https://github.com/cncf/glossary/commit/053bb51c437c013817b7d6c0732f718ca1152d7a)
> 
> @ai-naymul sure. In order to fix and sign-off all the previous commits, you could follow the instructions given in the [DCO test details](https://github.com/cncf/glossary/pull/1854/checks?check_run_id=12385104199):
> 
> ![image](https://user-images.githubusercontent.com/2797052/229185600-2d27bb6c-9ca7-4ba5-9c4a-fb31b54be5ea.png)
> 
> Since in the beginning, many commits were missing the sign-off, you should do a `git ammend` or `git rebase` to re-write the commit messages.
> 
> Let me know if this information helps you.

 I have made a mistake by doing a empty commit to try to fix the failure,I try a lot ,Can I delete the whole pull request and make it again to fix that?

2023-04-03 16:47 UTC, 92nqb commented
Hi @ai-naymul, 

have you tried with the command `git rebase HEAD~15 --signoff`?  I think that it would fix the issue with the DCO.

Let me know if it works :)

2023-04-03 17:01 UTC, ai-naymul commented
> git rebase HEAD~15 --signoff

Hello @92nqb,
I try it and after trying the `tightly-coupled-architectures.md` file is deleted from the `content/es` directory .
So what should I do now, make the pull request again or not?
I am extremely sorry for you inconvenience 
Thank you :)

2023-04-04 16:29 UTC, krol3 requested changes

2023-04-04 16:29 UTC, krol3 commented on assets/scss/_cookie-banner.scss
the Spanish translation only do changes in the `content/es`, for any doubt please join us to our calls also you can find groups in your local languages to collaborate @ai-naymul

2023-04-09 14:48 UTC, ai-naymul commented
Hello @ramrodo ,
I have been facing problem with rebasing the commits,could you please help me?
should I use `git reset --soft HEAD~66` to reset all commit and make it again?
Thank you :)

2023-04-10 21:16 UTC, ramrodo commented
> Hello @ramrodo , I have been facing problem with rebasing the commits,could you please help me? should I use `git reset --soft HEAD~66` to reset all commit and make it again? Thank you :)

Right @ai-naymul, resetting with `--soft` is a good option to re-write the commits and add the sign-off.

2023-07-01 00:09 UTC, closed without merging