[es] #1775 Issue: Localized the software-as-a-service.md document
cncf/glossary pull request #1856
Opened 2023-03-30 13:14 UTC by ai-naymul

### Describe your changes
Localized the content/en/software-as-a-service.md document into Spanish

### Related issue number or link (ex: `resolves #issue-number`)
Tracking issue: #1775 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-03-30 18:12 UTC, ai-naymul commented
@electrocucaracha I am a newbie contributor so If I have done any mistake please give me a review 
Thanks a lot for your consideration :)

2023-03-31 17:24 UTC, ramrodo commented
Thanks for your contribution!

I just realized that this concept of _"Software as a Service (SaaS)"_ [is marked as Deprecated](https://github.com/cncf/glossary/blob/main/content/en/software-as-a-service.md?plain=1#L3) in the **main** branch.

Should we translate these concepts @electrocucaracha? I don't remember well.

2023-03-31 17:45 UTC, electrocucaracha commented
> Thanks for your contribution!
> 
> I just realized that this concept of _"Software as a Service (SaaS)"_ [is marked as Deprecated](https://github.com/cncf/glossary/blob/main/content/en/software-as-a-service.md?plain=1#L3) in the **main** branch.
> 
> Should we translate these concepts @electrocucaracha? I don't remember well.

Right, maybe these terms should have the lowest priority until we discuss them with other maintainers.

2023-04-03 17:03 UTC, ai-naymul commented
> Thanks for your contribution!
> 
> I just realized that this concept of _"Software as a Service (SaaS)"_ [is marked as Deprecated](https://github.com/cncf/glossary/blob/main/content/en/software-as-a-service.md?plain=1#L3) in the **main** branch.
> 
> Should we translate these concepts @electrocucaracha? I don't remember well.

Okay no problem😊

2023-04-04 16:24 UTC, krol3 commented
@ai-naymul  you need to change it to the branch `dev-es`,  instructions [here]([Contribution guide](https://github.com/cncf/glossary/blob/dev-es/content/es/contribute/_index.md#ayudar-a-traducir-el-glosario-help-translate-the-glossary))

2023-04-06 17:09 UTC, ai-naymul commented
> @ai-naymul you need to change it to the branch `dev-es`, instructions [here]([Contribution guide](https://github.com/cncf/glossary/blob/dev-es/content/es/contribute/_index.md#ayudar-a-traducir-el-glosario-help-translate-the-glossary))

I have changed the branch to `dev-es` :)

2023-04-06 18:14 UTC, ramrodo commented on content/es/software-as-a-service.md
> +Category: Technology
The category should be in Spanish

```suggestion
Category: Tecnología
```

2023-04-06 18:17 UTC, ramrodo requested changes
I'll like to invite you to review our [Contribution guide](https://github.com/cncf/glossary/blob/dev-es/content/es/contribute/_index.md#ayudar-a-traducir-el-glosario-help-translate-the-glossary), there are a few additional considerations for translating terms in Spanish.

2023-04-06 18:21 UTC, ramrodo requested changes

2023-04-06 18:21 UTC, ramrodo commented on content/es/software-as-a-service.md
> +The up front cost associated with licenses, installation, and potentially additional hardware can be prohibitive.
All these words are in English instead of Spanish.

2023-04-10 21:08 UTC, ramrodo commented on content/es/software-as-a-service.md
> +## Lo que es
```suggestion
## ¿Qué es?
```

2023-04-10 21:08 UTC, ramrodo commented on content/es/software-as-a-service.md
> +## Problema que aborda
```suggestion
## ¿Cómo ayuda?
```

2023-04-10 21:11 UTC, ramrodo commented on content/es/software-as-a-service.md
> +## Cómo ayuda
```suggestion
## ¿Cómo ayuda?
```

2023-04-10 21:13 UTC, ramrodo commented
Also, add the word(s) missing to the spellcheck file, please.

2023-04-16 06:42 UTC, ai-naymul commented
> Also, add the word(s) missing to the spellcheck file, please.

Please check the file now
Thank you :)

2023-04-18 08:25 UTC, krol3 commented
Hi @ai-naymul , What is your local language, do you speak Spanish? Regards

2023-04-18 17:24 UTC, ai-naymul commented
> Hi @ai-naymul , What is your local language, do you speak Spanish? Regards

No I don't speak spanish, our local language is Bengali and English.

2023-04-25 16:34 UTC, ramrodo approved these changes
I think the localization looks good to me now

2023-04-25 17:11 UTC, electrocucaracha approved these changes

2023-04-25 17:12 UTC, merged