[Spanish] localize 'Site Reliability Engineering'
cncf/glossary pull request #1858
Opened 2023-03-31 10:16 UTC by Azanul

### Describe your changes
Translated site-reliability-engineering.md in spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1774 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-01 20:12 UTC, ramrodo commented on content/es/site-reliability-engineering.md
> +Hay similitudes con [DevOps](/devops/), pero mientras DevOps se enfoca en llevar el código a producción,
```suggestion
Hay similitudes con [DevOps](/es/devops/), pero mientras DevOps se enfoca en llevar el código a producción,
```

2023-04-01 20:13 UTC, ramrodo commented on content/es/site-reliability-engineering.md
> +desde la supervisión del rendimiento, las alertas, la [depuración](/debugging/) hasta la resolución de problemas.
```suggestion
desde la supervisión del rendimiento, las alertas, la [depuración](/es/debugging/) hasta la resolución de problemas.
```

2023-04-01 20:15 UTC, ramrodo commented on content/es/site-reliability-engineering.md
> +Este enfoque ayuda a crear sistemas de software altamente [escalables](/scalability/) y confiables mediante la automatización de tareas operativas.
```suggestion
Este enfoque ayuda a crear sistemas de software altamente [escalables](/es/scalability/) y confiables mediante la automatización de tareas operativas.
```

2023-04-01 20:17 UTC, ramrodo requested changes
Thanks for your contribution!

Just some suggestions to update the concepts already localized adding `/es/`

2023-04-01 20:17 UTC, Azanul commented
> Thanks for your contribution!
> 
> Just some suggestions to update the concepts already localized adding `/es/`

Applied the suggested changes

2023-04-01 20:28 UTC, electrocucaracha commented
@Azanul Spanish translations must target to `dev-es` branch. Maybe you'll require to redo this PR using `dev-es` branch as a base instead of `main`

2023-04-04 16:25 UTC, ramrodo requested changes
@Azanul could you keep only the changes related to the localization and remove the GitHub Actions upgrades and SCSS, please?

2023-04-04 16:48 UTC, krol3 requested changes

2023-04-04 16:59 UTC, Azanul commented
For now, I've force pushed to resolve it.

2023-04-04 17:08 UTC, ramrodo commented
> @ramrodo @krol3 There's something wrong here. I didn't change any of those. Someone else has also faced the same issue. #1855

This error is probably due to a rebase problem. We should rebase our branch and keep it updated against the `main` branch. With that, the PR/branch should not include other changes.

2023-04-05 20:49 UTC, ramrodo requested changes
Could you do a rebase against the upstream **dev-es** branch, please? It seems there are some conflicts with the `content/es/.wordlist.txt` file.

2023-04-06 05:02 UTC, Azanul commented
@ramrodo Resolved conflicts

2023-04-06 18:29 UTC, ramrodo requested changes
Suggestion made

2023-04-06 18:29 UTC, ramrodo commented on content/es/site-reliability-engineering.md
> +Sin estos, los operadores del sistema solo pueden reaccionar a los problemas en lugar de trabajar de manera proactiva para evitarlos.
Remove the final dot. This dot is not in the original English file and this was added automatically by using a machine translator:

```suggestion
Sin estos, los operadores del sistema solo pueden reaccionar a los problemas en lugar de trabajar de manera proactiva para evitarlos
```

2023-04-10 21:16 UTC, ramrodo approved these changes
Thanks!
/lgtm

2023-04-10 21:36 UTC, krol3 approved these changes
ltgm

2023-04-10 21:37 UTC, merged