Traduction de scalability.md
cncf/glossary pull request #1862
Opened 2023-03-31 22:09 UTC by huats

### Describe your changes

This PR localizes scalability concept to French

### Related issue number or link (ex: `resolves #issue-number`)

resolves #1840 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-01 16:24 UTC, Krast76 requested changes

2023-04-01 16:24 UTC, Krast76 commented on content/fr/scalability.md
> +C'est à dire augmenter la capacité d'un système à faire ce qu'il supposé faire.
ce qu'il est supposé

2023-04-01 16:24 UTC, Krast76 commented on content/fr/scalability.md
> +D'un coté, il y a l'[extensibilité horizontale](/horizontal-scaling/) aui ajoute des noeuds pour supporter l'augmentation de charge.
qui ajoute des noeuds*

2023-04-15 09:00 UTC, Krast76 commented on content/fr/scalability.md
> +A l'opposé, il y a l'[extensibilité verticale](/vertical-scaling/) où les nodes individuelles sont rendues plus performantes pour permettre plus de transactions
les nodes -> les noeuds individuels sont rendus plus performants

2023-04-15 09:00 UTC, Krast76 commented on content/fr/scalability.md
> +Un système extensible est capable de changer facilement pour satisfaire les besoins des utilisateurs.
est -> et

2023-04-16 22:38 UTC, huats commented on content/fr/scalability.md
> +Un système extensible est capable de changer facilement pour satisfaire les besoins des utilisateurs.
Euh non sur ce coup c'est bien "est" :)

2023-04-21 19:35 UTC, Krast76 commented on content/fr/scalability.md
> +C'est à dire augmenter la capacité d'un système à faire ce qu'il est supposé faire.
Je rajouterai bien un à entre "C'est à dire" et "augmenter" -> C'est à dire à augmenter la capacité...

2023-05-03 02:46 UTC, fydrah requested changes

2023-05-03 02:46 UTC, fydrah commented on content/fr/scalability.md
> +ou en réduisant le nombre d'applications [contenerisées](/containerization/),
'contenerisées' --> 'conteneurisées' ?

2023-05-03 02:46 UTC, fydrah commented on content/fr/scalability.md
> +A l'opposé, il y a l'[extensibilité verticale](/vertical-scaling/) où les noeuds individuels sont rendus plus performants pour permettre plus de transactions
A --> À

2023-05-03 02:51 UTC, fydrah reviewed
Dans https://github.com/cncf/glossary/pull/1709, on parle de 'passer à l'échelle'. Ici, on parle d'extensibilité. Il faudrait que l'on reste cohérent. J'ai plus eu l'habitude de 'mise à l'échelle' pour la traduction.

2023-05-14 16:03 UTC, sestegra requested changes

2023-06-20 15:34 UTC, sestegra approved these changes
LGTM 🚀

2023-06-23 10:04 UTC, sestegra commented
Comme je ne suis pas encore Owner dans la branche "dev-fr", il faut que @fydrah approuve le PR.

2023-06-23 12:05 UTC, merged