[ES] added missing sections + semantic line breaks in content/es/style-guide
cncf/glossary pull request #1867
Opened 2023-04-01 15:09 UTC by marianogg9

### Describe your changes
- added missing sections + semantic line breaks in `content/es/style-guide/_index.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1667 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-02 15:38 UTC, electrocucaracha requested changes
@marianogg9 muchas gracias por la actualización de la guía. Deje algunos cambios mínimos al respecto. Además, parece ser que la sección de `Categoría` [fue](https://github.com/cncf/glossary/commit/fd7222d9d21e10dfda9142636df1119c7976da18) remplazada por `Etiquetas`, podrías agregar ese cambio?

2023-04-02 15:38 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +Nuestro objetivo es facilitar la comprensión de términos nativos de nube a cualquiera.
```suggestion
## Contenido mínimo viable

Nuestro objetivo es facilitar la comprensión de términos nativos de nube a cualquiera.
```

2023-04-02 15:38 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +**No cometa plagio**. Como cualquier publicación seria, las mismas reglas aplican al Glosario.
```suggestion
Tenga en cuenta que la etiqueta **properties** no requiere secciones separadas.Una definición será suficiente.

Para facilitar la revisión, por favor utilice **[semántica de saltos de línea](https://sembr.org/)** (una oración por línea).

#### La calidad es esencial

Si ha sido agregada, su contribución sera la definición oficial de la CNCF para ese término (hasta que alguien más la mejore).
Crear un término que cumpla con los altos estándares de la CNCF no puede ser un proceso apurado - la calidad toma su tiempo y esfuerzo.

**Haga su investigación**: Incluso si usted se siente confiado de que conoce el término, verifique que realmente es como lo piensa.
Habitualmente utilizamos términos en una organización de una cierta manera que no refleja el panorama completo.
Cuando haga su investigación, especialmente cuando el término no sea del todo familiar, utilice múltiples fuentes.
Muchas definiciones son algo subjetivas, especialmente si provienen de un proveedor.
El Glosario debe contener definiciones aceptadas globalmente y sin perspectivas particulares.

**No cometa plagio**. Como cualquier publicación seria, las mismas reglas aplican al Glosario.
```

2023-04-02 15:38 UTC, electrocucaracha commented on content/es/style-guide/_index.md
>  Antes de comenzar, lea algunos de los términos publicados del Glosario para tener una idea del nivel de detalle y dificultad y cuándo los ejemplos son apropiados.
```suggestion
Antes de comenzar, lea algunos de los términos publicados del Glosario
para tener una idea del nivel de detalle y dificultad y cuándo los ejemplos son apropiados.
```

2023-04-02 15:38 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +Agradecemos su paciencia.
```suggestion
Ocasionalmente, podremos revisar los términos rápidamente; en otras ocasiones, puede llevar algo de tiempo — agradecemos su paciencia.
```

2023-04-03 18:30 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +- application
```suggestion
Las etiquetas existentes son:

- application
```

2023-04-12 17:35 UTC, electrocucaracha approved these changes

2023-04-12 21:01 UTC, ramrodo approved these changes
/lgtm

2023-04-12 21:02 UTC, merged