[ES] added content/es/horizontal-autoscaling.md
cncf/glossary pull request #1870
Opened 2023-04-01 17:03 UTC by marianogg9

### Describe your changes
- added `content/es/horizontal-autoscaling.md`

### Related issue number or link (ex: `resolves #issue-number`)
- #1765 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-01 20:38 UTC, electrocucaracha requested changes

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +en vez de agregar más recursos computacionales a nodos individuales (conocido como [escalado vertical](/es/vertical-scaling/)).
```suggestion
en vez de agregar más recursos computacionales a nodos individuales (conocido como [escalado vertical](/vertical-scaling/)).
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +necesitamos encontrar una manera de [escalar](/es/scale) (agregar capacidad) al sistema.
```suggestion
necesitamos encontrar una manera de [escalar](/scale) (agregar capacidad) al sistema.
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +* [Escalado vertical](/es/vertical-scaling/)
```suggestion
* [Escalado vertical](/vertical-scaling/)
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +Al agregar más instancias al sistema, la aplicación puede procesar una mayor cantidad de pedidos.
```suggestion
Al agregar más instancias al sistema, la aplicación puede procesar una mayor cantidad de peticiones.
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +Si una aplicación puede manejar 1000 pedidos por segundo,
```suggestion
Si una aplicación puede manejar 1000 peticiones por segundo,
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +cada nodo adicional debería incrementar el total de pedidos alrededor de 1000 por segundo.
```suggestion
cada nodo adicional debería incrementar el total de peticiones alrededor de 1000 por segundo.
```

2023-04-01 20:38 UTC, electrocucaracha commented on content/es/horizontal-scaling.md
> +Esto permite más trabajo concurrente
```suggestion
Esto permite hacer más trabajo concurrentemente
```

2023-04-03 18:32 UTC, electrocucaracha approved these changes

2023-04-04 16:15 UTC, krol3 approved these changes
lgtm

2023-04-04 16:15 UTC, merged