[ES] added content/es/hypervisor.md
cncf/glossary pull request #1883
Opened 2023-04-03 17:27 UTC by marianogg9

### Describe your changes
- added `content/es/hypervisor.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1766 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-04 16:18 UTC, krol3 approved these changes
lgtm

2023-04-04 16:32 UTC, electrocucaracha requested changes

2023-04-04 16:32 UTC, electrocucaracha commented on content/es/hypervisor.md
> +y ubicando recursos suficientes para crear [máquinas virtuales](/es/virtual-machine/)
```suggestion
y ubicando recursos suficientes para crear [máquinas virtuales](/virtual-machine/)
```

2023-04-05 20:55 UTC, ramrodo approved these changes
/lgtm

2023-04-12 17:45 UTC, electrocucaracha approved these changes

2023-04-12 17:45 UTC, merged