[it] Localizzazione termine Service Discovery
cncf/glossary pull request #1885
Opened 2023-04-04 16:08 UTC by ugho16

### Describe your changes
Added Service discovery italian localization

### Related issue number or link (ex: `resolves #issue-number`)
Closes #1655 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-06 10:02 UTC, sistella approved these changes
Bella! non ero sicuro sulle "istanze che _compongono_ un servizio": l'idea del service discovery è (anche) che perfino diverse implementazioni possono corrispondere ad uno stesso servizio, se rispettano la stessa interfaccia... se non ricordo male. _Compongono_ richiama un po' alle parti (istanze) che determinano un unicum (il servizio) dove ciascuna serve alle altre. Ma onestamente non ho trovato di meglio :D

2023-05-08 12:54 UTC, annalisag-spark requested changes

2023-05-08 12:54 UTC, annalisag-spark commented on content/it/service-discovery.md
> +Il service discovery è il processo di individuare le singole istanze che compongono un servizio.
```suggestion
Il service discovery è il processo di individuazione delle singole istanze che compongono un servizio.
```

2023-05-08 12:54 UTC, annalisag-spark commented on content/it/service-discovery.md
> +Ogni volta che ciò accade, l'applicazione avrà un nuovo indirizzo e ogni altra applicazione che vuole individuarla avrà bisogno di un servizio che fornisca le informazioni circa il suo nuovo indirizz
```suggestion
Ogni volta che ciò accadrà, l'applicazione avrà un nuovo indirizzo: qualunque altra applicazione che vorrà individuarla avrà bisogno di un servizio che possa fornire le informazioni circa il suo nuovo indirizzo.
```

2023-05-08 15:41 UTC, annalisag-spark approved these changes

2023-05-09 07:33 UTC, merged