[bn] Localized the content/bn/event-driven-architecture.md
cncf/glossary pull request #1900
Opened 2023-04-09 11:20 UTC by ai-naymul

### Describe your changes
Localize the content/bn/event-driven-architecture.md into bengali

### Related issue number or link (ex: `resolves #issue-number`)
Tracking No: #410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-09 12:19 UTC, mitul3737 requested changes

2023-04-09 12:19 UTC, mitul3737 commented on content/bn/event-driven-architecture.md
> +title: ঘটনা-চালিত স্থাপত্য
```suggestion
title: ঘটনা-চালিত স্থাপত্য (Event-Driven Architecture)
```

2023-04-09 12:19 UTC, mitul3737 commented on content/bn/event-driven-architecture.md
> +এই স্থাপত্যটি এমন কাঠামো তৈরি করে যেখানে ঘটনাগুলো তাদের উত্স থেকে (অ্যাপটি একটি রাইডের অনুরোধ করে) থেকে পছন্দসই রিসিভারগুলিতে (আশেপাশে উপলব্ধ ড্রাইভারদের অ্যাপগুলি) সঠিকভাবে রুট করা যেতে পারে।
```suggestion
এই স্থাপত্যটি এমন কাঠামো তৈরি করে যেখানে ঘটনাগুলো তাদের উৎস থেকে (অ্যাপটি একটি রাইডের অনুরোধ করে) থেকে পছন্দসই রিসিভারগুলিতে (আশেপাশে উপলব্ধ ড্রাইভারদের অ্যাপগুলি) সঠিকভাবে রুট করা যেতে পারে।
```

2023-04-09 12:19 UTC, mitul3737 commented on content/bn/event-driven-architecture.md
> +যত বেশি তথ্য বাস্তব সময় পরিণত হয়, ঘটনাগুলো ক্যাপচার করা এবং উপযুক্ত [সার্ভিস](/service/) যা ঘটনার অনুরোধগুলি প্রক্রিয়া করতে হবে তা নিশ্চিত করার জন্য নির্ভরযোগ্য উপায়গুলি খুঁজে পাওয়া ক্রমশ চ্যালে
Kindly make this a more suitable sentence "যত বেশি তথ্য বাস্তব সময় পরিণত হয়, ঘটনাগুলো ক্যাপচার করা এবং উপযুক্ত [সার্ভিস](/bn/service/) যা ঘটনার অনুরোধগুলি প্রক্রিয়া করতে হবে তা নিশ্চিত করার জন্য নির্ভরযোগ্য উপায়গুলি খুঁজে পাওয়া ক্রমশ চ্যালেঞ্জিং হয়ে উঠছে৷"

2023-04-09 12:19 UTC, mitul3737 commented on content/bn/event-driven-architecture.md
> +যত বেশি তথ্য বাস্তব সময় পরিণত হয়, ঘটনাগুলো ক্যাপচার করা এবং উপযুক্ত [সার্ভিস](/service/) যা ঘটনার অনুরোধগুলি প্রক্রিয়া করতে হবে তা নিশ্চিত করার জন্য নির্ভরযোগ্য উপায়গুলি খুঁজে পাওয়া ক্রমশ চ্যালে
```suggestion
যত বেশি তথ্য বাস্তব সময় পরিণত হয়, ঘটনাগুলো ক্যাপচার করা এবং উপযুক্ত [সার্ভিস](/bn/service/) যা ঘটনার অনুরোধগুলি প্রক্রিয়া করতে হবে তা নিশ্চিত করার জন্য নির্ভরযোগ্য উপায়গুলি খুঁজে পাওয়া ক্রমশ চ্যালেঞ্জিং হয়ে উঠছে৷
```

2023-04-09 12:20 UTC, mitul3737 commented
@ai-naymul  You have done a very great job  Although I have asked for some changes here. Feel free to make those changes.

2023-04-09 14:20 UTC, ai-naymul commented
> 

Thank You let me fix those :)

2023-04-10 15:20 UTC, mitul3737 approved these changes

2023-04-10 15:23 UTC, Imtiaz1234 approved these changes

2023-04-10 15:23 UTC, mitul3737 commented
Great job @ai-naymul ! Glad that you contributed to this project. I hope to see you contribute more in this project.

2023-04-10 15:25 UTC, merged

2023-04-10 15:42 UTC, ai-naymul commented
> 

Thanks a lot @mitul3737 bhaiya for giving me this opportunity and ofcourse I am also Looking forward to contribute more on this 😊