[ES] content/es/serverless.md
cncf/glossary pull request #1939
Opened 2023-04-11 16:04 UTC by marianogg9

### Describe your changes
- added `content/es/serverless.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1770 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-11 21:29 UTC, ramrodo commented on content/es/serverless.md
> +La modalidad sin servidor de proveedores de nube públicas usualmente esta medida bajo demanda a través de un modelo de ejecución basado en eventos.
```suggestion
La modalidad sin servidor de proveedores de nube públicas usualmente está medida bajo demanda a través de un modelo de ejecución basado en eventos.
```

2023-04-11 21:38 UTC, ramrodo commented on content/es/serverless.md
> +Title: Sin servidor
@electrocucaracha @krol3 @92nqb, ¿estaría bien colocar el término original en inglés entre paréntesis como `Sin servidor (Serverless)` o solo dejar la traducción como tal?

Ya que aún en Español, siento que es más común _Serverless_. Y colocándolo entre paréntesis como referencia podría ser opción como lo fue para el término de _multitenancy_ de [éste PR](https://github.com/cncf/glossary/pull/1638/files#diff-e39259e7b9696cdc87944e88a1a570ab38112e4d782c4e3f2502fffeaef843fdR2).

2023-04-11 21:38 UTC, ramrodo reviewed
¡Gracias! Solo una sugerencia y un comentario para consulta con los demás.

2023-04-12 17:21 UTC, electrocucaracha commented on content/es/serverless.md
> +Title: Sin servidor
Es raro escuchar esa traducción, pero parece la correcta o al menos es la que [utiliza](https://aws.amazon.com/es/serverless/?nc1=h_ls) AWS. A favor de la recomendación.

2023-04-12 17:34 UTC, electrocucaracha requested changes

2023-04-12 17:34 UTC, electrocucaracha commented on content/es/serverless.md
> +Sin servidor es un modelo de desarrollo cloud native que ayuda a los desarrolladores a
```suggestion
Sin servidor es un modelo de desarrollo nativo en la nube que ayuda a los desarrolladores a
```

2023-04-12 17:34 UTC, electrocucaracha commented on content/es/serverless.md
> +La modalidad sin servidor de proveedores de nube públicas usualmente esta medida bajo demanda a través de un modelo de ejecución basado en eventos.
```suggestion
La modalidad sin servidor en proveedores de nube públicas usualmente es una medida bajo demanda, a través de un modelo de ejecución basado en eventos.
```

2023-04-12 17:34 UTC, electrocucaracha commented on content/es/serverless.md
> +En un modelo de [Infraestructura-como-servicio](/es/infrastructure-as-a-service/),
```suggestion
En un modelo de [Infraestructura como Servicio](/es/infrastructure-as-a-service/),
```

2023-04-13 16:50 UTC, electrocucaracha approved these changes

2023-04-13 17:23 UTC, ramrodo approved these changes
/lgtm

2023-04-13 17:24 UTC, merged