Dev bn event streaming
cncf/glossary pull request #1940
Opened 2023-04-11 16:55 UTC by ai-naymul

### Describe your changes
Localize the content/bn/event-streaming.md file

### Related issue number or link (ex: `resolves #issue-number`)
Tracking no: #410 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-16 06:59 UTC, mitul3737 commented
@ai-naymul  , you need to mention your name and mail at the description.

2023-04-16 07:11 UTC, mitul3737 requested changes

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +title: ঘটনা প্রবাহ
```suggestion
title: ঘটনা প্রবাহ ( Event Streaming )
```

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +ইয়াহু! ফাইন্যান্স একটি [API](/bn/application-programming-interface/) প্রদান করে যা NASDAQ থেকে টেনে নেয় এবং তাদের অ্যাপ্লিকেশন থেকে তথ্য (বা ঘটনা) পাঠায় (বা প্রবাহ) যেকোন অ্যাপ্লিকেশনে যা সদস্যতা
```suggestion
ফাইন্যান্স একটি [API](/bn/application-programming-interface/) প্রদান করে যা NASDAQ থেকে টেনে নেয় এবং তাদের অ্যাপ্লিকেশন থেকে তথ্য (বা ঘটনা) পাঠায় (বা প্রবাহ) যেকোন অ্যাপ্লিকেশনে যার সদস্যতা নেয়।
```

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +ঐতিহ্যগতভাবে, ইয়াহু! ফাইন্যান্স একক TCP অনুরোধ ব্যবহার করবে।
```suggestion
ঐতিহ্যগতভাবে, ফাইন্যান্স একক TCP অনুরোধ ব্যবহার করবে।
```

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +তথ্য প্রকৃপক্ষে যত বর্তমান-সময়ে উঠে, এই জাতীয় সমাধানকে স্কেল করা অকার্যকর হয়ে পড়ে।
Kindly make a clear sentence instead of this sentence ""তথ্য প্রকৃপক্ষে যত বর্তমান-সময়ে উঠে, এই জাতীয় সমাধানকে স্কেল করা অকার্যকর হয়ে পড়ে।"

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +একবার সংযোগ খোলা এবং ঘটনাগুলোকে প্রবাহিত করার অনুমতি দেওয়া বর্তমান-সময়ে সংগ্রহের জন্য আদর্শ।
Update this sentence as well "একবার সংযোগ খোলা এবং ঘটনাগুলোকে প্রবাহিত করার অনুমতি দেওয়া বর্তমান-সময়ে সংগ্রহের জন্য আদর্শ।"

2023-04-16 07:11 UTC, mitul3737 commented on content/bn/event-streaming.md
> +তথ্যের কি হবে তা নিয়ে উদ্বিগ্ন নয়।
Kindly make this sentence more clearer "তথ্যের কি হবে তা নিয়ে উদ্বিগ্ন নয়।"

2023-04-16 13:38 UTC, ai-naymul commented
> @ai-naymul , you need to mention your name and mail at the description.

I am facing the comment 
```
You asked to amend the most recent commit, but doing so would make
it empty. You can repeat your command with --allow-empty, or you can
remove the commit entirely with "git reset HEAD^".
On branch dev-bn-event-streaming
Your branch is up to date with 'origin/dev-bn-event-streaming'.

No changes
```  

while I am trying to amend the commit, could you please help me on this?
Thank you :)

2023-04-16 14:11 UTC, mitul3737 commented
> > @ai-naymul , you need to mention your name and mail at the description.
> 
> I am facing the comment
> 
> ```
> You asked to amend the most recent commit, but doing so would make
> it empty. You can repeat your command with --allow-empty, or you can
> remove the commit entirely with "git reset HEAD^".
> On branch dev-bn-event-streaming
> Your branch is up to date with 'origin/dev-bn-event-streaming'.
> 
> No changes
> ```
> 
> while I am trying to amend the commit, could you please help me on this? Thank you :)

Kindly mention your name and email here.

2023-04-16 14:17 UTC, ai-naymul commented
> > > @ai-naymul , you need to mention your name and mail at the description.
> > 
> > 
> > I am facing the comment
> > ```
> > You asked to amend the most recent commit, but doing so would make
> > it empty. You can repeat your command with --allow-empty, or you can
> > remove the commit entirely with "git reset HEAD^".
> > On branch dev-bn-event-streaming
> > Your branch is up to date with 'origin/dev-bn-event-streaming'.
> > 
> > No changes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > while I am trying to amend the commit, could you please help me on this? Thank you :)
> 
> Kindly mention your name and email here.

Name: Naymul Islam 
Email: naymul504@gmail.com

2023-05-19 12:24 UTC, mitul3737 approved these changes

2023-05-19 12:25 UTC, merged