[ES] content/es/security-chaos-engineering.md
cncf/glossary pull request #1941
Opened 2023-04-11 17:22 UTC by marianogg9

### Describe your changes
- added `content/es/security-chaos-engineering.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1768 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-11 21:41 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +category: concepto
```suggestion
category: Concepto
```

2023-04-11 21:42 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +Seguridad en ingeniería del caos, o SCE en Inglés, es una disciplina basada en la [ingeniería del caos](/es/chaos-engineering/).
```suggestion
Seguridad en ingeniería del caos, o SCE en Inglés, es una disciplina basada en la [Ingeniería del Caos](/es/chaos-engineering/).
```

2023-04-11 21:42 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +title: Seguridad en Ingeniería del caos
```suggestion
title: Seguridad en Ingeniería del Caos
```

2023-04-11 21:44 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +para aportar a la confianza del sistema en relación a su capacidad de soportar condiciones maliciosas o turbulentas.
```suggestion
para aportar confianza en la capacidad del sistema de soportar condiciones maliciosas o turbulentas.
```

2023-04-11 21:53 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +La mayor prioridad de los [ingenieros de site reliability](/es/site-reliability-engineering/) (o SRE en Inglés) e ingenieros de seguridad informática es
Podemos manejar el término como `ingenieros de confiabilidad del sitio` tal y como se manejó en [la localización del término SRE](https://github.com/cncf/glossary/blob/dev-es/content/es/site-reliability-engineering.md?plain=1#L12).

```suggestion
La mayor prioridad de los [ingenieros de confiabilidad del sitio](/es/site-reliability-engineering/) (o SRE en Inglés) e ingenieros de seguridad informática es
```

2023-04-11 21:54 UTC, ramrodo commented on content/es/security-chaos-engineering.md
> +La seguridad en ingeniería del caos está construida alrededor de la [observabilidad](/es/observability/) y las prácticas de resiliencia informática.
```suggestion
La Seguridad en Ingeniería del Caos está construida alrededor de la [observabilidad](/es/observability/) y las prácticas de resiliencia informática.
```

2023-04-11 21:55 UTC, ramrodo requested changes
Genial. Solo algunas sugerencias propuestas.

2023-04-13 17:25 UTC, ramrodo approved these changes
/lgtm

2023-04-22 14:27 UTC, krol3 approved these changes
lgtm

2023-04-22 14:28 UTC, merged