[fr] Localize Observability
cncf/glossary pull request #1965
Opened 2023-04-16 10:10 UTC by sestegra

### Describe your changes

This PR localizes Observability to French

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #1961 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-22 13:01 UTC, huats requested changes

2023-04-22 13:01 UTC, huats commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
A mon sens tu dois avoir une concordance entre "niveau supérieur" et "métiers". J'aurai tendance à mettre du pluriel

2023-04-22 13:58 UTC, sestegra commented on content/fr/observability.md
> +title: Observability
Oups, corrigé

2023-04-22 14:03 UTC, sestegra commented on content/fr/observability.md
> +Elle permet aux utilisateurs de comprendre l'état d'un système à partir de ses sorties externes et de prendre des mesures (correctives).
En passant au singulier "sa sortie" ou "cette sortie", je trouve que "sa sortie" représente mieux celle du système.

2023-04-22 14:05 UTC, sestegra commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
Ok pour changer

2023-04-22 14:09 UTC, sestegra commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
Ici, ce sont les "signaux métiers". 
Le passage en anglais est "low-level signals such as CPU time, memory, disk space, and higher-level and business signals".

2023-04-22 14:15 UTC, sestegra commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
Il est possible aussi de répéter "signaux", "des signaux de niveau supérieur et des signaux métiers" ou mettre une virgule avant "des signaux de niveau supérieur, et métiers".

2023-05-03 03:12 UTC, fydrah approved these changes

2023-05-03 03:15 UTC, fydrah requested changes
~Si on regarde le format EN, il y a la séparation en 3 sections. Il faudrait mettre la taduction sous le même format~

edit: en effet dev-fr a l'ancienne version encore, donc la traduction est valide.

2023-05-03 03:18 UTC, fydrah approved these changes

2023-05-06 16:00 UTC, Krast76 approved these changes

2023-05-10 16:16 UTC, sestegra commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
Mettre "des signaux de niveau supérieur et des signaux métiers"

2023-05-14 14:18 UTC, sestegra commented on content/fr/observability.md
> +Les systèmes informatiques sont mesurés en observant des signaux de bas niveau tels que le temps CPU, la mémoire, l'espace disque, et des signaux de niveau supérieur et métiers, notamment les temps d
Modification effectuée

2023-06-14 14:44 UTC, huats approved these changes
LGTM ! Thanks !

2023-06-14 14:59 UTC, merged