Es virtual machine
cncf/glossary pull request #1980
Opened 2023-04-23 15:09 UTC by marianogg9

### Describe your changes
- added `es/content/virtual-machine.md`.
- fixed `máquinas virtuales` reference link in `bare-metal-machine.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1784 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-04-25 16:04 UTC, electrocucaracha requested changes

2023-04-25 16:04 UTC, electrocucaracha commented on content/es/virtual-machine.md
> +a crear y eliminar máquinas virtuales sin impactar el hardware de base.
```suggestion
al crear y eliminar máquinas virtuales sin impactar el hardware de base.
```

2023-04-25 16:04 UTC, electrocucaracha commented on content/es/virtual-machine.md
> +su disponibilidad está directamente supeditada a ese hardware.
```suggestion
su disponibilidad está directamente ligada a ese hardware.
```

2023-04-25 17:52 UTC, marianogg9 commented on content/es/virtual-machine.md
> +a crear y eliminar máquinas virtuales sin impactar el hardware de base.
@electrocucaracha la frase es: "Esta separación facilita a organizaciones y proveedores de infraestructura a crear y eliminar máquinas virtuales sin impactar el hardware de base." 

Con la sugerencia quedaría: "Esta separación facilita a organizaciones y proveedores de infraestructura al crear y eliminar máquinas virtuales sin impactar el hardware de base."

Me parece que no va un "al" alli, puede ser?

2023-04-25 17:53 UTC, marianogg9 commented on content/es/virtual-machine.md
> +a crear y eliminar máquinas virtuales sin impactar el hardware de base.
Quizás podría ser algo como "Esta separación facilita el trabajo a organizaciones y proveedores de infraestructura al crear y eliminar maquinas virtuales sin impactar el hardware de base"?

2023-04-25 17:54 UTC, marianogg9 commented on content/es/virtual-machine.md
> +su disponibilidad está directamente supeditada a ese hardware.
Nota: La pensé más para evitar repetir **ligado/a**.

2023-04-25 18:00 UTC, electrocucaracha commented on content/es/virtual-machine.md
> +su disponibilidad está directamente supeditada a ese hardware.
Tienes razón quizá utilizar un sinónimo como `enlazada`, `atada` o `vinculada`

2023-04-25 18:01 UTC, marianogg9 commented on content/es/virtual-machine.md
> +su disponibilidad está directamente supeditada a ese hardware.
Sale con `vinculada` :D

2023-04-26 20:30 UTC, electrocucaracha commented on content/es/virtual-machine.md
> +a crear y eliminar máquinas virtuales sin impactar el hardware de base.
Tienes razón, `crear` y `eliminar` son beneficios obtenidos por la separación de dependencias. Dejémoslo tal como lo propones

2023-04-27 15:57 UTC, ramrodo approved these changes

2023-04-27 15:57 UTC, merged