[ES] added content/es/service-discovery
cncf/glossary pull request #1991
Opened 2023-04-29 08:06 UTC by marianogg9

### Describe your changes
- added `content/es/service-discovery`.

### Related issue number or link (ex: `resolves #issue-number`)
- #1788 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-02 02:24 UTC, ramrodo commented on content/es/service-discovery.md
> +title: Descubrimiento de Servicios
```suggestion
title: Descubrimiento de Servicio
```
En la traducción original dice `Service Discovery` en singular. Podemos manejarlo igual en todas las referencias de la localización.

2023-05-02 02:26 UTC, ramrodo commented on content/es/service-discovery.md
> +El descubrimiento de servicios mantiene una lista de aplicaciones en una red para que puedan encontrarse unas a otras cuando sea necesario.
```suggestion
El descubrimiento de servicio mantiene una lista de aplicaciones en una red para que puedan encontrarse unas a otras cuando sea necesario.
```

Mismo comentario que el anterior

2023-05-02 02:27 UTC, ramrodo commented on content/es/service-discovery.md
> +Los motores de descubrimiento de servicios son herramientas similares a las bases de datos que almacenan información referente a qué servicios existen y cómo localizarlos.
```suggestion
Los motores de descubrimiento de servicio son herramientas similares a las bases de datos que almacenan información referente a qué servicios existen y cómo localizarlos.
```

Mismo comentario que el anterior

2023-05-02 02:27 UTC, ramrodo requested changes
Algunas observaciones sobre el singular de la palabra **Servicios**

2023-05-15 22:54 UTC, 92nqb approved these changes
LGTM

2023-05-16 02:06 UTC, ramrodo approved these changes
Thanks! LGTM

2023-05-16 02:06 UTC, merged