[ES] added content/es/service-proxy
cncf/glossary pull request #1992
Opened 2023-04-29 08:25 UTC by marianogg9

### Describe your changes
- added `content/es/service-proxy.md`

### Related issue number or link (ex: `resolves #issue-number`)
- #1772 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-02 02:31 UTC, ramrodo commented on content/es/service-proxy.md
> +title: Intermediario de Servicios
```suggestion
title: Intermediario de Servicio
```

Comentario similar al PR https://github.com/cncf/glossary/pull/1991, la traducción original dice `Service` y no `Services`. Creo que deberíamos manejar el singular de la palabra.

2023-05-02 02:31 UTC, ramrodo commented on content/es/service-proxy.md
> +Un intermediario de servicios intercepta tráfico desde o hacia un [servicio](/service/) determinado,
```suggestion
Un intermediario de servicio intercepta tráfico desde o hacia un [servicio](/service/) determinado,
```

2023-05-02 02:32 UTC, ramrodo commented on content/es/service-proxy.md
> +Un intermediario de servicios nos permite separar esta funcionalidad.
```suggestion
Un intermediario de servicio nos permite separar esta funcionalidad.
```

2023-05-02 02:33 UTC, ramrodo commented on content/es/service-proxy.md
> +En reemplazo, ahora será parte de la capa de plataforma (donde la aplicación se ejecuta)
```suggestion
En cambio, ahora será parte de la capa de plataforma (donde la aplicación se ejecuta)
```

2023-05-02 02:35 UTC, ramrodo requested changes
Un par de comentarios relacionados al singular de la palabra **Servicios** y una sugerencia sobre la traducción de _Instead_.

2023-05-02 02:36 UTC, ramrodo commented on content/es/service-proxy.md
> +se encargan de la encriptación de conexiones y acumulan contenido (reduciendo el consumo de recursos).
```suggestion
se encargan del cifrado de conexiones y acumulan contenido (reduciendo el consumo de recursos).
```

2023-05-15 22:58 UTC, 92nqb requested changes
Una pequeña sugerencia. 
Gracias por la contribución :)

2023-05-15 22:58 UTC, 92nqb commented on content/es/service-proxy.md
> +aplica algún tipo de lógica predefinida y luego envía ese tráfico hacia otro servicio.
```suggestion
aplicando algún tipo de lógica predefinida y luego envía ese tráfico hacia otro servicio.
```

2023-06-12 18:34 UTC, ramrodo commented on content/es/service-proxy.md
> +aplica algún tipo de lógica predefinida y luego envía ese tráfico hacia otro servicio.
Hola @marianogg9, ¿podrías aplicar ésta sugerencia por favor? :)

2023-06-20 17:39 UTC, ramrodo approved these changes
lgtm

2023-06-26 13:15 UTC, ramrodo commented
/cc @92nqb @electrocucaracha @krol3

2023-06-27 01:44 UTC, electrocucaracha commented on content/es/service-proxy.md
> +title: Intermediario de Servicio
Personalmente, nunca he escuchado esa traducción, no se si seria mejor no traducirlo
```suggestion
title: Servicio de Proxy
```
* [Referencia Wikipedia](https://es.wikipedia.org/wiki/Servidor_proxy)

2023-06-27 01:44 UTC, electrocucaracha commented on content/es/service-proxy.md
> +Un intermediario de servicio intercepta tráfico desde o hacia un [servicio](/service/) determinado,
Me parece que ya se hizo la traducción del servicio
```suggestion
Un intermediario de servicio intercepta tráfico desde o hacia un [servicio](/es/service/) determinado,
```

2023-06-27 01:44 UTC, electrocucaracha commented on content/es/service-proxy.md
> +Los intermediarios colectan información crítica, manejan el enrutamiento (distribuyendo el tráfico equitativamente entre servicios o redirigiendo el mismo si algún servicio se rompiera),
```suggestion
Los intermediarios recolectan información crítica, manejan el enrutamiento (distribuyendo el tráfico equitativamente entre servicios o redirigiendo el mismo si algún servicio se rompiera),
```

2023-06-27 16:02 UTC, electrocucaracha requested changes

2023-06-27 16:02 UTC, electrocucaracha commented on content/es/service-proxy.md
> +Un intermediario de servicio intercepta tráfico desde o hacia un [servicio](/es/service/) determinado,
```suggestion
Un servicio de Proxy intercepta tráfico desde o hacia un [servicio](/es/service/) determinado,
```

2023-06-27 16:02 UTC, electrocucaracha commented on content/es/service-proxy.md
> +Un intermediario de servicio nos permite separar esta funcionalidad.
```suggestion
Un servicio de Proxy nos permite separar esta funcionalidad.
```

2023-06-27 16:02 UTC, electrocucaracha commented on content/es/service-proxy.md
> +Los intermediarios recolectan información crítica, manejan el enrutamiento (distribuyendo el tráfico equitativamente entre servicios o redirigiendo el mismo si algún servicio se rompiera),
```suggestion
Los servicios de Proxy recolectan información crítica, manejan el enrutamiento (distribuyendo el tráfico equitativamente entre servicios o redirigiendo el mismo si algún servicio se rompiera),
```

2023-07-01 23:52 UTC, electrocucaracha approved these changes

2023-07-01 23:55 UTC, merged