[fr] Localize term DevOps
cncf/glossary pull request #2004
Opened 2023-05-03 04:39 UTC by fydrah

### Describe your changes

Add `DevOps` french translation.

### Related issue number or link (ex: `resolves #issue-number`)

resolves #1264 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-06 16:12 UTC, Krast76 requested changes

2023-05-06 16:12 UTC, Krast76 commented on content/fr/devops.md
> +Le DevOps fait appel à un groupe d'ingénieurs travaillant sur des petits composants (en opposition à un fonctionnalité complète), permettant ainsi de réduire les actions de passations – une source d'
à une fonctionnalité*

2023-05-06 16:12 UTC, Krast76 commented on content/fr/devops.md
> +le travail était généralement fragmenté entre en plusieurs équipes.
entre plusieurs équipes. (le "en" et en trop là)

2023-05-06 16:12 UTC, Krast76 commented on content/fr/devops.md
> +Une fois le code livré en production, ce dernier passé entre les mains de tellement de différents développeurs, et ayant attendu dans tellement de files d'attente, il en devenait alors compliqué de t
J'aurais plutôt mis : 
" de différents développeurs, ayant attendu dans..."

2023-05-06 16:12 UTC, Krast76 commented on content/fr/devops.md
> +la satisfaction des employés de part le gain d'autonomie et de responsabilité.
"de sa mise en production augmentant la satisfaction... grâce au gain d'autonomie et de responsabilité"

2023-07-17 09:04 UTC, sestegra requested changes

2023-07-17 09:04 UTC, sestegra commented on content/fr/devops.md
> +la qualité du code car les équipes sont également responsable de sa mise en production et augmentant
Je pense qu'il manque une virgule avant "car".
Ensuite, "responsable" doit s'accorder aux équipes, donc "responsables".

2023-07-19 16:13 UTC, sestegra approved these changes
LGTM 🚀

2023-07-19 16:13 UTC, Krast76 approved these changes

2023-07-19 16:14 UTC, merged