Settings and initial contents for Traditional Chinese localization
cncf/glossary pull request #2006
Opened 2023-05-04 09:40 UTC by ydFu

This PR is to initiate Traditional Chinese localization based on

- Issue to https://github.com/cncf/glossary/issues/1987
- https://github.com/cncf/glossary/blob/main/LOCALIZATION.md guide
Base and target branch of this PR is `dev-tw` which is development branch for Traditional Chinese  localization.

This PR includes

- `[languages.zh-tw]` section in `config.toml`
- content/**zh-tw**/ directory
- i18n/zh-tw.toml
- Some translated documents
  - Main page
    - content/zh-tw/_index.md
  - Terms
     - "Cloud Native Technology": content/ko/cloud_native_tech.md
  - Others
     - contribute: content/zh-tw/contribute/_index.md
     - style-guide: content/zh-tw/style-guide/_index.md
     - contributor-ladder: content/zh-tw/contributor-ladder/_index.md

Since Traditional Chinese localization team owns content `/zh-tw/*` only,
this PR will require approvals from upstream owners (maintainers).

2023-05-04 09:45 UTC, ydFu commented
![image](https://user-images.githubusercontent.com/64598482/236169879-45fba3eb-2300-4abf-a34f-0c04fec4be1d.png)

2023-05-04 09:45 UTC, seokho-son commented
Hi @ydFu 

Commit sha: [57cd3d0](https://github.com/cncf/glossary/pull/2006/commits/57cd3d0986469b61b45a6a3e61c1f5931e981e79), Author: ydFu, Committer: ydFu; The sign-off is missing.


--> you did! :) Thanks

2023-05-04 10:18 UTC, ydFu commented
Invite the `zh-tw` team for review and if they like it, they can leave the "LGTM" label.

- [A] Phil Huang (@pichuang)
- Cody Chen (@cdxvy30)
- Kent Lin (@kentlin520)
- Eagle Tseng (@tsengeagle)

2023-05-04 10:51 UTC, pichuang commented
LGTM. Thank you for @ydFu 's effort and contribution. 🥇

2023-05-04 12:04 UTC, cdxvy30 commented
![Screen Shot 2023-05-04 at 7 49 15 PM](https://user-images.githubusercontent.com/109569898/236196297-bf3a6659-b46f-4acc-8829-3c311968dc82.png)

Just noticed that here might be a small mistake in Netlify preview. Not sure if it's a bug. Others LGTM. Thanks @ydFu !

2023-05-04 12:52 UTC, ydFu commented
> ![Screen Shot 2023-05-04 at 7 49 15 PM](https://user-images.githubusercontent.com/109569898/236196297-bf3a6659-b46f-4acc-8829-3c311968dc82.png)
> 
> Just noticed that here might be a small mistake in Netlify preview. Not sure if it's a bug. Others LGTM. Thanks @ydFu !

thanks for feedback,now is working

![image](https://user-images.githubusercontent.com/64598482/236209827-16cd5762-af5d-47ed-bd98-6975802a0af2.png)

2023-05-04 13:21 UTC, hwchiu requested changes

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/cloud-native-tech.md
> +它們從頭開始設計，以利用雲計算和容器，服務網格、微服務和不可變基礎架構的能力。
這句話有種英翻中但是卻沒有採用慣用文法的感覺

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/style-guide/_index.md
> +偶爾，我們會很快審查術語；在其他情況下，可能需要一些時間 — 我們感謝你的耐心。
這邊的翻譯斷點滿怪的，不太順

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/contributor-ladder/_index.md
> +成為審核者的候選人應具有證明提交高質量 PR 並幫助他人將其 PR 置於可合併狀態的卓越記錄。
質量應該不是繁體中文慣用語

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/cloud-native-tech.md
> +雖然每種技術都解決了非常具體的問題，但作為一組，雲原生技術使鬆散耦合的系統具有彈性、可管理和可觀察性。
`但作為一組，雲原生技術使鬆散耦合的系統具有彈性` 斷句有點奇怪，唸起來不太通順，到底是一組什麼

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/contribute/_index.md
> +專業知識是必需的，因為用簡單的話語解釋複雜的概念 _真的_ 很難。而且，儘管易於理解的結果可能看起來很簡單，但達到所需的簡單性需要雲原生專家之間的努力和協作。
_真的_ 這個是真的斜體字還是會用 markdown 語法處理？

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/style-guide/_index.md
> +#### 質量是最重要的
質量應該非繁體中文慣用語

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/contributor-ladder/_index.md
> +維護者應該有成功批准並提交高質量的 PR 的紀錄。
質量應該非繁體中文慣用語

2023-05-04 13:21 UTC, hwchiu commented on content/zh-tw/contributor-ladder/_index.md
> +如果和當貢獻者的承諾水平改變，貢獻者可以考慮退回(降低貢獻者階層)或退休狀態(完全退出專案)。
水平應該非繁體中文慣用語

2023-05-04 13:43 UTC, hwchiu commented on content/zh-tw/_index.md
> +詞彙表是由 CNCF 商業價值小組（BVS, Business Value Subcommittee）領導的項目。
一些想法與改進

雲原生詞彙表旨在讓技術人員與商業人員能夠用一種更簡易的方式理解複雜的雲原生技術領域
為了實現這一目標，我們透過使用簡單的描述方式，不帶有特定領域的專業術語並且基於任何技術的從業人員都可以理解的範例
本詞彙表是由 CNCF 商業價值小組 (BVS, Business Value Subcommittee) 所管理的專案

2023-05-04 13:43 UTC, hwchiu commented on content/zh-tw/_index.md
> +詞彙表提供了一個供所有參與者使用的供應商中立平台，以組織雲原生技術的共享詞彙。歡迎所有遵守該項目目的和章程的參與者做出貢獻。
歡迎所有遵守該項目目的和章程的參與者做出貢獻。 
->
歡迎所有遵守該專案目的與章程的參與者作出貢獻

2023-05-04 13:43 UTC, hwchiu commented on content/zh-tw/cloud-native-tech.md
> +挑戰包括難以創建可擴展、容錯、自我修復的應用程式，以及低效的資源利用率，等等。
一些粗略想法

查看 [CNCF Cloud Native Landscape](https://landscape.cncf.io/)這份文件您將會發現雲原生技術棧實際上
已經深根至各式各樣領域並且透過蓬勃發展的技術來面對挑戰。
從高維度來看，雲原生技術棧根本上解決了傳統 IT 維運上的困境，包括難以創建可擴展、容錯、自我修復的應用程式，以及低效的資源利用率，等等。

2023-05-08 06:46 UTC, ydFu commented on content/zh-tw/contributor-ladder/_index.md
> +成為審核者的候選人應具有證明提交高質量 PR 並幫助他人將其 PR 置於可合併狀態的卓越記錄。
原文:
```
Approver candidates should have a proven track record of submitting high-quality PRs and helping others get their PRs in a mergeable state. 
```

調整內容如下:
```suggestion
批准者候選人應該有提交高品質 PR 和幫助其他人使他們的 PR 處於可合併狀態的良好記錄。
```
將"quality"從"質量"改成常見繁中用語"品質"

2023-05-08 06:51 UTC, ydFu commented on content/zh-tw/contribute/_index.md
> +您可以參與該專案的方式取決於您的雲原生專業水平。
原文:
```
How you can participate in this project depends on your level of cloud native expertise. 
```

```suggestion
您如何參與此專案取決於您的雲原生專業知識水準。
```
將"level"從"水平"改成常見繁中用語"水準"

2023-05-08 06:56 UTC, ydFu commented on content/zh-tw/style-guide/_index.md
> +#### 質量是最重要的
原文:
```
#### Quality is paramount
```
調整內如下
```suggestion
#### 品質至上
```
將"quality"從"質量"改成常見繁中用語"品質"

2023-05-08 07:03 UTC, ydFu commented on content/zh-tw/contributor-ladder/_index.md
> +維護者應該有成功批准並提交高質量的 PR 的紀錄。
原文:
```
Maintainers should have a proven track record of being successful approvers and submitting high-quality PRs. 
```

調整內容如下:
```suggestion
維護者應該有成為成功批准者的良好記錄並提交高品質的 PR 
```
將"quality"從"質量"改成常見繁中用語"品質"

2023-05-08 08:37 UTC, ydFu commented on content/zh-tw/cloud-native-tech.md
> +它們從頭開始設計，以利用雲計算和容器，服務網格、微服務和不可變基礎架構的能力。
依照 #glossary-localization-traditional-chinese 討論決議內容，

1. 翻譯風格未定案()
目前翻譯風格尚未有規範，有區分"直譯"與"意譯"，
其中意譯又有三大風格:
「信」（faithfulness）指意義不悖原文，即是譯文要準確，不偏離，不遺漏，也不要隨意增減意思；
「達」（expressiveness）指不拘泥於原文形式，譯文通順明白；
「雅」（elegance）則指譯文時選用的詞語要得體，追求文章本身的古雅，簡明優雅。

本次 PR 以"直譯"優先行!
仍謝謝的翻譯審閱與技術意見回饋，後續仍可以討論與修改文檔。

2023-05-08 08:37 UTC, ydFu commented on content/zh-tw/cloud-native-tech.md
> +挑戰包括難以創建可擴展、容錯、自我修復的應用程式，以及低效的資源利用率，等等。
依照 #glossary-localization-traditional-chinese 討論決議內容，

1. 翻譯風格未定案()
目前翻譯風格尚未有規範，有區分"直譯"與"意譯"，
其中意譯又有三大風格:
「信」（faithfulness）指意義不悖原文，即是譯文要準確，不偏離，不遺漏，也不要隨意增減意思；
「達」（expressiveness）指不拘泥於原文形式，譯文通順明白；
「雅」（elegance）則指譯文時選用的詞語要得體，追求文章本身的古雅，簡明優雅。

本次 PR 以"直譯"優先行!
仍謝謝的翻譯審閱與技術意見回饋，後續仍可以討論與修改文檔。

2023-05-08 08:38 UTC, ydFu commented on content/zh-tw/cloud-native-tech.md
> +雖然每種技術都解決了非常具體的問題，但作為一組，雲原生技術使鬆散耦合的系統具有彈性、可管理和可觀察性。
依照 #glossary-localization-traditional-chinese 討論決議內容，

翻譯風格未定案
目前翻譯風格尚未有規範，有區分"直譯"與"意譯"，
其中意譯又有三大風格:
「信」（faithfulness）指意義不悖原文，即是譯文要準確，不偏離，不遺漏，也不要隨意增減意思；
「達」（expressiveness）指不拘泥於原文形式，譯文通順明白；
「雅」（elegance）則指譯文時選用的詞語要得體，追求文章本身的古雅，簡明優雅。

本次 PR 以"直譯"優先行!
仍謝謝的翻譯審閱與技術意見回饋，後續仍可以討論與修改文檔。

2023-05-08 08:38 UTC, ydFu commented on content/zh-tw/contribute/_index.md
> +專業知識是必需的，因為用簡單的話語解釋複雜的概念 _真的_ 很難。而且，儘管易於理解的結果可能看起來很簡單，但達到所需的簡單性需要雲原生專家之間的努力和協作。
依照 #glossary-localization-traditional-chinese 討論決議內容，

翻譯風格未定案
目前翻譯風格尚未有規範，有區分"直譯"與"意譯"，
其中意譯又有三大風格:
「信」（faithfulness）指意義不悖原文，即是譯文要準確，不偏離，不遺漏，也不要隨意增減意思；
「達」（expressiveness）指不拘泥於原文形式，譯文通順明白；
「雅」（elegance）則指譯文時選用的詞語要得體，追求文章本身的古雅，簡明優雅。

本次 PR 以"直譯"優先行!
仍謝謝的翻譯審閱與技術意見回饋，後續仍可以討論與修改文檔。

2023-05-09 16:31 UTC, hwchiu commented
LGTM, Thanks

2023-05-10 09:52 UTC, tsengeagle commented
LGTM, thanks

2023-05-11 08:01 UTC, seokho-son reviewed
Thank you all !! :)

LGTM!

2023-05-11 08:04 UTC, merged