[ES] Localize stateless app
cncf/glossary pull request #2015
Opened 2023-05-09 14:49 UTC by jossemarGT

### Describe your changes

Localize "Stateless app" into Spanish

### Related issue number or link (ex: `resolves #issue-number`)

#1777 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-10 18:57 UTC, ramrodo commented on content/es/stateless-apps.md
> +Cada interacción del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
```suggestion
Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
```

2023-05-10 18:59 UTC, ramrodo commented on content/es/stateless-apps.md
> +En caso se presente un problema, usted podrá reiniciar la aplicación,
Últimamente hemos estado manejando primera persona _tú_, en vez de _usted_:

```suggestion
En caso de que se presente un problema, tú podrás reiniciar la aplicación,
```

2023-05-10 19:01 UTC, ramrodo commented on content/es/stateless-apps.md
> +dado que usted no necesitará preocuparse de guardar los datos en volúmenes de almacenamiento persistente ó
```suggestion
dado que no necesitarás preocuparte de guardar los datos en volúmenes de almacenamiento persistente ó
```

2023-05-10 19:03 UTC, ramrodo requested changes
Excelente @jossemarGT! Solo algunas recomendaciones

2023-05-12 19:26 UTC, jossemarGT commented on content/es/stateless-apps.md
> +status: Feedback Appreciated
Una vez tenga su visto bueno con este cambio, ¿les parece bien si cambio esto a `Completed`?

2023-05-15 23:06 UTC, 92nqb commented on content/es/stateless-apps.md
> +status: Feedback Appreciated
Hola @jossemarGT, en primer lugar gracias por la contribución :)

El `status` de los términos depende de la definición original hecha en inglés. Puedes encontrar mas información aqui https://glossary.cncf.io/style-guide/#status

Por lo tanto este cambio no depende de nosotros

2023-05-16 02:10 UTC, ramrodo commented on content/es/stateless-apps.md
> +status: Feedback Appreciated
Así es, hasta que el término original en Inglés cambié el `status`, nosotros igual actualizaríamos ésta línea en ese momento @jossemarGT. Por el momento, se quedará como _Feedback Appreciated_ en nuestra rama de **dev-es**.

2023-05-16 13:41 UTC, krol3 requested changes
@jossemarGT  unas pequeñas sugerencias en el texto. Gracias !!

2023-05-16 13:41 UTC, krol3 commented on content/es/stateless-apps.md
> +Una aplicación sin estado ó independiente al estado, es la que no guarda ningún dato de sesión del cliente (estado) en el servidor donde la aplicación vive.
```suggestion
Una aplicación sin estado o independiente al estado es la que no guarda ningún dato de sesión del cliente (estado) en el servidor donde la aplicación vive.
```

2023-05-16 13:41 UTC, krol3 commented on content/es/stateless-apps.md
> +Aún así, la mayoría de las aplicaciones que se utilizan hoy en día son al menos parcialmente [dependientes al estado](/stateful-apps/),
```suggestion
Aun así, la mayoría de las aplicaciones que se utilizan hoy en día son al menos parcialmente [aplicativos con estado](/stateful-apps/),
```

2023-05-16 14:45 UTC, jossemarGT commented on content/es/stateless-apps.md
> +status: Feedback Appreciated
Ok, entendido. Yo había interpretado ese campo de la manera incorrecta.

2023-05-17 22:33 UTC, ramrodo commented on content/es/stateless-apps.md
> +Aun así, la mayoría de las aplicaciones que se utilizan hoy en día son al menos parcialmente [aplicativos con estado](/stateful-apps/),
Una disculpa @jossemarGT, justo hace un par de días se añadió la definición en Español de _stateful-apps_ en https://github.com/cncf/glossary/pull/2010

```suggestion
Aun así, la mayoría de las aplicaciones que se utilizan hoy en día son al menos parcialmente [aplicativos con estado](/es/stateful-apps/),
```

2023-05-17 22:33 UTC, ramrodo requested changes
Actualizar la referencia al concepto recién añadido

2023-05-18 01:01 UTC, jossemarGT commented on content/es/stateless-apps.md
> +Aun así, la mayoría de las aplicaciones que se utilizan hoy en día son al menos parcialmente [aplicativos con estado](/stateful-apps/),
Listo.

2023-05-18 04:20 UTC, electrocucaracha commented on content/es/stateless-apps.md
> +Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
Me parece que en la versión en inglés cuenta con más información
```suggestion
Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no dependen de los datos de la sesión anterior y
brinda funcionalidad para usar servicios de impresión, CDN (Red de distribución de contenido) o los servidores web
para procesar cada solicitud a corto plazo.
```

2023-06-12 18:31 UTC, ramrodo commented on content/es/stateless-apps.md
> +Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
Hola @jossemarGT. Es verdad, en la versión en inglés están éstas otras dos líneas que Víc está sugeriendo y creo que fueron omitidas por error, ¿podrías aplicarlas por favor?

2023-06-12 18:31 UTC, ramrodo requested changes
Faltan algunas líneas por traducir

2023-06-12 18:38 UTC, jossemarGT commented on content/es/stateless-apps.md
> +Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
Enterado. Esperaba poder proponer el cambio en el texto original primero (`[EN]`), pero me enfocaré en los cambios sugeridos en cuanto antes.

2023-06-13 06:17 UTC, ramrodo commented on content/es/stateless-apps.md
> +Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
Muchas gracias Jossemar :)

2023-06-13 15:50 UTC, krol3 commented on content/es/stateless-apps.md
> +brinda funcionalidad para usar servicios de impresión, CDN (Red de distribución de contenido) o los servidores web
```suggestion
brinda funcionalidad para usar servicios de impresión, red de distribución de contenido - CDN (Content delivery network) o los servidores web
```

2023-06-13 15:53 UTC, electrocucaracha commented on content/es/stateless-apps.md
> +brinda funcionalidad para usar servicios de impresión, CDN (Red de distribución de contenido) o los servidores web
```suggestion
brinda funcionalidad para usar servicios de impresión, la Red de Distribución de Contenido (CDN, Content Delivery Network) o los servidores web
```

2023-06-13 16:02 UTC, jossemarGT commented on content/es/stateless-apps.md
> +Cada sesión del usuario se maneja como si fuese la primera vez y las respuestas no son dependientes de datos de la sesión anterior.
Procedí de la siguiente manera:

- Modifiqué el texto en base a las recomendaciones de @electrocucaracha 
- Agregué el término CDN al archivo `content/es/.wordlist.txt`

2023-06-13 16:03 UTC, jossemarGT commented on content/es/stateless-apps.md
> +brinda funcionalidad para usar servicios de impresión, CDN (Red de distribución de contenido) o los servidores web
Procedí a agregar los cambios sugeridos, sin embargo no parece que necesitemos el uso de los artículos dentro del contexto de la oración completa.

2023-06-13 16:15 UTC, ramrodo commented on content/es/stateless-apps.md
> +brinda funcionalidad para usar servicios de impresión, CDN (Red de distribución de contenido) o los servidores web
A favor de que no se necesitan agregar artículos o preposiciones a `..., Red de Distribución de Contenido (CDN, Content Delivery Network)...`

2023-06-13 23:40 UTC, ramrodo approved these changes
LGTM

2023-06-20 16:11 UTC, krol3 approved these changes
lgtm!

2023-06-20 16:11 UTC, merged