[FR] Traduction de Loosely Coupled Architecture into French
cncf/glossary pull request #2030
Opened 2023-05-12 14:13 UTC by huats

### Describe your changes

This PR localizes Loosely Coupled Architecture concept to French

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2029 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-14 15:12 UTC, sestegra requested changes

2023-05-14 15:12 UTC, sestegra commented on content/fr/loosely-coupled-architectures.md
> +Cette approche est souvent plus longue à mettre en oeuvre que l'architecture fortement couplée
s/oeuvre/œuvre/

2023-05-14 15:12 UTC, sestegra commented on content/fr/loosely-coupled-architectures.md
> +mais elle a plusieurs avantages, en particulier lorsque l'application change d'échelle.
Il est conseillée de mettre une virgule avec `mais`.

2023-05-14 15:12 UTC, sestegra commented on content/fr/loosely-coupled-architectures.md
> +Les application faiblement couplées permettent aux équipes de développer des fonctionnalités, de les déployer et les mettre à l'échelle de manière indépendante, ce qui permet aux organisations d'itér
s/application/applications/

2023-05-14 15:12 UTC, sestegra commented on content/fr/loosely-coupled-architectures.md
> +Les application faiblement couplées permettent aux équipes de développer des fonctionnalités, de les déployer et les mettre à l'échelle de manière indépendante, ce qui permet aux organisations d'itér
Dans la traduction de `reliability`, j'ai traduit `individual component` par `composant unitaire`.
Qu'en penses-tu ?

2023-06-14 15:31 UTC, sestegra approved these changes

2023-06-21 16:35 UTC, Krast76 approved these changes

2023-06-21 16:38 UTC, merged