Initialize traduction of Kubernetes into french
cncf/glossary pull request #2039
Opened 2023-05-14 14:16 UTC by Krast76

### Describe your changes

This PR localize Kubernetes into french.

### Related issue number or link (ex: `resolves #issue-number`)
Resolv #2038 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-14 14:20 UTC, Krast76 commented
@sestegra is missing from reviewer list cause I created my MR from dev-fr :(

2023-05-14 14:29 UTC, sestegra commented on content/fr/kubernetes.md
> +Il automatise le cycle de vie des applications conteneurisées sur des infrastructures modernes, fonctionnant comme un "Système d'exploitation de centre de données" qui gères des applications à traver
s/gères/gère/

2023-05-14 14:31 UTC, sestegra commented on content/fr/kubernetes.md
> +Kubernetes planifie la création de [conteneurs](/container/) sur les [noeuds](/nodes/) d'un  [cluster](/cluster/), regroupant plusieurs ressources d'infrastructure tel qu'un répartiteur de charge (lo
s/noeud/nœud/
Nœud a une ligature entre l'o et l'e (`e dans l'o`)

2023-05-14 14:35 UTC, sestegra commented on content/fr/kubernetes.md
> +Kubernetes permets l'automatisation et l'extensibilitié, permettant aux utilisateurs de déployer des applications de manière déclarative (voir ci-dessosu) et reproductible.
s/permets/permet/
s/l'extensibilitié/l'extensibilité/
s/ci-dessosu/ci-dessous/

2023-05-14 14:37 UTC, sestegra commented on content/fr/kubernetes.md
> +L'automatisation de l'infrastructure et la gestion de configuration déclarative sont des concepts importants depuis longtemps, mais ils sont devenus omniprésent depuis que le [cloud computing](/cloud
s/omniprésent/omniprésents/

2023-05-14 14:38 UTC, sestegra commented on content/fr/kubernetes.md
> +A mesure que la demande de ressources de calcul augmente et que les organisations ont besoin de plus de capacités avec moins d'ingénieurs, les nouvelles technologies et les méthodes de travaille doiv
s/A/À/
s/travaille/travail/

2023-05-14 14:51 UTC, sestegra commented on content/fr/kubernetes.md
> +Comme pour les outils traditionnels d'[infrastructure en tant que code](/infrastructure-as-code/), Kubernetes aide à l'automatisation mais à l'avantage de fonctionnait avec des conteneurs.
Dans cette phrase, la virgule est conseillée avant mais.
s/fonctionnait/fonctionner/

2023-05-14 14:52 UTC, sestegra commented on content/fr/kubernetes.md
> +Les conteneurs sont plus résistants aux écarts de configuration que les machines [virtuelles](/virtual-machine/) ou physique.
s/machines[virtuelles]/[machines virtuelles]/

2023-05-14 14:54 UTC, sestegra commented on content/fr/kubernetes.md
> +Kubernetes s'[auto-guérit](/self-healing/) également.
De mon côté, j'ai traduis `self-healing` par `auto-réparant`. Ainsi, je propose s/auto-guérit/auto-répare/

2023-05-14 14:58 UTC, sestegra commented on content/fr/kubernetes.md
> +Si kubernetes détecte une déviation par rapport à ce qui est décrit dans les fichiers manifests, un contrôleur Kubernetes va s'en occuper et le corriger.
s/kubernetes/Kubernetes/
s/fichiers manifest/fichiers manifestes/ (tu l'as mis en français plus haut)

2023-06-20 12:47 UTC, huats commented on content/fr/kubernetes.md
> +Kubernetes, souvent abrégé en k8s, est un orchestrateur de conteneur open source.
Il faut un s à conteneur je pense

2023-06-20 12:48 UTC, huats commented on content/fr/kubernetes.md
> +Il automatise le cycle de vie des applications conteneurisées sur des infrastructures modernes, fonctionnant comme un "Système d'exploitation de centre de données" qui gères des applications à traver
gère il ne faut pas de s

2023-06-20 12:52 UTC, huats commented on content/fr/kubernetes.md
> +Comme pour les outils traditionnels d'[infrastructure en tant que code](/infrastructure-as-code/) Kubernetes aide à l'automatisation, mais à l'avantage de fonctionner avec des conteneurs.
c'est "a l'avantage" pas "à"

2023-06-20 12:53 UTC, huats commented on content/fr/kubernetes.md
> +Les conteneurs sont plus résistants aux écarts de configuration que les [machines virtuelles](/virtual-machine/) ou physique.
physiqueS

2023-06-20 12:56 UTC, huats commented on content/fr/kubernetes.md
> +Bien que l'infrastructure utilisée par Kubernetes puisse être en constante évolution, Kubernetes s'adapte constamment et automatiquement aux changements et s'assure qu'elle correspond à l'état souhai
qu'elle correspondE

2023-06-23 10:01 UTC, sestegra requested changes

2023-06-23 10:01 UTC, sestegra commented on content/fr/kubernetes.md
> +Bien que l'infrastructure utilisée par Kubernetes puisse être en constante évolution, Kubernetes s'adapte constamment et automatiquement aux changements et s'assure qu'elle corresponde à l'état souha
Ici; le temps de la phrase est au présent, donc "correspond".
On utilise "corresponde" au subjonctif dans un contexte hypothétique.

2023-06-27 21:11 UTC, guillaumebernard84 commented on content/fr/kubernetes.md
> +De plus, Kubernetes fonctionne de manière déclarative, cela veut dire qu'au lieu que des opérateurs demandent à la machine de faire quelque chose, ils décrivent - souvent via un manifeste (p. ex., YA
Je pense qu'il faudrait utiliser des tirets longs (emdash) comme dans la version anglaise et non des tirets courts
En voici un prêt a être copié collé: —

2023-07-16 21:51 UTC, guillaumebernard84 approved these changes
LGTM 🚀

2023-07-17 08:35 UTC, sestegra requested changes

2023-07-17 08:35 UTC, sestegra commented on content/fr/kubernetes.md
> +Comme pour les outils traditionnels d'[infrastructure en tant que code](/infrastructure-as-code/) Kubernetes aide à l'automatisation, mais a l'avantage de fonctionner avec des conteneurs.
Je pense qu'il manque une virgule avant Kubernetes

2023-07-17 08:35 UTC, sestegra commented on content/fr/kubernetes.md
> +Kubernetes planifie la création de [conteneurs](/container/) sur les [nœuds](/nodes/) d'un  [cluster](/cluster/), regroupant plusieurs ressources d'infrastructure tel qu'un répartiteur de charge (loa
Il y a une espace en trop devant "cluster".

2023-07-17 08:35 UTC, sestegra commented on content/fr/kubernetes.md
> +De plus, Kubernetes fonctionne de manière déclarative, cela veut dire qu'au lieu que des opérateurs demandent à la machine de faire quelque chose, ils décrivent - souvent via un manifeste (p. ex., YA
Les 2 traits autour de "souvent via un manifeste" n'ont pas la même longueur, utilise le même caractère pour les 2.

2023-07-17 13:59 UTC, huats approved these changes
LGTM !

2023-07-18 09:33 UTC, sestegra approved these changes
LGTM 🚀

2023-07-18 09:49 UTC, merged