1409 german localize containers
cncf/glossary pull request #2049
Opened 2023-05-16 13:02 UTC by DaveVentura

### Describe your changes
added german localization for containers

### Related issue number or link (ex: `resolves #1409`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-07-05 10:25 UTC, BjoernSchotte commented on content/de/containers.md
> +Es können mehrere Container auf der selben Maschine laufen und es wird von der Container-Engine sichergestellt, dass diese nicht dieselben physischen Ressourcen belegen und auch nicht miteinander int
"derselben" statt "der selben"

2023-07-05 10:25 UTC, BjoernSchotte commented on content/de/containers.md
> +Durch die Nutzung des zugrunde liegenden Betriebssystem, sind sie im Vergleich zu [virtuellen Maschinen](/virtual-machine/) sehr leichtgewichtig und können schneller hoch- und heruntergefahren werden
Betriebssystems statt Betriebssystem:

Durch die Nutzung des zugrunde liegenden Betriebssystems

2023-07-13 07:57 UTC, DaveVentura commented on content/de/containers.md
> +Es können mehrere Container auf der selben Maschine laufen und es wird von der Container-Engine sichergestellt, dass diese nicht dieselben physischen Ressourcen belegen und auch nicht miteinander int
```suggestion
Es können mehrere Container auf derselben Maschine laufen und es wird von der Container-Engine sichergestellt, dass diese nicht dieselben physischen Ressourcen belegen und auch nicht miteinander interagieren.
```

2023-07-13 07:58 UTC, DaveVentura commented on content/de/containers.md
> +Container teilen sich dasselbe Betriebssysten, jedoch sind sie durch die Zuordnung virtueller Ressourcen voneinander isoliert, wodurch der Ressourcen-Overhead des Betriebssystems verteilt wird und ei
```suggestion
Container teilen sich dasselbe Betriebssystem, jedoch sind sie durch die Zuordnung virtueller Ressourcen voneinander isoliert, wodurch der Ressourcen-Overhead des Betriebssystems verteilt wird und eine effiziente Nutzung des physischen Rechners ermöglicht wird. 
```

2023-07-13 07:58 UTC, DaveVentura commented on content/de/containers.md
> +Durch die Nutzung des zugrunde liegenden Betriebssystem, sind sie im Vergleich zu [virtuellen Maschinen](/virtual-machine/) sehr leichtgewichtig und können schneller hoch- und heruntergefahren werden
```suggestion
Durch die Nutzung des zugrunde liegenden Betriebssystems, sind sie im Vergleich zu [virtuellen Maschinen](/virtual-machine/) sehr leichtgewichtig und können schneller hoch- und heruntergefahren werden.
```

2023-07-13 08:00 UTC, DaveVentura commented on content/de/containers.md
> +Durch die Nutzung des zugrunde liegenden Betriebssystem, sind sie im Vergleich zu [virtuellen Maschinen](/virtual-machine/) sehr leichtgewichtig und können schneller hoch- und heruntergefahren werden
Danke für das Review. :) Habe die Fehler korrigiert. Noch ein Tipp: Man kann Suggsestions machen, die kann man dann mit einem Klick übernehmen und commiten. Gerade bei so Rechtschreibefehlern nützlich. Aber auch bei Satzumformulierungen.

2023-07-13 12:39 UTC, iamNoah1 requested changes
@DaveVentura hab ein paar kleine Vorschläge. Sonst passt es :)

2023-07-13 12:39 UTC, iamNoah1 commented on content/de/containers.md
> +Ein Container ist eine virtuelle isolierte Umgebung, die als Prozess mit Ressourcen- und Kapazitätsbeschränkungen auf einem Computer läuft und von dessem Betriebssystem verwaltet wird.
```suggestion
Ein Container ist eine virtuelle isolierte Umgebung, die als Prozess mit Ressourcen- und Kapazitätsbeschränkungen auf einem Computer läuft und von dessen Betriebssystem verwaltet wird. 
```

2023-07-13 12:39 UTC, iamNoah1 commented on content/de/containers.md
> +Es können mehrere Container auf derselben Maschine laufen und es wird von der Container-Engine sichergestellt, dass diese nicht dieselben physischen Ressourcen belegen und auch nicht miteinander inte
```suggestion
Es können mehrere Container auf derselben Maschine laufen und es wird von der Container-Engine sichergestellt, 
dass diese nicht dieselben physischen Ressourcen belegen und auch nicht miteinander interagieren.
```

2023-07-13 12:39 UTC, iamNoah1 commented on content/de/containers.md
> +Benötigte Tools und Dateien werden als Container-Image verpackt und dieses ist somit in sich geschlossen und kann mit einer Container-Engine ohne weitere Abhängigkeiten von Tools oder Dateien ausgefü
```suggestion
Benötigte Tools und Dateien werden zu einem autonomen Container-Image verpackt, welches von einer  Container-Engine ohne weitere Abhängigkeiten von Tools oder Dateien ausgeführt werden kann. 
```

2023-07-17 06:33 UTC, bcubk approved these changes
Liest sich sehr gut 👍 LGTM

2023-07-17 07:42 UTC, merged