[fr] Localize vertical scaling
cncf/glossary pull request #2060
Opened 2023-05-18 15:54 UTC by sestegra

### Describe your changes

Localize `Vertical Scaling` in French

### Related issue number or link (ex: `resolves #issue-number`)

#1998 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-22 18:39 UTC, huats requested changes

2023-06-22 18:39 UTC, huats commented on content/fr/vertical-scaling.md
> +La [capacité de mise à l'échelle](/scalability/) contribue à la compétitivité, l'efficacité, la réputation et la qualité
il manque le point à la fin de la phrase

2023-06-22 18:39 UTC, huats commented on content/fr/vertical-scaling.md
> +La [capacité de mise à l'échelle](/scalability/) contribue à la compétitivité, l'efficacité, la réputation et la qualité
je mettrais un à devant "l'efficacité", "la réputation" et "la qualité" pour avoir "à l'efficacité, à la réputation et à la qualité."

2023-06-23 07:28 UTC, sestegra commented on content/fr/vertical-scaling.md
> +La [capacité de mise à l'échelle](/scalability/) contribue à la compétitivité, l'efficacité, la réputation et la qualité
Modification effectuée

2023-06-23 07:34 UTC, sestegra commented on content/fr/vertical-scaling.md
> +La [capacité de mise à l'échelle](/scalability/) contribue à la compétitivité, l'efficacité, la réputation et la qualité
Oui, c'est mieux.
Modification effectuée

2023-06-23 17:04 UTC, guillaumebernard84 commented
LGTM 🚀 

(bon, j'ai la aussi envie d'ouvrir une issue sur la version anglaise pour préciser "la compétitivité, l'efficacité, la réputation et la qualité" de quoi... j'ai l'impression qu'il manque la fin de la phrase. Mais j'attends de savoir ce qu'il va advenir de mes deux autres issues 😀 )

2023-06-26 10:50 UTC, Krast76 approved these changes
LGTM !

2023-06-26 15:29 UTC, huats approved these changes
LGTM !

2023-06-26 15:29 UTC, merged