[ES] content/es/_TEMPLATE.md
cncf/glossary pull request #2071
Opened 2023-05-21 10:25 UTC by marianogg9

### Describe your changes
- added `es/_TEMPLATE.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- resolves #1778 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-22 16:31 UTC, electrocucaracha requested changes

2023-05-22 16:31 UTC, electrocucaracha commented on content/es/_TEMPLATE.md
> +category: concepto
```suggestion
category: Concepto
```

2023-05-22 16:31 UTC, electrocucaracha commented on content/es/_TEMPLATE.md
> +Definir el problema que aborda. Idealmente, no mencionar el término que se está definiendo.
```suggestion
Definir el problema que aborda. Idealmente, no se debe mencionar el término que se está definiendo.
```

2023-05-22 22:57 UTC, ramrodo approved these changes
lgtm

2023-05-25 16:57 UTC, electrocucaracha approved these changes
/lgtm

2023-05-25 16:57 UTC, merged