[ES] content/es/mutual-transport-layer-security.md
cncf/glossary pull request #2072
Opened 2023-05-21 10:44 UTC by marianogg9

### Describe your changes
- added `es/mutual-transport-layer-security.md`.

### Related issue number or link (ex: `resolves #issue-number`)
- resolves #1397 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-22 16:29 UTC, electrocucaracha approved these changes
/lgtm

2023-05-22 22:54 UTC, ramrodo commented on content/es/mutual-transport-layer-security.md
> +La seguridad mutua de capa de transporte (mTLS en Inglés) es una técnica utilizada para autenticar y codificar mensajes enviados entre dos [servicios](/services).
La URL correcta es [/service](https://github.com/cncf/glossary/blob/main/content/en/mutual-transport-layer-security.md?plain=1#L10)

```suggestion
La seguridad mutua de capa de transporte (mTLS en Inglés) es una técnica utilizada para autenticar y codificar mensajes enviados entre dos [servicios](/service).
```

2023-05-22 22:56 UTC, ramrodo commented on content/es/mutual-transport-layer-security.md
> +Los ataques tales como personificación, robo de credenciales, fuerza bruta, etc, pueden ser prevenidos por mTLS.
```suggestion
Los ataques tales como personificación, robo de credenciales, fuerza bruta, etc., pueden ser prevenidos por mTLS.
```

2023-05-22 22:56 UTC, ramrodo requested changes
Un par de comentarios :)

2023-05-30 15:59 UTC, ramrodo approved these changes
LGTM

2023-05-30 15:59 UTC, merged