[ES] /content/es/search.md
cncf/glossary pull request #2086
Opened 2023-05-24 01:44 UTC by MartinEliasQ

### Describe your changes
This commit updates the text  _Site Results_ to _Resultados de la búsqueda_ to provide a version in Spanish.

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-24 16:57 UTC, ramrodo requested changes
Gracias por el PR, @MartinEliasQ .

¿Podrías agregar éstas dos palabras al archivo de palabras (`content/es/.wordlist.txt`) a ignorar en Inglés por favor...? Para que pase el test que está fallando:
- _layout_
- _search_

2023-05-24 17:12 UTC, MartinEliasQ commented
> Gracias por el PR, @MartinEliasQ .
> 
> ¿Podrías agregar éstas dos palabras al archivo de palabras (`content/es/.wordlist.txt`) a ignorar en Inglés por favor...? Para que pase el test que está fallando:
> 
> * _layout_
> * _search_

Hola @ramrodo ¡Listo!, Agregadas.

2023-05-24 18:01 UTC, MartinEliasQ reviewed
Las palabras fueron agregadas a content/es/.wordlist.txt

2023-05-24 18:07 UTC, electrocucaracha approved these changes

2023-05-30 15:45 UTC, ramrodo approved these changes
LGTM

2023-05-30 15:46 UTC, merged