[ES] Service.md
cncf/glossary pull request #2091
Opened 2023-05-24 14:18 UTC by MartinEliasQ

### Describe your changes

- Added service.md file with
- Change Linked Concept in Followiing files: 
    - content/es/abstraction.md
    - content/es/blue-green-deployment.md
    - content/es/event-driven-architecture.md
    - content/es/function-as-a-service.md
    - content/es/microservices-architecture.md
    - content/es/service-mesh.md

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-05-24 14:41 UTC, electrocucaracha requested changes

2023-05-24 14:41 UTC, electrocucaracha commented on content/es/service.md
> +category: concept
```suggestion
category: Concepto
```

2023-05-24 14:41 UTC, electrocucaracha commented on content/es/microservices-architecture.md
Este espacio adicional viene de la versión en inglés
```suggestion

```

2023-05-24 14:41 UTC, electrocucaracha commented on content/es/service.md
> +Es importante señalar que en TI, el término 'servicio' tiene diversos significados. En esta definición, nos enfocaremos en el más tradicional: servicio en términos de microservicio.
```suggestion
Es importante señalar que en TI, el término 'servicio' tiene diversos significados.
En esta definición, nos enfocaremos en el más tradicional: servicio en términos de microservicio.
```

2023-05-24 17:16 UTC, MartinEliasQ commented on content/es/microservices-architecture.md
>  La arquitectura de microservicios es una respuesta a estos retos.
Ah vale, gracias @electrocucaracha

2023-05-24 22:26 UTC, electrocucaracha approved these changes
/lgtm

2023-05-27 22:37 UTC, ramrodo approved these changes
LGTM

2023-05-27 22:38 UTC, merged