[it] Localizzazione termine Virtualization
cncf/glossary pull request #2102
Opened 2023-05-29 15:22 UTC by ugho16

### Describe your changes
Added Virtualization italian localization

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1658 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-04 13:23 UTC, fsbaraglia requested changes

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +Questi sistemi operativi e le loro risorse computazionali dedicate (CPU, memoria e rete) sono
```suggestion
Tali sistemi operativi isolati e le risorse di calcolo dedicate ad essi (CPU, memoria e rete) vengono
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +chiamati macchine virtuali (VM).
```suggestion
chiamati macchine virtuali o VM.
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +Nel contesto del cloud native computing, la virtualizzazione
```suggestion
La virtualizzazione, nell'ambito del calcolo nativo su cloud, 
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +si riferisce al processo di prendere un computer fisico, a volte chiamato server,
```suggestion
fa riferimento al processo di prendere un computer fisico, talvolta denominato server, 
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +e permettergli di eseguire diversi sistemi operativi isolati tra loro.
```suggestion
e consentirgli di eseguire più sistemi operativi isolati.
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +Le applicazioni eseguite su macchine virtuali non sono consapevoli di star condividendo un computer fisico.
```suggestion
Le applicazioni eseguite su macchine virtuali operano senza alcuna consapevolezza del fatto che condividono una stessa risorsa fisica.
```

2023-09-04 13:23 UTC, fsbaraglia commented on content/it/virtualization.md
> +Le VM, inoltre, permettono agli utenti di ridurre il tempo necessario per avere a disposizione un nuovo computer virtuale.
```suggestion
Le VM consentono inoltre agli utenti di ridurre il tempo necessario per mettere a disposizione un nuovo computer.
```

2023-09-06 22:18 UTC, fsbaraglia approved these changes

2023-09-06 22:18 UTC, fsbaraglia commented
@annalisag-spark  please review

2023-09-07 07:28 UTC, annalisag-spark commented on content/it/virtualization.md
> +La virtualizzazione, nell'ambito del calcolo nativo su cloud,
"calcolo nativo sul cloud" mi suona molto curioso. sento sempre utilizzare la versione in inglese. manterrei quella con la traduzione in italiano tra parentesi, al massimo.

2023-09-07 07:30 UTC, annalisag-spark commented on content/it/virtualization.md
> +fa riferimento al processo di prendere un computer fisico, talvolta denominato server,
```suggestion
si riferisce alla pratica per la quale a un computer fisico, talvolta denominato server,
```

2023-09-07 07:30 UTC, annalisag-spark commented on content/it/virtualization.md
> +e consentirgli di eseguire più sistemi operativi isolati.
```suggestion
viene consentito di eseguire più sistemi operativi isolati.
```

2023-09-07 07:30 UTC, annalisag-spark commented on content/it/virtualization.md
> +Tali sistemi operativi isolati e le risorse di calcolo dedicate ad essi (CPU, memoria e rete) vengono
```suggestion
Tali sistemi operativi isolati e le risorse di calcolo ad essi dedicate (CPU, memoria e rete) vengono
```

2023-09-07 07:31 UTC, annalisag-spark commented on content/it/virtualization.md
> +Per esempio, è possibile noleggiare un "computer" da AWS, ma quel computer è in realtà una VM.
qui preferirei rimanere vendor agnostic e sostituire "da AWS" con "dal cloud provider"

2023-09-07 07:32 UTC, annalisag-spark commented on content/it/virtualization.md
> +senza preoccuparsi dei vincoli fisici di dover aggiungere un nuovo computer fisico al datacenter.
```suggestion
senza preoccuparsi dei vincoli fisici di dover aggiungere del nuovo hardware al datacenter.
```

2023-09-07 08:02 UTC, ugho16 commented on content/it/virtualization.md
> +Per esempio, è possibile noleggiare un "computer" da AWS, ma quel computer è in realtà una VM.
```suggestion
Per esempio, è possibile noleggiare un "computer" da un provider, ma quel computer è in realtà una VM.
```

2023-09-07 08:05 UTC, ugho16 commented on content/it/virtualization.md
> +La virtualizzazione, nell'ambito del calcolo nativo su cloud,
```suggestion
La virtualizzazione, nell'ambito del cloud native computing (calcolo nativo su cloud), 
```

2023-09-07 08:12 UTC, annalisag-spark approved these changes

2023-09-07 08:19 UTC, merged