[bn] Localization for DevSecOps
cncf/glossary pull request #2110
Opened 2023-06-05 04:48 UTC by abhijeet-26

Signed-off-by: Abhijeet Basfore abhibas14@gmail.com

### Describe your changes
link - > https://glossary.cncf.io/devsecops/

### Related issue number or link (ex: `resolves #issue-number`)
#410

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-05 06:32 UTC, mitul3737 requested changes
You have not added the details:
---
title: DevSecOps 
status: Completed
category: concept
tags: ["methodology", "security", ""]
---

in localized form

2023-06-05 06:45 UTC, mitul3737 requested changes

2023-06-05 06:45 UTC, mitul3737 commented on content/bn/devsecops.md
> +দেভসেকঅপ্স (DevSecOps) শব্দটি উন্নয়ন, কর্মক্ষম, এবং নিরাপত্তা দায়িত্বের সাংস্কৃতিক একীকরণকে বোঝায়।
```suggestion
ডেভসেকঅপ্স (DevSecOps) শব্দটি উন্নয়ন, কর্মক্ষম, এবং নিরাপত্তা দায়িত্বের সাংস্কৃতিক একীকরণকে বোঝায়।
```

2023-06-05 06:45 UTC, mitul3737 commented on content/bn/devsecops.md
> +এটি ডেভেলপার এবং অপারেশনাল ওয়ার্কফ্লোতে ন্যূনতম থেকে কোনও ব্যাঘাত না করে সুরক্ষা অগ্রাধিকারগুলি অন্তর্ভুক্ত করতে দেভঅপ্স [(DevOps)](/bn/devops/) পদ্ধতির প্রসারিত করে৷
```suggestion
এটি ডেভেলপার এবং অপারেশনাল ওয়ার্কফ্লোতে ন্যূনতম  কোনও ব্যাঘাত না করে সুরক্ষা অগ্রাধিকারগুলি অন্তর্ভুক্ত করতে ডেভঅপ্স [(DevOps)](/bn/devops/) পদ্ধতির প্রসারিত করে৷ 
```

2023-06-05 06:45 UTC, mitul3737 commented on content/bn/devsecops.md
> +দেভঅপ্স-এর মতো, দেভসেকঅপ্স হল একটি সাংস্কৃতিক পরিবর্তন, যা গৃহীত প্রযুক্তির দ্বারা ঠেলে দেওয়া হয়, অনন্য গ্রহণের পদ্ধতি সহ।
```suggestion
ডেভঅপ্স-এর মতো, ডেভসেকঅপ্স হল একটি সাংস্কৃতিক পরিবর্তন, যা গৃহীত প্রযুক্তির দ্বারা ঠেলে দেওয়া হয়, অনন্য গ্রহণের পদ্ধতি সহ।
```

2023-06-05 06:45 UTC, mitul3737 commented on content/bn/devsecops.md
> +দেভঅপ্স অনুশীলনের মধ্যে রয়েছে অবিচ্ছিন্ন একীকরণ [(continuous integration)](/bn/continuous-integration/) এবং
```suggestion
ডেভঅপ্স অনুশীলনের মধ্যে রয়েছে অবিচ্ছিন্ন একীকরণ [(continuous integration)](/bn/continuous-integration/) এবং 
```

2023-06-05 06:45 UTC, mitul3737 commented on content/bn/devsecops.md
> +দেভসেকঅপ্স টিম সাইলো ভাঙ্গার উপর ফোকাস করে এবং সুরক্ষিত, স্বয়ংক্রিয় ওয়ার্কফ্লো তৈরির প্রচার করে।
```suggestion
ডেভসেকঅপ্স টিম সাইলো (silos) ভাঙ্গার উপর ফোকাস করে এবং সুরক্ষিত, স্বয়ংক্রিয় ওয়ার্কফ্লো তৈরির প্রচার করে। 
```

2023-06-06 18:21 UTC, Imtiaz1234 approved these changes

2023-06-06 18:21 UTC, merged