[FR] localization of Microservice-architecture
cncf/glossary pull request #2116
Opened 2023-06-05 20:41 UTC by guillaumebernard84

### Describe your changes
This PR localizes Microservice-architecture to French

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2115

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-23 09:52 UTC, sestegra requested changes

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Prenez Netflix comme exemple.
Je mettrais "Prenons" à la place de "Prenez".

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Ces fonctionnalités sont probablement alimentées par des services plus petits qui gèrent chacun une fonctionnalité, par exemple l'authentification, la recherche ou l'affichage d'aperçus dans votre na
Je garderais "each / chacun" dans la phrase pour accentuer et quelque chose comme cela:
"Ces fonctionnalités sont probablement alimentées par de plus petits services, chacun gérant une fonctionnalité spécifique, telle que l'authentification, la recherche et l'exécution des prévisualisations dans votre navigateur."

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Étant donné que tout le code se trouve au même endroit, il est facile de rendre ce code [étroitement couplé](/architectures-couplées-étroitement/) et plus difficile d'appliquer le principe de séparat
Il ne faut pas traduire les liens: `/tightly-coupled-architectures`

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Étant donné que tout le code se trouve au même endroit, il est facile de rendre ce code [étroitement couplé](/architectures-couplées-étroitement/) et plus difficile d'appliquer le principe de séparat
Je mettrais "tout le code se **re**trouve au même endroit, il est **plus** facile de..."

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Les monolithes exigent également souvent que les développeurs comprennent l'intégralité de la base de code avant d'y faire des modifications.
Je remplacerais "l'intégralité de la base de code" par "l'ensemble du code".

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +L'architecture des microservices est une réponse à ces défis.
Tu as utilisé "architecture en microservices" jusque là.
Pour rester homogène, je mettrais "architecture en microservices".

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +Cela permet également à différentes équipes de travailler simultanément sur une petite partie d'une grosse application sans avoir d'impact négatif par inadvertance sur le reste de l'application.
Pour "sur une petite partie d'une grosse application sans avoir d'impact négatif par inadvertance sur le reste de l'application", je préfère "sur une petite partie d'une application plus grande sans avoir d'impact involontairement négatif sur le reste de l'application"

2023-06-23 09:52 UTC, sestegra commented on content/fr/microservices-architecture.md
> +L'augmentation de la demande pour une fonctionnalité particulière n'augmentera pas forcement la demande pour d'autres fonctionnalités de l'application.
s/forcement/forcément/

2023-06-23 15:12 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Prenez Netflix comme exemple.
Oui, c'est corrigé

2023-06-23 15:12 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Ces fonctionnalités sont probablement alimentées par des services plus petits qui gèrent chacun une fonctionnalité, par exemple l'authentification, la recherche ou l'affichage d'aperçus dans votre na
OK, ça me va. C'est corrigé

2023-06-23 15:13 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Étant donné que tout le code se trouve au même endroit, il est facile de rendre ce code [étroitement couplé](/architectures-couplées-étroitement/) et plus difficile d'appliquer le principe de séparat
Un copié collé malheureux d'un logiciel de traduction auto. C'est corrigé

2023-06-23 15:14 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Étant donné que tout le code se trouve au même endroit, il est facile de rendre ce code [étroitement couplé](/architectures-couplées-étroitement/) et plus difficile d'appliquer le principe de séparat
oui, c'est mieux. C'est corrigé

2023-06-23 15:14 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Les monolithes exigent également souvent que les développeurs comprennent l'intégralité de la base de code avant d'y faire des modifications.
oui, c’est plus concis et plus clair. c'est corrigé

2023-06-23 15:14 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +L'architecture des microservices est une réponse à ces défis.
Un autre copié collé malheureux qui m'a échappé à la relecture, je pense. Je corrige.

2023-06-23 15:15 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Cela permet également à différentes équipes de travailler simultanément sur une petite partie d'une grosse application sans avoir d'impact négatif par inadvertance sur le reste de l'application.
Ok, c'est corrigé

2023-06-23 15:16 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +L'augmentation de la demande pour une fonctionnalité particulière n'augmentera pas forcement la demande pour d'autres fonctionnalités de l'application.
Oups, c'est passé au travers du correcteur orthographique. C'est corrigé

2023-06-23 17:59 UTC, sestegra approved these changes
LGTM 🚀

2023-06-25 19:44 UTC, Krast76 commented on content/fr/microservices-architecture.md
> +Bien qu'une architecture en microservices résolve de nombreux problèmes, elle crée également des surcouts opérationnels - le nombre d'éléments que vous devez déployer et gérer augmente considérableme
Il manque un ^sur le u de "surcoûts"

2023-06-26 13:49 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Bien qu'une architecture en microservices résolve de nombreux problèmes, elle crée également des surcouts opérationnels - le nombre d'éléments que vous devez déployer et gérer augmente considérableme
Depuis la réforme de l'orthographe de 1990, les deux orthographes sont valides. 
https://www.larousse.fr/dictionnaires/francais/surco%C3%BBt/75638
Moi je serais d'avis de laisser comme ça, mais je veux bien un autre avis.

2023-06-27 14:52 UTC, huats commented on content/fr/microservices-architecture.md
> +Bien qu'une architecture en microservices résolve de nombreux problèmes, elle crée également des surcouts opérationnels - le nombre d'éléments que vous devez déployer et gérer augmente considérableme
C'est vrai que c'est correct, mais j'avoue que je suis toujours choqué de le voir sans accent. Donc j'ai tendance à dire qu'il vaut mieux le mettre

2023-06-27 20:32 UTC, guillaumebernard84 commented on content/fr/microservices-architecture.md
> +Bien qu'une architecture en microservices résolve de nombreux problèmes, elle crée également des surcouts opérationnels - le nombre d'éléments que vous devez déployer et gérer augmente considérableme
OK, les deux sont corrects de toute façon 😄

2023-06-28 16:07 UTC, Krast76 approved these changes
LGTM

2023-06-28 16:07 UTC, merged