[EN] Added New Term - Cloud Native Storage
cncf/glossary pull request #2119
Opened 2023-06-08 13:38 UTC by Manthan1313Github

### Describe your changes
Added New Term - Cloud Native Storage

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2089

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-15 13:44 UTC, CathPag commented
Thanks for your contribution, @Manthan1313Github. We currently have a backlog and not enough people to help with reviews. We'll get to this but we would ask for your patience. Thanks in advance!

2024-01-09 13:59 UTC, iamNoah1 requested changes
Hei @Manthan1313Github and thanks for your contribution. I left some comments :)

2024-01-31 20:41 UTC, Manthan1313Github commented
@iamNoah1 
Thank you for the review. I will start working your comments and will create PR for this. Can you please assign this issue to me. So I can the updates.

2024-02-01 08:52 UTC, iamNoah1 commented
Hei @Manthan1313Github, the issue is already assigned to you :) And there is no to create a new PR you could just follow up your work in this PR. Thanks :)

2024-02-07 00:25 UTC, Manthan1313Github commented on content/en/cloud-native-storage.md
> +[containerized](/containerization/) environments. It efficiently manages data, replication, protection, and
@iamNoah1 
Problem it addresses
Traditional storage solutions are often slow and inflexible, making it difficult for cloud-based applications to store and manage large amounts of data. These solutions were designed for on-premises environments and are not optimized for the cloud. As a result, they can be expensive, difficult to scale, and may not provide the performance and availability that modern applications require.

2024-02-07 00:25 UTC, Manthan1313Github commented on content/en/cloud-native-storage.md
> +
@iamNoah1 
How it helps
Cloud native storage solutions offer several benefits for modern cloud native applications, including scalability, high availability, improved performance, and seamless integration with microservice-based architectures. These solutions are designed to be flexible and adaptable, allowing organizations to easily scale and manage large amounts of data as their applications grow. Additionally, cloud native storage solutions provide built-in redundancy and failover capabilities to ensure high availability, and they can be easily integrated with a wide range of microservices. Overall, cloud native storage solutions are an essential component of modern cloud native applications.

2024-08-15 23:33 UTC, manthan-parmar-1998 reviewed
Implemented suggested changes.

2024-11-01 20:02 UTC, nate-double-u requested changes
Thanks for this @manthan-parmar-1998. I have some comments and suggestions below.

2024-12-15 12:34 UTC, iamNoah1 commented
friendly ping @manthan-parmar-1998

2025-01-28 09:19 UTC, iamNoah1 reviewed
@nate-double-u can you do a last check please :)

2025-01-28 09:19 UTC, iamNoah1 commented on content/en/cloud-native-storage.md
> +Traditional storage systems often struggle to grow with increasing demand. They can be complicated to manage, slow to handle large amounts of data, and inefficient with resources. Older systems may a
```suggestion
Traditional storage systems often struggle to grow with increasing demand. 
They can be complicated to manage, slow to handle large amounts of data, and inefficient with resources. 
Older systems may also have trouble connecting with modern applications, leading to slow processes and scattered data. 
Manual scaling and maintenance further increase downtime and operational costs. 
These limitations make it difficult for businesses to adapt to evolving technology needs quickly.
```

Don't forget about semantic line breaks :)

2025-01-28 09:19 UTC, iamNoah1 commented on content/en/cloud-native-storage.md
> +Cloud native storage solves these problems by offering flexible scaling, easier management, and faster data access. It automatically increases or decreases storage based on demand, reducing manual wo
```suggestion
Cloud native storage solves these problems by offering flexible scaling, easier management, and faster data access. 
It automatically increases or decreases storage based on demand, reducing manual work and improving performance. 
With built-in caching and [distributed systems](/distributed-systems/), it ensures quick data retrieval. 
Pay-as-you-go pricing helps control costs while easily integrating with modern applications for smooth and efficient data management. 
Enhanced security features also protect sensitive data, and built-in automation reduces the risk of human error in storage operations.
```

Don't forget about semantic line breaks :)

2025-04-01 16:22 UTC, iamNoah1 approved these changes

2025-04-01 16:22 UTC, iamNoah1 commented on content/en/cloud-native-storage.md
> +status: Feedback Appreciated
```suggestion
status: Completed
```

2025-04-01 16:22 UTC, merged

2025-04-01 16:23 UTC, iamNoah1 commented
@manthan-parmar-1998 thank you so much for  your patience. Finally, we got it in :)

2025-04-03 14:36 UTC, manthan-parmar-1998 commented
@iamNoah1 @nate-double-u Thank You for Your Review and Guidance.