Added the translated version of the Zero trist architecture.
cncf/glossary pull request #2122
Opened 2023-06-11 20:42 UTC by MartinEliasQ

### Describe your changes
Added the translated version of the Zero trist architecture.

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-12 18:08 UTC, ramrodo commented on content/es/zero-trust-architecture.md
> +La arquitectura de Confianza cero se refiere a un enfoque del diseño y la implementación de sistemas informáticos donde la confianza se elimina por completo.
```suggestion
La arquitectura de confianza cero se refiere a un enfoque del diseño y la implementación de sistemas informáticos donde la confianza se elimina por completo.
```

2023-06-12 18:09 UTC, ramrodo commented on content/es/zero-trust-architecture.md
> +La arquitectura de Confianza cero toma un enfoque opuesto en el que, a pesar de estar dentro del perímetro de la red, los componentes dentro del sistema tienen que pasar primero por una verificación
```suggestion
La arquitectura de confianza cero toma un enfoque opuesto en el que, a pesar de estar dentro del perímetro de la red, los componentes dentro del sistema tienen que pasar primero por una verificación antes de que se establezca cualquier comunicación.
```

2023-06-12 18:10 UTC, ramrodo commented on content/es/zero-trust-architecture.md
> +En el supuesto de que un atacante consiga acceso a un dispositivo confiable, el sistema se vuelve vulnerable a un ataque. Esto depende del nivel de confianza y del acceso que se le haya otorgado a di
```suggestion
En el supuesto de que un atacante consiga acceso a un dispositivo confiable, el sistema se vuelve vulnerable a un ataque. Esto depende del nivel de confianza y del acceso que se le haya otorgado a dicho dispositivo, pues el atacante, al estar dentro del perímetro "de confianza" de la red, es capaz de moverse lateralmente a lo largo del sistema.
```

2023-06-12 18:11 UTC, ramrodo requested changes
Algunas sugerencias :)

2023-06-12 18:45 UTC, MartinEliasQ commented
> @MartinEliasQ podrías añadir en la descripción del PR (justo debajo de **Related issue number...** la leyenda de `resolves #1785` por favor? Esto para poder relacionar/unir el issue con el PR. Y, una vez fusionado éste PR, se cierre automáticamente el issue ligado.

Listo, @ramrodo

2023-06-12 23:22 UTC, ramrodo approved these changes
LGTM

2023-06-13 00:33 UTC, electrocucaracha approved these changes

2023-06-13 00:34 UTC, merged