[fr] Localize Virtualization
cncf/glossary pull request #2145
Opened 2023-06-15 08:04 UTC by guillaumebernard84

### Describe your changes
This PR localizes Virtualization to French

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2144 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-23 09:16 UTC, sestegra requested changes

2023-06-23 09:16 UTC, sestegra commented on content/fr/virtualization.md
> +appelées machines virtuelles ou VM.
Je mettrais un "s" à VM

2023-06-23 09:16 UTC, sestegra commented on content/fr/virtualization.md
> +C'est à dire quelque chose qui ressemble et se comporte comme un vrai ordinateur mais partage son matériel avec d'autres machines virtuelles.
"C'est-à-dire" prend des tirets

2023-06-23 09:16 UTC, sestegra commented on content/fr/virtualization.md
> +C'est à dire quelque chose qui ressemble et se comporte comme un vrai ordinateur mais partage son matériel avec d'autres machines virtuelles.
Je mettrais une virgule avant "mais".

2023-06-23 09:16 UTC, sestegra commented on content/fr/virtualization.md
> +sans se soucier des contraintes physiques liées à l'ajout d'un nouvel ordinateur dans un centre de données.
Comme discuté lors de notre réunion, la dernière phrase est valable.
"VMs also enable users to speed up the time to get a new virtual computer."
=> "Les VMs permettent également aux utilisateurs de réduire le temps nécessaire pour obtenir un nouvel ordinateur virtuel."
La VM est le moyen technique (abstraction du matériel) pour obtenir des ordinateurs virtuels (ou une instance de machine virtuelle).

2023-06-23 09:16 UTC, sestegra commented on content/fr/virtualization.md
> +Lorsque nous parlons d'une [machine virtuelle](/virtual-machine/), nous parlons d'un ordinateur défini logiciellement.
Je ne suis pas sûr que "logiciellement" existe.
Je mettrais "défini par logiciel".

2023-06-23 13:29 UTC, guillaumebernard84 commented on content/fr/virtualization.md
> +appelées machines virtuelles ou VM.
OK, moi je trouve toujours ça un peu bizarre, mais ça se fait.

2023-06-23 13:29 UTC, guillaumebernard84 commented on content/fr/virtualization.md
> +C'est à dire quelque chose qui ressemble et se comporte comme un vrai ordinateur mais partage son matériel avec d'autres machines virtuelles.
Bonne idée, c'est fait

2023-06-23 13:29 UTC, guillaumebernard84 commented on content/fr/virtualization.md
> +sans se soucier des contraintes physiques liées à l'ajout d'un nouvel ordinateur dans un centre de données.
Oui, j'ai ajouté la phrase. On verra bien ce que deviens mon issue sur la version anglaise.

2023-06-23 13:31 UTC, guillaumebernard84 commented on content/fr/virtualization.md
> +C'est à dire quelque chose qui ressemble et se comporte comme un vrai ordinateur mais partage son matériel avec d'autres machines virtuelles.
Je sais pas pourquoi mon correcteur orthographique laisse passer ça, désolé :/

2023-06-23 14:08 UTC, sestegra requested changes

2023-06-23 14:08 UTC, sestegra commented on content/fr/virtualization.md
> +Le [cloud computing](/cloud-computing/) fonctionne  principalement grâce à la virtualisation.
Il y a 2 espaces entre "fonctionne" et "principalement"

2023-06-23 15:06 UTC, guillaumebernard84 commented on content/fr/virtualization.md
> +Le [cloud computing](/cloud-computing/) fonctionne  principalement grâce à la virtualisation.
Bien vu! c'est corrigé

2023-06-23 17:57 UTC, sestegra approved these changes
LGTM 🚀

2023-06-25 19:35 UTC, Krast76 approved these changes
LGTM !

2023-06-26 15:27 UTC, merged