[FR] localize Nodes
cncf/glossary pull request #2147
Opened 2023-06-15 11:49 UTC by guillaumebernard84

### Describe your changes
This PR localizes Nodes to French

### Related issue number or link (ex: `resolves #issue-number`)
Solves https://github.com/cncf/glossary/issues/2146

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-23 08:54 UTC, sestegra requested changes

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Prenez par exemple votre ordinateur portable, votre modem et votre imprimante.
Je mettrais "prenons" à la place de "prenez".
"prenons" à la première personne du pluriel, convient si l'auteur de l'article inclut le lecteur dans le processus de réflexion ou d'analyse.

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Ils sont tous connectés sur votre réseau wifi communiquant et collaborant, chacun représentant un nœud.
Je mettrais "via" ou "à", à la place de "sur".

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Ils sont tous connectés sur votre réseau wifi communiquant et collaborant, chacun représentant un nœud.
J'ajouterais une virgule et "ensemble" dans la phrase, ce qui donnerait:
"votre réseau wifi, communiquant et collaborant ensemble, chacun représentant un nœud."

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +En effet, une panne du système sous-jacent va perturber l'application.
Je remplacerais "panne" par "défaillance".

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +En effet, une panne du système sous-jacent va perturber l'application.
Je remplacerais "En effet" par "En particulier".

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
"c'est-à-dire" prend des tirets et un accent grave sur le "a"

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
"un groupe de nœuds qui travaille ensemble" car c'est le groupe qui travaille.

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Un nœud fourni une unité de calcul (mémoire, processeur, réseau) que vous pouvez attribuer à un cluster.
s/fourni/fournit/
Ensuite, dans la version anglaise, l'auteur interpèle le lecteur avec "vous" et je pense qu'il faut accentuer en laissant le "distincte".
"Un nœud vous fournit une unité de calcul distincte"

2023-06-23 08:54 UTC, sestegra commented on content/fr/nodes.md
> +Idéalement, les nœuds individuels sont indifférenciés, c'est à dire que
"c'est-à-dire" prend des tirets et un accent grave sur le "a"

2023-06-23 13:11 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Prenez par exemple votre ordinateur portable, votre modem et votre imprimante.
Bonne idée, j'ai corrigé

2023-06-23 13:11 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Ils sont tous connectés sur votre réseau wifi communiquant et collaborant, chacun représentant un nœud.
Bonne idée. J'ai choisi "via"

2023-06-23 13:13 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
mon mauvais, je ne sais pas pourquoi c'est passé au travers de mon correcteur orthographique

2023-06-23 13:13 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Idéalement, les nœuds individuels sont indifférenciés, c'est à dire que
mon mauvais, je ne sais pas pourquoi c'est passé au travers de mon correcteur orthographique

2023-06-23 13:13 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +En effet, une panne du système sous-jacent va perturber l'application.
Bonne idée, c'est corrigé

2023-06-23 13:18 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
Tu es sur? Pour moi un seul groupe ne peut pas travailler ensemble.
Si un autre reviewer passe par là, j'aimerais avoir un deuxième avis

2023-06-23 13:20 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Un nœud fourni une unité de calcul (mémoire, processeur, réseau) que vous pouvez attribuer à un cluster.
J'ai corrigé s/fourni/fournit/
Pour distinct, je l'avais enlevé car je n'en comprenais pas le sens. 
"Un nœud vous fournit une unité de calcul distincte": distincte de quoi?

2023-06-27 14:48 UTC, huats commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
Oui pour moi aussi c'est au pluriel

2023-06-27 14:51 UTC, huats commented on content/fr/nodes.md
> +Un nœud fourni une unité de calcul (mémoire, processeur, réseau) que vous pouvez attribuer à un cluster.
Le distinct est séparé au sens non dépendant. Donc pourquoi en pas mettre "indépendante" ?

2023-06-27 20:29 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Un nœud fourni une unité de calcul (mémoire, processeur, réseau) que vous pouvez attribuer à un cluster.
Bon, je vous avoue que je ne suis pas sur de comprendre, mais vous avez l'air d'accord et c'est dans la version anglaise, donc je remet "distincte".

2023-06-27 20:29 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
Ok, je touche pas alors 😄

2023-06-28 16:23 UTC, guillaumebernard84 commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
Si on veux, on peux aussi esquiver la difficulté en mettant "un groupe de nœuds travaillant ensemble"

2023-06-28 16:40 UTC, sestegra commented on content/fr/nodes.md
> +Ainsi, les nœuds exécutent des applications ou des processus dans le cadre d'un groupe formant un [cluster](/cluster/), c'est a dire un groupe de nœuds qui travaillent ensemble pour atteindre un obje
Les deux formes sont valides.
https://dictionnaire.lerobert.com/guide/accord-du-verbe-avec-un-sujet-collectif

L'accord avec le nom collectif (ici "groupe") met l'accent sur la notion d'ensemble ;
l'accord avec le complément (ici "noeuds") insiste davantage sur les éléments qui composent cet ensemble.

2023-06-28 16:49 UTC, sestegra approved these changes

2023-06-28 21:22 UTC, huats approved these changes
LGTM

2023-06-28 21:22 UTC, merged