[FR] localize Distributed Apps
cncf/glossary pull request #2150
Opened 2023-06-15 21:13 UTC by guillaumebernard84

### Describe your changes
This PR localizes Distributed Apps to French

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2149

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-22 18:34 UTC, huats reviewed
Je veux bien ton retour là dessus

2023-06-22 18:34 UTC, huats commented on content/fr/distributed-apps.md
> +Une application distribuée est une application dont les fonctionnalités sont découpées en plusieurs parties indépendantes plus petites.
J'aurai tendance à dire en plusieurs parties indépendantes ET plus petites.

2023-06-22 18:34 UTC, huats commented on content/fr/distributed-apps.md
> +Une application monolithique peut également devenir un frein à la vitesse de développement à mesure que l'application grossi
grossiT non ?

2023-06-22 19:16 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application distribuée est une application dont les fonctionnalités sont découpées en plusieurs parties indépendantes plus petites.
Les deux me paraissent corrects, aucun souci pour rajouter "et"

2023-06-22 19:16 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application monolithique peut également devenir un frein à la vitesse de développement à mesure que l'application grossi
Exact, mon mauvais!

2023-06-23 07:45 UTC, sestegra commented on content/fr/distributed-apps.md
> +Une application monolithique peut également devenir un frein à la vitesse de développement à mesure que l'application grossi
Corrigé

2023-06-23 07:45 UTC, sestegra commented on content/fr/distributed-apps.md
> +Une application distribuée est une application dont les fonctionnalités sont découpées en plusieurs parties indépendantes plus petites.
Corrigé

2023-06-23 08:14 UTC, sestegra requested changes

2023-06-23 08:14 UTC, sestegra commented on content/fr/distributed-apps.md
> +car davantage de développeurs doivent travailler sur une base de code partagée qui n'a pas toujours des limites bien définies.
Je mettrais une virgule avant "car".

2023-06-23 08:14 UTC, sestegra commented on content/fr/distributed-apps.md
> +En divisant une application en différents éléments et en les exécutant à différents endroits, le système global peut tolérer davantage d'échecs.
J'utiliserais le terme "pannes" au lieu "échecs"

2023-06-23 08:14 UTC, sestegra commented on content/fr/distributed-apps.md
> +car vous exécutez désormais de nombreux composants d'application au lieu d'une seule application monolithique.
Dans la version anglaise, il y a une accentuation avec un "tiret" au lieu de l'utilisation de "car".

2023-06-23 08:14 UTC, sestegra commented on content/fr/distributed-apps.md
> +car vous exécutez désormais de nombreux composants d'application au lieu d'une seule application monolithique.
Pour garder le sens, je supprimerais le monolithique (non présent dans la version anglaise).
" - vous exécutez désormais de nombreux composants d'application au lieu d'une seule application".
L'accent est ici sur le nombre et pas le format.

2023-06-23 09:54 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application s'exécutant sur un seul ordinateur représente un point unique de défaillance : si cet ordinateur tombe en panne, l'application devient indisponible.
Parce que je n'aime pas trop les tirets, mais c’est une préférence personnelle, rien de plus. Je comprends la volonté de respecter au mieux le texte d'origine. Je le remet!

2023-06-23 09:55 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application s'exécutant sur un seul ordinateur représente un point unique de défaillance : si cet ordinateur tombe en panne, l'application devient indisponible.
Ok, je corrige

2023-06-23 09:58 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application monolithique peut également devenir un frein à la vitesse de développement à mesure que l'application grossit
J'ai trouvé que la version anglaise passait du singulier au pluriel de façon un peu abrupte, en utilisant un "they" dont on sait pas vraiment ce qu'il désigne. Mais c'est encore une fois une préférence personnelle, je corrige.

2023-06-23 09:58 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +car davantage de développeurs doivent travailler sur une base de code partagée qui n'a pas toujours des limites bien définies.
exact

2023-06-23 09:59 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +En divisant une application en différents éléments et en les exécutant à différents endroits, le système global peut tolérer davantage d'échecs.
tu as raison, ça colle mieux avec tolérance de panne

2023-06-23 10:02 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +car vous exécutez désormais de nombreux composants d'application au lieu d'une seule application monolithique.
Je corrige, je pensait justement que l'accent était sur le format, mon mauvais

2023-06-23 10:13 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +car davantage de développeurs doivent travailler sur une base de code partagée qui n'a pas toujours des limites bien définies.
Corrigé

2023-06-23 10:13 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application s'exécutant sur un seul ordinateur représente un point unique de défaillance : si cet ordinateur tombe en panne, l'application devient indisponible.
Corrigé

2023-06-23 10:13 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application s'exécutant sur un seul ordinateur représente un point unique de défaillance : si cet ordinateur tombe en panne, l'application devient indisponible.
Corrigé

2023-06-23 10:14 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +Une application monolithique peut également devenir un frein à la vitesse de développement à mesure que l'application grossit
Corrigé

2023-06-23 10:14 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +En divisant une application en différents éléments et en les exécutant à différents endroits, le système global peut tolérer davantage d'échecs.
Corrigé

2023-06-23 10:14 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +car vous exécutez désormais de nombreux composants d'application au lieu d'une seule application monolithique.
Corrigé

2023-06-23 10:14 UTC, guillaumebernard84 commented on content/fr/distributed-apps.md
> +car vous exécutez désormais de nombreux composants d'application au lieu d'une seule application monolithique.
Corrigé

2023-06-23 14:11 UTC, sestegra approved these changes
LGTM 🚀

2023-06-25 19:48 UTC, Krast76 approved these changes
LGTM !

2023-06-26 15:26 UTC, merged