[it] Localizzazione termine Zero Trust Architecture
cncf/glossary pull request #2159
Opened 2023-06-19 13:09 UTC by ugho16

### Describe your changes
Added Zero Trust Architecture Italian localization

### Related issue number or link (ex: `resolves #issue-number`)
Resolves #1659 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-26 12:27 UTC, annalisag-spark requested changes

2023-06-26 12:27 UTC, annalisag-spark commented on content/it/zero-trust-architecture.md
> +Oggi accade spesso che all'interno di un network aziendale i sistemi e i dispositivi possano comunicare liberamente tra loro
`Oggi accade spesso che internamente ad un network aziendale`

2023-06-26 12:27 UTC, annalisag-spark commented on content/it/zero-trust-architecture.md
> +i componenti all'interno del sistema devono superare delle verifiche, prima che possa avvenire un qualsiasi tipo di comunicazione.
`i componenti del sistema debbano superare delle verifiche`

2023-06-26 12:27 UTC, annalisag-spark commented on content/it/zero-trust-architecture.md
> +Con l'approccio tradizionale basato sulla fiducia con il quale si ritengono affidabili i sistemi e i dispositivi all'interno del perimetro del network aziendale,
`L'approccio tradizionale che si fonda sulla fiducia, secondo la quale si ritengono affidabili i sistemi e i dispositivi`

2023-06-26 12:27 UTC, annalisag-spark commented on content/it/zero-trust-architecture.md
> +l'assunto è che siccome c'è fiducia non ci sono problemi.
`si basa sull'assunto che siccome c'è fiducia, non c'è da preoccuparsi.`

2023-09-04 13:10 UTC, fsbaraglia approved these changes

2023-09-04 13:12 UTC, fsbaraglia commented
@annalisag-spark  se puoi fare una review, le modifiche da te richieste sono state implementate da Paolo

2023-09-04 13:49 UTC, annalisag-spark approved these changes

2023-09-04 13:53 UTC, merged