Initialize cluster into French
cncf/glossary pull request #2161
Opened 2023-06-19 20:12 UTC by Krast76

### Describe your changes

Localize cluster into French 

### Related issue number or link (ex: `resolves #issue-number`)

Fix #2041 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-06-20 13:07 UTC, huats requested changes

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +Dans le contexte du cloud native computing, le terme est souvent appliqué à [Kubernetes](/kubernetes/).
Perso je dirais "Dans le contexte du cloud native," et donc sans computing

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +Un cluster Kubernetes est un ensemble de services (ou de charge de travail) qui s'exécute dans leurs propres conteneurs, souvent sur des machines différentes.
chargeS de travail comme tu es au pluriel sur services

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +Un cluster Kubernetes est un ensemble de services (ou de charge de travail) qui s'exécute dans leurs propres conteneurs, souvent sur des machines différentes.
s'exécuteNT

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +alors quelque système critique pourrait être mis hors-ligne.
je mettrais "un" au lieu de quelque ici

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +C'est pourquoi généralement les logiciels modernes sont souvent construits sous forme d'[applications distribuée](/distributed-apps/), regroupés ensemble comme un cluster.
il faut que tu choisisse entre singulier et pluriel pour "application distribuée" et mettre tout au singulier ou pluriel :)

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +C'est pourquoi généralement les logiciels modernes sont souvent construits sous forme d'[applications distribuée](/distributed-apps/), regroupés ensemble comme un cluster.
ce sont les logiciels ou les applications qui sont regroupées ?

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +Les applications réparties en cluster s'exécutent sur plusieurs machines, élimine le point de défaillance unique.
je dirais "éliminant"

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +Le besoin en systèmes globaux et les années d'essais et d'erreur ont mené au développement d'un nouveau genre de pile technique:
d'erreurS

2023-06-20 13:07 UTC, huats commented on content/fr/cluster.md
> +[cloud native technologies](/cloud-native-tech/).
"technologies cloud nativeS" (et dans ce sens) ou alors tout au singulier (mais toujours dans le sens ici)

2023-06-20 15:11 UTC, guillaumebernard84 commented on content/fr/cluster.md
> +Dans le contexte du cloud native computing, le terme est souvent appliqué à [Kubernetes](/kubernetes/).
Salut. De mon coté quand je suis tombé sur ce genre de truc j'ai traduit "computing": _"Dans le contexte de l'informatique Cloud Native"_, avec des majuscules a Cloud et a Native, d'ailleurs. Dites moi ce que vous en pensez, et si je dois enlever mes majuscules :)

2023-06-27 21:07 UTC, guillaumebernard84 commented on content/fr/cluster.md
> +- si cet ordinateur tombe en panne, ou si accidentellement quelqu'un débranche le cable d'alimentation,
Je pense qu'il faudrait utiliser un tiret long (emdash) comme dans la version anglaise et non un tiret court
En voici un prêt a être copié collé:  —

2023-07-16 09:18 UTC, Krast76 commented on content/fr/cluster.md
> +Dans le contexte du cloud native computing, le terme est souvent appliqué à [Kubernetes](/kubernetes/).
Je partirais bien sur "Dans un contexte Cloud native" au final ?

2023-07-16 09:18 UTC, Krast76 commented on content/fr/cluster.md
> +Dans le contexte du cloud native computing, le terme est souvent appliqué à [Kubernetes](/kubernetes/).
Et je suis d'accord avec les majuscule à Cloud et Native ;)

2023-07-16 09:21 UTC, Krast76 commented on content/fr/cluster.md
> +C'est pourquoi généralement les logiciels modernes sont souvent construits sous forme d'[applications distribuée](/distributed-apps/), regroupés ensemble comme un cluster.
Les applications je dirais, j'ai rajouté un "e" du coup ;)

2023-07-17 08:42 UTC, sestegra requested changes

2023-07-17 08:42 UTC, sestegra commented on content/fr/cluster.md
> +— si cet ordinateur tombe en panne, ou si accidentellement quelqu'un débranche le cable d'alimentation,
Il manque un accent circonflexe sur "cable" => "câble"

2023-07-17 15:15 UTC, guillaumebernard84 commented
LGTM 🚀

2023-07-18 09:28 UTC, sestegra approved these changes
LGTM 🚀

2023-07-18 15:27 UTC, huats approved these changes
LGTM Ludo

2023-07-18 15:27 UTC, merged