Create service discovery.md
cncf/glossary pull request #2163
Opened 2023-06-20 05:05 UTC by akshayamadhuri

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-06 08:43 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-06 08:43 UTC, aj11anuj commented on content/hi/service discovery.md
> +title: सेवा खोज (Service Discovery)
```suggestion
title: सर्विस डिस्कवरी (Service Discovery)
```

2023-10-06 08:43 UTC, aj11anuj commented on content/hi/service discovery.md
> +सेवा की खोज एक सेवा बनाने वाले व्यक्तिगत उदाहरणों को खोजने की प्रक्रिया है। एक सर्विस डिस्कवरी टूल विभिन्न नोड्स या एंडपॉइंट्स का ट्रैक रखता है जो सेवा बनाते हैं।
```suggestion
'सर्विस डिस्कवरी' एक सेवा बनाने वाले व्यक्तिगत उदाहरणों को खोजने की प्रक्रिया है। एक सर्विस डिस्कवरी टूल, सर्विस बनाने वाले विभिन नोड्स या एंड-पॉइंट्स को ट्रैक करता है।
```

2023-10-06 08:43 UTC, aj11anuj commented on content/hi/service discovery.md
> +क्लाउड नेटिव आर्किटेक्चर गतिशील और तरल हैं, जिसका अर्थ है कि वे लगातार बदल रहे हैं। एक कंटेनरीकृत ऐप संभवतः अपने जीवनकाल में कई बार शुरू और बंद हो जाएगा। हर बार ऐसा होने पर, इसका एक नया पता होगा और क
```suggestion
क्लाउड नेटिव आर्किटेक्चर गतिशील और तरल हैं, जिसका अर्थ है कि वे लगातार बदलते रहेते हैं। एक कंटेनरीकृत ऐप संभवतः अपने जीवनकाल में कई बार शुरू और बंद होगा। हर बार ऐसा होने पर, इसका एक नया पता होगा और कोई भी ऐप जो इसे खोजना चाहता है उसे नए स्थान की जानकारी प्रदान करने के लिए एक टूल की आवश्यकता होगी।
```

2023-10-06 08:43 UTC, aj11anuj commented on content/hi/service discovery.md
> +सर्विस डिस्कवरी नेटवर्क के भीतर ऐप्स का ट्रैक रखती है ताकि जरूरत पड़ने पर वे एक-दूसरे को ढूंढ सकें। यह व्यक्तिगत सेवाओं को खोजने और संभावित रूप से पहचानने के लिए एक सामान्य स्थान प्रदान करता है। सेवा
```suggestion
सर्विस डिस्कवरी नेटवर्क के भीतर ऐप्स का ट्रैक रखती है ताकि जरूरत पड़ने पर वे एक-दूसरे को ढूंढ सकें। यह व्यक्तिगत सेवाओं को खोजने और संभावित रूप से पहचानने के लिए एक सामान्य स्थान प्रदान करता है। सर्विस की खोज करने वाले सर्च-इंजन डेटाबेस-जैसे उपकरण हैं, जो इस बारे में जानकारी संग्रहीत करते हैं कि कौन सी सेवाएँ मौजूद हैं और उनका पता कैसे लगाया जाए।
```

2023-10-08 04:27 UTC, aj11anuj approved these changes
LGTM, 👍

2023-11-27 17:49 UTC, bishal7679 commented on content/hi/service discovery.md
> +## समस्या यह संबोधित करती है
```suggestion
## समस्या
```

2023-11-27 17:49 UTC, bishal7679 commented on content/hi/service discovery.md
> +## यह कैसे मदद करता है
```suggestion
## समाधान
```

2023-11-30 06:52 UTC, bishal7679 commented on content/hi/service discovery.md
> +'सर्विस डिस्कवरी' एक सेवा बनाने वाले व्यक्तिगत उदाहरणों को खोजने की प्रक्रिया है। एक सर्विस डिस्कवरी टूल, सर्विस बनाने वाले विभिन नोड्स या एंड-पॉइंट्स को ट्रैक करता है।
```suggestion
सर्विस डिस्कवरी एक सेवा बनाने वाले व्यक्तिगत उदाहरणों को खोजने की प्रक्रिया है। एक सर्विस डिस्कवरी टूल, सर्विस बनाने वाले विभिन नोड्स या एंड-पॉइंट्स को ट्रैक करता है।
```

2023-11-30 06:55 UTC, bishal7679 approved these changes
LGTM!
Thank you @akshayamadhuri :sparkles:

2023-11-30 06:56 UTC, merged