Reput the french translation for container
cncf/glossary pull request #2202
Opened 2023-07-06 16:14 UTC by huats

### Describe your changes

Reput the translation for container in French

### Related issue number or link (ex: `resolves #issue-number`)

#2200 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-07-06 18:36 UTC, sestegra requested changes

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +tags: ["application", "", ""]
Il manque le tag "fundamental"

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +Les conteneurs sont executés les uns à coté des autres sur la même machine,
Il manque un accent sur `exécutés`

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +mais habituellement le système d'exploitation empêche les processus de conteneurs différents d'interagir ensemble.
Je préfère `les uns avec les autres` à place de `ensemble`.
De mon point de vue, `ensemble` sous-entend que tous les containers interagissent tous ensemble.

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +Ceci permet de faire fonctionner plus d'applications sur la même machine physique.
Dans la version anglaise, il y a `many more` pour accentuer la grande différence.
Je prèfère `beaucoup plus` à la place de seulement `plus`.

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +Les conteneurs sont executés les uns à coté des autres sur la même machine,
Il manque un accent circonflexe sur `côté`

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +tout celà pour faire fonctionner une simple application.
`cela` ne prend pas d'accent.

2023-07-06 18:36 UTC, sestegra commented on content/fr/container.md
> +Cette possibilité est uniquement offerte car les conteneurs sont habituellement limités dans leurs interactions mutuelles.
Une virgule est conseillée dans ce contexte devant `car`: les deux parties reliées ne sont pas courtes.
Sinon, il est possible d'utiliser `parce que` sans virgule.

2023-07-07 11:12 UTC, sestegra approved these changes
LGTM 🚀

2023-07-11 21:02 UTC, guillaumebernard84 commented on content/fr/container.md
> +et se répartissent la surcharge des ressources dues au système d'exploitation, permettant un usage efficace de la machine physique.
Ce bout de phrase ne me parait pas très clair, même si c’est une traduction correcte de l'anglais: "et se répartissent la surcharge des ressources dues au système d'exploitation"
Je ne suis pas sûr que le terme "surcharge" convienne pour parler de la consommation de l'OS, et elle n'est pas vraiment répartie.

Malheureusement j'ai pas beaucoup mieux à proposer, mais je pense qu'on peut trouver un truc bien en y réfléchissant ensemble. 

Je propose: "la consommation de ressources du système d'exploitation est donc lissée sur l'ensemble des conteneurs". 
ça me semble plus clair tout en restant conforme à l'esprit de la phrase en anglais.

Si vous trouvez que je pinaille, je comprendrais 😁

2023-07-11 21:06 UTC, guillaumebernard84 commented on content/fr/container.md
> +mais habituellement le système d'exploitation empêche les processus de conteneurs différents d'interagir les uns avec les autres.
J'aurais traduit "typically" par "généralement" au lieu de "habituellement". Pareil ligne 26.

2023-07-16 09:50 UTC, Krast76 commented on content/fr/container.md
> +mais habituellement le système d'exploitation empêche les processus de conteneurs différents d'interagir les uns avec les autres.
Les deux me vont, mais je trouve que généralement est plus "jolie" également. :)

2023-07-16 09:50 UTC, Krast76 commented on content/fr/container.md
> +et se répartissent la surcharge des ressources dues au système d'exploitation, permettant un usage efficace de la machine physique.
Je suis assez d'accord pour qu'on en rediscute. 

Je pense que le fond de la phrase là c'est plus de dire qu'on a pas le côut de l'OS dans chaques conteneurs, car on partage celui de l'hôte justement.

On pourrait peut-être reformuler comme ça :

"Les conteneurs partagent le même système d'exploitation et ses ressources machine, ce qui diminue la surcharge de l'OS et permet un usage de la machine physique plus efficient."

2023-07-16 22:23 UTC, guillaumebernard84 commented on content/fr/container.md
> +et se répartissent la surcharge des ressources dues au système d'exploitation, permettant un usage efficace de la machine physique.
J'aime pas trop "diminue la surcharge", pour moi il n'y a pas de surcharge, et rien n'est diminué. 
Allez je tente un autre truc. ça s'éloigne pas mal du texte anglais d'origine, donc je sais déjà que ça plaira pas a Stéphane 😁 

"Les conteneurs partagent le même système d'exploitation et ses ressources machine. Faire fonctionner un seul système d'exploitation pour de nombreux containers économise des ressources, et permet donc usage plus efficace de la machine physique."

2023-07-17 14:03 UTC, huats commented on content/fr/container.md
> +et se répartissent la surcharge des ressources dues au système d'exploitation, permettant un usage efficace de la machine physique.
Je viens de mettre la phrase suivante : 
" Les conteneurs partagent le même système d'exploitation et ses ressources machine,
  et se partagent donc la charge additionnelle des ressources dues au système d'exploitation, ce qui permet un usage efficace de la machine physique."

2023-07-17 15:13 UTC, guillaumebernard84 commented
LGTM 🚀

2023-07-17 15:13 UTC, guillaumebernard84 commented on content/fr/container.md
> +mais habituellement le système d'exploitation empêche les processus de conteneurs différents d'interagir les uns avec les autres.
@huats il y a la même chose ligne 26, mais tu ne l'a pas changé. C'est volontaire?

2023-07-17 15:14 UTC, Krast76 approved these changes

2023-07-18 09:49 UTC, merged