[DE] localize Cluster
cncf/glossary pull request #2208
Opened 2023-07-07 11:11 UTC by iamNoah1

### Describe your changes
A new approach to localize the term Cluster 

### Related issue number or link (ex: `resolves #issue-number`)
#1407

deprecates #1967

Thanks @Björn for the contribution, this is a new approach. 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-07-08 19:26 UTC, BjoernSchotte commented
Thanks @iamNoah1 for the excellent cooperation. Really appreciated that.

I assume that English language is the leading branch, so advancements in localized branches have to be pulled back to the English branch in order to achieve better consistency.

Not sure if you evaluated toolings for this (I saw some slack message about this), maybe there are some toolings for l10ns which could help improving consistency.

Further thinking: If there are n:1 PRs re 1 english term (i.e. multiple suggestions from different branches) there will be some coordination effort, too.

2023-07-12 16:14 UTC, iamNoah1 commented
> Thanks @iamNoah1 for the excellent cooperation. Really appreciated that.
> 
> I assume that English language is the leading branch, so advancements in localized branches have to be pulled back to the English branch in order to achieve better consistency.
> 
> Not sure if you evaluated toolings for this (I saw some slack message about this), maybe there are some toolings for l10ns which could help improving consistency.
> 
> Further thinking: If there are n:1 PRs re 1 english term (i.e. multiple suggestions from different branches) there will be some coordination effort, too.

see #2210

2023-07-13 08:04 UTC, DaveVentura requested changes

2023-07-13 08:04 UTC, DaveVentura commented on content/de/cluster.md
> +Hierfür wird üblicherweise eine Komponente verwendet die als Load Balancer bekannt ist und anfragen an ein Cluster lediglich an erreichbare Computer weiterleitet.
```suggestion
Hierfür wird üblicherweise eine Komponente verwendet, die als Load Balancer bekannt ist und Anfragen an ein Cluster lediglich an erreichbare Computer weiterleitet.
```

2023-07-13 08:04 UTC, DaveVentura commented on content/de/cluster.md
> +Wenn eines dieser Computer oder die Anwendung darin abstürzt oder aus anderen Gründen ausfällt, können die anderen Computer übernehmen.
```suggestion
Wenn einer dieser Computer oder die Anwendung darin abstürzt oder aus anderen Gründen ausfällt, können die anderen Computer übernehmen. 
```

2023-07-13 12:33 UTC, iamNoah1 commented
@DaveVentura hab die suggestions eingebaut. Können wir noch einen review von @bcubk bekommen bitte :)

2023-07-16 20:03 UTC, bcubk approved these changes
Finde ich sehr gut übersetzt. Das Orginal in Englisch ist schon sehr aufgebläht. Diese Version finde ich sehr schlank und sachlich. LGTM 👍

2023-07-18 13:40 UTC, iamNoah1 commented on content/de/cluster.md
> +Jedenfalls kommunizieren einzelnen Computer über ein geeignetes Netzwerk miteinander.
```suggestion
Jedenfalls kommunizieren einzelnen Computer über ein Netzwerk miteinander. 
```

2023-07-18 13:41 UTC, merged