Update hi.toml
cncf/glossary pull request #2215
Opened 2023-07-10 17:57 UTC by panchal20bhavin

### Describe your changes
Translate Remaining English String into hindi language

### Related issue number or link (ex: `resolves #issue-number`)
#2182 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-07-11 01:38 UTC, jihoon-seo commented on i18n/hi.toml
> +other ="टैग"
We don't need to remove the spaces. Let's preserve.

```suggestion
other = "टैग"
```

2023-07-11 01:38 UTC, jihoon-seo commented on i18n/hi.toml
> +other ="सभी CNCF साइटें"
```suggestion
other = "सभी CNCF साइटें"
```

2023-07-11 01:40 UTC, jihoon-seo commented
@Garima-Negi @sayantani11 @anubha-v-ardhan @jayesh-srivastava please review the Hindi localization in this PR!

2023-10-08 10:49 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "देखना सभी टैग"
```suggestion
other = "सभी टैग को देख़े"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "टैग"
```suggestion
other = "टैग्स"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "ब्राउज़ द्वारा टैग"
```suggestion
other = "टैग द्वारा ब्राउज करें"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "हमने शब्दावली शब्दों को वर्गीकृत किया है. टैग द्वारा शब्दों को ब्राउज़ करने के लिए फ़िल्टर का उपयोग करें."
```suggestion
other = "हमने शब्दावली के शब्दों को वर्गीकृत किया है। टैग द्वारा शब्दों को ब्राउज़ करने के लिए फ़िल्टर का उपयोग करें।"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "...या ब्राउज़ द्वारा टैग"
```suggestion
other = "...या टैग द्वारा ब्राउज़ करें"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "सबका चुनाव करना"
```suggestion
other = "सबका चुनाव करें"
```

2023-10-08 10:49 UTC, aj11anuj commented on i18n/hi.toml
> +other = "सबका चुनाव रद्द करें"
```suggestion
other = "सारे चुनाव रद्द करें"
```

2023-10-31 17:02 UTC, kumarankit999 reviewed
Now looks good by anuj

2023-11-12 05:38 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-12 10:52 UTC, seokho-son approved these changes
LGTM. :)

FYI, to apply the latest approvers (the https://github.com/cncf/glossary/blob/main/CODEOWNERS#L43 ) to dev-hi, dev-hi needs to be rebased. 

After that, /i18n/hi.toml can be approved solely by Hindi team.

2023-11-12 10:52 UTC, merged