[FR] Localize blue-green deployment
cncf/glossary pull request #2261
Opened 2023-07-28 17:52 UTC by sestegra

### Describe your changes

Localize `blue-green deployment`

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2260 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-08-23 18:43 UTC, guillaumebernard84 commented on content/fr/blue-green-deployment.md
> +Les déploiements bleu/vert permettent une interruption minimale lors de la mise à jour de logiciels qui doivent être modifiés en "étapes vérouillées" en raison d'un manque de rétrocompatibilité.
Cette phrase me parait confuse, et un peu jargoneuse. Je suis pas dev mais j'ai jamais entendu  "étapes vérouillées" pour un deploiement lockstep. On ne sais pas trop non plus de quelle retrocompatibilité on parle
J'aurais plutot traduit "lockstep" par "simultanément".  

Quelque chose comme:
Les déploiements bleu/vert permettent une interruption minimale lors de la mise à jour d'un ensemble de logiciels qui nécessitent une mise a jour simultanée en raison d'un manque de rétrocompatibilité entre eux.

C'est toujours confus, mais un peu moins. J'ai pas mieux.
Vous en pensez quoi?

2023-08-23 18:43 UTC, guillaumebernard84 commented on content/fr/blue-green-deployment.md
> +Cependant, son utilisation est normalement un "signe" que le logiciel hérité doit être réingénierisé afin que les composants puissent être mis à jour individuellement.
Je trouve que réingénierisé est correct mais un peu jargoneux. Repensé, ou refondu, ou un truc comme ça me parait plus simple. 
En plus dans la vraie vie, personne ne dis réingénierisé, tout le monde dit réingénieré même si c'est incorrect et un anglicisme 😁

2023-08-23 18:43 UTC, guillaumebernard84 commented on content/fr/blue-green-deployment.md
> +Par exemple, le déploiement bleu/vert serait approprié pour une boutique en ligne composée d'un site web et d'une base de données qui doit être mise à jour, mais la nouvelle version de la base de don
"qui doivent être mise à jour", au pluriel puisqu'on met a jour le site et la base

2023-09-03 16:11 UTC, Krast76 requested changes

2023-09-03 16:11 UTC, Krast76 commented on content/fr/blue-green-deployment.md
> +Les déploiements bleu/vert permettent une interruption minimale lors de la mise à jour de logiciels qui doivent être modifiés en "étapes vérouillées" en raison d'un manque de rétrocompatibilité.
Pour ma part, la traduction de lockstep en "étapes vérouillées" me convient bien.

2023-09-03 16:11 UTC, Krast76 commented on content/fr/blue-green-deployment.md
> +Cependant, son utilisation est normalement un "signe" que le logiciel hérité doit être réingénierisé afin que les composants puissent être mis à jour individuellement.
Je suis assez d'accord avec @guillaumebernard84.

J'proposerai bien "redévelopper" ou "réorganiser"

2023-09-20 08:02 UTC, sestegra commented on content/fr/blue-green-deployment.md
> +Une fois que les tests ont été conclus sur l'environnement non actif (vert),
Mise à jour effectuée

2023-09-20 08:03 UTC, sestegra commented on content/fr/blue-green-deployment.md
> +Par exemple, le déploiement bleu/vert serait approprié pour une boutique en ligne composée d'un site web et d'une base de données qui doit être mise à jour, mais la nouvelle version de la base de don
Mise à jour effectuée

2023-09-20 08:05 UTC, sestegra commented on content/fr/blue-green-deployment.md
> +Cependant, son utilisation est normalement un "signe" que le logiciel hérité doit être réingénierisé afin que les composants puissent être mis à jour individuellement.
J'ai choise "redéveloppé"

2023-09-20 08:11 UTC, sestegra commented on content/fr/blue-green-deployment.md
> +Les déploiements bleu/vert permettent une interruption minimale lors de la mise à jour de logiciels qui doivent être modifiés en "étapes vérouillées" en raison d'un manque de rétrocompatibilité.
Mise à jour effectuée

2023-10-01 15:34 UTC, Krast76 approved these changes
LGTM 🚀

2023-10-01 15:35 UTC, merged