Localize policy as code #1653
cncf/glossary pull request #2265
Opened 2023-07-31 13:36 UTC by matteobisi

### Describe your changes
I've added the IT localization for "policy as a code"

### Related issue number or link (ex: `resolves #issue-number`)

#1653 
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-08-01 08:22 UTC, annalisag-spark requested changes
🙂

2023-08-01 08:22 UTC, annalisag-spark commented on content/it/policy-as-code.md
> +Il processo di verifica manuale della loro appliaczione su applicazioni o infrastruttura da parte di sviluppatori e revisori
```suggestion
 Per gli sviluppatori e i revisori è molto laborioso e soggetto a errori verificare manualmente le applicazioni e le infrastrutture rispetto alle policy documentate.
```

2023-08-01 08:22 UTC, annalisag-spark commented on content/it/policy-as-code.md
> +è complesso e soggetto a errori.
```suggestion

```

2023-08-01 08:22 UTC, annalisag-spark commented on content/it/policy-as-code.md
> +Utilizzare il policy as a code consente la ripetibilità ed automazione, riducendo gli errori rispetto alla loro applicazione manuale.
```suggestion
Utilizzare Policy as Code la ripetibilità e riduce gli errori, a differenza di quanto avviene manualmente.
```

2023-08-01 08:43 UTC, annalisag-spark requested changes

2023-08-01 08:43 UTC, annalisag-spark commented on content/it/policy-as-code.md
> +Utilizzare il policy as a code consente la ripetibilità ed automazione, riducendo gli errori rispetto alla loro applicazione manuale.
togliere quell'_a_ che precede Code

2023-08-01 12:36 UTC, ugho16 requested changes

2023-08-01 12:36 UTC, ugho16 commented on content/it/policy-as-code.md
> + Per gli sviluppatori e i revisori è molto laborioso e soggetto a errori verificare manualmente le applicazioni e le infrastrutture rispetto alle policy documentate.
```suggestion
Per gli sviluppatori e i revisori è molto laborioso e soggetto a errori verificare manualmente le applicazioni e le infrastrutture rispetto alle policy documentate.
```

2023-08-01 12:36 UTC, ugho16 commented on content/it/policy-as-code.md
> +Utilizzare Policy as Code la ripetibilità e riduce gli errori, a differenza di quanto avviene manualmente.
```suggestion
Utilizzare Policy as Code consente la ripetibilità e riduce gli errori, a differenza di quanto avviene manualmente.
```

2023-08-01 12:36 UTC, ugho16 commented on content/it/policy-as-code.md
> +La costruzione di applicazioni e infrastrutture è spesso vincolata da molte policy che un'organizzazione definisce,
```suggestion
La costruzione di applicazioni e infrastrutture è spesso vincolata a molte policy che un'organizzazione definisce, 
```

2023-08-02 06:45 UTC, ugho16 approved these changes

2023-08-02 06:49 UTC, annalisag-spark approved these changes

2023-08-02 09:37 UTC, merged