[FR] localize `Cloud Computing`
cncf/glossary pull request #2272
Opened 2023-08-05 07:12 UTC by guillaumebernard84

### Describe your changes
localize `Cloud Computing` in french

### Related issue number or link (ex: `resolves #issue-number`)
Solves https://github.com/cncf/glossary/issues/1263

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-08-09 07:46 UTC, sestegra requested changes

2023-08-09 07:46 UTC, sestegra commented on content/fr/cloud-computing.md
> +situées dans un emplacement physique distant. On différencie généralement le cloud privé du cloud public,
Je préfère "nous" à "on", ou alors changer la formulation.

2023-08-09 07:46 UTC, sestegra commented on content/fr/cloud-computing.md
> +suivant si l'infrastructure cloud est exclusivement dédiée à une entreprise, ou mutualisée et ouverte au public.
Je propose de remplacer "entreprise" par "organisation", car les administrations, les associations... (et pas seulement les entreprises) utilisent aussi.

2023-08-09 07:46 UTC, sestegra commented on content/fr/cloud-computing.md
> +Les entreprises avaient traditionnellement deux solutions lorsqu'elles voulaient accroitre leur capacité de calcul.
Je propose de remplacer "entreprises" par "organisations", car les administrations, les associations (et pas seulement les entreprises) utilisent aussi.

2023-08-09 07:46 UTC, sestegra commented on content/fr/cloud-computing.md
> +Les fournisseurs de cloud permettent aux entreprises de louer des ressources informatiques à la demande et de payer à l'utilisation, offrant deux avantages majeurs.
Je propose de remplacer "entreprises" par "organisations", car les administrations, les associations (et pas seulement les entreprises) utilisent aussi.

2023-08-09 07:46 UTC, sestegra commented on content/fr/cloud-computing.md
> +Le cloud computing permet aux entreprises d'adopter autant ou aussi peu d'infrastructure qu'elles le souhaitent.
Je propose de remplacer "entreprises" par "organisations", car les administrations, les associations (et pas seulement les entreprises) utilisent aussi.

2023-08-09 12:20 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +situées dans un emplacement physique distant. On différencie généralement le cloud privé du cloud public,
Le nous me va bien!

2023-08-09 12:21 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +suivant si l'infrastructure cloud est exclusivement dédiée à une entreprise, ou mutualisée et ouverte au public.
J'avais hésité, ça me va!

2023-08-09 12:37 UTC, sestegra approved these changes
LGTM 🚀

2023-08-10 16:53 UTC, huats requested changes

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +du réseau et de l'espace disque à la demande sur Internet, permettant aux utilisateurs d'accéder à des ressources informatiques
au lieu de dire espace disque, peut être "espace de stockage" ?

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +Le cloud computing, ou informatique en nuage, offre des ressources informatiques telles que de la puissance de calcul,
tu pourrais rajouter infonuagique au Québec,

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +situées dans un emplacement physique distant. nous différencions généralement le cloud privé du cloud public,
Nous (il manque la majuscule)

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +Les organisations avaient traditionnellement deux solutions lorsqu'elles voulaient accroitre leur capacité de calcul.
On pourrait dire accroître non ? je sais que les 2 sont valides... je vous laisse choisir

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +soit étendre et entretenir celles qui existent déjà. Le cloud computing résout ce dilemme
qui existaient déjà (pour concordance des temps)

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +Et deuxièmement, elles peuvent simplement se [mettre à l’échelle] (/scalability/) souhaitée à la demande, en fonctions de leurs besoins.
Cette phrase est bizarre. Le "se" est en trop au minima.

2023-08-10 16:53 UTC, huats commented on content/fr/cloud-computing.md
> +Le cloud computing permet aux organisations d'adopter autant ou aussi peu d'infrastructure qu'elles le souhaitent.
je trouve que le  "autant ou aussi peu" ni le "adopter" ne sont naturels... Peut être faire une traduction moins proche de l'anglais ?

2023-08-10 17:22 UTC, sestegra commented on content/fr/cloud-computing.md
> +Les organisations avaient traditionnellement deux solutions lorsqu'elles voulaient accroitre leur capacité de calcul.
On a mis l'accent circonflexe dans les autres, pour rester cohérent, il faut le mettre.

2023-08-10 17:24 UTC, sestegra commented on content/fr/cloud-computing.md
> +Et deuxièmement, elles peuvent simplement se [mettre à l’échelle] (/scalability/) souhaitée à la demande, en fonctions de leurs besoins.
Est-ce que si on ajoute une virgule avant "à la demande", cela passe mieux pour toi ?

2023-08-10 17:27 UTC, sestegra commented on content/fr/cloud-computing.md
> +Le cloud computing permet aux organisations d'adopter autant ou aussi peu d'infrastructure qu'elles le souhaitent.
Je propose quelque chose comme cela
"Le cloud computing permet aux organisations de disposer de l'infrastructure nécessaire, en grande ou en petite quantité."

2023-08-10 17:30 UTC, huats commented on content/fr/cloud-computing.md
> +Le cloud computing permet aux organisations d'adopter autant ou aussi peu d'infrastructure qu'elles le souhaitent.
Oui ! je vote pour !

2023-08-10 17:31 UTC, huats commented on content/fr/cloud-computing.md
> +Et deuxièmement, elles peuvent simplement se [mettre à l’échelle] (/scalability/) souhaitée à la demande, en fonctions de leurs besoins.
Oui !

2023-08-10 17:31 UTC, sestegra commented on content/fr/cloud-computing.md
> +Et deuxièmement, elles peuvent simplement se [mettre à l’échelle] (/scalability/) souhaitée à la demande, en fonctions de leurs besoins.
Ou cette proposition
"Et deuxièmement, elles peuvent simplement réaliser une mise à l'échelle à la demande selon les besoins."

2023-08-11 12:33 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +du réseau et de l'espace disque à la demande sur Internet, permettant aux utilisateurs d'accéder à des ressources informatiques
Les deux me vont

2023-08-11 12:33 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +Le cloud computing, ou informatique en nuage, offre des ressources informatiques telles que de la puissance de calcul,
les quebequois ont vraiment des mots rigolos :) c'est fait

2023-08-11 12:33 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +situées dans un emplacement physique distant. nous différencions généralement le cloud privé du cloud public,
bien vu

2023-08-11 12:34 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +Les organisations avaient traditionnellement deux solutions lorsqu'elles voulaient accroitre leur capacité de calcul.
Ok, ça me va

2023-08-11 12:35 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +Et deuxièmement, elles peuvent simplement se [mettre à l’échelle] (/scalability/) souhaitée à la demande, en fonctions de leurs besoins.
J'ai fait un tout petit peu different, dites moi si ça va: Et deuxièmement, elles peuvent simplement réaliser une [mise à l'échelle ] (/scalability/) de leur infrastructure à la demande, en fonctions de leurs besoins

2023-08-11 12:35 UTC, guillaumebernard84 commented on content/fr/cloud-computing.md
> +Le cloud computing permet aux organisations d'adopter autant ou aussi peu d'infrastructure qu'elles le souhaitent.
oui, c'est plus français

2023-08-11 15:37 UTC, sestegra approved these changes
LGTM 🚀

2023-08-11 16:01 UTC, huats approved these changes
GREAT ! Thanks for your work !

2023-08-11 16:01 UTC, merged