Localize continuous integration #1650
cncf/glossary pull request #2287
Opened 2023-08-11 15:39 UTC by matteobisi

### Describe your changes
localizzato continuous integration

### Related issue number or link (ex: `resolves #issue-number`)
#1650 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-08-24 08:48 UTC, annalisag-spark approved these changes

2023-08-28 10:08 UTC, ugho16 requested changes

2023-08-28 10:08 UTC, ugho16 commented on content/it/continuous-integration.md
> +in produzione valido.
```suggestion
Il processo di CI consente ai team di software di identificare chiaramente ogni commit di codice come un fallimento o come un valido candidato
 al rilascio in produzione.
```

2023-08-28 10:08 UTC, ugho16 commented on content/it/continuous-integration.md
> +gli sviluppatori potrebbero apportare modifiche in conflitto e inavvertitamente rompere il lavoro l'uno dell'altro.
```suggestion
gli sviluppatori potrebbero apportare modifiche in conflitto e danneggiare inavvertitamente il lavoro l'uno dell'altro.
```

2023-09-04 09:22 UTC, ugho16 approved these changes

2023-09-04 09:23 UTC, merged