Localize Cloud Native Security in french
cncf/glossary pull request #2316
Opened 2023-08-19 15:41 UTC by Krast76

Localize Cloud Native Security into French. Close #2289

2023-08-19 17:33 UTC, sestegra requested changes

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +tags: ["securité", "", ""]
Il manque un accent sur le premier "e" => "sécurité"

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +La sécurité Cloud Native vise à garantir les mêmes standards que les modèles de sécurités traditionnel tout en s'adaptant aux particularités des environnements Cloud Natives, comme les infrastructure
je pense que "les modèles de sécurité traditionnels" est plus juste.
Le "de" ici spécifie le type de modèle dont on parle, donc pas de pluriel.

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les modèles de sécurités traditionnels ont été conçu avec des hypothèses qui ne sont aujourd'hui plus valide.
Idem ici "les modèles de sécurité traditionnels"
De plus, "conçus" et "valides" s'accordent avec "les modèles".

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +La sécurité Cloud Native est hautement liée à la pratique du [DevSecOps](/devsecops/)
Lors de la navigation dens l'espace Français, pour garder l'utilisateur dans l'espace, il faut ajouter le préfixe "/fr" sur les liens.
`[DevSecOps](/fr/devsecops/)`

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les applications Cloud Natives changent fréquemment, utilises beaucoup d'outils et de bibliothèque open source, elles tournent dans des infrastructures souvent contrôlés par un revendeur et elles son
- s/utilises/utilisent/
- Il manque un "s" à "bibliothèques"
- Il manque l'accord féminin dans "des infrastructures souvent contrôlées"

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les revues de code, les longs cycles d'assurance qualité, l'analyse des vulnérabilités des hôtes, et les révisions de sécurités de dernière minute ne se mettent pas à l'échelle avec les applications
Même remarque que précédemment, je pense que "les révisions de sécurité" (sans "s") est plus juste.

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les pipelines de livraison de code ont intégré les outils qui analyse le code pour détecter des vulnérabilités avant que celui-ci soit compilé.
Il manque l'accord à "les outils qui analysent".

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les bibliothèques open source sont récupérées depuis des sources de confiance qui monitore leurs vulnérabilités.
Il manque l'accord à "des sources de confiance qui monitorent"

2023-08-19 17:33 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Au lieu de ralentir le changement le modèle de sécurité Cloud Native l'adopte
Une virgule me semble requise après changement:
"Au lieu de ralentir le changement, le modèle de sécurité"

2023-08-22 19:02 UTC, sestegra commented on content/fr/cloud-native-security.md
> +en migrant depuis les modèles de sécurités traditionnels vers un modèle ou la sécurité est impliqué dans chaque étape du cycle de livraison.
"modèle de sécurité" sans s

2023-08-23 19:04 UTC, guillaumebernard84 commented on content/fr/cloud-native-security.md
> +La sécurité Cloud Native vise à garantir les mêmes standards que les modèles de sécurité traditionnels tout en s'adaptant aux particularités des environnements Cloud Natives, comme les infrastructure
Moi j'aurais mis fréquentes avec un s, mais comme Stéphane l'a laissé passé, j'ai un doute 😁

2023-08-23 19:04 UTC, guillaumebernard84 commented on content/fr/cloud-native-security.md
> +en mettant à jour les composants vulnérables fréquemment ou en s'assurant que l'infrastructure est remplacée régulièrement.
J'aurais dit "en s'assurant que l'infrastructure soit remplacée régulièrement."
mais comme Stéphane l'a laissé passé, j'ai un doute 😁

2023-08-23 19:08 UTC, sestegra commented on content/fr/cloud-native-security.md
> +La sécurité Cloud Native vise à garantir les mêmes standards que les modèles de sécurité traditionnels tout en s'adaptant aux particularités des environnements Cloud Natives, comme les infrastructure
Bien vu, il faut bien un "s" à fréquentes.

2023-08-23 19:12 UTC, sestegra commented on content/fr/cloud-native-security.md
> +en mettant à jour les composants vulnérables fréquemment ou en s'assurant que l'infrastructure est remplacée régulièrement.
J'ai hésité aussi, mais il y une différence subtile entre les deux versions:

"en s'assurant que l'infrastructure est remplacée régulièrement"
Ici, l'action de remplacement est présentée comme un fait réel. Cela implique que l'infrastructure est effectivement et activement remplacée de manière régulière.

"ou en s'assurant que l'infrastructure soit remplacée régulièrement"
L'utilisation du subjonctif "soit" suggère une action souhaitée ou potentielle mais pas nécessairement réalisée.
Il y a une nuance d'incertitude ou de désir que cela se produise, mais ce n'est pas présenté comme un fait établi.

2023-08-23 19:14 UTC, sestegra commented on content/fr/cloud-native-security.md
> +en migrant depuis les modèle de sécurité traditionnels vers un modèle ou la sécurité est impliqué dans chaque étape du cycle de livraison.
Il manque un "s" à modèle.

2023-08-28 20:28 UTC, guillaumebernard84 commented
LGTM 🚀

2023-09-18 17:32 UTC, guillaumebernard84 approved these changes
Je réintére mon LGTM 🚀 , mais en tant  que vrai approver cette fois ci 😀

2023-09-20 06:19 UTC, sestegra requested changes

2023-09-20 06:19 UTC, sestegra commented on content/fr/cloud-native-security.md
> +La sécurité Cloud Native est une approche qui intègre la sécurité dans les [applications Cloud Natives](/cloud-native-apps/).
Il manque le "/fr" dans le lien

2023-09-20 06:19 UTC, sestegra commented on content/fr/cloud-native-security.md
> +en migrant depuis les modèle de sécurité traditionnels vers un modèles ou la sécurité est impliqué dans chaque étape du cycle de livraison.
- Il manque un 's' ici: "les modèles"
- Un "s" en trop ici: "un modèle"
- Il manque un "e" ici: "la sécurité est impliquée"

2023-09-20 06:19 UTC, sestegra commented on content/fr/cloud-native-security.md
> +Les audits et vérifications manuels sont remplacés par des analyses automatisées.
* Je pense que "manuel" s'appliquent aux vérifications, l'accord est féminin pluriel "vérifications manuelles"

2023-09-23 14:49 UTC, Krast76 commented
@sestegra Done ! J'en ai profité pour squash + rebase

2023-09-24 09:18 UTC, sestegra approved these changes

2023-09-24 09:18 UTC, merged