Improve the transaltion for "How it helps" for Traditional Chinese
cncf/glossary pull request #2318
Opened 2023-08-20 00:23 UTC by johnlinp

### Describe your changes

The current translation for "How it helps" is "如何幫助". However, I don't think it's something we would say in Taiwan. After discussion on Slack, we proposed to change it into "如何幫助我們".

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-08-20 03:47 UTC, hwchiu approved these changes

2023-08-20 06:45 UTC, pichuang requested changes
Require DCO (Developer's Certificate of Origin)

2023-08-20 08:05 UTC, ydFu commented
After reviewing the contents, the following files have been synchronized upstream in English,LGTM.
```
content/zh-tw/canary-deployment.md
content/zh-tw/cloud-computing.md
content/zh-tw/cloud-native-tech.md
content/zh-tw/cluster.md
content/zh-tw/container-orchestration.md
content/zh-tw/container.md
content/zh-tw/continuous-delivery.md
content/zh-tw/continuous-integration.md
content/zh-tw/devops.md
content/zh-tw/devsecops.md
content/zh-tw/function-as-a-service.md
content/zh-tw/pod.md
content/zh-tw/service-mesh.md
content/zh-tw/shift-left.md
content/zh-tw/zero-trust-architecture.md
```

The content of these two documents, because the English upstream has been updated, so they are not fully synchronized.
The content of this change will make future updates unable to use the dev-tw branch to compare the change time of the main branch and then track it.
```
content/zh-tw/style-guide/_index.md
```
It is suggested that the above two files should not be updated in this PR, and the PR should be submitted separately so that the review can focus

2023-08-21 08:21 UTC, pichuang approved these changes
LGTM

2023-08-21 09:06 UTC, merged