[FR] Localize `Continuous Integration`
cncf/glossary pull request #2336
Opened 2023-08-28 20:45 UTC by guillaumebernard84

### Describe your changes
Localize `Continuous Integration` to french

### Related issue number or link (ex: `resolves #issue-number`)
solves https://github.com/cncf/glossary/issues/2292

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-20 07:18 UTC, sestegra requested changes

2023-09-20 07:18 UTC, sestegra commented on content/fr/continuous-integration.md
> +ces développeurs peuvent apporter des modifications contradictoires et, par inadvertance, se causer les uns les autres des problémes.
Typo "problèmes"

2023-09-20 07:18 UTC, sestegra commented on content/fr/continuous-integration.md
> +Traditionnellement, le processus CI commence lorsque les modifications du code sont envoyées dans un système de contrôle de code source (Git, Mercurial ou Subversion).
Je propose "de code" au lieu "du code" qui est plus général.

2023-09-20 07:18 UTC, sestegra commented on content/fr/continuous-integration.md
> +Traditionnellement, le processus CI commence lorsque les modifications du code sont envoyées dans un système de contrôle de code source (Git, Mercurial ou Subversion).
Typo: une virgule à la place du point "(Git, Mercurial ou Subversion),"

2023-09-20 07:18 UTC, sestegra commented on content/fr/continuous-integration.md
> +Le logiciel CI vérifie automatiquement que les modifications de code sont fusionées proprement chaque fois qu'un développeur soumet une modification.
Je propose "Le logiciel de CI"

2023-09-22 19:25 UTC, guillaumebernard84 commented on content/fr/continuous-integration.md
> +Traditionnellement, le processus CI commence lorsque les modifications du code sont envoyées dans un système de contrôle de code source (Git, Mercurial ou Subversion).
Tu as raison, c'est mieux

2023-09-26 06:17 UTC, sestegra approved these changes
LGTM 🚀

2023-10-01 15:49 UTC, Krast76 approved these changes
LGTM 🚀

2023-10-01 15:49 UTC, merged