localization of IaaS FR
cncf/glossary pull request #2339
Opened 2023-08-30 16:45 UTC by pmilaneo

### Describe your changes
IaaS french translation

### Related issue number or link (ex: `resolves #issue-number`)
Issue resolved #2276 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-06 15:55 UTC, guillaumebernard84 commented on content/fr/IaaS.md
> +L'infrastructure en tant que service, ou IaaS, est un modèle de service de cloud computing qui offre des ressources physiques ou virtualisées de calcul, de stockage et de réseau à la demande selon un
J'aurais mis IaaS en toutes lettres:
L'infrastructure en tant que service, ou Infrastructure as a Service (IaaS) en anglais,

2023-09-06 18:32 UTC, guillaumebernard84 commented on content/fr/IaaS.md
> +Dans les configurations traditionnelles sur site, les organisations ont souvent du mal à utiliser efficacement les ressources informatiques. Les centres de données doivent être construits pour répond
Dans nos autres traductions, on essaie d'éviter au maximum l'anglicisme scalabilité. Je te propose:
Cette incapacité de mise à l'échelle entraîne une augmentation des coûts et une utilisation inefficace des ressources.
Qu'en pensent les autres?

2023-09-06 18:32 UTC, guillaumebernard84 commented on content/fr/IaaS.md
> +Avec l'IaaS, les entreprises peuvent éviter d'acheter et de maintenir l'espace de calcul et le centre de données pour leurs applications. Une infrastructure à la demande leur permet de louer des ress
l'espace de calcul ==> j'aurais plutôt dit la capacité de calcul

2023-09-10 11:43 UTC, sestegra commented on content/fr/IaaS.md
> +Dans les configurations traditionnelles sur site, les organisations ont souvent du mal à utiliser efficacement les ressources informatiques. Les centres de données doivent être construits pour répond
@pmilaneo Effectivement, sur ce point, le groupe a déjà discuté.
Ainsi, "Scalabilité" a été traduit en "capacité de mise à l'échelle".
Voir la traduction ici: https://github.com/cncf/glossary/blob/dev-fr/content/fr/scalability.md

2023-09-11 18:25 UTC, guillaumebernard84 commented on content/fr/IaaS.md
> +L'infrastructure en tant que service, ou Infrastructure as a Service (IaaS) en anglais, est un modèle de service de cloud computing qui offre des ressources physiques ou virtualisées de calcul, de st
Merci pour tes corrections 😀 
Par contre tu as oublié de sauter des lignes 😆 
A part ça tout m'a l'air bon 🚀

2023-09-20 07:40 UTC, sestegra requested changes

2023-09-20 07:40 UTC, sestegra commented on content/fr/IaaS.md
> +tags: [""]
Les tags sont manquants
"tags: ["infrastructure", "méthodologie", ""]

2023-09-20 08:56 UTC, pmilaneo commented on content/fr/IaaS.md
> +tags: [""]
Merci, j'ai modifié. J'ai enlevé le double quote à la fin mais si c'est utile, je peux le remettre

2023-09-22 19:28 UTC, guillaumebernard84 commented on content/fr/IaaS.md
> +tags: [""]
il me semble qu'il faut toujours 3 tags. je t'avoue que je ne sais pas si il s'agit d'une problématique technique ou uniquement de style.

2023-09-25 07:11 UTC, pmilaneo commented on content/fr/IaaS.md
> +tags: [""]
Ok, c'est rajouté!

2023-09-25 18:00 UTC, guillaumebernard84 approved these changes
LGTM 🚀

2023-09-25 18:00 UTC, merged