Add cloud native tech
cncf/glossary pull request #2344
Opened 2023-09-01 07:24 UTC by symys

### Describe your changes
Localize "Cloud Native Tech" page into Turkish

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-01 20:38 UTC, halil-bugol submitted a review, later dismissed
lgtm

2023-09-01 20:40 UTC, halil-bugol reviewed
DCO aktif görünmüyor kontrol eder misin @symys PR'ı imzalaman gerekiyor.

2023-09-03 12:02 UTC, symys commented
I fixed the DCO issue, can you check again?

2023-09-03 12:11 UTC, aliok approved these changes
Thanks! LGTM!

2023-09-03 12:12 UTC, aliok commented
Preview looks fine: https://deploy-preview-2344--cncfglossary.netlify.app/tr/cloud-native-tech/

2023-09-03 12:16 UTC, aliok commented on content/tr/cloud-native-tech.md
> +## Hangi sorunu çözer
```suggestion
## Hangi Sorunları Çözer
```

We used this header in https://deploy-preview-2344--cncfglossary.netlify.app/tr/cloud-computing/.

Let's use the same for consistency.

2023-09-03 12:16 UTC, aliok commented on content/tr/cloud-native-tech.md
> +## Sorunu nasıl çözer
```suggestion
## Nasıl Yardımcı Olur
```

We used this header in https://deploy-preview-2344--cncfglossary.netlify.app/tr/cloud-computing/.

Let's use the same for consistency.

2023-09-03 12:16 UTC, aliok requested changes
Just noticed some things that I would prefer to have changed.

2023-09-03 12:34 UTC, aliok approved these changes
LGTM!

2023-09-03 15:16 UTC, halil-bugol approved these changes
lgtm

2023-09-03 15:16 UTC, merged