[es] Localize role-based-access-control (RBAC) #2186
cncf/glossary pull request #2346
Opened 2023-09-01 22:16 UTC by franciscorodriguezsv24

### Describe your changes
Localize the document `content/en/role-based-access-control.md` to spanish
 

### Related issue number or link (ex: `resolves #issue-number`)
resolve #2186

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-03 21:13 UTC, ramrodo approved these changes
Thanks! @franciscorodriguezsv24.
Congrats on your first contribution!
/lgtm

2023-09-03 22:11 UTC, franciscorodriguezsv24 commented
Thanks, It's only the first step of this great great world  🙌

El dom., 3 de septiembre de 2023 3:13 p. m., Rodolfo Martínez Vega <
***@***.***> escribió:

> ***@***.**** approved this pull request.
>
> Thanks! @franciscorodriguezsv24
> <https://github.com/franciscorodriguezsv24>.
> Congrats on your first contribution!
> /lgtm
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/cncf/glossary/pull/2346#pullrequestreview-1608578956>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYWO4UP54OK744KCOR7TD4LXYTXJDANCNFSM6AAAAAA4IDXB3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-03 23:30 UTC, electrocucaracha requested changes
Muchas gracias por tu contribución, he dejado una pequeña observación para que quede igual que el resto de los documentos

2023-09-03 23:30 UTC, electrocucaracha commented on content/es/role-based-access-control.md
> +category: concepto
```suggestion
category: Concepto
```

2023-09-05 16:02 UTC, electrocucaracha approved these changes

2023-09-05 16:17 UTC, ramrodo commented
@franciscorodriguezsv24 se nos pasó comentarte que tu branch de tu PR debe ser cortado y ser apuntado a `dev-es`. ¿Puedes crear otro PR con tus cambios pero creando una rama desde `dev-es`?

Lo puedes hacer con los sig. comandos:

```
$ git checkout dev-es
$ git checkout -b <nueva-rama-desde-dev-es>
```

Y colocar tu cambio/traducción aquí.

Si tienes dudas, avísanos por aquí o por Slack.

2023-09-05 16:48 UTC, franciscorodriguezsv24 commented
Perfecto, hoy por la tarde estare trabajando en ello, Gracias !

2023-09-06 03:27 UTC, closed without merging