[es] Localize role-based-access-control (RBAC) #2186
cncf/glossary pull request #2354
Opened 2023-09-06 03:46 UTC by franciscorodriguezsv24

### Describe your changes
Localize the document content/en/role-based-access-control.md to spanish

### Related issue number or link (ex: `resolves #issue-number`)
resolve https://github.com/cncf/glossary/issues/2186

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-06 04:36 UTC, electrocucaracha commented on content/es/role-based-access-control.md
> +category: concepto
```suggestion
category: Concepto
```

2023-09-06 14:28 UTC, ramrodo requested changes
Mismo comentario de Vïctor. Cambiar a `Concepto`

2023-09-07 18:42 UTC, electrocucaracha commented
Parece ser que va a ser necesario agregar [RBAC](https://github.com/cncf/glossary/actions/runs/6092516128/job/16531299895?pr=2354#step:5:31) en el [wordlist ](https://github.com/cncf/glossary/blob/main/content/es/.wordlist.txt) para evitar que el Spellchecker falle

2023-09-08 22:22 UTC, franciscorodriguezsv24 commented
ok, voy a cerrar este pull request y voy a mandar uno con todos los cambios

2023-09-08 22:22 UTC, closed without merging