Localize ebpf #2334
cncf/glossary pull request #2361
Opened 2023-09-07 15:02 UTC by matteobisi

### Describe your changes
ebpf it localization

### Related issue number or link (ex: `resolves #issue-number`)
#2334 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-02 15:50 UTC, ugho16 requested changes

2023-10-02 15:50 UTC, ugho16 commented on content/it/ebpf.md
> +in cui i sviluppatori richiedono una maggiore privilegi per l'accesso al sistema a basso livello.
```suggestion
in cui gli sviluppatori richiedono una maggiore flessibilità per l'accesso al sistema a basso livello. 
```

2023-10-03 05:59 UTC, annalisag-spark approved these changes

2023-10-03 07:01 UTC, ugho16 approved these changes

2023-10-03 07:01 UTC, merged