[FR] Localize `Continuous Delivery` to French
cncf/glossary pull request #2371
Opened 2023-09-10 19:32 UTC by guillaumebernard84

### Describe your changes
[FR] Localize `Continuous Delivery` to French

### Related issue number or link (ex: `resolves #issue-number`)
Solves https://github.com/cncf/glossary/issues/2290

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-10 19:38 UTC, guillaumebernard84 commented on content/fr/continuous-delivery.md
> +En règle générale, le développement basé sur le tronc est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités ou aux demandes d'extraction.
Que pensez vous de cette phrase? Pour moi, elle s'adresse a des développeurs qui ont déjà réfléchit a leur workflow git, et sont donc très probablement déjà bien au fait de ce qu’est la CI/CD/CD.
Je ferais bien une PR pour la faire sauter de la VO.
Dite moi ce que vous en pensez

2023-09-20 07:03 UTC, sestegra requested changes

2023-09-20 07:03 UTC, sestegra commented on content/fr/continuous-delivery.md
> +En règle générale, le développement basé sur le tronc est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités ou aux demandes d'extraction.
Ici, les termes anglais sont beaucoup utilisés, je les laisserai entre parenthèses et je trouve "propositions de révision" mieux pour PR.
"En règle générale, le développement basé sur le tronc (trunk-based development) est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités (feature branching) ou aux propositions de révision (pull requests)."

2023-09-22 19:42 UTC, guillaumebernard84 commented on content/fr/continuous-delivery.md
> +En règle générale, le développement basé sur le tronc est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités ou aux demandes d'extraction.
ça je sais bien! Ce que je voulais dire, c'est qu'il me parait improbable de savoir ce que veux dire "développement basé sur le tronc " si on ne sais pas ce que veut dire "livraison continue".
Et au contraire, si on sais ce que veux dire "développement basé sur le tronc ", c'est qu'on déja réfléchi a sa CI/CD, et qu'on ne va donc pas lire le glossaire 😁 
En tout cas ça ne me géne pas de le laisser, je trouve juste ça un peu incongru.
Peut etre que la bonne solution serais de proposer "trunk-based development" en tant que nouveau terme dans la VO, et de faire un lien vers cette nouvelle définition ?

2023-09-26 06:34 UTC, sestegra commented on content/fr/continuous-delivery.md
> +En règle générale, le développement basé sur le tronc est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités ou aux demandes d'extraction.
Ok, je comprends ce que tu veux dire.
Ce nouveau terme peut être intéressant à définir, de même pour feature branching.

2023-09-26 06:34 UTC, sestegra approved these changes
LGTM 🚀

2023-09-28 18:55 UTC, guillaumebernard84 commented on content/fr/continuous-delivery.md
> +En règle générale, le développement basé sur le tronc est utilisé dans les stratégies CD, par opposition aux branches de fonctionnalités ou aux demandes d'extraction.
En fait ça a déja été demandé, et refusé. Du coup j'ai fait une demande d'update term sur Continuous Delivery
https://github.com/cncf/glossary/issues/2433

2023-10-15 15:22 UTC, Krast76 commented on content/fr/continuous-delivery.md
> +title: Livraison Continue (CD)
Même commentaire que pour Continuous Deployment

2023-11-08 17:09 UTC, Krast76 approved these changes
LGTM 🚀

2023-11-08 17:09 UTC, merged