Localize runtime #2335
cncf/glossary pull request #2374
Opened 2023-09-11 13:31 UTC by matteobisi

### Describe your changes
localize Runtime IT

### Related issue number or link (ex: `resolves #issue-number`)
#2335 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-02 15:56 UTC, ugho16 requested changes

2023-10-02 15:56 UTC, ugho16 commented on content/it/runtime.md
> +gestiscono le risorse hardware occupandosi di tutte queste azioni a livello di sistema operativo, come allocazione e isolamento delle risorse.
```suggestion

- definisce come vengono specificate le immagini del container e come il runtime può recuperarle;
- gestisce come queste immagini vengono decompresse, stratificate, montate ed eseguite;
- gestisce le risorse hardware occupandosi di tutte queste azioni a livello di sistema operativo, come allocazione e isolamento delle risorse.

```

2023-10-02 15:56 UTC, ugho16 commented on content/it/runtime.md
> +Nel tempo, diversi implementazioni di container runtime hanno continuato ad evolversi, portando alla Specifica OCI, che è diventata lo standard per i runtime dei container.
```suggestion
Nel tempo, diverse implementazioni di container runtime hanno continuato ad evolversi, portando alla Specifica OCI, che è diventata lo standard per i runtime dei container.
```

2023-10-02 15:56 UTC, ugho16 commented on content/it/runtime.md
> +I container runtime sono un componente necessario degli orchestratori di container come Kubernetes.
```suggestion
I container runtime sono un componente necessario degli orchestratori di container come [Kubernetes](/it/kubernetes). 
```

2023-10-02 15:56 UTC, ugho16 commented on content/it/runtime.md
> +I container runtime sono un componente necessario degli orchestratori di container come Kubernetes.
Non c'è nell'originale ma secondo me ci sta bene

2023-10-03 05:55 UTC, annalisag-spark requested changes

2023-10-03 05:55 UTC, annalisag-spark commented on content/it/runtime.md
> +È un'[astrazione](/it/abstraction/) del sistema operativo sottostante che traduce i comandi del programma in azioni relative per il sistema operativo.
```suggestion
È un'[astrazione](/it/abstraction/) del sistema operativo sottostante che traduce i comandi del programma in azioni corrispondenti perché siano utili al sistema operativo stesso.
```

2023-10-03 05:55 UTC, annalisag-spark commented on content/it/runtime.md
> +Nel contesto [cloud native](/it/cloud-native-apps/), per _runtime_ si intende container runtime.
```suggestion
Nel contesto [cloud native](/it/cloud-native-apps/), il termine runtime si riferisce generalmente al runtime dei container. 
```

2023-10-03 05:55 UTC, annalisag-spark commented on content/it/runtime.md
> +Senza l'astrazione di un runtime del container, l'applicazione dovrebbe occuparsi di tutte le meccaniche di ciascun sistema operativo, aumentando la complessità dell'esecuzione dell'app.
```suggestion
Senza l'astrazione di un runtime del container, l'applicazione dovrebbe occuparsi di tutte le meccaniche di ciascun sistema operativo, aumentando la complessità dell'esecuzione dell'applicazione.
```

2023-10-03 07:02 UTC, ugho16 approved these changes

2023-10-03 07:11 UTC, annalisag-spark approved these changes

2023-10-03 07:14 UTC, merged