Create zero-trust-architecture.md
cncf/glossary pull request #2400
Opened 2023-09-15 16:11 UTC by ARYANis0001

### Describe your changes
Zero-trust-architecture.md file for /hi localization

### Related issue number or link (#2326)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-15 16:14 UTC, ARYANis0001 commented
Reviewers Please look on this PR

2023-10-06 18:09 UTC, aj11anuj requested changes
Some suggestions from my side

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +टैग: ["सुरक्षा", "", ""]
```suggestion
title: जीरो ट्रस्ट आर्किटेक्चर (Zero Trust Architecture)
status: पूर्ण
category: संकल्पना
tags: ["सुरक्षा", "", ""]
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +जीरो ट्रस्ट आर्किटेक्चर आईटी सिस्टम के डिजाइन और कार्यान्वयन के लिए एक दृष्टिकोण निर्धारित करता है
```suggestion
'जीरो ट्रस्ट आर्किटेक्चर' आई-टी सिस्टम के डिजाइन और कार्यान्वयन के लिए एक दृष्टिकोण निर्धारित करता है
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +जहां भरोसा पूरी तरह से खत्म हो जाता है.
```suggestion
जहां भरोसा पूरी तरह से खत्म हो जाता है।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +मूल सिद्धांत है "कभी भरोसा मत करो, हमेशा सत्यापित करो", डिवाइस या सिस्टम स्वयं,
```suggestion
मूल सिद्धांत यह है की डिवाइस हो या सिस्टम "कभी भरोसा मत करो, हमेशा स्वयं पुष्टि करो"। 
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +सिस्टम के अन्य घटकों से संचार करते समय, ऐसा करने से पहले हमेशा स्वयं को सत्यापित करें।
```suggestion
सिस्टम के अन्य घटकों से संचार करते समय, ऐसा करने से पहले हमेशा स्वयं पुष्टि करें।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +किसी भी संचार से पहले सिस्टम के घटकों को पहले सत्यापन से गुजरना पड़ता है।
```suggestion
आज कई नेटवर्कों में, कंपनी के नेटवर्क के भीतर, सिस्टम और डिवाइस एक-दूसरे के साथ स्वतंत्र रूप से संचार कर सकते हैं, 
क्योंकि वे कंपनी के नेटवर्क परिधि की विश्वसनीय सीमा के भीतर हैं। 
जीरो ट्रस्ट आर्किटेक्चर विपरीत दृष्टिकोण अपनाता है, हालांकि नेटवर्क परिधि के अंदर,
किसी भी संचार से पहले सिस्टम के घटकों को पहले जाँच से गुजरना पड़ता है।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +धारणा यह है कि चूँकि विश्वास है, इसलिए कोई समस्या नहीं है।
```suggestion
पारंपरिक विश्वास आधारित दृष्टिकोण के साथ जहां सिस्टम और उपकरण कंपनी के नेटवर्क परिधि के भीतर मौजूद होते हैं,
धारणा यह है कि "चूँकि विश्वास है, इसलिए कोई समस्या नहीं है"।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +हालाँकि, शून्य विश्वास वास्तुकला यह मानती है कि विश्वास एक भेद्यता है।
```suggestion
हालाँकि, जीरो ट्रस्ट आर्किटेक्चर यह मानती है कि विश्वास एक भेद्यता है।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +सिस्टम अब हमले के प्रति संवेदनशील है
```suggestion
उस उपकरण को दिए गए विश्वास और पहुंच के स्तर पर निर्भर करता है कि,
सिस्टम अब हमले के प्रति कितना संवेदनशील है।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +क्योंकि एक हमलावर को अब पूरे सिस्टम में आगे जाने से पहले सत्यापित करने के लिए मजबूर किया जाता है।
```suggestion
जीरो ट्रस्ट आर्किटेक्चर में, विश्वास को हटा दिया जाता है, जिससे हमले की सतह कम हो जाती है
क्योंकि एक हमलावर को अब पूरे सिस्टम में आगे जाने से पहले जाँच करने के लिए मजबूर किया जाता है।
```

2023-10-06 18:09 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +एक हमलावर को सिस्टम के अन्य क्षेत्रों तक पहुंच प्राप्त करने के लिए इससे गुजरना पड़ता है।
```suggestion
जीरो ट्रस्ट आर्किटेक्चर को अपनाने से बढ़ी हुई सुरक्षा का मुख्य लाभ यह मिलता है कि, 
हमले की सतह में कमी के साथ 
आपके कंपनी के सिस्टम से भरोसा हटाने से अब सुरक्षा द्वारों की संख्या और ताकत दोनों बढ़ जाती है। 
एक हमलावर को सिस्टम के अन्य क्षेत्रों तक पहुंच प्राप्त करने के लिए इससे गुजरना पड़ता है।
```

2023-11-08 18:52 UTC, kumarankit999 reviewed
Please Improve this PR, as suggested by @aj11anuj

2023-11-09 02:40 UTC, ARYANis0001 commented
Sure

2023-11-09 02:40 UTC, ARYANis0001 commented
I will improve

2023-11-09 03:04 UTC, ARYANis0001 reviewed
Updated

2023-11-09 06:40 UTC, ARYANis0001 commented
Please review this I have made the changes

2023-11-09 07:43 UTC, aj11anuj requested changes
Apart from these minor suggestions, rest of the things looks good to me 👍

2023-11-09 07:43 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +status: पूर्ण
```suggestion
status: completed
```

2023-11-09 07:43 UTC, aj11anuj commented on content/hi/content/en/zero-trust-architecture.md
> +category: संकल्पना
```suggestion
category: concept
```

2023-11-09 08:02 UTC, ARYANis0001 reviewed
Updated

2023-11-09 08:02 UTC, ARYANis0001 commented
Please review this I have made the changes

2023-11-09 08:07 UTC, kumarankit999 reviewed
lgtm if you have gone through @aj11anuj Review!

2023-11-12 05:41 UTC, aj11anuj approved these changes
Lgtm 👍

2023-11-14 15:34 UTC, kumarankit999 reviewed
looks good now!

2023-11-14 15:34 UTC, kumarankit999 approved these changes
lgtm

2023-11-14 15:36 UTC, ARYANis0001 commented
@kumarankit999 how i can contact to you

2023-11-14 16:30 UTC, ARYANis0001 commented
ok wait

2023-11-15 01:32 UTC, ARYANis0001 commented
@aj11anuj  I have changed the branch to cncf dev-hi

2023-11-15 04:02 UTC, aj11anuj reviewed
I just noticed it, Location of this file "content/hi/content/en/zero-trust-architecture.md" doesn't exist. It should be "content/hi/zero-trust-architecture.md". And due to recent sync of dev-hi branch with main branch since a long time, some issues are arising like this one- "Zero-trust-architecture file already exists". So, now we cannot accept this one. Sorry for this inconvenience.

2023-11-15 04:03 UTC, closed without merging

2023-11-15 04:06 UTC, ARYANis0001 commented
Ok ki will close this