localize-Container-Orchestration-#1648
cncf/glossary pull request #2417
Opened 2023-09-18 14:25 UTC by SaraTrap

### Describe your changes
localize it Container-Orchestration

### Related issue number or link (ex: `resolves #issue-number`)
#1648 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-27 14:38 UTC, ugho16 requested changes

2023-09-27 14:38 UTC, ugho16 commented on content/it/container-orchestration.md
> +Per orchestrazione dei [Container](/it/container/) si intende la gestione e l'automatizzazione, in ambienti dinamici, del ciclo di vita delle applicazioni containerizzate.
```suggestion
Per orchestrazione dei [Container](/it/container/) si intende la gestione e l'automatizzazione del ciclo di vita delle applicazioni containerizzate in ambienti dinamici.
```

2023-09-27 14:38 UTC, ugho16 commented on content/it/container-orchestration.md
> +L'orchestrazione dei container viene effettuata tramite l'utilizzo di un orchestratore di container (nella maggior parte dei casi, [Kubernetes](/it/kubernetes)), che consente di eseguire i processi d
```suggestion
L'orchestrazione dei container viene effettuata tramite l'utilizzo di un orchestratore di container (nella maggior parte dei casi [Kubernetes](/it/kubernetes)), che consente di eseguire i processi di deployement, (auto)scaling, auto-healing e monitoraggio.
```

2023-10-03 07:56 UTC, annalisag-spark requested changes

2023-10-03 07:56 UTC, annalisag-spark commented on content/it/container-orchestration.md
> +Per orchestrazione dei [Container](/it/container/) si intende la gestione e l'automatizzazione del ciclo di vita delle applicazioni containerizzate in ambienti dinamici.
```suggestion
Per orchestrazione dei [Container](/it/container/) si intende la gestione e l'automazione del ciclo di vita delle applicazioni containerizzate in ambienti dinamici.
```

2023-10-03 10:28 UTC, ugho16 approved these changes

2023-10-12 17:07 UTC, sistella commented on content/it/container-orchestration.md
> +L'orchestrazione dei container viene effettuata tramite l'utilizzo di un orchestratore di container (nella maggior parte dei casi [Kubernetes](/it/kubernetes)), che consente di eseguire i processi di
In una riunione moooolto vecchia (vedi [qui](https://docs.google.com/document/d/1g4__gy--tB79UH_KMcWFNbJpPQQUhlVpqnKKGGndOZU/edit#bookmark=id.bxndpdwsldp0)), si era deciso di lasciare i termini inglesi, dove si ritenesse necessario, ma con una traduzione in italiano tra parentesi. Qui secondo me è utile tenere i termini inglesi, ma anche una traduzione in Italiano tra parentesi credo farebbe bene.  che ne dici
```suggestion
L'orchestrazione dei container viene effettuata tramite l'utilizzo di un orchestratore di container (nella maggior parte dei casi [Kubernetes](/it/kubernetes)), che consente di eseguire i processi di deployment (distribuzione), (auto)scaling (scalabilità), auto-healing (riparazione) e monitoraggio.
```

2023-10-12 17:09 UTC, sistella commented on content/it/container-orchestration.md
> +Per orchestrazione dei [Container](/it/container/) si intende la gestione e l'automazione del ciclo di vita delle applicazioni containerizzate in ambienti dinamici.
```suggestion
Per orchestrazione dei [container](/it/container/) si intende la gestione e l'automazione del ciclo di vita delle applicazioni containerizzate in ambienti dinamici.
```

2023-10-12 17:10 UTC, sistella commented on content/it/container-orchestration.md
> +Gestire manualmente i [microservizi](/it/microservices), la sicurezza e la comunicazione di rete su larga scala - e [sistemi distribuiti](/it/distributed-systems) in generale - è difficile, se non im
```suggestion
Gestire manualmente i [microservizi](/it/microservices), la sicurezza e la comunicazione di rete su larga scala - e i [sistemi distribuiti](/it/distributed-systems) in generale - è difficile, se non impossibile.
```

2023-10-12 17:16 UTC, sistella commented on content/it/container-orchestration.md
> +Questa automazione semplifica molte delle attività operative - altrimenti altamente manuali e complesse - dei team di engineering, tra cui il provisioning, il deployment, lo scaling (verso l'alto o v
Mi sono lanciato in una profonda traduzione verso l'italiano. Non vorrei snaturare i singoli termini ma questa parte mi pareva poco tradotta. Che ne dici?
```suggestion
Questa automazione semplifica molte delle attività operative dei team di engineering, che risulterebbero altrimenti profondamente manuali e complesse. Tra queste figurano: l'assegnazione di risorse, la distribuzione, lo scaling (sia in termini di aggiunta che di rimozione di nodi), la connettività, il bilanciamento del traffico e altre attività.
```

2023-10-13 08:22 UTC, sistella approved these changes

2023-10-13 09:21 UTC, merged