[FR] localize `DevSecOps`
cncf/glossary pull request #2419
Opened 2023-09-18 15:53 UTC by guillaumebernard84

### Describe your changes
[FR] localize `DevSecOps`

### Related issue number or link (ex: `resolves #issue-number`)
Solves https://github.com/cncf/glossary/issues/2293

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-09-20 06:36 UTC, sestegra requested changes

2023-09-20 06:36 UTC, sestegra commented on content/fr/devsecops.md
> +Il étend l'approche [DevOps](/fr/devops/) pour inclure les probélmatiques de sécurité
Typo "problématiques"

2023-09-22 19:50 UTC, guillaumebernard84 commented on content/fr/devsecops.md
> +Comme DevOps, DevSecOps est un changement culturel, poussé par les technologies adoptées, avec des méthodes d'adoption uniques.
Vous pensez quoi de ces "unique adoption methods" ? ça a un sens selon vous?

2023-09-26 06:20 UTC, sestegra commented on content/fr/devsecops.md
> +Comme DevOps, DevSecOps est un changement culturel, poussé par les technologies adoptées, avec des méthodes d'adoption uniques.
Je ne vois pas ce que cela veut dire.

2023-09-26 06:22 UTC, sestegra approved these changes
LGTM 🚀

2023-10-02 17:48 UTC, guillaumebernard84 commented on content/fr/devsecops.md
> +Comme DevOps, DevSecOps est un changement culturel, poussé par les technologies adoptées, avec des méthodes d'adoption uniques.
Si on met "des méthodes d'adoptions particulières", ça aurais plus de sens. Mais est-ce que ça aurais le même sens qu'en anglais? On atteint les limites de mon niveau d'anglais 😢

2023-10-15 15:25 UTC, Krast76 approved these changes

2023-10-15 15:25 UTC, merged