[FR] Localize Role-based Access Control (RBAC) to French
cncf/glossary pull request #2435
Opened 2023-09-28 22:59 UTC by juliafmorgado

### Describe your changes
[FR] Localize `Role-Based Access Control (RBAC)` to French
https://glossary.cncf.io/role-based-access-control/

### Related issue number or link (ex: `resolves #issue-number`)
Solves #2434

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-01 20:00 UTC, guillaumebernard84 commented on content/fr/role-based-access-control.md
> +Le RBAC confère un contrôle granulaire sur les autorisations des utilisateurs au sein des systèmes logiciels. En fonction de leurs rôles, les membres de l'équipe peuvent soit modifier une section, si
"Cette allocation précise des autorisations"
Il me semble que l'on dit plutôt "attribution" des des autorisations en français.

2023-10-02 12:09 UTC, juliafmorgado commented on content/fr/role-based-access-control.md
> +Le contrôle d'accès basé sur les rôles (RBAC) est une méthode visant à réguler l'accès aux systèmes et aux ressources en fonction des rôles attribués aux utilisateurs au sein d'une organisation. Chaq
Désolée, j'avais oublié de le faire!

2023-10-02 14:26 UTC, juliafmorgado commented on content/fr/role-based-access-control.md
> +Le RBAC simplifie le processus en offrant un contrôle d'accès préétabli basé sur des groupes de rôles.
À mon avis, les deux approches sont acceptables (mais je vais vérifier):
- On peut avoir des utilisateurs regroupés par rôles, où chaque utilisateur est associé à un ou plusieurs rôles qui déterminent leurs autorisations. 
- On peut également organiser ces rôles en groupes de rôles ("account groups") pour simplifier la gestion des autorisations.

2023-10-03 15:45 UTC, sestegra requested changes

2023-10-03 15:45 UTC, sestegra commented on content/fr/role-based-access-control.md
> +Supposons qu'une organisation compte avec 500 développeurs (utilisateurs) et 300 ressources avec différents niveaux d'autorisation (lecture, écriture et absence d'accès).
Je pense que "avec" est en trop ici.
"Supposons qu'une organisation compte 500 développeurs"

2023-10-09 14:21 UTC, juliafmorgado commented on content/fr/role-based-access-control.md
> +Le RBAC simplifie le processus en offrant un contrôle d'accès préétabli basé sur des groupes de rôles.
Alors en realité, il y a une confusion dans la VO car le mot "groupe" ici ne s'applique pas sur les roles mais sur les utilisateurs. En effet, Kubernetes definit deux objets: des roles et des rolesbindings. Un role definit un ou des verbes sur une ressource (par example un secret ou un deployment) et le rolebinding dit qui peut prendre ce role. Ce qui peut être un user ou un groupe. Il ne s'agit donc pas de regrouper des roles mais plutôt des utilisateurs.

Je vais ouvrir un PR pour changer la VO avant qu'on approuve la version française.

2023-10-25 16:30 UTC, juliafmorgado commented on content/fr/role-based-access-control.md
> +Le RBAC simplifie le processus en offrant un contrôle d'accès préétabli basé sur des groupes de rôles.
#2437 

Waiting PR review

2023-10-31 13:51 UTC, juliafmorgado commented on content/fr/role-based-access-control.md
> +Le RBAC simplifie le processus en offrant un contrôle d'accès préétabli basé sur des groupes de rôles.
PR merged into main.

2023-11-05 12:14 UTC, sestegra requested changes
LGTM except a small change in the header.

2023-11-05 12:14 UTC, sestegra commented on content/fr/role-based-access-control.md
> +tags: ["securité", "fondamental", ""]
Dans la version anglaise, seul le tag "security" est présent et il manque un accent à sécurité.
Ainsi, je propose de remplacer cette ligne par `tags: ["sécurité", "", ""]`

2023-11-26 16:42 UTC, Krast76 commented
LGTM 👍 

Waiting the fix suggested by @sestegra to approve.

2023-11-30 07:33 UTC, sestegra commented on content/fr/role-based-access-control.md
> +tags: ["securité", "fondamental", ""]
Modification effectuée

2023-11-30 07:35 UTC, sestegra approved these changes
LGTM 🚀

2023-11-30 11:09 UTC, Krast76 approved these changes
LGTM 🚀

2023-11-30 16:43 UTC, merged