Localized cloud-computing.md
cncf/glossary pull request #2441
Opened 2023-10-01 04:50 UTC by kumarankit999

Localize the Cloud Computing Part in the Hindi language

### Describe your changes
I have Localized the whole Cloud Computing file in the Hindi language

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-05 18:00 UTC, aj11anuj requested changes
Some suggestions from me

2023-10-05 18:00 UTC, aj11anuj commented on content/hi/cloud-computing.md
> +क्लाउड प्रदाता संगठनों को ऑन-डिमांड कंप्यूटिंग संसाधनों को किराए पर लेने और उपयोग के लिए भुगतान करने की अनुमति देते हैं, जिससे दो प्रमुख लाभ मिलते हैं।
```suggestion
क्लाउड के प्रदाता संगठनों को ऑन-डिमांड कंप्यूटिंग के संसाधनों को किराए पर लेने और उपयोग के लिए भुगतान करने की अनुमति देते हैं, जिससे दो प्रमुख लाभ मिलते हैं।
```

2023-10-05 18:00 UTC, aj11anuj commented on content/hi/cloud-computing.md
> +सबसे पहले, संगठन नए भौतिक बुनियादी ढांचे पर प्रतीक्षा, योजना और संसाधन खर्च किए बिना अपने उत्पाद या सेवा पर ध्यान केंद्रित कर सकते हैं। और दूसरा, वे आवश्यकतानुसार ऑन-डिमांड स्केल कर सकते हैं।
```suggestion
पहला, संगठन नए भौतिक इन्फ्रा़स्ट्रक्चर पर प्रतीक्षा, योजना और संसाधन के खर्च किए बिना अपने उत्पाद या सेवा पर ध्यान केंद्रित कर सकते हैं। और दूसरा, वे आवश्यकतानुसार ऑन-डिमांड स्केल कर सकते हैं।
```

2023-10-05 18:00 UTC, aj11anuj commented on content/hi/cloud-computing.md
> +क्लाउड कंप्यूटिंग संगठनों को आवश्यकतानुसार अधिक या कम बुनियादी ढाँचा अपनाने की अनुमति देता है।
```suggestion
क्लाउड कंप्यूटिंग संगठनों को आवश्यकतानुसार अधिक या कम इन्फ्रा़स्ट्रक्चर अपनाने की अनुमति देता है।
```

2023-10-31 17:04 UTC, kumarankit999 reviewed
Now I will do it soon.

2023-12-12 14:28 UTC, aj11anuj commented
@kumarankit999 gentle reminder to work on this PR

2023-12-12 15:33 UTC, kumarankit999 commented
Yes!

2024-02-28 11:49 UTC, aj11anuj commented
@kumarankit999 gentle ping reminder

2024-03-11 05:13 UTC, bishal7679 commented
Since this PR has no activity for a long while so closing it!
Feel free to open whenever you'd get bandwidth to work :+1:

2024-03-11 05:13 UTC, closed without merging