Localize Contributor Ladder for Japanese
cncf/glossary pull request #2442
Opened 2023-10-01 10:25 UTC by naonishijima

### Describe your changes

Localize Contributor Ladder for Japanese

Ladderの単語をどう翻訳するか迷いましたがカタカナでラダーにしました。
ご意見があればよろしくお願いします。

### Related issue number or link (ex: `resolves #issue-number`)

#2124

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-02 05:41 UTC, yuichi-nakamura commented on content/ja/contributor-ladder/_index.md
> +もしメンテナーが上記の職務に興味がなくなったり、遂行できなくなったりした場合は、名誉会員に移行する必要があります。
名誉会員、と訳していますが、名誉メンテナーのほうがいいのではないでしょうか。
https://github.com/cncf/glossary
見ますと、このステータスの人々をEmeritus Maintainers と呼んでいますので。

2023-10-02 05:42 UTC, yuichi-nakamura commented on content/ja/contributor-ladder/_index.md
> +貢献者の非自発的な解任は、責任と要求が満たされない場合に行われます。これには、度重なる活動停止、長期の活動停止、および/または行動規範違反などが含まれます。このプロセスは、コミュニティとその成果物を保護すると同時に、新しい貢献者が参入する機会を開くという意味で重要です。
非自主的 or 非自発的、はどちらかに合わせましょう

2023-10-02 07:16 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +貢献者の非自発的な解任は、責任と要求が満たされない場合に行われます。これには、度重なる活動停止、長期の活動停止、および/または行動規範違反などが含まれます。このプロセスは、コミュニティとその成果物を保護すると同時に、新しい貢献者が参入する機会を開くという意味で重要です。
レビューありがとうございます。非自主的に統一しました。

2023-10-02 07:17 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +もしメンテナーが上記の職務に興味がなくなったり、遂行できなくなったりした場合は、名誉会員に移行する必要があります。
レビューありがとうございます。名誉メンテナーに変更しました。

2023-10-02 07:39 UTC, yuichi-nakamura commented on content/ja/contributor-ladder/_index.md
> +貢献者のコミットメントレベルが変化した場合、貢献者は退任（貢献者の階段を下りること）か名誉職（プロジェクトから完全に離れる）かを検討することができます。
ここでは、「ladder」を階段と訳していて、表記ゆれです。ラダーと統一したほうがいいですね。
貢献者のラダーを下りる、についてもイマイチ分かりづらいので、「例えば、メンテナ―から承認者に貢献レベルを落とす」のように、訳注付けたほうがいいと思います。

2023-10-02 07:57 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +貢献者のコミットメントレベルが変化した場合、貢献者は退任（貢献者の階段を下りること）か名誉職（プロジェクトから完全に離れる）かを検討することができます。
もしかして「貢献者のラダー」ではなく「貢献者の地位」で統一した方がしっくりくるのでしょうか。
ladderは「はしご」以外に「地位」とも訳せます。

2023-10-02 08:58 UTC, yuichi-nakamura commented on content/ja/contributor-ladder/_index.md
> +貢献者のコミットメントレベルが変化した場合、貢献者は退任（貢献者の階段を下りること）か名誉職（プロジェクトから完全に離れる）かを検討することができます。
LFの他の文書では、OSSの貢献の段階のことをそのまま「ラダー」と訳しているため、ラダーのままのほうがいいと思います。例　https://www.linuxfoundation.jp/wp-content/uploads/2019/10/JP-Enterprise_Open_Source_-A_Practical_Introduction.pdf

2023-10-02 09:13 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +貢献者のコミットメントレベルが変化した場合、貢献者は退任（貢献者の階段を下りること）か名誉職（プロジェクトから完全に離れる）かを検討することができます。
貢献者のラダーに統一し、訳注をつけてみました。

2023-10-04 10:12 UTC, kaitoii11 requested changes

2023-10-04 10:12 UTC, kaitoii11 commented on content/ja/contributor-ladder/_index.md
> +メンテナーは、PRをマージすることもできる承認者です。誰でも用語集のメンテナーになることができます（[メンテナーになる](#メンテナーになる)を参照）。メンテナーには、以下のような期待があります：
> メンテナーは、PRをマージすることもできる承認者です。

`メンテナーもPRをマージすることができます。`
原文のalsoはおそらく承認者に加えてメンテナーもPRをマージをできるという意味かと思います。

2023-10-04 10:12 UTC, kaitoii11 commented on content/ja/contributor-ladder/_index.md
> +メンテナーになるには、まず既存のメンテナーに興味を示すことから始めましょう。既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたにメンテナーの地位を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
> 既存のメンテナーに興味を示す

細かいですが、既存のメンテナーに対して興味を示すとも読み取れてしまいます。
本来は「メンテナーになりたい」という意思表示を既存のメンテナに対してするという意味かと思います。

2023-10-04 10:12 UTC, kaitoii11 commented on content/ja/contributor-ladder/_index.md
> +用語集のコミュニティマネージャーは誰でもなることができます。コミュニティマネージャーは、貢献とローカライゼーションのプロセスをしっかりと理解し、他者との交流や手助けを楽しむことが求められます。コミュニティマネージャーになるには、まず既存のメンテナーに興味を示すことから始めます。オンボード/トライアル期間を経て、メンテナーは実績に基づいてコミュニティマネージャーのステータスを付与するかどうかを決定
> 既存のメンテナーに興味を示す

細かいですが、既存のメンテナーに対して興味を示すとも読み取れてしまいます。
本来は「コミュニティマネージャーになりたい」という意思表示を既存のメンテナに対してするという意味かと思います。

2023-10-04 10:12 UTC, kaitoii11 commented on content/ja/contributor-ladder/_index.md
> +承認者になるには、まず既存のメンテナーに興味を示すことから始めましょう。 既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたに承認者の資格を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
> 既存のメンテナーに興味を示す

細かいですが、既存のメンテナーに対して興味を示すとも読み取れてしまいます。
本来は「承認者になりたい」という意思表示を既存のメンテナに対してするという意味かと思います。

2023-10-04 22:29 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +メンテナーは、PRをマージすることもできる承認者です。誰でも用語集のメンテナーになることができます（[メンテナーになる](#メンテナーになる)を参照）。メンテナーには、以下のような期待があります：
レビューありがとうございます。「メンテナーもPRをマージすることができます。」に変更しました。

2023-10-04 22:29 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +メンテナーになるには、まず既存のメンテナーに興味を示すことから始めましょう。既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたにメンテナーの地位を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
レビューありがとうございます。「興味があることを既存のメンテナーに伝えることから始めましょう」に変更しました。

2023-10-04 22:29 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +用語集のコミュニティマネージャーは誰でもなることができます。コミュニティマネージャーは、貢献とローカライゼーションのプロセスをしっかりと理解し、他者との交流や手助けを楽しむことが求められます。コミュニティマネージャーになるには、まず既存のメンテナーに興味を示すことから始めます。オンボード/トライアル期間を経て、メンテナーは実績に基づいてコミュニティマネージャーのステータスを付与するかどうかを決定
レビューありがとうございます。「興味があることを既存のメンテナーに伝えることから始めましょう」に変更しました。

2023-10-04 22:29 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +承認者になるには、まず既存のメンテナーに興味を示すことから始めましょう。 既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたに承認者の資格を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
レビューありがとうございます。「興味があることを既存のメンテナーに伝えることから始めましょう」に変更しました。

2023-10-05 01:02 UTC, yuichi-nakamura approved these changes
LGTM

2023-10-05 02:01 UTC, kaitoii11 commented on content/ja/contributor-ladder/_index.md
> +承認者になるには、まず既存のメンテナーに興味を示すことから始めましょう。 既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたに承認者の資格を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
変更をpushできてないみたいなので、お手すきの際にpushお願いしますー

2023-10-05 06:12 UTC, naonishijima commented on content/ja/contributor-ladder/_index.md
> +承認者になるには、まず既存のメンテナーに興味を示すことから始めましょう。 既存のメンテナーはあなたに、彼らの指導のもとでPRを投稿したり、レビューをしたり、その他の仕事をしたり上記の資格を証明するよう求めます。しばらく一緒に仕事をした後、メンテナーはあなたに承認者の資格を与えるかどうかを決定します。この決定は、あなたが示した熟練度と対応能力に基づいて行われます。
ご指摘ありがとうございます。pushし忘れていました…

2023-10-05 06:52 UTC, kaitoii11 approved these changes

2023-10-05 06:52 UTC, merged