[tw] localize API for traditional chinese (#2459)
cncf/glossary pull request #2467
Opened 2023-10-04 08:47 UTC by EmilyXinyi

### Describe your changes
original content from https://glossary.cncf.io/application-programming-interface/

### Related issue number or link (ex: `resolves #issue-number`)
resolve #2459

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-04 13:29 UTC, hwchiu commented on content/zh-tw/application-programming-interface.md
> +應用程式介面（API）是電腦程式互動的一種方式。就像人類通過網頁與網站互動一樣，API 允許電腦程式之間進行交互。
有種感覺交互這個詞比較是中國大陸的用法，繁體中文針對 interfaction 似乎用別的居多

2023-10-04 13:29 UTC, hwchiu commented on content/zh-tw/application-programming-interface.md
> +與人類的交互不同，API可以限制對方可以和不可以問什麽。對交互的限制有助於在程式之間創建穩定且實用的信息傳輸。
信息也是簡體用語居多

2023-10-04 13:29 UTC, hwchiu commented on content/zh-tw/application-programming-interface.md
> +API 允許電腦程式或應用程式以一種明確的、可理解的方式互動和共享資訊。
你這邊就用互動，所以我覺得前面都將交互換成互動會滿通順的

2023-10-04 13:29 UTC, hwchiu commented on content/zh-tw/application-programming-interface.md
> +它們是現代應用程式的基本構建組，它們為開發人員提供了一種將應用程式整合在一起的方法。
思考有沒有比 基本構建組 更好的翻譯

2023-10-04 13:37 UTC, EmilyXinyi commented on content/zh-tw/application-programming-interface.md
> +應用程式介面（API）是電腦程式互動的一種方式。就像人類通過網頁與網站互動一樣，API 允許電腦程式之間進行交互。
用“互動”會不會更好？

2023-10-04 13:40 UTC, EmilyXinyi commented on content/zh-tw/application-programming-interface.md
> +與人類的交互不同，API可以限制對方可以和不可以問什麽。對交互的限制有助於在程式之間創建穩定且實用的信息傳輸。
"資訊傳輸“會更好嗎？

2023-10-04 13:40 UTC, EmilyXinyi commented on content/zh-tw/application-programming-interface.md
> +它們是現代應用程式的基本構建組，它們為開發人員提供了一種將應用程式整合在一起的方法。
”基本模塊“？

2023-10-06 14:55 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +它們是現代應用程式的基本構建組，它們為開發人員提供了一種將應用程式整合在一起的方法。
"它們是奠定現代應用程式的基礎" 如何呢？

2023-10-06 22:15 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +與人類的交互不同，API可以限制對方可以和不可以問什麽。對交互的限制有助於在程式之間創建穩定且實用的信息傳輸。
"資訊傳輸" 我覺得ok

2023-10-06 22:18 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +應用程式介面（API）是電腦程式互動的一種方式。就像人類通過網頁與網站互動一樣，API 允許電腦程式之間進行交互。
我贊成 "互動"

2023-10-06 22:33 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +沒有一個共享的框架，應用程式[擴展](/zh-tw/scalability/)和整合將是一個挑戰。
"將是一個挑戰" 在我聽起來有點太過中性，畢竟挑戰有可能是正面的也有可能是負面的。但原文比較像是要把 "沒有一個共享的框架" 這件事形容成一件負面的事情，所以我建議可以翻成 "將會變得很辛苦" 。

原文：

> Without a shared framework, it is challenging for applications to scale and integrate.

2023-10-06 22:33 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起工作時，就可以推斷它們是通過某種API互動的。
"一起工作" 也是比較偏向簡體用語，在台灣通常只有真人才會一起工作，機器的話則是 "運作" 。

2023-10-08 13:39 UTC, EmilyXinyi commented
謝謝 @johnlinp @hwchiu 指正，已修改 :)

2023-10-08 17:16 UTC, johnlinp approved these changes
感謝!

2023-10-09 23:50 UTC, HungWeiChiu approved these changes

2023-10-09 23:52 UTC, hwchiu approved these changes
LGTM

2023-10-10 11:11 UTC, pichuang reviewed
中英空格一下，然後合併一個 commit 即可

2023-10-10 11:11 UTC, pichuang commented on content/zh-tw/application-programming-interface.md
> +與人類的互動不同，API可以限制對方可以和不可以問什麽。對互動的限制有助於在程式之間創建穩定且實用的資訊傳輸。
```suggestion
與人類的互動不同，API 可以限制對方可以和不可以問什麽。對互動的限制有助於在程式之間創建穩定且實用的資訊傳輸。
```

2023-10-10 11:11 UTC, pichuang commented on content/zh-tw/application-programming-interface.md
> +沒有API，應用程式之間就缺乏一個應用程式之間互動的框架。
```suggestion
沒有 API，應用程式之間就缺乏一個應用程式之間互動的框架。
```

2023-10-10 11:11 UTC, pichuang commented on content/zh-tw/application-programming-interface.md
> +每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起運作時，就可以推斷它們是通過某種API互動的。
```suggestion
每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起運作時，就可以推斷它們是通過某種 API 互動的。
```

2023-10-16 15:07 UTC, johnlinp requested changes

2023-10-16 15:07 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +應用程式介面（API）是電腦程式互動的一種方式。就像人類通過網頁與網站互動一樣，API 允許電腦程式之間進行互動。
這邊我建議把 "通過" 改成 "透過" ，比較符合台灣人的用法，謝謝。

2023-10-16 15:07 UTC, johnlinp commented on content/zh-tw/application-programming-interface.md
> +每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起運作時，就可以推斷它們是通過某種API互動的。
這邊我也是建議把 "通過" 改成 "透過" 。

2023-11-13 13:43 UTC, EmilyXinyi commented on content/zh-tw/application-programming-interface.md
> +每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起運作時，就可以推斷它們是通過某種API互動的。
已改 :)

2023-11-13 13:43 UTC, EmilyXinyi commented on content/zh-tw/application-programming-interface.md
> +每當您聽到[微服務](/zh-tw/microservices-architecture/)在一起運作時，就可以推斷它們是通過某種API互動的。
已更正 :)

2023-11-18 18:56 UTC, johnlinp approved these changes
感謝!

2023-11-19 13:10 UTC, hwchiu commented
@EmilyXinyi  我覺得內容都沒有問題了，剩下就是把 Commit 合成一筆，這樣我們合併會比較方便，再麻煩了

2023-11-20 13:37 UTC, merged