[ru] Second set of terms for Russian localization
cncf/glossary pull request #2470
Opened 2023-10-04 13:25 UTC by kirkonru

### Description

This PR adds a second set of localized Russian terms.

In total, 14 terms were translated from English and 2 Russian-specific terms were added.

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-06 10:17 UTC, kirkonru commented on content/ru/native.md
> +title: Abstraction
```suggestion
title: Нативный
```

2023-10-09 09:32 UTC, kirkonru commented
@shurup please review this one as well 😇

2023-10-20 15:46 UTC, shurup requested changes
Great job was already done here! Here are my corrections.

2023-10-20 15:46 UTC, shurup commented on content/ru/blue-green-deployment.md
> +Одно из них обслуживает production-трафик (в нем работает старая версия), а другое в это время обновляется.
```suggestion
Одно из них обслуживает production-трафик (в нем работает текущая версия, с которой работают пользователи), а другое в это время обновляется.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/blue-green-deployment.md
> +использовать термин "развертывание с нулевым временем простоя".
```suggestion
использовать термин "развертывание с нулевым временем простоя" _(zero-downtime deployment)_.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/canary-deployment.md
> +Стратегия канареечных развертываний начинается с двух окружений:
```suggestion
Стратегия канареечных развертываний _(canary deployments)_ начинается с двух окружений: 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/canary-deployment.md
> +одно из них обслуживает живой трафик, другое содержит обновленный код (но без трафика).
```suggestion
одно из них обслуживает живой трафик, другое — содержит обновленный код (но без трафика).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/chaos-engineering.md
> +Хаос-инженерия (Chaos Engineering или CE) — подход, при котором над [распределенной](/distributed-systems/) production-системой проводится ряд экспериментов,
```suggestion
Хаос-инженерия (_chaos engineering_, CE) — подход, при котором над [распределенной](/distributed-systems/) production-системой проводится ряд экспериментов, 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/chaos-engineering.md
> +Практики [SRE](/site-reliability-engineering/) и [DevOps](/devops/) концентрируются на
```suggestion
Практики [SRE](/site-reliability-engineering/) и [DevOps](/ru/devops/) концентрируются на 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/auto-scaling.md
> +Используя облачные технологии, [виртуализацию](/virtualization/) и [контейнеризацию](/containerization/) приложений и их зависимостей,
```suggestion
Используя облачные технологии, [виртуализацию](/virtualization/) и [контейнеризацию](/ru/containerization/) приложений и их зависимостей, 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cluster.md
> +Совокупность всех этих [контейнеризованных](/containerization/) сервисов, соединенных по сети, представляет собой кластер.
```suggestion
Совокупность всех этих [контейнеризованных](/ru/containerization/) сервисов, соединенных по сети, представляет собой кластер.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/container-image.md
> +Образы контейнеров являются результатом [контейнеризации](/containerization/) приложения и обычно хранятся в реестрах контейнеров,
```suggestion
Образы контейнеров являются результатом [контейнеризации](/ru/containerization/) приложения и обычно хранятся в реестрах контейнеров, 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/client-server-architecture.md
> +Этот подход отличается от автономных приложений (например, настольных), которые выполняют всю работу в одном месте.
```suggestion
Этот подход отличается от автономных приложений (например, десктопных), которые выполняют всю работу в одном месте.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/client-server-architecture.md
> +В втором случае (когда интернет не было доступен повсеместно) файлы приходилось копировать
```suggestion
Во втором случае (когда интернет не было доступен повсеместно) файлы приходилось копировать 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-computing.md
> +"Облачные вычисления" (cloud computing) — собирательное название систем, которые предоставляют вычислительные ресурсы (процессорные, сетевые и дисковые) по запросу через сеть Интернет. В резульатет п
```suggestion
Облачные вычисления _(cloud computing)_ — собирательное название систем, которые предоставляют вычислительные ресурсы (процессорные, сетевые и дисковые) по запросу через сеть Интернет. В результате пользователи получают доступ к вычислительным мощностям, которые физически расположены в совершенно другом, удаленном месте.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +Нативная облачная безопасность — подход, при котором безопасность встраивается в [нативные облачные приложения](/cloud-native-apps/).
```suggestion
Нативная облачная безопасность — подход, при котором безопасность встраивается в [нативные облачные приложения](/ru/cloud-native-apps/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +В его рамках безопасность становится частью всего жизненного цикла приложения — от разработки до production.
```suggestion
В его рамках безопасность становится частью всего жизненного цикла приложения: от разработки до production.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +Нативная облачная безопасность тесно связана с практикой, известной как [DevSecOps](/devsecops/).
```suggestion
Нативная облачная безопасность тесно связана с практикой, известной как [DevSecOps](/ru/devsecops/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +и проверки безопасности "последней минуты" не соответствуют потребностям нативных облачных приложений.
```suggestion
и проверки безопасности в самый последний момент не соответствуют потребностям нативных облачных приложений.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +Проверка кода, длительные циклы обеспечения качества, сканирование уязвимостей на хостах
```suggestion
Рецензии кода, длительные циклы обеспечения качества, сканирование уязвимостей на хостах 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cloud-native-security.md
> +постоянно обновляя уязвимые компоненты или следя за тем, чтобы инфраструктура регулярно заменялась.
```suggestion
постоянно обновляя уязвимые компоненты или следя за тем, чтобы инфраструктура регулярно обновлялась.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cluster.md
> +В контексте нативных облачных вычислений этот термин чаще всего применяется к [Kubernetes](/kubernetes/).
```suggestion
В контексте нативных облачных вычислений этот термин чаще всего применяется к [Kubernetes](/ru/kubernetes/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cluster.md
> +Программное обеспечение, работающее на одном компьютере, представляет собой единую точку отказа
```suggestion
Программное обеспечение, работающее на одном компьютере, представляет собой единую точку отказа: 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cluster.md
> +— если этот компьютер сломается или кто-то случайно отключит его питание,
```suggestion
если этот компьютер сломается или кто-то случайно отключит его питание, 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/cluster.md
> +Потребность в глобальных системах и годы проб и ошибок привели к созданию нового вида технологического стека — [нативных облачных технологий](/cloud-native-tech/).
```suggestion
Потребность в глобальных системах и годы проб и ошибок привели к созданию нового вида технологического стека — [нативных облачных технологий](/ru/cloud-native-tech/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/container-image.md
> +Образ контейнера — это неизменяемый статический файл, содержащий зависимости, необходимые для создания [контейнера](/container/).
```suggestion
Образ контейнера — это неизменяемый статический файл, содержащий зависимости, необходимые для создания [контейнера](/ru/container/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/container-image.md
> +Эти зависимости могут включать один исполняемый двоичный файл,
```suggestion
Эти зависимости могут включать один исполняемый бинарный файл, 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/container-image.md
> +Образы контейнеров содержат приложение с любыми его рантайм-зависимостями, например, с сервером этого приложения.
```suggestion
Образы контейнеров содержат приложение с любыми его runtime-зависимостями, например, с сервером этого приложения.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/containers-as-a-service.md
> +позволяющий управлять и развертывать приложения с использованием [контейнерной](/container/) [абстракции](/abstraction/).
```suggestion
позволяющий управлять и развертывать приложения с использованием [контейнерной](/ru/container/) [абстракции](/ru/abstraction/).
```

2023-10-20 15:46 UTC, shurup commented on content/ru/containers-as-a-service.md
> +доставки [нативных облачных приложений](/cloud-native-apps/), которые могут работать где угодно.
```suggestion
доставки [нативных облачных приложений](/ru/cloud-native-apps/), которые могут работать где угодно.
```

2023-10-20 15:46 UTC, shurup commented on content/ru/containers-as-a-service.md
> +CaaS также включает встроенную функциональность для [автоматического масштабирования](/auto-scaling/) и управления оркестрацией
```suggestion
CaaS также включает встроенную функциональность для [автоматического масштабирования](/ru/auto-scaling/) и управления оркестрацией 
```

2023-10-20 15:46 UTC, shurup commented on content/ru/containers-as-a-service.md
> +CaaS снижает операционные затраты за счет сокращения ресурсов [DevOps](/devops/), необходимых для управления развертыванием.
```suggestion
CaaS снижает операционные затраты за счет сокращения ресурсов [DevOps](/ru/devops/), необходимых для управления развертыванием.
```

2023-11-03 07:46 UTC, shurup commented
Based on our [recent Slack discussion](https://cloud-native.slack.com/archives/C05G46RMQTX/p1698057198264159?thread_ts=1698038167.603209&cid=C05G46RMQTX), closing this in favour of a bunch of separate PRs with each of them adding one term.

2023-11-03 07:46 UTC, closed without merging

2023-11-03 07:55 UTC, shurup reviewed
- sorry, it was a wrong comment here -