Bangaliscript
cncf/glossary pull request #2474
Opened 2023-10-07 08:09 UTC by PrashantDesale2004

#2403
- corrected Grammatical Errors in Bengali Version of Virtualization

2023-10-09 12:36 UTC, sajibAdhi commented
Hey @PrashantDesale2004
Kindly set the targeted branch from `main` to `dev-bn`. You can use `[bn] localization update content/bn/virtualization.md` as PR as I have changed it.

2023-10-09 13:57 UTC, PrashantDesale2004 commented
> Hey @PrashantDesale2004 Kindly set the targeted branch from `main` to `dev-bn`. You can use `[bn] localization update content/bn/virtualization.md` as PR as I have changed it.

i didn't get it. Do you mean i have to specify "[bn] localization update content/bn/virtualization.md"  in commit meassag. can you elaborate??

2023-10-10 14:35 UTC, sajibAdhi commented
> > Hey @PrashantDesale2004 Kindly set the targeted branch from `main` to `dev-bn`. You can use `[bn] localization update content/bn/virtualization.md` as PR as I have changed it.
> 
> i didn't get it. Do you mean i have to specify "[bn] localization update content/bn/virtualization.md" in commit meassag. can you elaborate??

No, you don't have to specify  `[bn] localization update content/bn/virtualization.md` in the commit message, you can submit a Pull Request following the name convention `[bn]  Localize <file_name.md>`, so it will be easy to track Pull Requests.

2023-10-11 10:58 UTC, PrashantDesale2004 commented
> > > Hey @PrashantDesale2004 Kindly set the targeted branch from `main` to `dev-bn`. You can use `[bn] localization update content/bn/virtualization.md` as PR as I have changed it.
> > 
> > 
> > i didn't get it. Do you mean i have to specify "[bn] localization update content/bn/virtualization.md" in commit meassag. can you elaborate??
> 
> No, you don't have to specify `[bn] localization update content/bn/virtualization.md` in the commit message, you can submit a Pull Request following the name convention `[bn] Localize <file_name.md>`, so it will be easy to track Pull Requests.



> > > Hey @PrashantDesale2004 Kindly set the targeted branch from `main` to `dev-bn`. You can use `[bn] localization update content/bn/virtualization.md` as PR as I have changed it.
> > 
> > 
> > i didn't get it. Do you mean i have to specify "[bn] localization update content/bn/virtualization.md" in commit meassag. can you elaborate??
> 
> No, you don't have to specify `[bn] localization update content/bn/virtualization.md` in the commit message, you can submit a Pull Request following the name convention `[bn] Localize <file_name.md>`, so it will be easy to track Pull Requests.

@sajibAdhi, I have change my commit message, so you can  review it.

2024-01-21 04:59 UTC, sajibAdhi requested changes

2024-01-21 04:59 UTC, sajibAdhi commented on content/bn/virtualization.md
> +ভার্চুয়ালাইজেশন, ক্লাউড নেটিভ কম্পিউটিং সম্পর্কে, <br>-কখনওকি কখনও একটি সার্ভারের সঙ্গে সম্প্রেষণ করে এবং এটি একাধিক বিভিন্ন অপারেটিং সিস্টেম চালাতে দেয়। <br>-এই বিভিন্ন অপারেটিং সিস্টেম এবং তাদের
Hello @PrashantDesale2004.

Kindly remove `<br>` tags. As you can see in the below picture that it is breaking the UI.
![image](https://github.com/cncf/glossary/assets/60180521/794bd662-fa24-4347-8c26-a6f2ac83a19f)
 
 Kindly make those sentence more easy for reader?

2024-02-04 08:45 UTC, sajibAdhi commented
Hey @PrashantDesale2004., do you have any update on this PR?
If you are working on this PR kindly let me know.

2024-02-14 17:41 UTC, asem-hamid commented
This issue is already fixed in this [PR](https://github.com/cncf/glossary/pull/2404 )  

@sajibAdhi you can close it now

2024-02-15 04:57 UTC, sajibAdhi commented
> This issue is already fixed in this [PR](https://github.com/cncf/glossary/pull/2404)
> 
> @sajibAdhi you can close it now

As this issue is already fixed. So I am closing this issue.

2024-02-15 04:57 UTC, closed without merging