[zh-tw] Localize 'Containerization'
cncf/glossary pull request #2479
Opened 2023-10-09 19:56 UTC by rosawu159

### Describe your changes

Origin content from https://glossary.cncf.io/containerization/

### Related issue number or link (ex: `resolves #issue-number`)

resolves https://github.com/cncf/glossary/issues/2478

### Checklist before opening this PR (put `x` in the checkboxes)
- [V] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [V] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-09 23:50 UTC, HungWeiChiu commented on content/zh-tw/containerization.md
> +容器映像檔輕巧（與傳統虛擬機器不同），容器化過程需要一個列出依賴項目的檔案。這個檔案可以進行版本控制，並且可以自動化建置過程，使組織可以專注於其他重要事務，而自動化流程則負責建置。容器映像檔以唯一識別碼存儲，與其確切的內容和配置相關聯。由於容器被安排和重新安排，它們始終被重置為初始狀態，這消除了配置漂移的問題。
建議按照原文分段落，不需要把所有內容變成一行，這樣 review 過程會比較難針對單一句子留言

2023-10-09 23:50 UTC, HungWeiChiu commented on content/zh-tw/containerization.md
> +容器映像檔輕巧（與傳統虛擬機器不同），容器化過程需要一個列出依賴項目的檔案。這個檔案可以進行版本控制，並且可以自動化建置過程，使組織可以專注於其他重要事務，而自動化流程則負責建置。容器映像檔以唯一識別碼存儲，與其確切的內容和配置相關聯。由於容器被安排和重新安排，它們始終被重置為初始狀態，這消除了配置漂移的問題。
配置 -> 似乎是簡體中文用法？

2023-10-09 23:50 UTC, HungWeiChiu commented on content/zh-tw/containerization.md
> +容器映像檔輕巧（與傳統虛擬機器不同），容器化過程需要一個列出依賴項目的檔案。這個檔案可以進行版本控制，並且可以自動化建置過程，使組織可以專注於其他重要事務，而自動化流程則負責建置。容器映像檔以唯一識別碼存儲，與其確切的內容和配置相關聯。由於容器被安排和重新安排，它們始終被重置為初始狀態，這消除了配置漂移的問題。
不確定我們其他翻譯是不是都用 安排 來翻譯 "schedule"

2023-10-09 23:53 UTC, hwchiu commented on content/zh-tw/containerization.md
> +
內容參照原文分多行，全部擠成一行對於 review 會有困難

2023-10-09 23:53 UTC, hwchiu commented on content/zh-tw/containerization.md
> +容器映像檔輕巧（與傳統虛擬機器不同），容器化過程需要一個列出依賴項目的檔案。這個檔案可以進行版本控制，並且可以自動化建置過程，使組織可以專注於其他重要事務，而自動化流程則負責建置。容器映像檔以唯一識別碼存儲，與其確切的內容和配置相關聯。由於容器被安排和重新安排，它們始終被重置為初始狀態，這消除了配置漂移的問題。
不確定我們其他翻譯是不是都用 安排 來翻譯 "schedule"

2023-10-09 23:53 UTC, hwchiu commented on content/zh-tw/containerization.md
> +在容器變得普遍之前，組織依賴虛擬機器來在單一[裸機]((/zh-tw/bare-metal-machine/))上協調多個應用程式。虛擬機器比容器大得多，並且需要虛擬機器管理程式才能運作。由於這些較大的虛擬機器模板的儲存、備份和傳輸，建立虛擬機器模板的速度也很慢。此外，虛擬機器可能會受到配置漂移的影響，這違反了[不變性原則](/zh-tw/immutable-infrastructure/)。
配置似乎是簡體中文用語？ 要確認一下

2023-10-10 03:59 UTC, rosawu159 commented on content/zh-tw/containerization.md
> +容器映像檔輕巧（與傳統虛擬機器不同），容器化過程需要一個列出依賴項目的檔案。這個檔案可以進行版本控制，並且可以自動化建置過程，使組織可以專注於其他重要事務，而自動化流程則負責建置。容器映像檔以唯一識別碼存儲，與其確切的內容和配置相關聯。由於容器被安排和重新安排，它們始終被重置為初始狀態，這消除了配置漂移的問題。
/zh-tw/kubernetes/ 對schedule的翻譯是『排程』，會修正為此翻譯

2023-10-10 04:10 UTC, rosawu159 commented on content/zh-tw/containerization.md
> +在容器變得普遍之前，組織依賴虛擬機器來在單一[裸機]((/zh-tw/bare-metal-machine/))上協調多個應用程式。虛擬機器比容器大得多，並且需要虛擬機器管理程式才能運作。由於這些較大的虛擬機器模板的儲存、備份和傳輸，建立虛擬機器模板的速度也很慢。此外，虛擬機器可能會受到配置漂移的影響，這違反了[不變性原則](/zh-tw/immutable-infrastructure/)。
參考了[Oracle](https://www.oracle.com/tw/security/cloud-security/what-is-cloud-security/)和[Azure](https://learn.microsoft.com/zh-tw/azure/well-architected/devops/principles)的說法，會修正為 組態漂移

2023-10-10 07:31 UTC, hwchiu approved these changes
LGTM

2023-10-10 11:17 UTC, pichuang commented on content/zh-tw/containerization.md
> +在容器變得普遍之前，組織依賴虛擬機器在單一[裸機]((/zh-tw/bare-metal-machine/))上協調多個應用程式。
```suggestion
在容器變得普遍之前，組織依賴虛擬機器在單一[裸機](/zh-tw/bare-metal-machine/)上協調多個應用程式。
```

2023-10-10 11:17 UTC, pichuang commented on content/zh-tw/containerization.md
> +容器建構過程需要遵循[開放容器倡議](https://opencontainers.org/)（OCI）標準。
```suggestion
容器建構過程需要遵循[開放容器倡議組織](https://opencontainers.org/)（OCI）標準。
```

2023-10-10 11:17 UTC, pichuang commented on content/zh-tw/containerization.md
> +由於這些較大的虛擬機器模板的儲存、備份和傳輸，建立虛擬機器模板的速度也很慢。
```suggestion
由於這些較大的虛擬機器樣板的儲存、備份和傳輸，建立虛擬機器模板的速度也很慢。
```

2023-10-10 11:17 UTC, pichuang commented on content/zh-tw/containerization.md
> +title:  容器化
```suggestion
title: 容器化
```

2023-10-10 11:17 UTC, pichuang commented on content/zh-tw/containerization.md
> +此外，虛擬機器可能會受到組態漂移的影響，這違反了[不變性原則](/zh-tw/immutable-infrastructure/)。
```suggestion
此外，虛擬機器可能會受到組態漂移的影響，這違反了[不可變原則](/zh-tw/immutable-infrastructure/)。
```

2023-10-10 14:10 UTC, pichuang commented
@rosawu159 請將 9 個 commits 使用 git squash 收成 1 個，即可合併

2023-10-10 18:49 UTC, johnlinp commented on content/zh-tw/containerization.md
> +在容器變得普遍之前，組織依賴虛擬機器在單一[裸機](/zh-tw/bare-metal-machine/)上協調多個應用程式。
我覺得這句如果改成這樣會比較通順，不知道你覺得如何呢？

```suggestion
在容器變得普遍之前，組織需要使用在單一[裸機](/zh-tw/bare-metal-machine/)上的多個虛擬機器來協調多個應用程式。
```

原文:

> Before containers became prevalent, organizations relied on virtual machines (VMs) to orchestrate multiple applications on a single [bare-metal machine](https://glossary.cncf.io/bare-metal-machine/).

2023-10-10 18:49 UTC, johnlinp commented on content/zh-tw/containerization.md
> +由於這些較大的虛擬機器樣板的儲存、備份和傳輸，建立虛擬機器樣板的速度也很慢。
這一句我也建議這樣改會比較通順：

```suggestion
由於需要儲存、備份和傳輸這些較大的虛擬機器樣板，建立虛擬機器樣板的速度也很慢。
```

原文:

> Due to the storage, backup, and transfer of these larger VM templates, creating the VM templates is also slow.

2023-10-10 18:49 UTC, johnlinp commented on content/zh-tw/containerization.md
> +容器化是將一個應用程式及其相關依賴項打包成一個容器映像的過程。
我建議把 "container image" 一律翻譯成 "容器映像檔" ，就像你下面翻的一樣。

2023-10-10 18:49 UTC, johnlinp commented on content/zh-tw/containerization.md
> +只要輸出是符合此標準的容器映像，使用哪個容器化工具都不重要。
這邊也是建議把 "容器映像" 改為 "容器映像檔" ，謝謝。

2023-11-02 01:27 UTC, ydFu requested changes
Please compress redundant commits into one

2023-11-02 07:34 UTC, ydFu approved these changes
Thanks for compressing git commit

2023-11-02 07:35 UTC, ydFu requested changes

2023-11-02 07:35 UTC, ydFu commented on content/zh-tw/containerization.md
> +=======
```suggestion
<<<<<<< HEAD
=======
```
delete this line

2023-11-06 01:30 UTC, ydFu requested changes
nit

2023-11-06 01:30 UTC, ydFu commented on content/zh-tw/containerization.md
> +在容器變得普遍之前，組織需要使用在單一[裸機](/zh-tw/bare-metal-machine/)上的多個虛擬機器來協調多個應用程式。
```suggestion
在容器變得普遍之前，組織依賴虛擬機器(VM)在單一[裸機](/zh-tw/bare-metal-machine/)上協調多個應用程式。
```

en
```
Before containers became prevalent, organizations relied on virtual machines (VMs) to 
orchestrate multiple applications on a single [bare-metal machine](/bare-metal-machine/).
```

2023-11-06 01:30 UTC, ydFu commented on content/zh-tw/containerization.md
> +由於需要儲存、備份和傳輸這些較大的虛擬機器樣板，建立虛擬機器樣板的速度也很慢。
```suggestion
由於需要較大儲存、備份和傳輸的虛擬機器樣板，建立虛擬機器樣板的速度也很慢。
```

2023-11-21 05:59 UTC, johnlinp approved these changes
感謝!

2023-12-12 06:21 UTC, ydFu commented
@rosawu159 
May I inquire if the current pull request is still active, and if there are any technical challenges that need to be addressed?

2023-12-12 19:01 UTC, rosawu159 commented
@ydFu Everything is fine. All technical challenges have been resolved in the ongoing conversation, please check.

2024-02-03 17:05 UTC, merged