localize-datacenter-#2011
cncf/glossary pull request #2482
Opened 2023-10-10 14:30 UTC by matteobisi

### Describe your changes
I saw an abandoned issue about the translation of this term, so I made a new translation of the term

### Related issue number or link (ex: `resolves #issue-number`)
#2011 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-10 15:00 UTC, ugho16 commented on content/it/data-center.md
> +Gli edifici che ospitano i data center sono attrezzati per mantenere il servizio anche durante eventi avversi, ad esempio con generatori che forniscono energia durante le interruzioni o con potenti s
```suggestion
Gli edifici che ospitano i data center sono attrezzati per mantenere il servizio anche durante eventi avversi, ad esempio con generatori che forniscono energia durante le interruzioni o con potenti sistemi di aria condizionata che mantengono una temperatura controllata, proteggendo i computer dal calore che producono lavorando.
```

2023-10-11 09:47 UTC, ugho16 approved these changes

2023-10-12 16:51 UTC, sistella requested changes

2023-10-12 16:51 UTC, sistella commented on content/it/data-center.md
> +I data center sono abitualmente collegati a linee Internet ad alta velocità, soprattutto quando sono focalizzati sul [cloud computing](/it/cloud-computing/).
```suggestion
I data center sono abitualmente collegati a linee internet ad alta velocità, soprattutto quando sono focalizzati sul [cloud computing](/it/cloud-computing/).
```

2023-10-12 16:51 UTC, sistella commented on content/it/data-center.md
> +Gli edifici che ospitano i data center sono attrezzati per mantenere il servizio anche durante eventi avversi, ad esempio con generatori che forniscono energia durante le interruzioni o con potenti s
```suggestion
Gli edifici che ospitano i data center sono attrezzati per mantenere il servizio anche durante eventi avversi, inclusi generatori che forniscono energia durante le interruzioni e potenti sistemi di aria condizionata che mantengono una temperatura controllata, proteggendo i computer dal calore che producono lavorando.
```
più che altro per rimuovere la "o" che sembra quasi esclusiva... che ne dici?

2023-10-12 16:51 UTC, sistella commented on content/it/data-center.md
> +Prima che i data center diventassero prevalenti alla fine degli anni '90, c'erano principalmente computer individuali con compiti specifici o computer utilizzati dalle persone per svolgere il proprio
A rileggerlo, computer individuali mi dà l'idea di computer dedicati ad una singola persona, mentre qui si vuole indicare le postazioni che erano purpose specifici. Non so, proporrei questo:
```suggestion
Prima che i data center si diffondessero alla fine degli anni '90, i computer si distinguevano principalmente tra quelli dedicati a compiti specifici e quelli utilizzati dalle persone per svolgere il proprio lavoro.
```

2023-10-13 13:20 UTC, sistella approved these changes

2023-10-13 15:41 UTC, merged