[tw] Localize `Scalability` for Traditional Chinese
cncf/glossary pull request #2498
Opened 2023-10-13 17:13 UTC by win5923

### Describe your changes

Origin content from https://glossary.cncf.io/scalability/

### Related issue number or link (ex: `resolves #issue-number`)

`resolves` #2491 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-13 19:21 UTC, johnlinp commented on content/zh-tw/scalability.md
> +[Kubernetes](/zh-tw/kubernetes/) [叢集]((/zh-tw/cluster/)) 透過增減 [容器化](/zh-tw/containerization/) 應用程式的數量來實現擴展，
我個人覺得 "實現" 這個詞在台灣的語境比較像是 "實現夢想" 或是 "實現諾言" 這種用法，
在軟體上比較少用。

因為 "擴展" 已經是一個動詞了，所以我建議這邊直接用 "擴展" 這個動詞就好：

```
Kubernetes 叢集透過增減容器化應用程式的數量來擴展
```

原文:

> For example, a [Kubernetes](https://glossary.cncf.io/kubernetes/) [cluster](https://glossary.cncf.io/cluster/) scales by increasing or reducing the number of [containerized](https://glossary.cncf.io/containerization/) apps, but that scalability depends on several factors.

2023-10-13 19:21 UTC, johnlinp commented on content/zh-tw/scalability.md
> +在 [垂直擴展](/zh-tw/vertical-scaling/) 中，
nit: 我注意到你在中文專有名詞的左右有加上空白：

<img width="789" alt="image" src="https://github.com/cncf/glossary/assets/1290376/d20c0b15-2eb7-4f3f-b2a5-3f570fc46b09">

但我看我們目前的翻譯中，似乎沒有把中文專有名詞的左右加上空白的習慣，比方說 "分散式系統" ：

<img width="819" alt="image" src="https://github.com/cncf/glossary/assets/1290376/de63c934-9504-4911-954b-89c3dbbc2611">

2023-10-13 19:21 UTC, johnlinp commented on content/zh-tw/scalability.md
> +以及控制平面能夠支援多少記錄和操作？
在英文裡，我常看到多個問句是用逗點隔開的，但在中文裡，我比較少看到這樣的用法。
中文裡，我覺得比較常看到的是用問號隔開的，像是這樣：

```
它擁有多少節點？
每個節點可以處理多少容器？
以及控制平面能夠支援多少記錄和操作？
```

不知道你覺得呢？

原文：

> How many [nodes](https://glossary.cncf.io/nodes/) does it have, how many [containers](https://glossary.cncf.io/container/) can each node handle, and how many records and operations can the control plane support?

2023-10-13 19:21 UTC, johnlinp commented on content/zh-tw/scalability.md
> +主要區分為兩種擴展方法。一方面，
這邊我建議把 "On the one hand" 翻譯成 "其中一種方法" ，好像會比較通順一點。

原文:

> On the one hand, there is [horizontal scaling](https://glossary.cncf.io/horizontal-scaling/) which adds more nodes to handle increased load. In contrast, in [vertical scaling](https://glossary.cncf.io/vertical-scaling/) individual nodes are made more powerful to perform more transactions (e.g. by adding more memory or CPU to an individual machine).

2023-10-14 01:03 UTC, hwchiu commented on content/zh-tw/scalability.md
> +在 [垂直擴展](/zh-tw/vertical-scaling/) 中，
我傾向中文不需要保留空白，英文有就好

2023-10-14 01:07 UTC, hwchiu commented on content/zh-tw/scalability.md
> +以及控制平面能夠支援多少記錄和操作？
我個人覺得還好，因為最後產出的結果還是放同一行，這邊應該只是為了跟英文版的內容對齊

2023-10-14 01:13 UTC, johnlinp commented on content/zh-tw/scalability.md
> +以及控制平面能夠支援多少記錄和操作？
@hwchiu 抱歉，我可能表達不清楚，
我的重點不是在分行，
我想講的是建議用問號隔開問句，
而不是用逗號，
謝謝。

2023-10-14 17:10 UTC, win5923 commented on content/zh-tw/scalability.md
> +主要區分為兩種擴展方法。一方面，
修正完畢!

2023-10-15 01:56 UTC, hwchiu commented on content/zh-tw/scalability.md
> +以及控制平面能夠支援多少記錄和操作？
@johnlinp 哦哦，懂了，感謝解釋
原文的問句的確是針對三個問題，所以中文這邊我也支持有三個問號來區別彼此

2023-10-16 03:45 UTC, johnlinp approved these changes
謝謝!

2023-10-19 07:01 UTC, ydFu commented on content/zh-tw/scalability.md
> +其中一種方法，
```suggestion
其中之一，
```

2023-10-19 07:01 UTC, ydFu commented on content/zh-tw/scalability.md
> +有[水平擴展](/zh-tw/horizontal-scaling/)增加更多節點以處理增加的負載。
```suggestion
[水平擴展](/zh-tw/horizontal-scaling/)添加更多節點以處理增加的負載。
```
en
```
On the one hand, there is [horizontal scaling](/horizontal-scaling/) which adds more nodes to handle increased load. 
```

單一句子有兩個重複的單字，不像中文書寫慣用方式

2023-10-19 15:55 UTC, win5923 commented on content/zh-tw/scalability.md
> +有[水平擴展](/zh-tw/horizontal-scaling/)增加更多節點以處理增加的負載。
修改完成!

2023-10-20 01:22 UTC, ydFu reviewed
The whole thing looks good. After modifying the quantifiers, I compressed multiple git commits into one. I can merge this PR. If you don’t know how to compress git commits, you can ask in slack.

2023-10-20 01:22 UTC, ydFu commented on content/zh-tw/scalability.md
> +但這種可擴展性取決於幾個因素。
```suggestion
但這種可擴展性取決於幾項因素。
```

2023-10-20 01:22 UTC, ydFu commented on content/zh-tw/scalability.md
> +每個節點可以處理多少[容器](/zh-tw/container/)？
```suggestion
每個節點可以處理多少個[容器](/zh-tw/container/)？
```

2023-10-20 03:48 UTC, ydFu commented
It seems that the change has been changed to other documents. Check the commit to be contributed.

![image](https://github.com/cncf/glossary/assets/64598482/96836554-ecc8-409a-8b4a-17bdea25b87e)


https://github.com/cncf/glossary/compare/2e050009cfbd60c911f9e4ad740c429412bb11af..5e37df2ce54faaeca09839a989ff954c8ebb54f4

2023-10-20 04:32 UTC, win5923 commented
Sorry, I forgot to merge it.

2023-10-21 02:59 UTC, hwchiu requested changes
麻煩 rebase 一下變成 1 筆 commit，剩下沒問題就可以合併了

感謝

2023-10-24 09:10 UTC, ydFu approved these changes
LGTM

2023-10-28 04:21 UTC, hwchiu approved these changes
LGTM

2023-10-28 04:21 UTC, merged