[tw] Localize `Vertical Scaling` for Traditional Chinese
cncf/glossary pull request #2516
Opened 2023-10-16 14:34 UTC by KevinSpringfield

### Describe your changes

1. Localize Vertical Scaling for Traditional Chinese
2. Source: https://glossary.cncf.io/vertical-scaling/

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #2497 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-16 14:38 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
原文的 “scaling up and down” 我有考慮不翻直接用英文表達，看看 reviewer 有沒有什麼建議

2023-10-16 15:29 UTC, hwchiu requested changes

2023-10-16 15:29 UTC, hwchiu commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
慣例上我們會遵循英文的斷行，markdown 最後產生會一樣，只是一樣的斷行結果會讓我們比較方便 review，不然所有翻譯塞一行會很難指出是哪一段有議題需要討論

2023-10-16 15:29 UTC, hwchiu commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
後面的水平擴展少了超連結

2023-10-17 04:40 UTC, johnlinp commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
這真的超難翻XDD 我參考了一下簡體中文的翻法，他們翻成：

> 垂直伸缩，也称为“向上和向下伸缩”

如果說我們也翻成 `也稱為"向上和向下擴展"` 呢？

2023-10-17 06:36 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
ref: 
Please use semantic line breaks (one sentence per line) to ease review.
https://glossary.cncf.io/style-guide/#three-subheadings

請盡量參照英文的換行方式，這樣approver可以針對你有需要討論的單行句子，針對單行給予建議。

2023-10-17 13:34 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
沒問題還算通順，先採用這個翻譯

2023-10-17 13:35 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為擴大與縮小，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。(請參考另一種擴展方法：[水平擴展](/zh-tw/horizontal-sca
了解了，已修改斷行

2023-10-17 14:09 UTC, johnlinp commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
真的耶，原文的 "horizontal scaling" 兩次都有超連結。但因為我們是翻譯，所以我自己覺得如果能跟原文一樣會比較好。

但我也同意第二次提到同一個詞的時候其實並不需要超連結了，所以我在想你要不要發一個 PR 來直接修改原文，把原文第二次 "horizontal scaling" 的超連結拿掉？

2023-10-19 11:04 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
送 PR 改原文是沒有問題，但這樣會不會造成其他已經翻譯過的語系也需要修改呢？

2023-10-19 17:53 UTC, johnlinp commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
我猜我們不需要擔心這件事XD 如果其他語系想要採納新的原文變動的話，他們自己再各自處理就好。

我前陣子在翻譯的時候，也遇到一個原文有的小問題，就有直接送 PR 改原文: https://github.com/cncf/glossary/pull/2338

2023-10-20 01:57 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
> 送 PR 改原文是沒有問題，但這樣會不會造成其他已經翻譯過的語系也需要修改呢？

1. 繁中超連結議題:  繁體中文建議對齊英文上游，畢竟本地化內容還是以追蹤英文上游為主，所以我傾向本PR在上游未修正的情況一樣保持超連結，不然後續造成後續維護問題。
2. 英文超連結議題:  英文超連結，如果在有格式規範前提，因該如您所述，不應該有兩次超連結，所以可以發起在英文進行PR修改。
3. 其他語系是否因為英文調整需要修正: 答案是必須的，不管是連結修正或者是文檔內容調整，本地化語系本來就要跟隨上游異動，而上游會有基礎的'格式審核','技術審核'等標準，可以盡量保證英文內容就是正確與權威性的。
4. 向英文發起異動PR，先暫緩一下: 這個是個人的建議，非具有強迫性。由於英文審查人員審查量能有限，審核速度可能沒辦法具有即時性反饋。但是我們繁體中文我個人還是傾向快一點有一版合併到main branch，並且到官網上發布呈現，但是如果一直異動英文內容，合併dev-tw到main有一個子任務「dev-tw必須更新到最新」，如果英文內容一直變更，我就會一直無法更新。簡單來說的小結論，現在"此PR更新英文內容"與"繁中更新至官網"這樣兩項任務有相依性關係，因為英文量能不足，如果同時繁中發佈會變慢，希望您能體諒，但是不是強迫性的建議。

2023-10-20 05:03 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。我們可以加入更多計算資源到目前的節點(垂直擴展)，或是加入更多節點至此系統(水平擴展)。[可擴展性](/zh-tw/scalability/)有助於提升系統的競爭力、效率、評價以及品質。
感謝 Ader 的回建議，那我這邊就對齊原文先把超連結補上

2023-10-21 03:01 UTC, hwchiu requested changes
內容看起來沒問題，那麻煩透過 rebase 的方式重新壓成一個 commit，謝謝

2023-10-24 09:28 UTC, ydFu reviewed
Suggestions for modifying some details

2023-10-24 09:28 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +垂直擴展也被稱為向上與向下擴展，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。
```suggestion
垂直擴展也被稱為「向上與向下擴展」，是一項當系統負載提高時透過對單一[節點](/zh-tw/nodes/)增加 CPU 或 RAM 來提升系統容量的技術。
```

2023-10-24 09:28 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +假設你的系統中有一台 4 GB RAM 的計算機，並且想要提升系統的容量至 16 GB RAM，那麼對這個系統作垂直擴就展意味著切換為另一台 16 GB RAM 的計算機。
```suggestion
假設您的系統中有一台 4GB RAM 的計算機，並且想要提升系統的容量至 16GB RAM，那麼對這個系統作垂直擴展意味著切換為另一台 16GB RAM 的計算機。
```

2023-10-24 09:28 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +當對應用程式的需求超過了目前系統的容量，我們需要找出一種方式來擴展系統(增加容量)。
```suggestion
當應用程式的需求成長超出該應用程式實例的當前容量時，
我們需要找出一種方式來擴展系統(增加容量)。
```

en
```
As demand for an application grows beyond the current capacity of that application instance, 
```

2023-10-24 09:28 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +垂直擴展藉由增加計算資源來提升系統容量，使應用程式能夠同時處理更多請求以及執行工作。
```suggestion
垂直擴展藉由增加計算資源來提升現有應用程式的容量，
使得應用程式能夠處理更多請求並同時執行更多工作量。
```

en
```
Vertical scaling increases the capacity of an existing application by 
adding compute resources, allowing the app to process more requests and do more work concurrently.
```

2023-10-24 09:28 UTC, ydFu commented on content/zh-tw/vertical-scaling.md
> +垂直擴展讓我們不用修改應用程式中的程式碼就能調整伺服器的大小。
```suggestion
垂直擴展讓您不用修改應用程式中的程式碼就能調整伺服器的大小。
```

en
```
Vertical scaling allows you to resize your server without changing the application code. 
```

2023-10-25 12:54 UTC, KevinSpringfield commented on content/zh-tw/vertical-scaling.md
> +垂直擴展讓我們不用修改應用程式中的程式碼就能調整伺服器的大小。
感謝提醒，有重新檢視過所有 `you` 的翻譯了

2023-10-27 02:41 UTC, ydFu approved these changes
LGTM,Thanks @KevinSpringfield

2023-10-28 04:22 UTC, hwchiu approved these changes
LGTM

2023-10-28 04:22 UTC, merged