[FR] Localize `Policy as Code`
cncf/glossary pull request #2564
Opened 2023-10-28 19:01 UTC by sestegra

### Describe your changes

Localize `Policy as Code`

### Related issue number or link (ex: `resolves #issue-number`)

Resolved #2563 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-10-29 08:56 UTC, guillaumebernard84 requested changes

2023-10-29 08:56 UTC, guillaumebernard84 commented on content/fr/policy-as-code.md
> +La politique en tant que code est la pratique de stocker la définition des politiques sous forme d'un ou plusieurs fichiers dans un format lisible et exploitable par une machine.
J'aurais plutôt dit: lisible et exploitable par un programme informatique.

2023-10-29 08:56 UTC, guillaumebernard84 commented on content/fr/policy-as-code.md
> +par exemple, des politiques de sécurité qui interdisent de stocker des secrets dans le code source, d'exécuter un conteneur avec des permissions de super-utilisateur
C’est du pinaillage, mais il me semble que l'on peut enlever la virgule derrière "par example", et que l'on peut en ajouter une derrière  "super-utilisateur".

2023-10-29 08:56 UTC, guillaumebernard84 commented on content/fr/policy-as-code.md
> +Git crée un historique des journaux de modifications, ce qui est particulièrement utile lorsque quelque chose ne fonctionne pas comme prévu.
J'aurais mis "un historique des modifications" au lieu de "un historique des journaux de modifications"

2023-11-05 11:51 UTC, sestegra commented on content/fr/policy-as-code.md
> +La politique en tant que code est la pratique de stocker la définition des politiques sous forme d'un ou plusieurs fichiers dans un format lisible et exploitable par une machine.
Oui, je préfère aussi.

2023-11-05 11:54 UTC, sestegra commented on content/fr/policy-as-code.md
> +par exemple, des politiques de sécurité qui interdisent de stocker des secrets dans le code source, d'exécuter un conteneur avec des permissions de super-utilisateur
C'est correct, la virgule avant suffit.

2023-11-05 11:54 UTC, sestegra commented on content/fr/policy-as-code.md
> +Git crée un historique des journaux de modifications, ce qui est particulièrement utile lorsque quelque chose ne fonctionne pas comme prévu.
C'est plus clair effactivement

2023-11-05 21:19 UTC, guillaumebernard84 approved these changes
LGTM 🚀

2023-11-26 16:47 UTC, Krast76 approved these changes
LGTM 🚀

2023-11-26 16:47 UTC, merged