[ja] Localize microservices architecture
cncf/glossary pull request #2582
Opened 2023-11-05 14:22 UTC by A-aiura

### Describe your changes
Localize https://glossary.cncf.io/microservices-architecture/

### Related issue number or link (ex: `resolves #issue-number`)
#2447 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-08 04:57 UTC, naonishijima reviewed
Sorry for late.
I have a comment. Please check it.

2023-11-08 04:57 UTC, naonishijima commented on content/ja/microservices-architecture.md
> +アプリケーションは、特定の機能を実現する異なる部分で構成されています。特定の機能に対する需要は、アプリケーションの他のパーツに対する需要と連動して必ず増減するわけではありません。Netflix の例に戻りましょう。例えば、大規模なマーケティングキャンペーンの後で、Netflix の契約者数が急増したが、その日の早い時間帯におけるストリーミングは概ね安定しているとします。
「特定の機能を実現する異なる部分で構成されています」は「責任」や「担当」などの言葉があるとよいとおもいました。例えば「さまざまな部分で構成され、それぞれが特定の能力を担当します」など

2023-11-08 11:47 UTC, kaitoii11 requested changes

2023-11-08 11:47 UTC, kaitoii11 commented on content/ja/microservices-architecture.md
> +マイクロサービスアーキテクチャは、アプリケーションを個々の独立した（マイクロ）[サービス](/ja/service/)に分割するアーキテクチャ手法で、各サービスは特定の機能に焦点を当てています。これらのサービスは密接に連携して動作し、エンドユーザーには単一のエンティティとして表示されます。例として、Netflix を考えてみます。そのインターフェイスにより、ビデオへのアクセス、検索、プレビューが
「そのインターフェイスにより」は「そのインターフェイスは」の方がインタフェース自体の説明をしているので適切かと思います。

2023-11-08 11:47 UTC, kaitoii11 commented on content/ja/microservices-architecture.md
> +マイクロサービスアーキテクチャは、アプリケーションを個々の独立した（マイクロ）[サービス](/ja/service/)に分割するアーキテクチャ手法で、各サービスは特定の機能に焦点を当てています。これらのサービスは密接に連携して動作し、エンドユーザーには単一のエンティティとして表示されます。例として、Netflix を考えてみます。そのインターフェイスにより、ビデオへのアクセス、検索、プレビューが
「単一のエンティティとして表示されます」は「単一のエンティティとして見えます」の方がappear asを適切に訳しているかと思います

2023-11-08 11:47 UTC, kaitoii11 commented on content/ja/microservices-architecture.md
> +アプリケーションは、特定の機能を実現する異なる部分で構成されています。特定の機能に対する需要は、アプリケーションの他のパーツに対する需要と連動して必ず増減するわけではありません。Netflix の例に戻りましょう。例えば、大規模なマーケティングキャンペーンの後で、Netflix の契約者数が急増したが、その日の早い時間帯におけるストリーミングは概ね安定しているとします。
partsを部分やパーツに訳しているのでどちらかに統一しましょう

2023-11-11 03:36 UTC, A-aiura commented
@naonishijima @kaitoii11   
I appreciate your review and suggestions. The points raised in the review were modified.  
If you have any questions or further suggestions, please free to ask me.

2023-11-11 13:11 UTC, kaitoii11 approved these changes
LGTM

2023-11-12 04:16 UTC, naonishijima approved these changes
LGTM

2023-11-12 04:16 UTC, merged