[tw] Localize infrastructure as code for Traditional Chinese
cncf/glossary pull request #2584
Opened 2023-11-06 13:31 UTC by chienfuchen32

### Describe your changes
reference to https://glossary.cncf.io/infrastructure-as-code/

### Related issue number or link (ex: `resolves #issue-number`)
#2583

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-06 15:09 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +以雲端原生方式建立應用程式需要基礎設施是一次性且可複製的。
reproducible 似乎比較會翻譯為可重現的，複製容易想到 duplicate, clone 等詞

2023-11-06 15:09 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +它還需要以 [擴展性](/zh-tw/scalability/) 自動化和可重複的方式按需，可能無需人工干預。
這句話翻譯的有點怪，原文的意思比較像是
1. 自動化且可重複的方式
2. 根據需求去擴展
這邊的 scale 覺得比較偏向動詞

2023-11-06 15:09 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +手動設定無法滿足[雲端原生應用程式](/zh-tw/cloud-native-apps/)的回應能力和規模要求。
`provisioning`比較不算是設定的概念，特別是當受詞是 infrastructure 時，其含義比較多偏向將整個底層建立起來。

2023-11-06 15:09 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +By representing the data center resources such as servers, load balancers, and subnets as code,
原文可刪除

2023-11-06 15:09 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +它允許基礎設施團隊擁有所有配置的單一事實來源，並且也允許他們在管道中[持續整合](/zh-tw/continuous-integration/)/[持續部署](/zh-tw/continuous-delivery/)管理資料中心,
一般會將 CI/CD 中的pipeline 翻譯成流水線，比較不會用管道，另外這邊感覺可以討論需不需要翻譯出來

2023-11-06 15:31 UTC, chienfuchen32 commented on content/zh-tw/infrastructure-as-code.md
> +它允許基礎設施團隊擁有所有配置的單一事實來源，並且也允許他們在管道中[持續整合](/zh-tw/continuous-integration/)/[持續部署](/zh-tw/continuous-delivery/)管理資料中心,
目前變更較為可讀的內容，不確定是否有同步原始描述的原則，若有勘誤，還請見諒，謝謝

2023-11-07 12:46 UTC, hwchiu commented on content/zh-tw/infrastructure-as-code.md
> +它允許基礎設施團隊擁有所有配置的單一事實來源，並且也允許他們在管道中[持續整合](/zh-tw/continuous-integration/)/[持續部署](/zh-tw/continuous-delivery/)管理資料中心,
目前看起來有一派覺得保持 CI/CD pipeline 也是一個說法

https://cloud-native.slack.com/archives/C055KERTNCX/p1699283441194729

2023-11-07 14:32 UTC, chienfuchen32 commented on content/zh-tw/infrastructure-as-code.md
> +它允許基礎設施團隊擁有所有配置的單一事實來源，並且也允許他們在管道中[持續整合](/zh-tw/continuous-integration/)/[持續部署](/zh-tw/continuous-delivery/)管理資料中心,
完全可以理解，感謝資訊分享

2023-11-09 18:36 UTC, mattwang44 reviewed
一點改進流暢性的建議

2023-11-09 18:36 UTC, mattwang44 commented on content/zh-tw/infrastructure-as-code.md
> +此行為允許基礎設施團隊對於所有配置能夠掌握的單一事實來源，並且也能夠團隊在[CI](/zh-tw/continuous-integration/)/[CD](/zh-tw/continuous-delivery/) pipeline中計畫並管理資料中心，實作版本控制和部署策略。
```suggestion
此行為使得基礎設施團隊對於所有配置有能夠掌握的單一事實來源，並且也讓團隊能在 [CI](/zh-tw/continuous-integration/)/[CD](/zh-tw/continuous-delivery/) pipeline 中管理資料中心，得以實作版本控制和部署策略。
```

2023-11-09 18:36 UTC, mattwang44 commented on content/zh-tw/infrastructure-as-code.md
> +手動建立基礎設施無法滿足[雲端原生應用程式](/zh-tw/cloud-native-apps/)的即時反應能力和延展需求。
```suggestion
手動建立基礎設施無法滿足[雲端原生應用程式](/zh-tw/cloud-native-apps/)的即時反應能力和擴展需求。
```

2023-11-09 18:36 UTC, mattwang44 commented on content/zh-tw/infrastructure-as-code.md
> +若手動變更基礎設施則不容易重新複製環境，並且很快就會達到擴展上的限制，並造成錯誤配置相關錯誤。
```suggestion
若手動變更基礎設施則不容易重現環境、很快就會達到擴展上的限制，並易造成配置錯誤。
```

2023-11-11 04:49 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +title: Infrastructure as Code (IaC)
```suggestion
title: 基礎架構即程式碼
```

2023-11-11 04:49 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +這取代了手動配置基礎設施即服務的傳統模型，通常透過 shell 腳本或其他配置工具。
"配置" --> "設定"

2023-11-11 04:49 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +以雲端原生方式建立應用程式需要在基礎設施上是可支配且可重現的。
"disposable" 我認為是 "丟棄式的" 的意思。在這邊的 context 中，應該就像是 docker container 那種感覺，開了一個出來之後用一用，用完就可以砍掉了。

原文:
> Building applications in a cloud native way requires infrastructure to be disposable and reproducible.

2023-11-11 04:49 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +若手動變更基礎設施則不容易重現環境、很快就會達到擴展上的限制，並易造成配置錯誤。
這邊使用頓號 (、) 來隔開句子有點像是日文的用法。如果改成逗號 (，) 的話或許比較接近中文的用法。

2023-11-12 14:25 UTC, hwchiu approved these changes
LGTM

2023-11-12 18:28 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +這取代了手動配置基礎設施即服務的傳統模型，通常透過 shell 腳本或其他配置工具。
@chienfuchen32 我注意到你有改了一個地方，不過

2023-11-12 18:31 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +title: 基礎架構即程式碼 (IaC)
不好意思，我有點不確定這邊為什麼要保留 IaC 的縮寫，可以麻煩說明嗎？謝謝。

2023-11-13 14:18 UTC, chienfuchen32 commented on content/zh-tw/infrastructure-as-code.md
> +title: 基礎架構即程式碼 (IaC)
抱歉，我沒特別留意到縮寫也是很重要的同步內容，感謝您的提醒

2023-11-13 14:20 UTC, chienfuchen32 commented on content/zh-tw/infrastructure-as-code.md
> +這取代了手動配置基礎設施即服務的傳統模型，通常透過 shell 腳本或其他配置工具。
@johnlinp 此處原文提到`This replaces the traditional model where infrastructure as a service is provisioned manually`
若是以`這取代了人工建置基礎設施即服務的傳統模型`來描述，是否貼近原意，感謝！

2023-11-13 16:57 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +這取代了手動配置基礎設施即服務的傳統模型，通常透過 shell 腳本或其他配置工具。
"provision" 這個字我們通常會翻譯成 "佈建" ：

https://aws.amazon.com/tw/products/management-and-governance/use-cases/provisioning-and-orchestration/

2023-11-14 01:00 UTC, pichuang approved these changes
LGTM

2023-11-14 14:40 UTC, johnlinp commented on content/zh-tw/infrastructure-as-code.md
> +這取代了手動配置基礎設施即服務的傳統模型，通常透過 shell 腳本或其他配置工具。
另外我注意到你整篇翻譯還有其他地方有用到 "配置" ，不知道方不方便也都一併修改成 "設定" ，謝謝!

2023-11-15 02:55 UTC, ydFu requested changes

2023-11-15 02:55 UTC, ydFu commented on content/zh-tw/infrastructure-as-code.md
> +## 它解決的問題 {#problem-it-addresses}
```suggestion
## 解決的問題 {#problem-it-addresses}
```


Unified Traditional Chinese description

2023-11-15 02:55 UTC, ydFu commented on content/zh-tw/infrastructure-as-code.md
> +title: 基礎架構即程式碼
```suggestion
title: 基礎設施即程式碼
```

2023-11-15 02:55 UTC, ydFu commented on content/zh-tw/infrastructure-as-code.md
> +基礎架構即程式碼是將基礎設施的定義儲存為一個或多個檔案的做法。
```suggestion
基礎設施即程式碼是將基礎設施的定義儲存為一個或多個檔案的做法。 
```

2023-11-15 02:55 UTC, ydFu commented on content/zh-tw/infrastructure-as-code.md
> +此行為使得基礎設施團隊對於所有設定有能夠掌握的單一事實來源，並且也讓團隊能在 [CI](/zh-tw/continuous-integration/)/[CD](/zh-tw/continuous-delivery/) pipeline 中管理資料中心，得以實作版本控制和部署策略。
```suggestion
此行為使得基礎設施團隊對於所有設定有能夠掌握的單一事實來源，並且也讓團隊能在 [CI](/zh-tw/continuous-integration/)/[CD](/zh-tw/continuous-delivery/) Pipeline 中管理資料中心，得以實作版本控制和部署策略。
```

2023-11-15 02:55 UTC, ydFu commented on content/zh-tw/infrastructure-as-code.md
> +若手動變更基礎設施則不容易重現，環境很快就會達到擴展上的限制，並易造成設定錯誤。
```suggestion
若手動進行變更基礎設施則不容易進行重現，環境很快就會達到擴展上的限制，並易造成設定錯誤。
```

2023-11-16 03:38 UTC, ydFu approved these changes
LGTM,Thank @chienfuchen32

2023-11-16 03:39 UTC, merged