Create container-orchestration.md
cncf/glossary pull request #2609
Opened 2023-11-12 06:40 UTC by ARYANis0001

### Describe your changes
ocalize container-orchestration.md to Hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves https://github.com/cncf/glossary/issues/1977

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-12 06:42 UTC, ARYANis0001 commented
Please assign this issue to me I have raised the PR

2023-11-12 06:43 UTC, ARYANis0001 reviewed
Updated

2023-11-14 15:27 UTC, kumarankit999 commented on content/hi/container-orchestration.md
> +## यह समस्या का समाधान करता है
## यह किस समस्या का समाधान करता है

2023-11-28 14:28 UTC, Aryan-Singla commented
Hey @aj11anuj @kumarankit999  please review it

2023-12-03 17:15 UTC, ankur0904 requested changes
Please have a look.

2023-12-04 03:24 UTC, Aryan-Singla commented
@ankur0904 I have added your suggestions

2023-12-04 09:59 UTC, Garima-Negi requested changes

2023-12-12 19:25 UTC, Garima-Negi approved these changes

2023-12-13 09:12 UTC, Aryan-Singla commented
Hey @kumarankit999 if you find this PR is correct. Can you please approve it. Already received 1 approval

2023-12-13 09:46 UTC, ankur0904 commented on content/hi/container-orchestration.md
> +सबसे पहले, वे घोषणा करते हैं कि यह कैसा दिखना चाहिए (उदाहरण के लिए, एक्स कंटेनर, वाई पॉड्स, आदि)।
```suggestion
सबसे पहले, वे परिभाषित करते हैं कि यह कैसा दिखना चाहिए (उदाहरण के लिए X कंटेनर, Y पॉड्स, आदि)।
```

2023-12-13 09:46 UTC, ankur0904 commented on content/hi/container-orchestration.md
> +ऑर्केस्ट्रेशन टूल तब स्वचालित रूप से बुनियादी ढांचे की निगरानी करेगा और यदि इसकी स्थिति घोषित स्थिति से भटकती है तो इसे ठीक कर देगा (उदाहरण के लिए, यदि कोई कंटेनर दुर्घटनाग्रस्त हो जाता है तो एक नया
```suggestion
ऑर्केस्ट्रेशन टूल तब स्वचालित रूप से बुनियादी ढांचे की निगरानी करेगा और यदि इसकी स्थिति परिभाषित स्थिति से भटकती है तो इसे ठीक कर देगा (उदाहरण के लिए यदि कोई कंटेनर दुर्घटनाग्रस्त हो जाता है तो एक नया कंटेनर स्पिन करें)।
```

2023-12-13 09:49 UTC, ankur0904 reviewed
Please *don't* consider the change until other maintainers approves the suggested changes.

_Thanks_

2023-12-13 12:17 UTC, abhay-raj19 approved these changes
Looks good to me !

2023-12-13 12:28 UTC, bishal7679 commented
Please wait for final approval!

2023-12-13 12:31 UTC, Aryan-Singla commented
@bishal7679 Please check slack glossary-loclization-hindi

2023-12-13 12:57 UTC, kumarankit999 reviewed
lgtm

2023-12-13 14:56 UTC, ankur0904 approved these changes
LGTM

2023-12-13 15:11 UTC, aj11anuj commented
> Please _don't_ consider the change until other maintainers approves the suggested changes.
> 
> _Thanks_

@ankur0904 feel free to review Hindi localization PR's, no need to wait for our approval for your reviews to be considered helpful. 
@Aryan-Singla, you can consider reviews from other people as well and implement changes if you feel like it. We will take care of unhelpful changes (if there are any) during final review and approval.

2023-12-13 18:12 UTC, Aryan-Singla commented
@kumarankit999  assign issue(#1977) to me. We have been working on it for the last few days but the issue is not assigned to me

2023-12-13 18:14 UTC, bishal7679 requested changes
Left some suggestions!

2023-12-13 18:14 UTC, bishal7679 commented on content/hi/container-orchestration.md
> +[माइक्रोसर्विसेज](/माइक्रोसर्विसेज/), सुरक्षा और नेटवर्क संचार को बड़े पैमाने पर प्रबंधित करना - और [वितरित सिस्टम](/वितरित-सिस्टम/) को सामान्य रूप से प्रबंधित करना - मैन्युअल रूप से प्रबंधित करना अस
```suggestion
[माइक्रोसर्विसेज](/microservices/), सुरक्षा और नेटवर्क संचार को बड़े पैमाने पर प्रबंधित करना - और [वितरित सिस्टम](/distributed-systems/) को सामान्य रूप से प्रबंधित करना - मैन्युअल रूप से प्रबंधित करना असंभव नहीं लेकिन कठिन है।
```

2023-12-13 18:14 UTC, bishal7679 commented on content/hi/container-orchestration.md
> +## यह कैसे मदद करता है
```suggestion
## समाधान
```

2023-12-13 18:14 UTC, bishal7679 commented on content/hi/container-orchestration.md
> +कंटेनर ऑर्केस्ट्रेशन उपकरण उपयोगकर्ताओं को सिस्टम की स्थिति निर्धारित करने की अनुमति देते हैं।
```suggestion
कंटेनर ऑर्केस्ट्रेशन टूल उपयोगकर्ताओं को सिस्टम की स्थिति निर्धारित करने की अनुमति देते हैं।
```

2023-12-13 18:14 UTC, bishal7679 commented on content/hi/container-orchestration.md
> +ऑर्केस्ट्रेशन टूल तब स्वचालित रूप से बुनियादी ढांचे की निगरानी करेगा और यदि इसकी स्थिति परिभाषित स्थिति से भटकती है तो इसे ठीक कर देगा (उदाहरण के लिए यदि कोई कंटेनर दुर्घटनाग्रस्त हो जाता है तो एक नय
```suggestion
ऑर्केस्ट्रेशन टूल तब स्वचालित रूप से इंफ्रास्ट्रक्चर की निगरानी करेगा और यदि इसकी स्थिति परिभाषित स्थिति से भटकती है तो इसे ठीक कर देगा (उदाहरण के लिए यदि कोई कंटेनर दुर्घटनाग्रस्त हो जाता है तो एक नया कंटेनर स्पिन करें)।
```

2023-12-13 18:14 UTC, bishal7679 commented on content/hi/container-orchestration.md
> +यह स्वचालन कई इंजीनियरिंग टीमों के अन्यथा अत्यधिक मैन्युअल और जटिल परिचालन कार्यों को सरल बनाता है, जिसमें प्रावधान, तैनाती, स्केलिंग (ऊपर और नीचे), नेटवर्किंग, लोड संतुलन और अन्य गतिविधियां शामिल है
```suggestion
यह स्वचालन कई इंजीनियरिंग टीमों के अन्यथा अत्यधिक मैन्युअल और जटिल परिचालन कार्यों को सरल बनाता है, जिसमें प्रावधान, डिप्लॉयमेंट, स्केलिंग (उप और डाउन), नेटवर्किंग, लोड संतुलन और अन्य गतिविधियां शामिल हैं।
```

2023-12-14 14:40 UTC, bishal7679 approved these changes
Thank you @Aryan-Singla!

2023-12-14 14:41 UTC, merged