Made Suggested Changes
cncf/glossary pull request #2616
Opened 2023-11-13 04:13 UTC by AniketNS

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-13 06:19 UTC, kumarankit999 reviewed
lgtm, What others says??

2023-11-13 16:48 UTC, abhay-raj19 commented on content/hi/api-gateway.md
> +एपीआई गेटवे (अक्सर बाहरी) एपीआई उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।
एपीआई गेटवे अक्सर बाहरी उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।

2023-11-13 16:51 UTC, abhay-raj19 requested changes
And else looks good to me .

2023-11-13 16:51 UTC, abhay-raj19 commented on content/hi/api-gateway.md
> +एपीआई गेटवे (अक्सर बाहरी) एपीआई उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।
एपीआई गेटवे अक्सर बाहरी उपभोक्ताओं के लिए एक सामान्य इंटरफ़ेस के रूप में कार्य करता है।

2023-11-14 03:45 UTC, AniketNS commented
I've made the changes you told @abhay-raj19. Will you please check and tell me if is there anything I should do?

2023-11-14 06:35 UTC, jihoon-seo commented
@AniketNS Please change the target branch of this PR to `dev-hi`, not `main`.

2023-11-14 07:14 UTC, bishal7679 reviewed
Left some suggestions!

2023-11-14 07:16 UTC, bishal7679 commented
> @AniketNS Please change the target branch of this PR to `dev-hi`, not `main`.

+1

2023-11-14 07:22 UTC, bishal7679 commented
@AniketNS Its always a good practise to create your local branch significant
you should signoff your commit as well to avoid DCO failure! use `git commit -s -m "your message here"` in this way

2023-11-16 14:12 UTC, aj11anuj reviewed
@AniketNS, Why you opened a duplicate PR here, when you were already working on #1614.

2023-11-16 14:28 UTC, kumarankit999 reviewed
Yes @aj11anuj, Why are you creating Duplicate PR for this Since #1614 is opened

2023-11-16 15:40 UTC, AniketNS commented
Hey @aj11anuj and @kumarankit999, I don't How this new PR got created. As I'm a beginner, I don't actually how it is happening. Really sorry for that.

2023-11-16 16:34 UTC, kumarankit999 commented
No Problem @AniketNS, you can work on that PR Only!

2023-11-17 05:17 UTC, aj11anuj commented
Approvers, please check for duplication before starting review process.

And contributors are also advised to check if there's already an open PR or not, before making a new PR

Closing this one as it's a duplicate

2023-11-17 05:17 UTC, closed without merging