Added stateful-apps Hindi Page
cncf/glossary pull request #2617
Opened 2023-11-13 05:15 UTC by AniketNS

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-14 06:35 UTC, jihoon-seo commented
@AniketNS Please change the target branch of this PR to `dev-hi`, not `main`.

2023-11-15 06:46 UTC, AniketNS commented
> @AniketNS Please change the target branch of this PR to `dev-hi`, not `main`.

Hey @jihoon-seo, Can you tell me, How am I supposed to do that?

2023-11-17 04:28 UTC, kumarankit999 commented
I think @bishal7679 has changed the branch to dev-hi,  you can work on your PR now!

2023-11-25 10:43 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +किसी ऐप का उपयोग करने के लिए आम तौर पर एकाधिक अनुरोधों की आवश्यकता होती है।
```suggestion
किसी ऐप का उपयोग करने के लिए आम तौर पर एकाधिक रिक्वेस्ट की आवश्यकता होती है।
```

2023-11-25 10:44 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +अपना पासवर्ड दर्ज करते हो (अनुरोध #1),
```suggestion
अपना पासवर्ड दर्ज करते हो (रिक्वेस्ट #1),
```

2023-11-25 10:44 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +शायद आप किसी मित्र को धन हस्तांतरित कर सकते हैं (अनुरोध #2),
```suggestion
शायद आप किसी मित्र को धन हस्तांतरित कर सकते हैं (रिक्वेस्ट #2),
```

2023-11-25 10:44 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +और अंत में, आप स्थानांतरण विवरण देखना चाहेंगे (अनुरोध #3)।
```suggestion
और अंत में, आप स्थानांतरण विवरण देखना चाहेंगे (रिक्वेस्ट #3)।
```

2023-11-25 10:47 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +सही ढंग से कार्य करने के लिए, प्रत्येक स्टेप को पिछले स्टेप्स को याद रखना होगा,
```suggestion
सही ढंग से कार्य करने के लिए, प्रत्येक स्टेप मे पिछले स्टेप्स को याद रखना होगा,
```

2023-11-25 10:48 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +और अंत में, आप स्थानांतरण विवरण देखना चाहेंगे (अनुरोध #3)।
```suggestion
और अंत में, आप स्थानांतरण विवरण देखना चाहेंगे (रिक्वेस्ट #3)।
```

2023-11-25 10:53 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +सबसे सरल है स्थिति को स्मृति में बनाए रखना और उसे कहीं भी कायम न रखना।
```suggestion
सबसे सरल है स्टेट को मेमोरी में बनाए रखना और उसे कहीं भी सेव न करना।
```

2023-11-25 10:53 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +इसके साथ समस्या यह है कि, जब भी एप्लिकेशन को पुनरारंभ करना पड़ता है, तो सभी स्थिति खो जाती है।
```suggestion
इसके साथ समस्या यह है कि, जब भी एप्लिकेशन को पुनरारंभ करना पड़ता है, तो सभी स्टेट खो जाती है।
```

2023-11-25 10:54 UTC, ankur0904 commented on content/hi/stateful-apps.md
> +इसे रोकने के लिए, स्थिति को स्थानीय रूप से (डिस्क पर) या डेटाबेस सिस्टम में कायम रखा जाता है।
```suggestion
इसे रोकने के लिए, स्टेट को स्थानीय रूप से (डिस्क पर) या डेटाबेस सिस्टम में सेव रखा जाता है।
```

2023-11-25 10:55 UTC, ankur0904 requested changes
Please have a look at those changes.

2023-12-14 08:28 UTC, kumarankit999 commented
Hey @AniketNS, are you still working on this PR!!

2023-12-19 09:48 UTC, AniketNS commented
> Hey @AniketNS, are you still working on this PR!!

Yup!!

2023-12-19 09:55 UTC, AniketNS commented
Hey @ankur0904, I've made the changes as per your request. Can you please check and tell me if there is something I should change more.

2024-08-02 17:59 UTC, aj11anuj approved these changes
/lgtm

2024-10-04 12:09 UTC, kumarankit999 approved these changes
Apologies for the late Review of this PR! It looks great! Thanks for raising this PR and help!

2025-01-28 02:57 UTC, aj11anuj commented
@bishal7679 @abhay-raj19 @Garima-Negi @jayesh-srivastava

2025-04-01 04:52 UTC, bishal7679 commented
Apologies for taking long time to merge it.
LGTM!
/lgtm

2025-04-01 04:53 UTC, merged