[hi] Create vertical-scaling.md
cncf/glossary pull request #2626
Opened 2023-11-14 16:42 UTC by Aryan-Singla

Signed off: Aryan-Singla [devendergupta4573@gmail.com]
### Describe your changes
 Localize Vertical Scaling in Hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2624

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-17 05:43 UTC, seokho-son commented
@ARYANis0001 I have a common comment on your PRs.
PTAL: https://github.com/cncf/glossary/pull/2605#issuecomment-1815774999

2023-11-17 05:47 UTC, kumarankit999 commented
+1 @seokho-son

2023-11-20 02:16 UTC, ARYANis0001 commented
> +1 @seokho-son 


Hey @seokho-son  
Hey @kumarankit999 
I want to express my sincere apologies for any inconvenience caused to the team members of CNCF/Glossary due to my raised PRs. I fully understand my mistake and acknowledge that I need to be more careful in the future. Going forward, I will ensure to thoroughly read the contributing guidelines and submit PRs in my native language, which I am fluent in and proficient in.

2023-11-21 11:21 UTC, ARYANis0001 reviewed
Update (add some words)

2023-11-21 11:23 UTC, ARYANis0001 commented
Hey @aj11anuj @kumarankit999  I have added some words to simplify it can you please review it

2023-11-27 07:14 UTC, ankur0904 commented on content/hi/vertical-scaling.md
> +यह क्षैतिज स्केलिंग के विपरीत है, जहां ऐप को स्केल करने योग्य होना चाहिए, जहां संभावित रूप से कोड अपडेट की आवश्यकता होती है।
```suggestion
यह क्षैतिज स्केलिंग के विपरीत है, जहां ऐप को स्केल करने के लिए प्रतिकृति चाहिए, जहां संभावित रूप से कोड अपडेट की आवश्यकता होती है।
```

2023-11-27 07:15 UTC, ankur0904 requested changes
Please have a look at this suggestion.

2023-11-28 04:29 UTC, Aryan-Singla commented
> Please have a look at this suggestion.

Updated

2023-11-28 14:03 UTC, ankur0904 approved these changes
LGTM

2023-11-28 14:27 UTC, Aryan-Singla commented
Hey @aj11anuj @kumarankit999  please review it

2023-12-01 17:57 UTC, Garima-Negi approved these changes
LGTM!

2023-12-01 19:37 UTC, Aryan-Singla commented
@bishal7679 why this hold label is added

2023-12-06 11:44 UTC, Aryan-Singla commented on content/hi/vertical-scaling.md
> +यह क्षैतिज स्केलिंग के विपरीत है, जहां ऐप को स्केल करने योग्य होना चाहिए, जहां संभावित रूप से कोड अपडेट की आवश्यकता होती है।
Added the suggestions

2023-12-07 10:19 UTC, abhay-raj19 approved these changes
LGTM ! 
Thanks for contributing .

2023-12-12 19:26 UTC, merged