Create immutable-infrastructure.md
cncf/glossary pull request #2628
Opened 2023-11-15 15:52 UTC by ARYANis0001

### Describe your changes
Localize immutable-infrastructure.md in Hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1585 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-16 04:49 UTC, ARYANis0001 commented
Hey @bishal7679 can you please elaborate more about what changes you are expecting from this PR so that in the future I can take care of then

2023-11-17 05:44 UTC, seokho-son commented
> Hey @bishal7679 can you please elaborate more about what changes you are expecting from this PR so that in the future I will take care of them

Regarding `what changes you are expecting`

@ARYANis0001 I have a common comment on your PRs.
PTAL: https://github.com/cncf/glossary/pull/2605#issuecomment-1815774999

2023-11-21 13:43 UTC, ARYANis0001 commented
Hey @aj11anuj 
@kumarankit999
I have added some words to simplify it can you please review it

2023-11-21 17:47 UTC, kumarankit999 approved these changes
Thanks for Contributing this, lgtm!!

2023-11-22 09:46 UTC, ARYANis0001 commented
Hey @aj11anuj @bishal7679
I have added some words to simplify it can you please review it

2023-11-23 18:55 UTC, ankur0904 commented on content/hi/immutable-infrastructure.md
> +([वर्चुअल मशीन](/वर्चुअल-मशीन/, [कंटेनर](/कंटेनर/), नेटवर्क उपकरण)
```suggestion
([वर्चुअल मशीन](/वर्चुअल-मशीन/), [कंटेनर](/कंटेनर/), नेटवर्क उपकरण)
```

2023-11-23 19:05 UTC, ankur0904 commented on content/hi/immutable-infrastructure.md
> +बनाके या मौजूदा कंटेनर को उसकी छवि से पुनः बनाके ही किए जा सकते हैं
In this paragraph we are talking about the container image
छवि -> "Image(Picture)"
you can replace with `छवि` to `इमेज`

2023-11-23 19:10 UTC, ankur0904 requested changes
Some sentences are not clear. Please make sure to review it carefully.
e.g. line 12, 19

2023-11-23 19:14 UTC, ARYANis0001 commented
@ankur0904 Thanks any other suggestions

2023-11-24 04:40 UTC, ARYANis0001 reviewed
Signed-off-by: ARYANis0001 [devendergupta4573@gmail.com]

2023-11-28 15:00 UTC, aj11anuj requested changes

2023-11-29 04:13 UTC, Aryan-Singla commented
Hi @aj11anuj I have updated the suggestions

2023-12-13 17:39 UTC, closed without merging