Localised shift-left into hi
cncf/glossary pull request #2632
Opened 2023-11-17 21:30 UTC by abhay-raj19

### Describe your changes
Localised Shift left into hindi as suggested under #2061 

### Related issue number or link (ex: `resolves #issue-number`)
#2061 
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-21 17:36 UTC, kumarankit999 reviewed
Looking good here!
What about other Approvers! wait for them also!!

2023-12-01 17:54 UTC, Garima-Negi approved these changes
LGTM!

2023-12-03 17:02 UTC, ankur0904 approved these changes
LGTM :)

2023-12-03 17:21 UTC, kumarankit999 approved these changes
/lgtm

2023-12-04 14:32 UTC, aj11anuj requested changes

2023-12-04 14:32 UTC, aj11anuj commented on content/hi/shift-left.md
> +सुरक्षा समस्याएं, बग और सॉफ़्टवेयर के दोषों को सुधारना और ठीक करना अधिक कठिन और महंगा हो सकता है, अगर उन्हें विकास चक्र के दौरान या डिप्लॉयमेंट के पश्चात में खोजा जाता है, विशेषतः अगर सॉफ़्टवेयर पहले
```suggestion
सुरक्षा समस्याएं, बग और सॉफ़्टवेयर के दोषों को सुधारना और ठीक करना अधिक कठिन और महंगा हो सकता है, अगर उन्हें विकास चक्र के दौरान या डिप्लॉयमेंट के पश्चात खोजा जाता है, विशेषतः अगर सॉफ़्टवेयर पहले से ही उत्पादन में डिप्लॉय हो चुका हो।
```

2023-12-04 14:41 UTC, aj11anuj approved these changes
lgtm

2023-12-04 14:44 UTC, merged