[tw] Localize `Service Discovery` for Traditional Chinese
cncf/glossary pull request #2634
Opened 2023-11-19 23:39 UTC by soupstandstop

### Describe your changes
Origin content from https://glossary.cncf.io/service-discovery/

### Related issue number or link (ex: `resolves #issue-number`)
[2623](https://github.com/cncf/glossary/issues/2623)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-20 01:17 UTC, hanyuancheung approved these changes

2023-11-21 06:11 UTC, johnlinp requested changes

2023-11-21 06:11 UTC, johnlinp commented on content/zh-tw/service-discovery.md
> +服務探索是一個尋找可以組成服務之個別實體的過程
歡迎你加入團隊!
我這邊看到你在每個句子的結尾沒有標上標點符號，這樣子在網頁上看起來就會怪怪的，句子會全部黏在一起：
https://deploy-preview-2634--cncfglossary.netlify.app/zh-tw/service-discovery/

<img width="1728" alt="image" src="https://github.com/cncf/glossary/assets/1290376/c7569cde-19f6-4ec8-8516-33a276654c0b">

所以我這邊建議你可以在每個句子的結尾標上合適的標點符號，比方說逗號或是句號。

2023-11-21 12:35 UTC, soupstandstop commented on content/zh-tw/service-discovery.md
> +服務探索是一個尋找可以組成服務之個別實體的過程
你好John，很開心加入！
感謝你的建議，已經補上標點符號，再麻煩確認，非常感謝你！

2023-12-02 01:57 UTC, tico88612 commented on content/zh-tw/service-discovery.md
> +每一次的重新啟動，它都會被配發一個新的IP地址，所以當任一應用程式想要找到此服務時，都需要有工具來取得它的新IP地址資訊。
英文與中文之間需要加入空格
```suggestion
每一次的重新啟動，它都會被配發一個新的 IP 地址，所以當任一應用程式想要找到此服務時，都需要有工具來取得它的新 IP 地址資訊。
```

2024-02-03 17:13 UTC, pichuang approved these changes
LGTM

2024-02-03 17:13 UTC, merged