[FR] Localize `Transport Layer Security (TLS)`
cncf/glossary pull request #2641
Opened 2023-11-26 11:54 UTC by guillaumebernard84

### Describe your changes
[FR] Localize `Transport Layer Security (TLS)`

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2639

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-26 16:57 UTC, Krast76 commented on content/fr/transport-layer-security.md
> +title: Transport Layer Security (TLS)
Il y a des moments où on traduit les termes (Policy as Code par exemple) et là on les traduit pas. Je me demande si on devrait pas le faire partout tout en gardant l'acronyme qui est connu entre parenthèse ?

2023-11-26 16:57 UTC, Krast76 commented on content/fr/transport-layer-security.md
> +Il garantit la livraison sécurisée des données envoyées sur Internet,
j'aurais peut-être plutôt traduit ça de la manière suivante : Il garantie la sécurité des données lors de la livraison de celle-ci sur Internet. Je pinaille sûrement :)

2023-11-26 16:57 UTC, Krast76 commented on content/fr/transport-layer-security.md
> +que les données transmises entre elles sont chiffrées et ne peuvent pas être consultées par des tiers.
transmissent*

2023-11-26 18:20 UTC, guillaumebernard84 commented on content/fr/transport-layer-security.md
> +title: Transport Layer Security (TLS)
J'ai trouvé ça bizarre de traduire TLS, alors que dans la vraie vie on ne le dis jamais en entier. Mais effectivement on peut mettre "Sécurité de la couche de transport" et laisser l’acronyme entre parentheses. Qu'en pensent les autres?

2023-11-26 18:23 UTC, guillaumebernard84 commented on content/fr/transport-layer-security.md
> +Il garantit la livraison sécurisée des données envoyées sur Internet,
C'est mieux, même si c’est du pinaillage :p 
Je prends

2023-11-26 18:25 UTC, guillaumebernard84 commented on content/fr/transport-layer-security.md
> +que les données transmises entre elles sont chiffrées et ne peuvent pas être consultées par des tiers.
Hum, je ne pense pas, ce n'est pas un verbe ici. @sestegra tu confirmes?

2023-11-30 07:56 UTC, sestegra commented on content/fr/transport-layer-security.md
> +title: Transport Layer Security (TLS)
Dans ce cas, c'est un acronyme qui n'a pas d'équivalent en français.
Néanmoins, tous les autres termes ont été traduits.
Pour garder une traduction homogène, je propose de mettre "Sécurité de la couche de transport (TLS)" comme titre.

2023-11-30 08:02 UTC, sestegra commented on content/fr/transport-layer-security.md
> +que les données transmises entre elles sont chiffrées et ne peuvent pas être consultées par des tiers.
Je confirme. Ici, c'est un adjectif. donc "transmises".
Une astuce, si tu essaies de remplacer cet adjectif par un autre, comme "définies", la solution est trouvée.

2023-12-10 11:27 UTC, sestegra requested changes
Pour application client/server, je vais demander aux autres sur le Slack.

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +TLS permet une connexion chiffrée entre une application cliente et un serveur, par example un navigateur web et un site bancaire.
Typo sur `exemple`

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +en évitant toute consultation et/ou altération des données.
Je propose `interception` au lieu de `consultation`.
C'est le terme adapté à la sécurité des communications.

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +Sans TLS, les informations sensibles telles que les habitudes de navigation, la correspondance par courrier électronique, les discussions en ligne et les conférences téléphoniques peuvent facilement
Je propose de mettre `des informations sensibles`, c'est plus généraliste.

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +facilement être suivies et modifiées par d'autres personnes au cours de la transmission.
Traduction en double à supprimier. je préfère la 1ère phrase.

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +La prise en charge de TLS par les applications serveur et clientes garantit que
Je propose d'unifier le genre de serveur et client.
`par les applications serveur et client`
ou 
`par les applications serveurs et clientes`
Généralement, les termes "client" et "serveur" sont souvent utilisés pour désigner à la fois le singulier et le pluriel, sans distinction de genre.
En effet, au singulier, on dit plutôt `application client` et `application serveur`, pour moi, c'est la contraction de `application de type client` et `application de type serveur`.

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +TLS permet une connexion chiffrée entre une application cliente et un serveur, par example un navigateur web et un site bancaire.
Même remarque  `application client`

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +Il permet également aux applications clientes d'identifier avec certitude le serveur auquel elles s'adressent,
Même remarque `applications client`

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +ce qui réduit le risque qu'une application cliente se connecte à un site frauduleux.
Même remarque `applications client`

2023-12-10 11:27 UTC, sestegra commented on content/fr/transport-layer-security.md
> +Le protocole TLS garantit que des tiers ne peuvent pas consulter les données transmises entre les applications utilisant le protocole TLS,
Même remarque pour remplacer `consulter` par `intercepter`

2023-12-17 18:59 UTC, guillaumebernard84 commented on content/fr/transport-layer-security.md
> +La prise en charge de TLS par les applications serveur et clientes garantit que
Si je me rappelle bien notre discussion de mercredi, on laisse "applications clientes". Dis moi si je me trompe!

2023-12-17 19:46 UTC, sestegra commented on content/fr/transport-layer-security.md
> +La prise en charge de TLS par les applications serveur et clientes garantit que
C'est cela, oui.

2023-12-17 19:58 UTC, guillaumebernard84 commented on content/fr/transport-layer-security.md
> +La prise en charge de TLS par les applications serveur et clientes garantit que
Bien vu!

2023-12-18 14:40 UTC, sestegra approved these changes
🚀 LGTM

2023-12-30 18:45 UTC, Krast76 reviewed
Un dernier petit truc avant un LGTM bien mérité :)

2023-12-30 18:45 UTC, Krast76 commented on content/fr/transport-layer-security.md
> +que les données transmises entre elles sont chiffrées et ne peuvent pas être consultées par des tiers.
Il y a deux fois "que", fin de ligne 16 et début de ligne 17

2024-01-02 09:56 UTC, Krast76 approved these changes
LGTM 🚀

2024-01-02 09:56 UTC, merged