[hi] Localize  Tightly Coupled Architectures in hindi.
cncf/glossary pull request #2643
Opened 2023-11-26 14:52 UTC by Aarav238

Signed-off-by : Aarav238 [aarav8090shukla@gmail.com](mailto:aarav8090shukla@gmail.com)

### Describe your changes
I have localized the ` Tightly Coupled Architectures ` in hindi.

### resolves #2640 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-26 17:39 UTC, kumarankit999 reviewed
Hey @Aarav238, Thanks for raising this PR, but check the above error!

2023-11-26 17:40 UTC, kumarankit999 commented
Netlify build has been failed!

2023-11-26 17:41 UTC, Aarav238 commented
@kumarankit999 How I can resolve it ?

2023-11-27 19:14 UTC, Aarav238 commented
I have resolved them @kumarankit999

2023-12-01 02:03 UTC, abhay-raj19 approved these changes
LGTM 👍
Thanks for contributing @Aarav238

2023-12-01 17:06 UTC, kumarankit999 reviewed
Looking Fixed Now!!!

2023-12-01 17:07 UTC, Aarav238 commented
Please approve this @kumarankit999 .

2023-12-01 17:16 UTC, kumarankit999 approved these changes
Thanks for Contributing!!!

2023-12-01 17:17 UTC, kumarankit999 commented
@bishal7679 check this one PR!

2023-12-01 17:27 UTC, Garima-Negi requested changes

2023-12-01 17:27 UTC, Garima-Negi commented on content/hi/tightly-coupled-architecture.md
> +title: साइट विश्वसनीयता इंजीनियरिंग (Tightly Coupled Architecture)
Hi can we please replace साइट विश्वसनीयता इंजीनियरिंग with टाइट्ली कपल्ड आर्किटेक्चर

2023-12-01 17:27 UTC, Garima-Negi commented on content/hi/tightly-coupled-architecture.md
> +कसकर युग्मित वास्तुकला एक वास्तुशिल्प शैली है जहां कई अनुप्रयोग घटक एक दूसरे पर निर्भर होते हैं (शिथिल रूप से युग्मित वास्तुकला के विपरीत प्रतिमान)। इसका मतलब यह है कि एक घटक में बदलाव से अन्य घटकों
Similarly here, please replace with exact words rather than rarely used words.

2023-12-01 17:38 UTC, ankur0904 commented on content/hi/tightly-coupled-architecture.md
> +कसकर युग्मित वास्तुकला एक वास्तुशिल्प शैली है जहां कई अनुप्रयोग घटक एक दूसरे पर निर्भर होते हैं (शिथिल रूप से युग्मित वास्तुकला के विपरीत प्रतिमान)। इसका मतलब यह है कि एक घटक में बदलाव से अन्य घटकों
```suggestion
टाइटली कपल आर्किटेक्चर एक आर्किटेक्चर शैली है जहां कई अनुप्रयोग घटक एक दूसरे पर निर्भर होते हैं (लूसली कपल आर्किटेक्चर के विपरीत प्रतिमान)। इसका मतलब यह है कि एक घटक में बदलाव से अन्य घटकों पर असर पड़ने की संभावना है। आम तौर पर अधिक लूसली कपल आर्किटेक्चर की तुलना में इसे लागू करना आसान होता है, लेकिन यह सिस्टम को कैस्केडिंग विफलताओं के प्रति अधिक संवेदनशील बना सकता है। उन्हें घटकों के समन्वित रोलआउट की भी आवश्यकता होती है जो डेवलपर उत्पादकता पर दबाव बन सकता है।
```

2023-12-01 17:39 UTC, ankur0904 commented on content/hi/tightly-coupled-architecture.md
> +कसकर युग्मित एप्लिकेशन आर्किटेक्चर अनुप्रयोगों के निर्माण का एक काफी पारंपरिक तरीका है। हालांकि जरूरी नहीं कि वे माइक्रोसर्विस विकास की सभी सर्वोत्तम प्रथाओं के अनुरूप हों, लेकिन वे विशिष्ट परिस्थिति
```suggestion
टाइटली कपल आर्किटेक्चर अनुप्रयोगों के निर्माण का एक काफी पारंपरिक तरीका है। हालांकि जरूरी नहीं कि वे माइक्रोसर्विस विकास की सभी सर्वोत्तम प्रथाओं के अनुरूप हों, लेकिन वे विशिष्ट परिस्थितियों में उपयोगी हो सकते हैं। वे लागू करने में तेज़ और सरल होते हैं और मोनोलिथिक अनुप्रयोगों की तरह वे प्रारंभिक विकास चक्र को गति दे सकते हैं।
```

2023-12-01 17:42 UTC, ankur0904 requested changes
Please have a look. `कसकर युग्मित वास्तुकला` doesn't make sense and same for others.

cc: @Garima-Negi

2023-12-01 17:50 UTC, Garima-Negi requested changes

2023-12-01 18:01 UTC, Aarav238 commented
I have replaced all the words with exact words. @Garima-Negi  @abhay-raj19 @kumarankit999 @bishal7679 Please review.

2023-12-01 18:01 UTC, Garima-Negi commented on content/hi/tightly-coupled-architecture.md
> +टाइट्ली कपल्ड आर्किटेक्चर एक आर्किटेक्चर शैली है जहां कई अनुप्रयोग घटक एक दूसरे पर निर्भर होते हैं (लूसली कपल आर्किटेक्चर के विपरीत प्रतिमान)। इसका मतलब यह है कि एक घटक में बदलाव से अन्य घटकों पर असर
```suggestion
टाइट्ली कपल्ड आर्किटेक्चर एक आर्किटेक्चर शैली है जहां कई अनुप्रयोग घटक एक दूसरे पर निर्भर होते हैं (लूज़ली कपल्ड आर्किटेक्चर के विपरीत प्रतिमान)। इसका मतलब यह है कि एक घटक में बदलाव से अन्य घटकों पर असर पड़ने की संभावना है। आम तौर पर अधिक लूज़ली कपल्ड आर्किटेक्चर की तुलना में इसे लागू करना आसान होता है, लेकिन यह सिस्टम को कैस्केडिंग विफलताओं के प्रति अधिक संवेदनशील बना सकता है। उन्हें घटकों के समन्वित रोलआउट की भी आवश्यकता होती है जो डेवलपर उत्पादकता पर दबाव बन सकता है।
```

2023-12-01 18:03 UTC, Garima-Negi approved these changes

2023-12-01 18:03 UTC, merged

2023-12-01 18:03 UTC, Aarav238 commented
Thanks @Garima-Negi .

2023-12-02 03:06 UTC, kumarankit999 commented
Thanks for contributing @Aarav238