[tr] Add Turkish localization for infrastructure-as-code.md
cncf/glossary pull request #2645
Opened 2023-11-26 15:55 UTC by rwxdash

### Describe your changes

- Added Turkish localization for infrastructure-as-code.md

Google Docs for reference

- [`infrastructure-as-code.md`](https://docs.google.com/document/d/13LmCPLw-FTBkBaFaZlAeYYpHABJd4gRxbxrArWjINhE)

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-26 16:47 UTC, eminalemdar requested changes
Eline sağlık @rwxdash fakat direkt olarak kelime kelime çevirilerden kaçınmak daha iyi olur. Çünkü dil yapılarının farklılıklarından dolayı bazen kendi dilimize göre değişik ifadeler eklememiz daha mantıklı olacaktır.

2023-11-26 16:47 UTC, eminalemdar commented on content/tr/infrastructure-as-code.md
> +hell betiği veya diğer yapılandırma araçları aracılığıyla manuel olarak sağlandığı geleneksel modelin yerini alır.
```suggestion
bir shell script veya diğer yapılandırma araçları aracılığıyla manuel olarak oluşturulduğu geleneksel modelin yerini alır.
```

2023-11-26 16:47 UTC, eminalemdar commented on content/tr/infrastructure-as-code.md
> +Manuel provizyon, bulut tabanlı uygulamaların yanıt verme ve ölçeklendirme gereksinimlerini karşılayamaz.
```suggestion
Altyapı kaynaklarının manuel olarak oluşturulması, bulut tabanlı uygulamaların yanıt verme ve ölçeklendirme gereksinimlerini karşılayamaz.
```

2023-11-26 16:47 UTC, eminalemdar commented on content/tr/infrastructure-as-code.md
> +ve aynı zamanda sürüm kontrolü ve dağıtım stratejilerini uygulayarak veri merkezlerini
```suggestion
ve aynı zamanda versiyon kontrolü ve dağıtım stratejilerini uygulayarak veri merkezlerini
```

2023-11-27 06:51 UTC, aliok approved these changes
LGTM
Leaving final approval to @eminalemdar

2023-11-27 08:17 UTC, eminalemdar approved these changes
LGTM

2023-11-27 09:04 UTC, merged