[FR] Localize `Mutual Transport Layer Security (mTLS)`
cncf/glossary pull request #2648
Opened 2023-11-27 19:52 UTC by guillaumebernard84

### Describe your changes
Localize `Mutual Transport Layer Security (mTLS)` in French

### Related issue number or link (ex: `resolves #issue-number`)
solves https://github.com/cncf/glossary/issues/2647

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-28 09:40 UTC, Krast76 commented on content/fr/mutual-transport-layer-security.md
> +title: Mutual Transport Layer Security (mTLS)
Je suis pour, avec mTLS entre parenthèse ?

2023-11-30 08:15 UTC, sestegra commented on content/fr/mutual-transport-layer-security.md
> +title: Mutual Transport Layer Security (mTLS)
Pour les mêmes raison que TLS, je propose "Sécurité mutuelle de la couche de transport (mTLS)"

2023-12-10 11:28 UTC, sestegra requested changes
Super, j'ai découvert le terme `on-path attack` qui remplace le terme non inclusif de main-in-the-middle.

2023-12-17 19:51 UTC, sestegra approved these changes
🚀 LGTM

2023-12-30 18:41 UTC, Krast76 approved these changes
LGTM 👍

2023-12-30 18:41 UTC, merged