Translated all ES tags
cncf/glossary pull request #2651
Opened 2023-11-29 10:22 UTC by JorgePRamos

### Describe your changes
Translated all ES tags

### Related issue number or link (ex: `resolves #issue-number`)
#2294 
### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-11-29 15:44 UTC, electrocucaracha requested changes
Muchas gracias @JorgePRamos, por traducir las etiquetas de todos los documentos del glosario. Al parecer has incluido cambios en las ligas, lo cual terminan apuntando a documentos no existentes (404). Por último, agregué la traducción de `fundamental` como `fundamento`.

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/api-gateway.md
> +Un [API](/es/aplicación-programming-interface/) gateway es una herramienta que
```suggestion
Un [API](/es/application-programming-interface/) gateway es una herramienta que
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/containerization.md
> +Adicionalmente, las máquinas virtuales pueden sufrir variaciones en la configuración, lo cuál contradice el principio de [inmutabilidad](/es/immutable-infraestructura/).
```suggestion
Adicionalmente, las máquinas virtuales pueden sufrir variaciones en la configuración, lo cuál contradice el principio de [inmutabilidad](/es/immutable-infrastructure/).
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/event-streaming.md
> +Yahoo! Finance proporciona una [API](/es/aplicación-programming-interface/) que extrae de NASDAQ y envía (o transmite) la información (o eventos) de su aplicación a cualquier aplicación que se suscri
```suggestion
Yahoo! Finance proporciona una [API](/es/application-programming-interface/) que extrae de NASDAQ y envía (o transmite) la información (o eventos) de su aplicación a cualquier aplicación que se suscriba a ella.
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/function-as-a-service.md
> +típicamente asociada con la creación y lanzamiento de aplicaciones en [arquitectura de microservicios](/es/microservices-arquitectura/).
```suggestion
típicamente asociada con la creación y lanzamiento de aplicaciones en [arquitectura de microservicios](/es/microservices-architecture/).
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/function-as-a-service.md
> +Bajo un modelo estándar de computación en la nube basado en [Infraestructura como Servicio (IaaS)](/es/infraestructura-as-a-service/),
```suggestion
Bajo un modelo estándar de computación en la nube basado en [Infraestructura como Servicio (IaaS)](/es/infrastructure-as-a-service/),
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/immutable-infrastructure.md
> +La infraestructura inmutable va de la mano con [infraestructura como código](/es/infraestructura-as-code/)
```suggestion
La infraestructura inmutable va de la mano con [infraestructura como código](/es/infrastructure-as-code/)
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/kubernetes.md
> +Kubernetes puede ser extendido a través de su [API](/es/aplicación-programming-interface/), permitiendo aprovechar la automatización de Kubernetes y hacer que sus herramientas sean más accesibles par
```suggestion
Kubernetes puede ser extendido a través de su [API](/es/application-programming-interface/), permitiendo aprovechar la automatización de Kubernetes y hacer que sus herramientas sean más accesibles para profesionistas experimentados de Kubernetes.
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/kubernetes.md
> +De manera parecida a las herramientas tradicionales de [infraestructura como código](/es/infraestructura-as-code/), Kubernetes ayuda con la automatización pero tiene la ventaja de trabajar con conten
```suggestion
De manera parecida a las herramientas tradicionales de [infraestructura como código](/es/infrastructure-as-code/), Kubernetes ayuda con la automatización pero tiene la ventaja de trabajar con contenedores.
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/managed-services.md
> +con límites bien definidos y, por lo general impulsados por la [API](/es/aplicación-programming-interface/).
```suggestion
con límites bien definidos y, por lo general impulsados por la [API](/es/application-programming-interface/).
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/multitenancy.md
> +que los inquilinos se conecten a través de la red mediante una interfaz y/o una [API](/es/aplicación-programming-interface/)
```suggestion
que los inquilinos se conecten a través de la red mediante una interfaz y/o una [API](/es/application-programming-interface/)
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/multitenancy.md
> +(consulte también [Arquitectura Cliente-Servidor](/es/client-server-arquitectura/)).
```suggestion
(consulte también [Arquitectura Cliente-Servidor](/es/client-server-architecture/)).
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/mutual-transport-layer-security.md
> +mTLS es el protocolo de [Seguridad de capa de transporte](/es/transport-layer-seguridad/) (TLS) estándar pero,
```suggestion
mTLS es el protocolo de [Seguridad de capa de transporte](/es/transport-layer-security/) (TLS) estándar pero,
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/mutual-transport-layer-security.md
> +Los [microservicios](/es/microservices-arquitectura/) se comunican a través de una red y,
```suggestion
Los [microservicios](/es/microservices-architecture/) se comunican a través de una red y,
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/portability.md
> +tags: ["fundamental", "propiedad", ""]
```suggestion
tags: ["fundamento", "propiedad", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/serverless.md
> +En un modelo de [Infraestructura como Servicio](/es/infraestructura-as-a-service/),
```suggestion
En un modelo de [Infraestructura como Servicio](/es/infrastructure-as-a-service/),
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/service-mesh.md
> +En un mundo de [arquitectura de microservicios](/es/microservices-arquitectura/), las aplicaciones se dividen en múltiples [servicios](/es/service/) que se comunican a través de una red.
```suggestion
En un mundo de [arquitectura de microservicios](/es/microservices-architecture/), las aplicaciones se dividen en múltiples [servicios](/es/service/) que se comunican a través de una red.
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/service.md
> +Por favor, consulte la definición de [microservicios](/es/microservices-arquitectura/).
```suggestion
Por favor, consulte la definición de [microservicios](/es/microservices-architecture/).
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/software-as-a-service.md
> +tags: ["fundamental", "plataforma", ""]
```suggestion
tags: ["fundamento", "plataforma", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/stateful-apps.md
> +tags: ["fundamental", "aplicación", ""]
```suggestion
tags: ["fundamento", "aplicación", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/stateless-apps.md
> +tags: ["fundamental", "aplicación", ""]
```suggestion
tags: ["fundamento", "aplicación", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/style-guide/_index.md
>  - fundamental
```suggestion
- fundamento
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/tightly-coupled-architectures.md
> +(es el paradigma opuesto a [arquitectura débilmente acoplada](/es/loosely-coupled-arquitectura/)).
```suggestion
(es el paradigma opuesto a [arquitectura débilmente acoplada](/es/loosely-coupled-architecture/)). 
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/monolithic-apps.md
> +tags: ["arquitectura", "fundamental", ""]
```suggestion
tags: ["arquitectura", "fundamento", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/nodes.md
> +tags: ["infraestructura", "fundamental", ""]
```suggestion
tags: ["infraestructura", "fundamento", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/reliability.md
> +tags: ["fundamental", "propiedad", ""]
```suggestion
tags: ["fundamento", "propiedad", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/scalability.md
> +tags: ["fundamental", "propiedad", ""]
```suggestion
tags: ["fundamento", "propiedad", ""]
```

2023-11-29 15:44 UTC, electrocucaracha commented on content/es/service.md
> +tags: ["aplicación", "fundamental", ""]
```suggestion
tags: ["aplicación", "fundamento", ""]
```

2023-11-29 16:42 UTC, JorgePRamos commented
@electrocucaracha Muchas gracias por las correcciones. 
Debí haber excluido las ligas de mi búsqueda RegEx, a veces es mejor no hacer las cosas más despacio.
Un saludo.

2024-01-05 16:46 UTC, ramrodo commented
Hola @JorgePRamos, gracias por abrir este PR.

¿Tienes planeado incorporar las sugerencias recibidas para poder continuar con la revisión y posterior merge de éste PR?

Avísanos si hay algo en lo que podemos ayudarte :)

2024-01-06 01:39 UTC, JorgePRamos commented
Buenas @ramrodo, pensaba que @electrocucaracha había corregido mi error y estaba listo para el merge. Si no es así. Por favor indícame qué debería hacer.
Muchas gracias y perdón por las molestias

2024-01-06 06:30 UTC, ramrodo commented
> Buenas @ramrodo, pensaba que @electrocucaracha había corregido mi error y estaba listo para el merge. Si no es así. Por favor indícame qué debería hacer. Muchas gracias y perdón por las molestias

Buenas @JorgePRamos, no te preocupes, no es ninguna molestia.

Aún no se han aplicado las sugerencias. Le puedes dar clic en el botón que dice _Sign off and commit suggestion_ para aplicar cada sugerencia.

De igual forma, el branch ya se quedo atrasado. Habría que actualizarlo con respecto a main.

2024-01-30 22:57 UTC, ramrodo commented
Hola @JorgePRamos, solo un amable recordatorio para continuar con éste PR. Avísanos si necesitas ayuda o si gustas que lo completemos nosotros :)

2024-01-31 16:38 UTC, JorgePRamos commented
He añadido todas las sugerencias y resuleto los conflictos que imagino se daban por que la branch se habia quedado por detrás.
Espero que todo este bien.
Gracias por la ayuda.

2024-01-31 18:28 UTC, electrocucaracha commented on content/es/platform-as-a-service.md
> +
nit:
```suggestion
```

2024-01-31 18:29 UTC, electrocucaracha commented on content/es/service-mesh.md
> +
```suggestion
```

2024-01-31 18:29 UTC, electrocucaracha commented on content/es/transport-layer-security.md
> +
```suggestion
```

2024-01-31 18:30 UTC, electrocucaracha approved these changes

2024-02-06 16:54 UTC, ramrodo approved these changes
Thanks!

2024-02-06 16:54 UTC, merged