[tw] Remove what-it-is header from all TW docs
cncf/glossary pull request #2664
Opened 2023-12-02 01:44 UTC by tico88612

### Describe your changes

- Remove `what-it-is` header from all TW docs
- Follow #2575 

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2662

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-02 17:54 UTC, johnlinp approved these changes
LGTM

2023-12-02 18:01 UTC, johnlinp requested changes

2023-12-02 18:01 UTC, johnlinp commented on content/zh-tw/style-guide/_index.md
> -
不好意思，我注意到底下 "三個小標題" 的部份也需要修改，
再麻煩你幫忙，謝謝!

2023-12-03 05:53 UTC, johnlinp approved these changes
感謝!

2023-12-03 09:41 UTC, ydFu requested changes
Large-scale file changes need to be confirmed one by one to see if there are other updates.

2023-12-03 20:18 UTC, johnlinp commented
@tico88612 哈囉，我想 @ydFu 的意思是說，當我們在修改多個檔案的內容時，我們會需要確認英文版的內容有沒有在這期間被更新。我想這樣是為了避免到時候編輯的時序錯亂，造成之後更新的困難。

但我剛剛掃了一下，看起來你的檔案都已經跟到英文版的最新版了，所以我覺得這部份應該是沒問題的，謝謝。

2023-12-03 23:01 UTC, pichuang approved these changes
Confirmed and thx

2023-12-04 12:13 UTC, hwchiu approved these changes
LGTM

2023-12-05 02:56 UTC, ydFu commented on content/zh-tw/_TEMPLATE.md
>  快速總結概念及其意義。
```suggestion
快速總結概念。
```

Miss this change

https://github.com/cncf/glossary/pull/2652

2023-12-05 02:56 UTC, ydFu commented on content/zh-tw/style-guide/_index.md
Miss this change.

https://github.com/cncf/glossary/pull/2652/files#diff-f0035a3662384e762cfe06bd4661211988eae9f632b7e5ab740ef932a16df1acR82

2023-12-05 02:56 UTC, ydFu commented on content/zh-tw/cloud-native-tech.md
> -
miss this change

https://github.com/cncf/glossary/pull/2471

2023-12-05 03:11 UTC, ydFu commented
> @tico88612 哈囉，我想 @ydFu 的意思是說，當我們在修改多個檔案的內容時，我們會需要確認英文版的內容有沒有在這期間被更新。我想這樣是為了避免到時候編輯的時序錯亂，造成之後更新的困難。
> 
> 但我剛剛掃了一下，看起來你的檔案都已經跟到英文版的最新版了，所以我覺得這部份應該是沒問題的，謝謝。

誠如上述所敘，在進行詳盡補充，
英文內容可以大量檔案相關異動更新
與本地化語系內容大量不適合有相關異動更新，
最大的差別是本地化內容同時可能會有多個其他相關更新，
並不只侷限於這個PR。

從Approver的審核視角，多半已會依照上次更新內容與您提供的相關PR review，
如果沒有檢查到或是miss掉就會發生本地化與英文內容越來越脫鉤的議題，
你仔細觀察本專案中簡體中文就有這種問題。

而從本PR就我部份review的內容就有發現3個以上沒有被更新到，
其他有沒有相關沒有被更新到的問題，一次44個檔案也無法進行保證。

所以我的建議本次更新不需要再一個PR中就完成，
可以在一個issue開多個子任務分批完成。

2023-12-05 03:11 UTC, closed without merging