Stateless statefull update noah
cncf/glossary pull request #2685
Opened 2023-12-06 15:19 UTC by iamNoah1

### Describe your changes
Follow up for #1731 

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-07 05:52 UTC, hlipsig requested changes
Suggestions made to improve clarity of language.  No technical issues noted.

2023-12-07 05:52 UTC, hlipsig commented on content/en/stateless-apps.md
> +Stateless applications process requests as if they were their first.
```suggestion
Stateless applications process requests as if each request were the first it's ever been sent. 
```

2023-12-07 07:25 UTC, seokho-son commented
Hi @iamNoah1 
https://github.com/cncf/glossary/pull/2684#pullrequestreview-1769373067 updated the wordlist.txt 
So, this PR does not need to include it. :)

2023-12-07 22:41 UTC, hlipsig approved these changes
LGTM

2023-12-09 01:20 UTC, nate-double-u approved these changes
Thanks for the update, /lgtm

2023-12-09 21:11 UTC, iamNoah1 commented on content/en/stateful-apps.md
> +status: Feedback Appreciated
```suggestion
status: Completed
```

2023-12-09 21:11 UTC, iamNoah1 commented on content/en/stateless-apps.md
> + status: Feedback Appreciated
```suggestion
 status: Completed
```

2023-12-09 21:12 UTC, iamNoah1 commented
thanks @nate-double-u and @hlipsig for the lgtm, @seokho-son I removed my changes on the wordlist again and merged main.

2023-12-11 05:20 UTC, seokho-son approved these changes
LGTM! Let me merge this PR.

2023-12-11 05:21 UTC, merged