[ja] Localize Containerization for Japanese
cncf/glossary pull request #2687
Opened 2023-12-07 06:40 UTC by Okabe-Junya

### Describe your changes

- Localize Containerization for Japanese

### Related issue number or link (ex: `resolves #issue-number`)

closes #2598 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-07 13:25 UTC, kaitoii11 requested changes

2023-12-07 13:25 UTC, kaitoii11 commented on content/ja/containerization.md
> +これらの大きなVMテンプレートのストレージ、バックアップ、転送により、VMテンプレートの作成もより遅くなります。
```suggestion
このようなの大きなVMテンプレートのストレージ、バックアップ、転送により、VMテンプレートの作成もより遅くなります。
```

2023-12-07 13:57 UTC, Okabe-Junya commented on content/ja/containerization.md
> +これらの大きなVMテンプレートのストレージ、バックアップ、転送により、VMテンプレートの作成もより遅くなります。
> このような大きな

への変更案ということだと思ったのですが、形容詞が連続する場合は

- このように大きな

の方が自然なのではないかと考えていました。ただ、「このように大きな」という表現だと英語では "in this way" と意味になってしまうのではないかと思い、 "these" は素直に「これらの」と翻訳しました

2023-12-07 14:05 UTC, Okabe-Junya commented on content/ja/containerization.md
> +さらに、VMは[不変性](/ja/immutable-infrastructure/)の原則に反する設定のずれに悩まされることがあります。
少し調べてみたのですが、

IBMのterraformの[日本語ドキュメント](https://www.ibm.com/jp-ja/topics/terraform) では、「構成のずれ」「構成のドリフト」という表現が用いられていました。

> 構成のずれを防ぐ：構成のドリフトは、環境をプロビジョニングした構成が実際の環境と一致しなくなったときに発生します。

VMwareのドキュメントの中には、[構成ドリフト バンドルの適用](https://docs.vmware.com/jp/VMware-Cloud-Foundation/4.1/vcf-41-lifecycle/GUID-FC2B3247-9080-40CC-9B24-CCB0B7A428EB.html) という項目が確かにあるので、「構成ドリフト」あるいは「構成のずれ」という表現が適切そうですね。

この箇所に関しては、他のreviewerの方の意見も参考にしたいので、一旦保留させてください

2023-12-13 06:29 UTC, naonishijima commented on content/ja/containerization.md
> +さらに、VMは[不変性](/ja/immutable-infrastructure/)の原則に反する設定のずれに悩まされることがあります。
ご参考としてSecurity White Paperの翻訳では「構成ドリフト」としました。
https://github.com/cncf/tag-security/blob/main/security-whitepaper/v2/cloud-native-security-whitepaper-ja.md

2023-12-13 14:48 UTC, Okabe-Junya commented on content/ja/containerization.md
> +さらに、VMは[不変性](/ja/immutable-infrastructure/)の原則に反する設定のずれに悩まされることがあります。
お二方ともありがとうございます。構成ドリフトが良さそうなので、そのようにしたいと思います。

https://github.com/cncf/glossary/pull/2687/commits/e9f4e166390b134e1bcf192752305c91aaa63e4e で修正を行いました。

2023-12-13 14:52 UTC, naonishijima commented on content/ja/containerization.md
> +常に初期状態にリセットされるため、設定のずれが解消されます。
ここも「設定のずれ」があるので「構成ドリフト」でお願いします。

2023-12-13 14:53 UTC, Okabe-Junya commented on content/ja/containerization.md
> +常に初期状態にリセットされるため、設定のずれが解消されます。
https://github.com/cncf/glossary/pull/2687/commits/a6a788deb8595c2254de1bf3a1e168fff776b55b で修正しました

2023-12-14 14:24 UTC, naonishijima approved these changes
LGTM

2023-12-14 14:24 UTC, merged