Create distributed-systems.md
cncf/glossary pull request #2708
Opened 2023-12-13 17:35 UTC by Aryan-Singla

Signed off by: Aryan-Singla [devendergupta4573@gmail.com]

### Describe your changes
Localize Distributed System in Hindi in hindi

### Related issue number or link (ex: `resolves #issue-number`)
resolves #1300 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-01 14:20 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +एक नेटवर्क पर जुड़ा हुआ है जो उपयोगकर्ताओं को एकल सुसंगत प्रणाली के रूप में दिखाई देता है।
```suggestion
जो एक नेटवर्क पर जुड़ा हुआ है और उपयोगकर्ताओं को एकल सुसंगत प्रणाली के रूप में दिखाई देता है।
```

2024-01-01 14:24 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +आम तौर पर [नोड्स](/nodes/) के रूप में संदर्भित, ये घटक हार्डवेयर डिवाइस (जैसे कंप्यूटर, मोबाइल फोन) या सॉफ्टवेयर प्रक्रियाएं हो सकते हैं।
```suggestion
आम तौर पर [नोड्स](/nodes/) के रूप में संदर्भित, ये भाग हार्डवेयर डिवाइस जैसे - कंप्यूटर, मोबाइल फोन या सॉफ्टवेयर प्रक्रियाएं हो सकते हैं।
```

2024-01-01 14:37 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +इसे स्वचालित किया जा सकता है जिससे सिस्टम कार्यभार या संसाधन खपत में अचानक वृद्धि को संभाल सकता है।
```suggestion
इसे स्वचालित किया जा सकता है जिससे सिस्टम के कार्यभार या संसाधन की खपत में अचानक हुई वृद्धि को संभालना सरल हो सके।
```

2024-01-01 14:38 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +भले ही कुछ मशीनें खराब हो जाएं, फिर भी समग्र प्रणाली समान परिणाम देने के लिए काम करना जारी रख सकती है।
```suggestion
भले ही कुछ मशीनें खराब हो जाएं, फिर भी समग्र प्रणाली समान परिणाम देने के लिए काम करना जारी रख सके।
```

2024-01-02 17:58 UTC, kumarankit999 reviewed
Otherwise it looks good!

2024-01-28 16:41 UTC, Aryan-Singla commented
Hello @aj11anuj if you have bandwidth then Please check this localization is there any need for improvement

2024-02-07 10:25 UTC, aj11anuj requested changes
Replace 'वितरित', 'गैर-वितरित', 'प्रणाली', 'सुसंगत', 'स्वायत्त' words with relevant alternative, wherever you have used them.

2024-02-07 10:25 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +जीमेल या नेटफ्लिक्स के बारे में सोचें। कोई भी कंप्यूटर संपूर्ण एप्लिकेशन को होस्ट करने के लिए पर्याप्त शक्तिशाली नहीं है।
```suggestion
जी-मेल या नेटफ्लिक्स के बारे में सोचें। कोई भी कंप्यूटर संपूर्ण एप्लिकेशन को होस्ट करने के लिए पर्याप्त शक्तिशाली नहीं है।
```

2024-02-07 11:57 UTC, Aryan-Singla commented
> Replace 'वितरित', 'गैर-वितरित', 'प्रणाली', 'सुसंगत', 'स्वायत्त' words with relevant alternative, wherever you have used them.
Update all the items with other words

2024-02-09 10:36 UTC, aj11anuj requested changes
.

2024-02-09 10:36 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +डिसटीब्यूट कंप्यूटिंग के बिना, आज जिन कई अनुप्रयोगों पर हम भरोसा करते हैं, वे संभव नहीं होंगे।
```suggestion
डिस्ट्रिब्यूटेड कंप्यूटिंग के बिना, आज जिन कई अनुप्रयोगों पर हम भरोसा करते हैं, वे संभव नहीं होंगे।
```

2024-02-09 10:36 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +तभी आप किसी व्यक्तिगत मशीन में अधिक सीपीयू या मेमोरी जोड़ते हैं।
```suggestion
तभी आप किसी व्यक्तिगत मशीन में अधिक सीपीयू या मेमोरी जोड़ पाते हैं।
```

2024-02-09 10:36 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +डिस्ट्रिब्यूटेड सिस्टम [होरिजेंटल स्केलिंग](/horizontal-scaling/) की अनुमति देती हैं (उदाहरण के लिए जब भी जरूरत हो सिस्टम में अधिक नोड्स जोड़ना)।
```suggestion
डिस्ट्रिब्यूटेड सिस्टम [होरिजेंटल स्केलिंग](/horizontal-scaling/) की अनुमति देती हैं (उदाहरण के लिए जरूरत के समय सिस्टम में अधिक नोड्स जोड़ना)।
```

2024-02-09 10:36 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +एक नॉन डिसटीब्यूट सिस्टम विफलता के जोखिमों को उजागर करती है क्योंकि यदि एक मशीन विफल हो जाती है, तो पूरी सिस्टम विफल हो जाती है।
```suggestion
एक नॉन-डिस्ट्रिब्यूटेड सिस्टम विफलता के जोखिमों को उजागर करती है क्योंकि यदि एक मशीन विफल हो जाती है, तो पुरा सिस्टम विफल हो जाता है।
```

2024-02-09 10:36 UTC, aj11anuj commented on content/hi/distributed-systems.md
> +एक डिसटीब्यूट सिस्टम को इस तरह से डिज़ाइन किया जा सकता है कि,
```suggestion
एक डिस्ट्रिब्यूटेड सिस्टम को इस तरह से डिज़ाइन किया जा सकता है कि,
```

2024-02-09 11:18 UTC, aj11anuj approved these changes
Lgtm

2024-02-09 18:12 UTC, bishal7679 commented
@Aryan-Singla Pls keep patience!
Will review this PR for final soon

2024-02-09 18:19 UTC, Aryan-Singla commented
@bishal7679 Yes bishal I have no hurry

2024-05-25 06:27 UTC, Aryan-Singla commented
@bishal7679 Please check PR pending from long time

2024-05-26 04:28 UTC, Aryan-Singla commented
@bishal7679 Also check this

2024-05-30 04:25 UTC, Aryan-Singla commented
Hello @kumarankit999, @aj11anuj, @abhay-raj19. I think @bishal7679 is busy nowadays. Can you please check and merge this PR? It's been pending for a long time, and we've all invested time in this localization.

2024-05-30 13:54 UTC, abhay-raj19 approved these changes
Looks Good to me !!
Would love to see your contribution to Glossary !

2024-05-30 14:08 UTC, bishal7679 commented on content/hi/distributed-systems.md
> +## यह समस्या का समाधान करता है
```suggestion
## समस्या
```

2024-05-30 14:08 UTC, bishal7679 commented
Delete the lines from 33 - 35

2024-05-30 14:11 UTC, Aryan-Singla commented
@bishal7679 Check now

2024-05-30 14:16 UTC, bishal7679 commented on content/hi/distributed-systems.md
> +भले ही कुछ मशीनें खराब हो जाएं, फिर भी समग्र सिस्टम समान परिणाम देने के लिए काम करना जारी रख सके।
```suggestion
भले ही कुछ मशीनें खराब हो जाएं, फिर भी समग्र सिस्टम समान परिणाम देने के लिए काम करना जारी रख सके।

```

2024-05-30 14:16 UTC, merged

2024-05-30 15:06 UTC, abhay-raj19 commented
Thanks for contributing to Glossary @Aryan-Singla !!