2532 german localize continuous integration
cncf/glossary pull request #2732
Opened 2023-12-18 06:39 UTC by DaveVentura

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-30 15:30 UTC, iamNoah1 requested changes
Danke für die Contribution. Ich bin verwirrt, da sind 2 Dateien im PR und ich weiß nicht welche die "richtige" ist. Bitte prüf das nochmal. Bei der Gelegenheit kannst du auch überall aus Contineous und Contineaous, Continuous Integration machen und denk an die line breaks. Danke

2024-04-01 16:31 UTC, iamNoah1 requested changes
Nice, bis auf kleines editing ist alles paletti :)

2024-04-01 16:31 UTC, iamNoah1 commented on content/de/continuous-integration.md
> +## Was es ist
```suggestion
```

Die Headline haben wir mittlerweile rausgenommen

2024-04-01 16:31 UTC, iamNoah1 commented on content/de/continuous-integration.md
> +Traditionell beginnt der CI-Prozess mit der Übergabe von Codeänderungen an ein Versionskontrollsystem (Git, Mercurial oder Subversion) und endet mit einem getesteten Artefakt, das von einem CD-System
```suggestion
Traditionell beginnt der CI-Prozess mit der Übergabe von Codeänderungen an ein Versionskontrollsystem (Git, Mercurial oder Subversion) 
und endet mit einem getesteten Artefakt, das von einem CD-System verwendet werden kann.  
```

2024-04-01 16:31 UTC, iamNoah1 commented on content/de/continuous-integration.md
> +Wenn diese Entwickler parallel an verschiedenen Teilen des Systems arbeiten, kann es vorkommen, dass sie im Konflikt miteinander stehende Änderungen vornehmen und versehentlich die Arbeit des jeweils
```suggestion
Wenn diese Entwickler parallel an verschiedenen Teilen des Systems arbeiten, kann es vorkommen, dass sie im Konflikt miteinander stehende Änderungen vornehmen und versehentlich die Arbeit des jeweils anderen beschädigen. 
Wenn mehrere Entwickler an demselben Projekt arbeiten, müssen außerdem alle alltäglichen Aufgaben wie das Testen, 
das Berechnen der Codequalität so wie das Ermitteln von Sicherheitsrisiken von jedem Entwickler wiederholt werden, was zu zeitaufwändig ist.
```

2024-04-01 16:31 UTC, iamNoah1 commented on content/de/continuous-integration.md
> +Es ist eine fast allgegenwärtige Praxis, den CI-Server zu verwenden, um Builds, Codequalitätsprüfungen, Sicherheitsscans, Tests und sogar Bereitstellungen durchzuführen. So wird er zu einer konkreten
```suggestion
Es ist eine fast allgegenwärtige Praxis, den CI-Server zu verwenden, um Builds, Codequalitätsprüfungen, Sicherheitsscans, Tests und sogar Bereitstellungen durchzuführen. 
So wird er zu einer konkreten Umsetzung der Qualitätskontrolle innerhalb von Teams. 
```

2024-04-15 09:05 UTC, iamNoah1 approved these changes
lgtm

2024-04-15 09:05 UTC, iamNoah1 commented on content/de/continuous-integration.md
> +status: Feedback erwünscht
```suggestion
status: Completed
```

2024-04-15 09:06 UTC, iamNoah1 commented
@bcubk final review is for you :)

2024-04-20 06:20 UTC, bcubk approved these changes
LGTM 👍 Kann gemerged werden

2024-04-21 10:30 UTC, merged