[ja] Localize Loosely Coupled Architecture for Japanese
cncf/glossary pull request #2740
Opened 2023-12-22 13:12 UTC by bashi8128

### Describe your changes
Localize Loosely Coupled Architecture for Japanese.

### Related issue number or link (ex: `resolves #issue-number`)
#2446

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-25 09:31 UTC, naonishijima approved these changes
LGTM

2024-01-14 14:15 UTC, kaitoii11 requested changes

2024-01-14 14:15 UTC, kaitoii11 commented on content/ja/loosely-coupled-architecture.md
> +title: 粗結合アーキテクチャ
```suggestion
title: 疎結合アーキテクチャ
```

2024-01-14 14:15 UTC, kaitoii11 commented on content/ja/loosely-coupled-architecture.md
> +粗結合アーキテクチャは、アプリケーションの構成要素それぞれが互いに独立して構築されるようなアーキテクチャです
```suggestion
疎結合アーキテクチャは、アプリケーションの構成要素それぞれが互いに独立して構築されるようなアーキテクチャです
```

2024-01-14 14:15 UTC, kaitoii11 commented on content/ja/loosely-coupled-architecture.md
> +粗結合アーキテクチャは密結合アーキテクチャより一般的に実装が遅くなりますが、特にアプリケーションがスケールする際に多くの利点があります。
```suggestion
疎結合アーキテクチャは密結合アーキテクチャより一般的に実装が遅くなりますが、特にアプリケーションがスケールする際に多くの利点があります。
```

2024-01-14 14:15 UTC, kaitoii11 commented on content/ja/loosely-coupled-architecture.md
> +アプリケーションが粗結合だと、チームは独立して機能開発、デプロイ、スケールすることが可能です。
```suggestion
アプリケーションが疎結合だと、チームは独立して機能開発、デプロイ、スケールすることが可能です。
```

2024-01-14 19:07 UTC, bashi8128 commented
あらゆるところで誤字を生んでいました。
「粗」を「疎」に修正しました。

2024-01-15 14:16 UTC, kaitoii11 approved these changes
LGTM

2024-01-15 14:16 UTC, merged