Review initial Russian content
cncf/glossary pull request #2750
Opened 2023-12-26 02:06 UTC by tym83

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2023-12-26 02:06 UTC, tym83 commented
Edited descriptions of all terms

2024-01-11 12:15 UTC, shurup requested changes
Thank you very much @tym83! Here are a few comments from me.

I also want to note that now, we will have different labels (e.g. «Что это такое» vs «Описание») in our template and all actual pages — let's make them consistent.

2024-01-11 12:15 UTC, shurup commented on content/ru/container.md
> +Контейнер — это запущенный процесс, работающий под управлением операционной системы компьютера, но ограниченный в ресурсах и возможностях.
Why «но»? It confuses me.

2024-01-11 12:15 UTC, shurup commented on content/ru/container.md
> +при этом операционная система, как правило, не позволяет контейнерам напрямую взаимодействовать и влиять друг на друга.
While «влиять друг на друга» sounds true, it's not stated in the original version, so we'd better avoid this addition.
```suggestion
при этом операционная система, как правило, не позволяет контейнерам напрямую взаимодействовать.
```

2024-01-11 12:15 UTC, shurup commented on content/ru/container.md
> +Такая совместная работа контейнеров возможна только потому, что они, как правило, не могут напрямую взаимодействовать и влиять друг на друга.
```suggestion
Такая совместная работа контейнеров возможна только потому, что они, как правило, не могут напрямую взаимодействовать.
```

2024-01-11 12:15 UTC, shurup commented on content/ru/continuous-delivery.md
> +— или, в случае [непрерывного развертывания](/continuous-deployment/) (Continuous Deployment), в production.
While I agree with this link, to have it here, we need to change the original (English) version first.
```suggestion
— или, в случае непрерывного развертывания, в production.
```

2024-01-11 12:15 UTC, shurup commented on content/ru/continuous-delivery.md
> +[Непрерывная интеграция](/continuous-integration/) (CI) — первый шаг на пути к непрерывной доставке:
Same formal issue is here.
```suggestion
Непрерывная интеграция — первый шаг на пути к непрерывной доставке:
```

2024-01-11 12:15 UTC, shurup commented on content/ru/continuous-deployment.md
> +То есть автоматизирует потенциально способные вызвать болезненные последствия и привести к ошибкам этапы развертывания ПО в production, снижая общий риск.
I think we definitely need to do something with «потенциально способные вызвать болезненные последствия»… :-)

2024-01-11 12:15 UTC, shurup commented on content/ru/devops.md
> +до работы с ним (**OP**eration**S**) в production. Отсюда и название DevOps.
I would still insist on using this word.
```suggestion
его эксплуатации (**OP**eration**S**) в production. Отсюда и название DevOps.
```

2024-01-11 12:15 UTC, shurup commented on content/ru/devops.md
> +Кроме того, растет общая удовлетворенность сотрудников от работы, поскольку они ощущают себя более самостоятельными и видят свое влияние на проект и отвественность за общий результат.
```suggestion
Кроме того, растет общая удовлетворенность сотрудников от работы, поскольку они ощущают себя более самостоятельными и видят свое влияние на проект и ответственность за общий результат.
```

2024-01-11 12:15 UTC, shurup commented on content/ru/devsecops.md
> +Кроме того они ускоряют цикл разработки и релизный цикл приложений.
```suggestion
Кроме того, они ускоряют цикл разработки и релизный цикл приложений.
```

2024-01-11 13:24 UTC, kirkonru approved these changes

2024-01-11 13:24 UTC, kirkonru commented on content/ru/continuous-deployment.md
> +То есть автоматизирует потенциально способные вызвать болезненные последствия и привести к ошибкам этапы развертывания ПО в production, снижая общий риск.
```suggestion
То есть автоматизирует этапы развертывания ПО в production, сокращая вероятность ошибок и негативных последствий и снижая общий риск.
```

2024-01-11 13:24 UTC, kirkonru commented on content/ru/devsecops.md
> +снижает количество инцидентов, связанных с безопаностью, и вызванные ими расходы.
```suggestion
снижает количество инцидентов, связанных с безопасностью, и вызванные ими расходы.
```

2024-01-11 13:24 UTC, kirkonru commented on content/ru/kubernetes.md
> +Kubernetes планирует (т. е. распределяет) [контейнеры](/ru/container/) по [узлам](/nodes/) [кластера](/cluster/), попутно обеспечивая их различными инфраструктурными ресурсами: например, балансировщи
```suggestion
Kubernetes планирует (т. е. распределяет) [контейнеры](/ru/container/) по [узлам](/nodes/) [кластера](/cluster/), попутно обеспечивая их различными инфраструктурными ресурсами: например, балансировщиками нагрузки, постоянным хранилищем и т. д., — которые необходимы для запуска контейнеризованных приложений.
```

2024-01-11 13:30 UTC, kirkonru commented on content/ru/cloud-native-apps.md
> +Приложения, которые не были специально разработаны для облачных сред, не могли полноценно задействовать главные преимущества облачных вычислений — отказоустойчивость и возможности по масштабированию.
```suggestion
Приложения, которые не были специально разработаны для облачных сред, не могли полноценно задействовать преимущества облачных вычислений — отказоустойчивость и возможности по масштабированию.
```

2024-01-11 13:31 UTC, kirkonru commented on content/ru/container.md
> +Контейнер — это запущенный процесс, работающий под управлением операционной системы компьютера, но ограниченный в ресурсах и возможностях.
```suggestion
Контейнер — это запущенный процесс, работающий под управлением операционной системы компьютера, ограниченный в ресурсах и возможностях. 
```

2024-01-11 14:06 UTC, kirkonru approved these changes

2024-01-11 14:06 UTC, kirkonru commented on content/ru/cloud-native-apps.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/cloud-native-tech.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/container-orchestration.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/container.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/containerization.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/continuous-deployment.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/continuous-integration.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/devops.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/devsecops.md
>  ## Описание
```suggestion
```

2024-01-11 14:06 UTC, kirkonru commented on content/ru/kubernetes.md
>  ## Описание
```suggestion
```

2024-01-12 04:04 UTC, shurup commented
Thanks, everyone! All is good now with a small exception I noted above. We need to do something with different labels («Что это такое» vs «Описание», etc.) in the template and all other pages. They should be the same throughout all documents.

2024-01-12 08:20 UTC, kirkonru commented on content/ru/_TEMPLATE.md
> +## Что это такое
```suggestion
```

2024-01-12 08:42 UTC, kirkonru approved these changes

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-apps.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-tech.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container-orchestration.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container-orchestration.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/containerization.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-delivery.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-deployment.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-integration.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devops.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devsecops.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/kubernetes.md
>  ## Проблема
```suggestion
## Какую проблему решает
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-apps.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-tech.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container-orchestration.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/containerization.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-delivery.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-deployment.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-integration.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devops.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devsecops.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/kubernetes.md
>  ## Решение
```suggestion
## Как именно решает проблему
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/_TEMPLATE.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-apps.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/cloud-native-tech.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container-orchestration.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/container.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/containerization.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-deployment.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/continuous-integration.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devops.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/devsecops.md
```suggestion
```

2024-01-12 08:42 UTC, kirkonru commented on content/ru/kubernetes.md
```suggestion
```

2024-01-12 10:17 UTC, kirkonru commented
LGTM

2024-01-12 10:18 UTC, merged