[FR] Localize `eBPF`
cncf/glossary pull request #2755
Opened 2023-12-28 18:29 UTC by guillaumebernard84

### Describe your changes
Localize `eBPF` in French

### Related issue number or link (ex: `resolves #issue-number`)
Resolves https://github.com/cncf/glossary/issues/2731

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-03 12:27 UTC, Krast76 commented on content/fr/ebpf.md
> +Les applications résident dans l'espace utilisateur, et envoient une demande au noyau lorsqu'elles ont besoin d'autorisations plus importantes.
J'aurais plutôt traduit ça comme ça : 
Les applications qui s'exécutent dans l'espace utilisateur, quand elles ont besoins de permissions plus importantes, envoient une requête au kernel.

2024-01-03 12:27 UTC, Krast76 commented on content/fr/ebpf.md
> + Cependant, cette approche introduit également des risques de sécurité, ce qui fait de l'eBPF une alternative intéressante.
ce qui fait d'eBPF plutôt ?

2024-01-04 11:37 UTC, sestegra commented on content/fr/ebpf.md
> +Les applications résident dans l'espace utilisateur, et envoient une demande au noyau lorsqu'elles ont besoin d'autorisations plus importantes.
De même, je suggère la phrase suivante:
Les applications résidant dans l'espace utilisateur envoient une requête au noyau lorsqu'elles ont besoin d'autorisations plus importantes.

2024-01-04 11:39 UTC, sestegra commented on content/fr/ebpf.md
> + Cependant, cette approche introduit également des risques de sécurité, ce qui fait de l'eBPF une alternative intéressante.
Je suis d'accord avec cette remarque.

2024-01-04 11:59 UTC, sestegra requested changes

2024-01-04 11:59 UTC, sestegra commented on content/fr/ebpf.md
> +Dans la plupart des cas, cette approche fonctionne parfaitement. Cependant, dans certains cas, les développeurs ont besoin d'une plus grande flexibilité pour accéder au système de bas niveau.
Je suggère une légére modification "pour un accès système de bas niveau."

2024-01-04 11:59 UTC, sestegra commented on content/fr/ebpf.md
> +L'observabilité, la sécurité et les fonctionnalités réseau sont de bons exemples.
Je propose la traduction suivante:
"Les fonctionnalités d'observabilité, de sécurité et de réseau sont de bons exemples."
A mon sens, "features" s'appliquent aux 3.

2024-01-04 11:59 UTC, sestegra commented on content/fr/ebpf.md
> +Ces contrôles de sécurité font de l'eBPF une option plus sûre que les modules du noyau Linux pour l'exécution d'applications dans le noyau Linux.
Idem, je propose de remplacer "de l'eBPF" avec "d'eBPF".

2024-01-12 09:00 UTC, seb-835 commented on content/fr/ebpf.md
> + permettant aux applications d'accéder plus directement aux composants sous-jacents.
répétition : permet, permettant

Cette approche permet d'étendre les fonctionnalités par défaut du noyau,
 ainsi les applications peuvent accéder plus directement aux composants sous-jacents.

2024-01-12 09:06 UTC, seb-835 commented on content/fr/ebpf.md
> +eBPF, ou "extended Berkeley Packet Filter", est une technologie qui permet à de petits programmes ou scripts de s'exécuter au sein d'un environnement contrôlé dans l'espace du noyau d'un système Linu
Je laisserai qd même apparaitre au moins une fois le mot kernel, dans la définition, ici par exemple : 

 l'espace du noyau (Kernel) d'un système Linux

2024-01-30 15:49 UTC, sestegra commented on content/fr/ebpf.md
> +category: architecture
Dans la VO, des tags ont été ajoutés

2024-01-31 07:39 UTC, seb-835 approved these changes
LGTM 🚀

2024-02-10 13:47 UTC, Krast76 approved these changes
LGTM 🚀

2024-02-19 09:49 UTC, sestegra approved these changes
LGTM 🚀

2024-02-19 09:50 UTC, merged