[WIP] [ja] Localize Function as a Service (FaaS) for Japanese
cncf/glossary pull request #2759
Opened 2023-12-29 19:45 UTC by Okabe-Junya

### Describe your changes

Localize Function as a Service (FaaS)  for Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2746 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-04 06:15 UTC, naonishijima commented on content/ja/function-as-a-service.md
> +複雑なインフラのメンテナンスを必要としません。
インフラストラクチャーをインフラと略していますが、インフラストラクチャーがよいと思いました。
下の方でも「FaaSのインフラストラクチャーは」と訳しています。

2024-01-04 06:21 UTC, Okabe-Junya commented on content/ja/function-as-a-service.md
> +複雑なインフラのメンテナンスを必要としません。
ありがとうございます

https://github.com/cncf/glossary/pull/2759/commits/5b782aacb1a1e9a6f84f3f47474f8a6e21deb453 で修正を行いました。

（出先のためモバイルアプリからcommitしたところ、dcoに失敗していました。後ほど修正します）

2024-01-04 06:24 UTC, naonishijima approved these changes
LGTM

2024-01-16 11:34 UTC, kaitoii11 requested changes

2024-01-16 11:34 UTC, kaitoii11 commented on content/ja/function-as-a-service.md
> +データセンターはピーク需要に合わせて構築されるため、作業負荷が減少し、それらのリソースが稼働していなくても対応しなければなりません。
こちらは原文だと、閑散期やアイドル状態の時期があるにも関わらずピーク需要に見合った条件で構築が必要という意味合いかと思います。

2024-01-17 08:40 UTC, Okabe-Junya commented on content/ja/function-as-a-service.md
> +データセンターはピーク需要に合わせて構築されるため、作業負荷が減少し、それらのリソースが稼働していなくても対応しなければなりません。
ありがとうございます。

> データセンターは、作業負荷が減少しリソースがアイドリング状態の時期があるにも関わらず、ピーク需要に対応できるように建設されなければなりません。

という表現に修正させて頂きました

2024-01-18 14:44 UTC, kaitoii11 approved these changes
LGTM

2024-01-18 14:44 UTC, merged