Removed the header
cncf/glossary pull request #2776
Opened 2024-01-08 16:12 UTC by professorabhay

[pt] Updated the style guide to reflect the removal of the "What is it" header

### resolves #2669 

- [x] This PR does not contain plagiarism
- [x] I have signed off on all commits

2024-01-08 16:16 UTC, professorabhay commented
Hey, @edsoncelio ! 
Finally, here is my PR 😮‍💨
Please take a look and let me know if you are looking for further changes 🙂

2024-01-09 01:51 UTC, edsoncelio commented
> Hey, @edsoncelio ! Finally, here is my PR 😮‍💨 Please take a look and let me know if you are looking for further changes 🙂

Thanks! 
As soon as possible (this week) I'll take a look
/cc @MrErlison

2024-01-14 17:17 UTC, edsoncelio requested changes
Hi @professorabhay 
A few changes, after this will be LGTM

2024-01-14 17:17 UTC, edsoncelio commented on content/pt-br/style-guide/_index.md
>  As definições para **tecnologia** e **conceito** contém três subcabeçalhos:
"As definições para tecnologia e conceito contém dois subcabeçalhos:"

2024-01-14 17:17 UTC, edsoncelio commented on content/pt-br/style-guide/_index.md
> +- forneça uma visão curta e clara da definição abordada.
This line can be removed

2024-01-14 17:17 UTC, edsoncelio commented on content/pt-br/style-guide/_index.md
> +**Exemplo**: veja seção da definição de [service mesh](/service-mesh/). Ele se refere aos conceitos de microsserviços, serviços, confiabilidade e observabilidade. Além disso, é usado um exemplo do mu
"veja seção da definição de [service mesh](/service-mesh/)" can be "veja a seção inicial da definição de [service mesh](/pt-br/service-mesh/)"

2024-02-11 07:30 UTC, professorabhay commented
Ok @edsoncelio, I will commit the required changes asap. 
Btw sorry for the delay!

2024-03-22 20:06 UTC, edsoncelio commented
Hey @professorabhay 
Do you need some help with the requested changes? 
If yes let me know :)

2024-10-13 13:21 UTC, edsoncelio commented
Due to inactivity, I'll close this PR and continue working on another one. Thanks for your contribution.

2024-10-13 13:21 UTC, closed without merging