“it-localization-ingress-#2711”
cncf/glossary pull request #2802
Opened 2024-01-15 09:39 UTC by matteobisi

### Describe your changes
Ingress italian localization, new term

### Related issue number or link (ex: `resolves #issue-number`)
#2711 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-15 10:02 UTC, ugho16 commented on content/it/ingress.md
> +questo introduce nuovi costi e oneri gestionali, ma ogni nuovo bilanciatore di carico creato ha il proprio indirizzo IP esterno.
```suggestion
questo non solo introdurrebbe nuovi costi e oneri gestionali, ma ogni nuovo bilanciatore di carico creato avrebbe il proprio indirizzo IP esterno.
```

2024-01-15 10:02 UTC, ugho16 commented on content/it/ingress.md
> +Questo porta a un'esperienza utente negativa, poiché, come utenti, non vogliamo navigare su URL differenti per accedere a un'applicazione
```suggestion
Questo porterebbe a un'esperienza utente negativa, poiché, come utenti, non vogliamo navigare su URL differenti per accedere a un'applicazione
```

2024-01-15 10:02 UTC, ugho16 commented on content/it/ingress.md
> +Una risorsa Ingress consente di configurare come il traffico viene bilanciato e instradato verso i servizi di un'applicazione.
```suggestion
Una risorsa ingress consente di configurare come il traffico viene bilanciato e instradato verso i servizi di un'applicazione.
```

2024-01-15 10:02 UTC, ugho16 commented on content/it/ingress.md
> +Questo elimina la necessità di numerosi bilanciatori di carico separati a livello di infrastruttura e semplifica la configurazione delle regole del firewall e del bilanciatori di carico per ciascun s
```suggestion
Questo elimina la necessità di numerosi bilanciatori di carico separati a livello di infrastruttura e semplifica la configurazione delle regole del firewall e dei bilanciatori di carico per ciascun servizio.
```

2024-01-18 08:38 UTC, ugho16 approved these changes

2024-01-18 08:56 UTC, annalisag-spark requested changes

2024-01-18 08:56 UTC, annalisag-spark commented on content/it/ingress.md
> +È composto da due elementi: la risorsa ingress e dall'ingress controller.
```suggestion
È composto da due elementi: la risorsa ingress e l'ingress controller.
```

2024-01-18 08:56 UTC, annalisag-spark commented on content/it/ingress.md
> +riduzione dei costi e migliora la gestibilità complessiva delle applicazioni in esecuzione in un cluster.
forse c'è un a capo di troppo alla riga 31

in generale deciderei se usare Ingress con la maiuscola sempre o con la minuscola (anche se l'originale stesso è indeciso)

2024-01-18 10:55 UTC, annalisag-spark approved these changes

2024-02-14 14:20 UTC, merged