[ja] Localize Edge Computing for Japanese
cncf/glossary pull request #2820
Opened 2024-01-19 19:11 UTC by Okabe-Junya

### Describe your changes

Localize Edge Computing for Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2745 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-19 19:14 UTC, Okabe-Junya commented
The target page on deploy preview:

- https://deploy-preview-2820--cncfglossary.netlify.app/ja/edge-computing/

2024-02-14 23:33 UTC, naonishijima commented on content/ja/edge-computing.md
> +収集されたデータは、一元的なデータセンターで処理や分析されるのではなく、ローカルに(例えば工場内や店内、あるいは街の全域にわたって)計算されます。
distributedの対比としてcentralizedなので、一元的よりも中央の/集中型の方がよいと思いました。

2024-02-15 00:50 UTC, Okabe-Junya commented on content/ja/edge-computing.md
> +収集されたデータは、一元的なデータセンターで処理や分析されるのではなく、ローカルに(例えば工場内や店内、あるいは街の全域にわたって)計算されます。
ありがとうございます。

「中央の」が良い表現だと思いました 👍 https://github.com/cncf/glossary/pull/2820/commits/4875707d25bdc25a04322c5ec749842f4e20f1a3 で修正しました

2024-02-15 00:55 UTC, naonishijima approved these changes
LGTM

2024-02-17 13:12 UTC, kaitoii11 requested changes

2024-02-17 13:12 UTC, kaitoii11 commented on content/ja/edge-computing.md
> +エッジコンピューティングの例には、交通量を分析するためのリストバンド型ガジェットやコンピューターが含まれます。
"that analyze traffic flow"はcomputerだけにかかる気もします。
(個人的にリストバンド型のガジェットで交通量の分析をやってるというイメージがあまりない)

2024-02-17 13:36 UTC, Okabe-Junya commented on content/ja/edge-computing.md
> +エッジコンピューティングの例には、交通量を分析するためのリストバンド型ガジェットやコンピューターが含まれます。
ありがとうございます。

確かにその通りですね。。修飾関係を https://github.com/cncf/glossary/pull/2820/commits/f61779cf39d411dfcbd74f85d49dcfa9a092ebcc で修正しました

2024-03-11 11:53 UTC, kaitoii11 approved these changes
LGTM

2024-03-11 11:53 UTC, merged