[ja] Localize Stateful Apps into Japanese
cncf/glossary pull request #2829
Opened 2024-01-20 07:51 UTC by Okabe-Junya

### Describe your changes

Localize Stateful Apps into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2821 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-20 08:10 UTC, Okabe-Junya commented
The target page on deploy preview:

- https://deploy-preview-2829--cncfglossary.netlify.app/ja/stateful-apps/

2024-01-22 01:59 UTC, naonishijima approved these changes
LGTM

2024-01-24 13:46 UTC, kaitoii11 requested changes

2024-01-24 13:46 UTC, kaitoii11 commented on content/ja/stateful-apps.md
> +しかし、クラウドネイティブ環境では、ステートフルアプリは課題です。
どちらかというと、難題や難しいというニュアンスかと思います。

2024-01-25 00:13 UTC, kaitoii11 approved these changes
LGTM

2024-01-25 00:13 UTC, merged