[bn] adding tags in ebpf.md
cncf/glossary pull request #2869
Opened 2024-01-28 17:52 UTC by asem-hamid

Adding tags in ebpf.md

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-01-29 04:23 UTC, sajibAdhi approved these changes

2024-01-29 11:07 UTC, mitul3737 requested changes
Which file did you refer to while adding networking and security here?

2024-01-29 11:08 UTC, mitul3737 commented
If you follow this one, you can see the previous version was right: https://github.com/cncf/glossary/blob/main/content/en/ebpf.md

2024-01-29 11:32 UTC, asem-hamid commented
> If you follow this one, you can see the previous version was right: https://github.com/cncf/glossary/blob/main/content/en/ebpf.md
> 
> @asem-hamid



> networking and security are missing in main content . already fixed in #2868

2024-01-31 17:11 UTC, mitul3737 approved these changes

2024-01-31 17:15 UTC, merged