[ja] Localize Service Proxy into Japanese
cncf/glossary pull request #2898
Opened 2024-02-05 13:27 UTC by Okabe-Junya

close #2769 

### Describe your changes

Localize Service Proxy into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2769 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-02-05 13:30 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-2898--cncfglossary.netlify.app/ja/service-proxy/

2024-02-09 07:01 UTC, Okabe-Junya commented
feel free to remove `hold` after #2872 will merge

2024-02-09 11:09 UTC, naonishijima approved these changes
LGTM

2024-02-17 12:50 UTC, kaitoii11 requested changes

2024-02-17 12:50 UTC, kaitoii11 commented on content/ja/service-proxy.md
> +また(トラフィックをサービス間で均等に分散させたり、一部のサービスが故障した場合には再ルーティングしたり)、接続を暗号化し、コンテンツをキャッシュします(リソース消費を減らします)。
訳としては原文通りですが、日本語として1つめの括弧は違和感がありますね。

> プロキシは重要なデータを収集し、ルーティングを管理します(トラフィックをサービス間で均等に分散させたり、一部のサービスが故障した場合には再ルーティングしたり)。
また、接続を暗号化し、コンテンツをキャッシュします(リソース消費を減らします)。

こんな感じで位置をずらすのはどうでしょう。

2024-02-17 13:03 UTC, Okabe-Junya commented on content/ja/service-proxy.md
> +また(トラフィックをサービス間で均等に分散させたり、一部のサービスが故障した場合には再ルーティングしたり)、接続を暗号化し、コンテンツをキャッシュします(リソース消費を減らします)。
> こんな感じで位置をずらすのはどうでしょう。

ありがとうございます。確かに、

>  (spreading ... down)

の箇所は、"manage routing" を補足しているので、括弧の位置があまり良くなかったですね。https://github.com/cncf/glossary/pull/2898/commits/b5f01189b920190849a10b75add579fa020f0d08 で修正しました :)

2024-02-17 13:12 UTC, kaitoii11 approved these changes
LGTM

2024-02-17 13:13 UTC, merged