[FR] Added architecture server client translation
cncf/glossary pull request #2901
Opened 2024-02-05 17:28 UTC by p1000ans

### Describe your changes
Added architecture server client translation

### Related issue number or link (ex: `resolves #issue-number`)
resolves  #2568

### Checklist before opening this PR (put `x` in the checkboxes)
- [ x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-02-08 10:34 UTC, seb-835 commented
Dans la version EN, le fichier se nomme :  client-server-architecture.md . Or Ici : architecture-server-client.md.
Est-ce Problématique ?

2024-02-08 10:38 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +tags: ["architecture", "client", "server",""]
Les Tags et Category sont différents dans la version EN : 

```
category: concept
tags: ["architecture", "fundamental", ""]
```

2024-02-08 10:46 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +En mettant en œuvre la logique de l'application dans un serveur ou un service distant, les opérateurs peuvent mettre l'application à jour sans avoir à modifier la logique côté client.
Ajouter un retour a la ligne aprés "distant," pour garder la structure du fichier de la version EN

2024-02-08 10:49 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +
est-ce que l'on doit garder la mise en forme de la version EN ? sans les -  et les phrases entre () precedézs d'un retour à la ligne ?

2024-02-08 10:51 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +
Supprimer la ligne vide 27.

2024-02-08 10:53 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +Dans le premier cas, vos fichiers existent sur le serveur et peuvent être partagés avec d'autres utilisateurs qui les téléchargent simplement à partir du serveur.
Doit on faire le même split de ligne que la version EN ?

2024-02-08 11:01 UTC, seb-835 commented on content/fr/architecture-server-client.md
> +Dans l'ancien monde, les fichiers devaient être copiés sur des supports amovibles (disquettes !) et partagés avec des individus.
Pour avoir connu les disquettes ,je me sens vieux,  et donc de l'ancien monde.  
D'autres idées pour traduire "legacy world" ?

2024-02-18 20:03 UTC, guillaumebernard84 commented on content/fr/architecture-server-client.md
> +
Garder les mêmes retours a la ligne c'est bien, ça permet de faciliter les review.
Pour les tirets, je trouve ça mieux, plus lisible. Je proposerais bien de les utiliser aussi dans la VO

2024-02-18 20:05 UTC, guillaumebernard84 commented on content/fr/architecture-server-client.md
> +Dans le premier cas, vos fichiers existent sur le serveur et peuvent être partagés avec d'autres utilisateurs qui les téléchargent simplement à partir du serveur.
Oui, c’est mieux, ça facilite les review et les mises a jour

2024-02-19 10:46 UTC, sestegra commented
> Dans la version EN, le fichier se nomme : client-server-architecture.md . Or Ici : architecture-server-client.md.
> Est-ce Problématique ?

@p1000ans 
Oui, c'est problématique, il ne faut pas traduire le nom du fichier.
Il faut conserver exactement le même nom de fichier.

2024-02-21 15:52 UTC, sestegra requested changes

2024-02-21 15:52 UTC, sestegra commented on content/fr/client-server-architecture.md
> +# Problème auquel cela répond
Il faut 2 # dans les titres
`## Problème auquel cela répond`

2024-02-21 15:52 UTC, sestegra commented on content/fr/client-server-architecture.md
> +# Quelle en est l’utilité
Il faut 2 # dans les titres
`## Quelle en est l'utilité`

2024-02-21 20:21 UTC, p1000ans commented on content/fr/client-server-architecture.md
> +# Problème auquel cela répond
c'est rajouté

2024-02-21 20:21 UTC, p1000ans commented on content/fr/client-server-architecture.md
> +# Quelle en est l’utilité
c'est rajouté

2024-02-24 18:37 UTC, sestegra commented on content/fr/architecture-server-client.md
> +Dans l'ancien monde, les fichiers devaient être copiés sur des supports amovibles (disquettes !) et partagés avec des individus.
Je ne vois rien de mieux.
Par example, le "monde d'avant" est trop dans le style "c'était mieux avant."

2024-03-07 21:33 UTC, guillaumebernard84 approved these changes
LGTM 🚀 🚀 🚀

2024-03-07 21:34 UTC, merged