[ja] Localize eBPF for Japanese
cncf/glossary pull request #2935
Opened 2024-02-17 09:05 UTC by bashi8128

### Describe your changes
Localize eBPF into Japanese

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2804

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-02-17 13:10 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-2935--cncfglossary.netlify.app/ja/ebpf/

2024-02-17 13:25 UTC, Okabe-Junya requested changes
ありがとうございます :)

何点かコメントを残させて頂きました。nitsの箇所に関しては、取り込むかどうかの判断はお任せします

2024-02-17 13:25 UTC, Okabe-Junya commented on content/ja/ebpf.md
> +eBPF(拡張Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
```suggestion
eBPF(extended Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
```

IMO: eBPFの正式表記は、日本語訳せずそのままでも良いかと思いました。また、多くの（権威的な）サイトでもママ表記が多そうです

参考

- [第49章 RHEL 8 の eBPF ネットワーク機能について](https://access.redhat.com/documentation/ja-jp/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/assembly_understanding-the-ebpf-features-in-rhel-8_configuring-and-managing-networking)
- [eBPF によるカーネルの拡張](https://source.android.com/docs/core/architecture/kernel/bpf?hl=ja)

2024-02-17 13:25 UTC, Okabe-Junya commented on content/ja/ebpf.md
> +多くの場合このアプローチはうまく働きますが、低水準なシステムに対するより柔軟なアクセスを開発者が必要とする場合があります。
```suggestion
多くの場合、このアプローチはうまく働きますが、低水準なシステムに対するより柔軟なアクセスを開発者が必要とする場合があります。
```

nits: 原文にも `,` があり、日本語としても句点があった方が読みやすいかなと感じました

2024-02-17 13:25 UTC, Okabe-Junya commented on content/ja/ebpf.md
> +これらのような安全制御によって、Linuxカーネル内でアプリケーションを動かすための選択肢としてeBPFはLinuxカーネルモジュールよりも安全なものになっています。
```suggestion
これらの安全制御によって、Linuxカーネル内でアプリケーションを動かすための選択肢としてeBPFはLinuxカーネルモジュールよりも安全なものになっています。
```

nits: "These safety controls" は単に「これらの安全制御」で良いかと思いました

2024-02-17 17:24 UTC, bashi8128 commented on content/ja/ebpf.md
> +eBPF(拡張Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
[a401d2d0](https://github.com/cncf/glossary/pull/2935/commits/a401d2d09293c8b6db3674d2f0add9665feddcbe)で修正しました。

2024-02-17 17:25 UTC, Okabe-Junya approved these changes
ありがとうございます :)

almost LGTMです〜ー（こちらのミスで1箇所だけ修正して欲しい箇所があるので、そちらの対応だけお願いします 🙏 ）

2024-02-17 17:25 UTC, Okabe-Junya commented on content/ja/ebpf.md
> +eBPF(extended Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
```suggestion
eBPF (extended Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
```

自分のsuggestの仕方が悪くて非常に恐縮なのですが、英文字になったので空白が必要そうですね。。

2024-02-17 17:26 UTC, bashi8128 commented on content/ja/ebpf.md
> +多くの場合このアプローチはうまく働きますが、低水準なシステムに対するより柔軟なアクセスを開発者が必要とする場合があります。
「、」の有無で比較してみて、たしかにあったほうが読みやすかったので修正いたしました。
[aa24effc](https://github.com/cncf/glossary/pull/2935/commits/aa24effc89e11e05f3869edabfa769a2c2ad6dd9)です。

2024-02-17 17:30 UTC, bashi8128 commented on content/ja/ebpf.md
> +eBPF(extended Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
あ、本当ですね...
ありがとうございます！
修正しました。

2024-02-17 17:30 UTC, bashi8128 commented on content/ja/ebpf.md
> +これらのような安全制御によって、Linuxカーネル内でアプリケーションを動かすための選択肢としてeBPFはLinuxカーネルモジュールよりも安全なものになっています。
原文に「ような」のニュアンスなかったのでこちらも修正しました。
[d6209f24](https://github.com/cncf/glossary/pull/2935/commits/d6209f24a2d9835d15c2634a7c5f5d0cd10dc103)

2024-02-17 17:31 UTC, Okabe-Junya commented on content/ja/ebpf.md
> +eBPF(extended Berkeley Packet Filter)は、Linuxカーネルのソースコードを修正したりカーネルモジュールを導入したりすることなく、サンドボックス化された小さなプログラムやスクリプトをLinuxシステムのカーネル空間で実行できる技術です。
ありがとうございます〜ー

LGTMです👍

2024-02-29 12:02 UTC, kaitoii11 requested changes

2024-02-29 14:08 UTC, bashi8128 commented on content/ja/ebpf.md
> +Linuxカーネルモジュールの使用には利点もありますが、セキュリティリスクもももたらします。
ありがとうございます、誤字修正しました

2024-02-29 14:29 UTC, kaitoii11 approved these changes
LGTM

2024-02-29 14:29 UTC, merged