[ja] Localize Chaos Engineering into Japanese
cncf/glossary pull request #2986
Opened 2024-03-14 03:36 UTC by Okabe-Junya

### Describe your changes

Localize Chaos Engineering into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2819 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-03-14 03:40 UTC, Okabe-Junya commented
The target page on the deploy preview:

- https://deploy-preview-2986--cncfglossary.netlify.app/ja/chaos-engineering/

2024-03-15 02:21 UTC, naonishijima commented on content/ja/chaos-engineering.md
> +このアプローチは、特に本番環境において、複雑なシステムにおける回復力とチームの自信を高めるのに役立ちます。
こちらが人が対象なので自信で良いと思います。

2024-03-15 02:31 UTC, Okabe-Junya commented on content/ja/chaos-engineering.md
> +分散システムが乱雑で予期せぬ状況に耐えるシステムの能力に自信を持つことを目指します。
ありがとうございます。確かにご指摘の通り、「信頼」の方が適切に感じました

https://github.com/cncf/glossary/pull/2986/commits/8939117499924137f993d9ad81745337041de141 で修正しました

2024-03-15 02:34 UTC, naonishijima approved these changes
LGTM

2024-03-15 02:39 UTC, Okabe-Junya commented
ありがとうございます〜！

2024-03-19 15:37 UTC, kaitoii11 requested changes

2024-03-19 15:37 UTC, kaitoii11 commented on content/ja/chaos-engineering.md
> +[SRE](/ja/site-reliability-engineering/)や[DevOps](/ja/devops/)の実践は、プロダクトの回復力と信頼性を高める技術に焦点を当てています。
```suggestion
[SRE](/ja/site-reliability-engineering/)や[DevOps](/ja/devops/)の実践は、プロダクトの回復力と[信頼性](/ja/reliability/)を高める技術に焦点を当てています。
```

2024-03-19 15:39 UTC, Okabe-Junya commented
すいません、完全に抜けていました。。

2024-03-19 15:47 UTC, merged