[ja] Localize Event-Driven Architecture into Japanese
cncf/glossary pull request #2987
Opened 2024-03-17 14:49 UTC by Okabe-Junya

### Describe your changes

Localize Event-Driven Architecture into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

resolves #2855 

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-03-17 14:52 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-2987--cncfglossary.netlify.app/ja/event-driven-architecture/

2024-03-21 01:52 UTC, naonishijima approved these changes
LGTM

2024-03-21 11:35 UTC, kaitoii11 requested changes

2024-03-21 11:35 UTC, kaitoii11 commented on content/ja/event-driven-architecture.md
> +データがリアルタイムになるにつれて、イベントがキャプチャされ、イベントリクエストを処理する必要がある適切な[サービス](/ja/service/)へ正確にルーティングされる信頼性の高い方法を見つけることがますます困難になります。
```suggestion
より多くのデータがリアルタイムになるにつれて、イベントがキャプチャされ、イベントリクエストを処理する必要がある適切な[サービス](/ja/service/)へ正確にルーティングされる信頼性の高い方法を見つけることがますます困難になります。
```

2024-03-21 11:35 UTC, kaitoii11 commented on content/ja/event-driven-architecture.md
> +このアーキテクチャは、サービスが結合されずに残り、イベントがプロデューサーからコンシューマーに適切にルーティングされることを保証します。
```suggestion
このアーキテクチャは、サービス同士が疎結合のまま、イベントがプロデューサーからコンシューマーに適切にルーティングされることを保証します。
```

2024-03-21 11:39 UTC, Okabe-Junya commented
ありがとうございます〜！提案をcommitさせて頂きました

2024-03-21 11:42 UTC, kaitoii11 approved these changes
LGTM

2024-03-21 11:42 UTC, merged