[ja] Localize Distributed Apps into Japanese
cncf/glossary pull request #2988
Opened 2024-03-18 11:11 UTC by t-katsumura

### Describe your changes

Localize Distributed Apps into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

Resolve https://github.com/cncf/glossary/issues/2863

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-03-18 14:40 UTC, Okabe-Junya commented
The target page on the deploy preview:

- https://deploy-preview-2988--cncfglossary.netlify.app/ja/distributed-apps/

2024-03-18 14:56 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます〜！

almost LGTMですが、リンク周りでいくつかの修正をお願いしたいです

2024-03-18 14:56 UTC, Okabe-Junya commented on content/ja/distributed-apps.md
> +分散アプリケーションは通常、広範なアプリケーション内で異なる機能を担う個々の[マイクロサービス](/ja/microservices/)から構成されます。
```suggestion
分散アプリケーションは通常、広範なアプリケーション内で異なる機能を担う個々の[マイクロサービス](/ja/microservices-architecture/)から構成されます。
```

https://github.com/cncf/glossary/pull/2988/commits/a7c3eb6c8be5838b5380e3c1767b5903ef892a08 で `/ja/microservices-architecture` から翻訳元に合わせて変更していただいたと思うんですが、リンク切れになってしまうので、revert（あるいは↑のsuggestionを入れて）いただきたいです

---

## 余談

翻訳元の英語版のコンテンツでは以下のファイルでリダイレクトを設定しているので、`/microservices/` でリンクできるようになっています。

https://github.com/cncf/glossary/blob/main/static/_redirects

2024-03-18 14:56 UTC, Okabe-Junya commented on content/ja/distributed-apps.md
> +クラウドネイティブ環境において、個々のコンポーネントは[クラスター](/ja/cluster/)内のコンテナとして実行されます。
```suggestion
クラウドネイティブ環境において、個々のコンポーネントは[クラスター](/ja/cluster/)内の[コンテナ](/ja/container/)として実行されます。
```

翻訳元に準拠して、"コンテナ" へのリンクをお願いします

2024-03-19 06:48 UTC, t-katsumura commented
ありがとうございますー。なるほど、そこにリダイレクトの定義があったんですね
どちらも修正しました！

2024-03-19 06:50 UTC, Okabe-Junya approved these changes
修正ありがとうございます！LGTMです

2024-03-21 01:14 UTC, merged