[ja] rename `tightly-coupled-architectures.md` to `tightly-coupled-architecture.md`
cncf/glossary pull request #3006
Opened 2024-03-23 13:08 UTC by Okabe-Junya

### Describe your changes

"密結合アーキテクチャ" のファイル名が日本語と英語で異なっていたため、修正しました

- en: https://github.com/cncf/glossary/blob/main/content/en/tightly-coupled-architecture.md
- ja: https://github.com/cncf/glossary/blob/main/content/ja/tightly-coupled-architectures.md

### Related issue number or link (ex: `resolves #issue-number`)

No issue related to this pr

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-03-25 05:47 UTC, naonishijima approved these changes
LGTM

2024-03-26 11:06 UTC, kaitoii11 requested changes
全ページを確認したわけじゃないですが、少なくとも`content/ja/loosely-coupled-architecture.md`は文中のリンクを修正する
必要があります。
こちらも合わせて修正お願いできますか。

2024-03-26 12:17 UTC, Okabe-Junya commented
ありがとうございます。ご指摘いただいた通りですね。以下の4ファイルからリンクされていたので、合わせて修正させて頂きました

```bash
$ pwd
/path/to/glossary
$ grep  "tightly-coupled-architectures"  -rl ./content/ja
./content/ja/microservices-architecture.md
./content/ja/cloud-native-apps.md
./content/ja/loosely-coupled-architecture.md
./content/ja/devops.md
```

2024-03-26 12:29 UTC, kaitoii11 approved these changes
LGTM

2024-03-26 12:29 UTC, merged