Update containerization.md
cncf/glossary pull request #3007
Opened 2024-03-23 18:16 UTC by NitishRawat123

easier way to define containersiation.

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-04-08 18:34 UTC, iamNoah1 requested changes
Thanks @NitishRawat123 for your contribution. I agree that your approach is more simple and straight forward to understand. I added the link to container image and removed information that is already present in the pages of the other terms.

2024-04-08 18:34 UTC, iamNoah1 commented on content/en/containerization.md
> +Containerization is the packaging of software code with just the operating system (OS) libraries and dependencies required to run the code to create a single lightweight executable—called a container
```suggestion
Containerization is the process of packaging of application code including libraries and dependencies required to run the code into a single lightweight executable—called [container image](/container-image/). 
```

2024-07-03 11:38 UTC, iamNoah1 approved these changes
lgtm

2024-07-04 00:05 UTC, nate-double-u approved these changes
Thanks for this @NitishRawat123 

/approve

2024-07-04 00:07 UTC, merged