[ja] Localize Event Streaming into Japanese
cncf/glossary pull request #3033
Opened 2024-04-05 12:36 UTC by katzchang

### Describe your changes

Localize https://glossary.cncf.io/event-streaming/ into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #2854 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-04-06 08:43 UTC, Okabe-Junya requested changes
継続的な貢献ありがとうございます！

Almost LGTMですが、一点だけ細かな修正をお願いいたします

2024-04-06 08:43 UTC, Okabe-Junya commented on content/ja/event-streaming.md
> +category: 概念
```suggestion
category: コンセプト
```

既存の例に合わせて "コンセプト" でお願いいたします

e.g. 

https://github.com/cncf/glossary/blob/5b05c81eedc37e4217c04964ec184a93ebae4e8d/content/ja/agile-software-development.md?plain=1#L4

2024-04-06 08:47 UTC, Okabe-Junya approved these changes
LGTMです！

2024-04-08 02:10 UTC, naonishijima approved these changes
LGTM

2024-04-08 02:10 UTC, merged