Add data center.md
cncf/glossary pull request #3034
Opened 2024-04-07 10:08 UTC by shinjichan

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [ ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [ ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-04-07 10:26 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます〜！

レビューの前に何点かご対応をお願いしたいです

1. 日本語の翻訳は `dev-ja` ブランチで管理しているので、そこに向けてPRの作成をお願いします
2. 翻訳する場合は、1つのPRで1ファイルのみを翻訳する形でお願いします（ベースブランチの問題ですかね。。？？）
3. DCOチェックに失敗しているため、こちらのご対応をお願いします

2024-04-07 10:29 UTC, Okabe-Junya commented
すいません、1, 2はこちらで対応したので、

> DCOチェックに失敗しているため、こちらのご対応をお願いします

をお願いしたいです。具体的には、https://github.com/cncf/glossary/pull/3034/checks?check_run_id=23532228545 に書いてある内容を実行してください。あと、PRのタイトルやディスクリプションの部分を他のもの (e.g. #3032 ) に合わせていただくようお願いします！

2024-04-07 10:36 UTC, Okabe-Junya commented
全く問題ないです🙆‍♂️ 何か必要あれば、@Okabe-Junya 宛でメンション飛ばしていただくなり、Slackの方でコメントするなりしていただければと思います！

2024-04-07 11:05 UTC, shinjichan commented
1番と2番のご対応ありがとうございます。3番DCOの対応しました。よろしくお願いいたします。

2024-04-07 11:11 UTC, shinjichan commented
1番と2番のご対応ありがとうございます。3番DCOの対応してみました。よろしくお願いいたします。

2024-04-07 11:32 UTC, Okabe-Junya commented
あー。。もしかして、 `git rebase -I HEAD~10` みたいなコマンドを実行されたかもしれないですね。。（ベースブランチを更新した関係で、https://github.com/cncf/glossary/pull/3034/checks?check_run_id=23532228545 のメッセージがおかしくなっていたかもしれないですね。。）

手元で、

```bash
$ git branch
add_data-center.md

$ git rebase dev-ja
...
Successfully rebased ...

$ git push origin add_data-center.md --force-with-lease
```

とか実行すればうまく解消されますかね。。？？

2024-04-07 12:45 UTC, shinjichan commented
本流ではない部分でお手数お掛けしており申し訳ありません。確認を進めます。

2024-04-07 13:11 UTC, Okabe-Junya commented
諸々ご対応ありがとうございます！一旦良さそうです！

> あと、PRのタイトルやディスクリプションの部分を他のもの (e.g. https://github.com/cncf/glossary/pull/3032 ) に合わせていただくようお願いします！

だけご対応お願いします！

2024-04-07 13:29 UTC, Okabe-Junya requested changes
コントリビューション & いくつかのご対応ありがとうございます！

何点かコメントさせて頂きました。お手数ですがご確認よろしくお願いいたします！

2024-04-07 13:29 UTC, Okabe-Junya commented on content/ja/data-center.md
> +ユーザーはさまざまなサーバーに接続することで、「スーパーコンピューター」のように機能する[分散システム](en/distributed-systems/)を構築できます。
```suggestion
ユーザーはさまざまなサーバーに接続することで、「スーパーコンピューター」のように機能する[分散システム](/ja/distributed-systems/)を構築できます。
```

日本語訳が存在しなくても、`/ja` にリンクするようにして大丈夫です。また、リンクの先頭に `/` を挿入しないと適切にリンクされないため、挿入をお願いいたします

2024-04-07 13:29 UTC, Okabe-Junya commented on content/ja/data-center.md
> +[パブリッククラウド](ja/cloud-computing/)はクライアントにコンピューターリソースを貸し出すデータセンターです。ここ数年、企業所有のデータセンターからパブリッククラウドへ移行している事例が多数あります。
```suggestion
[パブリッククラウド](/ja/cloud-computing/)はクライアントにコンピューターリソースを貸し出すデータセンターです。ここ数年、企業所有のデータセンターからパブリッククラウドへ移行している事例が多数あります。
```

ditto

> また、リンクの先頭に `/` を挿入しないと適切にリンクされないため、挿入をお願いいたします

2024-04-07 13:29 UTC, Okabe-Junya commented on content/ja/data-center.md
> +データセンターはコンピューター(サーバー)を収容するために設計された特別な建物または施設です。
```suggestion
データセンターはコンピューター(その多くはサーバー)を収容するために設計された特別な建物または施設です。
```

IMHO: "most often" のニュアンスは加えて良いかなと思いました

> A datacenter is a specialized building or facility designed to house computers, most often servers.

2024-04-07 13:29 UTC, Okabe-Junya commented on content/ja/data-center.md
> +ただし、コンピューターのリソース(ハードディスク、メモリ、CPU)は限られていましたので、その上で実行されるアプリケーションには厳しい制約があり、実行できるアプリケーションの種類が制限されます。データセンターが普及する前は、アプリケーションの規模が実行されているコンピューターの容量によって制限されていました。
```suggestion
ただし、コンピューターのリソース(ハードディスク、メモリ、CPU)は限られていたため、その上で実行されるアプリケーションには厳しい制約があり、実行できるアプリケーションの種類が制限されます。
データセンターが普及する前は、アプリケーションの規模が実行されているコンピューターの容量によって制限されていました。
```

1. "限られていましたので" は少し畏まっているので、単に "限られていたため" でどうでしょうか
2. 文末では改行をお願いします

2024-04-07 13:29 UTC, Okabe-Junya commented on content/ja/data-center.md
> +しかし、GmailやNetflixのような大規模なアプリケーション(携帯電話やコンピューターのユーザーインターフェイスではなくサーバーサイドアプリ)について考えてみると、1 台のコンピューターが提供できる能力よりも多くのコンピューティング能力が必要になります。そこでデータセンターが登場します。
```suggestion
しかし、GmailやNetflixのような大規模なアプリケーション(携帯電話やコンピューターのユーザーインターフェースではなくサーバーサイドアプリ)について考えてみると、1 台のコンピューターが提供できる能力よりも多くのコンピューティング能力が必要になります。
そこでデータセンターが登場します。
```

cncf/glossaryの日本語訳では、[Kubernetesのドキュメントを翻訳する](https://kubernetes.io/ja/docs/contribute/localization)のルールに準拠しています。ここでは、"interface" の訳語は "インターフェース" で統一するようになっています

ref. https://kubernetes.io/ja/docs/contribute/localization/#other-notation

2024-04-07 21:38 UTC, shinjichan commented
素早くて的確なコメントありがとうございます！PRタイトルとディスクリプションの訂正、それから頂いた各コメントへコミットしました。よろしくお願いいたします。

2024-04-07 23:43 UTC, Okabe-Junya approved these changes
ご対応ありがとうございます！LGTMです！

2024-04-08 02:14 UTC, naonishijima approved these changes
LGTM

2024-04-08 02:14 UTC, merged