[ja] Localize Distributed System into Japanese
cncf/glossary pull request #3043
Opened 2024-04-11 16:35 UTC by t-katsumura

### Describe your changes

Localize https://glossary.cncf.io/distributed-systems/ into Japanese

### Related issue number or link (ex: `resolves #issue-number`)

Resolve https://github.com/cncf/glossary/issues/2864

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-04-11 18:47 UTC, Okabe-Junya commented
Target previews:

- https://deploy-preview-3043--cncfglossary.netlify.app/ja/distributed-systems/

2024-04-11 19:00 UTC, Okabe-Junya requested changes
ありがとうございます！極めて細かい点で恐縮ですが、ご確認いただければと思います

2024-04-11 19:00 UTC, Okabe-Junya commented on content/ja/distributed-systems.md
> +分散システムは、ネットワーク上で接続された自立型のコンピューティング要素の集合であり、ユーザから見ると1つの統一されたシステムとして見えます。
```suggestion
分散システムは、ネットワーク上で接続された自立型のコンピューティング要素の集合であり、ユーザーから見ると1つの統一されたシステムとして見えます。
```

nits: "user" は長音を付与する表記になっています

FYI: https://kubernetes.io/ja/docs/contribute/localization/#long-vowel

> -er、-or、-ar、-cy、-gyで終わる単語は長音を付与する

2024-04-11 23:58 UTC, t-katsumura commented on content/ja/distributed-systems.md
> +分散システムは、ネットワーク上で接続された自立型のコンピューティング要素の集合であり、ユーザから見ると1つの統一されたシステムとして見えます。
ありがとうございます！
取り込ませていただきますー

2024-04-12 03:55 UTC, Okabe-Junya approved these changes
ありがとうございます！LGTMです！

2024-04-12 09:07 UTC, kaitoii11 requested changes

2024-04-12 09:07 UTC, kaitoii11 commented on content/ja/distributed-systems.md
> +分散コンピューティングなしでは、今日、我々が依存している多くのアプリケーションは実現できないでしょう。
細かいですが、relyはどっちかというと依存よりもちょっと度合いが低いなので、「頼りにする」や「当てにする」が近いかと思います。depend onの方が依存するに近い可と思います。

2024-04-12 09:07 UTC, kaitoii11 commented on content/ja/distributed-systems.md
> +単一のコンピューターでは、アプリケーション全体を提供するのに十分な性能がありません。
このPRは無関係ですが、調べた限り「コンピュータ」と「コンピューター」が混ざってるみたいなので、統一しないとですね。

2024-04-15 01:33 UTC, t-katsumura commented on content/ja/distributed-systems.md
> +分散コンピューティングなしでは、今日、我々が依存している多くのアプリケーションは実現できないでしょう。
ありがとうございます。
「頼りにしている」に修正しました！

2024-04-16 11:03 UTC, kaitoii11 approved these changes
LGTM

2024-04-16 11:03 UTC, merged