[FR] localize multitenancy
cncf/glossary pull request #3143
Opened 2024-05-10 16:07 UTC by Krast76

Localize multitenancy in French

Close #2996.

For reviewers : J'ai longuement hésité entre mutualisation et colocation. Je dois avouer qu'après m'être relu je trouve que colocation est plus appropriée,  WDYT ?

2024-05-10 17:01 UTC, guillaumebernard84 commented
> Localize multitenancy in French
> 
> Close #2996.
> 
> For reviewers : J'ai longuement hésité entre mutualisation et colocation. Je dois avouer qu'après m'être relu je trouve que colocation est plus appropriée, WDYT ?

Le problème c'est qu'en anglais "colocation" désigne  un datacenter dans lequel on peut louer de la place pour mettre ses propres machines. Ça risque d'être confus, du coup. Je préfère donc mutualisation.

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Le logiciel mutualisé fournit pour chaque locataire un environement ségrégué (données de travail, paramètres, liste d'identifiants etc),
environnement avec 2 n

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Le logiciel mutualisé fournit pour chaque locataire un environement ségrégué (données de travail, paramètres, liste d'identifiants etc),
Il manque une virgule derrière identifiants, et un point derrière etc. 

(données de travail, paramètres, liste d'identifiants etc)
==>
(données de travail, paramètres, liste d'identifiants, etc.)

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Cela augmente l'utilisation de ressources et l'effort en maintenant, le coût du logiciel en fin de compte.
l'effort de maintenance

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Cela augmente l'utilisation de ressources et l'effort en maintenant, le coût du logiciel en fin de compte.
Je propose "et au final le coût du logiciel" au lieu de "le coût du logiciel en fin de compte"

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Le logiciel mutualisé fournit pour chaque locataire un environement ségrégué (données de travail, paramètres, liste d'identifiants etc),
ségrégué est un terme correct, mais il me semble qu'en français on dirais plutôt "isolé".
Qu'en pensent les autres?

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +servant simultanément plusieurs locataires. De la perspective du locataire, chacun à son installation logicielle dédiée,
*Depuis* la perspective du locataire
me parait mieux

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +bien qu'en réalité, ils en partagent tous une. Tout cela est possible en exécutant le logiciel sur un serveur et en autorisant
ils en partagent tous *une seule*
me parait mieux

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +[Architecture Client-Server](/fr/client-server-architecture.md).
il manque un U a serveur
Architecture Client-Serveur

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Avec les logiciels mutualisés, Les colocataires partagent les mêmes ressources d'une même installation sans atteindre les autres où seulement
j'aurais mis "affecter" à la place d'atteindre

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Bien qu'il soit commun pour les SaaS d'être mutualisé et même de proposer la mutualisation comme un bénéfice majeurs.
pas de "s" a majeurs, je pense. Sebastien tu confirmes?

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +— Penser à un logiciel de productivité personnelle — ou aussi large qu'une entreprise complète avec
"grand" au lieu de "large" me parait plus français

2024-05-10 20:41 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +manières. Les exemples de colocation incluent : Google Mail, Google Docs, Microsoft Office 365, Salesforce CRM,
colocation ou mutualisation?

2024-05-12 18:06 UTC, Krast76 commented on content/fr/multitenancy.md
> +Cela augmente l'utilisation de ressources et l'effort en maintenant, le coût du logiciel en fin de compte.
C'était un peu familier en effet :p

2024-05-14 15:20 UTC, Krast76 commented on content/fr/multitenancy.md
> +servant simultanément plusieurs locataires. De la perspective du locataire, chacun à son installation logicielle dédiée,
J'aime bien la tournure que j'ai fait.
Vous en pensez quoi les autres ?

2024-05-15 16:35 UTC, seb-835 commented on content/fr/multitenancy.md
> +servant simultanément plusieurs locataires. De la perspective du locataire, chacun à son installation logicielle dédiée,
J'aurais mis une autre tournure encore :( :   "Du point de vue du locataire"

2024-05-15 16:36 UTC, seb-835 commented on content/fr/multitenancy.md
> +Bien qu'il soit commun pour les SaaS d'être mutualisé et même de proposer la mutualisation comme un bénéfice majeurs.
oui, m'sieur je confirme.

2024-05-15 16:38 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +servant simultanément plusieurs locataires. De la perspective du locataire, chacun à son installation logicielle dédiée,
Oui, c'est très bien aussi

2024-05-15 16:41 UTC, seb-835 commented on content/fr/multitenancy.md
> +manières. Les exemples de colocation incluent : Google Mail, Google Docs, Microsoft Office 365, Salesforce CRM,
je préfère "colocation" pour éviter la répétition de "mutualisation"  avec mutualisé en fin de phrase.

2024-05-20 07:58 UTC, sestegra requested changes

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +— Penser à un logiciel de productivité personnelle — ou aussi grand qu'une entreprise complète avec
La phrase est sous la forme impérative.
s/Penser/Pensez/

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +manières. Les exemples de colocation incluent : Google Mail, Google Docs, Microsoft Office 365, Salesforce CRM,
Je pense qu'il est nécessaire de reprendre le titre du terme utilisé.
On donne un exemple pour cette définition, donc "mutualisation".

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +Le logiciel mutualisé fournit pour chaque locataire un environement ségrégué (données de travail, paramètres, liste d'identifiants etc),
Je préfère aussi "isolé"

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +servant simultanément plusieurs locataires. De la perspective du locataire, chacun à son installation logicielle dédiée,
Je vote pour "Du point de vue du locataire" aussi.

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +Avec les logiciels mutualisés, Les colocataires partagent les mêmes ressources d'une même installation sans affecter les autres où seulement
s/Les colocataires/,  la majuscule n'est pas nécessaire

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +Avec les logiciels mutualisés, Les colocataires partagent les mêmes ressources d'une même installation sans affecter les autres où seulement
Dans ce cas, c'est "ou" (car on peut dire "ou bien").

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +d'une manière prédéfinie et contrôlé. Les resources économisées du côté du fournisseur du logiciel peuvent être répercutées aux locataires, réduisant
s/contrôlé/contrôlée/

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +les colocataires à se connecter à celui-ci par le réseau et/ou par une [API](/fr/application-programming-interface.md), se référer à
Dans la version anglaise, la partie `(also refer to Client-Server Architecture)` est entre parenthèse.
Ensuite, je propose la traduction suivante `(faisant référence à une architecture client-serveur)`.

2024-05-20 07:58 UTC, sestegra commented on content/fr/multitenancy.md
> +de manière significative le coût du logiciel pour les utilisateurs (encore une fois, pensez aux emails et aux éditeurs de documents en ligne).
Je trouve que `ou` passe mieux que `et`
`pensez aux emails ou aux éditeurs`

2024-05-26 15:37 UTC, sandrineperrin reviewed
quelques propositions sur la syntaxe

2024-06-09 16:19 UTC, Krast76 commented on content/fr/multitenancy.md
> +Bien qu'il soit commun pour les SaaS d'être mutualisé et même de proposer la mutualisation comme un bénéfice majeur.
Je suis pas sûr là, on parle d'un logiciel à la demande et d'une solution en SaaS ? 🤔

2024-06-09 16:20 UTC, Krast76 commented on content/fr/multitenancy.md
> +Le logiciel mutualisé fournit pour chaque locataire un environnement ségrégué (données de travail, paramètres, liste d'identifiants, etc.),
J'aime bien configurations, en effet.

2024-06-09 16:21 UTC, Krast76 commented on content/fr/multitenancy.md
> +les colocataires à se connecter à celui-ci par le réseau et/ou par une [API](/fr/application-programming-interface.md), se référer à
Je pensais que ça faisait référence a une interface au sens "réseau", je trouvais ça un peu plus clair sans le redire ici pour le coup :)

2024-06-10 17:51 UTC, guillaumebernard84 commented on content/fr/multitenancy.md
> +Bien qu'il soit commun pour les SaaS d'être mutualisé et même de proposer la mutualisation comme un bénéfice majeur.
moi je suis d'accord sur le s'accorde, mais pas sur le genre des SaaS 😆 
Mais il faut bien accorder en nombre
s/mutualisé/mutualisés/

2024-06-12 16:17 UTC, sestegra commented on content/fr/multitenancy.md
> +Bien qu'il soit commun pour les SaaS d'être mutualisé et même de proposer la mutualisation comme un bénéfice majeur.
Je suis pour la version s/mutualisé/mutualisés/

2024-06-12 16:19 UTC, sestegra commented on content/fr/multitenancy.md
> +les colocataires à se connecter à celui-ci par le réseau et/ou par une [API](/fr/application-programming-interface.md), se référer à
Je pense aussi que c'est une interface graphique (console graphique)

2024-07-02 17:32 UTC, sestegra commented on content/fr/multitenancy.md
> +les colocataires à se connecter à celui-ci par le réseau et/ou par une [API](/fr/application-programming-interface.md) (faisant référence à une
Les liens doivent avoir un slash final sans le .md.

2024-07-14 07:54 UTC, sestegra commented on content/fr/multitenancy.md
> +tags: ["architecture", "property", ""]
s/property/propriété/

2024-07-22 18:58 UTC, guillaumebernard84 approved these changes
LGTM :rocket:

2024-07-23 18:10 UTC, sestegra commented on content/fr/multitenancy.md
> +d'une manière prédéfinie et contrôlée. Les resources économisées du côté du fournisseur du logiciel peuvent être répercutées aux locataires, réduisant
s/resources économisées/ressources économisées/

2024-07-24 14:40 UTC, sestegra approved these changes
LGTM 🚀

2024-07-24 14:40 UTC, merged