it-update-sre-#3108
cncf/glossary pull request #3150
Opened 2024-05-17 07:04 UTC by matteobisi

### Describe your changes
IT localization udpdate of SRE page

### Related issue number or link (ex: `resolves #issue-number`)
#3108 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-05-17 10:38 UTC, ugho16 approved these changes

2025-04-10 10:18 UTC, sistella requested changes
Ho aggiunto i tag e le interruzioni di riga che mancavano. Oltre a qualche altro suggerimento per migliorare la traduzione.

2025-04-10 10:18 UTC, sistella commented on content/it/site-reliability-engineering.md
> +Site Reliability Engineering o SRE è una disciplina che combina operations e ingegneria del software. Quest'ultima viene applicata specificamente a problemi infrastrutturali e operativi. In altre par
```suggestion
Site Reliability Engineering o SRE è una disciplina che combina gestione ordinaria e ingegneria del software. 
Quest'ultima viene applicata specificamente a problemi infrastrutturali e operativi. 
In altre parole, invece di creare funzionalità di prodotto, i Site Reliability Engineers realizzano i sistemi per eseguire le applicazioni. 
Ci sono alcune somiglianze con [DevOps](/it/devops/), ma mentre DevOps si concentra sul portare il codice in produzione, 
SRE garantisce che il codice in produzione funzioni correttamente.
```

riguardo la traduzione di _operations_, mi sono rifatto a quanto avevamo in managed_services.md . Non so se mi piace al 100%, ma credo che dovremmo tradurlo.
Ho esteso il secondo SRE perché fa riferimento agli Engineers, e poteva confondersi con l'acronimo che era invece proposto per Engineering. (Non credo sia traducibile, anche se sarebbe bello...)

2025-04-10 10:18 UTC, sistella commented on content/it/site-reliability-engineering.md
> +Un approccio SRE riduce al minimo i costi, i tempi e gli sforzi del processo di sviluppo del software migliorando in modo continuo l’infrastruttura. Il sistema misura e monitora continuamente l'infra
```suggestion
Un approccio SRE riduce al minimo i costi, i tempi e gli sforzi del processo di sviluppo del software migliorando in modo continuo l’infrastruttura. 
Il sistema misura e monitora continuamente l'infrastruttura e i componenti dell'applicazione. 
Quando qualcosa va storto, il sistema indica ai SRE quando, dove e come risolvere il problema. 
Questo approccio aiuta a creare sistemi software altamente [scalabili](/it/scalability/) e affidabili, automatizzando le attività operative.
```

2025-04-11 09:31 UTC, ugho16 approved these changes
LGTM

2025-04-11 12:45 UTC, sistella approved these changes
Great!

2025-04-15 11:48 UTC, merged