dev-pt-2379 container orchestration
cncf/glossary pull request #3151
Opened 2024-05-17 08:17 UTC by fharris

### Describe your changes
Localize https://glossary.cncf.io/container-orchestration/.

### Related issue number or link (ex: `resolves #issue-number`)
resolves #2379 

### Checklist before opening this PR (put `x` in the checkboxes)
- [X] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-05-26 22:03 UTC, edsoncelio requested changes
Hi @fharris 
I made a few comments before approving it.
Please take a look and in case of doubt let me know.

2024-05-26 22:03 UTC, edsoncelio commented on content/pt-br/container-orchestration.md
> +É executado através de um Orquestrador de Contêiners ([Kubernetes](/kubernetes) na maioria dos casos). Plataformas que possibilitam e facilitam a implantação controlada de multiplos aplicativos,  o s
The links need to be updated to point to the pt-br version, like:
* pt-br/container
* pt-br/containerization
* pt-br/kubernetes
* pt-br/scalability

Please take a look and update the other occurrences.

2024-05-26 22:03 UTC, edsoncelio commented on content/pt-br/container-orchestration.md
> +Plataformas e respectivas ferramentas de orquestração de contêiners, são eminentemente declarativas. Isto é, permitem declarar o estado desejável do sistema, como por exemplo o número de containers,
"containers" -> "contêineres"

2024-05-27 09:18 UTC, fharris commented
Thank you @edsoncelio . Changed accordingly to your review.

2024-05-31 15:42 UTC, edsoncelio approved these changes
Thanks!

2024-05-31 15:46 UTC, merged