it-update-observability-term-#3103
cncf/glossary pull request #3154
Opened 2024-05-20 07:55 UTC by matteobisi

### Describe your changes
IT localization update, observability

### Related issue number or link (ex: `resolves #issue-number`)
#3103 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-05-20 13:54 UTC, ugho16 commented on content/it/observability.md
> +I sistemi osservabili forniscono dati significativi e utilizzabili ai loro operatori, permettendo loro di raggiungere risultati favorevoli (risposta agli incidenti più rapida, maggiore produttività d
```suggestion
I sistemi osservabili forniscono dati significativi e utilizzabili dai loro operatori, permettendo loro di raggiungere risultati favorevoli (risposta agli incidenti più rapida, maggiore produttività di chi sviluppa) 
```

2025-05-06 09:47 UTC, sistella requested changes

2025-05-06 09:47 UTC, sistella commented on content/it/observability.md
> +L'osservabilità è una proprietà di un sistema che definisce il grado in cui il sistema può generare informazioni utili,
```suggestion
L'osservabilità è una proprietà di un sistema che definisce il grado in cui il sistema può generare informazioni utili.
```

2025-05-06 09:47 UTC, sistella commented on content/it/observability.md
> +permette agli utenti di comprendere lo stato di un sistema dai suoi risultati esterni e intervenire di conseguenza (correggendo).
```suggestion
Permette agli utenti di comprendere lo stato di un sistema sulla base dei suoi risultati, ed all'occorrenza di intervenire per correggerlo.
```
Vedi un po' se ti piace di più...

2025-05-06 09:47 UTC, sistella commented on content/it/observability.md
> +In conclusione, quanto sia osservabile un sistema influenzerà significativamente i suoi costi operativi e di sviluppo.
```suggestion

In conclusione, quanto sia osservabile un sistema influenzerà significativamente i suoi costi operativi e di sviluppo.
```

2025-05-07 15:20 UTC, matteobisi commented
modifiche committate

2025-05-22 14:39 UTC, ugho16 approved these changes

2025-05-22 14:40 UTC, merged