2530 german localize continuous deployment
cncf/glossary pull request #3161
Opened 2024-05-24 07:55 UTC by DaveVentura

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [X ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-07-05 17:11 UTC, iamNoah1 requested changes
Danke @DaveVentura hab n paar Kommentare da gelassen

2024-07-05 17:11 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +Continuous Deployment, oft abgekürzt als CD, bezeichnet, wie [Continuous Delivery](/continuous-delivery), die automatische Bereitstellung von Software und geht dabei einen Schritt weiter als, indem f
da fehlt noch was `geht dabei noch einen Schritt als ...., `. Ich würde statt Produktion, Produktivsystem benutzen. Ich glaube anderen Stellen benutzen wir auch eher Produktivsystem oder sowas.

2024-07-05 17:11 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +Während der CI-Prozess, die Änderungen an der Codebasis validiert, stellt der CD-Prozess diese automatisch in den Umgebungen eines Unternehmens von der Testphase bis hin zur Produktion bereit.
siehe Kommentar zu Produktion -> Produktivsystem

2024-07-05 17:11 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +Mit dem ursprünglichen Prozess werden häufige Bereitstellungen vermieden, um Störungen in der Produktion zu vermeiden und die Notwendigkeit von Abrufbereitschaften von Technikern außerhalb der Geschä
Was ist hier mit ursprünglichem Prozess gemeint? Finde den Satz ziemlich lang und schwer zu greifen.

2024-07-05 17:11 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +So tritt das Problem auf, dass die Geschwindigkeit und Stabilität von Auslieferungen neuer Funktionen nicht den Anforderungen des Unternehmens entspricht.
Ich finde es schwierig allgemeine Aussagen über die Anforderungen von Unternehmen zu machen. Vielleicht haben manche Unternehmen überhaupt nicht die Anforderung schnell und oft zu deployen. 
Ich würde eher explizit hier sagen was es bedeutet nicht mit CICD zu arbeiten: deployments sind fehleranfällig, dauern lange etc

2024-07-05 17:11 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +Die Automatisierung des Release-Zyklus ermöglicht häufigere und einfachere Bereitstellung auf den Systemen bis hin zur Produktionsumgebung.
Hier Release als neues Wort einzuführen finde ich irreführend. Genau wie die neue Wortwahl Produktionsumgebung. Das sollte das gleiche Wort überall sein.

2024-09-27 06:06 UTC, DaveVentura commented
Danke für das review und sorry für die späte reaktion, habe es nicht mitbekommen.

Ich habe deine deine anmerkungen bearbeitet.
Es entspricht tw. aber nicht was wir besprochen haben, dass wir uns an der englischen Fassung orientieren. Habe es trotzdem entsprechend deiner Wünsche angepasst.

Ich gebe dir auch inhaltlich Recht, die englische Fassung ist manchmal komisch. Vlt sollten wir mal drüber reden, wie wir damit umgehen und die Inhalte auch in der englsichen Version beanstanden..

2024-09-27 16:19 UTC, iamNoah1 requested changes
Nur noch das eine fehlende Wort, dann sind wir soweit

2024-09-27 16:19 UTC, iamNoah1 commented on content/de/continuous-deployment.md
> +Außerdem kann es Tage oder Wochen dauern, dass sie durchgeführt werden, da sie oft von anderen Abteilungen als die, die Software entwickelt.
hier fehlt ein Wort im Satz.

2024-10-15 12:07 UTC, iamNoah1 approved these changes
lgtm :)

2024-10-15 12:07 UTC, merged