[ru] Localize `Edge computing`
cncf/glossary pull request #3216
Opened 2024-07-14 09:46 UTC by kirkonru

Create edge-computing.md and translate it into Russian

### Describe your changes
This PR is to localize edge-computing.md into Russian

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-07-23 11:05 UTC, shurup requested changes
We need to decide which translation we prefer to use as the primary one. Other corrections are optional.

2024-07-23 11:05 UTC, shurup commented on content/ru/edge-computing.md
> +Это достигается за счёт переноса части ресурсов для хранения и обработки данных из ЦОД к месту, где эти данные генерируются: периферийному устройству.
```suggestion
Это достигается за счёт переноса части ресурсов для хранения и обработки данных из ЦОД в место, где эти данные генерируются: периферийное устройство. 
```

2024-07-23 11:05 UTC, shurup commented on content/ru/edge-computing.md
> +Одним словом, эффективность и скорость — главная движущая сила пограничных вычислений.
Perhaps my version is a bit less precise, but sounds better (IMHO) :sweat_smile: 
```suggestion
Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений. 
```

2024-09-07 10:32 UTC, kirkonru commented on content/ru/edge-computing.md
> +Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений.
```suggestion
Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений.   
```

2024-09-07 10:34 UTC, kirkonru commented on content/ru/edge-computing.md
> +Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений.
```suggestion
Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений.
```

2024-10-08 17:44 UTC, shurup commented
Now, I am confused why we have "Граничные вычисления" in the title but "Пограничные вычисления" at the very beginning of this article. Russian Wikipedia sticks to "Граничные" only. I suggest doing the same (consistently throughout the text).

2024-10-09 06:27 UTC, kirkonru commented on content/ru/edge-computing.md
> +*Пограничные вычисления* (edge computing), также известные как *периферийные* — это подход к [распределённым системам](/ru/distributed-systems/), при котором часть задач по хранению и обработке данны
```suggestion
*Граничные вычисления* (edge computing), также известные как *периферийные* — это подход к [распределённым системам](/ru/distributed-systems/), при котором часть задач по хранению и обработке данных переносится от основного [центра обработки данных](/ru/data-center/) к источнику данных. 
```

2024-10-09 06:27 UTC, kirkonru commented on content/ru/edge-computing.md
> +Одним словом, эффективность и скорость — решающие факторы для пограничных вычислений.
```suggestion
Одним словом, эффективность и скорость — решающие факторы для граничных вычислений.
```

2024-10-09 07:34 UTC, tym83 approved these changes

2024-10-09 17:12 UTC, shurup approved these changes
Thank you; LGTM now!

2024-10-09 17:38 UTC, merged