[en] Small fix for horizontal-scaling.md
cncf/glossary pull request #3241
Opened 2024-07-24 05:32 UTC by shurup

### Describe your changes
Fixing the wrong statement that adding 4 x 4GB RAM nodes to a system of 4GB RAM will result in having 16GB RAM (it'll be 20GB then). I'm also removing a link to the Nodes article since this word was already linked in the previous paragraph.

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-08-27 16:14 UTC, iamNoah1 requested changes
Nice catch @shurup but why did you remove the link to the nodes term?

2024-08-28 03:28 UTC, shurup commented
Hi @iamNoah1! As I noticed, due to a repeated link in this article, I don't think it's necessary. Please let me know if I'm wrong.

>  I'm also removing a link to the Nodes article since this word was already linked in the previous paragraph.

2024-08-28 08:05 UTC, iamNoah1 approved these changes
lgtm, thanks @shurup

2024-08-28 10:31 UTC, seokho-son approved these changes
lgtm

2024-08-28 10:31 UTC, merged