add pt-br/horizontal-scaling
cncf/glossary pull request #3259
Opened 2024-07-29 13:30 UTC by rafaelmnatali

### Describe your changes
Added definition for `horizontal scaling`

### Related issue number or link (ex: `resolves #issue-number`)
https://github.com/cncf/glossary/issues/824

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-07-31 13:23 UTC, edsoncelio requested changes
Thanks! Just a tiny typo: after that, it will be LGTM!

2024-07-31 13:23 UTC, edsoncelio commented on content/pt-br/horizontal-scaling.md
> +Essa abordagem melhora o desempenho de uma aplicação adicionando novas instâncias, ou n ós, para distribuir melhor a carga de trabalho.
nit:"n ós"

2024-07-31 20:01 UTC, rafaelmnatali commented on content/pt-br/horizontal-scaling.md
> +Essa abordagem melhora o desempenho de uma aplicação adicionando novas instâncias, ou n ós, para distribuir melhor a carga de trabalho.
fixed.

2024-07-31 20:02 UTC, edsoncelio approved these changes
LGTM
Thanks!!

2024-08-05 12:25 UTC, edsoncelio commented
PTAL @brunoguidone @jessicalins

2024-08-05 13:06 UTC, MrErlison commented on content/pt-br/horizontal-scaling.md
> +tags: ["infrastructure", "", ""]
You forgot the tag.

2024-08-05 13:09 UTC, MrErlison commented on content/pt-br/horizontal-scaling.md
> +tags: ["infrastructure", "", ""]
"infraestrutura" instead "infrastructure"

Like Edson said, "just a tiny fix". After that LGTM!

Thank you!

2024-09-05 07:45 UTC, closed without merging