Create content/es/runtime.md
cncf/glossary pull request #3260
Opened 2024-08-01 16:00 UTC by SullyMA

I created a new file name runtime.md in Spanish to match the English file

### Describe your changes

### Related issue number or link (ex: `resolves #issue-number`)

### Checklist before opening this PR (put `x` in the checkboxes)
- [X ] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [X ] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-08-06 00:38 UTC, ramrodo commented on content/es/runtime.md
> +- [Cloud Native](https://glossary.cncf.io/cloud-native-apps/)
```suggestion
- [Cloud Native](https://glossary.cncf.io/es/cloud-native-apps/)
```

2024-08-06 00:39 UTC, ramrodo commented on content/es/runtime.md
> +- [Containerization](https://glossary.cncf.io/containerization/)
```suggestion
- [Contenerización](https://glossary.cncf.io/es/containerization/)
```

2024-08-06 00:39 UTC, ramrodo commented on content/es/runtime.md
> +- [Container Orchestration](https://glossary.cncf.io/container-orchestration/)
```suggestion
- [Orquestación de Contenedores](https://glossary.cncf.io/es/container-orchestration/)
```

2024-08-06 00:40 UTC, ramrodo commented on content/es/runtime.md
> +- [Microservices Architecture](https://glossary.cncf.io/microservices-architecture/)
```suggestion
- [Arquitectura de Microservicios](https://glossary.cncf.io/es/microservices-architecture/)
```

2024-08-06 00:43 UTC, ramrodo commented on content/es/runtime.md
> +Un *runtime*, en general, ejecuta un fragmento de software. Es una [abstracción](https://glossary.cncf.io/abstraction/) del sistema operativo subyacente que traduce los comandos del programa en accio
```suggestion
Un *runtime*, en general, ejecuta un fragmento de software. Es una [abstracción](/es/abstraction/) del sistema operativo subyacente que traduce los comandos del programa en acciones correspondientes para el sistema operativo.
```

2024-08-06 00:43 UTC, ramrodo commented on content/es/runtime.md
> +En el contexto de [cloud native](https://glossary.cncf.io/runtime/), *runtime* generalmente se refiere al *container runtime*. Un *container runtime* implementa específicamente la especificación de l
```suggestion
En el contexto de [cloud native](/es/cloud-native-apps/), *runtime* generalmente se refiere al *container runtime*. Un *container runtime* implementa específicamente la especificación de la [Open Container Initiative](https://opencontainers.org/) para asegurar un manejo consistente a través de diferentes tecnologías de orquestación de contenedores.
```

2024-08-06 00:45 UTC, ramrodo commented on content/es/runtime.md
> +**Problema que resuelve**
```suggestion
## Problema que aborda
```

2024-08-06 00:45 UTC, ramrodo commented on content/es/runtime.md
> +**Cómo ayuda**
```suggestion
## ¿Cómo ayuda?
```

2024-08-06 00:48 UTC, ramrodo requested changes
Thanks, Sully!

I left some suggestions.

2024-08-06 01:11 UTC, ramrodo commented on content/es/runtime.md
> +## Related terms
```suggestion
## Términos relacionados
```

2024-08-06 01:12 UTC, ramrodo commented
@SullyMA also, we need to add the following word to the `content/es/.wordlist.txt` file (to have the test in green):

- runtimes

2024-08-09 19:17 UTC, ramrodo approved these changes
LGTM. Thanks!

2024-08-09 19:18 UTC, ramrodo commented
/cc @electrocucaracha @krol3

2024-08-14 19:15 UTC, electrocucaracha requested changes

2024-08-14 19:15 UTC, electrocucaracha commented on content/es/runtime.md
> +Un *runtime*, en general, ejecuta un fragmento de software. Es una [abstracción](/es/abstraction/) del sistema operativo subyacente que traduce los comandos del programa en acciones correspondientes
```suggestion
Un *runtime*, en general, ejecuta un fragmento de software.
Es una [abstracción](/es/abstraction/) del sistema operativo subyacente que traduce los comandos del programa en acciones correspondientes para el sistema operativo.
```

2024-08-14 19:15 UTC, electrocucaracha commented on content/es/runtime.md
> +En el contexto de [cloud native](/es/cloud-native-apps/), *runtime* generalmente se refiere al *container runtime*. Un *container runtime* implementa específicamente la especificación de la [Open Con
```suggestion
En el contexto de [cloud native](/es/cloud-native-apps/), *runtime* generalmente se refiere al *container runtime*.
Un *container runtime* específicamente implementa la especificación de la [Open Container Initiative](https://opencontainers.org/) para asegurar un manejo consistente a través de diferentes tecnologías de orquestación de contenedores.
```

2024-08-14 19:15 UTC, electrocucaracha commented on content/es/runtime.md
> +Con el tiempo, diferentes productos de *container runtime* evolucionaron, llevando a la Especificación OCI, que se convirtió en el estándar para los *container runtimes*.
```suggestion
Los *container runtimes* son un componente necesario de los orquestadores de contenedores como Kubernetes.
Manejan el ciclo de vida del contenedor, lo cual hace principalmente tres cosas.
Primero, define cómo se especifican las imágenes de los contenedores y cómo el *runtime* puede recuperarlas.
En segundo lugar, gestionan cómo estas imágenes se descomprimen, se apilan, se montan y se ejecutan.
Por último, los *runtimes* gestionan los recursos de hardware, encargándose de todas estas acciones a nivel del sistema operativo.
Esto incluye la asignación y el aislamiento de recursos.
Con el tiempo, diferentes productos de *container runtime* evolucionaron, llevando a la Especificación OCI,
que se convirtió en el estándar para los *container runtimes*.
```

2024-08-14 19:15 UTC, electrocucaracha commented on content/es/runtime.md
> +category: concept
```suggestion
category: Concepto
```

2024-08-14 19:15 UTC, electrocucaracha commented on content/es/runtime.md
> +tags: ["application", "", ""]
```suggestion
tags: ["aplicación", "", ""]
```

2024-08-14 20:07 UTC, electrocucaracha approved these changes

2024-08-14 20:07 UTC, merged