fix links
cncf/glossary pull request #3271
Opened 2024-08-06 16:56 UTC by guillaumebernard84

### Describe your changes
Fix links before merging to main

### Related issue number or link (ex: `resolves #issue-number`)
needed before merging this PR: https://github.com/cncf/glossary/pull/3270

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-08-07 16:17 UTC, seb-835 approved these changes
LGTM 🚀

2024-08-07 17:22 UTC, sestegra requested changes

2024-08-07 17:22 UTC, sestegra commented on content/fr/chaos-engineering.md
> +comme l'infrastructure, la plateforme ou d'autres parties d'une application ([microservice](/fr/microservices-architecture/).
Il manque une parenthèse fermante

2024-08-07 20:51 UTC, guillaumebernard84 commented on content/fr/chaos-engineering.md
> +comme l'infrastructure, la plateforme ou d'autres parties d'une application ([microservice](/fr/microservices-architecture/).
bien vu, c'est corrigé

2024-08-08 12:03 UTC, sestegra approved these changes
LGTM 🚀

2024-08-08 12:03 UTC, merged