[FR] update `idempotence`
cncf/glossary pull request #3279
Opened 2024-08-19 19:21 UTC by guillaumebernard84

### Describe your changes
[FR] update `idempotence` following changes in English

### Related issue number or link (ex: `resolves #issue-number`)
N/A

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-08-23 08:44 UTC, Krast76 approved these changes
LGTM 🚀

2024-08-24 14:27 UTC, sestegra requested changes

2024-08-24 14:27 UTC, sestegra commented on content/fr/idempotence.md
> +Si les paramètres sont identiques, exécuter une opération idempotente plusieurs fois n'aura pas d'effet supplémentaire.
Je propose une version légèrement différente
"n'aura aucun effet supplémentaire"

2024-08-25 14:33 UTC, guillaumebernard84 commented on content/fr/idempotence.md
> +Si les paramètres sont identiques, exécuter une opération idempotente plusieurs fois n'aura pas d'effet supplémentaire.
Tu as raison, ça me parait mieux. C'est corrigé

2024-09-04 16:29 UTC, sestegra approved these changes
LGTM 🚀

2024-09-04 16:29 UTC, merged