[FR] add webassembly
cncf/glossary pull request #3320
Opened 2024-10-11 19:33 UTC by guillaumebernard84

### Describe your changes
add webassembly in french

### Related issue number or link (ex: `resolves #issue-number`)
solves https://github.com/cncf/glossary/issues/3319

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-12-18 10:46 UTC, sestegra requested changes

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +WebAssembly (souvent abrégé en Wasm) est un format d'instructions binaires conçu comme une cible de compilation portable pour des langages de haut niveau tels que C, C++, Rust et autres. Il permet le
Je propose d'ajouter "d'" pour
```pour des langages de haut niveau tels que C, C++, Rust et d'autres```

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
Je propose de remplace "dans les navigateurs web" par "aux navigateurs web"

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
Je suggère d'ajouter un i majuscule à Internet ici, car il est donné à titre général.
"Internet des objets"

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +Pendant de nombreuses années, la pile LAMP (Linux Apache MySQL PHP) a été la norme pour les applications web. Plus tard, Javascript a dominé le développement d'applications frontales et les applicati
Je propose de remplace "Plus tard" par "Par la suite"

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +Il permet aux développeurs de créer des applications web en s'appuyant sur leurs compétences existantes dans des langages tels que C, C++, Rust et autres.
Même remarque "et d'autres"

2024-12-18 10:46 UTC, sestegra commented on content/fr/webassembly.md
> +Cela ouvre de nouvelles possibilités et permet aux développeurs de réutiliser les bases de code et les bibliothèques existantes.
Je propose de mettre "des" à la place de "les" 
```réutiliser des bases de code et des bibliothèques existantes.```

2024-12-19 20:22 UTC, guillaumebernard84 commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
haha, je suis de l'autre camps, celui des minuscules. 
Mais je peux m'adapter. Par contre ça me fait bizarre de mettre une majuscule a Internet et pas Objets dans l'expression "l'Internet des Objets". Tu en penses quoi?

2024-12-22 09:30 UTC, sestegra commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
J'ai fait une recherche, je trouve toutes les combinaisons possibles.
Néanmoins, celle la plus souvent utilisée est "l'Internet des objets".
Qu'en penses les autres ?

2025-01-01 16:18 UTC, Krast76 commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
Pour le coup, j'aurais mis "Internet des Objets" également.

2025-01-01 20:18 UTC, guillaumebernard84 commented on content/fr/webassembly.md
> +Il s'agit d'un format de code à octets (bytecode en anglais) de bas niveau qui peut être exécuté dans une machine virtuelle, généralement intégrée dans les navigateurs web. Bien qu'initialement dével
Allez, on fait comme ça!

2025-01-05 14:37 UTC, sestegra approved these changes
🚀 LGTM

2025-03-16 15:45 UTC, Krast76 approved these changes
Very late is better than never 😞 

LGTM 🚀

2025-03-16 15:46 UTC, Krast76 commented
Oh ! 

@guillaumebernard84 ta MR vise cncf:main et non dev-fr, à un poil de pouvoir merge :)

2025-03-16 17:24 UTC, guillaumebernard84 commented
J'ai changé la branche cible @Krast76

2025-03-16 20:53 UTC, merged