[ru] Localize reliability.md
cncf/glossary pull request #3351
Opened 2024-11-05 05:42 UTC by vickylikh

### Describe your changes

This PR adds RU localization of reliability.

### Related issue number #3266 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2025-01-10 09:07 UTC, shurup requested changes
I have a few formal corrections, and happy to approve this translation!

2025-01-10 09:07 UTC, shurup commented on content/ru/reliability.md
> +title: Reliability
```suggestion
title: Надежность
```

2025-01-10 09:07 UTC, shurup commented on content/ru/reliability.md
> +Если [распределенная система](/distributed-systems/) продолжает работать при изменениях инфраструктуры и отказе отдельных компонентов, она надежна.
```suggestion
Если [распределенная система](/ru/distributed-systems/) продолжает работать при изменениях инфраструктуры и отказе отдельных компонентов, она надежна. 
```

2025-01-10 09:07 UTC, shurup commented on content/ru/reliability.md
> +Цель [нативных облачных приложений](/cloud-native-apps/) — создавать изначально надежные системы.
```suggestion
Цель [нативных облачных приложений](/ru/cloud-native-apps/) — создавать изначально надежные системы.
```

2025-01-10 09:39 UTC, shurup approved these changes

2025-03-28 08:54 UTC, kirkonru approved these changes

2025-03-28 08:54 UTC, merged