added the sign language video style guide (lang/es)
cncf/glossary pull request #3357
Opened 2024-11-20 02:33 UTC by tech-andgar

### Describe your changes

added the sign language video style guide (lang/es)

### Related issue number or link (ex: `resolves #issue-number`)

related to issue https://github.com/cncf/glossary/issues/3044#issue-2239321408

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-11-20 02:37 UTC, tech-andgar commented
Based of https://github.com/cncf/glossary/pull/3313

Ping: @seokho-son

2024-11-20 03:16 UTC, electrocucaracha requested changes
@tech-andgar muchas gracias por la actualización en el documento, parece ser que [algunas palabras](https://github.com/cncf/glossary/actions/runs/11925627296/job/33238702584?pr=3357) no están registradas en el [diccionario local](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt), podrías agregarlas en orden alfabético para que pueda pasar el CI?

2024-11-20 03:16 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +### Postproducción
Según la [RAE](https://dle.rae.es/posproducci%C3%B3n)

```suggestion
### Posproducción
```

2024-11-20 03:16 UTC, electrocucaracha commented on content/es/style-guide/_index.md
> +Si deseas contribuir con un video en lengua de señas, sigue estas pautas para garantizar que los videos sean claros, informativos y accesibles para una audiencia amplia (incluyendo miembros de la com
@ramrodo @krol3 habrá que definir si utilizaremos video o vídeo, ya que ambas son válidas en la [RAE](https://www.rae.es/dpd/video)

2024-11-20 22:06 UTC, tech-andgar commented
> @tech-andgar muchas gracias por la actualización en el documento, parece ser que [algunas palabras](https://github.com/cncf/glossary/actions/runs/11925627296/job/33238702584?pr=3357) no están registradas en el [diccionario local](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt), podrías agregarlas en orden alfabético para que pueda pasar el CI?

Actualizado archivo local

2024-11-21 01:09 UTC, electrocucaracha commented
@tech-andgar las palabras que agregaste están en el orden correcto, pero parece ser que tu editor de texto está cambiando, el fin del documento, por lo general eso sucede con editores windows o por alguna [configuración](https://stackoverflow.com/a/10419350) en git (`git config --global core.autocrlf true`).

Por otra parte, recuerda que cada commit debe ser firmado, en caso contrario no podra pasar el verificador de DCO

2024-11-21 16:16 UTC, electrocucaracha commented
De mi parte `video` debería no tener acento y ser agregado al `.wordlist`, pero me gustaría conocer lo que opinan @ramrodo @krol3 @jossemarGT @92nqb

2024-11-21 20:13 UTC, ramrodo commented
> De mi parte `video` debería no tener acento y ser agregado al `.wordlist`, pero me gustaría conocer lo que opinan @ramrodo @krol3 @jossemarGT @92nqb

Yo también estoy acostumbrado a escribir "video" sin acento. Sin embargo, investigando en la RAE, ambas son válidas: la opción sin acento mayormente usada en América Latina y con acento usada en España: https://www.rae.es/dpd/video

Mi conclusión personal sería igual que @electrocucaracha, usar la opción sin acento (y agregarla al `.wordlist`) ya que es la opción más usada en diferentes países de habla hispana.

2024-11-22 14:59 UTC, krol3 commented
> > De mi parte `video` debería no tener acento y ser agregado al `.wordlist`, pero me gustaría conocer lo que opinan @ramrodo @krol3 @jossemarGT @92nqb
> 
> Yo también estoy acostumbrado a escribir "video" sin acento. Sin embargo, investigando en la RAE, ambas son válidas: la opción sin acento mayormente usada en América Latina y con acento usada en España: https://www.rae.es/dpd/video
> 
> Mi conclusión personal sería igual que @electrocucaracha, usar la opción sin acento (y agregarla al `.wordlist`) ya que es la opción más usada en diferentes países de habla hispana.

+1 sin acento video

2024-11-22 16:06 UTC, electrocucaracha commented
@tech-andgar puedes agregar la palabra `video` al wordlist para que pase el CI y aprobar este cambio?

2024-11-22 16:18 UTC, tech-andgar commented
> @tech-andgar puedes agregar la palabra `video` al wordlist para que pase el CI y aprobar este cambio?

@electrocucaracha 
Listo

2024-11-22 21:08 UTC, ramrodo approved these changes

2024-11-22 21:08 UTC, merged

2024-11-25 15:52 UTC, tech-andgar commented
Muchas gracias @electrocucaracha @ramrodo @krol3