Localize service mesh
cncf/glossary pull request #3358
Opened 2024-11-29 10:46 UTC by classy-faker

### Describe your changes

Localize [Service Mesh](https://github.com/cncf/glossary/blob/main/content/en/service-mesh.md) into Russian.

### Related issue number or link (ex: `resolves #issue-number`)

Resolves #3332. 

### Checklist before opening this PR (put `x` in the checkboxes)
- [x] This PR does not contain plagiarism
  - don’t copy other people’s work unless you are quoting and contributing it to them.
- [x] I have signed off on all commits 
  - [signing off](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) (ex: `git commit -s`) is to affirm that commits comply [DCO](https://wiki.linuxfoundation.org/dco). If you are working locally, you could add an alias to your `gitconfig` by running `git config --global alias.ci "commit -s"`.

2024-11-29 12:22 UTC, kirkonru commented
Thanks for your contribution! LGTM

2024-11-29 12:23 UTC, kirkonru approved these changes

2025-01-10 09:03 UTC, shurup requested changes
Thank you! A few small corrections from me, and I'm happy to approve.

2025-01-10 09:03 UTC, shurup commented on content/ru/service-mesh.md
> +Встраивание этих функций в каждое приложение осложнит взаимодействие инженерных команд и замедлит развёртывание новых фичей.
Well, is it legit to refer to the grammatical cases' table [here](https://ru.wiktionary.org/wiki/%D1%84%D0%B8%D1%87%D0%B0)? :-D
```suggestion
Встраивание этих функций в каждое приложение осложнит взаимодействие инженерных команд и замедлит развёртывание новых фич. 
```

2025-03-03 11:06 UTC, kirkonru commented
@shurup thanks for the suggestions! @classy-faker has kindly granted me the permission to accept all of the changes you have suggested. Please review!

P. S. If approved, could you also do **squash and merge** as well? 🙏🏽

2025-04-01 05:18 UTC, shurup approved these changes

2025-04-01 05:18 UTC, merged