localize content/hi/abstraction.md
cncf/glossary pull request #355
Opened 2022-01-24 19:31 UTC by Shubh28698

Hi,

This PR is Hindi localization of content/hi/abstraction.md page.

ref : https://github.com/cncf/glossary/issues/270#issuecomment-998098556

/lang hi

@anubha-v-ardhan  @Garima-Negi Please review

2022-01-25 04:20 UTC, anubha-v-ardhan requested changes
Some NITs, otherwise LGTM
Thankyou @Shubh28698

2022-01-25 04:20 UTC, anubha-v-ardhan commented on content/hi/abstraction.md
> +कंप्यूटिंग के संदर्भ में, ऐब्स्ट्रैक्शन एक निरूपण है जो सेवाओं के उपभोक्ता से विशिष्टताओं को छुपाता है, एक सिस्टम को अधिक सामान्य बनाता है और इस प्रकार आसानी से समझा जाता है। आपके लैपटॉप का ऑपरेटिंग
```suggestion
कंप्यूटिंग के संदर्भ में, ऐब्स्ट्रैक्शन एक निरूपण है जो सेवाओं के उपभोक्ता से विशिष्टताओं को छुपाता है, एक सिस्टम को अधिक सामान्य बनाता है और इस प्रकार आसानी से समझा जाता है। आपके लैपटॉप का ऑपरेटिंग सिस्टम (OS) एक अच्छा उदाहरण है। यह आपके कंप्यूटर के काम करने के तरीके के सभी विवरणों को छुपा देता है। आपको सीपीयू, मेमोरी के बारे में और प्रोग्राम को कैसे संभाला जाता है, इसके बारे में कुछ भी जानने की जरूरत नहीं है, आप सिर्फ OS को संचालित करते हैं और OS विवरणों के साथ काम करता है। ये सभी विवरण OS "पर्दे" या ऐब्स्ट्रैक्शन के पीछे छिपे हुए हैं।
```

2022-01-25 04:20 UTC, anubha-v-ardhan commented on content/hi/abstraction.md
> +सिस्टम में आमतौर पर ऐब्स्ट्रैक्शन कि गुणक परतें होती हैं। इसे डेवलपमेंट करना काफी सरल हो जाता है। प्रोग्रामिंग करते समय, डेवलपर्स एक विशेष ऐब्स्ट्रैक्शन परत के साथ संगत घटकों का निर्माण करते हैं और स
```suggestion
सिस्टम में आमतौर पर ऐब्स्ट्रैक्शन कि कई परतें होती हैं। इससे डेवलपमेंट काफी सरल हो जाता है। प्रोग्रामिंग करते समय, डेवलपर्स एक विशेष ऐब्स्ट्रैक्शन परत के साथ संगत घटकों का निर्माण करते हैं और सभी अंतर्निहित बारीकियों के बारे में चिंता करने की ज़रूरत नहीं होती है जो बहुत विजातीय हो सकते हैं। यदि वह ऐब्स्ट्रैक्शन परत के साथ काम करता है, तो वह सिस्टम के साथ भी काम करता है।
```

2022-01-25 13:13 UTC, Shubh28698 commented on content/hi/abstraction.md
> +सिस्टम में आमतौर पर ऐब्स्ट्रैक्शन कि गुणक परतें होती हैं। इसे डेवलपमेंट करना काफी सरल हो जाता है। प्रोग्रामिंग करते समय, डेवलपर्स एक विशेष ऐब्स्ट्रैक्शन परत के साथ संगत घटकों का निर्माण करते हैं और स
Thanks a lot @anubha-v-ardhan

2022-01-25 17:52 UTC, sayantani11 commented
LGTM!

2022-01-31 22:10 UTC, Garima-Negi reviewed
LGTM!

2022-01-31 22:14 UTC, Garima-Negi approved these changes

2022-02-02 14:43 UTC, anubha-v-ardhan approved these changes
Thank you @Shubh28698

2022-02-03 18:13 UTC, merged