Create content/it/style-guide/_index.md
cncf/glossary pull request #375
Opened 2022-02-02 10:45 UTC by annalisag-spark

1. Glossario: ho scelto di tenere la maiuscola per valorizzare il progetto
2. Elenco delle regole per scrivere bene: da migliorare. Sarebbe bello individuare approfondimenti specifici come nella versione inglese originale (no link a pagine di agenzie, blog di privati, ecc)
3. ho lasciato le label  title, status, category, properties in inglese, così come i rispettivi valori, per una omogeneità con la struttura originaria, dato che si riferiscono ad elementi strutturali appunto e non al contenuto
4. [lemma service mesh] (https://glossary.cncf.io/service_mesh/): da sostituire con il termine in italiano quando sarà disponibile 
5. [Come contribuire](https://glossary.cncf.io/contribute/): da sostituire con la l'url della versione italiana quando sarà pubblicata 
6. Ritengo importante scegliere i titoli definitivi dei paragrafi delle definizioni: io ho proposto *Cos'è*, *Quali problematiche risolve* e *In cosa aiuta*, ma aperta a qualunque altro suggerimento.

2022-02-06 18:54 UTC, sistella requested changes
Alcuni suggerimenti, più o meno convinti, alla traduzione. Dei titoli delle sezioni del template possiamo discuterne al prossimo meeting

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Consigliamo di dare un'occhiata a questi [set di regole grammaticali](https://grammatica-italiana.dossier.net/grammatica-italiana-17.htm) e alle [40 regole di scrittura di Umberto Eco per scrivere be
Mi piace questo suggerimento!

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Questa guida ti aiuterà a comprendere la target audience del Glossario, la struttura delle definizioni, il livello di dettaglio richiesto e come mantenere uno stile coerente.
provo a evitare questo inglesismo :)
```suggestion
Questa guida ti aiuterà a comprendere chi sono i destinatari del Glossario, la struttura delle definizioni, il livello di dettaglio richiesto e come mantenere uno stile coerente.
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +## Audience
sulla scorta del commento precedente
```suggestion
## Destinatari
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Il Glossario è scritto sia per un'audience tecnica sia per un'audience NON-tecnica. Per questa ragione assicurati che le definizioni siano espresse in termini semplici e che non diano per scontata un
Di solito i rimandi a porzioni dello stesso documento si rendono con dei link agli elementi in pagina. In questo caso così
```suggestion
Il Glossario è scritto sia per un'audience tecnica sia per un'audience NON-tecnica. Per questa ragione assicurati che le definizioni siano espresse in termini semplici e che non diano per scontata una conoscenza tecnica pregressa. Lo spieghiamo meglio nel paragrafo [*Definizioni*](#template-definizioni).
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +## Quali problematiche risolve
Propongo
```suggestion
## Quali problematiche affronta
```
che ne dici?

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +## In cosa aiuta
credo sia più indicato
```suggestion
## In che modo aiuta
```
`In cosa aiuta` mi pare più siile al titolo precedente

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +All'inizio di una definizione si troverà l'etichetta **title** il cui valore deve essere espresso in title case (ogni elemento costituente il titolo deve iniziare con la maiuscola).
```suggestion
All'inizio di una definizione si troverà l'etichetta **title** il cui valore deve essere espresso in *title case* (ogni elemento costituente il titolo deve iniziare con la maiuscola).
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +- **In cosa aiuta**: in questa parte della definizione, si torna al termine che si sta spiegando e si chiarisce in che modo possa aiutare a risolvere il problema identificato.
```suggestion
- **In che modo aiuta**: in questa parte della definizione, si torna al termine che si sta spiegando e si chiarisce in che modo possa aiutare a risolvere il problema identificato. 
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +- **Quali problematiche risolve**: il focus è sul problema e non sulla soluzione (proposta nel paragrafo appena successivo). Di fatto si cerca di evitare il termine che si sta spiegando e ci si conce
```suggestion
- **Quali problematiche affronta**: il focus è sul problema e non sulla soluzione (proposta nel paragrafo appena successivo). Di fatto si cerca di evitare il termine che si sta spiegando e ci si concentra su *cosa* spinga ad avere bisogno della tecnologia o della pratica in questione. 
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Se vengono menzionati lemmi che sono già disponibili, ricordati di **inserire un link alla definizione presente nel Glossario** (linka il termine la prima volta che viene usato nel testo, non è neces
sono contro il `linka` :)
```suggestion
Se vengono menzionati lemmi che sono già disponibili, ricordati di **inserire un link alla definizione presente nel Glossario** (è sufficiente farlo solo la prima volta che viene usato nel testo).
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +**Esempio**: dà un'occhiata al paragrafo "Cos'è" del [lemma service mesh] (https://glossary.cncf.io/service_mesh/). Se noti, contiene link ai termini microservices, service, reliability e observabili
typo
```suggestion
**Esempio**: dà un'occhiata al paragrafo "Cos'è" del [lemma service mesh] (https://glossary.cncf.io/service_mesh/). Se noti, contiene link ai termini microservices, service, reliability e observability. Inoltre, il confronto tra le criticità della network in un ambiente a microservizi (qualcosa di tecnico con cui è difficile relazionarsi da non tecnici) con le problematiche di una rete wi-fi (un esempio che chiunque usi un portatile può capire) permette una migliore comprensione generale. Quando possibile, cerca di individuare una connessione simile tra i due mondi.
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Ultimo suggerimento di carattere redazionale, prima di buttarti nella scrittura, prova a leggere qualche termine già pubblicato nel Glossario in modo da intuire il livello di dettaglio richiesto e le
```suggestion
Ultimo suggerimento di carattere redazionale, prima di buttarti nella scrittura: prova a leggere qualche termine già pubblicato nel Glossario in modo da intuire il livello di dettaglio richiesto e le relative difficoltà, nonché l'utilizzo di esempi, come già citato sopra.
```

2022-02-06 18:54 UTC, sistella commented on content/it/style-guide/_index.md
> +Innanzitutto vorremmo far presente che i maintainer di questo progetto sono solo tre e che se ne occupano nel loro tempo libero, per cui a volte saranno più rapidi, altre volte avranno bisogno di più
```suggestion
Innanzitutto vorremmo far presente che i maintainer di questo progetto sono solo tre e che se ne occupano nel loro tempo libero, per cui a volte saranno più rapidi, altre volte avranno bisogno di più tempo per rispondere e revisionare: abbi pazienza. Per qualunque domanda, però, mettiti in contatto con loro o con i gruppi di lavoro sul canale #glossary dello Slack CNCF (per approfondimenti ti rimandiamo alla sezione [Come contribuire](https://glossary.cncf.io/contribute/)).
```

2022-02-07 11:56 UTC, annalisag-spark commented on content/it/style-guide/_index.md
> +Questa guida ti aiuterà a comprendere la target audience del Glossario, la struttura delle definizioni, il livello di dettaglio richiesto e come mantenere uno stile coerente.
vero. per me è assolutamente normale, ma se non lavorassi nel marketing potrebbe essere meno evidente!

2022-02-07 15:01 UTC, sistella approved these changes

2022-02-07 15:01 UTC, sistella commented
looks good!

2022-02-10 21:12 UTC, meryem-ldn reviewed
Ho appena finito la review alla style guide e aggiunto i miei commenti.

2022-02-16 09:58 UTC, annalisag-spark commented on content/it/style-guide/_index.md
> +title: Template Definizioni
mumble in italiano la struttura è inversa: (il) Template (delle / per le) Definizioni

2022-02-16 09:59 UTC, annalisag-spark commented on content/it/style-guide/_index.md
> +Innanzitutto vorremmo far presente che i maintainer di questo progetto sono solo tre e che se ne occupano nel loro tempo libero, per cui a volte saranno più rapidi, altre volte avranno bisogno di più
teoricamente in italiano le parole straniere non dovrebbero avere la s del plurale, ma effettivamente dovrei verificare di aver rispettato questa regola ovunque 😂

2022-02-16 10:01 UTC, annalisag-spark commented on content/it/style-guide/_index.md
> +**Esempio**: dà un'occhiata al paragrafo "Cos'è" del [lemma service mesh] (https://glossary.cncf.io/service_mesh/). Se noti, contiene link ai termini microservices, service, reliability e observabili
eh, anche su questo punto ci sarebbe da discutere: c'è chi utilizza il femminile perché sottintende LA RETE e c'è chi utilizza il maschile. mettiamoci d'accordo noi.

2022-02-20 11:33 UTC, meryem-ldn approved these changes

2022-02-21 14:10 UTC, annalisag-spark commented
Closed PR. New referring PR: https://github.com/cncf/glossary/pull/465

2022-02-21 14:10 UTC, closed without merging