New branch and translation for term/abstraction
cncf/glossary pull request #390
Opened 2022-02-05 16:40 UTC by meryem-ldn

2022-02-10 07:31 UTC, annalisag-spark requested changes

2022-02-10 07:31 UTC, annalisag-spark commented on content/it/abstraction.md
> +Nel campo dell'informatica, un'astrazione è una rappresentazione che nasconde le specifiche a un consumatore di servizi, rendendo un sistema più generico e quindi facilmente comprensibile. Un buon es
Un buon esempio è il sistema operativo (OS - Operating System) di un laptop, **dove** astrae tutti i dettagli di come funziona un computer. 

suggerisco

Un buon esempio è il sistema operativo (_OS, Operating System_) di un PC, che astrae tutti i dettagli sul funzionamento di un computer.

Non è necessario sapere nulla sulla CPU > doppia negazione

suggerisco

Non è necessario sapere alcunché sulla CPU

2022-02-17 08:05 UTC, sistella requested changes

2022-02-17 08:05 UTC, sistella commented on content/it/abstraction.md
> +Nel campo dell'informatica, un'astrazione è una rappresentazione che nasconde le specifiche a un consumatore di servizi, rendendo un sistema più generico e quindi facilmente comprensibile. Un buon es
Insieme alle modifiche proposte da @annalisag-spark, ho aggiunto una recente modifica del termine nel main branch [commit 027e759](https://github.com/sistella/glossary/commit/027e759cae294a898e1ae3d8e5e1f9337ebd0551)
```suggestion
Nel campo dell'informatica, un'astrazione è una rappresentazione che nasconde le specifiche a un consumatore di [servizi](/service/) (sia esso un programma o un utente), rendendo un sistema più generico e quindi facilmente comprensibile. Un buon esempio è il sistema operativo (OS - Operating System) di un laptop, che astrae tutti i dettagli di come funziona un computer. Non è necessario sapere alcunché sulla CPU, sulla memoria e su come vengono gestiti i programmi. È sufficiente azionare il sistema operativo che, a sua volta, si occuperà dei dettagli. Tutte queste specifiche sono nascoste dietro l'astrazione del sistema operativo.
```

2022-02-17 08:05 UTC, sistella commented on content/it/abstraction.md
> +I sistemi in genere hanno più livelli di astrazione, semplificando notevolmente lo sviluppo. Durante la programmazione, gli sviluppatori creano componenti compatibili con un particolare livello di as
```suggestion
I sistemi in genere hanno più livelli di astrazione, semplificando notevolmente lo sviluppo. Durante la programmazione, gli sviluppatori creano componenti compatibili con un particolare livello di astrazione e non devono preoccuparsi di tutte le specifiche sottostanti che possono essere molto eterogenee. Se funziona con il livello di astrazione, funzionerà anche con il sistema, indipendentemente da quello che si trova nel livello sottostante. 
```

2022-03-07 08:07 UTC, sistella approved these changes

2022-03-14 06:56 UTC, annalisag-spark approved these changes

2022-03-14 13:52 UTC, merged