New branch and translation for term/service
cncf/glossary pull request #391
Opened 2022-02-05 17:21 UTC by meryem-ldn

2022-03-07 08:09 UTC, sistella requested changes

2022-03-07 08:09 UTC, sistella commented on content/it/service.md
> +category: Concept
```suggestion
category: Concetto
```

2022-03-07 08:09 UTC, sistella commented on content/it/service.md
> +Bisogna notare che nel campo dell’informatica, l’uso della parola “servizio” può avere molteplici significati. In questa sezione, ci concentreremo sulla definizione tradizionale: il servizio come un
possiamo mettere il link alla pagina italiana, che fa parte del v1
```suggestion
Bisogna notare che nel campo dell’informatica, l’uso della parola “servizio” può avere molteplici significati. In questa sezione, ci concentreremo sulla definizione tradizionale: il servizio come un microservizio. Ci sono delle sfumature se i servizi differiscono dai microservizi, e persone diverse possono avere opinioni diverse a riguardo. Per una definizione ad alto livello, li tratteremo allo stesso modo. Si prega di fare riferimento alla definizione dei [microservizi](/it/microservices/).
```

2022-03-14 07:00 UTC, annalisag-spark approved these changes
Per me ok!

2022-03-17 08:40 UTC, annalisag-spark requested changes
Mia proposta, girando le frasi e aggiungendo mezza spiegazione (leggendola direttamente in italiano non mi quadrava il significato complessivo, per quanto la traduzione fosse rispettosa dell'originale).

2022-03-17 08:40 UTC, annalisag-spark commented on content/it/service.md
> +Bisogna notare che nel campo dell’informatica, l’uso della parola “servizio” può avere molteplici significati. In questa sezione, ci concentreremo sulla definizione tradizionale: il servizio come un
```suggestion
Bisogna notare che nel campo dell’informatica, l’uso della parola “servizio” può avere molteplici significati. In questa sezione, ci concentreremo sulla definizione tradizionale: il servizio come un microservizio. Se i servizi differiscono dai microservizi, possono registrarsi delle sfumature di significato e persone diverse possono avere opinioni diverse a riguardo. Abbiamo deciso che per proporre una spiegazione ad alto livello, li accumuneremo in un'unica definizione. Si prega di fare riferimento alla definizione dei [microservizi](/it/microservices/).
```

2022-04-12 14:55 UTC, sistella approved these changes

2022-05-19 04:44 UTC, annalisag-spark approved these changes

2022-05-19 04:44 UTC, annalisag-spark commented
@sistella ups, vero! grazie :) 
fatto!

2022-07-14 19:30 UTC, fsbaraglia approved these changes
LGTM

2022-07-14 19:32 UTC, merged