Add content/pt-br/blue_green_deployment.md
cncf/glossary pull request #436
Opened 2022-02-14 10:38 UTC by jessicalins

Reopening - same content as https://github.com/cncf/glossary/pull/274, but now with an organized tree/commits. Sorry for the confusion :sweat_smile: 

Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>

2022-02-14 10:40 UTC, jessicalins commented
cc @brunoguidone

2022-02-18 10:08 UTC, edsoncelio requested changes
Hi @jessicalins, i just left a small comment :)

2022-02-18 10:08 UTC, edsoncelio commented on content/pt-br/blue_green_deployment.md
> +category: Conceito
Conceito to conceito

2022-03-04 17:17 UTC, brunoguidone approved these changes
Review ok!

2022-03-04 17:18 UTC, merged