Add content/pt-br/application_programming_interface.md
cncf/glossary pull request #437
Opened 2022-02-14 10:44 UTC by jessicalins

Reopening - same content as https://github.com/cncf/glossary/pull/273, but now with an organized tree/commits. Sorry for the confusion :sweat_smile: 

Signed-off-by: Jéssica Lins <jessicaalins@gmail.com>

2022-02-14 10:44 UTC, jessicalins commented
cc @brunoguidone

2022-02-18 10:09 UTC, edsoncelio requested changes
Hi @jessicalins I just left some comments :)

2022-02-18 10:09 UTC, edsoncelio commented on content/pt-br/application_programming_interface.md
> +title: Interface de programação de aplicações
Interface de programação de aplicações to Interface de Programação de Aplicações

2022-02-18 10:09 UTC, edsoncelio commented on content/pt-br/application_programming_interface.md
> +category: Tecnologia
Tecnologia to tecnologia

2022-02-22 07:57 UTC, jessicalins commented on content/pt-br/application_programming_interface.md
> +title: Interface de Programação de aplicações
```suggestion
title: Interface de Programação de Aplicações
```

2022-02-22 10:00 UTC, edsoncelio approved these changes
LGTM

2022-02-22 12:17 UTC, brunoguidone approved these changes
Review ok

2022-02-22 12:51 UTC, edsoncelio commented
@seokho-son could you help us with this? We need just one approval from a codeowner :D

2022-03-03 23:07 UTC, merged