[bn] Localize abstraction.md
cncf/glossary pull request #453
Opened 2022-02-18 19:21 UTC by Mahrjose

Signed-off-by: Mirza Mahrab Hossain [mirzamahrabhossain@gmail.com](mailto:mirzamahrabhossain@gmail.com)
Localizes `content/bn/abstraction.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

2022-02-18 20:20 UTC, mitul3737 requested changes
Can you add a service link as it was here under the en branch? https://github.com/cncf/glossary/blob/main/content/en/abstraction.md

2022-02-18 21:05 UTC, Mahrjose commented
Added the link. Please check again now @mitul3737

2022-02-19 08:58 UTC, Mouly22 approved these changes
Looking good. Keep up the good work.

2022-02-19 19:32 UTC, mitul3737 approved these changes

2022-02-19 19:32 UTC, merged