traduzione del termine VM
cncf/glossary pull request #459
Opened 2022-02-20 12:41 UTC by meryem-ldn

2022-02-21 02:48 UTC, seokho-son commented
@meryem-ldn Please use (change) the title in English to help only relevant reviewers care PRs and issues.

2022-03-07 08:16 UTC, sistella requested changes

2022-03-07 08:16 UTC, sistella commented on content/it/virtual-machine.md
> +category: Technology
```suggestion
category: Tecnologia
```

2022-03-07 08:16 UTC, sistella commented on content/it/virtual-machine.md
> +Una macchina virtuale (VM) è un computer e il suo sistema operativo che non è legato a un particolare componente hardware. Le macchine virtuali si basano sulla [virtualizzazione] (/virtualization/) p
```suggestion
Una macchina virtuale (VM) è un computer e il suo sistema operativo che non è legato a un particolare componente hardware. Le macchine virtuali si basano sulla [virtualizzazione](/virtualization/) per suddividere un singolo computer fisico in più computer virtuali. Questa separazione consente alle organizzazioni e ai fornitori di infrastrutture di creare e distruggere VM senza influire sull'hardware sottostante.
```

2022-03-07 08:16 UTC, sistella commented on content/it/virtual-machine.md
> +Le macchine virtuali sfruttano la virtualizzazione. Quando una macchina di metallo [bare metal] (/bare_metal_machine/) è vincolata a un singolo sistema operativo (OS), il modo in cui le risorse della
mi pare abbiamo deciso in qualche altra PR di utilizzare il termine bare metal, senza traduzioni
```suggestion
Le macchine virtuali sfruttano la virtualizzazione. Quando una macchina [bare metal](/bare_metal_machine/) è vincolata a un singolo sistema operativo (OS), il modo in cui le risorse della macchina possono essere utilizzate è alquanto limitato. Inoltre, quando un sistema operativo è legato a una singola macchina fisica, la sua disponibilità è direttamente legata a quell'hardware. Se la macchina fisica è offline a causa di manutenzione o guasti hardware, lo è anche il sistema operativo.
```

2022-03-07 08:16 UTC, sistella commented on content/it/virtual-machine.md
> +Rimuovendo la relazione diretta tra un sistema operativo e una singola macchina fisica, si risolvono diversi problemi delle macchine bare metal: tempo di approvigionamento (provisioning), utilizzo de
```suggestion
Rimuovendo la relazione diretta tra un sistema operativo e una singola macchina fisica, si risolvono diversi problemi delle macchine bare metal: tempo di provisioning (approvvigionamento), utilizzo dell'hardware e resilienza.
```

2022-03-07 08:16 UTC, sistella commented on content/it/virtual-machine.md
> +I tempi di provisioning per un nuovo computer vengono notevolmente migliorati, senza l'acquisto, l'installazione o la configurazione di nuovo hardware per supportarlo. Le macchine virtuali consentono
```suggestion
I tempi di provisioning per un nuovo computer vengono notevolmente migliorati, senza l'acquisto, l'installazione o la configurazione di nuovo hardware per supportarlo. Le macchine virtuali consentono di utilizzare meglio le risorse hardware fisiche esistenti, creando più macchine virtuali su una singola macchina fisica. Non vincolate a una macchina fisica particolare, le macchine virtuali sono anche più resilienti delle macchine fisiche. Quando una macchina fisica deve essere spenta, le macchine virtuali in esecuzione su di essa possono essere spostate su un'altra macchina con tempi di inattività minimi o nulli.
```

2022-03-14 13:52 UTC, annalisag-spark approved these changes

2022-03-20 15:46 UTC, sistella requested changes

2022-03-20 15:46 UTC, sistella commented on content/it/virtual-machine.md
> +category: Technologia
```suggestion
category: Tecnologia
```

2022-04-10 19:08 UTC, fsbaraglia approved these changes
per me e' ok

2022-04-12 14:55 UTC, sistella approved these changes

2022-04-12 16:13 UTC, merged