Add content/pt-br/container.md
cncf/glossary pull request #485
Opened 2022-02-26 00:43 UTC by edsoncelio

Add container definition localization to ptbr.

2022-03-13 18:12 UTC, jessicalins requested changes
just a small suggestion, otherwise LGTM!

2022-03-13 18:12 UTC, jessicalins commented on content/pt-br/container.md
> +Antes da existência dos contêineres, eram necessárias máquinas separadas eram para executar os aplicativos. Cada máquina exigiria seu próprio sistema operacional, que consome CPU, memória e espaço em
I think here we could specify `TOIL` instead of `trabalho` (since TOIL means repetitive work) or use instead `trabalho repetitivo`

2022-03-14 09:28 UTC, jessicalins approved these changes
awesome :tada:

2022-03-25 13:08 UTC, brunoguidone approved these changes
Great Job !

2022-03-25 13:15 UTC, merged