[hi] Localize content/hi/bare_metal_machine.md
cncf/glossary pull request #490
Opened 2022-02-27 17:51 UTC by anubhav06

This PR localizes the file `content/hi/bare_metal_machine.md` in Hindi

Ref: #270 

@anubha-v-ardhan @ @Garima-Negi Pls review

2022-03-20 18:22 UTC, jayesh-srivastava commented on content/hi/bare_metal_machine.md
> +title: बेयर धातु मशीन
मेटल should be here as well.

2022-03-20 18:22 UTC, jayesh-srivastava commented on content/hi/bare_metal_machine.md
> +बेयर मेटल एक भौतिक कंप्यूटर को संदर्भित करता है, विशेष रूप से एक सर्वर, जिसमें एक, और केवल एक, ऑपरेटिंग सिस्टम होता है। आधुनिक कंप्यूटिंग में अंतर महत्वपूर्ण है क्योंकि कई सर्वर [वर्चुअल मशीन](/virtu
- क्योंकि कई सर्वर, [वर्चुअल मशीन](/virtual_machine/) होते हैं।

2022-03-20 18:22 UTC, jayesh-srivastava commented on content/hi/bare_metal_machine.md
> +बेयर मेटल एक भौतिक कंप्यूटर को संदर्भित करता है, विशेष रूप से एक सर्वर, जिसमें एक, और केवल एक, ऑपरेटिंग सिस्टम होता है। आधुनिक कंप्यूटिंग में अंतर महत्वपूर्ण है क्योंकि कई सर्वर [वर्चुअल मशीन](/virtu
- क्योंकि कई सर्वर, [वर्चुअल मशीन](/virtual_machine/) होते हैं।

2022-03-20 18:22 UTC, jayesh-srivastava requested changes

2022-03-20 18:22 UTC, jayesh-srivastava commented on content/hi/bare_metal_machine.md
> +title: बेयर धातु मशीन
मेटल should be here as well.

2022-03-30 13:29 UTC, anubhav06 commented
Hey. Sorry for the delay in completing the requested changes. I have my exams going on right now. Will get back to this in about 15 days.

2022-04-22 05:23 UTC, anubha-v-ardhan commented
> Hey. Sorry for the delay in completing the requested changes. I have my exams going on right now. Will get back to this in about 15 days.

@anubhav06 Do we have any update?

2022-04-26 22:50 UTC, anubha-v-ardhan requested changes

2022-04-26 22:50 UTC, anubha-v-ardhan commented on content/hi/bare_metal_machine.md
> +title: बेयर मेटल मशीन
```suggestion
title: बेयर मेटल मशीन (Bare Metal Machine)
```

2022-05-20 23:34 UTC, Garima-Negi approved these changes

2022-05-21 17:22 UTC, jayesh-srivastava approved these changes
lgtm

2022-05-22 16:04 UTC, anubha-v-ardhan approved these changes
Thank you @anubhav06 
LGTM!

2022-05-22 16:04 UTC, merged