Localizzazione Site Reliability Engineering
cncf/glossary pull request #585
Opened 2022-03-10 08:28 UTC by annalisag-spark

Please review.

2022-03-10 11:42 UTC, sistella requested changes

2022-03-10 11:42 UTC, sistella commented on content/it/site_reliability_engineering.md
> +Site Reliability Engineering o SRE è una disciplina che combina operations e ingegneria del software. Quest'ultima viene applicata specificamente a problemi infrastrutturali e operativi. In altre par
```suggestion
Site Reliability Engineering o SRE è una disciplina che combina operations e ingegneria del software. Quest'ultima viene applicata specificamente a problemi infrastrutturali e operativi. In altre parole, invece di creare funzionalità di prodotto, i SRE realizzano i sistemi su cui le applicazioni sono in esecuzione. Esistono somiglianze con DevOps, ma mentre DevOps si concentra sul portare il codice in produzione, SRE garantisce che il codice in produzione funzioni correttamente.
```
l'ultima frase non c'è nella versione inglese

2022-03-10 11:42 UTC, sistella commented on content/it/site_reliability_engineering.md
> +Per garantire che le applicazioni funzionino in modo affidabile, sono necessarie molteplici funzionalità, dal monitoraggio delle prestazioni, agli allarmi, al debug di errori e problemi. Senza questi
```suggestion
Per garantire che le applicazioni funzionino in modo affidabile, sono necessarie molteplici funzionalità, dal monitoraggio delle prestazioni, agli allarmi, al debug di errori e problemi. Senza questi elementi, gli sviluppatori possono solo reagire ai problemi anziché lavorare in modo proattivo per evitarli: il verificarsi di interruzioni di servizio sarà solo questione di tempo.
```

2022-03-10 11:42 UTC, sistella commented on content/it/site_reliability_engineering.md
> +Un approccio SRE riduce al minimo i costi, i tempi e gli sforzi del processo di sviluppo del software migliorando in modo continuo l’infrastruttura. Il sistema misura e monitora continuamente l'infra
```suggestion
Un approccio SRE riduce al minimo i costi, i tempi e gli sforzi del processo di sviluppo del software migliorando in modo continuo l’infrastruttura. Il sistema misura e monitora continuamente l'infrastruttura e i componenti dell'applicazione. Quando qualcosa va storto, il sistema indica ai SRE quando, dove e come risolvere il problema. Questo approccio aiuta a creare sistemi software altamente scalabili e affidabili, automatizzando le attività operative.
```

2022-03-10 13:44 UTC, sistella approved these changes

2022-03-13 21:01 UTC, meryem-ldn approved these changes

2022-03-14 06:57 UTC, merged