Create reliability.md
cncf/glossary pull request #586
Opened 2022-03-10 09:04 UTC by annalisag-spark

Please review.

2022-03-10 14:22 UTC, sistella requested changes

2022-03-10 14:22 UTC, sistella commented on content/it/reliability.md
> +Da una prospettiva cloud native, la reliability (affidabilità) si riferisce a quanto positivamente un sistema risponde a problemi. Per semplificare al massimo, se un sistema distribuito continua a fu
solo una sfumatura :)
```suggestion
Da una prospettiva cloud native, la reliability (affidabilità) si riferisce a quanto positivamente un sistema reagisce a problemi. Per semplificare al massimo, se un sistema distribuito continua a funzionare nonostante eventuali modifiche all'infrastruttura e al malfunzionamento di alcuni componenti, questo viene definito affidabile. Al contrario, se smette di funzionare correttamente e gli operatori devono intervenire manualmente per mantenerlo in funzione, il sistema è definito inaffidabile. L'obiettivo delle applicazioni cloud native è costruire sistemi intrinsecamente affidabili.
```

2022-03-11 09:30 UTC, sistella approved these changes

2022-03-14 22:01 UTC, meryem-ldn approved these changes

2022-04-04 12:40 UTC, merged