Term/blue green deployment
cncf/glossary pull request #615
Opened 2022-03-14 23:15 UTC by meryem-ldn

2022-03-20 16:19 UTC, sistella requested changes

2022-03-20 16:19 UTC, sistella commented on content/it/blue-green-deployment.md
> +Il _deployment blue-green_ (l'implementazione blu-verde) è una strategia per aggiornare i sistemi di un computer in esecuzione con tempi di inattività minimi. L'operatore mantiene due ambienti, sopra
```suggestion
Il _deployment blue-green_ (l'implementazione blu-verde) è una strategia per aggiornare i sistemi di un computer in esecuzione con tempi di inattività minimi. L'operatore mantiene due ambienti, soprannominati "blu" e "verde". Uno serve il traffico di produzione (la versione attualmente utilizzata da tutti gli utenti), mentre l'altro è aggiornato. Una volta conclusi i test sull'ambiente non attivo (verde), il traffico di produzione viene commutato (spesso tramite l'uso di un _load balancer_ - bilanciatore di traffico). Si noti che la distribuzione blu-verde di solito implica il cambio per intero degli ambienti, inclusi molti servizi, tutto in una volta. In modo confuso, a volte il termine viene utilizzato in relazione a singoli servizi all'interno di un sistema. Per evitare questa ambiguità, quando ci si riferisce ai singoli componenti si preferisce il termine "rilascio senza inattività".
```

2022-03-20 16:19 UTC, sistella commented on content/it/blue-green-deployment.md
> +Le implementazioni blu-verde consentono tempi di inattività minimi durante l'aggiornamento del software che deve essere modificato a pari passo, a causa della mancanza di compatibilità con le version
```suggestion
Le implementazioni blu-verde consentono tempi di inattività minimi durante l'aggiornamento del software che deve essere modificato di pari passo, a causa della mancanza di compatibilità con le versioni precedenti. Ad esempio, l'implementazione blu-verde sarebbe appropriata per un negozio online composto da un sito web e un database che deve essere aggiornato, ma la nuova versione del database non funziona con la vecchia versione del sito web e viceversa. In questo caso, entrambi devono essere modificati contemporaneamente. Se ciò avvenisse sul sistema di produzione, i clienti noterebbero tempi di inattività.
```

2022-03-28 12:50 UTC, annalisag-spark approved these changes

2022-07-04 19:09 UTC, merged