Term/canary deployment
cncf/glossary pull request #616
Opened 2022-03-14 23:30 UTC by meryem-ldn

2022-05-23 16:02 UTC, sistella requested changes
Bello! Solo qualche nota

2022-05-24 05:44 UTC, annalisag-spark commented on content/it/canary-deployment.md
> +Le implementazioni Canary consentono alle organizzazioni di vedere come si comporta il nuovo software in scenari reali prima di trasferire traffico significativo alla nuova versione. Questa strategia
"prima di trasferire traffico significativo alla nuova versione"
lascerei la proposta di Meryem perché è un concetto presente nell'originale, come a dire: "prima ne sposti una parte per testare, poi ne aumenti le dimensioni".

2022-05-24 05:45 UTC, annalisag-spark commented
Sono d'accordo con i suggerimenti di @sistella.

2022-05-24 05:45 UTC, annalisag-spark approved these changes

2022-05-24 08:06 UTC, sistella commented on content/it/canary-deployment.md
> +Le implementazioni Canary consentono alle organizzazioni di vedere come si comporta il nuovo software in scenari reali prima di trasferire traffico significativo alla nuova versione. Questa strategia
ripensandoci è vero... ok, aggiusto il suggerimento.

2022-07-04 19:17 UTC, fsbaraglia approved these changes

2022-07-14 19:51 UTC, fsbaraglia requested changes

2022-07-14 19:51 UTC, fsbaraglia commented on content/it/canary-deployment.md
> +## Quale problema affronta
```suggestion
## Quali problematiche affronta
```

2022-07-14 19:52 UTC, fsbaraglia approved these changes

2022-07-14 19:53 UTC, merged