Term/containers
cncf/glossary pull request #618
Opened 2022-03-14 23:57 UTC by meryem-ldn

2022-05-23 16:35 UTC, sistella requested changes
Qualche commento. Questa non era facile eh :D

2022-05-23 16:35 UTC, sistella commented on content/it/containers.md
> +Un container è un processo in esecuzione con vincoli di risorse e capacità gestiti dal sistema operativo di un computer. I file disponibili per il processo del contenitore vengono compressi come un'i
Io lascerei ovunque container. 
```suggestion
Un container è un processo in esecuzione con vincoli di risorse e capacità gestiti dal sistema operativo di un computer. I file disponibili per il processo del container vengono compressi in una "immagine" del container. I container vengono eseguiti in spazi di memoria adiacenti sulla stessa macchina, ma in genere il sistema operativo impedisce ai processi container separati di interagire tra loro.
```

2022-05-23 16:35 UTC, sistella commented on content/it/containers.md
> +Prima che i container fossero disponibili, erano necessarie macchine separate per eseguire le applicazioni. Ogni macchina richiedeva il proprio sistema operativo, che occupava CPU, memoria e spazio s
```suggestion
Prima che i container fossero disponibili, erano necessarie macchine separate per eseguire le applicazioni. Ogni macchina richiedeva il proprio sistema operativo, che occupava CPU, memoria e spazio su disco, il tutto per il funzionamento di una singola applicazione. Inoltre, la manutenzione, l'aggiornamento e l'avvio di un sistema operativo sono un'altra significativa fonte di lavoro.
```

2022-05-23 16:35 UTC, sistella commented on content/it/containers.md
> +Tuttavia, ci sono dei limiti. Poiché i container condividono lo stesso sistema operativo, i processi possono essere considerati meno sicuri delle alternative. I contenitori richiedono anche limiti al
che ne dici?

```suggestion
Tuttavia, ci sono dei limiti. Poiché i container condividono lo stesso sistema operativo, i processi possono essere considerati meno sicuri delle alternative. I container richiedono anche limiti alle risorse condivise. Per garantire la disponibilità di risorse, gli amministratori devono vincolare e limitare l'utilizzo della memoria e della CPU in ciascun container, in modo che le altre applicazioni non siano rallentate.
```

2022-05-24 06:14 UTC, annalisag-spark commented on content/it/containers.md
> +Tuttavia, ci sono dei limiti. Poiché i container condividono lo stesso sistema operativo, i processi possono essere considerati meno sicuri delle alternative. I contenitori richiedono anche limiti al
`I container richiedono anche limiti alle risorse condivise`
suggerirei "limitazioni alle risorse condivise"

2022-05-24 06:17 UTC, sistella commented on content/it/containers.md
> +Tuttavia, ci sono dei limiti. Poiché i container condividono lo stesso sistema operativo, i processi possono essere considerati meno sicuri delle alternative. I contenitori richiedono anche limiti al
Bello! L'ho integrato nel mio suggerimento così @meryem-ldn fa solo update se le piace tutto!

2022-05-24 06:23 UTC, annalisag-spark commented on content/it/containers.md
> +Tuttavia, ci sono dei limiti. Poiché i container condividono lo stesso sistema operativo, i processi possono essere considerati meno sicuri delle alternative. I contenitori richiedono anche limiti al
@sistella hai fatto bene, non volevo sovrapporre o pasticciare a causa dei miei di limiti 😂

2022-07-15 08:49 UTC, annalisag-spark approved these changes

2022-07-20 19:43 UTC, fsbaraglia requested changes

2022-07-20 19:43 UTC, fsbaraglia commented on content/it/containers.md
> +## Quale problema affronta
```suggestion
## Quali problematiche affronta
```

2022-07-20 19:44 UTC, fsbaraglia approved these changes

2022-07-23 08:40 UTC, sistella approved these changes

2022-07-25 13:55 UTC, merged