Term/dbaas
cncf/glossary pull request #624
Opened 2022-03-15 01:19 UTC by meryem-ldn

2022-04-15 09:45 UTC, fsbaraglia requested changes

2022-04-15 09:45 UTC, fsbaraglia commented on content/it/DBaaS.md
> +Database-as-a-Service (DBaaS) è ​​un servizio gestito da un operatore cloud (pubblico o privato) che supporta le applicazioni senza richiedere al team della app di eseguire le tradizionali funzioni d
good for me

2022-04-15 09:45 UTC, fsbaraglia commented on content/it/DBaaS.md
> +Tradizionalmente, nelle configurazioni on-premise, le organizzazioni devono investire regolarmente in capacità di archiviazione e elaborazione aggiuntive per accogliere l'espansione del database che
cambierei giusto un paio di cose

- [ ] ... nelle installazioni on-premise 
- [ ] ... le organizzazioni devono regolarmente investire in ulteriore capacità di archiviazione ed elaborazione per consentire l'espansione del database, il che può risultare costoso
- [ ] ... gli sviluppatori effettuano il provisioning e configurano i database con l'aiuto dei team responsabili dell'infrastruttura IT e ciò rallenta la velocità di implementazione delle ...

2022-04-15 09:45 UTC, fsbaraglia commented on content/it/DBaaS.md
> +DBaaS consente agli sviluppatori di delegare tutte le operazioni amministrative al cloud service provider. Il provider di servizi garantisce il corretto funzionamento del database, inclusa la gestion
- [ ] ... monitoraggio del servizio ed altro ...
- [ ] ... DBaaS aiuta le organizzazioni a sviluppare le applicazioni aziendali più velocemente, minimizzando oltretutto i costi del database.

2022-07-15 19:41 UTC, fsbaraglia requested changes

2022-07-15 19:41 UTC, fsbaraglia commented on content/it/DBaaS.md
> +## Quale problema affronta
```suggestion
## Quali problematiche affronta
```

2022-07-15 19:41 UTC, fsbaraglia commented
@sistella @annalisag-spark  for review

2022-07-18 12:59 UTC, annalisag-spark requested changes

2022-07-18 12:59 UTC, annalisag-spark commented on content/it/DBaaS.md
> +DBaaS consente agli sviluppatori di delegare tutte le operazioni amministrative al cloud service provider. Il provider di servizi garantisce il corretto funzionamento del database, inclusa la gestion
```suggestion
DBaaS consente agli sviluppatori di delegare tutte le operazioni amministrative al cloud service provider. Il provider di servizi garantisce il corretto funzionamento del database, inclusa la gestione della configurazione, backup, patch, aggiornamenti, monitoraggio del servizio e altro, con un'interfaccia di gestione intuitiva. DBaaS aiuta le organizzazioni a sviluppare applicazioni enterprise più velocemente, riducendo al minimo i costi del database.
```

2022-07-26 07:37 UTC, annalisag-spark approved these changes

2022-10-29 19:38 UTC, fsbaraglia commented
cleanup , close and create another pull with only the term

2022-10-29 19:38 UTC, closed without merging