Term/virtualization
cncf/glossary pull request #625
Opened 2022-03-15 01:29 UTC by meryem-ldn

2022-05-25 15:52 UTC, annalisag-spark requested changes

2022-05-25 15:52 UTC, annalisag-spark commented on content/it/virtualization.md
> +La virtualizzazione, nel contesto del cloud native computing, si riferisce al processo di prendere un computer fisico, a volte chiamato server, e consentirgli di eseguire più sistemi operativi isolat
```suggestion
La virtualizzazione, nel contesto del Cloud Native Computing, si riferisce al processo per il quale si consente ad un computer fisico, a volte chiamato server, di eseguire più sistemi operativi isolati. Questi sistemi operativi isolati e le relative risorse di calcolo dedicate (CPU, memoria e rete) sono indicati come macchine virtuali o VMs. Quando parliamo di una macchina virtuale, parliamo di un computer definito dal software. Qualcosa che sembra e si comporta come un vero computer ma condivide hardware con altre macchine virtuali. Ad esempio, puoi noleggiare un "computer" da AWS: quel computer è in realtà una VM.
```

2022-07-04 19:07 UTC, fsbaraglia approved these changes
super, grazie per il tuo lavoro

2022-07-18 12:56 UTC, annalisag-spark approved these changes

2022-10-29 19:39 UTC, closed without merging

2022-10-29 19:40 UTC, fsbaraglia commented
cleanup, close and reopen with only the term