Updated auto_scaling.md
cncf/glossary pull request #659
Opened 2022-03-25 05:12 UTC by ikramulkayes

Signed-off-Ikramul Kayes ikramul.kayesgg@gmail.com
Localizes ```content/bn/auto_scaling.md``` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #410

2022-03-25 12:54 UTC, Mouly22 approved these changes
Nicely done!

2022-03-25 13:05 UTC, mitul3737 requested changes

2022-03-25 13:05 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +অটোস্কেলিং হল একটি সিস্টেমের ক্ষমতা [scale](/scalability/) স্বয়ংক্রিয়ভাবে, সাধারণত, কম্পিউটিং সংস্থানগুলির পরিপ্রেক্ষিতে। একটি অটোস্কেলিং সিস্টেমের সাহায্যে, প্রয়োজনের সময় সংস্থানগুলি স্বয়ংক্রিয
@ikramulkayes Can you kindly check the sentence? It seems inappropriate

2022-03-25 13:05 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +অটোস্কেলিং হল একটি সিস্টেমের ক্ষমতা [scale](/scalability/) স্বয়ংক্রিয়ভাবে, সাধারণত, কম্পিউটিং সংস্থানগুলির পরিপ্রেক্ষিতে। একটি অটোস্কেলিং সিস্টেমের সাহায্যে, প্রয়োজনের সময় সংস্থানগুলি স্বয়ংক্রিয
I also think `মেমোরি` would be a good use

2022-03-25 13:05 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +পূর্বে, সর্বোচ্চ সিস্টেম ব্যবহার বিবেচনা করার জন্য অবকাঠামো এবং অ্যাপ্লিকেশনগুলিকে আর্কিটেক্ট করা হয়েছিল। এই স্থাপত্যের অর্থ হল যে আরও সংস্থানগুলি কম ব্যবহার করা হয়েছে এবং ভোক্তাদের চাহিদা পরিবর্তন
Can you check this sentence too?

2022-05-08 14:43 UTC, mitul3737 commented
@ikramulkayes , kindly use 1 branch to create just 1 file. In this branch, you have `canary_deployment.md` along with the `auto_scaling.md` file . Unless you take an action, we can not approve. I hope you understand.

2022-05-08 14:43 UTC, mitul3737 commented
/hold

2022-05-08 14:51 UTC, ikramulkayes commented
> @ikramulkayes , kindly use 1 branch to create just 1 file. In this branch, you have `canary_deployment.md` along with the `auto_scaling.md` file . Unless you take an action, we can not approve. I hope you understand.

I hope it is okay now.

2022-05-10 03:20 UTC, mitul3737 requested changes

2022-05-10 03:20 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +title: অটোস্কেলিং (Auto Scaling)
Can we have the title as `অটোস্কেলিং(Autoscaling)` ? For reference kindly check this [Glossary Page link](https://glossary.cncf.io/auto_scaling/)

2022-05-10 03:20 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +অটোস্কেলিং হল সাধারণত একটি সিস্টেমের কম্পিউটিং রিসোর্সগুলির পরিপ্রেক্ষিতে স্বয়ংক্রিয়ভাবে  [স্কেল](/স্কেলযোগ্যতা/)  ক্ষমতা। অটোস্কেলিং সিস্টেমের সাহায্যে, ব্যবহারকারী চাহিদা অনুযায়ী রিসোর্স স্কেল কর
I think you have localized the link `[স্কেল](/স্কেলযোগ্যতা/)`

2022-05-10 03:20 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +ক্লাউড, [virtualizing](/virtualization/), and [containerizing](/containerization/) অ্যাপ্লিকেশন এবং তাদের নির্ভরতা ব্যবহার করে, সংস্থাগুলি ব্যবহারকারীর চাহিদা অনুযায়ী অ্যাপ্লিকেশন তৈরি করতে পারে। তা
Can you localize these words `virtualizing`, `containerizing` ?

2022-05-10 03:20 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +ক্লাউড, [virtualizing](/virtualization/), and [containerizing](/containerization/) অ্যাপ্লিকেশন এবং তাদের নির্ভরতা ব্যবহার করে, সংস্থাগুলি ব্যবহারকারীর চাহিদা অনুযায়ী অ্যাপ্লিকেশন তৈরি করতে পারে। তা
I think this sentence can be modified `তারা অ্যাপ্লিকেশন চাহিদা নিরীক্ষণ করতে পারে এবং স্বয়ংক্রিয়ভাবে তাদের স্কেল করতে পারে, একটি সর্বোত্তম ব্যবহারকারীর অভিজ্ঞতা প্রদান করে`

2022-06-29 05:32 UTC, mitul3737 commented
@ikramulkayes  sorry for the late response . Can you please check this updated file https://github.com/cncf/glossary/blob/main/content/en/auto-scaling.md and update your file?

2022-07-25 18:51 UTC, mitul3737 approved these changes
LGTM

2022-07-25 18:51 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +অটোস্কেলিং হল সাধারণত একটি সিস্টেমের কম্পিউটিং রিসোর্সগুলির পরিপ্রেক্ষিতে স্বয়ংক্রিয়ভাবে  [স্কেল](/scalability/) ক্ষমতা। অটোস্কেলিং সিস্টেমের সাহায্যে, ব্যবহারকারী চাহিদা অনুযায়ী রিসোর্স স্কেল করতে
```suggestion
অটোস্কেলিং হল সাধারণত একটি সিস্টেমের কম্পিউটিং রিসোর্সগুলির পরিপ্রেক্ষিতে স্বয়ংক্রিয়ভাবে  [স্কেল](/bn/scalability/) ক্ষমতা। অটোস্কেলিং সিস্টেমের সাহায্যে, ব্যবহারকারী চাহিদা অনুযায়ী রিসোর্স স্কেল করতে এবং প্রয়োজনের সময়  স্বয়ংক্রিয়ভাবে রিসোর্সগুলি যোগ করতে পারে। অটোস্কেলিং প্রক্রিয়া পরিবর্তনশীল এবং মেমোরি বা প্রক্রিয়া সময়ের মতো বিভিন্ন মেট্রিক্সের উপর ভিত্তি করে স্কেল করার জন্য কনফিগারযোগ্য। ক্লাউড পরিষেবাগুলি সাধারণত অটোস্কেলিং এর মাধ্যমে পরিচালিত হয় কারণ বেশিরভাগ অন-প্রিমাইজ ডিপ্লোয়মেন্টের চেয়ে এটিতে আরও বেশি বাস্তবায়ন করার ব্যবস্থা রয়েছে।
```

2022-07-25 18:51 UTC, mitul3737 commented on content/bn/auto_scaling.md
> +ক্লাউড, [ভারচুয়ালাইজিং](/virtualization/), and [কন্টেইনারাইজিং](/containerization/) অ্যাপ্লিকেশন এবং তাদের নির্ভরতা ব্যবহার করে, সংস্থাগুলি ব্যবহারকারীর চাহিদা অনুযায়ী অ্যাপ্লিকেশন তৈরি করতে পারে। এ
```suggestion
ক্লাউড, [ভারচুয়ালাইজিং](/bn/virtualization/), and [কন্টেইনারাইজিং](/bn/containerization/) অ্যাপ্লিকেশন এবং তাদের নির্ভরতা ব্যবহার করে, সংস্থাগুলি ব্যবহারকারীর চাহিদা অনুযায়ী অ্যাপ্লিকেশন তৈরি করতে পারে। এটি অ্যাপ্লিকেশন চাহিদা নিরীক্ষণ করতে পারে এবং স্বয়ংক্রিয়ভাবে এসব অ্যাপ্লিকেশন স্কেল করতে পারে, যার ফলে এট ব্যবহারকারীদের সর্বোত্তম অভিজ্ঞতা প্রদান করে। যেমন প্রতি শুক্রবার সন্ধ্যায় Netflix-এর দর্শক সংখ্যা বৃদ্ধি পায়। স্বয়ংক্রিয়ভাবে আউট করার অর্থ হল গতিশীলভাবে আরও সংস্থান যোগ করা: উদাহরণস্বরূপ, আরও ভিডিও স্ট্রিমিংয়ের অনুমতি দেয় এমন সার্ভারের সংখ্যা বৃদ্ধি করা এবং একবার ব্যবহার স্বাভাবিক হয়ে গেলে আবার স্কেল করা।
```

2022-07-25 18:51 UTC, merged