German translation for agile software dev
cncf/glossary pull request #661
Opened 2022-03-26 07:36 UTC by iamNoah1

2022-03-31 02:04 UTC, jihoon-seo commented
Preview: https://deploy-preview-661--cncfglossary.netlify.app/de/agile_software_development/

Feedback section is displayed like this:
![image](https://user-images.githubusercontent.com/46767780/160961135-553e1ffe-49d2-4c8a-a829-1f9b68886e34.png)

@iamNoah1 Could you add some entries to [`de.toml` of `dev-de` branch](https://github.com/cncf/glossary/blob/dev-de/i18n/de.toml), by opening another PR?

Examples:
- https://github.com/cncf/glossary/blob/540e516abc4950f80463e3997d09355d6a671444/i18n/en.toml#L63-L71
- https://github.com/cncf/glossary/pull/665/files#diff-fd5507f0042e10570f36b7804477e5502fbb6f6a159db8e0a5e86f80c981be06
- https://github.com/cncf/glossary/pull/519/files#diff-bf91abcf6a5d6fc7b18204067500f96305db8352586d24a549a23cd973daa5a5

PTAL! 😊

2022-04-07 07:15 UTC, DaveVentura commented on content/de/agile_software_development.md
> +Das Kommunizieren und Verstehen der Anforderungen eines Softwareprojekts ist ein sehr schweres wenn nicht sogar unmögliches Unterfangen. Dennoch wollen Kunden meist, dass Softwareprojekte in einem fe
Charakter

2022-04-07 07:17 UTC, DaveVentura commented on content/de/agile_software_development.md
> +Das Kommunizieren und Verstehen der Anforderungen eines Softwareprojekts ist ein sehr schweres wenn nicht sogar unmögliches Unterfangen. Dennoch wollen Kunden meist, dass Softwareprojekte in einem fe
ein schweres, wenn nicht sogar..
Komma fehlt :)

2022-04-07 07:20 UTC, DaveVentura commented on content/de/agile_software_development.md
> +Alle Phasen traditioneller (wasserfallartiger) Vorgehensmodelle wie etwa Anforderungsmanagement, Planung, Implementierung, Test und Auslieferung sind in der agilen Softwareentwicklung gleichermaßen v
vorgesehen

2022-04-07 07:24 UTC, DaveVentura commented on content/de/agile_software_development.md
> +Alle Phasen traditioneller (wasserfallartiger) Vorgehensmodelle wie etwa Anforderungsmanagement, Planung, Implementierung, Test und Auslieferung sind in der agilen Softwareentwicklung gleichermaßen v
ich habe online nachgeschaut, scheinbar kommt vor sowie kein Komma, wenn es als "Aufzählungsverknüpfung" dient. Es ersetzt "und" und da wird auch kein Komma gesetzt.

2022-04-07 07:26 UTC, DaveVentura requested changes
Hört sich inhaltlich super an. :) Hab noch kleine typos gefunden aber ansonsten finde ich es sehr gut.

2022-04-09 08:35 UTC, iamNoah1 commented
#718 @jihoon-seo

2022-04-09 08:38 UTC, iamNoah1 commented on content/de/agile_software_development.md
> +Alle Phasen traditioneller (wasserfallartiger) Vorgehensmodelle wie etwa Anforderungsmanagement, Planung, Implementierung, Test und Auslieferung sind in der agilen Softwareentwicklung gleichermaßen v
^^

2022-04-09 08:38 UTC, iamNoah1 commented on content/de/agile_software_development.md
> +Alle Phasen traditioneller (wasserfallartiger) Vorgehensmodelle wie etwa Anforderungsmanagement, Planung, Implementierung, Test und Auslieferung sind in der agilen Softwareentwicklung gleichermaßen v
Kommasetzung ist echt nicht meine Stärke ^^

2022-04-09 08:39 UTC, iamNoah1 commented
> Hört sich inhaltlich super an. :) Hab noch kleine typos gefunden aber ansonsten finde ich es sehr gut.
hab alles angepasst.

2022-04-09 08:42 UTC, DaveVentura approved these changes

2022-04-09 10:03 UTC, Petria3s approved these changes

2022-04-09 10:03 UTC, merged