Add content/pt-br/data_center.md
cncf/glossary pull request #682
Opened 2022-04-02 17:02 UTC by MrErlison

Changes
* add data_center.md

2022-04-19 21:36 UTC, edsoncelio approved these changes
LGTM

2022-04-19 21:39 UTC, edsoncelio requested changes

2022-04-19 21:39 UTC, edsoncelio commented on content/pt-br/data_center.md
> +category: Tecnologia
`Tecnologia` to `tecnologia`

2022-04-19 22:53 UTC, edsoncelio approved these changes

2022-06-16 15:00 UTC, brunoguidone approved these changes
LGTM

2022-06-25 14:44 UTC, merged