Es loadbalancer
cncf/glossary pull request #694
Opened 2022-04-05 15:28 UTC by krol3

Related the issue https://github.com/cncf/glossary/issues/609

2022-04-05 16:01 UTC, electrocucaracha requested changes
@krol3 please add `enruta` into the word list to fix the CI jobs

2022-04-08 17:43 UTC, electrocucaracha requested changes
@krol3 we have re-created the `dev-es` branch in #692 can you verify that these changes are on top of them?

2022-04-08 17:43 UTC, electrocucaracha commented on content/es/load_balancer.md
> +## Qué es
There is a new suggestion for template headers in 2c9bc465434c15210917ab995cf0fdb33016ba58

```suggestion
## ¿Qué es?
```

2022-04-08 17:43 UTC, electrocucaracha commented on content/es/load_balancer.md
> +## Cómo ayuda
There is a new suggestion for template headers in 2c9bc465434c15210917ab995cf0fdb33016ba58

```suggestion
## ¿Cómo ayuda?
```

2022-04-08 17:43 UTC, electrocucaracha commented on content/es/load_balancer.md
> +El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de
```suggestion
El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de usuarios, a menudo será necesario distribuir esa aplicación en varios servidores. El balanceador de carga es el "policía de tráfico" que enruta el tráfico.
```

2022-04-08 17:43 UTC, electrocucaracha commented on content/es/load_balancer.md
> +Un balanceador de carga actuará como frontend para el tráfico de red y los clientes. A menudo tiene varios métodos para verificar qué servidor(es) está activo y tiene la carga más baja para manejar l
```suggestion
Un balanceador de carga actuará como frontend para el tráfico de red y los clientes. A menudo tiene varios métodos para verificar qué servidor(es) está activo y tiene la carga más baja para procesar la solicitud.
```

2022-04-09 16:44 UTC, krol3 commented on content/es/load_balancer.md
> +El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de
@electrocucaracha  relacionado al género de la policia, podría ser (el o la).

2022-04-09 16:53 UTC, raelga commented on content/es/load_balancer.md
> +Un balanceador de carga es un método para distribuir el tráfico de red entrante a través de un grupo de servidores en el backend. La solución puede estar basada en software o hardware.
```suggestion
Un balanceador de carga es un mecanismo para distribuir el tráfico de red entrante entre un grupo de servidores en el backend. La solución puede estar basada en software o hardware.
```

2022-04-09 16:54 UTC, raelga commented on content/es/load_balancer.md
> +El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de
```suggestion
El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de usuarios, a menudo será necesario distribuir esa aplicación en varios servidores. El balanceador de carga es el "policía de tráfico" encargado de distribuir las peticiones entrantes entre los diferentes servidores que ejecutan la aplicación.
```

2022-04-09 16:56 UTC, raelga commented on content/es/load_balancer.md
> +Un balanceador de carga actuará como frontend para el tráfico de red y los clientes. A menudo tiene varios métodos para verificar qué servidor(es) está activo y tiene la carga más baja para procesar
```suggestion
Un balanceador de carga actuará como frontend para el tráfico de red y los clientes. A menudo tiene varios métodos para verificar que servidores están disponibles e, idealmente, balancear las peticiones para cada uno de los servidores tengan una carga de trabajo similiar.
```

2022-04-09 16:57 UTC, raelga approved these changes
Comentarios menores @krol3  :)

2022-04-11 16:55 UTC, electrocucaracha commented on content/es/load_balancer.md
> +El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de
@krol3 tienes razón. Mi criterio es que cuando se refiere al departamento de policía se usa en su forma femenina, para un individuo en específico su forma masculina. Para este caso las siguientes opciones son válidas:

* `Los balanceadores de carga son la "policía de tráfico" que ...`
* `El balanceador de carga es la "policía de tráfico" que...`
* `El balanceador de carga es el "policía de tráfico" que...`

Quizá haga sentido dejarlo en su forma femenina refiriéndose a la función general

2022-04-12 15:50 UTC, krol3 commented on content/es/load_balancer.md
> +Un balanceador de carga actuará como frontend para el tráfico de red y los clientes. A menudo tiene varios métodos para verificar qué servidor(es) está activo y tiene la carga más baja para procesar
Gracias @raelga, solo me gustaría mantener la idea que represente que el balanceador, va a escoger el servidor con carga más baja.

2022-04-12 17:01 UTC, electrocucaracha commented on content/es/load_balancer.md
> +El balanceador ayuda a resolver el problema referente con la alta disponibilidad y los sistemas distribuidos. Cuando se trabaja en una aplicación o servicio que necesita escalar a cientos de miles de
La sugerencia me parece buena, más no sé si desvía o agrega más información de la que originalmente se había considerado. Quizá sea mejor modificar el concepto en inglés y así propagar esta expansión en el término

2022-04-12 17:04 UTC, electrocucaracha approved these changes

2022-04-12 17:08 UTC, raelga approved these changes

2022-04-12 17:09 UTC, merged