add content/es/api_gateway.md
cncf/glossary pull request #698
Opened 2022-04-06 03:26 UTC by gamba47

Please do a review of this concepts:

API Gateway : Concentrador API

I did not see any style guide or glossary about this translation.

Regards.

2022-04-06 23:03 UTC, jihoon-seo commented
Preview should be available at https://deploy-preview-698--cncfglossary.netlify.app/es/api_gateway/ .

And please refer to https://github.com/cncf/glossary/pull/705#issuecomment-1090893838 . 😊

2022-04-07 07:41 UTC, raelga commented on content/es/api_gateway.md
> +## ¿Que es esto?
```suggestion
## ¿Qué es esto?
```

2022-04-07 07:41 UTC, raelga commented on content/es/api_gateway.md
> +Un concentrador [API](/application_programming_interface/) es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organizaciones mov
```suggestion
Un [API Gateway](/application_programming_interface/), API de pasarela, es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organizaciones mover funciones clave, como ser la autenticación y la autorización o limitando el número de peticiones entre aplicaciones, a una ubicación de administración centralizada. Un API Gateway funciona como una interface común para los que la consumen (usualmente aplicaciones externas).
```

No sé si traduciría API Gateway, ya que en casi todos los sitios conservan en nombre en inglés. De todos modos, la traducción que he visto más común es `API de pasarela`, qué te parece? Cambiarías también el título por API de pasarela?

/cc @electrocucaracha  @gamba47

2022-04-07 07:41 UTC, raelga commented on content/es/api_gateway.md
> +Si usted esta haciendo APIs con disponibilidad para consumidores externos, es deseable tener un único punto de entrada para administrar y controlar todo el acceso. Adicionalmente, si usted necesita a
```suggestion
Si está haciendo APIs con disponibilidad para consumidores externos, es deseable tener un único punto de entrada para administrar y controlar todo el acceso. Adicionalmente, si necesita aplicar funcionalidades en estas interacciones, un API Gateway le permitirá aplicar sus funcionalidades, de manera uniforme a todo el tráfico, sin requerir cambios en el código de la aplicación.
```

2022-04-07 07:41 UTC, raelga commented on content/es/api_gateway.md
> +## ¿Como Ayuda?
```suggestion
## ¿Cómo Ayuda?
```

2022-04-07 07:41 UTC, raelga commented on content/es/api_gateway.md
> +Proveyendo un único punto de acceso para varias APIs en una aplicación, los concentradores API hacen simple para la organización, la aplicación de decisiones de negocio transversales o lógicas de seg
```suggestion
Proporcionando un único punto de acceso para varias APIs en una aplicación, los API Gateway hacen simple para la organización, la aplicación de decisiones de negocio transversales o lógicas de seguridad en una ubicación central. Adicionalmente, permiten a los consumidores de la misma ir a una sola dirección para todas sus necesidades. Una API de pasarela puede simplificar preocupaciones operativas, como son la seguridad y la [observabilidad](/observability/) proporcionando un único punto de acceso para las peticiones a todos los servicios web en el sistema. Como todas las peticiones fluyen por la pasarela, esta presenta un único lugar para agregar funcionalidades como la recolección de métricas, límites de tráfico y la autorización.
```

2022-04-07 11:13 UTC, gamba47 reviewed
Suggestions accepted!

2022-04-07 11:18 UTC, gamba47 commented on content/es/api_gateway.md
> +Un concentrador [API](/application_programming_interface/) es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organizaciones mov
A mi tampoco me gusta mucho la traduccion, pero no encontre nada referencial al tema por lo menos en el glosario del issue de github. Recuerdo que hay un drive con muchas más frases o palabras, pero no lo pude encontrar. Puede ser concentrador, ruta, puerta, hay varias opciones.

2022-04-07 11:43 UTC, raelga approved these changes
✨

2022-04-08 15:38 UTC, krol3 commented on content/es/api_gateway.md
> +Un [API Gateway](/application_programming_interface/), API de pasarela, es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organ
"Pasarela API", sigue la referencia https://www.connecting-software.com/es/blog/what-is-an-api-gateway-how-it-can-actually-deliver-practical-results/

2022-04-08 15:57 UTC, krol3 reviewed
Gracias por tu contribución, coloque algunas sugerencias.

2022-04-08 15:57 UTC, krol3 commented on content/es/api_gateway.md
> +Un [API Gateway](/application_programming_interface/), API de pasarela, es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organ
```suggestion
Un [API Gateway](/application_programming_interface/), pasarela API, es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organizaciones mover funciones clave, como puede ser la autenticación y la autorización o limitando el número de peticiones entre aplicaciones a una ubicación de administración centralizada. Un API Gateway funciona como una interface común para los que la consumen (usualmente aplicaciones externas).
```

2022-04-08 15:57 UTC, krol3 commented on content/es/api_gateway.md
> +Si usted esta haciendo APIs con disponibilidad para consumidores externos, es deseable tener un único punto de entrada para administrar y controlar todo el acceso. Adicionalmente, si usted necesita a
```suggestion
Si está haciendo APIs con disponibilidad para consumidores externos, es deseable tener un único punto de entrada para administrar y controlar todo el acceso. Adicionalmente, si necesita aplicar funcionalidad en estas interacciones, un API Gateway le permitirá aplicarla de manera uniforme a todo el tráfico, sin requerir cambios en el código de la aplicación.
```

2022-04-08 15:57 UTC, krol3 commented on content/es/api_gateway.md
> +Proporcionando un único punto de acceso para varias APIs en una aplicación, los API Gateway hacen simple para la organización, la aplicación de decisiones de negocio transversales o lógicas de seguri
```suggestion
Proporcionando un único punto de acceso para varias APIs en una aplicación, los API Gateway hacen simple para la organización aplicar decisiones de negocio transversales o lógicas de seguridad en una ubicación central. Adicionalmente, permiten a los consumidores de aplicaciones ir en una única dirección para todas sus necesidades. Una pasarela API puede simplificar preocupaciones operativas, como son la seguridad y la [observabilidad](/observability/) proporcionando un único punto de acceso para las peticiones a todos los servicios web en el sistema. Como todas las peticiones fluyen por la pasarela, esta presenta un único lugar para agregar funcionalidades como la recolección de métricas, límites de tráfico y la autorización.
```

2022-04-08 16:49 UTC, gamba47 commented
> Gracias por tu contribución, coloque algunas sugerencias.

Ya hice los cambios, gracias por las observaciones!

2022-04-09 23:46 UTC, krol3 approved these changes
LGTM

2022-04-11 16:45 UTC, electrocucaracha requested changes

2022-04-11 16:45 UTC, electrocucaracha commented on content/es/api_gateway.md
> +Un [API Gateway](/application_programming_interface/), pasarela API, es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organiza
```suggestion
Un [API Gateway](/application_programming_interface/) es una herramienta que concentra diferentes aplicaciones APIs, centralizando a todas en un solo lugar. Esto permite a las organizaciones mover funciones clave, como puede ser la autenticación y la autorización o limitando el número de peticiones entre aplicaciones a una ubicación de administración centralizada. Un API Gateway funciona como una interface común para los que la consumen (usualmente aplicaciones externas).
```

2022-04-11 16:45 UTC, electrocucaracha commented on content/es/api_gateway.md
> +Proporcionando un único punto de acceso para varias APIs en una aplicación, los API Gateway hacen simple para la organización aplicar decisiones de negocio transversales o lógicas de seguridad en una
```suggestion
Proporcionando un único punto de acceso para varias APIs en una aplicación, los API Gateway simplifican la organización para aplicar decisiones de negocio transversales o lógicas de seguridad en una ubicación central. Adicionalmente, permiten a los consumidores de aplicaciones ir en una única dirección para todas sus necesidades. Un  API Gateway puede simplificar preocupaciones operativas, como son la seguridad y la [observabilidad](/observability/) proporcionando un único punto de acceso para las peticiones a todos los servicios web en el sistema. Como todas las peticiones fluyen por el gateway, esto presenta un lugar único para agregar funcionalidades como la recolección de métricas, límites de tráfico y la autorización.
```

2022-04-12 16:52 UTC, electrocucaracha commented
@gamba47 podrías agregar las siguientes palabras al [wordlist](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt)?

```txt
API
APIs
Gateway
technology
interface
```

2022-04-18 18:21 UTC, gamba47 commented
> @gamba47 podrías agregar las siguientes palabras al [wordlist](https://github.com/cncf/glossary/blob/dev-es/content/es/.wordlist.txt)?
> 
> ```
> API
> APIs
> Gateway
> technology
> interface
> ```

done!

2022-04-18 18:54 UTC, electrocucaracha approved these changes

2022-04-18 18:54 UTC, merged