[ESP] add content/es/application_programming_interface.md done
cncf/glossary pull request #704
Opened 2022-04-06 14:59 UTC by gamba47

Based on #564 

Work done.

2022-04-06 22:59 UTC, jihoon-seo commented
Preview should be available at https://deploy-preview-704--cncfglossary.netlify.app/es/application_programming_interface/ .

And please refer to https://github.com/cncf/glossary/pull/705#issuecomment-1090893838 . 😊

2022-04-07 07:55 UTC, raelga requested changes
Faltan algunos signos de acentuación y hay algún error tipográfico.

2022-04-07 07:55 UTC, raelga commented on content/es/application_programming_interface.md
> +## ¿Que es?
```suggestion
## ¿Qué es?
```

2022-04-07 07:55 UTC, raelga commented on content/es/application_programming_interface.md
> +## ¿Como Ayuda?
```suggestion
## ¿Cómo Ayuda?
```

2022-04-07 07:55 UTC, raelga commented on content/es/application_programming_interface.md
> +A medida que las aplicaciones se vuelven más complejas, cualquier tipo de cambio en el mismo puede afectar drásticamente otras funcionalidades. Las aplicaciones deben adoptar un enfoque modular para
```suggestion
A medida que las aplicaciones se vuelven más complejas, cualquier tipo de cambio en el mismo puede afectar drásticamente otras funcionalidades. Las aplicaciones deben adoptar un enfoque modular para sus funcionalidades si no pueden crecer y mantener la estabilidad al mismo tiempo. Sin las APIs, falta un marco para la interacción entre las aplicaciones. Sin un marco compartido, es un desafío para las aplicaciones el [escalar](/scalability/) e integrarse.
```

2022-04-07 07:55 UTC, raelga commented on content/es/application_programming_interface.md
> +Las APIs permiten a los programas o aplicaciones interactuar y compartir información en una manera definida y entendible. Estas estan construidas en bloques para aplicaciones modernas y proveen a los
```suggestion
Las APIs permiten a los programas o aplicaciones interactuar y compartir información en una manera definida y entendible. Estas están construidas en bloques para aplicaciones modernas y proveen a los desarrolladores una manera de integrar aplicaciones. Siempre que escuche acerca de [microservicios](/microservices/) trabajando en conjunto, se puede inferir que están interactuando a través de una API.
```

2022-04-21 23:13 UTC, krol3 reviewed
Algunas pequenas sugerencias @gamba47, gracias por tu contribución

2022-04-21 23:13 UTC, krol3 commented on content/es/application_programming_interface.md
> +Una API es una manera en la que los programas de computadoras interactuan entre sí. Tal como los humanos interactúan con un sitio web usando la página del mismo, una API permite a los programas de la
```suggestion
Una API es una manera en la que los programas de computadoras interactúan entre sí. Tal como los humanos interactúan con un sitio web a través de la página web, una API permite a los programas de las computadoras interactuar entre sí. A diferencia de las interacciones humanas, las APIs tienen limitaciones en lo que se le puede preguntar o no a las mismas. La limitación en la interacción ayuda a crear comunicaciones estables y funcionales entre los diferentes programas.
```

2022-04-21 23:13 UTC, krol3 commented on content/es/application_programming_interface.md
> +A medida que las aplicaciones se vuelven más complejas, cualquier tipo de cambio en el mismo puede afectar drásticamente otras funcionalidades. Las aplicaciones deben adoptar un enfoque modular para
```suggestion
A medida que las aplicaciones se vuelven más complejas, cualquier tipo de cambio en el mismo puede afectar drásticamente otras funcionalidades. Las aplicaciones deben adoptar un enfoque modular para sus funcionalidades así pueden crecer y mantener la estabilidad simultáneamente. Sin las APIs, falta un marco para la interacción entre las aplicaciones. Sin un marco compartido, es un desafío para las aplicaciones el [escalar](/scalability/) e integrarse.
```

2022-04-26 08:01 UTC, raelga reviewed
Faltarían `microservicios` en el diccionario, una vez aceptada la sugerencia de @krol3 que corrige algunos errores tipográficos.

2022-04-26 08:01 UTC, raelga commented on content/es/application_programming_interface.md
> +title: Application Programming Interface
```suggestion
title: Interfaz de programación de aplicaciones  (API)
```

Quizás deberíamos traducir el título también? No estoy muy seguro.

2022-04-26 14:28 UTC, gamba47 commented
Me queda hacer los cambios en el diccionario, @electrocucaracha cuando puedas me ayudas? porque tengo el problema que no tengo el diccionario y tampoco el branch dev-es

2022-06-10 07:55 UTC, raelga commented
@gamba47 ya estaría pasando los checks de formato y spellcheck, faltaría añadir en tu commit el `Signed-off-by`. Lo puedes revisar? Si necesitas ayuda, no dudes en ponerte en contacto conmigo por slack.

2022-06-10 07:58 UTC, raelga commented
Con los últimos cambios, ya estaría pasando todos los checks. Puedes revisar que esté todo correcto?

cc @gamba47 @electrocucaracha

2022-06-10 07:58 UTC, raelga approved these changes

2022-06-10 16:22 UTC, electrocucaracha commented on content/es/application-programming-interface.md
> +category: technology
```suggestion
category: Tecnología
```

2022-06-10 16:34 UTC, electrocucaracha commented on content/es/application-programming-interface.md
> +## ¿Cómo Ayuda?
Con la excepción de `api_gateway.md` todas las definiciones usan minúscula para este titulo
```suggestion
## ¿Cómo ayuda?
```

2022-06-13 14:59 UTC, electrocucaracha approved these changes
@gamba47 Parece ser que lo único que necesitas es firmar los commits para que pase el CI, en cuanto a lo demás no hay problema en ser mergeado

2022-06-13 20:31 UTC, gamba47 commented
Hola @electrocucaracha ! leo bien y lo hago, parece que hay que hacer un rebase, vamos a aprender algo nuevo! gracias, mas tarde te cuento!

2022-08-02 15:49 UTC, merged