Add content/pt-br/zero_trust_architecture.md
cncf/glossary pull request #714
Opened 2022-04-09 05:49 UTC by MrErlison

Add
- content/pt-br/zero_trust_architecture.md

2022-04-30 22:36 UTC, edsoncelio requested changes

2022-04-30 22:36 UTC, edsoncelio commented on content/pt-br/zero_trust_architecture.md
> +category: Conceito
Conceito to conceito

2022-05-01 13:22 UTC, edsoncelio approved these changes

2022-06-16 15:02 UTC, brunoguidone approved these changes
LGTM

2022-06-25 14:46 UTC, merged