[bn] Updated content/bn/style-guide/_index.md
cncf/glossary pull request #751
Opened 2022-04-15 22:54 UTC by smrafy20

Signed-off-by: Shadman Rafy  rafyndc18@gmail.com
Updated `content/bn/style-guide/_index.md ` to Bengali
This is an intial PR as may need some improvements!

2022-04-15 23:01 UTC, mitul3737 requested changes
Can you make this changes?

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +- এটা যেসব সমস্যাতে ফোকাস করে: সমস্যাটির উপর ফোকাস করুন, সমাধানের দিকে নয় (যা পরবর্তী বিভাগে আসে)। আসলে, সংজ্ঞায়িত শব্দটি উল্লেখ করা এড়িয়ে চলুন। সমস্যাটি আমাদের সেই জিনিসটির প্রয়োজন কিসের উপর তা
`**এটা যেসব সমস্যাতে ফোকাস করে**`

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +- এটা কিভাবে সাহায্য করে: এখন, মেয়াদে ফিরে আসুন।  এটি কিভাবে উপরে বর্ণিত সমস্যার সমাধান করে?
`**এটা কিভাবে সাহায্য করে**`

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +শব্দকোষের লক্ষ্য জটিল ধারণাগুলিকে সহজ শব্দে ব্যাখ্যা করা — এটি একটি আশ্চর্যজনকভাবে কঠিন কাজ যা সম্ভবত একাধিক সংশোধন করতে পারে। আপনার সংজ্ঞা খসড়া করার সময় সর্বদা দর্শকদের কথা মাথায় রাখুন। শিল্পের শ
`**জটিল ধারণাগুলিকে সহজ শব্দে ব্যাখ্যা করা**`

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +উপযুক্ত হলে, বাস্তব-জগতের উদাহরণ ব্যবহার করুন যা পাঠকদের (বিশেষ করে অ-প্রযুক্তিগত) আরও ভালোভাবে বুঝতে সাহায্য করে কখন এবং কেন আপনি যে ধারণাটি ব্যাখ্যা করছেন তা প্রাসঙ্গিক।
`**বাস্তব-জগতের উদাহরণ**`

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +আপনার সংজ্ঞায় ব্যবহৃত হলে, সর্বদা বিদ্যমান শব্দকোষের শর্তাবলীর সাথে লিঙ্ক করুন (শুধুমাত্র প্রথম উল্লেখ হাইপারলিঙ্ক করা উচিত)।
`**বিদ্যমান শব্দকোষের শর্তাবলীর সাথে লিঙ্ক করুন**`

2022-04-15 23:01 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +উদাহরণ: [পরিষেবা মেশ সংজ্ঞা](https://glossary.cncf.io/service_mesh/) এর “এটি কী” বিভাগটি একবার দেখুন। এটি মাইক্রোসার্ভিস, পরিষেবা, নির্ভরযোগ্যতা এবং পর্যবেক্ষণযোগ্যতার সংজ্ঞাগুলির সাথে লিঙ্ক করে। উপর
`**উদাহরণ**`

2022-04-15 23:03 UTC, mitul3737 requested changes

2022-04-15 23:03 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +Title লেবেল সর্বদা একটি সংজ্ঞা লেআউটের শীর্ষে থাকবে এবং এর মান শিরোনামের ক্ষেত্রে হওয়া উচিত।
`**Title**`

2022-04-15 23:03 UTC, mitul3737 commented on content/bn/style-guide/_index.md
> +শিরোনাম লেবেলের পরে status লেবেল আসবে। স্থিতি লেবেল নির্দেশ করে যে সংজ্ঞাগুলি পুঙ্খানুপুঙ্খভাবে যাচাই করা হয়েছে বা আরও প্রচেষ্টার প্রয়োজন আছে কিনা।
`**status**`

2022-04-15 23:16 UTC, mitul3737 approved these changes
LGTM

2022-04-15 23:16 UTC, Imtiaz1234 approved these changes
LGTM

2022-04-15 23:16 UTC, merged

2022-04-16 00:55 UTC, jihoon-seo commented
Preview: https://deploy-preview-751--cncfglossary.netlify.app/bn/style-guide/

And PTAL at https://github.com/cncf/glossary/pull/750#pullrequestreview-943796044 !