Add content/pt-br/vertical_scaling.md
cncf/glossary pull request #758
Opened 2022-04-16 13:53 UTC by MrErlison

Add 
- content/pt-br/vertical_scaling.md

2022-04-24 18:27 UTC, edsoncelio requested changes
I left just a small request below, thanks!

2022-04-24 18:27 UTC, edsoncelio commented on content/pt-br/vertical_scaling.md
> +category: Conceito
Conceito to conceito

2022-04-24 19:22 UTC, edsoncelio approved these changes

2022-06-16 14:58 UTC, brunoguidone approved these changes
LGTM

2022-06-25 14:46 UTC, merged