This is a DevSecOps file in hindi
cncf/glossary pull request #760
Opened 2022-04-17 06:33 UTC by SahityaGupta25

2022-04-18 08:20 UTC, jihoon-seo reviewed
Previews:
- https://deploy-preview-760--cncfglossary.netlify.app/hi/devsecops/
- https://deploy-preview-760--cncfglossary.netlify.app/hi/microservices/

@SahityaGupta25 PTAL!

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +| [DevOps](https://github.com/cncf/glossary/blob/main/content/hi/devops.md) ( डेवॉप्स) | Completed | अवधारणा  | True           |
Please use https://github.com/cncf/glossary/blob/main/content/hi/_TEMPLATE.md?plain=1 as a markdown template.

```suggestion
---
title: DevOps (डेवॉप्स)
status: Completed
category: अवधारणा
exclude_search: true
---
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +सॉफ्टवेयर विकास जीवनचक्र के हर चरण में [DevOps](https://github.com/cncf/glossary/blob/main/content/hi/devops.md) स्वचालित रूप से सुरक्षा में साथ निभाना है | जिससे Agile और [DevOps](https://github.com
```suggestion
सॉफ्टवेयर विकास जीवनचक्र के हर चरण में [DevOps](/hi/devops/) स्वचालित रूप से सुरक्षा में साथ निभाना है | जिससे Agile और [DevOps](/hi/devops/) की गति से सुरक्षित सॉफ़्टवेयर का विकास संभव हो जाता है।
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +| Title                                    | Status    | Category | Exclude_Search |
Could you rename this file to `content/hi/devsecops.md` (with no uppercase)?

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +   #समाधान
```suggestion
## समाधान
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +#समस्या
```suggestion
## समस्या
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +#यह क्या है
```suggestion
## यह क्या है
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/DevSecOps.md
> +4. अपर्याप्त रूप से प्रबंधित विशेषाधिकार प्राप्त अभिगम नियंत्रण के परिणामस्वरूप हमले के अधिक अवसर मिलते हैं
In [English version](https://glossary.cncf.io/devsecops/), there is no numbered list.

Is it right that you localized from the [English version](https://glossary.cncf.io/devsecops/)?

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +| [Microservices](https://github.com/cncf/glossary/blob/main/content/en/microservices.md) | Completed | Concept  |
```suggestion
---
title: Microservices
status: Completed
category: अवधारणा
exclude_search: true
---
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +```
Please remove this line containing 3 backticks.

```suggestion
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +```
Please remove this line containing 3 backticks.

```suggestion
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +```
Please remove this line containing 3 backticks.

```suggestion
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +```
Please remove this line containing 3 backticks.

```suggestion
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +# यह क्या है
```suggestion
## यह क्या है
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +#समस्या यह संबोधित करता है
```suggestion
## समस्या यह संबोधित करता है
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +# यह कैसे मदद करता है
```suggestion
## यह कैसे मदद करता है
```

2022-04-18 08:20 UTC, jihoon-seo commented on content/hi/microservices.md
> +[Micro Services](https://github.com/cncf/glossary/blob/main/content/en/microservices.md) अखंड अनुप्रयोगों द्वारा उत्पन्न चुनौतियों की प्रतिक्रिया है। आम तौर पर, किसी एप्लिकेशन के विभिन्न हिस्सों को अ
- "Microservices" is a single-word term.
- It seems that the link to the term itself is not necessary.

```suggestion
Microservices अखंड अनुप्रयोगों द्वारा उत्पन्न चुनौतियों की प्रतिक्रिया है। आम तौर पर, किसी एप्लिकेशन के विभिन्न हिस्सों को अलग-अलग स्केल करने की आवश्यकता होगी। एक ऑनलाइन स्टोर, उदाहरण के लिए, चेकआउट की तुलना में अधिक उत्पाद दृश्य होने वाला है। इसका मतलब है कि आपको चेकआउट की तुलना में चल रहे उत्पाद दृश्य कार्यक्षमता की अधिक प्रतियों की आवश्यकता होगी। एक अखंड अनुप्रयोग में, तर्क के उन बिट्स को अलग से तैनात नहीं किया जा सकता है। यदि आप व्यक्तिगत रूप से उत्पाद की कार्यक्षमता को माप नहीं सकते हैं, तो आपको पूरे ऐप को उन सभी घटकों के साथ डुप्लिकेट करना होगा जिनकी आपको आवश्यकता नहीं है - संसाधनों का एक अक्षम उपयोग। मोनोलिथिक एप्लिकेशन भी डेवलपर्स के लिए डिजाइन के नुकसान के आगे झुकना आसान बनाते हैं। चूंकि सभी कोड एक ही स्थान पर हैं, इसलिए उस कोड को कसकर युग्मित करना आसान है और चिंताओं को अलग करने के सिद्धांत को लागू करना कठिन है। मोनोलिथ को अक्सर डेवलपर्स को उत्पादक होने से पहले पूरे कोडबेस को समझने की आवश्यकता होती है।
```

2022-04-21 04:51 UTC, seokho-son commented
Hi @SahityaGupta25 Hindi localization team is using `dev-hi` branch for localization contribution.

@anubha-v-ardhan could you guide @SahityaGupta25 to change the base and target branches to `dev-hi` ? :)
(note that, the contributor needs to change the base branch in Github GUI as well as change base branch in contributor's feature branch)

2022-04-23 09:49 UTC, Shivansh-yadav13 commented
- This PR will also close #728

2022-04-23 12:32 UTC, anubha-v-ardhan commented
> * This PR will also close [[hi] Translate `Microservices` into `Hindi` #728](https://github.com/cncf/glossary/issues/728)

We can accept this PR but please try to do one page per PR in future. It helps your PR to get reviewed and merged faster and us to easily manage the localization effort :)

2022-05-21 17:12 UTC, jayesh-srivastava requested changes

2022-05-21 17:12 UTC, jayesh-srivastava commented on content/hi/DevSecOps.md
> +   #समाधान
Here `समाधान` is wrong. It should be `यह कैसे मदद करता है`

2022-05-21 17:12 UTC, jayesh-srivastava commented on content/hi/DevSecOps.md
> +DevSecOps  के लाभों को ध्यान में रखते हुए, इसे अभी भी व्यापक रूप से लागू नहीं किया जा रहा है। कम से कम, अभी तक। आइए DevSecOps  को अपनाने के लाभों के बारे में गहराई से जानें:
@SahityaGupta25 This whole section doesn't seem like the correct localisation from the English version. Please use https://github.com/cncf/glossary/blob/main/content/en/devsecops.md as reference.

2022-05-21 17:14 UTC, jayesh-srivastava commented
@SahityaGupta25 Please consider using separate PRs for separate pages. It will be easier to review and merge.
PTAL @anubha-v-ardhan

2022-07-13 01:44 UTC, SahityaGupta25 commented
@Garima-Negi Sure but I don't know how to remove can you guide me how to remove pages ??

2022-07-13 16:27 UTC, closed without merging

2022-07-13 16:28 UTC, Garima-Negi commented
Closing this PR it is obsolete and had 2 different terms being localized leading to confusion.
I have synced with @SahityaGupta25  he will be working on microservices in a separate PR