feat(glossary): blue green deployment
cncf/glossary pull request #766
Opened 2022-04-19 16:13 UTC by anyulled

closes #567

2022-04-21 23:23 UTC, krol3 requested changes
@anyulled está muy bueno, mínimos cambios que sugeri.

2022-04-21 23:23 UTC, krol3 commented on content/es/blue_green_deployment.md
> +## Problema que soluciona
"Problema que aborda" , estamos colocando el mismo título, puedes ver este proceso en este PR https://github.com/cncf/glossary/pull/689

2022-04-21 23:23 UTC, krol3 commented on content/es/blue_green_deployment.md
> +## Cómo ayuda
```suggestion
## ¿Cómo ayuda?
```

2022-04-22 10:05 UTC, anyulled commented on content/es/blue_green_deployment.md
> +## Problema que soluciona
gracias, ¿podrías sugerirlo como un cambio para aceptarlo, con en el ejemplo de abajo?

2022-04-22 13:51 UTC, krol3 approved these changes
LGTM

2022-04-22 14:16 UTC, raelga commented on content/es/blue_green_deployment.md
> +
```suggestion
```

2022-04-23 07:08 UTC, raelga approved these changes

2022-04-23 07:09 UTC, raelga commented
Gracias @anyulled !

2022-04-23 07:09 UTC, merged