[de] Add localization cloud native tech
cncf/glossary pull request #776
Opened 2022-04-21 17:25 UTC by ohdle

2022-04-23 08:49 UTC, iamNoah1 requested changes
Danke @ohdle für den Beitrag. Ich habe ein paar Änderungsvorschläge hinterlassen.

2022-04-23 08:49 UTC, iamNoah1 commented on content/de/cloud_native_tech.md
> +Der Cloud Native Stack umfasst viele Technologiekategorien, die eine Vielzahl von Herausforderungen adressieren. Ein Blick auf die [CNCF Cloud Native Landscape](https://landscape.cncf.io/) macht deut
```suggestion
Cloud Native Technologien sind in unterschiedliche Kategorien unterteilt, die jeweils eine Vielzahl von Anwendungsfällen adressieren. Ein Blick auf die [CNCF Cloud Native Landscape](https://landscape.cncf.io/) macht deutlich, wie viele unterschiedliche Bereiche dazu gehören. Allgemein gesprochen adressieren Cloud Native Technologien allerdings immer den folgenden übergeordneten Anwendungsfall: die Nachteile traditioneller IT-Betriebsmodelle zu kompensieren. Zu diesen Nachteilen zählen unter anderem Schwierigkeiten bei der Erstellung von skalierbaren, fehlertoleranten, selbstheilenden Anwendungen, sowie eine ineffiziente Ressourcennutzung.
```

2022-04-23 08:49 UTC, iamNoah1 commented on content/de/cloud_native_tech.md
> +Der Cloud Native Stack umfasst viele Technologiekategorien, die eine Vielzahl von Herausforderungen adressieren. Ein Blick auf die [CNCF Cloud Native Landscape](https://landscape.cncf.io/) macht deut
```suggestion
Cloud Native Technologien sind in unterschiedliche Kategorien unterteilt, die jeweils eine Vielzahl von Anwendungsfällen adressieren. Ein Blick auf die [CNCF Cloud Native Landscape](https://landscape.cncf.io/) macht deutlich, wie viele unterschiedliche Bereiche dazu gehören. Allgemein gesprochen adressieren Cloud Native Technologien allerdings immer den folgenden übergeordneten Anwendungsfall: die Nachteile traditioneller IT-Betriebsmodelle zu kompensieren. Zu diesen Nachteilen zählen unter anderem Schwierigkeiten bei der Erstellung von skalierbaren, fehlertoleranten, selbstheilenden Anwendungen, sowie eine ineffiziente Ressourcennutzung.
```

2022-04-23 08:49 UTC, iamNoah1 commented on content/de/cloud_native_tech.md
> +Während jede Technologie auf ein ganz bestimmtes Problem abzielt, ermöglichen Cloud Native Technologien insgesamt lose gekoppelte Systeme, die belastbar, verwaltbar und beobachtbar sind. In Kombinati
```suggestion
Während jede Technologie auf einen ganz bestimmten Anwendungsfall abzielt, ermöglichen Cloud Native Technologien insgesamt lose gekoppelte Systeme, die belastbar sowie leichter zu verwalten und überwachen sind. In Kombination mit robuster Automatisierung ermöglichen sie es Entwicklern, wichtige Änderungen häufig und vorhersehbar mit minimalem Aufwand vorzunehmen. Cloud Native Technologien erleichtern es, moderne Softwaresysteme zu entwickeln, die den heutigen Anforderungen genügen.
```

2022-04-23 08:49 UTC, iamNoah1 commented on content/de/cloud_native_tech.md
> +Während jede Technologie auf ein ganz bestimmtes Problem abzielt, ermöglichen Cloud Native Technologien insgesamt lose gekoppelte Systeme, die belastbar, verwaltbar und beobachtbar sind. In Kombinati
```suggestion
Während jede Technologie auf einen ganz bestimmten Anwendungsfall abzielt, ermöglichen Cloud Native Technologien insgesamt lose gekoppelte Systeme, die belastbar sowie leichter zu verwalten und überwachen sind. In Kombination mit robuster Automatisierung ermöglichen sie es Entwicklern, wichtige Änderungen häufig und vorhersehbar mit minimalem Aufwand vorzunehmen. Cloud Native Technologien erleichtern es, moderne Softwaresysteme zu entwickeln, die den heutigen Anforderungen genügen.
```

2022-04-23 19:55 UTC, ohdle commented on content/de/cloud_native_tech.md
> +title: Cloud Native Technologie
Stimmt, klingt besser.

2022-04-23 20:02 UTC, ohdle commented
> 



> Danke @ohdle für den Beitrag. Ich habe ein paar Änderungsvorschläge hinterlassen.

Danke ebenfalls für dein Review. Ich weiß nicht wieso alle Änderungsvorschläge zweimal auftauchen, fand sie aber alle gut und habe sie angenommen.

2022-04-25 09:10 UTC, iamNoah1 commented
> > Danke @ohdle für den Beitrag. Ich habe ein paar Änderungsvorschläge hinterlassen.
> 
> Danke ebenfalls für dein Review. Ich weiß nicht wieso alle Änderungsvorschläge zweimal auftauchen, fand sie aber alle gut und habe sie angenommen.

Gute Frage haha, vielleicht sollte ich einen anderen Browser benutzen. Das ist mir schonmal passiert :/

2022-04-25 09:10 UTC, iamNoah1 approved these changes
lgtm

2022-05-02 12:35 UTC, DaveVentura commented on content/de/cloud_native_tech.md
> +Cloud Native Technologien, auch als Cloud Native Stack bezeichnet, sind Technologien, die für die Entwicklung von Cloud Nativen Applikationen verwendet werden. Diese Technologien ermöglichen es Organ
"...public, privaten und hybriden Clouds". Die Adjektive würde ich klein schreiben. Dabei könnte man überlegen, ob man public auch übersetzt also "öffentliche". Kling für mich sonst irgendwie komisch.  Oder "Public-, Privat- und Hybrid-Clouds."

2022-05-02 12:38 UTC, DaveVentura reviewed
Habe einen Kommentar hinterlassen :)

2022-05-02 21:48 UTC, ohdle commented on content/de/cloud_native_tech.md
> +Cloud Native Technologien, auch als Cloud Native Stack bezeichnet, sind Technologien, die für die Entwicklung von Cloud Nativen Applikationen verwendet werden. Diese Technologien ermöglichen es Organ
Danke für dein Kommentar, @DaveVentura !

Vielleicht können wir uns eine weitere Meinung holen bzgl. 'public' vs. 'öffentliche' (und ggf. auch wegen Bindestriche). Ich meine selber 'Public Cloud(s)' öfter als 'öffentliche Cloud(s)'  gehört zu haben, muss aber nicht unbedingt etwas bedeuten.

2022-05-04 12:14 UTC, iamNoah1 commented on content/de/cloud_native_tech.md
> +Cloud Native Technologien, auch als Cloud Native Stack bezeichnet, sind Technologien, die für die Entwicklung von Cloud Nativen Applikationen verwendet werden. Diese Technologien ermöglichen es Organ
@ohdle ich finde "Public-, Privat- und Hybrid-Clouds." gut :)

2022-05-05 12:54 UTC, iamNoah1 approved these changes
lgtm

2022-06-13 12:12 UTC, merged