[Spanish] localize 'Infrastructure as Code (IaC)
cncf/glossary pull request #791
Opened 2022-04-26 11:52 UTC by jthan24

Added content for localize Infrastructure as Code (IaC)

2022-04-26 23:48 UTC, electrocucaracha requested changes
@jthan24 muchas gracias por la traducción, dejo algunas sugerencias para algunos párrafos del mismo.

2022-04-26 23:48 UTC, electrocucaracha commented on content/es/infrastructure_as_code.md
> +Infraestructura como Código es una práctica para almacenar la definición de la infraestructura en uno o varios archivos. Esto reemplaza el modelo tradicional dónde la infraestructura es un servicio a
```suggestion
Infraestructura como código es una práctica para almacenar la definición de la infraestructura en uno o varios archivos. Esto reemplaza el modelo tradicional dónde la infraestructura como servicio es aprovisionado de forma manual, por lo general usando scripts con la consola u otras herramientas de configuración.
```

2022-04-26 23:48 UTC, electrocucaracha commented on content/es/infrastructure_as_code.md
> +Construir [aplicaciones nativas cloud](/cloud_native_apps/) requiere infraestructura de forma inmediata y reproducible. Además requiere de [escalabilidad](/scalability/), bajo demanda y reproducible
```suggestion
Construir aplicaciones de forma nativa para la nube requiere que la infraestructura sea desechable y reproducible. Además requiere [escalar](/scalability/) bajo demanda de forma automática y repetible, potencialmente sin la intervención humana. El aprovisionamiento manual no puede cumplir los requerimientos de respuesta y escalado de las [aplicaciones nativas para la nube](/cloud_native_apps/). Los cambios manuales no son reproducibles, rápidamente se enfrentan a limites de escalabilidad, e introducen errores de configuración.
```

2022-04-26 23:48 UTC, electrocucaracha commented on content/es/infrastructure_as_code.md
> +Representados los recursos del [centro de datos](/data_center/) tales como servidores, balanceadores de carga y sub-redes como código, habilita a los equipos a poseer una única fuente de la verdad de
```suggestion
Representados los recursos del [centro de datos](/data_center/) tales como servidores, balanceadores de carga y sub-redes como código, les permite a los equipos de infraestructura poseer una fuente única de verdad para todas las configuraciones y también les permite administrar sus [centro de datos](/data_center/) en flujos de [CI](/continuous_integration/)/[CD](/continuous_delivery/) implementando un sistema de control de versiones y estrategias de despliegue.
```

2022-04-26 23:56 UTC, jthan24 commented on content/es/infrastructure_as_code.md
> +Infraestructura como Código es una práctica para almacenar la definición de la infraestructura en uno o varios archivos. Esto reemplaza el modelo tradicional dónde la infraestructura es un servicio a
Modified!!

2022-04-26 23:56 UTC, jthan24 commented on content/es/infrastructure_as_code.md
> +Construir [aplicaciones nativas cloud](/cloud_native_apps/) requiere infraestructura de forma inmediata y reproducible. Además requiere de [escalabilidad](/scalability/), bajo demanda y reproducible
Modified!

2022-04-26 23:56 UTC, jthan24 commented on content/es/infrastructure_as_code.md
> +Representados los recursos del [centro de datos](/data_center/) tales como servidores, balanceadores de carga y sub-redes como código, habilita a los equipos a poseer una única fuente de la verdad de
Modified!

2022-04-27 00:01 UTC, electrocucaracha approved these changes
/lgtm

2022-04-27 07:43 UTC, raelga approved these changes
/lgtm
/approve

2022-04-27 07:44 UTC, merged