[ES] add content/es/auto_scaling.md
cncf/glossary pull request #836
Opened 2022-05-05 18:07 UTC by gamba47

Fix pr #705 erros

2022-06-07 15:33 UTC, krol3 commented on content/es/auto_scaling.md
> +El auto escalado es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de auto escalado, los recursos son agregados autom
```suggestion
El autoscaling es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de auto escalado, los recursos son agregados automáticamente cuando se necesitan y pueden escalar para cumplir con la demanda fluctuante de los usuarios. El proceso de auto escalado varía y es configurable para escalar basado en diferentes métricas, como son la memoria o el uso de CPU. Los servicios gestionados en la nube son los que están asociados típicamente con esta funcionalidad de escalado automático pero también hay opciones e implementaciones disponibles para la mayoría de los servicios existentes.
```
No encontre referencias de traduccion para "auto escalado", y si usando escalado automático.

2022-06-07 15:50 UTC, krol3 commented on content/es/auto_scaling.md
> +Aprovechando la nube, [virtualizando](/virtualization) y [contenerizando](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera a
```suggestion
Aprovechando la nube, [virtualizando](/virtualization) y [contenerizando](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera acorde a la demanda de los usuarios. Se pueden monitorear la demanda de las aplicaciones y de manera automática escalar las mismas, proporcionando una experiencia al usuario final óptima. Tomemos el ejemplo del aumento de la audiencia de Netflix todos los viernes por la noche. El escalado automático significa agregar más recursos dinámicamente: por ejemplo, incrementando el número de servidores que permitirán una mayor transmisión de los videos y reduciendo los servidores una vez que el consumo se ha normalizado.
```

2022-06-10 09:30 UTC, raelga requested changes

2022-06-10 09:30 UTC, raelga commented on content/es/auto_scaling.md
> +El autoscaling es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de auto escalado, los recursos son agregados automát
```suggestion

El autoescalado es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de auto escalado, los recursos son agregados automáticamente cuando se necesitan y pueden escalar para cumplir con la demanda fluctuante de los usuarios. El proceso de auto escalado varía y es configurable para escalar basado en diferentes métricas, como son la memoria o el uso de CPU. Los servicios gestionados en la nube son los que están asociados típicamente con esta funcionalidad de escalado automático pero también hay opciones e implementaciones disponibles para la mayoría de los servicios existentes.
```

2022-06-10 09:30 UTC, raelga commented on content/es/auto_scaling.md
> +title: Autoscaling
```suggestion
title: Autoescalado
```

2022-06-10 09:30 UTC, raelga commented on content/es/.wordlist.txt
> +Autoscaling
```suggestion
Autoscaling
autoescalado
```

2022-06-10 09:30 UTC, raelga commented on content/es/auto_scaling.md
> +Previamente, la infraestructura y las aplicaciones eran diseñadas para considerar los picos de uso del sistema. Esta arquitectura implicaba que había más recursos que eran infrautilizados o con cambi
```suggestion

Anteriormente, la infraestructura y las aplicaciones eran diseñadas para considerar los picos de uso del sistema. Esta arquitectura implicaba que había más recursos que eran infrautilizados o con cambios inelásticos frente a la demanda de los usuarios. La inelasticidad en este caso, incrementa el coste y puede suponer una pérdida de negocios debido a problemas de capacidad.
```

2022-06-10 09:30 UTC, raelga commented on content/es/auto_scaling.md
> +Aprovechando la nube, [virtualizando](/virtualization) y [contenerizando](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera a
```suggestion

Aprovechando la nube, la [virtualización](/virtualization) y la [contenerización](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera acorde a la demanda de los usuarios. Se pueden monitorear la demanda de las aplicaciones y de manera automática escalar las mismas, proporcionando una experiencia al usuario final óptima. Tomemos el ejemplo del aumento de la audiencia de Netflix todos los viernes por la noche. El escalado automático significa agregar más recursos dinámicamente: por ejemplo, incrementando el número de servidores que permitirán una mayor transmisión de los videos y reduciendo los servidores una vez que el consumo se ha normalizado.
```

2022-06-10 09:30 UTC, raelga commented on content/es/auto_scaling.md
> +Aprovechando la nube, [virtualizando](/virtualization) y [contenerizando](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera a
En caso de aceptar la sugerencia, habría que añadir `contenerización` al wordlist.

2022-06-13 14:55 UTC, electrocucaracha requested changes
@gamba47 podrías renombrar el archivo `auto_scaling.md` por `auto-scaling.md` (https://github.com/cncf/glossary/pull/922)

2022-06-13 14:55 UTC, electrocucaracha commented on content/es/auto_scaling.md
> +category: property
```suggestion
category: Propiedad
```

2022-06-13 14:55 UTC, electrocucaracha commented on content/es/auto_scaling.md
> +El autoescalado es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de auto escalado, los recursos son agregados automá
```suggestion
El autoescalado es la habilidad de un sistema para [escalar](/scalability) automáticamente, en términos de recursos computacionales. Con un sistema de autoescalado, los recursos son agregados automáticamente cuando se necesitan y pueden escalar para cumplir con la demanda fluctuante de los usuarios. El proceso de autoescalado varía y es configurable para escalar basado en diferentes métricas, como son la memoria o el uso de CPU. Los servicios gestionados en la nube son los que están asociados típicamente con esta funcionalidad de autoescalado pero también hay opciones e implementaciones disponibles para la mayoría de los servicios existentes.
```

2022-06-13 14:55 UTC, electrocucaracha commented on content/es/auto_scaling.md
> +Aprovechando la nube, la [virtualización](/virtualization) y la [contenerización](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de
```suggestion
Aprovechando la nube, la [virtualización](/virtualization) y la [contenerización](/containerization/) aplicaciones y sus dependencias, las organizaciones pueden construir aplicaciones que escalan de manera acorde a la demanda de los usuarios. Se pueden monitorear la demanda de las aplicaciones y de manera automática escalar las mismas, proporcionando una experiencia al usuario final óptima. Tomemos el ejemplo del aumento de la audiencia de Netflix todos los viernes por la noche. El autoescalado significa agregar más recursos dinámicamente: por ejemplo, incrementando el número de servidores que permitirán una mayor transmisión de los videos y reduciendo los servidores una vez que el consumo se ha normalizado.
```

2022-06-13 14:55 UTC, electrocucaracha commented on content/es/auto_scaling.md
> +Anteriormente, la infraestructura y las aplicaciones eran diseñadas para considerar los picos de uso del sistema. Esta arquitectura implicaba que había más recursos que eran infrautilizados o con cam
```suggestion
Anteriormente, la infraestructura y las aplicaciones eran diseñadas para considerar los picos de uso del sistema. Esta arquitectura implicaba que había más recursos que eran desaprovechados o con cambios inelásticos frente a la demanda de los usuarios. La inelasticidad en este caso, incrementa el coste y puede suponer una pérdida de negocios debido a problemas de capacidad.
```

2022-06-13 20:28 UTC, gamba47 commented
Renombrado!

2022-07-29 18:48 UTC, gamba47 commented
Closed. Continues on #1138 

Thanks @ramrodo for your help!

2022-07-29 18:48 UTC, closed without merging