[bn] Localize containerization.md
cncf/glossary pull request #875
Opened 2022-05-09 11:39 UTC by Mouly22

Signed-off-by: Umme Abira Azmary [abiraazmary22@gmail.com](mailto:abiraazmary22@gmail.com)
Localizes content/bn/containerization.md to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/cncf/glossary/issues/410

2022-05-10 03:14 UTC, mitul3737 requested changes

2022-05-10 03:14 UTC, mitul3737 commented on content/bn/containerization.md
> +title: কন্টেইনারাইজেশন
It should be `কন্টেইনারাইজেশন(Containerization)`

2022-05-10 03:14 UTC, mitul3737 commented on content/bn/containerization.md
> +কনটেইনারগুলি প্রচলিত হওয়ার আগে, সংস্থাগুলি যেকোনো  [বেয়ার-মেটাল মেশিন](/bare_metal_machine/) এর একাধিক অ্যাপ্লিকেশন তৈরি করার জন্য ভার্চুয়াল মেশিনের (VM) উপর নির্ভর করত। ভিএমগুলি পাত্রের তুলনায় উ
It seems that the link has been localized `[অপরিবর্তনশীলতা](/ অপরিবর্তনীয়_ইনফ্রাস্ট্রাকচার/)` thus this link is not working

2022-05-10 03:14 UTC, mitul3737 commented on content/bn/containerization.md
> +কনটেইনারগুলি প্রচলিত হওয়ার আগে, সংস্থাগুলি যেকোনো  [বেয়ার-মেটাল মেশিন](/bare_metal_machine/) এর একাধিক অ্যাপ্লিকেশন তৈরি করার জন্য ভার্চুয়াল মেশিনের (VM) উপর নির্ভর করত। ভিএমগুলি পাত্রের তুলনায় উ
Here in this line `ভিএমগুলি পাত্রের তুলনায় উল্লেখযোগ্যভাবে বড়`, you are using `পাত্র`  which means `container`. A reader might be confused between `পাত্র` and `কনটেইনার` which you used in line 13.

2022-05-10 03:14 UTC, mitul3737 commented on content/bn/containerization.md
> +কন্টেইনারাইজেশন প্রক্রিয়ার জন্য একটি নির্ভরযোগ্য একটি ফাইল প্রয়োজন যেখানে তথ্যসমূহ তালিকা আকারে রাখা সম্ভব হয় এবং এক্ষেত্রে ধারক চিত্রগুলি (প্রথাগত ভিএমগুলির তুলনায়) তুলনামূলক হালকা ওজনের হয়। এই
I hope this sentence can be modified `একটি নির্ভরযোগ্য একটি ফাইল প্রয়োজন`

2022-05-10 03:14 UTC, mitul3737 commented on content/bn/containerization.md
> +কন্টেইনারাইজেশন প্রক্রিয়ার জন্য একটি নির্ভরযোগ্য একটি ফাইল প্রয়োজন যেখানে তথ্যসমূহ তালিকা আকারে রাখা সম্ভব হয় এবং এক্ষেত্রে ধারক চিত্রগুলি (প্রথাগত ভিএমগুলির তুলনায়) তুলনামূলক হালকা ওজনের হয়। এই
Kindly replace `ধারক চিত্র` with `কন্টেইনার ইমেজ`

2022-06-03 13:06 UTC, mitul3737 commented
@Mouly22  any update on this?

2022-07-25 19:06 UTC, mitul3737 approved these changes
LGTM

2022-07-25 19:07 UTC, Imtiaz1234 approved these changes
LGTM

2022-07-25 19:07 UTC, merged