Rename markdown filenames
cncf/glossary pull request #922
Opened 2022-06-02 04:46 UTC by jihoon-seo

This PR
- closes #799.
- renames markdown filenames, replacing all the underscores (`_`) with hyphen (`-`).
  - "no capitalization, no spaces, no parentheses, and use hyphens to separate words"

---

[Commits]
- Insert empty lines before and after the header lines (for all languages) (f97e7f5dc92fd19b9800dd4cad6c4975d927542e)
- Add semantic line breaks (for English files only) (896a5bd006462520ae32274ae35e7726619bc6f1)
- Rename markdown filenames (for all languages) (434c4c01fd10547a94552121a673ee13b942445c)
- Update relevant links (for all languages) (0875381f22b9f235e2f5c057cd9e60331b3913bb)

2022-06-02 10:03 UTC, iamNoah1 requested changes
Commits seem not be signed correctly

2022-06-02 13:16 UTC, raelga commented
ack!

2022-06-03 01:04 UTC, jihoon-seo commented
@iamNoah1 As per your comment, I added `Signed-off-by:` string to all 4 commits' messages. 😊

2022-06-03 07:08 UTC, raelga approved these changes

2022-06-03 08:10 UTC, iamNoah1 approved these changes

2022-06-03 08:16 UTC, seokho-son reviewed
Hi @jihoon-seo 

I found two broken links.

2022-06-03 08:16 UTC, seokho-son commented on content/hi/devops.md
> +परंपरागत रूप से, [टाइटली-कपल्ड](/tightly-coupled-architectures/) [मोनोलिथिक ऐप्स](/monolith-apps/) का प्रयोग वाले जटिल संगठनों में, काम आम तौर पर कई समूहों के बीच खंडित होता था। इसमें एप्लीकेशन कई टी
```suggestion
परंपरागत रूप से, [टाइटली-कपल्ड](/tightly-coupled-architectures/) [मोनोलिथिक ऐप्स](/monolithic-apps/) का प्रयोग वाले जटिल संगठनों में, काम आम तौर पर कई समूहों के बीच खंडित होता था। इसमें एप्लीकेशन कई टीमों के बीच जाता था और काफी लम्बा समय लगता था। हर बार जब कोई घटक या अपडेट तैयार होता था, तो उसे अगली टीम के लिए एक कतार में रखा जाता था। क्योंकि प्रत्येक व्यक्ति केवल परियोजना के एक छोटे से हिस्से पर काम करता था, इस दृष्टिकोण के कारण स्वामित्व की कमी होती थी। उनका लक्ष्य काम को अगले समूह तक पहुंचाना था, न कि ग्राहक को सही कार्यक्षमता प्रदान करना - प्राथमिकताओं का एक स्पष्ट गलत संरेखण।
```

2022-06-03 08:16 UTC, seokho-son commented on content/zh-cn/scalability.md
>  可扩展性指的是一个系统能有多大的发展。这就是增加做任何系统应该做的事情的能力。 例如，[Kubernetes](/zh-cn/kubernetes/) [集群](/zh/cluster/) 通过增加或减少 [容器化](/zh-cn/containerization/) 应用程序的数量来进行扩展，但这种可扩展性取决于几个因素。 它有多少[节点](/nodes/)，每个节点可以处理多少个[容器](/
```suggestion
可扩展性指的是一个系统能有多大的发展。这就是增加做任何系统应该做的事情的能力。 例如，[Kubernetes](/zh-cn/kubernetes/) [集群](/zh-cn/cluster/) 通过增加或减少 [容器化](/zh-cn/containerization/) 应用程序的数量来进行扩展，但这种可扩展性取决于几个因素。 它有多少[节点](/nodes/)，每个节点可以处理多少个[容器](/zh-cn/container/)，控制平面可以支持多少条记录和操作？
```

2022-06-03 12:22 UTC, jihoon-seo commented
@seokho-son Fixed! Thank you for your review. 😊

2022-06-03 12:45 UTC, seokho-son commented
Hi, l10n team reviewers !

I hope to expedite this PR. (including lots of changes)

So, I hope to coordinate reviewers for localized contents. (Please review or assign another reviewer from your team)
 - Check (missing, problematic, inaccurate, ..) changed files for your language. 
   - (https://github.com/cncf/glossary/pull/922/files content/ko/* for instance)
 - Check preview for your language. 
   - (https://deploy-preview-922--cncfglossary.netlify.app/ko for Korean for instance)


--- 

- content/bn/* : @mitul3737 
- content/hi/* : @anubha-v-ardhan
- contnet/zh-cn/* : @Jacob953
- contnet/ko/* : @yunkon-kim 
- content/it/* : @sistella 
- content/de/* : seems reviewed already :)
- content/es/* : seems reviewed already :)

---

- content/en/* : @seokho-son @iamNoah1

2022-06-03 12:55 UTC, jihoon-seo reviewed
I will remove the hardcoded domain name (`glossary.cncf.io`)
in `content/ko/virtual-machine.md` too.

```diff
-[가상화(virtualization)](https://glossary.cncf.io/virtualization/)
+[가상화(virtualization)](/virtualization/)

-[베어 메탈(bare metal)](https://glossary.cncf.io/bare_metal_machine/)
+[베어 메탈(bare metal)](/bare-metal-machine/)
```

2022-06-03 13:03 UTC, mitul3737 approved these changes
LGTM FOR Bengali Contents

2022-06-08 18:10 UTC, iamNoah1 approved these changes
Big round of applause @jihoon-seo for this huge edit :). Thank you. English content looks good :) 

lgtm

2022-06-09 13:37 UTC, CathPag commented
Thank you, @jihoon-seo!!!

2022-06-10 04:15 UTC, seokho-son commented
LGTM for Korean contents

2022-06-13 11:55 UTC, Jacob953 approved these changes
LGTM for Chinese content.

2022-06-13 14:34 UTC, seokho-son commented
Hello, reviewers :) 
Most of l10n teams confirmed the changes of this PR. Since this PR touches many files, I hope to avoid conflicts with other coming PRs.

I'v checked (reviewed) files and previews for the l10n files which are not reviewed by l10n team yet. LGTM.

Considering a time limit, let me approve this PR .

Hi @cjyabraham . This PR will make conflicts to your PR #930 . (Both this PR and PR #930 changes overall files)
I'd like to avoid conflicts but there is no way this time. Thank you for the website enhancement !

2022-06-13 14:45 UTC, jihoon-seo commented
@seokho-son Please give me some time to tidy commits and apply [this](https://github.com/cncf/glossary/pull/922#pullrequestreview-994866484),
I will handle these tomorrow soon. :)

2022-06-13 14:45 UTC, iamNoah1 commented
Go for it @seokho-son. Conflicts can not be avoided sometimes, especially with so many changes. The sooner we get this merged, the better. We can fix broken things afterwards :)

2022-06-13 23:02 UTC, jihoon-seo commented
@seokho-son Done! Please take a look. Thank you. 😊

2022-06-14 00:08 UTC, seokho-son approved these changes
Final LGTM !

2022-06-14 00:09 UTC, merged

2022-06-14 15:16 UTC, iamNoah1 commented
Awesome :)