Localize Database as a service
cncf/glossary pull request #934
Opened 2022-06-09 12:27 UTC by sumit-158

This PR localizes file content/hi/database_as_a_service.md in Hindi

solve #894

2022-06-16 18:08 UTC, jayesh-srivastava requested changes

2022-06-16 18:08 UTC, jayesh-srivastava commented on content/hi/database_as_a_service.md
> +डेटाबेस-ए-ए-सर्विस (DBaaS) एक [क्लाउड](/cloud_computing/) ऑपरेटर (सार्वजनिक या निजी) द्वारा प्रबंधित एक सेवा है जो पारंपरिक डेटाबेस प्रशासन कार्यों को करने के लिए एप्लिकेशन टीम की आवश्यकता के बिना अन
It should be 'डेटाबेस-एज़-ए-सर्विस'

2022-06-19 10:27 UTC, sumit-158 commented
@jayesh-srivastava its ready to review

2022-08-05 11:11 UTC, anubha-v-ardhan requested changes

2022-08-05 11:11 UTC, anubha-v-ardhan commented on content/hi/database_as_a_service.md
> +डेटाबेस-एज़-ए-सर्विस (DBaaS) एक [क्लाउड](/cloud_computing/) ऑपरेटर (सार्वजनिक या निजी) द्वारा प्रबंधित एक सेवा है जो पारंपरिक डेटाबेस प्रशासन कार्यों को करने के लिए एप्लिकेशन टीम की आवश्यकता के बिना
```suggestion
डेटाबेस-एज़-ए-सर्विस (DBaaS) एक [क्लाउड](/cloud_computing/) ऑपरेटर (सार्वजनिक या निजी) द्वारा प्रबंधित एक सेवा है जो पारंपरिक डेटाबेस प्रशासन कार्यों को करने के लिए एप्लिकेशन टीम की आवश्यकता के बिना एप्लीकेशनों का समर्थन करती है। DBaaS ऐप डेवलपर्स को डेटाबेस को अपडेट रखने के लिए विशेषज्ञ न होने या डेटाबेस एडमिनिस्ट्रेटर (DBA) को नियुक्त किए बिना डेटाबेस का लाभ उठाने की अनुमति देता है।
```

2022-08-05 11:11 UTC, anubha-v-ardhan commented on content/hi/database_as_a_service.md
> +डीबीएएएस डेवलपर्स को सभी प्रशासन/प्रशासनिक कार्यों को क्लाउड-आधारित सेवा प्रदाता को आउटसोर्स करने की अनुमति देता है। सेवा प्रदाता यह सुनिश्चित करता है कि डेटाबेस सुचारू रूप से चल रहा है, जिसमें कॉन्फ
```suggestion
DBaaS डेवलपर्स के सभी प्रशासन/प्रशासनिक कार्यों को क्लाउड-आधारित सेवा प्रदाता को आउटसोर्स करने की अनुमति देता है। सेवा प्रदाता यह सुनिश्चित करता है कि डेटाबेस सुचारू रूप से चल रहा है, जिसमें कॉन्फ़िगरेशन प्रबंधन, बैकअप, पैच, अपग्रेड, सेवा निगरानी (service monitoring), ​​​​और बहुत कुछ प्रबंधित करने के लिए उपयोगकर्ता के अनुकूल इंटरफेस के साथ शामिल है। DBaaS डेटाबेस लागत को कम करते हुए संगठनों को एंटरप्राइज़-ग्रेड एप्लिकेशन को तेज़ी से विकसित करने में मदद करता है।
```

2022-08-05 11:12 UTC, anubha-v-ardhan requested changes
@sumit-158 Please also change the file name to `database-as-a-service.md`. We prefer keeping the file names same as that of English version.

2022-08-09 12:05 UTC, sumit-158 commented
@anubha-v-ardhan done!

2022-08-10 02:41 UTC, anubha-v-ardhan approved these changes
LGTM!

Please wait for one more approval for this PR to be merged.
Thank you @sumit-158

2022-08-10 06:55 UTC, Garima-Negi approved these changes
LGTM!

2022-08-10 06:56 UTC, Garima-Negi commented
will need @jayesh-srivastava 's approval to proceed with a merge

2022-09-23 20:14 UTC, Garima-Negi commented
@jayesh-srivastava waiting on your approval on this one :)

2022-09-23 20:15 UTC, jayesh-srivastava approved these changes
LGTM! Thanks!

2022-09-23 20:15 UTC, merged