[en] Add term: 'Event-Driven Architecture'
cncf/glossary pull request #976
Opened 2022-06-20 13:00 UTC by jihoon-seo

- This PR supersedes & closes #637.
  - [Removed irrelevant commits.](https://github.com/cncf/glossary/pull/637#issuecomment-1152419574)
  - Squashed 3 commits from @jasonsmithio to one single commit.
  - [Added missing line.](https://github.com/cncf/glossary/pull/637/files#r894446870)
  - [Renamed to `event-driven-architecture.md`.](https://github.com/cncf/glossary/pull/637/files#r894456454)
  - Removed hard-coded domain name. (`https://glossary.cncf.io/service/` → `/service/`)

2022-06-20 20:31 UTC, jihoon-seo commented
@iamNoah1 I appended my signature and force-pushed. PTAL again. 😊

2022-06-21 06:55 UTC, iamNoah1 requested changes

2022-06-21 06:55 UTC, iamNoah1 commented on content/en/event-driven-architecture.md
> +status: Feedback Appreciated
```suggestion
status: Completed
```

2022-06-21 09:55 UTC, jihoon-seo commented on content/en/event-driven-architecture.md
> +status: Feedback Appreciated
Done! 😊

2022-06-23 12:46 UTC, CathPag approved these changes
LGTM

2022-06-23 12:49 UTC, iamNoah1 approved these changes

2022-06-23 12:49 UTC, merged