[es] Localize cloud-native-apps.md
cncf/glossary pull request #983
Opened 2022-06-20 18:33 UTC by ramrodo

This PR localizes `cloud-native-apps.md` file to Spanish

**Notes for reviewers:** The English word `on-premise` is translated in Spanish as `on-premises` according to [this AWS documentation]( https://docs.aws.amazon.com/es_es/codedeploy/latest/userguide/instances-on-premises.html).

fixes https://github.com/cncf/glossary/issues/572

2022-06-29 14:11 UTC, electrocucaracha requested changes

2022-06-29 14:11 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +Cada centro de datos tenía servicios que [acoplaban estrechamente](/es/tightly-coupled-architectures/) aplicaciones a entornos específicos,
```suggestion
Cada centro de datos tenía servicios que [acoplaban estrechamente](/tightly-coupled-architectures/) aplicaciones a entornos específicos,
```

2022-06-29 14:11 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +a menudo dependiendo en gran medida del aprovisionamiento manual de infraestructura, como [máquinas virtuales](/es/virtual_machine/) y servicios.
```suggestion
a menudo dependiendo en gran medida del aprovisionamiento manual de infraestructura, como [máquinas virtuales](/virtual_machine/) y servicios.
```

2022-06-29 14:11 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +ni se pueden reiniciar automáticamente en caso de falla.
```suggestion
ni pueden reiniciar automáticamente en caso de falla.
```

2022-06-29 18:14 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +ni se pueden reiniciar automáticamente en caso de falla.
Es cierto, el renglón anterior refiere a `escalarse` por lo que suena mejor `reiniciarse`

2022-06-29 20:57 UTC, electrocucaracha requested changes
Homologación de término

2022-06-29 20:57 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +Las aplicaciones nativas de la nube están diseñadas específicamente para aprovechar las innovaciones en [computación en la nube](/es/cloud_computing/).
```suggestion
Las aplicaciones nativas para la nube están diseñadas específicamente para aprovechar las innovaciones en [computación en la nube](/es/cloud_computing/).
```

2022-06-29 20:57 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +Estas aplicaciones se integran fácilmente con sus respectivas arquitecturas en la nube, aprovechando los recursos de la nube y las capacidades de [escalado](/scalability/). También se refiere a las a
```suggestion
Estas aplicaciones se integran fácilmente con sus respectivas arquitecturas en la nube, aprovechando los recursos de la nube y las capacidades de [escalado](/scalability/). También se refiere a las aplicaciones que aprovechan las innovaciones en infraestructura impulsadas por la computación en la nube. Las aplicaciones nativas para la nube de hoy en día incluyen aplicaciones que se ejecutan en el centro de datos de un proveedor de la nube y en plataformas nativas de la nube on-premises.
```

2022-06-29 20:57 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +Si bien no existe una ruta única para las aplicaciones nativas en la nube, éstas sí tienen algunos puntos en común.
```suggestion
Si bien no existe una ruta única para las aplicaciones nativas para la nube, éstas sí tienen algunos puntos en común.
```

2022-06-29 20:57 UTC, electrocucaracha commented on content/es/cloud-native-apps.md
> +Las aplicaciones nativas de la nube son resistentes, manejables y cuentan con la ayuda del conjunto de servicios en la nube que las acompañan.
```suggestion
Las aplicaciones nativas para la nube son resistentes, manejables y cuentan con la ayuda del conjunto de servicios en la nube que las acompañan.
```

2022-06-29 23:25 UTC, electrocucaracha commented
> Cierto, me faltaba homologar el término en el resto del documento. Gracias @electrocucaracha. Ya he aplicado las sugerencias :)

Un último favor que a penas me di cuenta, puedes actualizar las referencias de los terminos de [Infrastructure as a code](https://github.com/cncf/glossary/blob/main/content/es/infrastructure_as_code.md) y [Bare Metal Machine](https://github.com/cncf/glossary/blob/dev-es/content/es/bare_metal_machine.md)

2022-06-30 21:39 UTC, ramrodo commented
> Un último favor que a penas me di cuenta, puedes actualizar y homologar las referencias de los términos de [Infrastructure as a code](https://github.com/cncf/glossary/blob/dev-es/content/es/infrastructure_as_code.md) y [Bare Metal Machine](https://github.com/cncf/glossary/blob/dev-es/content/es/bare_metal_machine.md)

Listo @electrocucaracha .
También verifiqué que los links funcionan.

2022-06-30 21:42 UTC, electrocucaracha approved these changes
Muchas gracias @ramrodo buen trabajo

2022-07-01 19:57 UTC, raelga approved these changes
/lgtm
/approve

2022-07-01 19:58 UTC, merged