[DE] Take Over Cloud Native Security localization
cncf/glossary pull request #990
Opened 2022-06-24 11:52 UTC by iamNoah1

2022-06-24 12:10 UTC, jihoon-seo reviewed
@iamNoah1 Please rename this file to `content/de/cloud-native-security.md` as well. 😊

2022-06-24 12:10 UTC, jihoon-seo commented on content/de/cloud_native_security.md
> +Cloud Native Security beschreibt den Ansatz, Konzepte aus dem Bereich Cyber Security in [Cloud Native Anwendungen](/cloud_native_apps/) zu integrieren.
This change will lead to https://glossary.cncf.io/cloud-native-apps/ (an English term). 😊

```suggestion
Cloud Native Security beschreibt den Ansatz, Konzepte aus dem Bereich Cyber Security in [Cloud Native Anwendungen](/cloud-native-apps/) zu integrieren. 
```

2022-06-24 12:10 UTC, jihoon-seo commented on content/de/cloud_native_security.md
> +status: Feedback appreciated
The EN term "Cloud Native Security" is GA, so let's mark this one "Completed". 😊

```suggestion
status: Completed
```

2022-06-26 10:33 UTC, DaveVentura requested changes

2022-06-26 10:33 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +Dabei ist vorgesehen, dass Sicherheitsbetrachtungen Teil des gesamten Software-entwicklungs und -Lebenszyklus ist, von der Entwicklung bis zur Inbetriebnahme und Wartung.
Softwareentwicklung schreibt man meiner Meinung nach zusammen ohne Bindestrich und einen Strich dahinter also: 
Softwareentwicklungs- und Lebenszyklus

2022-06-26 10:33 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +Dabei ist vorgesehen, dass Sicherheitsbetrachtungen Teil des gesamten Software-entwicklungs und -Lebenszyklus ist, von der Entwicklung bis zur Inbetriebnahme und Wartung.
... Lebenszyklus sind

2022-06-26 10:33 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +Cloud Native Anwendungen ändern sich häufig, verwenden eine große Anzahl von Open-Source-Tools und -Bibliotheken,
Bei diesem Aufzählunssatz fehlt ein "und".

2022-06-26 10:33 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +werden in der Regel in einer Infrastruktur betrieben, deren Änderungen sich der Kontrolle von Entwicklern entziehen.
der Satz entspricht auch sinngemäß mMn nicht dem englischen Original:

Dort heißt es eher: 
Cloud Native Anwendungen ändern sich häufig, verwenden eine große Anzahl von Open-Source-Tools und -Bibliotheken, werden oft in einer vom Anbieter kontrollierten Infrastruktur ausgeführt und unterliegen schnellen Infrastrukturänderungen.

2022-06-26 10:33 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +lassen sich nicht mit Cloud Native Anwendungen kombinieren.
auch hier bin ich mir nicht sicher. Im englischen steht "scale" also skalieren statt kombinieren.

Warum lassen sich Code-Reviews nicht mit Cloud Native Anwendungen kombinieren?

2022-07-05 13:54 UTC, iamNoah1 commented on content/de/cloud-native-security.md
> +lassen sich nicht mit Cloud Native Anwendungen kombinieren.
habs angepasst

2022-07-11 16:17 UTC, DavidWagnerDO requested changes

2022-07-11 16:17 UTC, DavidWagnerDO commented on content/de/cloud-native-security.md
> +Eine hohe Frequenz von Änderungen des Codes und eine sehr volatile Infrastruktur sind Bespiele für die Eigenschaften von Cloud Native Umgebungen.
Typo: Beispiele

2022-07-11 16:17 UTC, DavidWagnerDO commented on content/de/cloud-native-security.md
> +Cloud Native Security ist eng mit dem Methodologie des [DevSecOps](/devsecops/) verbunden.
..mit der Methodologie..

2022-07-11 16:21 UTC, DaveVentura requested changes

2022-07-11 16:21 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +Eine hohe Frequenz von Änderungen des Codes und eine sehr volatile Infrastruktur sind Bespiele für die Eigenschaften von Cloud Native Umgebungen.
```suggestion
Eine hohe Frequenz von Änderungen des Codes und eine sehr volatile Infrastruktur sind Beispiele für die Eigenschaften von Cloud Native Umgebungen. 
```

2022-07-11 16:21 UTC, DaveVentura commented on content/de/cloud-native-security.md
> +Cloud Native Security ist eng mit dem Methodologie des [DevSecOps](/devsecops/) verbunden.
```suggestion
Cloud Native Security ist eng mit der Methodologie des [DevSecOps](/devsecops/) verbunden.
```

2022-07-12 12:43 UTC, CathPag approved these changes
LGTM :)

2022-07-12 12:59 UTC, merged